dfsch: dfsch/bignum.h File Reference
dfsch/bignum.h File Reference
#include <dfsch/dfsch.h>
#include <dfsch/strings.h>
#include <stdint.h>
#include <stdlib.h>
Defines
#define DFSCH_BIGNUM_ARG(al, name) DFSCH_GENERIC_ARG(al, name, dfsch_bignum_t*, dfsch_bignum_from_number)
#define DFSCH_BIGNUM_ARG_OPT(al, name, default)
Typedefs
typedef struct dfsch_bignum_t dfsch_bignum_t
Functions
dfsch_bignum_t * dfsch_bignum_abs (dfsch_bignum_t *a)
dfsch_bignum_t * dfsch_bignum_add (dfsch_bignum_t *a, dfsch_bignum_t *b)
int dfsch_bignum_cmp (dfsch_bignum_t *a, dfsch_bignum_t *b)
int dfsch_bignum_cmp_abs (dfsch_bignum_t *a, dfsch_bignum_t *b)
void dfsch_bignum_div (dfsch_bignum_t *a, dfsch_bignum_t *b, dfsch_bignum_t **qp, dfsch_bignum_t **rp)
int dfsch_bignum_equal_p (dfsch_bignum_t *a, dfsch_bignum_t *b)
int dfsch_bignum_even_p (dfsch_bignum_t *a)
dfsch_bignum_t * dfsch_bignum_exp (dfsch_bignum_t *b, dfsch_bignum_t *e, dfsch_bignum_t *m)
dfsch_bignum_t * dfsch_bignum_from_bytes (uint8_t *buf, size_t len)
dfsch_bignum_t * dfsch_bignum_from_number (dfsch_object_t *n)
dfsch_bignum_t * dfsch_bignum_logand (dfsch_bignum_t *a, dfsch_bignum_t *b)
dfsch_bignum_t * dfsch_bignum_logior (dfsch_bignum_t *a, dfsch_bignum_t *b)
dfsch_bignum_t * dfsch_bignum_lognot (dfsch_bignum_t *a)
dfsch_bignum_t * dfsch_bignum_logxor (dfsch_bignum_t *a, dfsch_bignum_t *b)
dfsch_bignum_t * dfsch_bignum_mul (dfsch_bignum_t *a, dfsch_bignum_t *b)
dfsch_bignum_t * dfsch_bignum_neg (dfsch_bignum_t *a)
dfsch_bignum_t * dfsch_bignum_shl (dfsch_bignum_t *b, size_t count)
dfsch_bignum_t * dfsch_bignum_shr (dfsch_bignum_t *b, size_t count)
int dfsch_bignum_sign (dfsch_bignum_t *a)
dfsch_bignum_t * dfsch_bignum_sub (dfsch_bignum_t *a, dfsch_bignum_t *b)
dfsch_strbuf_t * dfsch_bignum_to_bytes (dfsch_bignum_t *b)
double dfsch_bignum_to_double (dfsch_bignum_t *b)
int dfsch_bignum_to_int64 (dfsch_bignum_t *b, int64_t *rp)
dfsch_object_t * dfsch_bignum_to_number (dfsch_bignum_t *b)
char * dfsch_bignum_to_string (dfsch_bignum_t *b, unsigned base)
int dfsch_bignum_to_uint64 (dfsch_bignum_t *b, uint64_t *rp)
dfsch_bignum_t * dfsch_make_bignum_int64 (int64_t n)
dfsch_bignum_t * dfsch_make_bignum_uint64 (uint64_t n)
Define Documentation
#define DFSCH_BIGNUM_ARG (al, name) DFSCH_GENERIC_ARG(al, name, dfsch_bignum_t*, dfsch_bignum_from_number)
Definition at line 40 of file bignum.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_BIGNUM_ARG_OPT (al, name, default)
Value:
DFSCH_GENERIC_ARG_OPT(al, name, default,                              \
                        dfsch_bignum_t*, dfsch_bignum_from_number)
Definition at line 42 of file bignum.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
Typedef Documentation
typedef struct dfsch_bignum_t dfsch_bignum_t
Definition at line 35 of file bignum.h.
Function Documentation
dfsch_bignum_t* dfsch_bignum_abs (dfsch_bignum_t * a)
Definition at line 465 of file bignum.c.
References dfsch_bignum_neg(), and dfsch_bignum_t::negative.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (a->negative){
    return dfsch_bignum_neg(a);
  } else {
    return a;
  }
}
dfsch_bignum_t* dfsch_bignum_add (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 430 of file bignum.c.
References bignum_add_abs(), bignum_sub_abs(), and dfsch_bignum_t::negative.
Referenced by dfsch_number_add().
{
  bignum_t* res;
  if (a->negative == b->negative){
    res = bignum_add_abs(a, b);
    res->negative = a->negative;
  } else if (a->negative){
    res = bignum_sub_abs(b, a);
  } else {
    res = bignum_sub_abs(a, b);
  }
  return res;
}
int dfsch_bignum_cmp (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 259 of file bignum.c.
References dfsch_bignum_t::length, dfsch_bignum_t::negative, and dfsch_bignum_t::words.
Referenced by dfsch_number_cmp().
{
  size_t i;
  if (a->negative && !b->negative){
    return -1;
  }
  if (b->negative && !a->negative){
    return 1;
  }
  if (a->length < b->length){
    return a->negative ? 1 : -1;
  }
  if (a->length > b->length){
    return a->negative ? -1 : 1;
  }
  for (i = a->length; i > 0; i--){
    if (a->words[i-1] != b->words[i-1]){
      if (a->words[i-1] < b->words[i-1]){
        return a->negative ? 1 : -1;
      } else {
        return a->negative ? -1 : 1;
      }
    }
  }
  return 0;
}
int dfsch_bignum_cmp_abs (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 240 of file bignum.c.
References dfsch_bignum_t::length, and dfsch_bignum_t::words.
Referenced by bignum_sub_abs().
{
  size_t i;
  if (a->length < b->length){
    return -1;
  }
  if (a->length > b->length){
    return 1;
  }
  for (i = a->length; i > 0; i--){
    if (a->words[i-1] != b->words[i-1]){
      if (a->words[i-1] < b->words[i-1]){
        return -1;
      } else {
        return 1;
      }
    }
  }
  return 0;
}
void dfsch_bignum_div (dfsch_bignum_t * a, dfsch_bignum_t * b, dfsch_bignum_t ** qp, dfsch_bignum_t ** rp)
Definition at line 711 of file bignum.c.
References bignum_div_big(), bignum_div_digit(), dfsch_error(), dfsch_bignum_t::length, make_bignum(), make_bignum_digit(), dfsch_bignum_t::negative, and dfsch_bignum_t::words.
Referenced by dfsch_bignum_exp(), dfsch_number_div_i(), and dfsch_number_mod().
{
  word_t wr;
  if (b->length == 0){
    dfsch_error("Division by zero", NULL);
  }
  if (a->length < b->length ||
      (a->length == b->length &&
       a->words[a->length - 1] < b->words[b->length - 1])){
    if (qp){
      *qp = make_bignum(0);
    }
    if (rp){
      *rp = a;
    }
    return;
  }
  if (b->length == 1){
    bignum_div_digit(a, b->words[0], qp, &wr);
    if (rp){
      (*rp) = make_bignum_digit(wr);
    }
  } else {
    bignum_div_big(a, b, qp, rp);
  }
  if (rp){
    (*rp)->negative = a->negative;
  }
  if (qp){
    (*qp)->negative = a->negative != b->negative;
  }
}
int dfsch_bignum_equal_p (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 74 of file bignum.c.
References dfsch_bignum_t::length, dfsch_bignum_t::negative, and dfsch_bignum_t::words.
Referenced by dfsch_number_equal_p().
{
  if (a->length != b->length){
    return 0;
  }
  if (a->length != 0 && a->negative != b->negative){
    return 0;
  }
  return memcmp(a->words, b->words, a->length*sizeof(word_t)) == 0;
}
int dfsch_bignum_even_p (dfsch_bignum_t * a)
Definition at line 291 of file bignum.c.
References dfsch_bignum_t::length, and dfsch_bignum_t::words.
Referenced by dfsch_number_even_p(), and dfsch_number_odd_p().
{
  if (a->length == 0){
    return 1;
  }
  return a->words[0] & 0x01 == 0;
}
dfsch_bignum_t* dfsch_bignum_exp (dfsch_bignum_t * b, dfsch_bignum_t * e, dfsch_bignum_t * m)
Definition at line 747 of file bignum.c.
References bignum_get_bit(), bignum_num_bits(), dfsch_bignum_div(), dfsch_bignum_mul(), dfsch_error(), dfsch_bignum_t::length, make_bignum_digit(), and dfsch_bignum_t::negative.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  bignum_t* r;
  size_t i;
  if (m && b->negative){
    dfsch_error("Negative base for modular exponentation", NULL);
  }
  if (m && m->length == 0){
    dfsch_error("Zero modulus", NULL);
  }
  r = make_bignum_digit(1);
  for (i = bignum_num_bits(e); i > 0; i--){
    r = dfsch_bignum_mul(r, r);
    if (bignum_get_bit(e, i-1)){
      r = dfsch_bignum_mul(r, b);
    }
    if (m){
      dfsch_bignum_div(r, m, NULL, &r);
    }
  }
  return r;
}
dfsch_bignum_t* dfsch_bignum_from_bytes (uint8_t * buf, size_t len)
Definition at line 936 of file bignum.c.
References bignum_set_word(), make_bignum(), dfsch_bignum_t::negative, normalize_bignum(), and WORD_BITS.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_random_get_bignum().
{
  bignum_t* b = make_bignum(len * (WORD_BITS / 8 + 1));
  size_t i;
  b->negative = 0;
  for (i = 0; i < len; i++){
    bignum_set_word(b, i << 3, buf[len - i - 1], 0xff);
  }
  normalize_bignum(b);
  return b;
}
dfsch_bignum_t* dfsch_bignum_from_number (dfsch_object_t * n)
Definition at line 229 of file bignum.c.
References DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, dfsch_make_bignum_int64(), and DFSCH_TYPE_OF.
Referenced by dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div_i(), dfsch_number_logand(), dfsch_number_logior(), dfsch_number_lognot(), dfsch_number_logxor(), dfsch_number_mod(), dfsch_number_mul(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return (dfsch_bignum_t*) n;
  }
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return dfsch_make_bignum_int64(DFSCH_FIXNUM_REF(n));
  }
  dfsch_error("Not an integer", n);
}
dfsch_bignum_t* dfsch_bignum_logand (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 836 of file bignum.c.
References logop().
Referenced by dfsch_number_logand().
{
  return logop(a, b, '&');
}
dfsch_bignum_t* dfsch_bignum_logior (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 840 of file bignum.c.
References logop().
Referenced by dfsch_number_logior().
{
  return logop(a, b, '|');
}
dfsch_bignum_t* dfsch_bignum_lognot (dfsch_bignum_t * a)
Definition at line 847 of file bignum.c.
References bignum_add_abs_digit(), bignum_sub_abs_digit(), and dfsch_bignum_t::negative.
Referenced by dfsch_number_lognot(), and logop().
{
  bignum_t* r;
  if (a->negative){
    r = bignum_sub_abs_digit(a, 1);
  } else {
    r = bignum_add_abs_digit(a, 1);
  }
  r->negative = ! a->negative;
  return r;
}
dfsch_bignum_t* dfsch_bignum_logxor (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 844 of file bignum.c.
References logop().
Referenced by dfsch_number_logxor().
{
  return logop(a, b, '^');
}
dfsch_bignum_t* dfsch_bignum_mul (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 477 of file bignum.c.
References dfsch_bignum_t::length, make_bignum(), dfsch_bignum_t::negative, normalize_bignum(), WORD_BITS, WORD_MASK, and dfsch_bignum_t::words.
Referenced by dfsch_bignum_exp(), and dfsch_number_mul().
{
  bignum_t* res;
  size_t i;
  size_t j;
  dword_t cy;
  res = make_bignum(a->length + b->length);
  for (i = 0; i < a->length; i++){
    cy = 0;
    for (j = 0; j < b->length; j++){
      cy = res->words[i+j] + a->words[i] * b->words[j] + cy;
      res->words[i+j] = cy & WORD_MASK;
      cy >>= WORD_BITS;
    }
    res->words[i+j] += cy;
  }
  res->negative = !(a->negative == b->negative);
  normalize_bignum(res);
  return res;
}
dfsch_bignum_t* dfsch_bignum_neg (dfsch_bignum_t * a)
Definition at line 460 of file bignum.c.
References copy_bignum(), and dfsch_bignum_t::negative.
Referenced by dfsch_bignum_abs(), and dfsch_number_neg().
{
  bignum_t* r = copy_bignum(a);
  r->negative = ! a->negative;
  return r;
}
dfsch_bignum_t* dfsch_bignum_shl (dfsch_bignum_t * b, size_t count)
dfsch_bignum_t* dfsch_bignum_shr (dfsch_bignum_t * b, size_t count)
Definition at line 858 of file bignum.c.
References dfsch_bignum_t::length, make_bignum(), dfsch_bignum_t::negative, normalize_bignum(), WORD_BITS, WORD_MASK, and dfsch_bignum_t::words.
{
  bignum_t* r;
  size_t i;
  size_t bs = count % WORD_BITS;
  size_t ws = count / WORD_BITS;
  r = make_bignum(b->length - ws + 1);
  r->negative = b->negative;
  for (i = 0; i < b->length - ws - 1; i++){
    r->words[i] = ((b->words[i + ws] >> bs) |
                   (b->words[i + ws + 1] << (WORD_BITS - bs))) & WORD_MASK;
  }
  r->words[b->length - ws] = (b->words[i + ws] >> bs) & WORD_MASK;
  normalize_bignum(r);
  return r;
}
int dfsch_bignum_sign (dfsch_bignum_t * a)
Definition at line 284 of file bignum.c.
References dfsch_bignum_t::length, and dfsch_bignum_t::negative.
Referenced by dfsch_number_sign().
{
  if (a->length == 0){
    return 0;
  } else {
    return a->negative ? -1 : 1;
  }
}
dfsch_bignum_t* dfsch_bignum_sub (dfsch_bignum_t * a, dfsch_bignum_t * b)
Definition at line 444 of file bignum.c.
References bignum_add_abs(), bignum_sub_abs(), and dfsch_bignum_t::negative.
Referenced by dfsch_number_sub().
{
  bignum_t* res;
  if (a->negative == b->negative){
    res = bignum_sub_abs(a, b);
    if (a->negative){
      res->negative = !res->negative;
    }
  } else {
    res = bignum_add_abs(a, b);
    res->negative = a->negative;
  }
  return res;
}
dfsch_strbuf_t* dfsch_bignum_to_bytes (dfsch_bignum_t * b)
Definition at line 918 of file bignum.c.
References bignum_get_word(), bignum_num_bits(), and dfsch_strbuf_create().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  char* buf;
  size_t len;
  size_t i;
  len = bignum_num_bits(b) / 8 + 1;
  buf = GC_MALLOC_ATOMIC(len);
  for (i = 0; i < bignum_num_bits(b); i+=8){
    buf[len - 1 - (i >> 3)] = bignum_get_word(b, i);
  }
  while (len > 0 && *buf == 0){
    buf++;
    len--;
  }
  return dfsch_strbuf_create(buf, len);
}
double dfsch_bignum_to_double (dfsch_bignum_t * b)
Definition at line 216 of file bignum.c.
References dfsch_bignum_t::length, WORD_BASE, WORD_MASK, and dfsch_bignum_t::words.
Referenced by dfsch_number_to_double().
{
  double r = 0;
  int i;
  for (i = b->length+1; i > 0; i--){
    r *= WORD_BASE;
    r += b->words[i-1] & WORD_MASK;
  }
  return r;
}
int dfsch_bignum_to_int64 (dfsch_bignum_t * b, int64_t * rp)
Definition at line 192 of file bignum.c.
References dfsch_bignum_to_uint64(), and dfsch_bignum_t::negative.
Referenced by dfsch_bignum_to_number(), dfsch_number_to_int64(), and dfsch_number_to_long().
{
  uint64_t t;
  if (!dfsch_bignum_to_uint64(b, &t)){
    return 0;
  }
  if (b->negative){
    if (t > ((uint64_t)INT64_MAX) + 1){
      return 0;
    }
    if (rp){
      *rp = -t;
    }
    return 1;
  } else {
    if (t > INT64_MAX){
      return 0;
    }
    if (rp){
      *rp = t;
    }
    return 1;
  }
}
dfsch_object_t* dfsch_bignum_to_number (dfsch_bignum_t * b)
Definition at line 951 of file bignum.c.
References dfsch_bignum_to_int64(), DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, and DFSCH_MAKE_FIXNUM.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_add(), dfsch_number_div_i(), dfsch_number_logand(), dfsch_number_logior(), dfsch_number_lognot(), dfsch_number_logxor(), dfsch_number_mod(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_sub(), and dfsch_random_get_bignum().
{
  int64_t n;
  if (!dfsch_bignum_to_int64(b, &n)){
    return (dfsch_object_t*)b;
  }
  if (n > DFSCH_FIXNUM_MAX || n < DFSCH_FIXNUM_MIN){
    return (dfsch_object_t*)b;
  }
  return DFSCH_MAKE_FIXNUM(n);
}
char* dfsch_bignum_to_string (dfsch_bignum_t * b, unsigned base)
Definition at line 887 of file bignum.c.
References bignum_div_digit(), dfsch_error(), digits, get_digits(), dfsch_bignum_t::length, and dfsch_bignum_t::negative.
Referenced by bignum_write(), and dfsch_number_to_string().
{
  char* buf;
  bignum_t* r;
  word_t d;
  if (base == 0 || base > 36){
    dfsch_error("Invalid base", NULL);
  }
  if (b->length == 0){
    return "0";
  }
  buf = GC_MALLOC_ATOMIC(b->length * get_digits(base) + 2);
  buf += b->length * get_digits(base) + 1;
  *(buf--) = 0;
  r = b;
  while (r->length > 0){
    bignum_div_digit(r, base, &r, &d);
    *(buf--) = digits[d];
  }
  if (b->negative){
    *buf = '-';
    return buf;
  } else {
    return buf+1;
  }
}
int dfsch_bignum_to_uint64 (dfsch_bignum_t * b, uint64_t * rp)
Definition at line 161 of file bignum.c.
References dfsch_bignum_t::length, UINT64_DIGITS, WORD_BITS, word_mag(), WORD_MASK, and dfsch_bignum_t::words.
Referenced by dfsch_bignum_to_int64().
{
  uint64_t r = 0;
  int i;
  if (b->length == 0){
    return 1;
    if (rp){
      *rp = 0;
    }
  }
  if ((b->length-1)*WORD_BITS + word_mag(b->words[b->length - 1]) > 64 ){
    return 0;
  }
  if (rp){
    if (UINT64_DIGITS > b->length + 1){
      i = b->length + 1;
    } else {
      i = UINT64_DIGITS;
    }
    for (; i > 0; i--){
      r <<= WORD_BITS;
      r |= b->words[i-1] & WORD_MASK;
    }
    *rp = r;
  }
  return 1;
}
dfsch_bignum_t* dfsch_make_bignum_int64 (int64_t n)
Definition at line 140 of file bignum.c.
References dfsch_make_bignum_uint64(), and dfsch_bignum_t::negative.
Referenced by dfsch_bignum_from_number(), dfsch_make_number_from_int64(), and dfsch_make_number_from_long().
{
  bignum_t* b;
  if (n < 0){
    b = dfsch_make_bignum_uint64(-n);
    b->negative = 1;
  } else {
    b = dfsch_make_bignum_uint64(n);
    b->negative = 0;
  }
  return b;
}
dfsch_bignum_t* dfsch_make_bignum_uint64 (uint64_t n)
Definition at line 126 of file bignum.c.
References make_bignum(), normalize_bignum(), UINT64_DIGITS, WORD_BITS, WORD_MASK, and dfsch_bignum_t::words.
Referenced by dfsch_make_bignum_int64().
{
  int i;
  bignum_t* b = make_bignum(UINT64_DIGITS);
  for (i=0; i < UINT64_DIGITS; i++){
    b->words[i] = n & WORD_MASK;
    n >>= WORD_BITS;
  }
  normalize_bignum(b);
  return b;
}