dfsch: lib/cdebug.c File Reference
lib/cdebug.c File Reference
#include "dfsch/lib/cdebug.h"
#include <dfsch/dfsch.h>
#include <dfsch/conditions.h>
#include <dfsch/introspect.h>
#include <stdio.h>
#include <dfsch/lib/console.h>
Functions
static dfsch_object_t * debug_invoke_restart (dfsch_object_t *list, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static void debug_main (dfsch_object_t *reason)
void dfsch_cdebug_enter_debugger (dfsch_object_t *reason)
dfsch_object_t * dfsch_cdebug_get_procedure ()
void dfsch_cdebug_set_as_debugger ()
DFSCH_DEFINE_PRIMITIVE (enter_debugger, 0)
static void prettyprint_condition_fields (dfsch_object_t *fields)
Variables
static dfsch_object_t * debugger_env = NULL
Function Documentation
static dfsch_object_t* debug_invoke_restart (dfsch_object_t * list, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 31 of file cdebug.c.
References dfsch_invoke_restart(), dfsch_list_item(), and DFSCH_LONG_ARG.
Referenced by debug_main().
{
  int index;
  DFSCH_LONG_ARG(args, index);
  dfsch_invoke_restart(dfsch_list_item(list, index), args);
  return NULL;
}
static void debug_main (dfsch_object_t * reason) [static]
Definition at line 62 of file cdebug.c.
References debug_invoke_restart(), dfsch_compute_restarts(), dfsch_condition_field_cstr(), dfsch_condition_fields(), DFSCH_CONDITION_TYPE, dfsch_console_run_repl(), dfsch_define_cstr(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_format_trace(), dfsch_get_debugger_depth(), dfsch_get_trace(), DFSCH_INSTANCE_P, dfsch_introspect_register(), dfsch_make_context(), dfsch_make_primitive(), dfsch_new_frame(), dfsch_object_2_string(), DFSCH_PAIR_P, dfsch_restart_description(), dfsch_restart_name(), dfsch_saprintf(), DFSCH_TYPE_OF, and prettyprint_condition_fields().
Referenced by dfsch_cdebug_enter_debugger().
{
  dfsch_object_t* restarts = dfsch_compute_restarts();
  dfsch_object_t* env;
  dfsch_object_t* ustack = dfsch_get_trace();
  char buf[512];
  int i;
  if (!debugger_env){
    debugger_env = dfsch_make_context();
  }
  env = dfsch_new_frame(debugger_env);
  dfsch_define_cstr(env, "reason", reason);
  dfsch_define_cstr(env, "stack-trace", ustack);
  if (DFSCH_INSTANCE_P(reason, DFSCH_CONDITION_TYPE)){
    fprintf(stderr, "debugger invoked on %s:\n",
            DFSCH_TYPE_OF(reason)->name);
    fprintf(stderr,"  %s\n",
            dfsch_object_2_string(dfsch_condition_field_cstr(reason,
                                                       "message"),
                            10, 0));
    prettyprint_condition_fields(dfsch_condition_fields(reason));
  } else {
    fprintf(stderr,"debugger invoked on:\n  %s\n",
            dfsch_object_2_string(reason, 10, 1));
  }
  fprintf(stderr, "\ntrace buffer:\n%s\n", dfsch_format_trace(ustack));
  dfsch_define_cstr(env, "restarts", restarts);
  dfsch_define_cstr(env, "r", dfsch_make_primitive(debug_invoke_restart,
                                                   restarts));
  fprintf(stderr, "restarts:\n");
  i = 0;
  while (DFSCH_PAIR_P(restarts)){
    dfsch_object_t* restart = DFSCH_FAST_CAR(restarts);
    fprintf(stderr, "  (r %d): [%s] %s\n",
            i,
            dfsch_object_2_string(dfsch_restart_name(restart), 1, 1),
            dfsch_restart_description(restart));
    i++;
    restarts = DFSCH_FAST_CDR(restarts);
  }
  dfsch_introspect_register(env);
  dfsch_console_run_repl(dfsch_saprintf("dbg%d> ",
                                        dfsch_get_debugger_depth()),
                         env);
}
void dfsch_cdebug_enter_debugger (dfsch_object_t * reason)
Definition at line 115 of file cdebug.c.
References debug_main().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  debug_main(reason);
}
dfsch_object_t* dfsch_cdebug_get_procedure ()
Definition at line 129 of file cdebug.c.
References DFSCH_PRIMITIVE_REF.
Referenced by dfsch_cdebug_set_as_debugger(), and dfsch_module_cdebug_register().
{
  return DFSCH_PRIMITIVE_REF(enter_debugger);
}
void dfsch_cdebug_set_as_debugger ()
Definition at line 132 of file cdebug.c.
References dfsch_cdebug_get_procedure(), and dfsch_set_debugger().
Referenced by main().
{
  dfsch_set_debugger(dfsch_cdebug_get_procedure());
}
DFSCH_DEFINE_PRIMITIVE (enter_debugger , 0)
Definition at line 119 of file cdebug.c.
References DFSCH_ARG_END, dfsch_cdebug_enter_debugger(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* condition;
  DFSCH_OBJECT_ARG(args, condition);
  DFSCH_ARG_END(args);
  dfsch_cdebug_enter_debugger(condition);
  return NULL;
}
static void prettyprint_condition_fields (dfsch_object_t * fields) [static]
Definition at line 41 of file cdebug.c.
References dfsch_compare_symbol(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_object_2_string(), DFSCH_PAIR_P, DFSCH_SYMBOL_TYPE, and DFSCH_TYPE_OF.
Referenced by debug_main().
{
  dfsch_object_t* i = fields;
  dfsch_object_t* j;
  while (DFSCH_PAIR_P(i)){
    j = DFSCH_FAST_CAR(i);
    i = DFSCH_FAST_CDR(i);
    if (!DFSCH_PAIR_P(j)){
      return;
    }
    if (DFSCH_TYPE_OF(DFSCH_FAST_CAR(j)) == DFSCH_SYMBOL_TYPE &&
        (dfsch_compare_symbol(DFSCH_FAST_CAR(j), "stack-trace") ||
         dfsch_compare_symbol(DFSCH_FAST_CAR(j), "message"))){
      continue;
    }
    fprintf(stderr, "    %s: %s\n" ,
            dfsch_object_2_string(DFSCH_FAST_CAR(j), 10, 1),
            dfsch_object_2_string(DFSCH_FAST_CDR(j), 10, 1));
  }
}
Variable Documentation
dfsch_object_t* debugger_env = NULL [static]
Definition at line 29 of file cdebug.c.