dfsch: dfsch/lib/cdebug.h File Reference
dfsch/lib/cdebug.h File Reference
#include <dfsch/dfsch.h>
Functions
void dfsch_cdebug_enter_debugger (dfsch_object_t *reason)
dfsch_object_t * dfsch_cdebug_get_procedure ()
void dfsch_cdebug_set_as_debugger ()
Function Documentation
void dfsch_cdebug_enter_debugger (dfsch_object_t * reason)
Definition at line 115 of file cdebug.c.
References debug_main().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  debug_main(reason);
}
dfsch_object_t* dfsch_cdebug_get_procedure ()
Definition at line 129 of file cdebug.c.
References DFSCH_PRIMITIVE_REF.
Referenced by dfsch_cdebug_set_as_debugger(), and dfsch_module_cdebug_register().
{
  return DFSCH_PRIMITIVE_REF(enter_debugger);
}
void dfsch_cdebug_set_as_debugger ()
Definition at line 132 of file cdebug.c.
References dfsch_cdebug_get_procedure(), and dfsch_set_debugger().
Referenced by main().
{
  dfsch_set_debugger(dfsch_cdebug_get_procedure());
}