dfsch: dfsch/lib/cmdopts.h File Reference
dfsch/lib/cmdopts.h File Reference
#include <dfsch/dfsch.h>
Defines
#define DFSCH_CMDOPTS_ARGUMENT_MULTIPLE 2
#define DFSCH_CMDOPTS_ARGUMENT_REQUIRED 1
#define DFSCH_CMDOPTS_ERROR_TYPE (&dfsch_cmdopts_error_type)
#define DFSCH_CMDOPTS_PARSER_TYPE (&dfsch_cmdopts_parser_type)
#define DFSCH_CMDOPTS_STRICT_ORDER 1
Typedefs
typedef void(* dfsch_cmdopts_callback_t)(dfsch_cmdopts_t *parser, void *baton, char *value)
typedef char *(* dfsch_cmdopts_source_t)(void *baton)
typedef struct dfsch_cmdopts_t dfsch_cmdopts_t
Functions
void dfsch_cmdopts_add_argument (dfsch_cmdopts_t *parser, int flags, dfsch_cmdopts_callback_t callback, void *baton)
void dfsch_cmdopts_add_option (dfsch_cmdopts_t *parser, int has_arg, char short_opt, char *long_opt, dfsch_cmdopts_callback_t callback, void *baton)
dfsch_object_t * dfsch_cmdopts_argv_to_list (int argc, char **argv)
dfsch_cmdopts_t * dfsch_cmdopts_make_parser (int flags)
void dfsch_cmdopts_parse (dfsch_cmdopts_t *parser, dfsch_cmdopts_source_t source, void *baton)
void dfsch_cmdopts_parse_argv (dfsch_cmdopts_t *parser, char **argv, int argc)
void dfsch_cmdopts_parse_list (dfsch_cmdopts_t *parser, dfsch_object_t *list)
Variables
dfsch_type_t dfsch_cmdopts_error_type
dfsch_type_t dfsch_cmdopts_parser_type
Define Documentation
#define DFSCH_CMDOPTS_ARGUMENT_MULTIPLE 2
Definition at line 49 of file cmdopts.h.
Referenced by dfsch_cmdopts_parse(), and DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_CMDOPTS_ARGUMENT_REQUIRED 1
Definition at line 48 of file cmdopts.h.
Referenced by dfsch_cmdopts_parse(), and DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_CMDOPTS_ERROR_TYPE (&dfsch_cmdopts_error_type)
Definition at line 34 of file cmdopts.h.
Referenced by dfsch_cmdopts_parse(), dfsch_module_cmdopts_register(), find_long_opt(), find_short_opt(), and get_argument().
#define DFSCH_CMDOPTS_PARSER_TYPE (&dfsch_cmdopts_parser_type)
Definition at line 36 of file cmdopts.h.
Referenced by dfsch_cmdopts_make_parser(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_module_cmdopts_register().
#define DFSCH_CMDOPTS_STRICT_ORDER 1
Definition at line 38 of file cmdopts.h.
Referenced by dfsch_cmdopts_parse(), and DFSCH_DEFINE_PRIMITIVE().
Typedef Documentation
typedef void(* dfsch_cmdopts_callback_t)(dfsch_cmdopts_t *parser, void *baton, char *value)
Definition at line 29 of file cmdopts.h.
typedef char*(* dfsch_cmdopts_source_t)(void *baton)
Definition at line 56 of file cmdopts.h.
typedef struct dfsch_cmdopts_t dfsch_cmdopts_t
Definition at line 27 of file cmdopts.h.
Function Documentation
void dfsch_cmdopts_add_argument (dfsch_cmdopts_t * parser, int flags, dfsch_cmdopts_callback_t callback, void * baton)
Definition at line 89 of file cmdopts.c.
References dfsch_cmdopts_t::arguments, argument_t::baton, argument_t::callback, argument_t::flags, and argument_t::next.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  argument_t* a = GC_NEW(argument_t);
  argument_t* i = parser->arguments;
  a->flags = flags;
  a->callback = callback;
  a->baton = baton;
  a->next = NULL;
  if (!i){
    parser->arguments = a;
  } else {
    while (i->next){
      i = i->next;
    }
    i->next = a;
  }
}
void dfsch_cmdopts_add_option (dfsch_cmdopts_t * parser, int has_arg, char short_opt, char * long_opt, dfsch_cmdopts_callback_t callback, void * baton)
Definition at line 72 of file cmdopts.c.
References option_t::baton, option_t::callback, dfsch_stracpy(), option_t::has_arg, option_t::long_opt, option_t::next, dfsch_cmdopts_t::options, and option_t::short_opt.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  option_t* o = GC_NEW(option_t);
  o->has_arg = has_arg;
  o->short_opt = short_opt;
  o->long_opt = dfsch_stracpy(long_opt);
  o->callback = callback;
  o->baton = baton;
  o->next = parser->options;
  parser->options = o;
}
dfsch_object_t* dfsch_cmdopts_argv_to_list (int argc, char ** argv)
Definition at line 284 of file cmdopts.c.
References dfsch_cons(), DFSCH_FAST_CDR_MUT, and dfsch_make_string_cstr().
Referenced by main().
{
  dfsch_object_t* head;
  dfsch_object_t* tail;
  dfsch_object_t* tmp;
  if (argc == 0){
    return NULL;
  }
  head = tail = dfsch_cons(dfsch_make_string_cstr(*argv), NULL);
  argc--;
  argv++;
  while (argc){
    tmp = dfsch_cons(dfsch_make_string_cstr(*argv), NULL);
    DFSCH_FAST_CDR_MUT(tail) = tmp;
    tail = tmp;
    argc--;
    argv++;
  }
  return head;
}
dfsch_cmdopts_t* dfsch_cmdopts_make_parser (int flags)
Definition at line 63 of file cmdopts.c.
References dfsch_cmdopts_t::arguments, DFSCH_CMDOPTS_PARSER_TYPE, dfsch_make_object(), dfsch_cmdopts_t::flags, and dfsch_cmdopts_t::options.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_cmdopts_t* p = dfsch_make_object(DFSCH_CMDOPTS_PARSER_TYPE);
  p->arguments = NULL;
  p->options = NULL;
  p->flags = flags;
  return p;
}
void dfsch_cmdopts_parse (dfsch_cmdopts_t * parser, dfsch_cmdopts_source_t source, void * baton)
Definition at line 186 of file cmdopts.c.
References dfsch_cmdopts_t::arguments, argument_t::baton, option_t::baton, argument_t::callback, option_t::callback, DFSCH_CMDOPTS_ARGUMENT_MULTIPLE, DFSCH_CMDOPTS_ARGUMENT_REQUIRED, DFSCH_CMDOPTS_ERROR_TYPE, DFSCH_CMDOPTS_STRICT_ORDER, dfsch_signal_condition(), find_long_opt(), dfsch_cmdopts_t::flags, argument_t::flags, get_argument(), option_t::has_arg, argument_t::next, and parse_short_opts().
Referenced by dfsch_cmdopts_parse_argv(), and dfsch_cmdopts_parse_list().
{
  char* argument;
  argument_t* next_arg = parser->arguments;
  option_t* opt;
  while ((argument = source(baton)) != NULL){
    if (argument[0] == '-'){
      if (argument[1] == '-'){
        if (argument[2] == 0){
          goto arg_only;
        }
        opt = find_long_opt(parser, argument + 2);
        if (opt->has_arg){
          opt->callback(parser, opt->baton, get_argument(source, baton));
        } else {
          opt->callback(parser, opt->baton, NULL);
        }
      } else {
        parse_short_opts(parser, argument + 1, source, baton);
      }
    } else {
      if (!next_arg){
        dfsch_signal_condition(DFSCH_CMDOPTS_ERROR_TYPE,
                               "Unexpected argument",
                               NULL);
      }
      next_arg->callback(parser,  next_arg->baton, argument);
      if (!(next_arg->flags & DFSCH_CMDOPTS_ARGUMENT_MULTIPLE)){
        next_arg = next_arg->next;
      }
      if (parser->flags & DFSCH_CMDOPTS_STRICT_ORDER){
        goto arg_only;
      }
    }
  }
  return;
 arg_only:
  while ((argument = source(baton)) != NULL){
    if (!next_arg){
      dfsch_signal_condition(DFSCH_CMDOPTS_ERROR_TYPE,
                             "Unexpected argument",
                             NULL);
    }
    next_arg->callback(parser,  next_arg->baton, argument);
    if (!(next_arg->flags & DFSCH_CMDOPTS_ARGUMENT_MULTIPLE)){
      next_arg = next_arg->next;
    }
  }
  if (next_arg && next_arg->flags & DFSCH_CMDOPTS_ARGUMENT_REQUIRED){
    dfsch_signal_condition(DFSCH_CMDOPTS_ERROR_TYPE,
                           "Required argument missing",
                           NULL);
  }
}
void dfsch_cmdopts_parse_argv (dfsch_cmdopts_t * parser, char ** argv, int argc)
Definition at line 261 of file cmdopts.c.
References argv_source_t::argc, argv_source_t::argv, argv_source(), and dfsch_cmdopts_parse().
{
  argv_source_t as;
  as.argv = argv;
  as.argc = argc;
  dfsch_cmdopts_parse(parser, argv_source, &as);
}
void dfsch_cmdopts_parse_list (dfsch_cmdopts_t * parser, dfsch_object_t * list)
Definition at line 277 of file cmdopts.c.
References dfsch_cmdopts_parse(), and list_source().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i = list;
  dfsch_cmdopts_parse(parser, list_source, &i);
}
Variable Documentation
dfsch_type_t dfsch_cmdopts_error_type
Definition at line 53 of file cmdopts.c.
dfsch_type_t dfsch_cmdopts_parser_type
Definition at line 56 of file cmdopts.c.