dfsch: lib/cmdopts_mod.c File Reference
lib/cmdopts_mod.c File Reference
#include "dfsch/lib/cmdopts.h"
Functions
DFSCH_DEFINE_PRIMITIVE (parse_list,"Parse command line from list")
DFSCH_DEFINE_PRIMITIVE (add_argument,"Define new command line argument")
DFSCH_DEFINE_PRIMITIVE (add_option,"Define new command line option")
DFSCH_DEFINE_PRIMITIVE (make_parser,"Create new command line parser")
dfsch_object_t * dfsch_module_cmdopts_register (dfsch_object_t *env)
static void lisp_callback (dfsch_cmdopts_t *parser, dfsch_object_t *function, char *value)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (parse_list , "Parse command line from list")
Definition at line 79 of file cmdopts_mod.c.
References DFSCH_ARG_END, DFSCH_ASSERT_TYPE, dfsch_cmdopts_parse_list(), DFSCH_CMDOPTS_PARSER_TYPE, DFSCH_OBJECT_ARG, and parser.
{
  dfsch_object_t* parser;
  dfsch_object_t* list;
  DFSCH_OBJECT_ARG(args, parser);
  DFSCH_OBJECT_ARG(args, list);
  DFSCH_ARG_END(args);
  dfsch_cmdopts_parse_list(DFSCH_ASSERT_TYPE(parser,
                                             DFSCH_CMDOPTS_PARSER_TYPE),
                           list);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (add_argument , "Define new command line argument")
Definition at line 60 of file cmdopts_mod.c.
References DFSCH_ASSERT_TYPE, dfsch_cmdopts_add_argument(), DFSCH_CMDOPTS_ARGUMENT_MULTIPLE, DFSCH_CMDOPTS_ARGUMENT_REQUIRED, DFSCH_CMDOPTS_PARSER_TYPE, DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_SET, DFSCH_OBJECT_ARG, lisp_callback(), and parser.
{
  dfsch_object_t* parser;
  dfsch_object_t* function;
  int flags = 0;
  DFSCH_OBJECT_ARG(args, parser);
  DFSCH_OBJECT_ARG(args, function);
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_SET("required", DFSCH_CMDOPTS_ARGUMENT_REQUIRED, flags);
  DFSCH_FLAG_SET("multiple", DFSCH_CMDOPTS_ARGUMENT_MULTIPLE, flags);
  DFSCH_FLAG_PARSER_END(args);
  dfsch_cmdopts_add_argument(DFSCH_ASSERT_TYPE(parser,
                                               DFSCH_CMDOPTS_PARSER_TYPE),
                             flags,
                             lisp_callback, function);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (add_option , "Define new command line option")
Definition at line 39 of file cmdopts_mod.c.
References DFSCH_ARG_END, DFSCH_ASSERT_TYPE, dfsch_cmdopts_add_option(), DFSCH_CMDOPTS_PARSER_TYPE, DFSCH_LONG_ARG_OPT, DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, DFSCH_STRING_ARG, DFSCH_TRUE_P, lisp_callback(), and parser.
{
  dfsch_object_t* parser;
  int has_arg;
  char short_opt;
  char* long_opt;
  dfsch_object_t* function;
  DFSCH_OBJECT_ARG(args, parser);
  DFSCH_STRING_ARG(args, long_opt);
  DFSCH_OBJECT_ARG(args, function);
  DFSCH_LONG_ARG_OPT(args, short_opt, 0);
  DFSCH_OBJECT_ARG_OPT(args, has_arg, 0);
  DFSCH_ARG_END(args);
  dfsch_cmdopts_add_option(DFSCH_ASSERT_TYPE(parser,
                                             DFSCH_CMDOPTS_PARSER_TYPE),
                           DFSCH_TRUE_P(has_arg), short_opt, long_opt,
                           lisp_callback, function);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (make_parser , "Create new command line parser")
Definition at line 24 of file cmdopts_mod.c.
References dfsch_cmdopts_make_parser(), DFSCH_CMDOPTS_STRICT_ORDER, DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, and DFSCH_FLAG_SET.
{
  int flags = 0;
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_SET("strict-order", DFSCH_CMDOPTS_STRICT_ORDER, flags);
  DFSCH_FLAG_PARSER_END(args);
  return dfsch_cmdopts_make_parser(flags);
}
dfsch_object_t* dfsch_module_cmdopts_register (dfsch_object_t * env)
Definition at line 93 of file cmdopts_mod.c.
References DFSCH_CMDOPTS_ERROR_TYPE, DFSCH_CMDOPTS_PARSER_TYPE, dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "cmdopts");
  dfsch_define_cstr(env, "cmdopts:<parser>", DFSCH_CMDOPTS_PARSER_TYPE);
  dfsch_define_cstr(env, "cmdopts:<error>", DFSCH_CMDOPTS_ERROR_TYPE);
  dfsch_define_cstr(env, "cmdopts:make-parser",
                    DFSCH_PRIMITIVE_REF(make_parser));
  dfsch_define_cstr(env, "cmdopts:add-option",
                    DFSCH_PRIMITIVE_REF(add_option));
  dfsch_define_cstr(env, "cmdopts:add-argument",
                    DFSCH_PRIMITIVE_REF(add_argument));
  dfsch_define_cstr(env, "cmdopts:parse-list",
                    DFSCH_PRIMITIVE_REF(parse_list));
}
static void lisp_callback (dfsch_cmdopts_t * parser, dfsch_object_t * function, char * value) [static]
Definition at line 33 of file cmdopts_mod.c.
References dfsch_apply(), dfsch_list(), and dfsch_make_string_cstr().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_apply(function, dfsch_list(2, parser, dfsch_make_string_cstr(value)));
}