dfsch: lib/collections_mod.c File Reference
lib/collections_mod.c File Reference
#include <dfsch/lib/collections.h>
Functions
DFSCH_DEFINE_PRIMITIVE (priority_queue_push, 0)
DFSCH_DEFINE_PRIMITIVE (priority_queue_pop, 0)
DFSCH_DEFINE_PRIMITIVE (priority_queue_empty_p, 0)
DFSCH_DEFINE_PRIMITIVE (make_priority_queue, 0)
void dfsch_module_collections_register (dfsch_object_t *env)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (priority_queue_push , 0)
Definition at line 21 of file collections_mod.c.
References DFSCH_ARG_END, dfsch_collections_priority_queue_push(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* queue;
  dfsch_object_t* object;
  DFSCH_OBJECT_ARG(args, queue);
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_ARG_END(args);
  dfsch_collections_priority_queue_push(queue, object);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (priority_queue_pop , 0)
Definition at line 15 of file collections_mod.c.
References DFSCH_ARG_END, dfsch_collections_priority_queue_pop(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* queue;
  DFSCH_OBJECT_ARG(args, queue);
  DFSCH_ARG_END(args);
  return dfsch_collections_priority_queue_pop(queue);
}
DFSCH_DEFINE_PRIMITIVE (priority_queue_empty_p , 0)
Definition at line 9 of file collections_mod.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_collections_priority_queue_empty_p(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* queue;
  DFSCH_OBJECT_ARG(args, queue);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_collections_priority_queue_empty_p(queue));
}
DFSCH_DEFINE_PRIMITIVE (make_priority_queue , 0)
Definition at line 3 of file collections_mod.c.
References DFSCH_ARG_END, dfsch_collections_make_priority_queue(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* lt;
  DFSCH_OBJECT_ARG(args, lt);
  DFSCH_ARG_END(args);
  return dfsch_collections_make_priority_queue(lt);
}
void dfsch_module_collections_register (dfsch_object_t * env)
Definition at line 31 of file collections_mod.c.
References DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE, dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "collections");
  dfsch_define_cstr(env, "collections:<priority-queue>",
                    DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE);
  dfsch_define_cstr(env, "collections:make-priority-queue",
                    DFSCH_PRIMITIVE_REF(make_priority_queue));
  dfsch_define_cstr(env, "collections:priority-queue-push!",
                    DFSCH_PRIMITIVE_REF(priority_queue_push));
  dfsch_define_cstr(env, "collections:priority-queue-pop!",
                    DFSCH_PRIMITIVE_REF(priority_queue_pop));
  dfsch_define_cstr(env, "collections:priority-queue-empty?",
                    DFSCH_PRIMITIVE_REF(priority_queue_empty_p));
}