dfsch: dfsch/lib/collections.h File Reference
dfsch/lib/collections.h File Reference
#include <dfsch/dfsch.h>
Defines
#define DFSCH_COLLECTIONS_BITVECTOR_TYPE (&dfsch_collections_bitvector_type)
#define DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE (&dfsch_collections_priority_queue_type)
Functions
dfsch_object_t * dfsch_collections_bitvector_2_integer (dfsch_object_t *bv)
dfsch_object_t * dfsch_collections_bitvector_and (dfsch_object_t *bva, dfsch_object_t *bvb)
size_t dfsch_collections_bitvector_length (dfsch_object_t *bv)
dfsch_object_t * dfsch_collections_bitvector_not (dfsch_object_t *bv)
dfsch_object_t * dfsch_collections_bitvector_or (dfsch_object_t *bva, dfsch_object_t *bvb)
int dfsch_collections_bitvector_ref (dfsch_object_t *bv, size_t n)
void dfsch_collections_bitvector_set (dfsch_object_t *bv, size_t n, int v)
dfsch_object_t * dfsch_collections_bitvector_xor (dfsch_object_t *bva, dfsch_object_t *bvb)
dfsch_object_t * dfsch_collections_integer_2_bitvector (dfsch_object_t *bv)
dfsch_object_t * dfsch_collections_make_bitvector (size_t length)
dfsch_object_t * dfsch_collections_make_priority_queue (dfsch_object_t *lt)
int dfsch_collections_priority_queue_empty_p (dfsch_object_t *q)
dfsch_object_t * dfsch_collections_priority_queue_pop (dfsch_object_t *q)
void dfsch_collections_priority_queue_push (dfsch_object_t *q, dfsch_object_t *o)
Variables
dfsch_type_t dfsch_collections_bitvector_type
dfsch_type_t dfsch_collections_priority_queue_type
Define Documentation
#define DFSCH_COLLECTIONS_BITVECTOR_TYPE (&dfsch_collections_bitvector_type)
Definition at line 17 of file collections.h.
#define DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE (&dfsch_collections_priority_queue_type)
Definition at line 7 of file collections.h.
Referenced by dfsch_collections_make_priority_queue(), dfsch_collections_priority_queue_empty_p(), dfsch_collections_priority_queue_pop(), dfsch_collections_priority_queue_push(), and dfsch_module_collections_register().
Function Documentation
dfsch_object_t* dfsch_collections_bitvector_2_integer (dfsch_object_t * bv)
dfsch_object_t* dfsch_collections_bitvector_and (dfsch_object_t * bva, dfsch_object_t * bvb)
size_t dfsch_collections_bitvector_length (dfsch_object_t * bv)
dfsch_object_t* dfsch_collections_bitvector_not (dfsch_object_t * bv)
dfsch_object_t* dfsch_collections_bitvector_or (dfsch_object_t * bva, dfsch_object_t * bvb)
int dfsch_collections_bitvector_ref (dfsch_object_t * bv, size_t n)
void dfsch_collections_bitvector_set (dfsch_object_t * bv, size_t n, int v)
dfsch_object_t* dfsch_collections_bitvector_xor (dfsch_object_t * bva, dfsch_object_t * bvb)
dfsch_object_t* dfsch_collections_integer_2_bitvector (dfsch_object_t * bv)
dfsch_object_t* dfsch_collections_make_bitvector (size_t length)
dfsch_object_t* dfsch_collections_make_priority_queue (dfsch_object_t * lt)
Definition at line 25 of file collections.c.
References DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE, dfsch_make_object(), pqueue_t::head, and pqueue_t::lt.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  pqueue_t* pq = dfsch_make_object(DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE);
  pq->head = NULL;
  pq->lt = lt;
  return (dfsch_object_t*)pq;
}
int dfsch_collections_priority_queue_empty_p (dfsch_object_t * q)
Definition at line 80 of file collections.c.
References DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE, dfsch_error(), and DFSCH_INSTANCE_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (!DFSCH_INSTANCE_P(q, DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE)){
    dfsch_error("Not a priority queue", q);
  }
  return ((pqueue_t*)q)->head == NULL;
}
dfsch_object_t* dfsch_collections_priority_queue_pop (dfsch_object_t * q)
Definition at line 66 of file collections.c.
References DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE, dfsch_error(), DFSCH_INSTANCE_P, pqueue_t::head, pq_entry_t::next, and pq_entry_t::object.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  pqueue_t* pq;
  pq_entry_t* e;
  if (!DFSCH_INSTANCE_P(q, DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE)){
    dfsch_error("Not a priority queue", q);
  }
  pq = q;
  if (!pq->head){
    dfsch_error("Priority queue is empty", q);
  }
  e = pq->head;
  pq->head = e->next;
  return e->object;
}
void dfsch_collections_priority_queue_push (dfsch_object_t * q, dfsch_object_t * o)
Definition at line 33 of file collections.c.
References dfsch_apply(), DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE, dfsch_error(), DFSCH_INSTANCE_P, dfsch_list(), pqueue_t::head, pqueue_t::lt, pq_entry_t::next, and pq_entry_t::object.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  pqueue_t* pq;
  pq_entry_t* e;
  pq_entry_t* i;
  if (!DFSCH_INSTANCE_P(q, DFSCH_COLLECTIONS_PRIORITY_QUEUE_TYPE)){
    dfsch_error("Not a priority queue", q);
  }
  pq = (pqueue_t*)q;
  e = GC_NEW(pq_entry_t);
  e->object = o;
  if (!pq->head){
    pq->head = e;
  } else if (dfsch_apply(pq->lt, dfsch_list(2,
                                            e->object,
                                            pq->head->object)) != NULL){
    e->next = pq->head;
    pq->head = e;
  } else {
    i = pq->head;
    while (i->next){
      if (dfsch_apply(pq->lt, dfsch_list(2,
                                         e->object,
                                         i->next->object))){
        e->next = i->next;
        break;
      }
    }
    i->next = e;
  }
}
Variable Documentation
dfsch_type_t dfsch_collections_bitvector_type
dfsch_type_t dfsch_collections_priority_queue_type
Definition at line 16 of file collections.c.