dfsch: src/conditions.c File Reference
src/conditions.c File Reference
#include "dfsch/conditions.h"
#include "dfsch/magic.h"
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include "util.h"
Data Structures
struct restart_t
Functions
static void condition_write (dfsch__condition_t *c, dfsch_writer_state_t *state)
void dfsch__conditions_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_compute_restarts ()
dfsch_object_t * dfsch_condition (dfsch_type_t *type,...)
dfsch_object_t * dfsch_condition_field (dfsch_object_t *condition, dfsch_object_t *name)
dfsch_object_t * dfsch_condition_field_cstr (dfsch_object_t *condition, char *name)
dfsch_object_t * dfsch_condition_fields (dfsch_object_t *condition)
void dfsch_condition_put_field (dfsch_object_t *condition, dfsch_object_t *name, dfsch_object_t *value)
void dfsch_condition_put_field_cstr (dfsch_object_t *condition, char *name, dfsch_object_t *value)
dfsch_object_t * dfsch_condition_with_fields (dfsch_type_t *type, dfsch_object_t *message, dfsch_object_t *fields)
DFSCH_DEFINE_FORM_IMPL (restart_bind, NULL)
DFSCH_DEFINE_FORM_IMPL (handler_bind, NULL)
DFSCH_DEFINE_PRIMITIVE (restart_description, 0)
DFSCH_DEFINE_PRIMITIVE (restart_name, 0)
DFSCH_DEFINE_PRIMITIVE (runtime_error,"Signal an runtime-error condition")
DFSCH_DEFINE_PRIMITIVE (error,"Signal an error condition")
DFSCH_DEFINE_PRIMITIVE (warning,"Signal a warning condition")
DFSCH_DEFINE_PRIMITIVE (compute_restarts, 0)
DFSCH_DEFINE_PRIMITIVE (invoke_restart, 0)
DFSCH_DEFINE_PRIMITIVE (signal, 0)
DFSCH_DEFINE_PRIMITIVE (condition_fields, 0)
DFSCH_DEFINE_PRIMITIVE (condition_put_field, 0)
DFSCH_DEFINE_PRIMITIVE (condition_field, 0)
DFSCH_DEFINE_PRIMITIVE (make_condition_with_fields, 0)
DFSCH_DEFINE_PRIMITIVE (make_condition, 0)
void dfsch_enter_debugger (dfsch_object_t *reason)
int dfsch_get_debugger_depth ()
void dfsch_handler_bind (dfsch_type_t *type, dfsch_object_t *handler)
dfsch_object_t * dfsch_invoke_restart (dfsch_object_t *restart, dfsch_object_t *args)
dfsch_object_t * dfsch_make_condition (dfsch_type_t *type)
dfsch_object_t * dfsch_make_restart (dfsch_object_t *name, dfsch_object_t *proc, char *description, char *arg_descriptions)
dfsch_object_t * dfsch_make_throw_proc (dfsch_object_t *catch_tag)
dfsch_object_t * dfsch_make_throw_proc_arg (dfsch_object_t *catch_tag)
void dfsch_operating_system_error (char *funname)
void dfsch_operating_system_error_saved (int e, char *funname)
void dfsch_restart_bind (dfsch_object_t *restart)
char * dfsch_restart_description (dfsch_object_t *restart)
dfsch_object_t * dfsch_restart_name (dfsch_object_t *restart)
dfsch_object_t * dfsch_restart_proc (dfsch_object_t *restart)
void dfsch_set_debugger (dfsch_object_t *proc)
void dfsch_set_invoke_debugger_on_all_conditions (int val)
void dfsch_signal (dfsch_object_t *condition)
void dfsch_signal_condition (dfsch_type_t *type, char *message,...)
void dfsch_type_error (dfsch_object_t *datum, dfsch_type_t *type, int instance_suffices)
static dfsch_object_t * throw_proc (dfsch_object_t *tag, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * throw_proc_arg (dfsch_object_t *tag, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Variables
static int debugger_depth = 0
static pthread_mutex_t debugger_depth_mutex = PTHREAD_MUTEX_INITIALIZER
static dfsch_object_t * debugger_proc = NULL
dfsch_type_t dfsch_condition_type
dfsch_type_t dfsch_error_type
dfsch_type_t dfsch_operating_system_error_type
dfsch_type_t dfsch_restart_type
dfsch_type_t dfsch_runtime_error_type
dfsch_type_t dfsch_type_error_type
dfsch_type_t dfsch_warning_type
static int invoke_debugger_on_all_conditions = 0
static int max_debugger_recursion = 10
Function Documentation
static void condition_write (dfsch__condition_t * c, dfsch_writer_state_t * state) [static]
Definition at line 21 of file conditions.c.
References dfsch_compare_symbol(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_PAIR_P, DFSCH_SYMBOL_TYPE, DFSCH_TYPE_OF, dfsch_write_object(), dfsch_write_string(), dfsch_write_unreadable_end(), dfsch_write_unreadable_start(), and dfsch__condition_t::fields.
{
  dfsch_object_t* i = c->fields;
  dfsch_object_t* j;
  dfsch_write_unreadable_start(state, c);
  while (DFSCH_PAIR_P(i)){
    j = DFSCH_FAST_CAR(i);
    i = DFSCH_FAST_CDR(i);
    if (!DFSCH_PAIR_P(j)){
      dfsch_write_string(state, "*malformed-fileds*");
      dfsch_write_unreadable_end(state);
      return;
    }
    if (DFSCH_TYPE_OF(DFSCH_FAST_CAR(j)) == DFSCH_SYMBOL_TYPE &&
        dfsch_compare_symbol(DFSCH_FAST_CAR(j), "stack-trace")){
      continue;
    }
    dfsch_write_object(state, DFSCH_FAST_CAR(j));
    dfsch_write_string(state, " ");
    dfsch_write_object(state, DFSCH_FAST_CDR(j));
    if (DFSCH_PAIR_P(i)){
      dfsch_write_string(state, " ");
    }
  }
  dfsch_write_unreadable_end(state);
}
void dfsch__conditions_register (dfsch_object_t * ctx)
Definition at line 582 of file conditions.c.
References DFSCH_CONDITION_TYPE, dfsch_define_cstr(), DFSCH_ERROR_TYPE, DFSCH_FORM_REF, DFSCH_OPERATING_SYSTEM_ERROR_TYPE, DFSCH_PRIMITIVE_REF, DFSCH_RUNTIME_ERROR_TYPE, DFSCH_TYPE_ERROR_TYPE, and DFSCH_WARNING_TYPE.
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<condition>", DFSCH_CONDITION_TYPE);
  dfsch_define_cstr(ctx, "<warning>", DFSCH_WARNING_TYPE);
  dfsch_define_cstr(ctx, "<error>", DFSCH_ERROR_TYPE);
  dfsch_define_cstr(ctx, "<runtime-error>", DFSCH_RUNTIME_ERROR_TYPE);
  dfsch_define_cstr(ctx, "<type-error>", DFSCH_TYPE_ERROR_TYPE);
  dfsch_define_cstr(ctx, "<operating-system-error>",
                    DFSCH_OPERATING_SYSTEM_ERROR_TYPE);
  dfsch_define_cstr(ctx, "make-condition",
                    DFSCH_PRIMITIVE_REF(make_condition));
  dfsch_define_cstr(ctx, "make-condition-with-fields",
                    DFSCH_PRIMITIVE_REF(make_condition_with_fields));
  dfsch_define_cstr(ctx, "condition-field",
                    DFSCH_PRIMITIVE_REF(condition_field));
  dfsch_define_cstr(ctx, "condition-put-field",
                    DFSCH_PRIMITIVE_REF(condition_put_field));
  dfsch_define_cstr(ctx, "condition-fields",
                    DFSCH_PRIMITIVE_REF(condition_fields));
  dfsch_define_cstr(ctx, "signal",
                    DFSCH_PRIMITIVE_REF(signal));
  dfsch_define_cstr(ctx, "invoke-restart",
                    DFSCH_PRIMITIVE_REF(invoke_restart));
  dfsch_define_cstr(ctx, "compute-restarts",
                    DFSCH_PRIMITIVE_REF(compute_restarts));
  dfsch_define_cstr(ctx, "warning",
                    DFSCH_PRIMITIVE_REF(warning));
  dfsch_define_cstr(ctx, "error",
                    DFSCH_PRIMITIVE_REF(error));
  dfsch_define_cstr(ctx, "runtime-error",
                    DFSCH_PRIMITIVE_REF(runtime_error));
  dfsch_define_cstr(ctx, "restart-name",
                    DFSCH_PRIMITIVE_REF(restart_name));
  dfsch_define_cstr(ctx, "restart-description",
                    DFSCH_PRIMITIVE_REF(restart_description));
  dfsch_define_cstr(ctx, "handler-bind",
                    DFSCH_FORM_REF(handler_bind));
  dfsch_define_cstr(ctx, "restart-bind",
                    DFSCH_FORM_REF(restart_bind));
}
dfsch_object_t* dfsch_compute_restarts ()
Definition at line 295 of file conditions.c.
References dfsch__get_thread_info(), dfsch_cons(), DFSCH_FAST_CDR_MUT, dfsch__restart_list_t::next, dfsch__restart_list_t::restart, and dfsch__thread_info_t::restart_list.
Referenced by debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  dfsch__restart_list_t* i = ti->restart_list;
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  while (i){
    dfsch_object_t* tmp = dfsch_cons(i->restart, NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    } else {
      head = tail = tmp;
    }
    i = i->next;
  }
  return head;
}
dfsch_object_t* dfsch_condition (dfsch_type_t * type, ...)
Definition at line 86 of file conditions.c.
References dfsch_condition_put_field_cstr(), and dfsch_make_condition().
Referenced by dfsch_cerror(), and dfsch_error().
{
  va_list al;
  dfsch_object_t* c = dfsch_make_condition(type);
  char* name;
  va_start(al, type);
  while (name = va_arg(al, char*)){
    dfsch_condition_put_field_cstr(c, name, va_arg(al, dfsch_object_t*));
  }
  va_end(al);
  return c;
}
dfsch_object_t* dfsch_condition_field (dfsch_object_t * condition, dfsch_object_t * name)
Definition at line 51 of file conditions.c.
References dfsch_assert_instance(), dfsch_assq(), dfsch_cdr(), DFSCH_CONDITION_TYPE, and dfsch__condition_t::fields.
Referenced by dfsch_condition_field_cstr(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* al;
  dfsch__condition_t* c = dfsch_assert_instance(condition,
                                                DFSCH_CONDITION_TYPE);
  al = dfsch_assq(name, c->fields);
  if (!al){
    return NULL;
  } else {
    return dfsch_cdr(al);
  }
}
dfsch_object_t* dfsch_condition_field_cstr (dfsch_object_t * condition, char * name)
Definition at line 71 of file conditions.c.
References dfsch_condition_field(), and dfsch_make_symbol().
Referenced by debug_main().
{
  return dfsch_condition_field(condition, dfsch_make_symbol(name));
}
dfsch_object_t* dfsch_condition_fields (dfsch_object_t * condition)
Definition at line 80 of file conditions.c.
References dfsch_assert_instance(), and DFSCH_CONDITION_TYPE.
Referenced by debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  return ((dfsch__condition_t*)
          dfsch_assert_instance(condition,
                                DFSCH_CONDITION_TYPE))->fields;
}
void dfsch_condition_put_field (dfsch_object_t * condition, dfsch_object_t * name, dfsch_object_t * value)
Definition at line 63 of file conditions.c.
References dfsch_assert_instance(), DFSCH_CONDITION_TYPE, dfsch_cons(), and dfsch__condition_t::fields.
Referenced by dfsch_condition_put_field_cstr(), dfsch_condition_with_fields(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch__condition_t* c = dfsch_assert_instance(condition,
                                                DFSCH_CONDITION_TYPE);
  c->fields = dfsch_cons(dfsch_cons(name, value), c->fields);
}
void dfsch_condition_put_field_cstr (dfsch_object_t * condition, char * name, dfsch_object_t * value)
Definition at line 75 of file conditions.c.
References dfsch_condition_put_field(), and dfsch_make_symbol().
Referenced by dfsch_condition(), dfsch_condition_with_fields(), dfsch_operating_system_error_saved(), dfsch_signal_condition(), and dfsch_type_error().
{
  return dfsch_condition_put_field(condition, dfsch_make_symbol(name), value);
}
dfsch_object_t* dfsch_condition_with_fields (dfsch_type_t * type, dfsch_object_t * message, dfsch_object_t * fields)
Definition at line 118 of file conditions.c.
References dfsch_condition_put_field(), dfsch_condition_put_field_cstr(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_condition(), and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* c = dfsch_make_condition(type);
  dfsch_object_t* name;
  dfsch_object_t* value;
  dfsch_condition_put_field_cstr(c, "message", message);
  while (DFSCH_PAIR_P(fields)){
    name = DFSCH_FAST_CAR(fields);
    fields = DFSCH_FAST_CDR(fields);
    if (!DFSCH_PAIR_P(fields)){
      dfsch_error("Missing value for keyword", name);
    }
    value = DFSCH_FAST_CAR(fields);
    fields = DFSCH_FAST_CDR(fields);
    dfsch_condition_put_field(c, name, value);
  }
  return c;
}
DFSCH_DEFINE_FORM_IMPL (restart_bind , NULL)
Definition at line 552 of file conditions.c.
References DFSCH_ARG_END, DFSCH_ARG_REST, dfsch_eval(), dfsch_eval_proc(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_restart(), DFSCH_OBJECT_ARG, DFSCH_PAIR_P, dfsch_restart_bind(), DFSCH_RESTORE_HANDLERS, and DFSCH_SAVE_HANDLERS.
{
  dfsch_object_t* ret;
  dfsch_object_t* bindings;
  dfsch_object_t* code;
  DFSCH_OBJECT_ARG(args, bindings);
  DFSCH_ARG_REST(args, code);
  DFSCH_SAVE_HANDLERS;
  while (DFSCH_PAIR_P(bindings)){
    dfsch_object_t* name;
    dfsch_object_t* proc;
    DFSCH_OBJECT_ARG(DFSCH_FAST_CAR(bindings), name);
    DFSCH_OBJECT_ARG(DFSCH_FAST_CAR(bindings), proc);
    DFSCH_ARG_END(DFSCH_FAST_CAR(bindings));
    proc = dfsch_eval(proc, env);
    // TODO
    dfsch_restart_bind(dfsch_make_restart(name, proc, "", NULL));
    bindings = DFSCH_FAST_CDR(bindings);
  }
  ret = dfsch_eval_proc(code, env);
  DFSCH_RESTORE_HANDLERS;
  return ret;
}
DFSCH_DEFINE_FORM_IMPL (handler_bind , NULL)
Definition at line 523 of file conditions.c.
References DFSCH_ARG_END, DFSCH_ARG_REST, dfsch_eval(), dfsch_eval_proc(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_handler_bind(), DFSCH_OBJECT_ARG, DFSCH_PAIR_P, DFSCH_RESTORE_HANDLERS, and DFSCH_SAVE_HANDLERS.
{
  dfsch_object_t* ret;
  dfsch_object_t* bindings;
  dfsch_object_t* code;
  DFSCH_OBJECT_ARG(args, bindings);
  DFSCH_ARG_REST(args, code);
  DFSCH_SAVE_HANDLERS;
  while (DFSCH_PAIR_P(bindings)){
    dfsch_object_t* type;
    dfsch_object_t* handler;
    DFSCH_OBJECT_ARG(DFSCH_FAST_CAR(bindings), type);
    DFSCH_OBJECT_ARG(DFSCH_FAST_CAR(bindings), handler);
    DFSCH_ARG_END(DFSCH_FAST_CAR(bindings));
    type = dfsch_eval(type, env);
    handler = dfsch_eval(handler, env);
    dfsch_handler_bind(type, handler);
    bindings = DFSCH_FAST_CDR(bindings);
  }
  ret = dfsch_eval_proc(code, env);
  DFSCH_RESTORE_HANDLERS;
  return ret;
}
DFSCH_DEFINE_PRIMITIVE (restart_description , 0)
Definition at line 510 of file conditions.c.
References DFSCH_ARG_END, dfsch_make_string_cstr(), DFSCH_OBJECT_ARG, and dfsch_restart_description().
{
  dfsch_object_t* restart;
  DFSCH_OBJECT_ARG(args, restart);
  DFSCH_ARG_END(args);
  return dfsch_make_string_cstr(dfsch_restart_description(restart));
}
DFSCH_DEFINE_PRIMITIVE (restart_name , 0)
Definition at line 503 of file conditions.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_restart_name().
{
  dfsch_object_t* restart;
  DFSCH_OBJECT_ARG(args, restart);
  DFSCH_ARG_END(args);
  return dfsch_restart_name(restart);
}
DFSCH_DEFINE_PRIMITIVE (runtime_error , "Signal an runtime-error condition")
Definition at line 491 of file conditions.c.
References DFSCH_ARG_REST, dfsch_condition_with_fields(), DFSCH_OBJECT_ARG, DFSCH_RUNTIME_ERROR_TYPE, and dfsch_signal().
{
  dfsch_object_t* message;
  dfsch_object_t* fields;
  DFSCH_OBJECT_ARG(args, message);
  DFSCH_ARG_REST(args, fields);
  dfsch_signal(dfsch_condition_with_fields(DFSCH_RUNTIME_ERROR_TYPE,
                                           message, fields));
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (error , "Signal an error condition")
Definition at line 481 of file conditions.c.
References DFSCH_ARG_REST, dfsch_condition_with_fields(), DFSCH_ERROR_TYPE, DFSCH_OBJECT_ARG, and dfsch_signal().
{
  dfsch_object_t* message;
  dfsch_object_t* fields;
  DFSCH_OBJECT_ARG(args, message);
  DFSCH_ARG_REST(args, fields);
  dfsch_signal(dfsch_condition_with_fields(DFSCH_ERROR_TYPE,
                                           message, fields));
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (warning , "Signal a warning condition")
Definition at line 471 of file conditions.c.
References DFSCH_ARG_REST, dfsch_condition_with_fields(), DFSCH_OBJECT_ARG, dfsch_signal(), and DFSCH_WARNING_TYPE.
{
  dfsch_object_t* message;
  dfsch_object_t* fields;
  DFSCH_OBJECT_ARG(args, message);
  DFSCH_ARG_REST(args, fields);
  dfsch_signal(dfsch_condition_with_fields(DFSCH_WARNING_TYPE,
                                           message, fields));
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (compute_restarts , 0)
Definition at line 465 of file conditions.c.
References DFSCH_ARG_END, and dfsch_compute_restarts().
{
  DFSCH_ARG_END(args);
  return dfsch_compute_restarts();
}
DFSCH_DEFINE_PRIMITIVE (invoke_restart , 0)
Definition at line 458 of file conditions.c.
References dfsch_invoke_restart(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* restart;
  DFSCH_OBJECT_ARG(args, restart);
  dfsch_invoke_restart(restart, args);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (signal , 0)
Definition at line 450 of file conditions.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_signal().
{
  dfsch_object_t* condition;
  DFSCH_OBJECT_ARG(args, condition);
  DFSCH_ARG_END(args);
  dfsch_signal(condition);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (condition_fields , 0)
Definition at line 440 of file conditions.c.
References DFSCH_ARG_END, dfsch_condition_fields(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* condition;
  DFSCH_OBJECT_ARG(args, condition);
  DFSCH_ARG_END(args);
  return dfsch_condition_fields(condition);
}
DFSCH_DEFINE_PRIMITIVE (condition_put_field , 0)
Definition at line 428 of file conditions.c.
References DFSCH_ARG_END, dfsch_condition_put_field(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* condition;
  dfsch_object_t* field;
  dfsch_object_t* value;
  DFSCH_OBJECT_ARG(args, condition);
  DFSCH_OBJECT_ARG(args, field);
  DFSCH_OBJECT_ARG(args, value);
  DFSCH_ARG_END(args);
  dfsch_condition_put_field(condition, field, value);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (condition_field , 0)
Definition at line 419 of file conditions.c.
References DFSCH_ARG_END, dfsch_condition_field(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* condition;
  dfsch_object_t* field;
  DFSCH_OBJECT_ARG(args, condition);
  DFSCH_OBJECT_ARG(args, field);
  DFSCH_ARG_END(args);
  return dfsch_condition_field(condition, field);
}
DFSCH_DEFINE_PRIMITIVE (make_condition_with_fields , 0)
Definition at line 409 of file conditions.c.
References DFSCH_ARG_REST, dfsch_condition_with_fields(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* type;
  dfsch_object_t* message;
  dfsch_object_t* fields;
  DFSCH_OBJECT_ARG(args, type);
  DFSCH_OBJECT_ARG(args, message);
  DFSCH_ARG_REST(args, fields);
  return dfsch_condition_with_fields(type, message, fields);
}
DFSCH_DEFINE_PRIMITIVE (make_condition , 0)
Definition at line 402 of file conditions.c.
References DFSCH_ARG_END, dfsch_make_condition(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* type;
  DFSCH_OBJECT_ARG(args, type);
  DFSCH_ARG_END(args);
  return dfsch_make_condition(type);
}
void dfsch_enter_debugger (dfsch_object_t * reason)
Definition at line 207 of file conditions.c.
References dfsch_apply(), dfsch_cons(), DFSCH_PROTECT, DFSCH_PROTECT_END, and DFSCH_UNWIND.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_signal().
{
  pthread_mutex_lock(&debugger_depth_mutex);
  if (debugger_depth > max_debugger_recursion){
    pthread_mutex_unlock(&debugger_depth_mutex);
    fputs("Debugger recursion limit exceeded!\n\n", stderr);
    return;
  }
  debugger_depth++;
  pthread_mutex_unlock(&debugger_depth_mutex);
  DFSCH_UNWIND {
    if (debugger_proc){
      dfsch_apply(debugger_proc, dfsch_cons(reason, NULL));
    }
  } DFSCH_PROTECT {
    pthread_mutex_lock(&debugger_depth_mutex);
    debugger_depth--;
    pthread_mutex_unlock(&debugger_depth_mutex);
  } DFSCH_PROTECT_END;
}
int dfsch_get_debugger_depth ()
Definition at line 228 of file conditions.c.
Referenced by debug_main().
{
  int r;
  pthread_mutex_lock(&debugger_depth_mutex);
  r = debugger_depth;
  pthread_mutex_unlock(&debugger_depth_mutex);
  return r;
}
void dfsch_handler_bind (dfsch_type_t * type, dfsch_object_t * handler)
Definition at line 283 of file conditions.c.
References dfsch__get_thread_info(), dfsch__handler_list_t::handler, dfsch__thread_info_t::handler_list, dfsch__handler_list_t::next, and dfsch__handler_list_t::type.
Referenced by dfsch_debug_register_handler(), and DFSCH_DEFINE_FORM_IMPL().
{
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  dfsch__handler_list_t* l = GC_NEW(dfsch__handler_list_t);
  l->next = ti->handler_list;
  l->type = type;
  l->handler = handler;
  ti->handler_list = l;
}
dfsch_object_t* dfsch_invoke_restart (dfsch_object_t * restart, dfsch_object_t * args)
Definition at line 315 of file conditions.c.
References dfsch__get_thread_info(), dfsch_apply(), dfsch_error(), dfsch_restart_name(), dfsch_restart_proc(), DFSCH_RESTART_TYPE, DFSCH_TYPE_OF, dfsch__restart_list_t::next, dfsch__restart_list_t::restart, and dfsch__thread_info_t::restart_list.
Referenced by debug_invoke_restart(), debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(restart) != DFSCH_RESTART_TYPE){
    dfsch__thread_info_t* ti = dfsch__get_thread_info();
    dfsch__restart_list_t* i = ti->restart_list;
    while (i){
      if (dfsch_restart_name(i->restart) == restart){
        break;
      }
      i = i->next;
    }
    if (!i){
      dfsch_error("No such restart", restart);
    }
    restart = i->restart;
  }
  return dfsch_apply(dfsch_restart_proc(restart), args);
}
dfsch_object_t* dfsch_make_condition (dfsch_type_t * type)
Definition at line 8 of file conditions.c.
References DFSCH_CONDITION_TYPE, dfsch_error(), DFSCH_INSTANCE_P, dfsch_make_object(), DFSCH_STANDARD_TYPE, dfsch_superclass_p(), and dfsch__condition_t::fields.
Referenced by dfsch_condition(), dfsch_condition_with_fields(), DFSCH_DEFINE_PRIMITIVE(), dfsch_operating_system_error_saved(), dfsch_signal_condition(), and dfsch_type_error().
{
  dfsch__condition_t* c;
  if (!DFSCH_INSTANCE_P(type, DFSCH_STANDARD_TYPE) ||
      !dfsch_superclass_p(type, DFSCH_CONDITION_TYPE)){
    dfsch_error("Not a condition type", (dfsch_object_t*)type);
  }
  c = (dfsch__condition_t*)dfsch_make_object(type);
  c->fields = NULL;
  return (dfsch_object_t*)c;
}
dfsch_object_t* dfsch_make_restart (dfsch_object_t * name, dfsch_object_t * proc, char * description, char * arg_descriptions)
Definition at line 251 of file conditions.c.
References restart_t::arg_descriptions, restart_t::description, dfsch_make_object(), DFSCH_RESTART_TYPE, restart_t::name, and restart_t::proc.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and main().
{
  restart_t* r = (restart_t*) dfsch_make_object(DFSCH_RESTART_TYPE);
  r->name = name;
  r->proc = proc;
  r->description = description;
  r->arg_descriptions = arg_descriptions;
  return (dfsch_object_t*) r;
}
dfsch_object_t* dfsch_make_throw_proc (dfsch_object_t * catch_tag)
Definition at line 343 of file conditions.c.
References dfsch_make_primitive(), and throw_proc().
{
  return dfsch_make_primitive(throw_proc, catch_tag);
}
dfsch_object_t* dfsch_make_throw_proc_arg (dfsch_object_t * catch_tag)
Definition at line 355 of file conditions.c.
References dfsch_make_primitive(), and throw_proc_arg().
{
  return dfsch_make_primitive(throw_proc_arg, catch_tag);
}
void dfsch_operating_system_error (char * funname)
Definition at line 393 of file conditions.c.
References dfsch_operating_system_error_saved().
Referenced by dfsch_open_file_port(), dfsch_read_scm(), dfsch_read_scm_fd(), dfsch_unix_opendir(), dfsch_unix_readdir(), file_port_read_buf(), file_port_seek(), file_port_tell(), file_port_write_buf(), native_access(), native_chdir(), native_chmod(), native_chown(), native_close(), native_creat(), native_dup(), native_dup2(), native_fchdir(), native_fchmod(), native_fchown(), native_fork(), native_fstat(), native_getpgid(), native_isatty(), native_kill(), native_killpg(), native_link(), native_lseek(), native_lstat(), native_mkdir(), native_mkfifo(), native_nice(), native_open(), native_pipe(), native_raise(), native_read(), native_rename(), native_rmdir(), native_setegid(), native_seteuid(), native_setgid(), native_setpgid(), native_setpgrp(), native_setsid(), native_setuid(), native_stat(), native_symlink(), native_unlink(), native_wait(), native_waitpid(), and native_write().
{
  dfsch_operating_system_error_saved(errno, funname);
}
void dfsch_operating_system_error_saved (int e, char * funname)
Definition at line 383 of file conditions.c.
References dfsch_condition_put_field_cstr(), dfsch_make_condition(), DFSCH_MAKE_FIXNUM, dfsch_make_string_cstr(), DFSCH_OPERATING_SYSTEM_ERROR_TYPE, and dfsch_signal().
Referenced by dfsch_operating_system_error(), and native_getcwd().
{
  dfsch_object_t* c = dfsch_make_condition(DFSCH_OPERATING_SYSTEM_ERROR_TYPE);
  char* m = strerror(e);
  dfsch_condition_put_field_cstr(c, "errno", DFSCH_MAKE_FIXNUM(e));
  dfsch_condition_put_field_cstr(c, "function",
                                 dfsch_make_string_cstr(funname));
  dfsch_condition_put_field_cstr(c, "message", dfsch_make_string_cstr(m));
  dfsch_signal(c);
}
void dfsch_restart_bind (dfsch_object_t * restart)
Definition at line 274 of file conditions.c.
References dfsch__get_thread_info(), dfsch__restart_list_t::next, dfsch__restart_list_t::restart, and dfsch__thread_info_t::restart_list.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and main().
{
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  dfsch__restart_list_t* l = GC_NEW(dfsch__restart_list_t);
  l->next = ti->restart_list;
  l->restart = restart;
  ti->restart_list = l;
}
char* dfsch_restart_description (dfsch_object_t * restart)
Definition at line 270 of file conditions.c.
References dfsch_assert_type(), and DFSCH_RESTART_TYPE.
Referenced by debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  return ((restart_t*)dfsch_assert_type(restart, DFSCH_RESTART_TYPE))->description;
}
dfsch_object_t* dfsch_restart_name (dfsch_object_t * restart)
Definition at line 264 of file conditions.c.
References dfsch_assert_type(), and DFSCH_RESTART_TYPE.
Referenced by debug_main(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_invoke_restart().
{
  return ((restart_t*)dfsch_assert_type(restart, DFSCH_RESTART_TYPE))->name;
}
dfsch_object_t* dfsch_restart_proc (dfsch_object_t * restart)
Definition at line 267 of file conditions.c.
References dfsch_assert_type(), and DFSCH_RESTART_TYPE.
Referenced by dfsch_invoke_restart().
{
  return ((restart_t*)dfsch_assert_type(restart, DFSCH_RESTART_TYPE))->proc;
}
void dfsch_set_debugger (dfsch_object_t * proc)
Definition at line 197 of file conditions.c.
Referenced by dfsch_cdebug_set_as_debugger(), and DFSCH_DEFINE_PRIMITIVE().
{
  debugger_proc = proc;
}
void dfsch_set_invoke_debugger_on_all_conditions (int val)
Definition at line 200 of file conditions.c.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  invoke_debugger_on_all_conditions = val;
}
void dfsch_signal (dfsch_object_t * condition)
Definition at line 163 of file conditions.c.
References dfsch__get_thread_info(), dfsch_apply(), dfsch_cons(), dfsch_enter_debugger(), DFSCH_ERROR_TYPE, DFSCH_INSTANCE_P, dfsch_object_2_string(), dfsch_print_trace_buffer(), dfsch__handler_list_t::handler, dfsch__thread_info_t::handler_list, dfsch__handler_list_t::next, and dfsch__handler_list_t::type.
Referenced by dfsch_cerror(), DFSCH_DEFINE_PRIMITIVE(), dfsch_error(), dfsch_operating_system_error_saved(), dfsch_signal_condition(), and dfsch_type_error().
{
  dfsch__handler_list_t* save;
  dfsch__handler_list_t* i;
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  i = save = ti->handler_list;
  while (i){
    if (DFSCH_INSTANCE_P(condition, i->type)){
      ti->handler_list = i->next;
      dfsch_apply(i->handler, dfsch_cons(condition, NULL));
    }
    i = i->next;
  }
  if (DFSCH_INSTANCE_P(condition, DFSCH_ERROR_TYPE)){
    dfsch_enter_debugger(condition);
    fputs("Unhandled error condition!\n\n", stderr);
    fprintf(stderr, "%s\n", dfsch_object_2_string(condition, 10, 1));
    dfsch_print_trace_buffer();
    abort();
  } else if (invoke_debugger_on_all_conditions){
    dfsch_enter_debugger(condition);
  }
  ti->handler_list = save;
}
void dfsch_signal_condition (dfsch_type_t * type, char * message, ...)
Definition at line 99 of file conditions.c.
References dfsch_condition_put_field_cstr(), dfsch_make_condition(), dfsch_make_string_cstr(), and dfsch_signal().
Referenced by dfsch_cmdopts_parse(), find_long_opt(), find_short_opt(), and get_argument().
{
  va_list al;
  dfsch_object_t* c = dfsch_make_condition(type);
  char* name;
  va_start(al, type);
  while (name = va_arg(al, char*)){
    dfsch_condition_put_field_cstr(c, name, va_arg(al, dfsch_object_t*));
  }
  va_end(al);
  dfsch_condition_put_field_cstr(c, "message",
                                 dfsch_make_string_cstr(message));
  dfsch_signal(c);
}
void dfsch_type_error (dfsch_object_t * datum, dfsch_type_t * type, int instance_suffices)
Definition at line 359 of file conditions.c.
References dfsch_bool(), dfsch_condition_put_field_cstr(), dfsch_make_condition(), dfsch_make_string_cstr(), dfsch_object_2_string(), dfsch_saprintf(), dfsch_signal(), and DFSCH_TYPE_ERROR_TYPE.
Referenced by dfsch_append(), dfsch_assert_instance(), dfsch_assert_type(), dfsch_list_copy(), dfsch_list_length_check(), dfsch_member(), dfsch_memq(), dfsch_memv(), dfsch_reverse(), and dfsch_zip().
{
  char* m;
  dfsch_object_t* c = dfsch_make_condition(DFSCH_TYPE_ERROR_TYPE);
  dfsch_condition_put_field_cstr(c, "datum", datum);
  dfsch_condition_put_field_cstr(c, "type", type);
  dfsch_condition_put_field_cstr(c, "instance-suffices?",
                                 dfsch_bool(instance_suffices));
  if (instance_suffices){
    m = dfsch_saprintf("%s is not an instance of %s",
                       dfsch_object_2_string(datum, 10, 1),
                       dfsch_object_2_string((dfsch_object_t*)type, 10, 1));
  } else {
    m = dfsch_saprintf("%s is not of type %s",
                       dfsch_object_2_string(datum, 10, 1),
                       dfsch_object_2_string((dfsch_object_t*)type, 10, 1));
  }
  dfsch_condition_put_field_cstr(c, "message", dfsch_make_string_cstr(m));
  dfsch_signal(c);
}
static dfsch_object_t* throw_proc (dfsch_object_t * tag, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 336 of file conditions.c.
References DFSCH_ARG_END, and dfsch_throw().
Referenced by dfsch_make_throw_proc().
{
  DFSCH_ARG_END(args);
  dfsch_throw(tag, NULL);
}
static dfsch_object_t* throw_proc_arg (dfsch_object_t * tag, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 346 of file conditions.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_throw().
Referenced by dfsch_make_throw_proc_arg().
{
  dfsch_object_t* arg;
  DFSCH_OBJECT_ARG(args, arg);
  DFSCH_ARG_END(args);
  dfsch_throw(tag, arg);
}
Variable Documentation
int debugger_depth = 0 [static]
Definition at line 204 of file conditions.c.
pthread_mutex_t debugger_depth_mutex = PTHREAD_MUTEX_INITIALIZER [static]
Definition at line 205 of file conditions.c.
dfsch_object_t* debugger_proc = NULL [static]
Definition at line 194 of file conditions.c.
dfsch_type_t dfsch_condition_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  DFSCH_CONDITION_SIZE,
  "condition",
  NULL,
  (dfsch_type_write_t)condition_write
}
Definition at line 140 of file conditions.c.
dfsch_type_t dfsch_error_type
Initial value:
  DFSCH_CONDITION_TYPE_INIT(DFSCH_CONDITION_TYPE, "error")
Definition at line 152 of file conditions.c.
dfsch_type_t dfsch_operating_system_error_type
Initial value:
  DFSCH_CONDITION_TYPE_INIT(DFSCH_RUNTIME_ERROR_TYPE,
                            "operating-system-error")
Definition at line 380 of file conditions.c.
dfsch_type_t dfsch_restart_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(restart_t),
  "restart"
}
Definition at line 245 of file conditions.c.
dfsch_type_t dfsch_runtime_error_type
Initial value:
  DFSCH_CONDITION_TYPE_INIT(DFSCH_ERROR_TYPE, "runtime-error")
Definition at line 158 of file conditions.c.
dfsch_type_t dfsch_type_error_type
Initial value:
  DFSCH_CONDITION_TYPE_INIT(DFSCH_ERROR_TYPE, "type-error")
Definition at line 155 of file conditions.c.
dfsch_type_t dfsch_warning_type
Initial value:
  DFSCH_CONDITION_TYPE_INIT(DFSCH_CONDITION_TYPE, "warning")
Definition at line 149 of file conditions.c.
int invoke_debugger_on_all_conditions = 0 [static]
Definition at line 161 of file conditions.c.
int max_debugger_recursion = 10 [static]
Definition at line 195 of file conditions.c.