dfsch: dfsch/conditions.h File Reference
dfsch/conditions.h File Reference
#include <dfsch/dfsch.h>
#include <stdarg.h>
Data Structures
struct dfsch__condition_t
Defines
#define DFSCH_CONDITION_SIZE (sizeof(dfsch__condition_t))
#define DFSCH_CONDITION_TYPE (&dfsch_condition_type)
#define DFSCH_CONDITION_TYPE_INIT(super, name) {DFSCH_STANDARD_TYPE, super, DFSCH_CONDITION_SIZE, name}
#define DFSCH_ERROR_TYPE (&dfsch_error_type)
#define DFSCH_OPERATING_SYSTEM_ERROR_TYPE (&dfsch_operating_system_error_type)
#define DFSCH_RESTART_TYPE (&dfsch_restart_type)
#define DFSCH_RUNTIME_ERROR_TYPE (&dfsch_runtime_error_type)
#define DFSCH_TYPE_ERROR_TYPE (&dfsch_type_error_type)
#define DFSCH_WARNING_TYPE (&dfsch_warning_type)
Functions
char * dfsch__condition_write (dfsch__condition_t *c, int depth, int readable)
dfsch_object_t * dfsch_compute_restarts ()
dfsch_object_t * dfsch_condition (dfsch_type_t *type,...)
dfsch_object_t * dfsch_condition_field (dfsch_object_t *condition, dfsch_object_t *name)
dfsch_object_t * dfsch_condition_field_cstr (dfsch_object_t *condition, char *name)
dfsch_object_t * dfsch_condition_fields (dfsch_object_t *condition)
void dfsch_condition_put_field (dfsch_object_t *condition, dfsch_object_t *name, dfsch_object_t *value)
void dfsch_condition_put_field_cstr (dfsch_object_t *condition, char *name, dfsch_object_t *value)
dfsch_object_t * dfsch_condition_with_fields (dfsch_type_t *type, dfsch_object_t *message, dfsch_object_t *fields)
void dfsch_enter_debugger (dfsch_object_t *reason)
int dfsch_get_debugger_depth ()
void dfsch_handler_bind (dfsch_type_t *type, dfsch_object_t *handler)
dfsch_object_t * dfsch_invoke_restart (dfsch_object_t *restart, dfsch_object_t *args)
dfsch_object_t * dfsch_make_condition (dfsch_type_t *type)
dfsch_object_t * dfsch_make_restart (dfsch_object_t *name, dfsch_object_t *proc, char *description, char *args_description)
dfsch_object_t * dfsch_make_throw_proc (dfsch_object_t *catch_tag)
dfsch_object_t * dfsch_make_throw_proc_arg (dfsch_object_t *catch_tag)
void dfsch_operating_system_error (char *funname)
void dfsch_operating_system_error_saved (int e, char *funname)
void dfsch_restart_bind (dfsch_object_t *restart)
char * dfsch_restart_description (dfsch_object_t *restart)
dfsch_object_t * dfsch_restart_name (dfsch_object_t *restart)
dfsch_object_t * dfsch_restart_proc (dfsch_object_t *restart)
void dfsch_set_debugger (dfsch_object_t *proc)
void dfsch_set_invoke_debugger_on_all_conditions (int val)
void dfsch_signal (dfsch_object_t *condition)
void dfsch_signal_condition (dfsch_type_t *type, char *message,...)
void dfsch_type_error (dfsch_object_t *datum, dfsch_type_t *type, int instance_suffices)
Variables
dfsch_type_t dfsch_condition_type
dfsch_type_t dfsch_error_type
dfsch_type_t dfsch_operating_system_error_type
dfsch_type_t dfsch_restart_type
dfsch_type_t dfsch_runtime_error_type
dfsch_type_t dfsch_type_error_type
dfsch_type_t dfsch_warning_type
Define Documentation
#define DFSCH_CONDITION_SIZE (sizeof(dfsch__condition_t))
Definition at line 36 of file conditions.h.
#define DFSCH_CONDITION_TYPE (&dfsch_condition_type)
Definition at line 41 of file conditions.h.
Referenced by debug_main(), dfsch__conditions_register(), dfsch_condition_field(), dfsch_condition_fields(), dfsch_condition_put_field(), and dfsch_make_condition().
#define DFSCH_CONDITION_TYPE_INIT (super, name) {DFSCH_STANDARD_TYPE, super, DFSCH_CONDITION_SIZE, name}
Definition at line 37 of file conditions.h.
#define DFSCH_ERROR_TYPE (&dfsch_error_type)
Definition at line 47 of file conditions.h.
Referenced by dfsch__conditions_register(), dfsch_cerror(), DFSCH_DEFINE_PRIMITIVE(), dfsch_error(), and dfsch_signal().
#define DFSCH_OPERATING_SYSTEM_ERROR_TYPE (&dfsch_operating_system_error_type)
Definition at line 86 of file conditions.h.
Referenced by dfsch__conditions_register(), and dfsch_operating_system_error_saved().
#define DFSCH_RESTART_TYPE (&dfsch_restart_type)
Definition at line 64 of file conditions.h.
Referenced by dfsch_invoke_restart(), dfsch_make_restart(), dfsch_restart_description(), dfsch_restart_name(), and dfsch_restart_proc().
#define DFSCH_RUNTIME_ERROR_TYPE (&dfsch_runtime_error_type)
Definition at line 50 of file conditions.h.
Referenced by dfsch__conditions_register(), and DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_TYPE_ERROR_TYPE (&dfsch_type_error_type)
Definition at line 81 of file conditions.h.
Referenced by dfsch__conditions_register(), and dfsch_type_error().
#define DFSCH_WARNING_TYPE (&dfsch_warning_type)
Definition at line 44 of file conditions.h.
Referenced by dfsch__conditions_register(), and DFSCH_DEFINE_PRIMITIVE().
Function Documentation
char* dfsch__condition_write (dfsch__condition_t * c, int depth, int readable)
dfsch_object_t* dfsch_compute_restarts ()
Definition at line 295 of file conditions.c.
References dfsch__get_thread_info(), dfsch_cons(), DFSCH_FAST_CDR_MUT, dfsch__restart_list_t::next, dfsch__restart_list_t::restart, and dfsch__thread_info_t::restart_list.
Referenced by debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  dfsch__restart_list_t* i = ti->restart_list;
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  while (i){
    dfsch_object_t* tmp = dfsch_cons(i->restart, NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    } else {
      head = tail = tmp;
    }
    i = i->next;
  }
  return head;
}
dfsch_object_t* dfsch_condition (dfsch_type_t * type, ...)
Definition at line 86 of file conditions.c.
References dfsch_condition_put_field_cstr(), and dfsch_make_condition().
Referenced by dfsch_cerror(), and dfsch_error().
{
  va_list al;
  dfsch_object_t* c = dfsch_make_condition(type);
  char* name;
  va_start(al, type);
  while (name = va_arg(al, char*)){
    dfsch_condition_put_field_cstr(c, name, va_arg(al, dfsch_object_t*));
  }
  va_end(al);
  return c;
}
dfsch_object_t* dfsch_condition_field (dfsch_object_t * condition, dfsch_object_t * name)
Definition at line 51 of file conditions.c.
References dfsch_assert_instance(), dfsch_assq(), dfsch_cdr(), DFSCH_CONDITION_TYPE, and dfsch__condition_t::fields.
Referenced by dfsch_condition_field_cstr(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* al;
  dfsch__condition_t* c = dfsch_assert_instance(condition,
                                                DFSCH_CONDITION_TYPE);
  al = dfsch_assq(name, c->fields);
  if (!al){
    return NULL;
  } else {
    return dfsch_cdr(al);
  }
}
dfsch_object_t* dfsch_condition_field_cstr (dfsch_object_t * condition, char * name)
Definition at line 71 of file conditions.c.
References dfsch_condition_field(), and dfsch_make_symbol().
Referenced by debug_main().
{
  return dfsch_condition_field(condition, dfsch_make_symbol(name));
}
dfsch_object_t* dfsch_condition_fields (dfsch_object_t * condition)
Definition at line 80 of file conditions.c.
References dfsch_assert_instance(), and DFSCH_CONDITION_TYPE.
Referenced by debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  return ((dfsch__condition_t*)
          dfsch_assert_instance(condition,
                                DFSCH_CONDITION_TYPE))->fields;
}
void dfsch_condition_put_field (dfsch_object_t * condition, dfsch_object_t * name, dfsch_object_t * value)
Definition at line 63 of file conditions.c.
References dfsch_assert_instance(), DFSCH_CONDITION_TYPE, dfsch_cons(), and dfsch__condition_t::fields.
Referenced by dfsch_condition_put_field_cstr(), dfsch_condition_with_fields(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch__condition_t* c = dfsch_assert_instance(condition,
                                                DFSCH_CONDITION_TYPE);
  c->fields = dfsch_cons(dfsch_cons(name, value), c->fields);
}
void dfsch_condition_put_field_cstr (dfsch_object_t * condition, char * name, dfsch_object_t * value)
Definition at line 75 of file conditions.c.
References dfsch_condition_put_field(), and dfsch_make_symbol().
Referenced by dfsch_condition(), dfsch_condition_with_fields(), dfsch_operating_system_error_saved(), dfsch_signal_condition(), and dfsch_type_error().
{
  return dfsch_condition_put_field(condition, dfsch_make_symbol(name), value);
}
dfsch_object_t* dfsch_condition_with_fields (dfsch_type_t * type, dfsch_object_t * message, dfsch_object_t * fields)
Definition at line 118 of file conditions.c.
References dfsch_condition_put_field(), dfsch_condition_put_field_cstr(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_condition(), and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* c = dfsch_make_condition(type);
  dfsch_object_t* name;
  dfsch_object_t* value;
  dfsch_condition_put_field_cstr(c, "message", message);
  while (DFSCH_PAIR_P(fields)){
    name = DFSCH_FAST_CAR(fields);
    fields = DFSCH_FAST_CDR(fields);
    if (!DFSCH_PAIR_P(fields)){
      dfsch_error("Missing value for keyword", name);
    }
    value = DFSCH_FAST_CAR(fields);
    fields = DFSCH_FAST_CDR(fields);
    dfsch_condition_put_field(c, name, value);
  }
  return c;
}
void dfsch_enter_debugger (dfsch_object_t * reason)
Definition at line 207 of file conditions.c.
References dfsch_apply(), dfsch_cons(), DFSCH_PROTECT, DFSCH_PROTECT_END, and DFSCH_UNWIND.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_signal().
{
  pthread_mutex_lock(&debugger_depth_mutex);
  if (debugger_depth > max_debugger_recursion){
    pthread_mutex_unlock(&debugger_depth_mutex);
    fputs("Debugger recursion limit exceeded!\n\n", stderr);
    return;
  }
  debugger_depth++;
  pthread_mutex_unlock(&debugger_depth_mutex);
  DFSCH_UNWIND {
    if (debugger_proc){
      dfsch_apply(debugger_proc, dfsch_cons(reason, NULL));
    }
  } DFSCH_PROTECT {
    pthread_mutex_lock(&debugger_depth_mutex);
    debugger_depth--;
    pthread_mutex_unlock(&debugger_depth_mutex);
  } DFSCH_PROTECT_END;
}
int dfsch_get_debugger_depth ()
Definition at line 228 of file conditions.c.
Referenced by debug_main().
{
  int r;
  pthread_mutex_lock(&debugger_depth_mutex);
  r = debugger_depth;
  pthread_mutex_unlock(&debugger_depth_mutex);
  return r;
}
void dfsch_handler_bind (dfsch_type_t * type, dfsch_object_t * handler)
Definition at line 283 of file conditions.c.
References dfsch__get_thread_info(), dfsch__handler_list_t::handler, dfsch__thread_info_t::handler_list, dfsch__handler_list_t::next, and dfsch__handler_list_t::type.
Referenced by dfsch_debug_register_handler(), and DFSCH_DEFINE_FORM_IMPL().
{
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  dfsch__handler_list_t* l = GC_NEW(dfsch__handler_list_t);
  l->next = ti->handler_list;
  l->type = type;
  l->handler = handler;
  ti->handler_list = l;
}
dfsch_object_t* dfsch_invoke_restart (dfsch_object_t * restart, dfsch_object_t * args)
Definition at line 315 of file conditions.c.
References dfsch__get_thread_info(), dfsch_apply(), dfsch_error(), dfsch_restart_name(), dfsch_restart_proc(), DFSCH_RESTART_TYPE, DFSCH_TYPE_OF, dfsch__restart_list_t::next, dfsch__restart_list_t::restart, and dfsch__thread_info_t::restart_list.
Referenced by debug_invoke_restart(), debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(restart) != DFSCH_RESTART_TYPE){
    dfsch__thread_info_t* ti = dfsch__get_thread_info();
    dfsch__restart_list_t* i = ti->restart_list;
    while (i){
      if (dfsch_restart_name(i->restart) == restart){
        break;
      }
      i = i->next;
    }
    if (!i){
      dfsch_error("No such restart", restart);
    }
    restart = i->restart;
  }
  return dfsch_apply(dfsch_restart_proc(restart), args);
}
dfsch_object_t* dfsch_make_condition (dfsch_type_t * type)
Definition at line 8 of file conditions.c.
References DFSCH_CONDITION_TYPE, dfsch_error(), DFSCH_INSTANCE_P, dfsch_make_object(), DFSCH_STANDARD_TYPE, dfsch_superclass_p(), and dfsch__condition_t::fields.
Referenced by dfsch_condition(), dfsch_condition_with_fields(), DFSCH_DEFINE_PRIMITIVE(), dfsch_operating_system_error_saved(), dfsch_signal_condition(), and dfsch_type_error().
{
  dfsch__condition_t* c;
  if (!DFSCH_INSTANCE_P(type, DFSCH_STANDARD_TYPE) ||
      !dfsch_superclass_p(type, DFSCH_CONDITION_TYPE)){
    dfsch_error("Not a condition type", (dfsch_object_t*)type);
  }
  c = (dfsch__condition_t*)dfsch_make_object(type);
  c->fields = NULL;
  return (dfsch_object_t*)c;
}
dfsch_object_t* dfsch_make_restart (dfsch_object_t * name, dfsch_object_t * proc, char * description, char * args_description)
Definition at line 251 of file conditions.c.
References restart_t::arg_descriptions, restart_t::description, dfsch_make_object(), DFSCH_RESTART_TYPE, restart_t::name, and restart_t::proc.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and main().
{
  restart_t* r = (restart_t*) dfsch_make_object(DFSCH_RESTART_TYPE);
  r->name = name;
  r->proc = proc;
  r->description = description;
  r->arg_descriptions = arg_descriptions;
  return (dfsch_object_t*) r;
}
dfsch_object_t* dfsch_make_throw_proc (dfsch_object_t * catch_tag)
Definition at line 343 of file conditions.c.
References dfsch_make_primitive(), and throw_proc().
{
  return dfsch_make_primitive(throw_proc, catch_tag);
}
dfsch_object_t* dfsch_make_throw_proc_arg (dfsch_object_t * catch_tag)
Definition at line 355 of file conditions.c.
References dfsch_make_primitive(), and throw_proc_arg().
{
  return dfsch_make_primitive(throw_proc_arg, catch_tag);
}
void dfsch_operating_system_error (char * funname)
Definition at line 393 of file conditions.c.
References dfsch_operating_system_error_saved().
Referenced by dfsch_open_file_port(), dfsch_read_scm(), dfsch_read_scm_fd(), dfsch_unix_opendir(), dfsch_unix_readdir(), file_port_read_buf(), file_port_seek(), file_port_tell(), file_port_write_buf(), native_access(), native_chdir(), native_chmod(), native_chown(), native_close(), native_creat(), native_dup(), native_dup2(), native_fchdir(), native_fchmod(), native_fchown(), native_fork(), native_fstat(), native_getpgid(), native_isatty(), native_kill(), native_killpg(), native_link(), native_lseek(), native_lstat(), native_mkdir(), native_mkfifo(), native_nice(), native_open(), native_pipe(), native_raise(), native_read(), native_rename(), native_rmdir(), native_setegid(), native_seteuid(), native_setgid(), native_setpgid(), native_setpgrp(), native_setsid(), native_setuid(), native_stat(), native_symlink(), native_unlink(), native_wait(), native_waitpid(), and native_write().
{
  dfsch_operating_system_error_saved(errno, funname);
}
void dfsch_operating_system_error_saved (int e, char * funname)
Definition at line 383 of file conditions.c.
References dfsch_condition_put_field_cstr(), dfsch_make_condition(), DFSCH_MAKE_FIXNUM, dfsch_make_string_cstr(), DFSCH_OPERATING_SYSTEM_ERROR_TYPE, and dfsch_signal().
Referenced by dfsch_operating_system_error(), and native_getcwd().
{
  dfsch_object_t* c = dfsch_make_condition(DFSCH_OPERATING_SYSTEM_ERROR_TYPE);
  char* m = strerror(e);
  dfsch_condition_put_field_cstr(c, "errno", DFSCH_MAKE_FIXNUM(e));
  dfsch_condition_put_field_cstr(c, "function",
                                 dfsch_make_string_cstr(funname));
  dfsch_condition_put_field_cstr(c, "message", dfsch_make_string_cstr(m));
  dfsch_signal(c);
}
void dfsch_restart_bind (dfsch_object_t * restart)
Definition at line 274 of file conditions.c.
References dfsch__get_thread_info(), dfsch__restart_list_t::next, dfsch__restart_list_t::restart, and dfsch__thread_info_t::restart_list.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and main().
{
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  dfsch__restart_list_t* l = GC_NEW(dfsch__restart_list_t);
  l->next = ti->restart_list;
  l->restart = restart;
  ti->restart_list = l;
}
char* dfsch_restart_description (dfsch_object_t * restart)
Definition at line 270 of file conditions.c.
References dfsch_assert_type(), and DFSCH_RESTART_TYPE.
Referenced by debug_main(), and DFSCH_DEFINE_PRIMITIVE().
{
  return ((restart_t*)dfsch_assert_type(restart, DFSCH_RESTART_TYPE))->description;
}
dfsch_object_t* dfsch_restart_name (dfsch_object_t * restart)
Definition at line 264 of file conditions.c.
References dfsch_assert_type(), and DFSCH_RESTART_TYPE.
Referenced by debug_main(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_invoke_restart().
{
  return ((restart_t*)dfsch_assert_type(restart, DFSCH_RESTART_TYPE))->name;
}
dfsch_object_t* dfsch_restart_proc (dfsch_object_t * restart)
Definition at line 267 of file conditions.c.
References dfsch_assert_type(), and DFSCH_RESTART_TYPE.
Referenced by dfsch_invoke_restart().
{
  return ((restart_t*)dfsch_assert_type(restart, DFSCH_RESTART_TYPE))->proc;
}
void dfsch_set_debugger (dfsch_object_t * proc)
Definition at line 197 of file conditions.c.
Referenced by dfsch_cdebug_set_as_debugger(), and DFSCH_DEFINE_PRIMITIVE().
{
  debugger_proc = proc;
}
void dfsch_set_invoke_debugger_on_all_conditions (int val)
Definition at line 200 of file conditions.c.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  invoke_debugger_on_all_conditions = val;
}
void dfsch_signal (dfsch_object_t * condition)
Definition at line 163 of file conditions.c.
References dfsch__get_thread_info(), dfsch_apply(), dfsch_cons(), dfsch_enter_debugger(), DFSCH_ERROR_TYPE, DFSCH_INSTANCE_P, dfsch_object_2_string(), dfsch_print_trace_buffer(), dfsch__handler_list_t::handler, dfsch__thread_info_t::handler_list, dfsch__handler_list_t::next, and dfsch__handler_list_t::type.
Referenced by dfsch_cerror(), DFSCH_DEFINE_PRIMITIVE(), dfsch_error(), dfsch_operating_system_error_saved(), dfsch_signal_condition(), and dfsch_type_error().
{
  dfsch__handler_list_t* save;
  dfsch__handler_list_t* i;
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  i = save = ti->handler_list;
  while (i){
    if (DFSCH_INSTANCE_P(condition, i->type)){
      ti->handler_list = i->next;
      dfsch_apply(i->handler, dfsch_cons(condition, NULL));
    }
    i = i->next;
  }
  if (DFSCH_INSTANCE_P(condition, DFSCH_ERROR_TYPE)){
    dfsch_enter_debugger(condition);
    fputs("Unhandled error condition!\n\n", stderr);
    fprintf(stderr, "%s\n", dfsch_object_2_string(condition, 10, 1));
    dfsch_print_trace_buffer();
    abort();
  } else if (invoke_debugger_on_all_conditions){
    dfsch_enter_debugger(condition);
  }
  ti->handler_list = save;
}
void dfsch_signal_condition (dfsch_type_t * type, char * message, ...)
Definition at line 99 of file conditions.c.
References dfsch_condition_put_field_cstr(), dfsch_make_condition(), dfsch_make_string_cstr(), and dfsch_signal().
Referenced by dfsch_cmdopts_parse(), find_long_opt(), find_short_opt(), and get_argument().
{
  va_list al;
  dfsch_object_t* c = dfsch_make_condition(type);
  char* name;
  va_start(al, type);
  while (name = va_arg(al, char*)){
    dfsch_condition_put_field_cstr(c, name, va_arg(al, dfsch_object_t*));
  }
  va_end(al);
  dfsch_condition_put_field_cstr(c, "message",
                                 dfsch_make_string_cstr(message));
  dfsch_signal(c);
}
void dfsch_type_error (dfsch_object_t * datum, dfsch_type_t * type, int instance_suffices)
Definition at line 359 of file conditions.c.
References dfsch_bool(), dfsch_condition_put_field_cstr(), dfsch_make_condition(), dfsch_make_string_cstr(), dfsch_object_2_string(), dfsch_saprintf(), dfsch_signal(), and DFSCH_TYPE_ERROR_TYPE.
Referenced by dfsch_append(), dfsch_assert_instance(), dfsch_assert_type(), dfsch_list_copy(), dfsch_list_length_check(), dfsch_member(), dfsch_memq(), dfsch_memv(), dfsch_reverse(), and dfsch_zip().
{
  char* m;
  dfsch_object_t* c = dfsch_make_condition(DFSCH_TYPE_ERROR_TYPE);
  dfsch_condition_put_field_cstr(c, "datum", datum);
  dfsch_condition_put_field_cstr(c, "type", type);
  dfsch_condition_put_field_cstr(c, "instance-suffices?",
                                 dfsch_bool(instance_suffices));
  if (instance_suffices){
    m = dfsch_saprintf("%s is not an instance of %s",
                       dfsch_object_2_string(datum, 10, 1),
                       dfsch_object_2_string((dfsch_object_t*)type, 10, 1));
  } else {
    m = dfsch_saprintf("%s is not of type %s",
                       dfsch_object_2_string(datum, 10, 1),
                       dfsch_object_2_string((dfsch_object_t*)type, 10, 1));
  }
  dfsch_condition_put_field_cstr(c, "message", dfsch_make_string_cstr(m));
  dfsch_signal(c);
}
Variable Documentation
dfsch_type_t dfsch_condition_type
Definition at line 140 of file conditions.c.
dfsch_type_t dfsch_error_type
Definition at line 152 of file conditions.c.
dfsch_type_t dfsch_operating_system_error_type
Definition at line 380 of file conditions.c.
dfsch_type_t dfsch_restart_type
Definition at line 245 of file conditions.c.
dfsch_type_t dfsch_runtime_error_type
Definition at line 158 of file conditions.c.
dfsch_type_t dfsch_type_error_type
Definition at line 155 of file conditions.c.
dfsch_type_t dfsch_warning_type
Definition at line 149 of file conditions.c.