dfsch: lib/console_mod.c File Reference
lib/console_mod.c File Reference
#include "dfsch/lib/console.h"
#include <dfsch/dfsch.h>
#include <dfsch/strings.h>
Functions
DFSCH_DEFINE_PRIMITIVE (read_object, 0)
DFSCH_DEFINE_PRIMITIVE (read_line, 0)
dfsch_object_t * dfsch_module_console_register (dfsch_object_t *env)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (read_object , 0)
Definition at line 12 of file console_mod.c.
References DFSCH_ARG_END, dfsch_console_read_object(), and DFSCH_STRING_ARG_OPT.
{
  char* prompt;
  DFSCH_STRING_ARG_OPT(args, prompt, "> ");
  DFSCH_ARG_END(args);
  return dfsch_console_read_object(prompt);
}
DFSCH_DEFINE_PRIMITIVE (read_line , 0)
Definition at line 5 of file console_mod.c.
References DFSCH_ARG_END, dfsch_console_read_line(), dfsch_make_string_cstr(), and DFSCH_STRING_ARG_OPT.
{
  char* prompt;
  DFSCH_STRING_ARG_OPT(args, prompt, "> ");
  DFSCH_ARG_END(args);
  return dfsch_make_string_cstr(dfsch_console_read_line(prompt));
}
dfsch_object_t* dfsch_module_console_register (dfsch_object_t * env)
Definition at line 20 of file console_mod.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "console");
  dfsch_define_cstr(env, "console:read-line", DFSCH_PRIMITIVE_REF(read_line));
  dfsch_define_cstr(env, "console:read-object", DFSCH_PRIMITIVE_REF(read_object));
  return env;
}