dfsch: lib/console.c File Reference
lib/console.c File Reference
#include "dfsch/lib/console.h"
#include <dfsch/util.h>
#include <dfsch/parse.h>
#include <dfsch/ports.h>
#include <dfsch/magic.h>
Typedefs
typedef void(* sighandler_t)(int)
Functions
char * dfsch_console_read_line (char *prompt)
char * dfsch_console_read_line_object (char *prompt)
dfsch_object_t * dfsch_console_read_object (char *prompt)
int dfsch_console_read_objects (char *prompt, dfsch_console_object_cb_t cb, void *baton)
int dfsch_console_read_objects_list (char *prompt, dfsch_console_object_cb_t cb, void *baton)
int dfsch_console_read_objects_list_parser (char *prompt, dfsch_parser_ctx_t *parser)
int dfsch_console_read_objects_parser (char *prompt, dfsch_parser_ctx_t *parser)
int dfsch_console_run_repl (char *prompt, dfsch_object_t *env)
void dfsch_console_set_general_completion ()
void dfsch_console_set_object_completion ()
static char * get_prompt (dfsch_parser_ctx_t *parser, char *dprompt)
static int read_callback (dfsch_object_t *obj, dfsch_object_t **res)
static int repl_callback (dfsch_object_t *obj, void *baton)
Variables
static dfsch_parser_ctx_t *volatile running_parser = NULL
static char *volatile running_prompt = NULL
Typedef Documentation
typedef void(* sighandler_t)(int)
Definition at line 17 of file console.c.
Function Documentation
char* dfsch_console_read_line (char * prompt)
Definition at line 53 of file console.c.
Referenced by dfsch_console_read_line_object(), and DFSCH_DEFINE_PRIMITIVE().
{
  char* ret;
  char* tmp;
  size_t allocd;
  size_t offset;
  size_t i;
  ret = GC_MALLOC(512);
  allocd = 512;
  offset = 0;
  fputs(prompt, stdout);
  while (1){
    if(!fgets(ret + offset, allocd - offset, stdin)){
      return NULL;
    }
    offset += strlen(ret + offset);
    if (offset == 0){  /* nothing */
        return ret;
    }
    if (ret[offset-1] == '\n') {   /* full line */
      ret[offset-1] = '\0';
      return ret;
    }
    allocd += 512;
    ret = GC_REALLOC(ret, allocd);
  }
}
char* dfsch_console_read_line_object (char * prompt)
Definition at line 132 of file console.c.
References dfsch_console_read_line(), dfsch_console_set_general_completion(), and dfsch_console_set_object_completion().
Referenced by dfsch_console_read_object(), and dfsch_console_read_objects_parser().
{
  char* line;
  dfsch_console_set_object_completion();
  line = dfsch_console_read_line(prompt);
  dfsch_console_set_general_completion();
  return line;
}
dfsch_object_t* dfsch_console_read_object (char * prompt)
Definition at line 169 of file console.c.
References dfsch_console_read_line_object(), dfsch_eof_object(), dfsch_error(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_feed_line(), dfsch_parser_top_level(), get_prompt(), parser, read_callback(), and running_prompt.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_parser_ctx_t* parser = dfsch_parser_create();
  char* line;
  dfsch_object_t* obj;
  dfsch_parser_callback(parser, read_callback, &obj);
  running_prompt = prompt;
  running_parser = parser;
  while (line = dfsch_console_read_line_object(get_prompt(parser, prompt))){
    if (dfsch_parser_feed_line(parser, line)){
      running_parser = NULL;
      running_prompt = NULL;
      return obj;
    }
  }
  running_parser = NULL;
  running_prompt = NULL;
  if (dfsch_parser_top_level(parser)){
    return dfsch_eof_object();
  } else {
    dfsch_error("Unexpected end of input", NULL);
  }
}
int dfsch_console_read_objects (char * prompt, dfsch_console_object_cb_t cb, void * baton)
Definition at line 224 of file console.c.
References dfsch_console_read_objects_parser(), dfsch_make_symbol(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_set_source(), and parser.
Referenced by dfsch_console_run_repl().
{
  dfsch_parser_ctx_t* parser = dfsch_parser_create();
  dfsch_parser_set_source(parser, dfsch_make_symbol("*console-io*"));
  dfsch_parser_callback(parser, cb, baton);
  return dfsch_console_read_objects_parser(prompt, parser);
}
int dfsch_console_read_objects_list (char * prompt, dfsch_console_object_cb_t cb, void * baton)
Definition at line 232 of file console.c.
{
}
int dfsch_console_read_objects_list_parser (char * prompt, dfsch_parser_ctx_t * parser)
Definition at line 218 of file console.c.
{
}
int dfsch_console_read_objects_parser (char * prompt, dfsch_parser_ctx_t * parser)
Definition at line 195 of file console.c.
References dfsch_console_read_line_object(), DFSCH_END_WITH_SIMPLE_RESTART, dfsch_make_symbol(), dfsch_parser_feed_line(), DFSCH_PROTECT, DFSCH_PROTECT_END, DFSCH_UNWIND, DFSCH_WITH_SIMPLE_RESTART, get_prompt(), and running_prompt.
Referenced by dfsch_console_read_objects().
{
  int ret;
  char* line;
  running_prompt = prompt;
  __asm(";;");
  running_parser = parser;
  DFSCH_UNWIND {
    while (line = dfsch_console_read_line_object(get_prompt(parser, prompt))){
      DFSCH_WITH_SIMPLE_RESTART(dfsch_make_symbol("abort"), "Return to reader"){
        ret = dfsch_parser_feed_line(parser, line);
      }DFSCH_END_WITH_SIMPLE_RESTART;
      if (ret){
        break;
      }
    }
  } DFSCH_PROTECT {
    running_parser = NULL;
    running_prompt = NULL;
  } DFSCH_PROTECT_END;
  return ret;
}
int dfsch_console_run_repl (char * prompt, dfsch_object_t * env)
Definition at line 243 of file console.c.
References dfsch_console_read_objects(), and repl_callback().
Referenced by debug_main(), and interactive_repl().
{
  return dfsch_console_read_objects(prompt, repl_callback, env);
}
void dfsch_console_set_general_completion ()
Definition at line 128 of file console.c.
Referenced by dfsch_console_read_line_object().
{
}
void dfsch_console_set_object_completion ()
Definition at line 126 of file console.c.
Referenced by dfsch_console_read_line_object().
{
}
static char* get_prompt (dfsch_parser_ctx_t * parser, char * dprompt) [static]
Definition at line 145 of file console.c.
References dfsch_parser_get_level().
Referenced by dfsch_console_read_object(), and dfsch_console_read_objects_parser().
{
  int level = dfsch_parser_get_level(parser);
  if (level){
    char *prompt;
    int fill;
    if (strlen(dprompt) < 2){
      fill = level*2;
    } else {
      fill = level*2 + (strlen(dprompt) - 4);
      /* minimal fill is 0, minimal level 1, thus 1 * 2 + (2 - 4) = 0 */
    }
    prompt = GC_MALLOC_ATOMIC(fill+5);
    memset(prompt, ' ', fill);
    prompt[fill+0] = '.';
    prompt[fill+1] = '.';
    prompt[fill+2] = '>';
    prompt[fill+3] = ' ';
    prompt[fill+4] = 0;
    return prompt;
  }else{
    return dprompt;
  }
}
static int read_callback (dfsch_object_t * obj, dfsch_object_t ** res) [static]
Definition at line 140 of file console.c.
Referenced by dfsch_console_read_object().
{
  *res = obj;
  return 0;
}
static int repl_callback (dfsch_object_t * obj, void * baton) [static]
Definition at line 237 of file console.c.
References dfsch_eval(), and dfsch_object_2_string().
Referenced by dfsch_console_run_repl().
{
  dfsch_object_t* ret;
  ret = dfsch_eval(obj, baton);
  puts(dfsch_object_2_string(ret,100,1));
}
Variable Documentation
dfsch_parser_ctx_t* volatile running_parser = NULL [static]
Definition at line 19 of file console.c.
char* volatile running_prompt = NULL [static]
Definition at line 20 of file console.c.
Referenced by dfsch_console_read_object(), and dfsch_console_read_objects_parser().