dfsch: src/control.c File Reference
src/control.c File Reference
#include "internal.h"
#include <dfsch/promise.h>
#include <dfsch/magic.h>
#include "util.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>
#include <dfsch/number.h>
Typedefs
typedef dfsch_object_t object_t
Functions
void dfsch__control_register (dfsch_object_t *ctx)
DFSCH_DEFINE_FORM_IMPL (destructuring_bind, NULL)
DFSCH_DEFINE_FORM_IMPL (dolist,"Iterate over list contents")
DFSCH_DEFINE_FORM_IMPL (do,"Iterative loop")
DFSCH_DEFINE_FORM_IMPL (catch, NULL)
DFSCH_DEFINE_FORM_IMPL (unwind_protect, NULL)
DFSCH_DEFINE_FORM_IMPL (let_seq, NULL)
DFSCH_DEFINE_FORM_IMPL (letrec, NULL)
DFSCH_DEFINE_FORM_IMPL (let, NULL)
DFSCH_DEFINE_FORM_IMPL (begin, NULL)
DFSCH_DEFINE_FORM_IMPL (quasiquote, NULL)
DFSCH_DEFINE_FORM_IMPL (quote, NULL)
DFSCH_DEFINE_FORM_IMPL (case, NULL)
DFSCH_DEFINE_FORM_IMPL (cond, NULL)
DFSCH_DEFINE_FORM_IMPL (unless,"Execute body only when condition is not true")
DFSCH_DEFINE_FORM_IMPL (when,"Execute body only when condition is true")
DFSCH_DEFINE_FORM_IMPL (if,"Conditional operator")
DFSCH_DEFINE_PRIMITIVE (throw, 0)
static object_t * native_apply (void *baton, object_t *args, dfsch_tail_escape_t *esc)
static object_t * native_eval (void *baton, object_t *args, dfsch_tail_escape_t *esc)
static object_t * native_eval_proc (void *baton, object_t *args, dfsch_tail_escape_t *esc)
Typedef Documentation
typedef dfsch_object_t object_t
Definition at line 39 of file control.c.
Function Documentation
void dfsch__control_register (dfsch_object_t * ctx)
Definition at line 454 of file control.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, native_apply(), native_eval(), and native_eval_proc().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "begin", DFSCH_FORM_REF(begin));
  dfsch_define_cstr(ctx, "let", DFSCH_FORM_REF(let));
  dfsch_define_cstr(ctx, "let*", DFSCH_FORM_REF(let_seq));
  dfsch_define_cstr(ctx, "letrec", DFSCH_FORM_REF(letrec));
  dfsch_define_cstr(ctx, "quasiquote", DFSCH_FORM_REF(quasiquote));
  dfsch_define_cstr(ctx, "quote", DFSCH_FORM_REF(quote));
  dfsch_define_cstr(ctx, "if", DFSCH_FORM_REF(if));
  dfsch_define_cstr(ctx, "when", DFSCH_FORM_REF(when));
  dfsch_define_cstr(ctx, "unless", DFSCH_FORM_REF(unless));
  dfsch_define_cstr(ctx, "cond", DFSCH_FORM_REF(cond));
  dfsch_define_cstr(ctx, "case", DFSCH_FORM_REF(case));
  dfsch_define_cstr(ctx, "unwind-protect", DFSCH_FORM_REF(unwind_protect));
  dfsch_define_cstr(ctx, "catch", DFSCH_FORM_REF(catch));
  dfsch_define_cstr(ctx, "throw", DFSCH_PRIMITIVE_REF(throw));
  dfsch_define_cstr(ctx, "eval", dfsch_make_primitive(&native_eval,NULL));
  dfsch_define_cstr(ctx, "eval-proc", dfsch_make_primitive(&native_eval_proc,
                                                          NULL));
  dfsch_define_cstr(ctx, "apply", dfsch_make_primitive(&native_apply,NULL));
  dfsch_define_cstr(ctx, "do", DFSCH_FORM_REF(do));
  dfsch_define_cstr(ctx, "dolist", DFSCH_FORM_REF(dolist));
  dfsch_define_cstr(ctx, "destructuring-bind",
                    DFSCH_FORM_REF(destructuring_bind));
}
DFSCH_DEFINE_FORM_IMPL (destructuring_bind , NULL)
Definition at line 432 of file control.c.
References DFSCH_ARG_REST, dfsch_destructuring_bind(), dfsch_eval(), dfsch_eval_proc_tr(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t *arglist;
  dfsch_object_t *list;
  dfsch_object_t *code;
  DFSCH_OBJECT_ARG(args, arglist);
  DFSCH_OBJECT_ARG(args, list);
  DFSCH_ARG_REST(args, code);
  list = dfsch_eval(list, env);
  return dfsch_eval_proc_tr(code,
                            dfsch_destructuring_bind(arglist,
                                                     list,
                                                     env),
                            esc);
}
DFSCH_DEFINE_FORM_IMPL (dolist , "Iterate over list contents")
Definition at line 404 of file control.c.
References DFSCH_ARG_REST, dfsch_cerror(), dfsch_define(), dfsch_eval(), dfsch_eval_proc(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_new_frame(), DFSCH_OBJECT_ARG, and DFSCH_PAIR_P.
{
  dfsch_object_t* farg;
  dfsch_object_t* variable;
  dfsch_object_t* list;
  dfsch_object_t* body;
  dfsch_object_t* result = NULL;
  DFSCH_OBJECT_ARG(args, farg);
  DFSCH_OBJECT_ARG(farg, variable);
  DFSCH_OBJECT_ARG(farg, list);
  DFSCH_ARG_REST(args, body);
  list = dfsch_eval(list, env);
  while (DFSCH_PAIR_P(list)){
    dfsch_object_t* inner_env = dfsch_new_frame(env);
    dfsch_define(variable, DFSCH_FAST_CAR(list), inner_env);
    result = dfsch_eval_proc(body, inner_env);
    list = DFSCH_FAST_CDR(list);
  }
  if (list){
    dfsch_cerror("Not a proper list", list);
  }
  return result;
}
DFSCH_DEFINE_FORM_IMPL (do , "Iterative loop")
Definition at line 346 of file control.c.
References dfsch_car(), dfsch_cdr(), dfsch_define(), dfsch_eval(), dfsch_eval_proc(), dfsch_eval_proc_tr(), dfsch_new_frame(), DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, and dfsch_pair_p().
{
  object_t* vars;
  object_t* test;
  object_t* exprs;
  object_t* commands;
  object_t* lenv;
  object_t* i;
  DFSCH_OBJECT_ARG(args, vars);
  DFSCH_OBJECT_ARG(args, test);
  commands = args;
  exprs = dfsch_cdr(test);
  test = dfsch_car(test);
  lenv = dfsch_new_frame(env);
  i = vars;
  while (dfsch_pair_p(i)){
    object_t* j = dfsch_car(i);
    object_t* name;
    object_t* init;
    object_t* step;
    DFSCH_OBJECT_ARG(j, name);
    DFSCH_OBJECT_ARG(j, init);
    dfsch_define(name, dfsch_eval(init, env), lenv);
    i = dfsch_cdr(i);
  }
  while (dfsch_eval(test, lenv) == NULL){
    object_t* nenv;
    dfsch_eval_proc(commands, lenv);
    nenv = dfsch_new_frame(env);
    i = vars;
    while (dfsch_pair_p(i)){
      object_t* j = dfsch_car(i);
      object_t* name;
      object_t* init;
      object_t* step;
      DFSCH_OBJECT_ARG(j, name);
      DFSCH_OBJECT_ARG(j, init);
      DFSCH_OBJECT_ARG_OPT(j, step, name);
      dfsch_define(name, dfsch_eval(step, lenv), nenv);
      i = dfsch_cdr(i);
    }
    lenv = nenv;
  }
  return dfsch_eval_proc_tr(exprs, lenv, esc);
}
DFSCH_DEFINE_FORM_IMPL (catch , NULL)
Definition at line 313 of file control.c.
References DFSCH_CATCH, DFSCH_CATCH_BEGIN, DFSCH_CATCH_END, DFSCH_CATCH_VALUE, dfsch_eval(), dfsch_eval_proc(), and DFSCH_OBJECT_ARG.
{
  object_t* tag;
  object_t* ret;
  DFSCH_OBJECT_ARG(args, tag);
  tag = dfsch_eval(tag, env);
  DFSCH_CATCH_BEGIN(tag) {
    ret = dfsch_eval_proc(args, env);
  } DFSCH_CATCH {
    ret = DFSCH_CATCH_VALUE;
  } DFSCH_CATCH_END;
  return ret;
}
DFSCH_DEFINE_FORM_IMPL (unwind_protect , NULL)
Definition at line 299 of file control.c.
References dfsch_eval(), dfsch_eval_proc(), DFSCH_OBJECT_ARG, DFSCH_PROTECT, DFSCH_PROTECT_END, and DFSCH_UNWIND.
{
  object_t* protect;
  object_t* ret;
  DFSCH_OBJECT_ARG(args, protect);
  DFSCH_UNWIND {
    dfsch_eval(protect, env);
  } DFSCH_PROTECT {
    ret = dfsch_eval_proc(args, env);
  } DFSCH_PROTECT_END;
  return ret;
}
DFSCH_DEFINE_FORM_IMPL (let_seq , NULL)
Definition at line 229 of file control.c.
References DFSCH_ARG_REST, dfsch_car(), dfsch_cdr(), dfsch_define(), dfsch_eval(), dfsch_eval_proc_tr(), dfsch_list_item(), dfsch_new_frame(), DFSCH_OBJECT_ARG, and dfsch_pair_p().
{
  object_t *vars;
  object_t *code;
  DFSCH_OBJECT_ARG(args, vars);
  DFSCH_ARG_REST(args, code);
  object_t* ext_env = env;
  while (dfsch_pair_p(vars)){
    object_t* var = dfsch_list_item(dfsch_car(vars),0);
    object_t* val = dfsch_eval(dfsch_list_item(dfsch_car(vars),1), ext_env);
    ext_env = dfsch_new_frame(ext_env);
    dfsch_define(var, val, ext_env);
    vars = dfsch_cdr(vars);
  }
  return dfsch_eval_proc_tr(code, ext_env, esc);
}
DFSCH_DEFINE_FORM_IMPL (letrec , NULL)
Definition at line 208 of file control.c.
References DFSCH_ARG_REST, dfsch_car(), dfsch_cdr(), dfsch_define(), dfsch_eval(), dfsch_eval_proc_tr(), dfsch_list_item(), dfsch_new_frame(), DFSCH_OBJECT_ARG, and dfsch_pair_p().
{
  object_t *vars;
  object_t *code;
  DFSCH_OBJECT_ARG(args, vars);
  DFSCH_ARG_REST(args, code);
  object_t* ext_env = dfsch_new_frame(env);
  while (dfsch_pair_p(vars)){
    object_t* var = dfsch_list_item(dfsch_car(vars),0);
    object_t* val = dfsch_eval(dfsch_list_item(dfsch_car(vars),1), ext_env);
    dfsch_define(var, val, ext_env);
    vars = dfsch_cdr(vars);
  }
  return dfsch_eval_proc_tr(code,ext_env, esc);
}
DFSCH_DEFINE_FORM_IMPL (let , NULL)
Definition at line 148 of file control.c.
References dfsch_apply_tr(), DFSCH_ARG_REST, dfsch_car(), dfsch_cdr(), dfsch_cons(), dfsch_define(), dfsch_eval(), dfsch_eval_proc_tr(), dfsch_list_item(), dfsch_named_lambda(), dfsch_new_frame(), DFSCH_OBJECT_ARG, dfsch_pair_p(), dfsch_set_cdr(), and dfsch_symbol_p().
{
  object_t *vars;
  object_t *code;
  DFSCH_OBJECT_ARG(args, vars);
  DFSCH_ARG_REST(args, code);
  object_t* ext_env = dfsch_new_frame(env);
  if (dfsch_symbol_p(vars)){ // named-let
    object_t* name = vars;
    object_t* ll_head = NULL;
    object_t* ll_tail = NULL;
    object_t* vl_head = NULL;
    object_t* vl_tail = NULL;
    object_t* lambda;
    DFSCH_OBJECT_ARG(code, vars);
    while (dfsch_pair_p(vars)){
      object_t* var = dfsch_list_item(dfsch_car(vars),0);
      object_t* val = dfsch_eval(dfsch_list_item(dfsch_car(vars),1), env);
      if (ll_head && vl_head){
        object_t* tmp;
        tmp = dfsch_cons(var, NULL);
        dfsch_set_cdr(ll_tail, tmp);
        ll_tail = tmp;
        tmp = dfsch_cons(val, NULL);
        dfsch_set_cdr(vl_tail, tmp);
        vl_tail = tmp;
      }else{
        ll_head = ll_tail = dfsch_cons(var, NULL);
        vl_head = vl_tail = dfsch_cons(val, NULL);
      }
      vars = dfsch_cdr(vars);
    }
    lambda = dfsch_named_lambda(ext_env, ll_head, code, name);
    dfsch_define(name, lambda, ext_env);
    return dfsch_apply_tr(lambda, vl_head, esc);
  }
  while (dfsch_pair_p(vars)){
    object_t* var = dfsch_list_item(dfsch_car(vars),0);
    object_t* val = dfsch_eval(dfsch_list_item(dfsch_car(vars),1), env);
    dfsch_define(var, val, ext_env);
    vars = dfsch_cdr(vars);
  }
  return dfsch_eval_proc_tr(code,ext_env, esc);
}
DFSCH_DEFINE_FORM_IMPL (begin , NULL)
Definition at line 145 of file control.c.
References dfsch_eval_proc_tr().
{
  return dfsch_eval_proc_tr(args, env, esc);
}
DFSCH_DEFINE_FORM_IMPL (quasiquote , NULL)
Definition at line 136 of file control.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_quasiquote().
{
  /* This is non-trivial to compile right */
  object_t* arg;
  DFSCH_OBJECT_ARG(args, arg);
  DFSCH_ARG_END(args);
  return dfsch_quasiquote(env,arg);
}
DFSCH_DEFINE_FORM_IMPL (quote , NULL)
Definition at line 127 of file control.c.
References DFSCH_ARG_END, and DFSCH_OBJECT_ARG.
{
  object_t* value;
  DFSCH_OBJECT_ARG(args, value);
  DFSCH_ARG_END(args);
  return value;
}
DFSCH_DEFINE_FORM_IMPL (case , NULL)
Definition at line 103 of file control.c.
References dfsch_car(), dfsch_cdr(), dfsch_eqv_p(), dfsch_eval(), dfsch_eval_proc_tr(), DFSCH_OBJECT_ARG, dfsch_pair_p(), and DFSCH_SYM_ELSE.
{
  object_t* val;
  DFSCH_OBJECT_ARG(args, val);
  val = dfsch_eval(val, env);
  while (dfsch_pair_p(args)){
    object_t* c = dfsch_car(args);
    object_t* i = dfsch_car(c);
    if (i == DFSCH_SYM_ELSE)
      return dfsch_eval_proc_tr(dfsch_cdr(c), env, esc);
    while (dfsch_pair_p(i)){
      if (dfsch_eqv_p(dfsch_car(i), val))
        return dfsch_eval_proc_tr(dfsch_cdr(c), env, esc);
      i = dfsch_cdr(i);
    }
    args = dfsch_cdr(args);
  }
  return NULL;
}
DFSCH_DEFINE_FORM_IMPL (cond , NULL)
Definition at line 82 of file control.c.
References dfsch_apply(), dfsch_car(), dfsch_cdr(), dfsch_eval(), dfsch_eval_proc_tr(), dfsch_list(), dfsch_list_item(), dfsch_pair_p(), and DFSCH_SYM_BOLD_RIGHT_ARROW.
{
  object_t* i = args;
  while (dfsch_pair_p(i)){
    object_t *o = dfsch_eval(dfsch_car(dfsch_car(i)), env);
    if (o){
      object_t* exp = dfsch_cdr(dfsch_car(i));
      if (dfsch_car(exp) == DFSCH_SYM_BOLD_RIGHT_ARROW){
        object_t* proc = dfsch_eval(dfsch_list_item(exp, 1), env);
        return dfsch_apply(proc, dfsch_list(1, o));
      }else{
        return dfsch_eval_proc_tr(exp, env, esc);
      }
    }
    i = dfsch_cdr(i);
  }
  return NULL;
}
DFSCH_DEFINE_FORM_IMPL (unless , "Execute body only when condition is not true")
Definition at line 69 of file control.c.
References dfsch_eval(), dfsch_eval_proc_tr(), and DFSCH_OBJECT_ARG.
{
  object_t* test;
  DFSCH_OBJECT_ARG(args,test);
  if (!dfsch_eval(test, env)){
    return dfsch_eval_proc_tr(args, env, esc);
  }
  return NULL;
}
DFSCH_DEFINE_FORM_IMPL (when , "Execute body only when condition is true")
Definition at line 57 of file control.c.
References dfsch_eval(), dfsch_eval_proc_tr(), and DFSCH_OBJECT_ARG.
{
  object_t* test;
  DFSCH_OBJECT_ARG(args,test);
  if (dfsch_eval(test, env)){
    return dfsch_eval_proc_tr(args, env, esc);
  }
  return NULL;
}
DFSCH_DEFINE_FORM_IMPL (if , "Conditional operator")
Definition at line 43 of file control.c.
References dfsch_eval(), dfsch_eval_tr(), DFSCH_OBJECT_ARG, and DFSCH_OBJECT_ARG_OPT.
{
  object_t* test;
  object_t* consequent;
  object_t* alternate;
  DFSCH_OBJECT_ARG(args,test);
  DFSCH_OBJECT_ARG(args,consequent);
  DFSCH_OBJECT_ARG_OPT(args,alternate, NULL);
  test = dfsch_eval(test, env);
  return dfsch_eval_tr((test?consequent:alternate), env, esc);
}
DFSCH_DEFINE_PRIMITIVE (throw , 0)
Definition at line 329 of file control.c.
References DFSCH_OBJECT_ARG, and dfsch_throw().
{
  dfsch_object_t* tag;
  dfsch_object_t* value;
  DFSCH_OBJECT_ARG(args, tag);
  DFSCH_OBJECT_ARG(args, value);
  dfsch_throw(tag, value);
  return NULL;
}
static object_t* native_apply (void * baton, object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 278 of file control.c.
References dfsch_apply_tr(), DFSCH_ARG_END, and DFSCH_OBJECT_ARG.
Referenced by dfsch__control_register().
{
  /* TODO: free arguments */
  object_t* func;
  object_t* arglist;
  DFSCH_OBJECT_ARG(args, func);
  DFSCH_OBJECT_ARG(args, arglist);
  DFSCH_ARG_END(args);
  return dfsch_apply_tr(func, arglist, esc);
}
static object_t* native_eval (void * baton, object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 258 of file control.c.
References DFSCH_ARG_END, dfsch_eval_tr(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__control_register().
{
  object_t* expr;
  object_t* env;
  DFSCH_OBJECT_ARG(args, expr);
  DFSCH_OBJECT_ARG(args, env);
  DFSCH_ARG_END(args);
  return dfsch_eval_tr(expr, env, esc);
}
static object_t* native_eval_proc (void * baton, object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 268 of file control.c.
References DFSCH_ARG_END, dfsch_eval_proc_tr(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__control_register().
{
  object_t* proc;
  object_t* env;
  DFSCH_OBJECT_ARG(args, proc);
  DFSCH_OBJECT_ARG(args, env);
  DFSCH_ARG_END(args);
  return dfsch_eval_proc_tr(proc, env, esc);
}