dfsch: src/debug.c File Reference
src/debug.c File Reference
#include "dfsch/debug.h"
#include <dfsch/dfsch.h>
#include <dfsch/conditions.h>
#include <stdio.h>
Functions
static void debug_main (dfsch_object_t *condition)
void dfsch_debug_register_handler ()
DFSCH_DEFINE_PRIMITIVE (debug_handler, 0)
Function Documentation
static void debug_main (dfsch_object_t * condition) [static]
Definition at line 27 of file debug.c.
References dfsch_compute_restarts(), dfsch_condition_field_cstr(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_invoke_restart(), dfsch_make_symbol(), dfsch_object_2_string(), DFSCH_PAIR_P, dfsch_restart_description(), dfsch_restart_name(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* restarts = dfsch_compute_restarts();
  char buf[512];
  fprintf(stderr, "debugger invoked on %s:\n",
          DFSCH_TYPE_OF(condition)->name);
  fprintf(stderr,"  %s\n",
          dfsch_object_2_string(dfsch_condition_field_cstr(condition,
                                                     "message"),
                          10, 0));
  fprintf(stderr, "\nrestarts:\n");
  while (DFSCH_PAIR_P(restarts)){
    dfsch_object_t* restart = DFSCH_FAST_CAR(restarts);
    fprintf(stderr, "  [%s]: %s\n",
            dfsch_object_2_string(dfsch_restart_name(restart), 1, 1),
            dfsch_restart_description(restart));
    restarts = DFSCH_FAST_CDR(restarts);
  }
  fprintf(stderr, "dbg> ");
  fgets(buf, 512, stdin);
  buf[strlen(buf)-1]='\0';
  dfsch_invoke_restart(dfsch_make_symbol(buf));
}
void dfsch_debug_register_handler ()
Definition at line 65 of file debug.c.
References dfsch_handler_bind(), and DFSCH_PRIMITIVE_REF.
{
  dfsch_handler_bind(NULL, DFSCH_PRIMITIVE_REF(debug_handler));
}
DFSCH_DEFINE_PRIMITIVE (debug_handler , 0)
Definition at line 55 of file debug.c.
References debug_main(), DFSCH_ARG_END, and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* condition;
  DFSCH_OBJECT_ARG(args, condition);
  DFSCH_ARG_END(args);
  debug_main(condition);
  return NULL;
}