dfsch: dfsch/lib/process.h File Reference
dfsch/lib/process.h File Reference
#include <dfsch/dfsch.h>
#include <dfsch/ports.h>
Defines
#define DFSCH_PROCESS_INPUT_PORT_TYPE (&dfsch_process_input_port_type)
#define DFSCH_PROCESS_OUTPUT_PORT_TYPE (&dfsch_process_output_port_type)
#define DFSCH_PROCESS_PORT_TYPE (&dfsch_process_port_type)
Functions
dfsch_object_t * dfsch_module_process_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_process_close_port (dfsch_object_t *port)
dfsch_object_t * dfsch_process_spawn_with_input_port (char *cmd_line)
dfsch_object_t * dfsch_process_spawn_with_output_port (char *cmd_line)
Variables
dfsch_port_type_t dfsch_process_input_port_type
dfsch_port_type_t dfsch_process_output_port_type
dfsch_type_t dfsch_process_port_type
Define Documentation
#define DFSCH_PROCESS_INPUT_PORT_TYPE (&dfsch_process_input_port_type)
Definition at line 37 of file process.h.
Referenced by dfsch_module_process_register(), dfsch_process_spawn_with_input_port(), and spawn_port().
#define DFSCH_PROCESS_OUTPUT_PORT_TYPE (&dfsch_process_output_port_type)
Definition at line 35 of file process.h.
Referenced by dfsch_module_process_register(), and dfsch_process_spawn_with_output_port().
#define DFSCH_PROCESS_PORT_TYPE (&dfsch_process_port_type)
Definition at line 33 of file process.h.
Referenced by dfsch_module_process_register(), and dfsch_process_close_port().
Function Documentation
dfsch_object_t* dfsch_module_process_register (dfsch_object_t * ctx)
Definition at line 63 of file process_mod.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, DFSCH_PROCESS_INPUT_PORT_TYPE, DFSCH_PROCESS_OUTPUT_PORT_TYPE, and DFSCH_PROCESS_PORT_TYPE.
{
  dfsch_define_cstr(ctx, "process:<port>",
                    DFSCH_PROCESS_PORT_TYPE);
  dfsch_define_cstr(ctx, "process:<input-port>",
                    DFSCH_PROCESS_INPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "process:<output-port>",
                    DFSCH_PROCESS_OUTPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "process:spawn!",
                    DFSCH_PRIMITIVE_REF(spawn));
  dfsch_define_cstr(ctx, "process:spawn-with-input-port!",
                    DFSCH_PRIMITIVE_REF(spawn_with_input_port));
  dfsch_define_cstr(ctx, "process:spawn-with-output-port!",
                    DFSCH_PRIMITIVE_REF(spawn_with_output_port));
  dfsch_define_cstr(ctx, "process:close-port!",
                    DFSCH_PRIMITIVE_REF(close_port));
}
dfsch_object_t* dfsch_process_close_port (dfsch_object_t * port)
Definition at line 172 of file process.c.
References DFSCH_ASSERT_INSTANCE, dfsch_error(), DFSCH_MAKE_FIXNUM, dfsch_make_string_cstr(), DFSCH_PROCESS_PORT_TYPE, processs_port_t::file, and processs_port_t::open.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  process_port_t* p = DFSCH_ASSERT_INSTANCE(port, DFSCH_PROCESS_PORT_TYPE);
  int r;
  if (p->open){
    p->open = 0;
    r = pclose(p->file);
    if (r == -1){
      dfsch_error("Error while closing process port",
                  dfsch_make_string_cstr(strerror(errno)));
    }
    return DFSCH_MAKE_FIXNUM(r);
  }
  return NULL;
}
dfsch_object_t* dfsch_process_spawn_with_input_port (char * cmd_line)
Definition at line 165 of file process.c.
References DFSCH_PROCESS_INPUT_PORT_TYPE, and spawn_port().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return spawn_port(DFSCH_PROCESS_INPUT_PORT_TYPE, cmd_line);
}
dfsch_object_t* dfsch_process_spawn_with_output_port (char * cmd_line)
Definition at line 168 of file process.c.
References DFSCH_PROCESS_OUTPUT_PORT_TYPE, and spawn_port().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return spawn_port(DFSCH_PROCESS_OUTPUT_PORT_TYPE, cmd_line);
}
Variable Documentation
dfsch_port_type_t dfsch_process_input_port_type
Definition at line 112 of file process.c.
dfsch_port_type_t dfsch_process_output_port_type
Definition at line 71 of file process.c.
dfsch_type_t dfsch_process_port_type
Definition at line 45 of file process.c.