dfsch: src/dfsch.c File Reference
src/dfsch.c File Reference
#include <dfsch/dfsch.h>
#include <dfsch/hash.h>
#include <dfsch/number.h>
#include <dfsch/parse.h>
#include <dfsch/strings.h>
#include <dfsch/magic.h>
#include <dfsch/conditions.h>
#include <dfsch/introspect.h>
#include <dfsch/weak.h>
#include "util.h"
#include "internal.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdarg.h>
#include "types.h"
Data Structures
struct dfsch_symbol_iter_t
struct dfsch_tail_escape_t
struct hash_entry_t
struct read_ctx_t
Defines
#define FORM (&dfsch_form_type)
#define FUNCTION DFSCH_STANDARD_FUNCTION_TYPE
#define HASH_BITS 10
#define HASH_SIZE (1 << HASH_BITS)
#define INT_ACCESSOR(type, name)
#define MACRO DFSCH_MACRO_TYPE
#define PAIR (&dfsch_pair_type)
#define PRIMITIVE (&dfsch_primitive_type)
#define SYMBOL DFSCH_SYMBOL_TYPE
#define VECTOR DFSCH_VECTOR_TYPE
Typedefs
typedef struct hash_entry_t hash_entry_t
typedef dfsch_tail_escape_t tail_escape_t
Functions
static environment_t * alloc_environment (dfsch__thread_info_t *ti)
static dfsch__tracepoint_t * alloc_trace_buffer (dfsch__thread_info_t *ti, int depth)
static void async_apply_check (dfsch__thread_info_t *ti)
static dfsch_object_t * boolean_accessor_ref (void *ptr)
static void boolean_accessor_set (void *ptr, dfsch_object_t *obj)
static void destructure_impl (lambda_list_t *ll, dfsch_object_t *list, environment_t *env)
static void destructuring_eval (lambda_list_t *ll, dfsch_object_t *list, environment_t *env, environment_t *outer, dfsch__thread_info_t *ti)
void dfsch__continue_unwind (dfsch__thread_info_t *ti)
void dfsch__finalize_unwind (dfsch__thread_info_t *ti)
dfsch__thread_info_t * dfsch__get_thread_info ()
dfsch_object_t * dfsch_append (dfsch_object_t *llist)
dfsch_object_t * dfsch_apply (dfsch_object_t *proc, dfsch_object_t *args)
static dfsch_object_t * dfsch_apply_impl (dfsch_object_t *proc, dfsch_object_t *args, environment_t *arg_env, tail_escape_t *esc, dfsch__thread_info_t *ti)
dfsch_object_t * dfsch_apply_tr (dfsch_object_t *proc, dfsch_object_t *args, tail_escape_t *esc)
dfsch_object_t * dfsch_assert_instance (dfsch_object_t *obj, dfsch_type_t *type)
void * dfsch_assert_type (dfsch_object_t *obj, dfsch_type_t *type)
dfsch_object_t * dfsch_assoc (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_assq (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_assv (dfsch_object_t *key, dfsch_object_t *alist)
void dfsch_async_apply_check ()
void dfsch_async_apply_self (dfsch_object_t *proc)
int dfsch_atom_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_bool (int bool)
dfsch_object_t * dfsch_car (dfsch_object_t *pair)
dfsch_object_t * dfsch_cdr (dfsch_object_t *pair)
void dfsch_cerror (char *name, dfsch_object_t *detail)
int dfsch_compare_symbol (dfsch_object_t *symbol, char *string)
dfsch_object_t * dfsch_compile_lambda_list (dfsch_object_t *list)
dfsch_object_t * dfsch_cons (dfsch_object_t *car, dfsch_object_t *cdr)
dfsch_object_t * dfsch_cons_immutable (dfsch_object_t *car, dfsch_object_t *cdr)
void dfsch_declare (dfsch_object_t *variable, dfsch_object_t *declaration, dfsch_object_t *env)
object_t * dfsch_define (object_t *name, object_t *value, object_t *env)
dfsch_object_t * dfsch_define_cstr (dfsch_object_t *ctx, char *name, dfsch_object_t *obj)
DFSCH_DEFINE_FORM_IMPL (current_environment,"Return lexically-enclosing environment")
dfsch_object_t * dfsch_destructuring_bind (dfsch_object_t *arglist, dfsch_object_t *list, dfsch_object_t *env)
dfsch_object_t * dfsch_ensure_mutable_list (dfsch_object_t *list)
object_t * dfsch_env_get (object_t *name, object_t *env)
dfsch_object_t * dfsch_env_get_cstr (dfsch_object_t *ctx, char *name)
int dfsch_eq_p (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_equal_p (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_eqv_p (dfsch_object_t *a, dfsch_object_t *b)
void dfsch_error (char *name, dfsch_object_t *detail)
dfsch_object_t * dfsch_eval (dfsch_object_t *exp, dfsch_object_t *env)
static dfsch_object_t * dfsch_eval_impl (dfsch_object_t *exp, environment_t *env, dfsch_tail_escape_t *esc, dfsch__thread_info_t *ti)
dfsch_object_t * dfsch_eval_list (dfsch_object_t *list, dfsch_object_t *env)
dfsch_object_t * dfsch_eval_proc (dfsch_object_t *code, dfsch_object_t *env)
static dfsch_object_t * dfsch_eval_proc_impl (dfsch_object_t *code, environment_t *env, tail_escape_t *esc, dfsch__thread_info_t *ti)
dfsch_object_t * dfsch_eval_proc_tr (dfsch_object_t *code, dfsch_object_t *env, tail_escape_t *esc)
dfsch_object_t * dfsch_eval_tr (dfsch_object_t *exp, dfsch_object_t *env, dfsch_tail_escape_t *esc)
dfsch_slot_t * dfsch_find_slot (dfsch_type_t *type, char *name)
int dfsch_form_p (dfsch_object_t *obj)
int dfsch_function_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_gensym ()
dfsch_object_t * dfsch_get_environment_variables (dfsch_object_t *env)
dfsch_object_t * dfsch_get_list_annotation (dfsch_object_t *list)
char * dfsch_get_next_symbol (dfsch_symbol_iter_t **iter)
dfsch_object_t * dfsch_get_slots (dfsch_type_t *type)
uint32_t dfsch_hash (dfsch_object_t *obj)
int dfsch_instance_p (dfsch_object_t *obj, dfsch_type_t *type)
dfsch_object_t * dfsch_lambda (dfsch_object_t *env, dfsch_object_t *args, dfsch_object_t *code)
dfsch_object_t * dfsch_list (size_t count,...)
dfsch_object_t * dfsch_list_2_vector (dfsch_object_t *list)
dfsch_object_t * dfsch_list_annotate (dfsch_object_t *list, dfsch_object_t *source, dfsch_object_t *location)
dfsch_object_t ** dfsch_list_as_array (dfsch_object_t *list, size_t *length)
dfsch_object_t * dfsch_list_copy (dfsch_object_t *list)
dfsch_object_t * dfsch_list_copy_immutable (dfsch_object_t *list)
dfsch_object_t * dfsch_list_from_array (dfsch_object_t **array, size_t length)
dfsch_object_t * dfsch_list_item (dfsch_object_t *list, int index)
long dfsch_list_length (object_t *list, int *proper)
long dfsch_list_length_check (object_t *list)
long dfsch_list_length_fast (object_t *list)
int dfsch_list_mutable_p (object_t *list)
int dfsch_list_p (dfsch_object_t *obj)
object_t * dfsch_lookup (object_t *name, object_t *env)
dfsch_object_t * dfsch_lookup_cstr (dfsch_object_t *ctx, char *name)
dfsch_object_t * dfsch_macro_expand (dfsch_object_t *macro, dfsch_object_t *args)
int dfsch_macro_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_make_context ()
dfsch_object_t * dfsch_make_form (dfsch_form_impl_t impl, void *baton, char *name)
object_t * dfsch_make_macro (object_t *proc)
object_t * dfsch_make_object (const dfsch_type_t *type)
dfsch_object_t * dfsch_make_object_var (const dfsch_type_t *type, size_t size)
object_t * dfsch_make_primitive (dfsch_primitive_impl_t prim, void *baton)
object_t * dfsch_make_primitive_flags (dfsch_primitive_impl_t prim, void *baton, int flags)
dfsch_object_t * dfsch_make_symbol (char *symbol)
dfsch_object_t * dfsch_make_vector (size_t length, dfsch_object_t *fill)
dfsch_object_t * dfsch_member (dfsch_object_t *key, dfsch_object_t *list)
dfsch_object_t * dfsch_memq (dfsch_object_t *key, dfsch_object_t *list)
dfsch_object_t * dfsch_memv (dfsch_object_t *key, dfsch_object_t *list)
dfsch_object_t * dfsch_multicons (size_t n)
dfsch_object_t * dfsch_named_lambda (dfsch_object_t *env, dfsch_object_t *args, dfsch_object_t *code, dfsch_object_t *name)
dfsch_object_t * dfsch_new_frame (dfsch_object_t *parent)
dfsch_object_t * dfsch_nil ()
int dfsch_null_p (dfsch_object_t *obj)
char * dfsch_object_2_string (dfsch_object_t *obj, int max_depth, int readable)
dfsch_type_t * dfsch_object_as_type (dfsch_object_t *obj)
int dfsch_pair_p (dfsch_object_t *obj)
int dfsch_primitive_p (dfsch_object_t *obj)
int dfsch_procedure_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_quasiquote (dfsch_object_t *env, dfsch_object_t *arg)
dfsch_object_t * dfsch_reverse (dfsch_object_t *list)
object_t * dfsch_set (object_t *name, object_t *value, object_t *env)
dfsch_object_t * dfsch_set_car (dfsch_object_t *pair, dfsch_object_t *car)
dfsch_object_t * dfsch_set_cdr (dfsch_object_t *pair, dfsch_object_t *cdr)
dfsch_object_t * dfsch_set_cstr (dfsch_object_t *ctx, char *name, dfsch_object_t *obj)
dfsch_object_t * dfsch_slot_ref (dfsch_object_t *obj, dfsch_slot_t *slot, int debug)
dfsch_object_t * dfsch_slot_ref_by_name (dfsch_object_t *obj, char *slot, int debug)
void dfsch_slot_set (dfsch_object_t *obj, dfsch_slot_t *slot, dfsch_object_t *value, int debug)
void dfsch_slot_set_by_name (dfsch_object_t *obj, char *slot, dfsch_object_t *value, int debug)
dfsch_object_t * dfsch_sort_list (dfsch_object_t *list, dfsch_object_t *comp)
dfsch_object_t * dfsch_string_2_object (char *str)
dfsch_object_t * dfsch_string_2_object_list (char *str)
dfsch_object_t * dfsch_superclass (dfsch_object_t *obj)
int dfsch_superclass_p (dfsch_type_t *sub, dfsch_type_t *super)
char * dfsch_symbol (dfsch_object_t *symbol)
char * dfsch_symbol_2_typename (dfsch_object_t *symbol)
int dfsch_symbol_p (dfsch_object_t *obj)
void dfsch_throw (dfsch_object_t *tag, dfsch_object_t *value)
dfsch_type_t * dfsch_type_of (dfsch_object_t *obj)
void dfsch_unset (object_t *name, object_t *env)
dfsch_object_t * dfsch_vector (size_t count,...)
dfsch_object_t * dfsch_vector_2_list (dfsch_object_t *vector)
dfsch_object_t ** dfsch_vector_as_array (dfsch_object_t *vector, size_t *length)
dfsch_object_t * dfsch_vector_from_array (dfsch_object_t **array, size_t length)
size_t dfsch_vector_length (dfsch_object_t *vector)
int dfsch_vector_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_vector_ref (dfsch_object_t *vector, size_t k)
dfsch_object_t * dfsch_vector_set (dfsch_object_t *vector, size_t k, dfsch_object_t *obj)
dfsch_object_t * dfsch_zip (dfsch_object_t *llist)
static object_t * eval_list (object_t *list, environment_t *env, dfsch__thread_info_t *ti)
static void free_symbol (symbol_t *s)
static void function_write (closure_t *c, dfsch_writer_state_t *state)
static void gsh_check_init ()
static size_t hash_combine (size_t a, size_t b)
static void lambda_list_write (lambda_list_t *ll, dfsch_writer_state_t *ws)
static object_t * lookup_impl (object_t *name, environment_t *env, dfsch__thread_info_t *ti)
static symbol_t * lookup_symbol (char *symbol)
static symbol_t * make_symbol (char *symbol)
static object_t * native_top_level_environment (void *baton, object_t *args, dfsch_tail_escape_t *esc)
static environment_t * new_frame_impl (environment_t *parent, dfsch__thread_info_t *ti)
static dfsch_object_t * object_accessor_ref (void *ptr)
static void object_accessor_set (void *ptr, dfsch_object_t *obj)
static int pair_equal_p (dfsch_object_t *a, dfsch_object_t *b)
static size_t pair_hash (dfsch_object_t *p)
static void pair_write (dfsch_object_t *p, dfsch_writer_state_t *state)
static void primitive_write (dfsch_primitive_t *p, dfsch_writer_state_t *state)
static void print_lambda_list (lambda_list_t *ll, dfsch_writer_state_t *ws)
static size_t ptr_hash (dfsch_object_t *ptr)
static read_callback (dfsch_object_t *obj, void *ctx)
static void register_static_symbol (symbol_t *s)
static void slot_write (dfsch_slot_t *slot, dfsch_writer_state_t *state)
static dfsch_object_t * string_accessor_ref (void *ptr)
static void string_accessor_set (void *ptr, dfsch_object_t *obj)
static size_t string_hash (char *string)
static void symbol_finalizer (symbol_t *symbol, void *cd)
static void symbol_write (object_t *o, dfsch_writer_state_t *state)
static void thread_info_destroy (void *ptr)
static void thread_key_alloc ()
static dfsch_object_t * tl_cons (dfsch__thread_info_t *ti, dfsch_object_t *car, dfsch_object_t *cdr)
static void type_write (dfsch_type_t *t, dfsch_writer_state_t *state)
static int vector_equal_p (vector_t *a, vector_t *b)
static size_t vector_hash (vector_t *v)
static void vector_write (vector_t *v, dfsch_writer_state_t *state)
Variables
static dfsch_slot_t closure_slots []
dfsch__symbol_t dfsch__static_symbols []
dfsch_type_t dfsch_abstract_type
dfsch_slot_type_t dfsch_boolean_slot_type
int dfsch_default_trace_depth = 3
dfsch_type_t dfsch_empty_list_type
dfsch_type_t dfsch_environment_type
dfsch_type_t dfsch_form_type
dfsch_type_t dfsch_function_type
dfsch_type_t dfsch_lambda_list_type
dfsch_type_t dfsch_list_type
dfsch_type_t dfsch_macro_type
dfsch_type_t dfsch_meta_type
dfsch_slot_type_t dfsch_object_slot_type
dfsch_type_t dfsch_pair_type
dfsch_type_t dfsch_primitive_type
dfsch_type_t dfsch_slot_type
dfsch_type_t dfsch_slot_type_type
dfsch_type_t dfsch_special_type
dfsch_type_t dfsch_standard_function_type
dfsch_type_t dfsch_standard_type
dfsch_slot_type_t dfsch_string_slot_type
dfsch_type_t dfsch_tagged_types [4]
dfsch_type_t dfsch_vector_type
static dfsch_rwlock_t environment_rwlock = DFSCH_RWLOCK_INITIALIZER
static dfsch_slot_t environment_slots []
static dfsch_slot_t form_slots []
static hash_entry_t * global_symbol_hash [HASH_SIZE]
static unsigned int gsh_init = 0
static dfsch_slot_t macro_slots []
static dfsch_slot_t primitive_slots []
static dfsch_slot_t slot_slots []
static dfsch_slot_t slot_type_slots []
static pthread_mutex_t symbol_lock = PTHREAD_MUTEX_INITIALIZER
static pthread_key_t thread_key
static pthread_once_t thread_once = PTHREAD_ONCE_INIT
static dfsch_slot_t type_slots []
Detailed Description
This is implementation of dfsch interpreter.
Definition in file dfsch.c.
Define Documentation
#define FORM (&dfsch_form_type)
Definition at line 739 of file dfsch.c.
Referenced by dfsch_eval_impl(), dfsch_form_p(), and dfsch_make_form().
#define FUNCTION DFSCH_STANDARD_FUNCTION_TYPE
Definition at line 698 of file dfsch.c.
Referenced by dfsch_function_p(), and dfsch_procedure_p().
#define HASH_BITS 10
Definition at line 1612 of file dfsch.c.
#define HASH_SIZE (1 << HASH_BITS)
Definition at line 1613 of file dfsch.c.
Referenced by dfsch_get_next_symbol(), gsh_check_init(), and string_hash().
#define INT_ACCESSOR (type, name)
Value:
static dfsch_object_t* name ## _accessor_ref(void* ptr){              \
    return dfsch_make_number_from_long(*((type*)ptr));                  \
  }                                                                     \
  static void name ## _accessor_set(void* ptr, dfsch_object_t* obj){    \
    *((type*)ptr) = dfsch_number_to_long(obj);                          \
  }                                                                     \
  dfsch_slot_type_t dfsch_ ## name ## _slot_type = {                    \
    DFSCH_SLOT_TYPE_HEAD(#name "-slot",                                 \
                         "Slot containing C " #name "value"),      \
    name ## _accessor_ref,                                              \
    name ## _accessor_set,                                              \
    sizeof(type)                                                        \
  };                                                                    \
Definition at line 299 of file dfsch.c.
#define MACRO DFSCH_MACRO_TYPE
Definition at line 717 of file dfsch.c.
Referenced by dfsch_eval_impl(), dfsch_macro_expand(), dfsch_macro_p(), and dfsch_make_macro().
#define PAIR (&dfsch_pair_type)
Definition at line 549 of file dfsch.c.
Referenced by dfsch_append().
#define PRIMITIVE (&dfsch_primitive_type)
Definition at line 643 of file dfsch.c.
Referenced by dfsch_apply_impl(), dfsch_make_primitive_flags(), dfsch_primitive_p(), and dfsch_procedure_p().
#define SYMBOL DFSCH_SYMBOL_TYPE
Definition at line 560 of file dfsch.c.
Referenced by dfsch_symbol(), and dfsch_symbol_p().
#define VECTOR DFSCH_VECTOR_TYPE
Definition at line 790 of file dfsch.c.
Referenced by dfsch_list_2_vector(), dfsch_make_vector(), dfsch_vector(), dfsch_vector_2_list(), dfsch_vector_as_array(), dfsch_vector_from_array(), dfsch_vector_length(), dfsch_vector_p(), dfsch_vector_ref(), and dfsch_vector_set().
Typedef Documentation
typedef struct hash_entry_t hash_entry_t
Definition at line 1615 of file dfsch.c.
typedef dfsch_tail_escape_t tail_escape_t
Definition at line 2429 of file dfsch.c.
Function Documentation
static environment_t* alloc_environment (dfsch__thread_info_t * ti) [static]
Definition at line 2192 of file dfsch.c.
References DFSCH_ENVIRONMENT_TYPE, and dfsch__thread_info_t::env_freelist.
Referenced by new_frame_impl().
{
  environment_t* e;
#ifdef GC_NEXT
  if (!ti->env_freelist){
    ti->env_freelist = GC_malloc_many(sizeof(environment_t));
  }
  e = ti->env_freelist;
  ti->env_freelist = GC_NEXT(ti->env_freelist);
#else
  e = GC_NEW(environment_t);
#endif
  ((dfsch_object_t*)e)->type = DFSCH_ENVIRONMENT_TYPE;
  return e;
}
static dfsch__tracepoint_t* alloc_trace_buffer (dfsch__thread_info_t * ti, int depth) [static]
Definition at line 1944 of file dfsch.c.
References dfsch__thread_info_t::trace_buffer, dfsch__thread_info_t::trace_depth, and dfsch__thread_info_t::trace_ptr.
Referenced by dfsch__get_thread_info().
{
  size_t size;
  depth = depth % (8 * sizeof(short));
  size = 1 << depth;
  ti->trace_depth = size - 1;
  ti->trace_ptr = 0;
  ti->trace_buffer = GC_MALLOC(sizeof(dfsch__tracepoint_t) * size);
}
static void async_apply_check (dfsch__thread_info_t * ti) [static]
Definition at line 2416 of file dfsch.c.
References dfsch__thread_info_t::async_apply, dfsch_apply(), and DFSCH_UNLIKELY.
Referenced by dfsch_async_apply_check(), and dfsch_eval_proc_impl().
{
  if (DFSCH_UNLIKELY(ti->async_apply)){
    dfsch_object_t* proc;
    proc = ti->async_apply;
    ti->async_apply = NULL;
    dfsch_apply(proc, NULL);
  }
}
static dfsch_object_t* boolean_accessor_ref (void * ptr) [static]
Definition at line 273 of file dfsch.c.
References dfsch_bool().
{
  return dfsch_bool(*((int*)ptr));
}
static void boolean_accessor_set (void * ptr, dfsch_object_t * obj) [static]
Definition at line 276 of file dfsch.c.
{
  *((int**)ptr) = (obj != NULL);
}
static void destructure_impl (lambda_list_t * ll, dfsch_object_t * list, environment_t * env) [static]
Definition at line 2573 of file dfsch.c.
References dfsch_eqhash_put(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_list(), DFSCH_PAIR_P, DFSCH_UNLIKELY, lambda_list_t::positional, lambda_list_t::positional_count, lambda_list_t::rest, and environment_t::values.
Referenced by dfsch_apply_impl(), and dfsch_destructuring_bind().
{
  int i;
  dfsch_object_t* j = list;
  for (i = 0; i < ll->positional_count; i++){
    if (DFSCH_UNLIKELY(!DFSCH_PAIR_P(j))){
      dfsch_error("Too few arguments", dfsch_list(2, ll, list));
    }
    dfsch_eqhash_put(&env->values, ll->positional[i], DFSCH_FAST_CAR(j));
    j = DFSCH_FAST_CDR(j);
  }
  if (DFSCH_UNLIKELY(ll->rest)) {
    dfsch_eqhash_put(&env->values, ll->rest, j);
  } else {
    if (DFSCH_UNLIKELY(j)) {
      dfsch_error("Too many arguments", dfsch_list(2,ll, list));
    }
  }
}
static void destructuring_eval (lambda_list_t * ll, dfsch_object_t * list, environment_t * env, environment_t * outer, dfsch__thread_info_t * ti) [static]
Definition at line 2596 of file dfsch.c.
References dfsch_eqhash_put(), dfsch_error(), dfsch_eval_impl(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_list(), DFSCH_PAIR_P, DFSCH_UNLIKELY, eval_list(), lambda_list_t::positional, lambda_list_t::positional_count, lambda_list_t::rest, and environment_t::values.
Referenced by dfsch_apply_impl().
{
  int i;
  dfsch_object_t* j = list;
  for (i = 0; i < ll->positional_count; i++){
    if (DFSCH_UNLIKELY(!DFSCH_PAIR_P(j))){
      dfsch_error("Too few arguments", dfsch_list(2, ll, list));
    }
    dfsch_eqhash_put(&env->values, ll->positional[i],
                     dfsch_eval_impl(DFSCH_FAST_CAR(j), outer, NULL, ti));
    j = DFSCH_FAST_CDR(j);
  }
  if (DFSCH_UNLIKELY(ll->rest)) {
    dfsch_eqhash_put(&env->values, ll->rest, eval_list(j, outer, ti));
  } else {
    if (DFSCH_UNLIKELY(j)) {
      dfsch_error("Too many arguments", dfsch_list(2,ll, list));
    }
  }
}
void dfsch__continue_unwind (dfsch__thread_info_t * ti)
Definition at line 1981 of file dfsch.c.
References dfsch__thread_info_t::throw_ret.
{
  if (!ti->throw_ret){
    fputs("No unwind target!!!\n", stderr);
    abort();
  }
  longjmp(*ti->throw_ret, 1);
}
void dfsch__finalize_unwind (dfsch__thread_info_t * ti)
Definition at line 1988 of file dfsch.c.
References dfsch__thread_info_t::throw_tag, and dfsch__thread_info_t::throw_value.
{
  ti->throw_tag = NULL;
  ti->throw_value = NULL;
}
dfsch__thread_info_t* dfsch__get_thread_info ()
Definition at line 1954 of file dfsch.c.
References alloc_trace_buffer(), dfsch__thread_info_t::async_apply, DFSCH_UNLIKELY, thread_key_alloc(), and dfsch__thread_info_t::throw_ret.
Referenced by dfsch_apply(), dfsch_apply_tr(), dfsch_async_apply_check(), dfsch_async_apply_self(), dfsch_compute_restarts(), dfsch_define(), dfsch_eval(), dfsch_eval_list(), dfsch_eval_proc(), dfsch_eval_proc_tr(), dfsch_eval_tr(), dfsch_get_trace(), dfsch_handler_bind(), dfsch_invoke_restart(), dfsch_lookup(), dfsch_new_frame(), dfsch_print_trace_buffer(), dfsch_restart_bind(), dfsch_set(), dfsch_signal(), and dfsch_throw().
{
#ifdef DFSCH__USE_TLS____BROKEN
  static __thread dfsch__thread_info_t* ei;
#else
  dfsch__thread_info_t *ei;
  pthread_once(&thread_once, thread_key_alloc);
  ei = pthread_getspecific(thread_key);
#endif
  if (DFSCH_UNLIKELY(!ei)){
    ei = GC_MALLOC_UNCOLLECTABLE(sizeof(dfsch__thread_info_t));
    ei->throw_ret = NULL;
    ei->async_apply = NULL;
    alloc_trace_buffer(ei, dfsch_default_trace_depth);
    pthread_setspecific(thread_key, ei);
  }
  return ei;
}
dfsch_object_t* dfsch_append (dfsch_object_t * llist)
Concatenate lists
Definition at line 1291 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, DFSCH_PAIR_P, dfsch_type_error(), and PAIR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_load_extend_path(), and dfsch_quasiquote().
{
  dfsch_object_t* head=NULL;
  dfsch_object_t* tail=NULL;
  dfsch_object_t* i = llist;
  dfsch_object_t* j;
  if (!llist)
    return NULL;
  while(DFSCH_PAIR_P(i) && DFSCH_PAIR_P(DFSCH_FAST_CDR(i))){
    j = DFSCH_FAST_CAR(i);
    while(DFSCH_PAIR_P(j)){
      if (head){
        object_t* tmp = dfsch_cons(DFSCH_FAST_CAR(j),NULL);
        DFSCH_FAST_CDR_MUT(tail) = tmp;
        tail = tmp;
      }else{
        head = tail = dfsch_cons(DFSCH_FAST_CAR(j),NULL);
      }
      j = DFSCH_FAST_CDR(j);
    }
    if (j && !DFSCH_PAIR_P(j)) {
      dfsch_type_error(j, PAIR, 0);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (!DFSCH_PAIR_P(i)){
    dfsch_type_error(i, PAIR, 0);
  }
  if (tail){
    DFSCH_FAST_CDR_MUT(tail) = DFSCH_FAST_CAR(i);
  }else{
    head = DFSCH_FAST_CAR(i);
  }
  return head;
}
dfsch_object_t* dfsch_apply (dfsch_object_t * proc, dfsch_object_t * args)
Apply procedure to given arguments
Definition at line 2765 of file dfsch.c.
References dfsch__get_thread_info(), and dfsch_apply_impl().
Referenced by async_apply_check(), dfsch_collections_priority_queue_push(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_enter_debugger(), dfsch_invoke_restart(), dfsch_macro_expand(), dfsch_signal(), dfsch_sort_list(), lisp_callback(), parser_apply(), thread_function(), wrapper_equal_p(), wrapper_hash(), and wrapper_write().
{
  return dfsch_apply_impl(proc, args, NULL, NULL, dfsch__get_thread_info());
}
static dfsch_object_t * dfsch_apply_impl (dfsch_object_t * proc, dfsch_object_t * args, environment_t * arg_env, tail_escape_t * esc, dfsch__thread_info_t * ti) [static]
Definition at line 2692 of file dfsch.c.
References dfsch_tail_escape_t::arg_env, dfsch_tail_escape_t::args, destructure_impl(), destructuring_eval(), DFSCH__TRACEPOINT_APPLY, dfsch_error(), dfsch_eval_proc_impl(), DFSCH_LIKELY, DFSCH_STANDARD_FUNCTION_TYPE, DFSCH_TRACEPOINT_FLAG_APPLY_LAZY, DFSCH_TRACEPOINT_FLAG_APPLY_TAIL, DFSCH_TYPE_OF, DFSCH_UNLIKELY, eval_list(), new_frame_impl(), PRIMITIVE, dfsch_tail_escape_t::proc, and dfsch_tail_escape_t::ret.
Referenced by dfsch_apply(), dfsch_apply_tr(), and dfsch_eval_impl().
{
  dfsch_object_t* r;
  tail_escape_t myesc;
  if (DFSCH_UNLIKELY(esc)){
    esc->proc = proc;
    esc->args = args;
    esc->arg_env = arg_env;
    longjmp(esc->ret,1);
  }
  if (setjmp(myesc.ret)){
    proc = myesc.proc;
    args = myesc.args;
    arg_env = myesc.arg_env;
    DFSCH__TRACEPOINT_APPLY(ti, proc, args,
                           DFSCH_TRACEPOINT_FLAG_APPLY_TAIL |
                           (arg_env ? DFSCH_TRACEPOINT_FLAG_APPLY_LAZY : 0));
  } else {
    DFSCH__TRACEPOINT_APPLY(ti, proc, args,
                           (arg_env ? DFSCH_TRACEPOINT_FLAG_APPLY_LAZY : 0));
  }
  /*
   * Two most common cases are written here explicitly (for historical
   * and performance reasons)
   */
  if (DFSCH_TYPE_OF(proc) == PRIMITIVE){
    if (DFSCH_LIKELY(arg_env)){
      args = eval_list(args, arg_env, ti);
    }
    return ((primitive_t*)proc)->proc(((primitive_t*)proc)->baton,args,
                                      &myesc);
  }
  if (DFSCH_TYPE_OF(proc) == DFSCH_STANDARD_FUNCTION_TYPE){
    environment_t* env = new_frame_impl(((closure_t*) proc)->env,
                                        ti);
    if (DFSCH_LIKELY(arg_env)){
      destructuring_eval(((closure_t*)proc)->args, args, env, arg_env, ti);
    } else {
      destructure_impl(((closure_t*)proc)->args, args, env);
    }
    return dfsch_eval_proc_impl(((closure_t*)proc)->code,
                                env,
                                &myesc,
                                ti);
  }
  if (DFSCH_TYPE_OF(proc)->apply){
    if (DFSCH_LIKELY(arg_env)){
      args = eval_list(args, arg_env, ti);
    }
    return DFSCH_TYPE_OF(proc)->apply(proc, args, &myesc);
  }
  dfsch_error("Not a procedure", proc);
}
dfsch_object_t* dfsch_apply_tr (dfsch_object_t * proc, dfsch_object_t * args, dfsch_tail_escape_t * esc)
Extended variant of dfsch_apply with support for tail recursion
Definition at line 2760 of file dfsch.c.
References dfsch__get_thread_info(), and dfsch_apply_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_perform_tr(), native_apply(), and wrapper_apply().
{
  return dfsch_apply_impl(proc, args, NULL, esc, dfsch__get_thread_info());
}
dfsch_object_t* dfsch_assert_instance (dfsch_object_t * obj, dfsch_type_t * type)
Definition at line 197 of file dfsch.c.
References DFSCH_END_WITH_RETRY_WITH_RESTART, DFSCH_INSTANCE_P, dfsch_make_symbol(), dfsch_type_error(), and DFSCH_WITH_RETRY_WITH_RESTART.
Referenced by dfsch_condition_field(), dfsch_condition_fields(), and dfsch_condition_put_field().
{
  dfsch_object_t* o = obj;
  while (!DFSCH_INSTANCE_P(o, type)){
    DFSCH_WITH_RETRY_WITH_RESTART(dfsch_make_symbol("use-value"),
                                  "Retry with alternate value") {
      dfsch_type_error(o, type, 1);
    } DFSCH_END_WITH_RETRY_WITH_RESTART(o);
  }
  return o;
}
void* dfsch_assert_type (dfsch_object_t * obj, dfsch_type_t * type)
Definition at line 187 of file dfsch.c.
References DFSCH_END_WITH_RETRY_WITH_RESTART, dfsch_make_symbol(), dfsch_type_error(), DFSCH_TYPE_OF, and DFSCH_WITH_RETRY_WITH_RESTART.
Referenced by dfsch_restart_description(), dfsch_restart_name(), and dfsch_restart_proc().
{
  dfsch_object_t* o = obj;
  while (DFSCH_TYPE_OF(o) != type){
    DFSCH_WITH_RETRY_WITH_RESTART(dfsch_make_symbol("use-value"),
                                  "Retry with alternate value") {
      dfsch_type_error(o, type, 0);
    } DFSCH_END_WITH_RETRY_WITH_RESTART(o);
  }
  return o;
}
dfsch_object_t* dfsch_assoc (dfsch_object_t * key, dfsch_object_t * alist)
Return alist entry with car equal? to key
Definition at line 1531 of file dfsch.c.
References dfsch_equal_p(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=alist;
  while (DFSCH_PAIR_P(i)){
    if (!DFSCH_PAIR_P(DFSCH_FAST_CAR(i))){
      dfsch_error("Not a alist",(object_t*)alist);
    }
    if (dfsch_equal_p(key, DFSCH_FAST_CAR(DFSCH_FAST_CAR(i)))){
      return DFSCH_FAST_CAR(i);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a alist", (object_t*)i);
  }
  return NULL;
}
dfsch_object_t* dfsch_assq (dfsch_object_t * key, dfsch_object_t * alist)
Return alist entry with car eq? to key
Definition at line 1557 of file dfsch.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by dfsch_condition_field(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=alist;
  while (DFSCH_PAIR_P(i)){
    if (!DFSCH_PAIR_P(DFSCH_FAST_CAR(i))){
      dfsch_error("Not a alist",(object_t*)alist);
    }
    if (key == DFSCH_FAST_CAR(DFSCH_FAST_CAR(i))){
      return DFSCH_FAST_CAR(i);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a alist",(object_t*)i);
  }
  return NULL;
}
dfsch_object_t* dfsch_assv (dfsch_object_t * key, dfsch_object_t * alist)
Return alist entry with car eqv? to key
Definition at line 1582 of file dfsch.c.
References dfsch_eqv_p(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=alist;
  while (DFSCH_PAIR_P(i)){
    if (!DFSCH_PAIR_P(DFSCH_FAST_CAR(i))){
      dfsch_error("Not a alist",(object_t*)alist);
    }
    if (dfsch_eqv_p(key, DFSCH_FAST_CAR(DFSCH_FAST_CAR(i)))){
      return DFSCH_FAST_CAR(i);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a alist",(object_t*)i);
  }
  return NULL;
}
void dfsch_async_apply_check ()
Check for pending asynchronous apply
Definition at line 2425 of file dfsch.c.
References async_apply_check(), and dfsch__get_thread_info().
{
  async_apply_check(dfsch__get_thread_info());
}
void dfsch_async_apply_self (dfsch_object_t * proc)
Apply procedure later in evaluation (useful for signal handlers)
Definition at line 2026 of file dfsch.c.
References dfsch__thread_info_t::async_apply, and dfsch__get_thread_info().
Referenced by sigint_handler_break().
{
  dfsch__get_thread_info()->async_apply = proc;
}
int dfsch_atom_p (dfsch_object_t * obj)
Is OBJ an atom? (i.e. not pair)
Definition at line 843 of file dfsch.c.
References DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return !DFSCH_PAIR_P(obj);
}
dfsch_object_t* dfsch_bool (int bool)
Return true or nil depending on value of BOOL.
Definition at line 1826 of file dfsch.c.
References DFSCH_SYM_TRUE.
Referenced by boolean_accessor_ref(), decoded_time_apply(), DFSCH_DEFINE_PRIMITIVE(), dfsch_number_even_p(), dfsch_number_odd_p(), DFSCH_PRIMITIVE_HEAD(), dfsch_type_error(), native_eof_object_p(), native_hash_p(), native_hash_set_if_exists(), native_hash_unset(), native_mutex_trylock(), native_regex_match_once_p(), native_regex_match_p(), native_weak_reference_live_p(), and stat_apply().
{
  return bool ? DFSCH_SYM_TRUE : NULL;
}
dfsch_object_t* dfsch_car (dfsch_object_t * pair)
Return first (car) item of pair
Definition at line 936 of file dfsch.c.
References DFSCH_ASSERT_PAIR, and DFSCH_FAST_CAR.
Referenced by command_exit(), command_print(), command_write(), dfsch_alist_2_hash(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_copy_immutable(), dfsch_list_item(), dfsch_load(), dfsch_load_extend_path(), dfsch_provide(), dfsch_quasiquote(), dfsch_require(), dfsch_string_2_object(), dfsch_string_list_append(), directive_import(), list_get(), list_peek(), list_source(), native_cxr(), native_stream_car(), process_directive(), and search_modules().
{
  dfsch_object_t* p = DFSCH_ASSERT_PAIR(pair);
  return DFSCH_FAST_CAR(p);
}
dfsch_object_t* dfsch_cdr (dfsch_object_t * pair)
Return second (cdr) item of pair
Definition at line 940 of file dfsch.c.
References DFSCH_ASSERT_PAIR, and DFSCH_FAST_CDR.
Referenced by command_print(), command_write(), dfsch_alist_2_hash(), dfsch_condition_field(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_copy_immutable(), dfsch_load(), dfsch_quasiquote(), dfsch_stream_cdr(), dfsch_string_list_append(), directive_import(), list_get(), list_seek(), list_skip(), list_source(), native_cxr(), process_directive(), and search_modules().
{
  dfsch_object_t* p = DFSCH_ASSERT_PAIR(pair);
  return DFSCH_FAST_CDR(p);
}
void dfsch_cerror (char * type, dfsch_object_t * data)
Convenience wrapper for signaling recoverable error condition
Definition at line 2015 of file dfsch.c.
References dfsch_condition(), DFSCH_END_WITH_SIMPLE_RESTART, DFSCH_ERROR_TYPE, dfsch_make_string_cstr(), dfsch_make_symbol(), dfsch_signal(), and DFSCH_WITH_SIMPLE_RESTART.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  DFSCH_WITH_SIMPLE_RESTART(dfsch_make_symbol("continue"),
                            "Ignore error condition"){
    dfsch_signal(dfsch_condition(DFSCH_ERROR_TYPE,
                                 "message", dfsch_make_string_cstr(name),
                                 "object", detail,
                                 NULL));
  } DFSCH_END_WITH_SIMPLE_RESTART;
}
int dfsch_compare_symbol (dfsch_object_t * symbol, char * string)
Compares value of given symbol to string.
Definition at line 1821 of file dfsch.c.
References ascii_strcasecmp, and dfsch_symbol().
Referenced by condition_write(), decoded_time_apply(), dfsch_format_trace(), native_lseek(), native_sig(), prettyprint_condition_fields(), and stat_apply().
{
  return (ascii_strcasecmp(string, dfsch_symbol(symbol)) == 0);
}
dfsch_object_t* dfsch_compile_lambda_list (dfsch_object_t * list)
Definition at line 2549 of file dfsch.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LAMBDA_LIST_TYPE, dfsch_list_length_fast(), dfsch_make_object_var(), DFSCH_PAIR_P, lambda_list_t::positional, lambda_list_t::positional_count, and lambda_list_t::rest.
Referenced by dfsch_destructuring_bind(), and dfsch_named_lambda().
{
  lambda_list_t* ll;
  long count = dfsch_list_length_fast(list);
  dfsch_object_t* i = list;
  size_t j;
  if (count == -1){
    count = 0;
  }
  ll = dfsch_make_object_var(DFSCH_LAMBDA_LIST_TYPE,
                             sizeof(dfsch_object_t*) * count);
  ll->positional_count = count;
  j = 0;
  while (DFSCH_PAIR_P(i)){
    if (j >= count){
      dfsch_error("wtf?", NULL);
    }
    ll->positional[j] = DFSCH_FAST_CAR(i);
    j++;
    i = DFSCH_FAST_CDR(i);
  }
  ll->rest = i;
  return ll;
}
dfsch_object_t* dfsch_cons (dfsch_object_t * car, dfsch_object_t * cdr)
Construct pair object
Definition at line 878 of file dfsch.c.
References dfsch_pair_t::car, dfsch_pair_t::cdr, and DFSCH_TAG_ENCODE.
Referenced by class_equal_p(), dfsch_append(), dfsch_cmdopts_argv_to_list(), dfsch_compute_restarts(), dfsch_condition_put_field(), dfsch_declare(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_enter_debugger(), dfsch_env_get(), dfsch_eqhash_2_alist(), dfsch_get_list_annotation(), dfsch_get_slots(), dfsch_hash_2_alist(), dfsch_http_query_2_alist(), dfsch_http_split_path(), dfsch_list_copy(), dfsch_parser_parse_object(), dfsch_provide(), dfsch_quasiquote(), dfsch_read_scm_stream(), dfsch_reverse(), dfsch_send(), dfsch_send_tr(), dfsch_signal(), dfsch_string_2_list(), dfsch_string_split(), dfsch_string_split_byte(), dfsch_string_split_char(), dfsch_string_utf8_2_list(), dfsch_xml_signal_error(), dfsch_zip(), load_callback(), lookup_impl(), parser_abort(), read_callback(), start_element_handler(), sxml_append(), and sxml_push().
{
  dfsch_pair_t* p = GC_NEW(dfsch_pair_t);
  p->car = car;
  p->cdr = cdr;
  return DFSCH_TAG_ENCODE(p, 1);
}
dfsch_object_t* dfsch_cons_immutable (dfsch_object_t * car, dfsch_object_t * cdr)
Construct immutable pair object
Definition at line 887 of file dfsch.c.
References dfsch_pair_t::car, dfsch_pair_t::cdr, and DFSCH_TAG_ENCODE.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_get_trace(), and dfsch_list_copy_immutable().
{
  dfsch_pair_t* p = GC_NEW(dfsch_pair_t);
  p->car = car;
  p->cdr = cdr;
  return DFSCH_TAG_ENCODE(p, 3);
}
void dfsch_declare (dfsch_object_t * variable, dfsch_object_t * declaration, dfsch_object_t * env)
Definition at line 2362 of file dfsch.c.
References environment_t::decls, DFSCH_ASSERT_TYPE, dfsch_cons(), DFSCH_ENVIRONMENT_TYPE, DFSCH_HASH_EQ, dfsch_hash_make(), dfsch_hash_ref_fast(), and dfsch_hash_set().
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  dfsch_object_t* old = NULL;
  environment_t* e = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  if (!e->decls){
    e->decls = dfsch_hash_make(DFSCH_HASH_EQ);
  } else {
    dfsch_hash_ref_fast(e->decls, variable, &old);
  }
  dfsch_hash_set(e->decls, variable,
                 dfsch_cons(declaration, old));
}
object_t* dfsch_define (dfsch_object_t * name, dfsch_object_t * value, dfsch_object_t * env)
Define variable name in environment env
Definition at line 2345 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_set(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, environment_t::owner, and environment_t::values.
Referenced by dfsch_define_cstr(), DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  environment_t* e = (environment_t*)DFSCH_ASSERT_TYPE(env,
                                                       DFSCH_ENVIRONMENT_TYPE);
  dfsch__thread_info_t *ti = dfsch__get_thread_info();
  if (e->owner != ti){
    e->owner = NULL;
    DFSCH_RWLOCK_WRLOCK(&environment_rwlock);
  }
  dfsch_eqhash_set(&e->values,
                   name, value);
  if (e->owner != ti){
    DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  }
  return value;
}
dfsch_object_t* dfsch_define_cstr (dfsch_object_t * ctx, char * name, dfsch_object_t * obj)
Define new variable in given context
Definition at line 2848 of file dfsch.c.
References dfsch_define(), and dfsch_make_symbol().
Referenced by debug_main(), dfsch__bignum_register(), dfsch__conditions_register(), dfsch__control_register(), dfsch__format_native_register(), dfsch__hash_native_register(), dfsch__native_cxr_register(), dfsch__native_register(), dfsch__number_native_register(), dfsch__object_native_register(), dfsch__port_native_register(), dfsch__promise_native_register(), dfsch__random_register(), dfsch__string_native_register(), dfsch__system_register(), dfsch__weak_native_register(), dfsch__wrapper_native_register(), dfsch_introspect_register(), dfsch_load_extend_path(), dfsch_load_register(), dfsch_make_context(), dfsch_module_cdebug_register(), dfsch_module_cmdopts_register(), dfsch_module_collections_register(), dfsch_module_console_register(), dfsch_module_extref_register(), dfsch_module_gcollect_register(), dfsch_module_inet_register(), dfsch_module_process_register(), dfsch_module_regex_register(), dfsch_module_sxml_register(), dfsch_module_threads_register(), dfsch_module_unix_register(), dfsch_module_xml_register(), dfsch_port_unsafe_register(), dfsch_provide(), load_scm(), and main().
{
  return dfsch_define(dfsch_make_symbol(name),
                      obj,
                      ctx);
}
DFSCH_DEFINE_FORM_IMPL (current_environment , "Return lexically-enclosing environment")
Definition at line 2796 of file dfsch.c.
{
  return env;
}
dfsch_object_t* dfsch_destructuring_bind (dfsch_object_t * arglist, dfsch_object_t * list, dfsch_object_t * env)
Definition at line 2622 of file dfsch.c.
References destructure_impl(), dfsch_compile_lambda_list(), DFSCH_LAMBDA_LIST_TYPE, dfsch_new_frame(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  environment_t* e = dfsch_new_frame(env);
  lambda_list_t* l;
  if (DFSCH_TYPE_OF(arglist) != DFSCH_LAMBDA_LIST_TYPE){
    l = dfsch_compile_lambda_list(arglist);
  } else {
    l = arglist;
  }
  destructure_impl(l, list, e);
  return e;
}
dfsch_object_t* dfsch_ensure_mutable_list (dfsch_object_t * list)
Return mutable list - argument if it is mutable, fresh copy if not
Definition at line 1061 of file dfsch.c.
References dfsch_list_copy(), dfsch_list_length_check(), and dfsch_list_mutable_p().
Referenced by dfsch_sort_list().
{
  if (dfsch_list_mutable_p(list)){
    return list;
  }
  dfsch_list_length_check(list);
  return dfsch_list_copy(list);
}
object_t* dfsch_env_get (dfsch_object_t * name, dfsch_object_t * env)
Get value of variable name in environment env. Return empty list in case of failure.
Definition at line 2271 of file dfsch.c.
References DFSCH_ASSERT_TYPE, dfsch_cons(), DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_ref(), DFSCH_INVALID_OBJECT, DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, environment_t::parent, and environment_t::values.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_env_get_cstr().
{
  environment_t *i;
  object_t* ret;
  i = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  DFSCH_RWLOCK_RDLOCK(&environment_rwlock);
  while (i){
    ret = dfsch_eqhash_ref(&i->values, name);
    if (ret != DFSCH_INVALID_OBJECT){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return dfsch_cons(ret, NULL);
    }
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  return NULL;
}
dfsch_object_t* dfsch_env_get_cstr (dfsch_object_t * ctx, char * name)
Look up value of given variable, returns list of one item if sucessful, empty list if not
Definition at line 2869 of file dfsch.c.
References dfsch_env_get(), and dfsch_make_symbol().
Referenced by dfsch_load(), dfsch_load_extend_path(), dfsch_provide(), and dfsch_require().
{
  return dfsch_env_get(dfsch_make_symbol(name), ctx);
}
int dfsch_eq_p (dfsch_object_t * a, dfsch_object_t * b)
Same object? (i.e. equal addresses)
Definition at line 76 of file dfsch.c.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return (a==b);
}
int dfsch_equal_p (dfsch_object_t * a, dfsch_object_t * b)
Equal object? (i.e. equal contents)
Definition at line 93 of file dfsch.c.
References dfsch_equal_p(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_PAIR_P, and DFSCH_TYPE_OF.
Referenced by dfsch_assoc(), DFSCH_DEFINE_PRIMITIVE(), dfsch_equal_p(), dfsch_hash_ref_fast(), dfsch_hash_set(), dfsch_hash_set_if_exists(), dfsch_hash_unset(), dfsch_member(), fracnum_equal_p(), pair_equal_p(), and vector_equal_p().
{
  if (a==b)
    return 1;
  if (!a || !b)
    return 0;
  if (DFSCH_TYPE_OF(a) != DFSCH_TYPE_OF(b)){
    if (DFSCH_PAIR_P(a) && DFSCH_PAIR_P(b)){
      return (dfsch_equal_p(DFSCH_FAST_CAR(a), DFSCH_FAST_CAR(b)) &&
              dfsch_equal_p(DFSCH_FAST_CDR(a), DFSCH_FAST_CDR(b)));
    } else {
      return 0;
    }
  }
  if (!DFSCH_TYPE_OF(a))
    return 0;
  if (!DFSCH_TYPE_OF(a)->equal_p)
    return 0;
  return DFSCH_TYPE_OF(a)->equal_p(a,b);
}
int dfsch_eqv_p (dfsch_object_t * a, dfsch_object_t * b)
Same object or number?
Definition at line 80 of file dfsch.c.
References dfsch_number_equal_p(), dfsch_number_p(), and DFSCH_TYPE_OF.
Referenced by dfsch_assv(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_memv().
{
  if (a==b)
    return 1;
  if (!a || !b)
    return 0;
  if ((DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b)) && dfsch_number_p(a))
    return dfsch_number_equal_p(a,b);
  return 0;
}
void dfsch_error (char * type, dfsch_object_t * data)
Convenience wrapper for signaling error condition from C code
Definition at line 2008 of file dfsch.c.
References dfsch_condition(), DFSCH_ERROR_TYPE, dfsch_make_string_cstr(), and dfsch_signal().
Referenced by decoded_time_apply(), destructure_impl(), destructuring_eval(), dfsch_apply_impl(), dfsch_assoc(), dfsch_assq(), dfsch_assv(), dfsch_bignum_div(), dfsch_bignum_exp(), dfsch_bignum_from_number(), dfsch_bignum_to_string(), dfsch_channel_read(), dfsch_channel_write(), dfsch_class_add_method(), dfsch_class_remove_method(), dfsch_collections_priority_queue_empty_p(), dfsch_collections_priority_queue_pop(), dfsch_collections_priority_queue_push(), dfsch_compile_lambda_list(), dfsch_condition_broadcast(), dfsch_condition_signal(), dfsch_condition_wait(), dfsch_condition_with_fields(), dfsch_console_read_object(), dfsch_decoded_time_get_tm(), DFSCH_DEFINE_PRIMITIVE(), dfsch_eval_proc_impl(), dfsch_extref_ref(), dfsch_find_method(), dfsch_find_slot(), dfsch_force_promise(), dfsch_format(), dfsch_invoke_restart(), dfsch_list_2_string_utf8(), dfsch_list_item(), dfsch_load(), dfsch_load_so(), dfsch_make_class(), dfsch_make_condition(), dfsch_make_file_random_state(), dfsch_make_instance(), dfsch_make_number_from_string(), dfsch_mutex_lock(), dfsch_mutex_trylock(), dfsch_mutex_unlock(), dfsch_number_denominator(), dfsch_number_div(), dfsch_number_div_i(), dfsch_number_mod(), dfsch_number_numerator(), dfsch_number_to_double(), dfsch_number_to_int64(), dfsch_number_to_long(), dfsch_number_to_string(), dfsch_open_file_port(), dfsch_parser_read_from_port(), dfsch_perform_tr(), dfsch_port_batch_read(), dfsch_port_batch_read_end(), dfsch_port_batch_read_start(), dfsch_port_read_buf(), dfsch_port_seek(), dfsch_port_tell(), dfsch_port_write_buf(), dfsch_process_close_port(), dfsch_provide(), dfsch_random_get_bytes(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_regex_match_p(), dfsch_regex_substrings(), dfsch_set(), dfsch_set_current_error_port(), dfsch_set_current_input_port(), dfsch_set_current_output_port(), dfsch_slot_ref(), dfsch_slot_set(), dfsch_string_2_object(), dfsch_string_2_object_list(), dfsch_string_output_port_value(), dfsch_string_ref(), dfsch_string_replace(), dfsch_string_split(), dfsch_string_split_byte(), dfsch_string_split_char(), dfsch_string_substring(), dfsch_string_substring_utf8(), dfsch_string_utf8_ref(), dfsch_sxml_emit_file(), dfsch_sxml_parse_file(), dfsch_thread_detach(), dfsch_thread_join(), dfsch_throw(), dfsch_unix_closedir(), dfsch_unix_get_stat(), dfsch_unix_readdir(), dfsch_unset(), dfsch_unwrap(), dfsch_vector_ref(), dfsch_vector_set(), dfsch_weak_reference_dereference(), dfsch_weak_reference_live_p(), dfsch_weak_vector_2_list(), dfsch_weak_vector_as_array(), dfsch_weak_vector_ref(), dfsch_weak_vector_set(), dfsch_wrap(), dfsch_write_strbuf(), dfsch_write_unreadable_start(), dfsch_xml_destroy_parser(), dfsch_xml_ext_set_character_data_proc(), dfsch_xml_parse_buf(), dfsch_xml_parse_file(), dfsch_xml_parse_port(), dfsch_xml_parser_ref(), dfsch_xml_set_comment_proc(), dfsch_xml_set_end_element_proc(), dfsch_xml_set_processing_instruction_proc(), dfsch_xml_set_start_element_proc(), dfsch_xml_signal_error(), dfsch_zip(), emit_attrs(), emit_object(), errno_error(), eval_list(), file_get_bytes(), file_port_read_buf(), file_port_seek(), file_port_tell(), file_port_write_buf(), int_to_str(), list_get(), list_peek(), list_seek(), list_skip(), lookup_impl(), native_alist_2_hash(), native_lseek(), native_make_hash(), native_sig(), parser_abort(), port_read_buf(), port_write_buf(), read_num_arg(), regex_compile(), rfputs(), spawn_port(), stat_apply(), and string_case().
{
  dfsch_signal(dfsch_condition(DFSCH_ERROR_TYPE,
                               "message", dfsch_make_string_cstr(name),
                               "object", detail,
                               NULL));
}
dfsch_object_t* dfsch_eval (dfsch_object_t * exp, dfsch_object_t * env)
Evaluate expression.
Definition at line 2543 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_parser_parse_object(), dfsch_quasiquote(), and repl_callback().
{
  return dfsch_eval_impl(exp,
                         DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                         NULL, dfsch__get_thread_info());
}
static dfsch_object_t * dfsch_eval_impl (dfsch_object_t * exp, environment_t * env, dfsch_tail_escape_t * esc, dfsch__thread_info_t * ti) [static]
Definition at line 2492 of file dfsch.c.
References DFSCH__TRACEPOINT_EVAL, dfsch_apply_impl(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIKELY, dfsch_macro_expand(), DFSCH_PAIR_P, DFSCH_SYMBOL_P, DFSCH_TYPE_OF, FORM, lookup_impl(), and MACRO.
Referenced by destructuring_eval(), dfsch_eval(), dfsch_eval_proc_impl(), dfsch_eval_tr(), and eval_list().
{
  DFSCH__TRACEPOINT_EVAL(ti, exp, env);
  if (!exp)
    return NULL;
  if(DFSCH_SYMBOL_P(exp)){
    return lookup_impl(exp, env, ti);
  }
  if(DFSCH_PAIR_P(exp)){
    object_t *f = DFSCH_FAST_CAR(exp);
    if (DFSCH_LIKELY(DFSCH_SYMBOL_P(f))){
      f = lookup_impl(f, env, ti);
    } else {
      f = dfsch_eval_impl(f , env, NULL, ti);
    }
    if (DFSCH_TYPE_OF(f) == FORM){
      return ((dfsch_form_t*)f)->impl(((dfsch_form_t*)f),
                                      env,
                                      DFSCH_FAST_CDR(exp),
                                      esc);
    }
    if (DFSCH_TYPE_OF(f) == MACRO){
      return dfsch_eval_impl(dfsch_macro_expand(f, DFSCH_FAST_CDR(exp)),
                             env,
                             esc,
                             ti);
    }
    return dfsch_apply_impl(f, DFSCH_FAST_CDR(exp), env, esc, ti);
  }
  return exp;
}
dfsch_object_t* dfsch_eval_list (dfsch_object_t * list, dfsch_object_t * env)
Evaluate multiple expressions and return values of all of them
Definition at line 2488 of file dfsch.c.
References dfsch__get_thread_info(), and eval_list().
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  return eval_list(list, env, dfsch__get_thread_info());
}
dfsch_object_t* dfsch_eval_proc (dfsch_object_t * exp, dfsch_object_t * env)
Evaluate multiple expressions returning value of final one.
Definition at line 2675 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_proc_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_force_promise(), dfsch_load_scm(), and main().
{
  return dfsch_eval_proc_impl(code,
                              DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                              NULL,
                              dfsch__get_thread_info());
}
static dfsch_object_t * dfsch_eval_proc_impl (dfsch_object_t * code, environment_t * env, tail_escape_t * esc, dfsch__thread_info_t * ti) [static]
Definition at line 2636 of file dfsch.c.
References async_apply_check(), dfsch_error(), dfsch_eval_impl(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIKELY, and DFSCH_PAIR_P.
Referenced by dfsch_apply_impl(), dfsch_eval_proc(), and dfsch_eval_proc_tr().
{
  dfsch_object_t *i;
  dfsch_object_t *old_frame;
  dfsch_object_t *my_frame;
  if (!env)
    return NULL;
  if (!code)
    return NULL;
  async_apply_check(ti);
  i = code;
  while (DFSCH_PAIR_P(i)){
    object_t* exp = DFSCH_FAST_CAR(i);
    if (DFSCH_LIKELY(DFSCH_FAST_CDR(i))) {
      dfsch_eval_impl(exp, env, NULL, ti);
    } else {
      return dfsch_eval_impl(exp, env, esc, ti);
    }
    i = DFSCH_FAST_CDR(i);
  }
  dfsch_error("eval-proc called on improper list", code);
}
dfsch_object_t* dfsch_eval_proc_tr (dfsch_object_t * code, dfsch_object_t * env, dfsch_tail_escape_t * esc)
Extended variant of dfsch_eval_proc with support for tail recursion
Definition at line 2667 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_proc_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_eval_proc().
{
  return dfsch_eval_proc_impl(code,
                              DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                              esc,
                              dfsch__get_thread_info());
}
dfsch_object_t* dfsch_eval_tr (dfsch_object_t * exp, dfsch_object_t * env, dfsch_tail_escape_t * esc)
Extended variant of dfsch_eval with support for tail recursion
Definition at line 2536 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_eval().
{
  return dfsch_eval_impl(exp,
                         DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                         esc, dfsch__get_thread_info());
}
dfsch_slot_t* dfsch_find_slot (dfsch_type_t * type, char * name)
Definition at line 342 of file dfsch.c.
References dfsch_error(), dfsch_make_symbol(), dfsch_slot_t::name, dfsch_type_t::slots, dfsch_type_t::superclass, and dfsch_slot_t::type.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_slot_ref_by_name(), and dfsch_slot_set_by_name().
{
  dfsch_slot_t* i;
  while(type){
    if (type->slots){
    i = type->slots;
    while (i->type){
      if (strcmp(i->name, name)==0){
        return i;
      }
      i++;
    }
    }
    type = type->superclass;
  }
  dfsch_error("No such slot", dfsch_make_symbol(name));
}
int dfsch_form_p (dfsch_object_t * obj)
Is OBJ a special form?
Definition at line 863 of file dfsch.c.
References DFSCH_TYPE_OF, and FORM.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == FORM;
}
int dfsch_function_p (dfsch_object_t * obj)
Definition at line 853 of file dfsch.c.
References DFSCH_TYPE_OF, and FUNCTION.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == FUNCTION;
}
dfsch_object_t* dfsch_gensym ()
Returns unique generated symbol.
Definition at line 1764 of file dfsch.c.
References dfsch__symbol_t::data, and DFSCH_TAG_ENCODE.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_make_symbol().
{
  symbol_t *s = GC_NEW(symbol_t);
  s->data = NULL;
  return DFSCH_TAG_ENCODE(s, 2);
}
dfsch_object_t* dfsch_get_environment_variables (dfsch_object_t * env)
Definition at line 2377 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_2_alist(), and environment_t::values.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  environment_t* e = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  return dfsch_eqhash_2_alist(&e->values);
}
dfsch_object_t* dfsch_get_list_annotation (dfsch_object_t * list)
Definition at line 1204 of file dfsch.c.
References DFSCH__FAST_CDR_CODED_P, dfsch_cons(), DFSCH_INVALID_OBJECT, DFSCH_PAIR_P, and DFSCH_PAIR_REF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_format_trace(), and dfsch_print_trace_buffer().
{
  dfsch_object_t** i;
  if (!DFSCH_PAIR_P(list) || !DFSCH__FAST_CDR_CODED_P(list)){
    return NULL;
  }
  i = (dfsch_object_t**) DFSCH_PAIR_REF(list);
  while (*i != DFSCH_INVALID_OBJECT){
    i++;
  }
  /* i[1] is last CDR */
  if (i[2] || i[3]){
    return dfsch_cons(i[2], i[3]);
  } else {
    return NULL;
  }
}
char* dfsch_get_next_symbol (dfsch_symbol_iter_t ** iter)
Iterates over all symbols known by interpreter. And returns one per call, useful for things like completion. ITER is pointer to dfsch_symbol_iter_t*, when its value is NULL, new iterator is allocated. NULL is returned, when no more symbols are avaiable.
Definition at line 1835 of file dfsch.c.
References dfsch__symbol_t::data, hash_entry_t::entry, HASH_SIZE, and hash_entry_t::next.
                                                       { // deep magic
  if (*iter == NULL){
    *iter = GC_MALLOC(sizeof(dfsch_symbol_iter_t));
    (*iter)->bucket = 0;
    (*iter)->item = global_symbol_hash[(*iter)->bucket];
  }
  while ((*iter)->bucket < HASH_SIZE){
    if (!(*iter)->item){
      (*iter)->bucket ++;
      (*iter)->item = global_symbol_hash[(*iter)->bucket];
    }else{
      hash_entry_t *i = (*iter)->item;
      (*iter)->item = (*iter)->item->next;
      return i->entry->data;
    }
  }
  return NULL;
}
dfsch_object_t* dfsch_get_slots (dfsch_type_t * type)
Definition at line 318 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CDR_MUT, and dfsch_slot_t::type.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_slot_t* i;
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  dfsch_object_t* tmp;
  while(type){
    if (type->slots){
      i = type->slots;
      while (i->type){
        tmp = dfsch_cons((dfsch_object_t*)i, NULL);
        if (!head) {
          head = tail = tmp;
        } else {
          DFSCH_FAST_CDR_MUT(tail) = tmp;
          tail = tmp;
        }
        i++;
      }
    }
    type = type->superclass;
  }
  return head;
}
uint32_t dfsch_hash (dfsch_object_t * obj)
Get object hash
Definition at line 147 of file dfsch.c.
References DFSCH_TYPE_OF, and ptr_hash().
Referenced by DFSCH_DEFINE_PRIMITIVE(), fracnum_hash(), pair_hash(), and vector_hash().
{
  if (!obj){
    return 0;
  }
  if (!DFSCH_TYPE_OF(obj) || !DFSCH_TYPE_OF(obj)->hash){
    return ptr_hash(obj);
  }
  return DFSCH_TYPE_OF(obj)->hash(obj);
}
int dfsch_instance_p (dfsch_object_t * obj, dfsch_type_t * type)
Is object direct or indirect instance of given type?
Definition at line 183 of file dfsch.c.
References dfsch_superclass_p(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_superclass_p(DFSCH_TYPE_OF(obj), type);
}
dfsch_object_t* dfsch_lambda (dfsch_object_t * env, dfsch_object_t * args, dfsch_object_t * code)
Create new lambda closure.
Definition at line 1880 of file dfsch.c.
References dfsch_named_lambda().
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  return dfsch_named_lambda(env, args, code, NULL);
}
dfsch_object_t* dfsch_list (size_t count, ...)
Construct list from arguments
Definition at line 1333 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, and dfsch_multicons().
Referenced by character_data_handler(), destructure_impl(), destructuring_eval(), dfsch_collections_priority_queue_push(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_eqhash_2_alist(), dfsch_hash_2_alist(), dfsch_hash_ref(), dfsch_http_query_2_alist(), dfsch_load_extend_path(), dfsch_load_register(), dfsch_perform_tr(), dfsch_quasiquote(), dfsch_sort_list(), dfsch_sxml_emit_file(), dfsch_sxml_parse_file(), dfsch_xml_parse_file(), dfsch_xml_signal_error(), end_element_handler(), errno_error(), http_split_query(), lisp_callback(), native_pipe(), native_wait(), native_waitpid(), start_element_handler(), wrapper_apply(), wrapper_equal_p(), wrapper_hash(), and wrapper_write().
{
  dfsch_object_t *head;
  dfsch_object_t *cur;
  size_t i;
  va_list al;
  va_start(al,count);
  if (count == 0)
    return NULL;
  head = cur = dfsch_multicons(count);
  for(i = 0; i < count; ++i){
    DFSCH_FAST_CAR(cur) = va_arg(al, dfsch_object_t*);
    cur = DFSCH_FAST_CDR(cur);
  }
  va_end(al);
  return head;
}
dfsch_object_t* dfsch_list_2_vector (dfsch_object_t * list)
Converts list to vector.
Definition at line 2118 of file dfsch.c.
References vector_t::data, dfsch_list_as_array(), dfsch_make_object_var(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_parser_parse_object().
{
  vector_t* vector;
  size_t length;
  dfsch_object_t** array;
  array = dfsch_list_as_array(list, &length);
  vector = (vector_t*)dfsch_make_object_var(VECTOR,
                                            length * sizeof(dfsch_object_t*));
  vector->length = length;
  memcpy(vector->data, array, sizeof(dfsch_object_t*) * length);
  return (object_t*)vector;
}
dfsch_object_t* dfsch_list_annotate (dfsch_object_t * list, dfsch_object_t * source, dfsch_object_t * location)
Definition at line 1170 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_INVALID_OBJECT, dfsch_list_length(), DFSCH_MAKE_CLIST, and DFSCH_PAIR_P.
Referenced by parse_close().
{
  dfsch_object_t* j = list;
  size_t i=0;
  size_t len;
  object_t** data;
  int proper;
  if (list == NULL){
    return NULL;
  }
  len = dfsch_list_length(list, &proper);
  data = GC_MALLOC(sizeof(object_t*)*(len+4));
  while (DFSCH_PAIR_P(j)){
    if (i >= len){
      break; /* Can happen due to race condition in user code */
    }
    data[i] = DFSCH_FAST_CAR(j);
    j = DFSCH_FAST_CDR(j);
    i++;
  }
  data[i] = DFSCH_INVALID_OBJECT;
  data[i+1] = j;
  data[i+2] = source;
  data[i+3] = location;
  return DFSCH_MAKE_CLIST(data);
}
dfsch_object_t** dfsch_list_as_array (dfsch_object_t * list, size_t * length)
Convert struct to C array
Definition at line 1107 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_list_length_check(), and DFSCH_PAIR_P.
Referenced by dfsch_list_2_vector(), dfsch_list_2_weak_vector(), and dfsch_zip().
{
  dfsch_object_t* j = list;
  size_t i=0;
  size_t len;
  object_t** data;
  len = dfsch_list_length_check(list);
  data = GC_MALLOC(sizeof(object_t*)*len);
  while (DFSCH_PAIR_P(j)){
    if (i >= len){
      break; /* Can happen due to race condition in user code */
    }
    data[i] = DFSCH_FAST_CAR(j);
    j = DFSCH_FAST_CDR(j);
    i++;
  }
  if (length){
    *length = len;
  }
  return data;
}
dfsch_object_t* dfsch_list_copy (dfsch_object_t * list)
Copy list.
Definition at line 1356 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_ensure_mutable_list().
{
  dfsch_object_t *head;
  dfsch_object_t *tail;
  dfsch_object_t *i =  list;
  head = tail = NULL;
  while(DFSCH_PAIR_P(i)){
    if (head){
      object_t* tmp = dfsch_cons(DFSCH_FAST_CAR(i),NULL);
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    }else{
      head = tail = dfsch_cons(DFSCH_FAST_CAR(i),NULL);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i && !DFSCH_PAIR_P(i)){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return (object_t*)head;
}
dfsch_object_t* dfsch_list_copy_immutable (dfsch_object_t * list)
Definition at line 1132 of file dfsch.c.
References dfsch_car(), dfsch_cdr(), dfsch_cons_immutable(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_INVALID_OBJECT, dfsch_list_length(), DFSCH_MAKE_CLIST, and DFSCH_PAIR_P.
{
  dfsch_object_t* j = list;
  size_t i=0;
  size_t len;
  object_t** data;
  int proper;
  if (list == NULL){
    return NULL;
  }
  len = dfsch_list_length(list, &proper);
  if (len == 1){
    return dfsch_cons_immutable(dfsch_car(list),
                                dfsch_cdr(list));
  }
  data = GC_MALLOC(sizeof(object_t*)*(len+4));
  while (DFSCH_PAIR_P(j)){
    if (i >= len){
      break; /* Can happen due to race condition in user code */
    }
    data[i] = DFSCH_FAST_CAR(j);
    j = DFSCH_FAST_CDR(j);
    i++;
  }
  data[i] = DFSCH_INVALID_OBJECT;
  i++;
  data[i] = j;
  data[i+1] = NULL;
  data[i+2] = NULL;
  return DFSCH_MAKE_CLIST(data);
}
dfsch_object_t* dfsch_list_from_array (dfsch_object_t ** array, size_t length)
Construct list from C array.
Definition at line 1090 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, and dfsch_multicons().
Referenced by dfsch_vector_2_list(), and dfsch_weak_vector_2_list().
{
  dfsch_object_t *head;
  dfsch_object_t *cur;
  size_t i;
  if (length == 0)
    return NULL;
  head = cur = dfsch_multicons(length);
  for(i = 0; i < length; ++i){
    DFSCH_FAST_CAR(cur) = array[i];
    cur = DFSCH_FAST_CDR(cur);
  }
  return (object_t*)head;
}
dfsch_object_t* dfsch_list_item (dfsch_object_t * list, int index)
Returns given item of list.
Definition at line 1077 of file dfsch.c.
References dfsch_car(), dfsch_error(), DFSCH_FAST_CDR, dfsch_make_number_from_long(), and DFSCH_PAIR_P.
Referenced by debug_invoke_restart(), dfsch_alist_2_hash(), DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* it = list;
  int i;
  for (i=0; i<index; ++i){
    if (DFSCH_PAIR_P(it)){
      it = DFSCH_FAST_CDR(it);
    }else{
      dfsch_error("No such item of list", dfsch_make_number_from_long(index));
    }
  }
  return dfsch_car(it);
}
long dfsch_list_length (dfsch_object_t * list, int * proper)
Returns number of items in given list or -1 for infinite lists
Definition at line 981 of file dfsch.c.
References DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by dfsch_list_annotate(), dfsch_list_copy_immutable(), dfsch_list_length_check(), and emit_attrs().
{
  dfsch_object_t *i;
  dfsch_object_t *j;
  long count;
  if (!list)
    return 0;
  if (!DFSCH_PAIR_P(list))
    return -1;
  i = j = list;
  count = 0;
  while (DFSCH_PAIR_P(i)){
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return -1;
    }
    j = DFSCH_FAST_CDR(j);
    if (!DFSCH_PAIR_P(i)){
      break;
    }
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return -1;
    }
  }
  if (proper){
    *proper = (i == NULL);
  } else {
    if (i) {
      return -1;
    }
  }
  return count;
}
long dfsch_list_length_check (dfsch_object_t * list)
Returns number of items in given finite list, fail otherwise
Definition at line 1069 of file dfsch.c.
References dfsch_list_length(), DFSCH_LIST_TYPE, and dfsch_type_error().
Referenced by command_exit(), DFSCH_DEFINE_PRIMITIVE(), dfsch_ensure_mutable_list(), dfsch_list_2_string(), dfsch_list_as_array(), make_bignum_from_digits(), and make_slots().
{
  long len;
  len = dfsch_list_length(list, NULL);
  if (len < 0)
    dfsch_type_error(list, DFSCH_LIST_TYPE, 1);
  return len;
}
long dfsch_list_length_fast (dfsch_object_t * list)
Returns number of items in given finite list
Definition at line 961 of file dfsch.c.
References DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by dfsch_compile_lambda_list().
{
  dfsch_object_t *i;
  long count;
  if (!list)
    return 0;
  if (!DFSCH_PAIR_P(list))
    return -1;
  i = list;
  count = 0;
  while (DFSCH_PAIR_P(i)){
    i = DFSCH_FAST_CDR(i);
    ++count;
  }
  return count;
}
int dfsch_list_mutable_p (dfsch_object_t * list)
Check whenever list is mutable
Definition at line 1023 of file dfsch.c.
References DFSCH_FAST_CDR, DFSCH_MUTABLE_PAIR_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_ensure_mutable_list().
{
  dfsch_object_t *i;
  dfsch_object_t *j;
  long count;
  if (!list)
    return 1;
  if (DFSCH_TYPE_OF(list) != DFSCH_MUTABLE_PAIR_TYPE){
    return 0;
  }
  i = j = list;
  count = 0;
  while (DFSCH_TYPE_OF(i) == DFSCH_MUTABLE_PAIR_TYPE){
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return 0;
    }
    j = DFSCH_FAST_CDR(j);
    if (DFSCH_TYPE_OF(i) != DFSCH_MUTABLE_PAIR_TYPE){
      break;
    }
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return 0;
    }
  }
  if (i)
    return 0;
  return 1;
}
int dfsch_list_p (dfsch_object_t * obj)
Is OBJ a proper list?
Definition at line 840 of file dfsch.c.
References DFSCH_INSTANCE_P, and DFSCH_LIST_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_LIST_TYPE);
}
object_t* dfsch_lookup (dfsch_object_t * name, dfsch_object_t * env)
Get value of variable name in environment env.
Definition at line 2266 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and lookup_impl().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_lookup_cstr().
{
  return lookup_impl(name,
                     DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                     dfsch__get_thread_info());
}
dfsch_object_t* dfsch_lookup_cstr (dfsch_object_t * ctx, char * name)
Looks up value of variable given by NAME. Throws exception:unbound-variable if such variable doesn't exist
Definition at line 2866 of file dfsch.c.
References dfsch_lookup(), and dfsch_make_symbol().
{
  return dfsch_lookup(dfsch_make_symbol(name), ctx);
}
dfsch_object_t* dfsch_macro_expand (dfsch_object_t * macro, dfsch_object_t * args)
Definition at line 2382 of file dfsch.c.
References dfsch_apply(), DFSCH_ASSERT_TYPE, and MACRO.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_eval_impl().
{
  return dfsch_apply(((macro_t*)DFSCH_ASSERT_TYPE(macro, MACRO))->proc, args);
}
int dfsch_macro_p (dfsch_object_t * obj)
Is OBJ a macro?
Definition at line 860 of file dfsch.c.
References DFSCH_TYPE_OF, and MACRO.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == MACRO;
}
dfsch_object_t* dfsch_make_context ()
Allocates new top-level context (environment).
Definition at line 2801 of file dfsch.c.
References dfsch__native_register(), DFSCH_ABSTRACT_TYPE, DFSCH_BOOLEAN_SLOT_TYPE, dfsch_define_cstr(), DFSCH_EMPTY_LIST_TYPE, DFSCH_ENVIRONMENT_TYPE, DFSCH_FORM_REF, DFSCH_FORM_TYPE, DFSCH_FUNCTION_TYPE, DFSCH_IMMUTABLE_PAIR_TYPE, DFSCH_INT_SLOT_TYPE, DFSCH_LIST_TYPE, DFSCH_LONG_SLOT_TYPE, DFSCH_MACRO_TYPE, dfsch_make_primitive(), dfsch_make_string_cstr(), DFSCH_META_TYPE, DFSCH_MUTABLE_PAIR_TYPE, dfsch_new_frame(), DFSCH_OBJECT_SLOT_TYPE, DFSCH_PAIR_TYPE, DFSCH_PRIMITIVE_TYPE, DFSCH_SIZE_T_SLOT_TYPE, DFSCH_SLOT_TYPE, DFSCH_SLOT_TYPE_TYPE, DFSCH_SPECIAL_TYPE, DFSCH_STANDARD_FUNCTION_TYPE, DFSCH_STRING_SLOT_TYPE, DFSCH_SYMBOL_TYPE, DFSCH_VECTOR_TYPE, HOST_TRIPLET, native_top_level_environment(), and PACKAGE_VERSION.
Referenced by debug_main(), DFSCH_DEFINE_PRIMITIVE(), and main().
{
  dfsch_object_t* ctx;
  ctx = dfsch_new_frame(NULL);
  dfsch_define_cstr(ctx, "<standard-type>", DFSCH_STANDARD_TYPE);
  dfsch_define_cstr(ctx, "<abstract-type>", DFSCH_ABSTRACT_TYPE);
  dfsch_define_cstr(ctx, "<meta-type>", DFSCH_META_TYPE);
  dfsch_define_cstr(ctx, "<special-type>", DFSCH_SPECIAL_TYPE);
  dfsch_define_cstr(ctx, "<standard-function>", DFSCH_STANDARD_FUNCTION_TYPE);
  dfsch_define_cstr(ctx, "<slot-type>", DFSCH_SLOT_TYPE_TYPE);
  dfsch_define_cstr(ctx, "<slot>", DFSCH_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<object-slot>", DFSCH_OBJECT_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<boolean-slot>", DFSCH_BOOLEAN_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<string-slot>", DFSCH_STRING_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<size_t-slot>", DFSCH_SIZE_T_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<int-slot>", DFSCH_INT_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<long-slot>", DFSCH_LONG_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<list>", DFSCH_LIST_TYPE);
  dfsch_define_cstr(ctx, "<pair>", DFSCH_PAIR_TYPE);
  dfsch_define_cstr(ctx, "<mutable-pair>", DFSCH_MUTABLE_PAIR_TYPE);
  dfsch_define_cstr(ctx, "<immutable-pair>", DFSCH_IMMUTABLE_PAIR_TYPE);
  dfsch_define_cstr(ctx, "<empty-list>", DFSCH_EMPTY_LIST_TYPE);
  dfsch_define_cstr(ctx, "<symbol>", DFSCH_SYMBOL_TYPE);
  dfsch_define_cstr(ctx, "<primitive>", DFSCH_PRIMITIVE_TYPE);
  dfsch_define_cstr(ctx, "<function>", DFSCH_FUNCTION_TYPE);
  dfsch_define_cstr(ctx, "<macro>", DFSCH_MACRO_TYPE);
  dfsch_define_cstr(ctx, "<form>", DFSCH_FORM_TYPE);
  dfsch_define_cstr(ctx, "<vector>", DFSCH_VECTOR_TYPE);
  dfsch_define_cstr(ctx, "<environment>", DFSCH_ENVIRONMENT_TYPE);
  dfsch_define_cstr(ctx, "top-level-environment",
                    dfsch_make_primitive(&native_top_level_environment, ctx));
  dfsch_define_cstr(ctx, "current-environment",
                    DFSCH_FORM_REF(current_environment));
  dfsch_define_cstr(ctx,"*dfsch-version*",dfsch_make_string_cstr(PACKAGE_VERSION));
  dfsch_define_cstr(ctx,"*dfsch-platform*",dfsch_make_string_cstr(HOST_TRIPLET));
  dfsch__native_register(ctx);
  return ctx;
}
dfsch_object_t* dfsch_make_form (dfsch_form_impl_t impl, void * baton, char * name)
Wraps procedure for use as special form.
Definition at line 1918 of file dfsch.c.
References dfsch_form_t::baton, dfsch_make_object(), FORM, dfsch_form_t::impl, and dfsch_form_t::name.
{
  dfsch_form_t *f = (dfsch_form_t*)dfsch_make_object(FORM);
  f->impl = impl;
  f->baton = baton;
  f->name = name;
  return (object_t*)f;
}
object_t* dfsch_make_macro (dfsch_object_t * proc)
Wraps procedure for use as macro.
Definition at line 1908 of file dfsch.c.
References dfsch_make_object(), MACRO, and macro_t::proc.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  macro_t *m = (macro_t*)dfsch_make_object(MACRO);
  if (!m)
    return NULL;
  m->proc = proc;
  return (object_t*)m;
}
object_t* dfsch_make_object (const dfsch_type_t * type)
Create object of given type.
Definition at line 71 of file dfsch.c.
References dfsch_make_object_var().
Referenced by dfsch_channel_create(), dfsch_cmdopts_make_parser(), dfsch_collections_make_priority_queue(), dfsch_condition_create(), dfsch_hash_make(), dfsch_make_class(), dfsch_make_condition(), dfsch_make_decoded_time(), dfsch_make_default_random_state(), dfsch_make_file_port(), dfsch_make_file_random_state(), dfsch_make_form(), dfsch_make_instance(), dfsch_make_macro(), dfsch_make_number_from_double(), dfsch_make_primitive_flags(), dfsch_make_promise(), dfsch_make_restart(), dfsch_make_string_nocopy(), dfsch_make_weak_key_hash(), dfsch_make_weak_vector(), dfsch_make_wrapper_type(), dfsch_make_writer_state(), dfsch_mutex_create(), dfsch_named_lambda(), dfsch_regex_compile(), dfsch_string_input_port(), dfsch_string_list_append(), dfsch_string_output_port(), dfsch_thread_create(), dfsch_thread_self(), dfsch_unix_make_stat_struct(), dfsch_unix_opendir(), dfsch_weak_vector_from_array(), dfsch_wrap(), dfsch_xml_make_parser(), frac_cons(), and spawn_port().
{
  return dfsch_make_object_var(type, 0);
}
dfsch_object_t* dfsch_make_object_var (const dfsch_type_t * type, size_t size)
Definition at line 54 of file dfsch.c.
References dfsch_type_t::name, dfsch_type_t::size, and dfsch_object_t::type.
Referenced by dfsch_compile_lambda_list(), dfsch_list_2_vector(), dfsch_make_object(), dfsch_make_vector(), dfsch_vector(), dfsch_vector_from_array(), and make_bignum().
{
  object_t* o = GC_MALLOC(type->size + size);
  if (!o)
    return NULL;
  o->type = (dfsch_type_t*)type;
#ifdef ALLOC_DEBUG
  obj_count ++;
  obj_size += type->size;
  printf(";; Alloc'd: #<%s 0x%x> serial %d arena %d\n", type->name, o,
         obj_count, obj_size);
#endif
  return o;
}
object_t* dfsch_make_primitive (dfsch_primitive_impl_t prim, void * baton)
Create native function object
Definition at line 1888 of file dfsch.c.
References dfsch_make_primitive_flags().
Referenced by debug_main(), dfsch__control_register(), dfsch__format_native_register(), dfsch__hash_native_register(), dfsch__native_cxr_register(), dfsch__port_native_register(), dfsch__promise_native_register(), dfsch__string_native_register(), dfsch__system_register(), dfsch__weak_native_register(), dfsch__wrapper_native_register(), dfsch_load_register(), dfsch_make_context(), dfsch_make_throw_proc(), dfsch_make_throw_proc_arg(), dfsch_module_inet_register(), dfsch_module_regex_register(), dfsch_module_threads_register(), dfsch_module_unix_register(), dfsch_port_unsafe_register(), load_scm(), and main().
{
  return dfsch_make_primitive_flags(prim, baton, 0);
}
object_t* dfsch_make_primitive_flags (dfsch_primitive_impl_t prim, void * baton, int flags)
Create native function object
Definition at line 1892 of file dfsch.c.
References dfsch_primitive_t::baton, dfsch_make_object(), dfsch_primitive_t::flags, PRIMITIVE, and dfsch_primitive_t::proc.
Referenced by dfsch_make_primitive().
{
  primitive_t* p = (primitive_t*)dfsch_make_object(PRIMITIVE);
  if (!p)
    return NULL;
  p->proc = prim;
  p->baton = baton;
  p->flags = 0;
  return (object_t*)p;
}
dfsch_object_t* dfsch_make_symbol (char * symbol)
Makes symbol object from string.
Definition at line 1772 of file dfsch.c.
References dfsch_gensym(), DFSCH_TAG_ENCODE, gsh_check_init(), lookup_symbol(), and make_symbol().
Referenced by debug_main(), dfsch_assert_instance(), dfsch_assert_type(), dfsch_cerror(), dfsch_condition_field_cstr(), dfsch_condition_put_field_cstr(), dfsch_console_read_objects(), dfsch_console_read_objects_parser(), dfsch_define_cstr(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_env_get_cstr(), dfsch_find_slot(), dfsch_get_trace(), dfsch_lookup_cstr(), dfsch_parser_define_directive_cstr(), dfsch_set_cstr(), main(), make_symbol(), native_alist_2_hash(), native_make_hash(), and start_element_handler().
{
  symbol_t *s;
  if (!symbol){
    return dfsch_gensym();
  }
  pthread_mutex_lock(&symbol_lock);
  gsh_check_init();
  // This code is slow already, so this check does not matter (too much)
  s = lookup_symbol(symbol);
  pthread_mutex_unlock(&symbol_lock);
  if (!s)
    s = make_symbol(symbol);
  return DFSCH_TAG_ENCODE(s, 2);
}
dfsch_object_t* dfsch_make_vector (size_t length, dfsch_object_t * fill)
Create vector
Definition at line 2032 of file dfsch.c.
References vector_t::data, dfsch_make_object_var(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and regex_substrings().
{
  vector_t* v;
  size_t i;
  v = (vector_t*)dfsch_make_object_var(VECTOR,
                                       length * sizeof(dfsch_object_t*));
  v->length = length;
  for(i = 0; i<length; ++i){
    v->data[i] = fill;
  }
  return (object_t*)v;
}
dfsch_object_t* dfsch_member (dfsch_object_t * key, dfsch_object_t * alist)
Return first cell of list with car equal? to key
Definition at line 1399 of file dfsch.c.
References dfsch_equal_p(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=list;
  while (DFSCH_PAIR_P(i)){
    if (dfsch_equal_p(key, DFSCH_FAST_CAR(i))){
      return (object_t*)i;
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return NULL;
}
dfsch_object_t* dfsch_memq (dfsch_object_t * key, dfsch_object_t * alist)
Return first cell of list with car eq? to key
Definition at line 1439 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=list;
  while (DFSCH_PAIR_P(i)){
    if (key == DFSCH_FAST_CAR(i)){
      return (object_t*)i;
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return NULL;
}
dfsch_object_t* dfsch_memv (dfsch_object_t * key, dfsch_object_t * alist)
Return first cell of list with car eqv? to key
Definition at line 1419 of file dfsch.c.
References dfsch_eqv_p(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=list;
  while (DFSCH_PAIR_P(i)){
    if (dfsch_eqv_p(key, DFSCH_FAST_CAR(i))){
      return (object_t*)i;
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return NULL;
}
dfsch_object_t* dfsch_multicons (size_t n)
Definition at line 919 of file dfsch.c.
References dfsch_pair_t::cdr, and DFSCH_TAG_ENCODE.
Referenced by dfsch_list(), and dfsch_list_from_array().
{
  size_t i;
  dfsch_pair_t* p;
  if (n == 0){
    return NULL;
  }
  p = GC_MALLOC(sizeof(dfsch_pair_t)*n);
  for (i = 0; i < (n-1); i++){
    p[i].cdr = DFSCH_TAG_ENCODE(&(p[i+1]), 1);
  }
  return DFSCH_TAG_ENCODE(&(p[0]), 1);
}
dfsch_object_t* dfsch_named_lambda (dfsch_object_t * env, dfsch_object_t * args, dfsch_object_t * code, dfsch_object_t * name)
Create new named lambda closure.
Definition at line 1857 of file dfsch.c.
References closure_t::args, closure_t::code, DFSCH_ASSERT_TYPE, dfsch_compile_lambda_list(), DFSCH_ENVIRONMENT_TYPE, DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_object(), DFSCH_PAIR_P, DFSCH_STANDARD_FUNCTION_TYPE, dfsch_string_p(), closure_t::documentation, closure_t::env, closure_t::name, and closure_t::orig_code.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_lambda().
{
  closure_t *c = (closure_t*)dfsch_make_object(DFSCH_STANDARD_FUNCTION_TYPE);
  c->env = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  c->args = (lambda_list_t*)dfsch_compile_lambda_list(args);
  c->orig_code = code;
  if (DFSCH_PAIR_P(code) && dfsch_string_p(DFSCH_FAST_CAR(code))){
    c->code = DFSCH_FAST_CDR(code);
    c->documentation = DFSCH_FAST_CAR(code);
  } else {
    c->code = code;
    c->documentation = NULL;
  }
  c->name = name;
  return (object_t*)c;
}
dfsch_object_t* dfsch_new_frame (dfsch_object_t * parent)
Create new environment frame.
Definition at line 2221 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and new_frame_impl().
Referenced by debug_main(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_destructuring_bind(), and dfsch_make_context().
{
  if (parent){
    parent = DFSCH_ASSERT_TYPE(parent, DFSCH_ENVIRONMENT_TYPE);
  }
  return (dfsch_object_t*)new_frame_impl((environment_t*)parent,
                                         dfsch__get_thread_info());
}
dfsch_object_t* dfsch_nil ()
Returns empty list, equivalent to NULL
Definition at line 872 of file dfsch.c.
{
  return NULL;
}
int dfsch_null_p (dfsch_object_t * obj)
Is OBJ null?
Definition at line 834 of file dfsch.c.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return !obj;
}
char* dfsch_object_2_string (dfsch_object_t * obj, int max_depth, int readable)
Definition at line 2130 of file dfsch.c.
References dfsch_make_writer_state(), DFSCH_PRINT, DFSCH_WRITE, dfsch_write_object(), sl_append, sl_create, and sl_value.
Referenced by command_exit(), command_print(), command_write(), debug_main(), DFSCH_DEFINE_PRIMITIVE(), dfsch_format(), dfsch_format_trace(), dfsch_number_to_string(), dfsch_print_trace_buffer(), dfsch_signal(), dfsch_type_error(), format_a(), format_s(), format_w(), format_y(), main(), native_display(), native_write(), prettyprint_condition_fields(), and repl_callback().
{
  str_list_t* sl = sl_create();
  dfsch_writer_state_t* state = dfsch_make_writer_state(max_depth,
                                                        readable?
                                                        DFSCH_WRITE:
                                                        DFSCH_PRINT,
                                                        sl_append,
                                                        sl);
  dfsch_write_object(state, obj);
  return sl_value(sl);
}
dfsch_type_t* dfsch_object_as_type (dfsch_object_t * obj)
Definition at line 162 of file dfsch.c.
References DFSCH_ASSERT_INSTANCE, and DFSCH_STANDARD_TYPE.
Referenced by dfsch_superclass().
{
  return (dfsch_type_t*)DFSCH_ASSERT_INSTANCE(obj, DFSCH_STANDARD_TYPE);
}
int dfsch_pair_p (dfsch_object_t * obj)
Is OBJ a pair?
Definition at line 837 of file dfsch.c.
References DFSCH_PAIR_P.
Referenced by command_print(), command_write(), dfsch_alist_2_hash(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_2_string_utf8(), dfsch_load(), dfsch_parser_parse_object(), dfsch_quasiquote(), directive_import(), and process_directive().
{
  return DFSCH_PAIR_P(obj);
}
int dfsch_primitive_p (dfsch_object_t * obj)
Is OBJ a primitive (native) function?
Definition at line 849 of file dfsch.c.
References DFSCH_TYPE_OF, and PRIMITIVE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == PRIMITIVE;
}
int dfsch_procedure_p (dfsch_object_t * obj)
Is OBJ an applicable procedure?
Definition at line 856 of file dfsch.c.
References DFSCH_TYPE_OF, FUNCTION, and PRIMITIVE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return (DFSCH_TYPE_OF(obj) == PRIMITIVE || DFSCH_TYPE_OF(obj) == FUNCTION) ||
    (DFSCH_TYPE_OF(obj)->apply);
}
dfsch_object_t* dfsch_quasiquote (dfsch_object_t * env, dfsch_object_t * arg)
Expand quasi-quoted expression
Definition at line 2769 of file dfsch.c.
References dfsch_append(), dfsch_car(), dfsch_cdr(), dfsch_cons(), dfsch_eval(), dfsch_list(), dfsch_pair_p(), dfsch_quasiquote(), DFSCH_SYM_UNQUOTE, and DFSCH_SYM_UNQUOTE_SPLICING.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_quasiquote().
{
  if (dfsch_pair_p(arg)){
    object_t* car = dfsch_car(arg);
    object_t* cdr = dfsch_cdr(arg);
    if (car == DFSCH_SYM_UNQUOTE && dfsch_pair_p(cdr)){
      return dfsch_eval(dfsch_car(cdr), env);
    }else if (dfsch_pair_p(car)){
      if (dfsch_car(car) == DFSCH_SYM_UNQUOTE_SPLICING){
        return dfsch_append(dfsch_list(2,
                                       dfsch_eval(dfsch_car(dfsch_cdr(car)),
                                                  env),
                                       dfsch_quasiquote(env, cdr)));
      }
    }
    return dfsch_cons(dfsch_quasiquote(env,car), dfsch_quasiquote(env,cdr));
  }else{
    return arg;
  }
}
dfsch_object_t* dfsch_reverse (dfsch_object_t * list)
Reverses list
Definition at line 1382 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  object_t *head;
  dfsch_object_t *i =  list;
  head = NULL;
  while(DFSCH_PAIR_P(i)){
    head = dfsch_cons(DFSCH_FAST_CAR(i), head);
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return (object_t*)head;
}
object_t* dfsch_set (dfsch_object_t * name, dfsch_object_t * value, dfsch_object_t * env)
Set value of variable name in environment env to value.
Definition at line 2291 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_set_if_exists(), dfsch_error(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, environment_t::owner, environment_t::parent, and environment_t::values.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_set_cstr().
{
  environment_t *i;
  dfsch__thread_info_t *ti = dfsch__get_thread_info();
  i = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  while (i){
    if (i->owner != ti){
      i->owner = NULL;
      goto lock;
    }
    if(dfsch_eqhash_set_if_exists(&i->values, name, value, NULL))
      return value;
    i = i->parent;
  }
  dfsch_error("Unbound variable",name);
 lock:
  DFSCH_RWLOCK_WRLOCK(&environment_rwlock);
  while (i){
    if(dfsch_eqhash_set_if_exists(&i->values, name, value, NULL)){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return value;
    }
    i->owner = NULL;
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  dfsch_error("Unbound variable",name);
}
dfsch_object_t* dfsch_set_car (dfsch_object_t * pair, dfsch_object_t * c)
Set first (car) item of pair
Definition at line 945 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_FAST_CAR, and DFSCH_MUTABLE_PAIR_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* p = DFSCH_ASSERT_TYPE(pair, DFSCH_MUTABLE_PAIR_TYPE);
  DFSCH_FAST_CAR(p) = car;
  return p;
}
dfsch_object_t* dfsch_set_cdr (dfsch_object_t * pair, dfsch_object_t * c)
Set second (cdr) item of pair
Definition at line 953 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_FAST_CDR_MUT, and DFSCH_MUTABLE_PAIR_TYPE.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_http_query_2_alist(), dfsch_http_split_path(), dfsch_parser_parse_object(), load_callback(), and read_callback().
{
  dfsch_object_t* p = DFSCH_ASSERT_TYPE(pair, DFSCH_MUTABLE_PAIR_TYPE);
  DFSCH_FAST_CDR_MUT(p) = cdr;
  return p;
}
dfsch_object_t* dfsch_set_cstr (dfsch_object_t * env, char * name, dfsch_object_t * obj)
Change value of variable.
Definition at line 2857 of file dfsch.c.
References dfsch_make_symbol(), and dfsch_set().
Referenced by dfsch_load_extend_path().
{
  return dfsch_set(dfsch_make_symbol(name),
                   obj,
                   ctx);
}
dfsch_object_t* dfsch_slot_ref (dfsch_object_t * obj, dfsch_slot_t * slot, int debug)
Definition at line 360 of file dfsch.c.
References dfsch_slot_t::access, dfsch_error(), DFSCH_SLOT_ACCESS_DEBUG_READ, dfsch_slot_t::offset, dfsch_slot_type_t::ref, and dfsch_slot_t::type.
Referenced by dfsch_slot_ref_by_name().
{
  if (!debug && slot->access == DFSCH_SLOT_ACCESS_DEBUG_READ) {
    dfsch_error("Slot not accesible", (dfsch_object_t*)slot);
  }
  return slot->type->ref(((char*) obj)+slot->offset);
}
dfsch_object_t* dfsch_slot_ref_by_name (dfsch_object_t * obj, char * slot, int debug)
Definition at line 379 of file dfsch.c.
References dfsch_find_slot(), dfsch_slot_ref(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_slot_ref(obj, dfsch_find_slot(DFSCH_TYPE_OF(obj),
                                             slot),
                        debug);
}
void dfsch_slot_set (dfsch_object_t * obj, dfsch_slot_t * slot, dfsch_object_t * value, int debug)
Definition at line 369 of file dfsch.c.
References dfsch_slot_t::access, dfsch_error(), DFSCH_SLOT_ACCESS_RW, dfsch_slot_t::offset, dfsch_slot_type_t::set, and dfsch_slot_t::type.
Referenced by dfsch_slot_set_by_name().
{
  if (!debug && slot->access != DFSCH_SLOT_ACCESS_RW) {
    dfsch_error("Slot not accesible", (dfsch_object_t*)slot);
  }
  slot->type->set(((char*) obj)+slot->offset, value);
}
void dfsch_slot_set_by_name (dfsch_object_t * obj, char * slot, dfsch_object_t * value, int debug)
Definition at line 386 of file dfsch.c.
References dfsch_find_slot(), dfsch_slot_set(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_slot_set(obj, dfsch_find_slot(DFSCH_TYPE_OF(obj),
                                      slot),
                 value,
                 debug);
}
dfsch_object_t* dfsch_sort_list (dfsch_object_t * list, dfsch_object_t * comp)
Definition at line 1463 of file dfsch.c.
References dfsch_apply(), dfsch_ensure_mutable_list(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, dfsch_list(), and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  size_t k = 1;
  dfsch_object_t* p = list;
  size_t p_s;
  dfsch_object_t* q;
  size_t q_s;
  dfsch_object_t* l;
  dfsch_object_t* lt;
  int nmerges;
  size_t i;
  dfsch_object_t* e;
  list = dfsch_ensure_mutable_list(list);
  l = list;
  do {
    nmerges = 0;
    p = l;
    l = NULL;
    lt = NULL;
    while (DFSCH_PAIR_P(p)){
      nmerges++;
      q = p;
      p_s = 0;
      for (i = 0; DFSCH_PAIR_P(q) && i < k; i++){
        q = DFSCH_FAST_CDR(q);
        p_s++;
      }
      q_s = k;
      while (p_s > 0 || (q_s >0 && DFSCH_PAIR_P(q))){
        if (p_s == 0){
          q_s--;
          e = q;
          q = DFSCH_FAST_CDR(q);
        } else if (q_s == 0 || !DFSCH_PAIR_P(q)){
          p_s--;
          e = p;
          p = DFSCH_FAST_CDR(p);
        } else if (dfsch_apply(comp, dfsch_list(2, DFSCH_FAST_CAR(q),
                                                DFSCH_FAST_CAR(p))) != NULL){
          q_s--;
          e = q;
          q = DFSCH_FAST_CDR(q);
        } else {
          p_s--;
          e = p;
          p = DFSCH_FAST_CDR(p);
        }
        DFSCH_FAST_CDR_MUT(e) = NULL;
        if (l) {
          DFSCH_FAST_CDR_MUT(lt) = e;
          lt = e;
        } else {
          l = lt = e;
        }
      }
      p = q;
    }
    k *= 2;
  } while(nmerges > 1);
  return l;
}
dfsch_object_t* dfsch_string_2_object (char * str)
Parse string into object.
Definition at line 2182 of file dfsch.c.
References dfsch_car(), dfsch_error(), and dfsch_string_2_object_list().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  object_t* list = dfsch_string_2_object_list(str);
  if (!list) {
    dfsch_error("Input empty", NULL);
  }
  return dfsch_car(list);
}
dfsch_object_t* dfsch_string_2_object_list (char * str)
Parse string into list of objects
Definition at line 2163 of file dfsch.c.
References dfsch_error(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_feed(), dfsch_parser_get_level(), DFSCH_PARSER_STOPPED, read_ctx_t::head, parser, read_callback(), and read_ctx_t::tail.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_string_2_object(), and main().
{
  dfsch_parser_ctx_t *parser = dfsch_parser_create();
  read_ctx_t ctx;
  int err;
  dfsch_parser_callback(parser, read_callback, &ctx);
  ctx.head = ctx.tail = NULL;
  err = dfsch_parser_feed(parser, str);
  if (!err)
    dfsch_parser_feed(parser, " ");
  if ((err && err != DFSCH_PARSER_STOPPED)
      || dfsch_parser_get_level(parser)!=0){
    dfsch_error("Syntax error",NULL);
  }
  return ctx.head;
}
dfsch_object_t* dfsch_superclass (dfsch_object_t * obj)
Get superclass of given type
Definition at line 166 of file dfsch.c.
References dfsch_object_as_type(), and dfsch_type_t::superclass.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return (dfsch_object_t*)dfsch_object_as_type(obj)->superclass;
}
int dfsch_superclass_p (dfsch_type_t * sub, dfsch_type_t * super)
Definition at line 170 of file dfsch.c.
References dfsch_type_t::superclass.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_instance_p(), and dfsch_make_condition().
{
  if (sub == super)
    return 1;
  while (sub){
    sub = sub->superclass;
    if (sub==super){
      return 1;
    }
  }
  return 0;
}
char* dfsch_symbol (dfsch_object_t * symbol)
Returns string representation of given symbol.
Definition at line 1795 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_TAG_REF, and SYMBOL.
Referenced by dfsch_compare_symbol(), DFSCH_DEFINE_PRIMITIVE(), dfsch_parser_import_symbol(), dfsch_string_or_symbol_to_cstr(), dfsch_symbol_2_typename(), emit_attrs(), emit_object(), and make_slots().
{
  return ((symbol_t*)DFSCH_TAG_REF(DFSCH_ASSERT_TYPE(symbol, SYMBOL)))->data;
}
char* dfsch_symbol_2_typename (dfsch_object_t * symbol)
Definition at line 1799 of file dfsch.c.
References dfsch_symbol(), strancat, and strancpy.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  char *name;
  char *flt;
  name = dfsch_symbol(symbol);
  if (name[strlen(name)-1] == '>'){
    flt = strchr(name, '<');
    if (flt){
      if (flt == name){
        return strancpy(name+1, strlen(name) - 2);
      } else {
        return strancat(name, flt - name, flt+1, strlen(flt+1)-1);
      }
    }
  }
  return name;
}
int dfsch_symbol_p (dfsch_object_t * obj)
Is OBJ a symbol?
Definition at line 846 of file dfsch.c.
References DFSCH_TYPE_OF, and SYMBOL.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_string_or_symbol_to_cstr().
{
  return DFSCH_TYPE_OF(obj) == SYMBOL;
}
void dfsch_throw (dfsch_object_t * tag, dfsch_object_t * value)
Definition at line 1993 of file dfsch.c.
References dfsch__thread_info_t::catch_list, dfsch__continue_unwind(), dfsch__get_thread_info(), dfsch_error(), dfsch__catch_list_t::next, dfsch__catch_list_t::tag, dfsch__thread_info_t::throw_tag, and dfsch__thread_info_t::throw_value.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_xml_parse_buf(), dfsch_xml_parse_file(), dfsch_xml_parse_port(), throw_proc(), and throw_proc_arg().
{
  dfsch__thread_info_t *ti = dfsch__get_thread_info();
  dfsch__catch_list_t* i = ti->catch_list;
  while (i){
    if (i->tag == tag){
      ti->throw_tag = tag;
      ti->throw_value = value;
      dfsch__continue_unwind(ti);
    }
    i = i->next;
  }
  dfsch_error("Invalid catch tag", tag);
}
dfsch_type_t* dfsch_type_of (dfsch_object_t * obj)
Get object type
Definition at line 158 of file dfsch.c.
References DFSCH_TYPE_OF.
{
  return DFSCH_TYPE_OF(obj);
}
void dfsch_unset (dfsch_object_t * name, dfsch_object_t * env)
Unset variable name in environment env
Definition at line 2324 of file dfsch.c.
References environment_t::decls, DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_unset(), dfsch_error(), dfsch_hash_unset(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, environment_t::parent, and environment_t::values.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  environment_t *i;
  i = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  DFSCH_RWLOCK_WRLOCK(&environment_rwlock);
  while (i){
    if (i->decls){
      dfsch_hash_unset(i->decls, name);
    }
    if(dfsch_eqhash_unset(&i->values, name)){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return;
    }
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  dfsch_error("Unbound variable",name);
}
dfsch_object_t* dfsch_vector (size_t count, ...)
Construct vector from arguments.
Definition at line 2046 of file dfsch.c.
References vector_t::data, dfsch_make_object_var(), vector_t::length, and VECTOR.
Referenced by dfsch_get_trace(), native_gettimeofday(), and regex_substrings().
{
  size_t i;
  vector_t* v =
    (vector_t*)dfsch_make_object_var(VECTOR, count * sizeof(dfsch_object_t*));
  va_list al;
  va_start(al,count);
  v->length = count;
  for(i = 0; i < count; ++i){
    v->data[i] = va_arg(al, dfsch_object_t*);
  }
  va_end(al);
  return (object_t*)v;
}
dfsch_object_t* dfsch_vector_2_list (dfsch_object_t * vector)
Converts vector to list.
Definition at line 2112 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, dfsch_list_from_array(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  return dfsch_list_from_array(v->data, v->length);
}
dfsch_object_t** dfsch_vector_as_array (dfsch_object_t * vector, size_t * length)
Returns pointer to internal object array of vector
Definition at line 2069 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, vector_t::length, and VECTOR.
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  if (length){
    *length = v->length;
  }
  return v->data;
}
dfsch_object_t* dfsch_vector_from_array (dfsch_object_t ** array, size_t length)
Creates vector from C array
Definition at line 2079 of file dfsch.c.
References vector_t::data, dfsch_make_object_var(), vector_t::length, and VECTOR.
{
  vector_t* v =
    (vector_t*)dfsch_make_object_var(VECTOR,
                                     sizeof(dfsch_object_t*) * length);
  v->length = length;
  memcpy(v->data, array, sizeof(object_t*) * length);
  return (object_t*)v;
}
size_t dfsch_vector_length (dfsch_object_t * vector)
Returns length of given vector.
Definition at line 2065 of file dfsch.c.
References DFSCH_ASSERT_TYPE, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return ((vector_t*)DFSCH_ASSERT_TYPE(vector, VECTOR))->length;
}
int dfsch_vector_p (dfsch_object_t * obj)
Is OBJ a vector?
Definition at line 867 of file dfsch.c.
References DFSCH_TYPE_OF, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_format_trace().
{
  return DFSCH_TYPE_OF(obj) == VECTOR;
}
dfsch_object_t* dfsch_vector_ref (dfsch_object_t * vector, size_t k)
Returns contents of k-th slot of vector.
Definition at line 2091 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, dfsch_error(), dfsch_make_number_from_long(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_format_trace().
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  if (v->length <= k)
    dfsch_error("Invalid index",dfsch_make_number_from_long(k));
  return v->data[k];
}
dfsch_object_t* dfsch_vector_set (dfsch_object_t * vector, size_t k, dfsch_object_t * obj)
Sets value of k-th slot of vector to obj.
Definition at line 2100 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, dfsch_error(), dfsch_make_number_from_long(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and regex_substrings().
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  if (v->length <= k)
    dfsch_error("Invalid index",dfsch_make_number_from_long(k));
  v->data[k] = obj;
  return vector;
}
dfsch_object_t* dfsch_zip (dfsch_object_t * llist)
Definition at line 1226 of file dfsch.c.
References dfsch_cons(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, dfsch_list_as_array(), DFSCH_PAIR_P, DFSCH_PAIR_TYPE, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  size_t len;
  object_t** args = dfsch_list_as_array(llist, &len);
  dfsch_object_t* shead;
  dfsch_object_t* stail;
  dfsch_object_t *head = NULL;
  dfsch_object_t *tail;
  dfsch_object_t* tmp;
  size_t i;
  if (len == 0){
    return NULL;
  }
  while(1){
    shead = NULL;
    for (i = 0; i<len; i++){
      if (!args[i]){
        if (i != 0){
          dfsch_error("Not a list of same length lists", llist);
        }
        goto out;
      }
      if (!DFSCH_PAIR_P(args[i])){
        dfsch_type_error(args[i], DFSCH_PAIR_TYPE, 0);
      }
      tmp = dfsch_cons(DFSCH_FAST_CAR(args[i]), NULL);
      if (shead){
        DFSCH_FAST_CDR_MUT(stail) = tmp;
      } else {
        shead = tmp;
      }
      stail = tmp;
      args[i] = DFSCH_FAST_CDR(args[i]);
    }
    tmp = dfsch_cons(shead, NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
    } else {
      head = tmp;
    }
    tail = tmp;
  }
 out:
  for (i = 0; i<len; i++){
    if (args[i]){
      dfsch_error("Not a list of same length lists", llist);
    }
  }
  return head;
}
static object_t* eval_list (object_t * list, environment_t * env, dfsch__thread_info_t * ti) [static]
Definition at line 2447 of file dfsch.c.
References dfsch_error(), dfsch_eval_impl(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, DFSCH_PAIR_P, DFSCH_SYMBOL_P, lookup_impl(), and tl_cons().
Referenced by destructuring_eval(), dfsch_apply_impl(), and dfsch_eval_list().
{
  dfsch_object_t *i;
  object_t *f=NULL;
  dfsch_object_t *t, *p;
  object_t *r;
  if (!list)
    return NULL;
  if (!DFSCH_PAIR_P(list)){
    dfsch_error("Not a proper list", list);
  }
  r = dfsch_eval_impl(DFSCH_FAST_CAR(list), env, NULL, ti);
  t = tl_cons(ti, r, NULL);
  f = p = t;
  i = DFSCH_FAST_CDR(list);
  while (DFSCH_PAIR_P(i)){
    r = DFSCH_FAST_CAR(i);
    if (DFSCH_SYMBOL_P(r)){
      r = lookup_impl(r, env, ti);
    } else {
      r = dfsch_eval_impl(r, env, NULL, ti);
    }
    t = tl_cons(ti, r, NULL);
    DFSCH_FAST_CDR_MUT(p) = (object_t*)t;
    p = t;
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a proper list", list);
  }
  return f;
}
static void free_symbol (symbol_t * s) [static]
Definition at line 1697 of file dfsch.c.
References dfsch__symbol_t::data, hash_entry_t::entry, hash_entry_t::next, and string_hash().
Referenced by symbol_finalizer().
{
  hash_entry_t *i;
  hash_entry_t *j;
  pthread_mutex_lock(&symbol_lock);
  i = global_symbol_hash[string_hash(s->data)];
  j = NULL;
  while (i){
    if (i->entry == s){
      if (j){
        j->next = i->next;
      } else {
        global_symbol_hash[string_hash(s->data)] = i->next;
      }
      free(i);
      break;
    }
    j = i;
    i = i->next;
  }
  pthread_mutex_unlock(&symbol_lock);
  s->data = NULL;
}
static void function_write (closure_t * c, dfsch_writer_state_t * state) [static]
Definition at line 657 of file dfsch.c.
References dfsch_write_object(), dfsch_write_string(), dfsch_write_unreadable_end(), dfsch_write_unreadable_start(), and print_lambda_list().
{
  dfsch_write_unreadable_start(state, (dfsch_object_t*)c);
  if (c->name){
    dfsch_write_object(state, c->name);
  }
  dfsch_write_string(state, " (");
  print_lambda_list(c->args, state);
  dfsch_write_string(state, ")");
  dfsch_write_unreadable_end(state);
}
static void gsh_check_init () [static]
Definition at line 1669 of file dfsch.c.
References HASH_SIZE, and register_static_symbol().
Referenced by dfsch_make_symbol().
{
  int i;
  if (gsh_init){
    return;
  }
  memset(global_symbol_hash, 0, sizeof(hash_entry_t*)*HASH_SIZE);
  for (i = 0; i < sizeof(dfsch__static_symbols)/sizeof(symbol_t); i++){
    register_static_symbol(dfsch__static_symbols + i);
  }
  gsh_init = 1;
}
static size_t hash_combine (size_t a, size_t b) [static]
Definition at line 133 of file dfsch.c.
Referenced by pair_hash(), and vector_hash().
{
  a ^= b >> 2;
  b ^= a >> 3;
  a ^= b << 5;
  b ^= a << 7;
  a ^= b >> 11;
  b ^= a >> 13;
  a ^= b << 17;
  b ^= a << 23;
  return b ^ a;
}
static void lambda_list_write (lambda_list_t * ll, dfsch_writer_state_t * ws) [static]
Definition at line 814 of file dfsch.c.
References dfsch_write_unreadable_end(), dfsch_write_unreadable_start(), and print_lambda_list().
{
  dfsch_write_unreadable_start(ws, (dfsch_object_t*)ll);
  print_lambda_list(ll, ws);
  dfsch_write_unreadable_end(ws);
}
static object_t* lookup_impl (object_t * name, environment_t * env, dfsch__thread_info_t * ti) [static]
Definition at line 2229 of file dfsch.c.
References dfsch_cons(), dfsch_eqhash_ref(), dfsch_error(), DFSCH_INVALID_OBJECT, DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, DFSCH_UNLIKELY, environment_t::owner, environment_t::parent, and environment_t::values.
Referenced by dfsch_eval_impl(), dfsch_lookup(), and eval_list().
{
  environment_t *i;
  object_t* ret;
  i = env;
  while (i){
    if (DFSCH_UNLIKELY(i->owner != ti)){
      i->owner = NULL;
      goto lock;
    }
    ret = dfsch_eqhash_ref(&i->values, name);
    if (ret != DFSCH_INVALID_OBJECT){
      return ret;
    }
    i = i->parent;
  }
  dfsch_error("Unbound variable", dfsch_cons(name, (dfsch_object_t*)env));
 lock:
   DFSCH_RWLOCK_RDLOCK(&environment_rwlock);
  while (i){
    ret = dfsch_eqhash_ref(&i->values, name);
    if (ret != DFSCH_INVALID_OBJECT){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return ret;
    }
    i->owner = NULL;
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  dfsch_error("Unbound variable", dfsch_cons(name, (dfsch_object_t*)env));
}
static symbol_t* lookup_symbol (char * symbol) [static]
Definition at line 1682 of file dfsch.c.
References dfsch__symbol_t::data, hash_entry_t::entry, hash_entry_t::hash, hash_entry_t::next, and string_hash().
Referenced by dfsch_make_symbol(), and make_symbol().
{
  size_t hash = string_hash(symbol);
  hash_entry_t *i = global_symbol_hash[hash];
  while (i){
    if (i->hash == hash && strcmp(i->entry->data, symbol)==0){
      return i->entry;
    }
    i = i->next;
  }
  return NULL;
}
static symbol_t* make_symbol (char * symbol) [static]
Definition at line 1729 of file dfsch.c.
References dfsch__symbol_t::data, hash_entry_t::entry, hash_entry_t::hash, lookup_symbol(), hash_entry_t::next, stracpy, string_hash(), and symbol_finalizer().
Referenced by dfsch_make_symbol().
{
  symbol_t *s;
  symbol_t *f;
  s = GC_NEW(symbol_t); /* !!! free_symbol could be called by this */
  s->data = stracpy(symbol);
  pthread_mutex_lock(&symbol_lock);
  f = lookup_symbol(symbol);
  if (f){
    GC_FREE(s->data);
    GC_FREE(s);
    pthread_mutex_unlock(&symbol_lock);
    return f;
  }
  GC_REGISTER_FINALIZER(s,
                        (GC_finalization_proc)symbol_finalizer, NULL,
                        NULL, NULL);
  hash_entry_t *e = malloc(sizeof(hash_entry_t));
  e->entry = s;
  e->hash = string_hash(symbol);
  e->next = global_symbol_hash[e->hash];
  global_symbol_hash[e->hash] = e;
  pthread_mutex_unlock(&symbol_lock);
  return s;
}
static object_t* native_top_level_environment (void * baton, object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 2791 of file dfsch.c.
Referenced by dfsch_make_context().
{
  return baton;
}
static environment_t* new_frame_impl (environment_t * parent, dfsch__thread_info_t * ti) [static]
Definition at line 2209 of file dfsch.c.
References alloc_environment(), environment_t::decls, dfsch_eqhash_init(), environment_t::owner, environment_t::parent, and environment_t::values.
Referenced by dfsch_apply_impl(), and dfsch_new_frame().
{
  environment_t* e = alloc_environment(ti);
  dfsch_eqhash_init(&e->values, 0);
  e->decls = NULL;
  e->owner = ti;
  e->parent = (environment_t*)parent;
  return e;
}
static dfsch_object_t* object_accessor_ref (void * ptr) [static]
Definition at line 260 of file dfsch.c.
{
  return *((dfsch_object_t**)ptr);
}
static void object_accessor_set (void * ptr, dfsch_object_t * obj) [static]
Definition at line 263 of file dfsch.c.
{
  *((dfsch_object_t**)ptr) = obj;
}
static int pair_equal_p (dfsch_object_t * a, dfsch_object_t * b) [static]
Definition at line 498 of file dfsch.c.
References dfsch_equal_p(), DFSCH_FAST_CAR, and DFSCH_FAST_CDR.
{
  return dfsch_equal_p(DFSCH_FAST_CAR(a), DFSCH_FAST_CAR(b))
    && dfsch_equal_p(DFSCH_FAST_CDR(a), DFSCH_FAST_CDR(b));
}
static size_t pair_hash (dfsch_object_t * p) [static]
Definition at line 502 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_hash(), and hash_combine().
{
  return hash_combine(dfsch_hash(DFSCH_FAST_CAR(p)),
                      dfsch_hash(DFSCH_FAST_CDR(p)));
}
static void pair_write (dfsch_object_t * p, dfsch_writer_state_t * state) [static]
Definition at line 506 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_PAIR_P, dfsch_write_object(), and dfsch_write_string().
{
  object_t* i=p;
  object_t* j=p;
  int c = 0;
  dfsch_write_string(state, "(");
  while (DFSCH_PAIR_P(i)){
    dfsch_write_object(state, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
    if (i == j){
      dfsch_write_string(state, "... #<infinite-list>)");
      return;
    }
    c++;
    if (c == 2){
      c = 0;
      j = DFSCH_FAST_CDR(j);
    }
    if (i) {
      dfsch_write_string(state, " ");
    }
  }
  if (i){
    dfsch_write_string(state, ". ");
    dfsch_write_object(state, i);
  }
  dfsch_write_string(state, ")");
}
static void primitive_write (dfsch_primitive_t * p, dfsch_writer_state_t * state) [static]
Definition at line 617 of file dfsch.c.
References dfsch_write_unreadable(), and dfsch_primitive_t::name.
{
  char* name = p->name ? p->name : "()";
  dfsch_write_unreadable(state, (dfsch_object_t*)p, "%s", name);
}
static void print_lambda_list (lambda_list_t * ll, dfsch_writer_state_t * ws) [static]
Definition at line 645 of file dfsch.c.
References dfsch_write_object(), dfsch_write_string(), lambda_list_t::positional, lambda_list_t::positional_count, and lambda_list_t::rest.
Referenced by function_write(), and lambda_list_write().
{
  int i;
  for (i = 0; i < ll->positional_count; i++){
    dfsch_write_object(ws, ll->positional[i]);
    dfsch_write_string(ws, " ");
  }
  if (ll->rest){
    dfsch_write_string(ws, "&rest ");
    dfsch_write_object(ws, ll->rest);
  }
}
static size_t ptr_hash (dfsch_object_t * ptr) [static]
Definition at line 117 of file dfsch.c.
Referenced by dfsch_hash().
{
  size_t a = (size_t)ptr;
  size_t b = (size_t)ptr >> 16 | (size_t)ptr << 16;
  a ^= b >> 2;
  b ^= a >> 3;
  a ^= b << 5;
  b ^= a << 7;
  a ^= b >> 11;
  b ^= a >> 13;
  a ^= b << 17;
  b ^= a << 23;
  return b ^ a;
}
static read_callback (dfsch_object_t * obj, void * ctx) [static]
Definition at line 2149 of file dfsch.c.
References dfsch_cons(), and dfsch_set_cdr().
Referenced by dfsch_string_2_object_list().
{
  dfsch_object_t* new_tail = dfsch_cons(obj, NULL);
  if (!((read_ctx_t*)ctx)->head){
    ((read_ctx_t*)ctx)->head = new_tail;
  }else{
    dfsch_set_cdr(((read_ctx_t*)ctx)->tail, new_tail);
  }
  ((read_ctx_t*)ctx)->tail = new_tail;
  return 1;
}
static void register_static_symbol (symbol_t * s) [static]
Definition at line 1659 of file dfsch.c.
References dfsch__symbol_t::data, hash_entry_t::entry, hash_entry_t::hash, hash_entry_t::next, and string_hash().
Referenced by gsh_check_init().
{
  hash_entry_t *e = malloc(sizeof(hash_entry_t));
  e->entry = s;
  e->hash = string_hash(s->data);
  e->next = global_symbol_hash[e->hash];
  global_symbol_hash[e->hash] = e;
}
static void slot_write (dfsch_slot_t * slot, dfsch_writer_state_t * state) [static]
Definition at line 222 of file dfsch.c.
References dfsch_write_unreadable().
{
  dfsch_write_unreadable(state, (dfsch_object_t*)slot, "%s", slot->name);
}
static dfsch_object_t* string_accessor_ref (void * ptr) [static]
Definition at line 286 of file dfsch.c.
References dfsch_make_string_cstr().
{
  return dfsch_make_string_cstr(*((char**)ptr));
}
static void string_accessor_set (void * ptr, dfsch_object_t * obj) [static]
Definition at line 289 of file dfsch.c.
References dfsch_string_to_cstr().
{
  *((char**)ptr) = dfsch_string_to_cstr(obj);
}
static size_t string_hash (char * string) [static]
Definition at line 1626 of file dfsch.c.
References HASH_SIZE.
Referenced by free_symbol(), lookup_symbol(), make_symbol(), and register_static_symbol().
{
  size_t tmp=0;
  while (*string){
    char c = *string;
    tmp ^= c ^ (tmp << 7);
    tmp ^= ((size_t)c << 17) ^ (tmp >> 11);
    ++string;
  }
  return tmp & (HASH_SIZE - 1);
}
static void symbol_finalizer (symbol_t * symbol, void * cd) [static]
Definition at line 1725 of file dfsch.c.
References free_symbol().
Referenced by make_symbol().
{
  free_symbol(symbol);
}
static void symbol_write (object_t * o, dfsch_writer_state_t * state) [static]
Definition at line 551 of file dfsch.c.
References dfsch__symbol_t::data, DFSCH_TAG_REF, dfsch_write_string(), and dfsch_write_unreadable().
{
  symbol_t* s;
  s = DFSCH_TAG_REF(o);
  if (s->data){
    dfsch_write_string(state, s->data);
  } else {
    dfsch_write_unreadable(state, o, "");
  }
}
static void thread_info_destroy (void * ptr) [static]
Definition at line 1934 of file dfsch.c.
Referenced by thread_key_alloc().
{
  if (ptr)
    GC_FREE(ptr);
}
static void thread_key_alloc () [static]
Definition at line 1938 of file dfsch.c.
References thread_info_destroy().
Referenced by dfsch__get_thread_info().
{
  pthread_key_create(&thread_key, thread_info_destroy);
}
static dfsch_object_t* tl_cons (dfsch__thread_info_t * ti, dfsch_object_t * car, dfsch_object_t * cdr) [static]
Definition at line 896 of file dfsch.c.
References dfsch_pair_t::car, dfsch_pair_t::cdr, DFSCH_TAG_ENCODE, and dfsch__thread_info_t::pair_freelist.
Referenced by eval_list().
{
  dfsch_pair_t* p;
#ifdef GC_NEXT
  if (!ti->pair_freelist){
    ti->pair_freelist = GC_malloc_many(sizeof(dfsch_pair_t));
  }
  p = ti->pair_freelist;
  ti->pair_freelist = GC_NEXT(ti->pair_freelist);
#else
  p = GC_NEW(dfsch_pair_t);
#endif
  p->car = car;
  p->cdr = cdr;
  return DFSCH_TAG_ENCODE(p, 1);
}
static void type_write (dfsch_type_t * t, dfsch_writer_state_t * state) [static]
Definition at line 417 of file dfsch.c.
References dfsch_write_unreadable().
{
  dfsch_write_unreadable(state, (dfsch_object_t*)t,
                         "%s instance-size: %d", t->name, t->size);
}
static int vector_equal_p (vector_t * a, vector_t * b) [static]
Definition at line 741 of file dfsch.c.
References vector_t::data, dfsch_equal_p(), and vector_t::length.
{
  size_t i;
  if (a->length != b->length)
    return 0;
  for (i=0; i<a->length; i++){
    if (!dfsch_equal_p(a->data[i], b->data[i]))
      return 0;
  }
  return 1;
}
static size_t vector_hash (vector_t * v) [static]
Definition at line 754 of file dfsch.c.
References vector_t::data, dfsch_hash(), hash_combine(), and vector_t::length.
{
  size_t i;
  size_t ret = 0;
  for (i=0; i<v->length; i++){
    ret = hash_combine(ret, dfsch_hash(v->data[i]));
  }
  return ret;
}
static void vector_write (vector_t * v, dfsch_writer_state_t * state) [static]
Definition at line 766 of file dfsch.c.
References vector_t::data, dfsch_write_object(), dfsch_write_string(), and vector_t::length.
{
  size_t i;
  dfsch_write_string(state, "#(");
  if (v->length > 0){
    for(i = 0; i < v->length-1; ++i){
      dfsch_write_object(state, v->data[i]);
      dfsch_write_string(state, " ");
    }
    dfsch_write_object(state, v->data[v->length - 1]);
  }
  dfsch_write_string(state, ")");
}
Variable Documentation
dfsch_slot_t closure_slots[] [static]
Initial value:
 {
  DFSCH_OBJECT_SLOT(closure_t, args, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Arguments of function (compiled lambda-list)"),
  DFSCH_OBJECT_SLOT(closure_t, code, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Actual implementation code"),
  DFSCH_OBJECT_SLOT(closure_t, env, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Lexically enclosing environment"),
  DFSCH_OBJECT_SLOT(closure_t, name, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Primitive name"),
  DFSCH_OBJECT_SLOT(closure_t, orig_code, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Original expression of closure"),
  DFSCH_OBJECT_SLOT(closure_t, documentation, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Documentation string"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 670 of file dfsch.c.
dfsch__symbol_t dfsch__static_symbols[]
Initial value:
 {
  {"true"},
  {"quote"},
  {"quasiquote"},
  {"unquote"},
  {"unquote-splicing"},
  {"else"},
  {"=>"},
}
Definition at line 1642 of file dfsch.c.
dfsch_type_t dfsch_abstract_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_type_t),
  "abstract-type",
  NULL,
  NULL,
  NULL
}
Definition at line 396 of file dfsch.c.
dfsch_slot_type_t dfsch_boolean_slot_type
Initial value:
 {
  DFSCH_SLOT_TYPE_HEAD("boolean-slot", "Slot holding boolean value as C int"),
  boolean_accessor_ref,
  boolean_accessor_set,
  sizeof(int)
}
Definition at line 279 of file dfsch.c.
int dfsch_default_trace_depth = 3
Definition at line 1942 of file dfsch.c.
dfsch_type_t dfsch_empty_list_type
Initial value:
 {
  DFSCH_SPECIAL_TYPE,
  DFSCH_LIST_TYPE,
  0,
  "empty-list",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  "Class with only one instance - ()"
}
Definition at line 485 of file dfsch.c.
dfsch_type_t dfsch_environment_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(environment_t),
  "environment",
  NULL,
  NULL,
  NULL,
  NULL,
  &environment_slots,
  "Lexical environment frame"
}
Definition at line 798 of file dfsch.c.
dfsch_type_t dfsch_form_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(dfsch_form_t),
  "form",
  NULL,
  NULL,
  NULL,
  NULL,
  &form_slots,
  "C-implemented special form"
}
Definition at line 727 of file dfsch.c.
dfsch_type_t dfsch_function_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "function",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  "Abstract superclass for functions"
}
Definition at line 469 of file dfsch.c.
dfsch_type_t dfsch_lambda_list_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(lambda_list_t),
  "lambda-list",
  NULL,
  (dfsch_type_write_t)lambda_list_write,
  NULL,
  NULL,
  NULL,
  "Compiled lambda-list for effective destructuring"
}
Definition at line 819 of file dfsch.c.
dfsch_type_t dfsch_list_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "list",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  "Abstract superclass of list-like objects"
}
Definition at line 456 of file dfsch.c.
dfsch_type_t dfsch_macro_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(macro_t),
  "macro",
  NULL,
  NULL,
  NULL,
  NULL,
  &macro_slots,
  "Macro implemented by arbitrary function"
}
Definition at line 705 of file dfsch.c.
dfsch_type_t dfsch_meta_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_type_t),
  "meta-type",
  NULL,
  NULL,
  NULL
}
Definition at line 406 of file dfsch.c.
dfsch_slot_type_t dfsch_object_slot_type
Initial value:
 {
  DFSCH_SLOT_TYPE_HEAD("object-slot", "Generic object-pointer slot"),
  object_accessor_ref,
  object_accessor_set,
  sizeof(dfsch_object_t*)
}
Definition at line 266 of file dfsch.c.
dfsch_type_t dfsch_pair_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  DFSCH_LIST_TYPE,
  sizeof(dfsch_pair_t),
  "pair",
  (dfsch_type_equal_p_t)pair_equal_p,
  (dfsch_type_write_t)pair_write,
  NULL,
  (dfsch_type_hash_t)pair_hash,
  NULL,
  "Abstract superclass for all pair representations"
}
Definition at line 537 of file dfsch.c.
dfsch_type_t dfsch_primitive_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  DFSCH_STANDARD_FUNCTION_TYPE,
  sizeof(primitive_t),
  "primitive",
  NULL,
  (dfsch_type_write_t)primitive_write,
  NULL,
  NULL,
  &primitive_slots,
  "Function implemented in C code"
}
Definition at line 631 of file dfsch.c.
dfsch_type_t dfsch_slot_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  sizeof(dfsch_slot_t),
  "slot",
  NULL,
  (dfsch_type_write_t)slot_write,
  NULL,
  NULL,
  &slot_slots,
  "Common superclass of all slot types"
}
Definition at line 226 of file dfsch.c.
dfsch_type_t dfsch_slot_type_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_slot_type_t),
  "slot-type",
  NULL,
  NULL,
  NULL,
  NULL,
  &slot_type_slots,
  "Slot metaclass - describes methods for reading and writing"
}
Definition at line 247 of file dfsch.c.
dfsch_type_t dfsch_special_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_type_t),
  "special-type",
  NULL,
  NULL,
  NULL,
  NULL,
  &type_slots,
  "Metaclass of types with special in-memory representation"
}
Definition at line 443 of file dfsch.c.
dfsch_type_t dfsch_standard_function_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  DFSCH_FUNCTION_TYPE,
  sizeof(closure_t),
  "function",
  NULL,
  (dfsch_type_write_t)function_write,
  NULL,
  NULL,
  &closure_slots,
  "User defined function"
}
Definition at line 686 of file dfsch.c.
dfsch_type_t dfsch_standard_type
Initial value:
 {
  DFSCH_META_TYPE,
  NULL,
  sizeof(dfsch_type_t),
  "standard-type",
  NULL,
  (dfsch_type_write_t)type_write,
  NULL,
  NULL,
  &type_slots,
  "Base metaclass representing common methods of all objects"
}
Definition at line 430 of file dfsch.c.
dfsch_slot_type_t dfsch_string_slot_type
Initial value:
 {
  DFSCH_SLOT_TYPE_HEAD("string-slot", "Slot holding string as C char*"),
  string_accessor_ref,
  string_accessor_set,
  sizeof(char*)
}
Definition at line 292 of file dfsch.c.
dfsch_type_t dfsch_tagged_types[4]
Definition at line 563 of file dfsch.c.
dfsch_type_t dfsch_vector_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(vector_t),
  "vector",
  (dfsch_type_equal_p_t)vector_equal_p,
  (dfsch_type_write_t)vector_write,
  NULL,
  (dfsch_type_hash_t)vector_hash
}
Definition at line 780 of file dfsch.c.
dfsch_rwlock_t environment_rwlock = DFSCH_RWLOCK_INITIALIZER [static]
Definition at line 2190 of file dfsch.c.
dfsch_slot_t environment_slots[] [static]
Initial value:
 {
  DFSCH_OBJECT_SLOT(environment_t, parent, DFSCH_SLOT_ACCESS_DEBUG_WRITE,
                    "Enclosing environment or NIL for top-level"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 792 of file dfsch.c.
dfsch_slot_t form_slots[] [static]
Initial value:
 {
  DFSCH_STRING_SLOT(dfsch_form_t, name, DFSCH_SLOT_ACCESS_RO,
                    "Internal name of special form"),
  DFSCH_STRING_SLOT(dfsch_form_t, documentation, DFSCH_SLOT_ACCESS_RO,
                    "Documentation string"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 719 of file dfsch.c.
hash_entry_t* global_symbol_hash[HASH_SIZE] [static]
Definition at line 1639 of file dfsch.c.
unsigned int gsh_init = 0 [static]
Definition at line 1640 of file dfsch.c.
dfsch_slot_t macro_slots[] [static]
Initial value:
 {
  DFSCH_STRING_SLOT(macro_t, proc, DFSCH_SLOT_ACCESS_RO,
                    "Procedure implementing macro"),
}
Definition at line 700 of file dfsch.c.
dfsch_slot_t primitive_slots[] [static]
Initial value:
 {
  DFSCH_STRING_SLOT(dfsch_primitive_t, name, DFSCH_SLOT_ACCESS_RO,
                    "Primitive's internal name"),
  DFSCH_STRING_SLOT(dfsch_primitive_t, documentation, DFSCH_SLOT_ACCESS_RO,
                    "Documentation string"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 623 of file dfsch.c.
dfsch_slot_t slot_slots[] [static]
Initial value:
 {
  DFSCH_STRING_SLOT(dfsch_slot_t, name, DFSCH_SLOT_ACCESS_RO,
                    "Slot name"),
  DFSCH_SIZE_T_SLOT(dfsch_slot_t, offset, DFSCH_SLOT_ACCESS_RO,
                    "Offset of data item in object"),
  DFSCH_INT_SLOT(dfsch_slot_t, access, DFSCH_SLOT_ACCESS_RO,
                 "Access mode of slot"),
  DFSCH_STRING_SLOT(dfsch_slot_t, documentation, DFSCH_SLOT_ACCESS_RO,
                    "Slot documentation string"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 210 of file dfsch.c.
dfsch_slot_t slot_type_slots[] [static]
Initial value:
 {
  DFSCH_SIZE_T_SLOT(dfsch_slot_type_t, size, DFSCH_SLOT_ACCESS_RO,
                    "Size of slot"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 241 of file dfsch.c.
pthread_mutex_t symbol_lock = PTHREAD_MUTEX_INITIALIZER [static]
Definition at line 1641 of file dfsch.c.
pthread_key_t thread_key [static]
Definition at line 1931 of file dfsch.c.
pthread_once_t thread_once = PTHREAD_ONCE_INIT [static]
Definition at line 1932 of file dfsch.c.
dfsch_slot_t type_slots[] [static]
Initial value:
 {
  DFSCH_STRING_SLOT(dfsch_type_t, name, DFSCH_SLOT_ACCESS_RO,
                    "Type name"),
  DFSCH_STRING_SLOT(dfsch_type_t, documentation, DFSCH_SLOT_ACCESS_RO,
                    "Documentation string"),
  DFSCH_SLOT_TERMINATOR
}
Definition at line 422 of file dfsch.c.