dfsch: dfsch/dfsch.h File Reference
dfsch/dfsch.h File Reference
#include <stdint.h>
#include <pthread.h>
#include <gc/gc.h>
#include <dfsch/defines.h>
#include <dfsch/number.h>
#include <dfsch/types.h>
#include <dfsch/writer.h>
#include <dfsch/strings.h>
Data Structures
struct dfsch_object_t
Defines
#define DFSCH_ARG_END(al)
#define DFSCH_ARG_REST(al, rest) (rest) = (al)
#define DFSCH_DISCARD_ARG(al, name)
#define DFSCH_FLAG_FUNC(name) if (dfsch_compare_symbol(dfsch___flag ,(name)))
#define DFSCH_FLAG_PARSER_BEGIN(args)
#define DFSCH_FLAG_PARSER_BEGIN_ONE(args, name)
#define DFSCH_FLAG_PARSER_BEGIN_ONE_OPT(args, name)
#define DFSCH_FLAG_PARSER_BEGIN_SYM_ONLY(args)
#define DFSCH_FLAG_PARSER_END(args)
#define DFSCH_FLAG_SET(name, value, variable) if (dfsch_compare_symbol(dfsch___flag, (name))) (variable) |= (value)
#define DFSCH_FLAG_UNSET(name, value, variable) if (dfsch_compare_symbol(dfsch___flag ,(name))) (variable) &= ~(value)
#define DFSCH_FLAG_VALUE(name, value, variable) if (dfsch_compare_symbol(dfsch___flag, (name))) (variable) = (value)
#define DFSCH_GENERIC_ARG(al, name, type, conv)
#define DFSCH_GENERIC_ARG_OPT(al, name, default, type, conv)
#define DFSCH_KEYWORD(name, variable)
#define DFSCH_KEYWORD_GENERIC(name, variable, conv)
#define DFSCH_KEYWORD_PARSER_BEGIN(args)
#define DFSCH_KEYWORD_PARSER_END(args)
#define DFSCH_LOCAL_SYMBOL_CACHE(symbol, name) static DFSCH_SYMBOL_CACHE(symbol, name)
#define DFSCH_OBJECT_ARG(al, name)
#define DFSCH_OBJECT_ARG_OPT(al, name, default)
#define DFSCH_OBJECT_CACHE(constructor, name)
#define DFSCH_SYMBOL_ARG(al, name) DFSCH_GENERIC_ARG(al, name, char*, dfsch_symbol)
#define DFSCH_SYMBOL_ARG_OPT(al, default, name) DFSCH_GENERIC_ARG_OPT(al, name, default, char*, dfsch_symbol)
#define DFSCH_SYMBOL_CACHE(symbol, name) DFSCH_OBJECT_CACHE(dfsch_make_symbol(symbol), name)
#define DFSCH_TRUE_P(o) ((o) != NULL)
#define DFSCH_TYPE_ARG(al, name) DFSCH_GENERIC_ARG(al, name, dfsch_type_t*, dfsch_object_as_type)
#define DFSCH_TYPE_ARG_OPT(al, default, name) DFSCH_GENERIC_ARG_OPT(al, name, default, dfsch_type_t*, dfsch_object_as_type)
Typedefs
typedef struct dfsch_object_t dfsch_object_t
typedef dfsch_object_t *(* dfsch_primitive_impl_t)(void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
typedef struct dfsch_symbol_iter_t dfsch_symbol_iter_t
typedef struct dfsch_tail_escape_t dfsch_tail_escape_t
typedef struct dfsch_type_t dfsch_type_t
Functions
dfsch_object_t * dfsch_append (dfsch_object_t *llist)
dfsch_object_t * dfsch_apply (dfsch_object_t *proc, dfsch_object_t *args)
dfsch_object_t * dfsch_apply_tr (dfsch_object_t *proc, dfsch_object_t *args, dfsch_tail_escape_t *esc)
dfsch_object_t * dfsch_assert_instance (dfsch_object_t *obj, dfsch_type_t *type)
void * dfsch_assert_type (dfsch_object_t *obj, dfsch_type_t *type)
dfsch_object_t * dfsch_assoc (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_assq (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_assv (dfsch_object_t *key, dfsch_object_t *alist)
void dfsch_async_apply_check ()
void dfsch_async_apply_self (dfsch_object_t *proc)
int dfsch_atom_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_bool (int bool)
dfsch_object_t * dfsch_car (dfsch_object_t *pair)
dfsch_object_t * dfsch_cdr (dfsch_object_t *pair)
void dfsch_cerror (char *type, dfsch_object_t *data)
int dfsch_closure_p (dfsch_object_t *obj)
int dfsch_compare_symbol (dfsch_object_t *symbol, char *string)
dfsch_object_t * dfsch_compile_lambda_list (dfsch_object_t *list)
dfsch_object_t * dfsch_cons (dfsch_object_t *car, dfsch_object_t *cdr)
dfsch_object_t * dfsch_cons_immutable (dfsch_object_t *car, dfsch_object_t *cdr)
dfsch_object_t * dfsch_define (dfsch_object_t *name, dfsch_object_t *value, dfsch_object_t *env)
dfsch_object_t * dfsch_define_cstr (dfsch_object_t *ctx, char *name, dfsch_object_t *obj)
dfsch_object_t * dfsch_destructuring_bind (dfsch_object_t *arglist, dfsch_object_t *list, dfsch_object_t *env)
dfsch_object_t * dfsch_ensure_mutable_list (dfsch_object_t *list)
dfsch_object_t * dfsch_env_get (dfsch_object_t *name, dfsch_object_t *env)
dfsch_object_t * dfsch_env_get_cstr (dfsch_object_t *ctx, char *name)
int dfsch_eq_p (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_equal_p (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_eqv_p (dfsch_object_t *a, dfsch_object_t *b)
void dfsch_error (char *type, dfsch_object_t *data)
dfsch_object_t * dfsch_eval (dfsch_object_t *exp, dfsch_object_t *env)
dfsch_object_t * dfsch_eval_list (dfsch_object_t *list, dfsch_object_t *env)
dfsch_object_t * dfsch_eval_proc (dfsch_object_t *exp, dfsch_object_t *env)
dfsch_object_t * dfsch_eval_proc_tr (dfsch_object_t *code, dfsch_object_t *env, dfsch_tail_escape_t *esc)
dfsch_object_t * dfsch_eval_tr (dfsch_object_t *exp, dfsch_object_t *env, dfsch_tail_escape_t *esc)
int dfsch_exception_p (dfsch_object_t *obj)
dfsch_slot_t * dfsch_find_slot (dfsch_type_t *type, char *name)
int dfsch_form_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_gensym ()
dfsch_object_t * dfsch_get_environment_variables (dfsch_object_t *env)
dfsch_object_t * dfsch_get_list_annotation (dfsch_object_t *list)
char * dfsch_get_next_symbol (dfsch_symbol_iter_t **iter)
dfsch_object_t * dfsch_get_slots (dfsch_type_t *type)
dfsch_object_t * dfsch_get_stack_trace ()
uint32_t dfsch_hash (dfsch_object_t *obj)
int dfsch_instance_p (dfsch_object_t *obj, dfsch_type_t *type)
dfsch_object_t * dfsch_lambda (dfsch_object_t *env, dfsch_object_t *args, dfsch_object_t *code)
dfsch_object_t * dfsch_list (size_t count,...)
dfsch_object_t * dfsch_list_2_vector (dfsch_object_t *list)
dfsch_object_t * dfsch_list_annotate (dfsch_object_t *list, dfsch_object_t *source, dfsch_object_t *location)
dfsch_object_t ** dfsch_list_as_array (dfsch_object_t *list, size_t *length)
dfsch_object_t * dfsch_list_copy (dfsch_object_t *list)
dfsch_object_t * dfsch_list_copy_immutable (dfsch_object_t *list)
dfsch_object_t * dfsch_list_from_array (dfsch_object_t **array, size_t length)
dfsch_object_t * dfsch_list_item (dfsch_object_t *list, int index)
long dfsch_list_length (dfsch_object_t *list, int *proper)
long dfsch_list_length_check (dfsch_object_t *list)
long dfsch_list_length_fast (dfsch_object_t *list)
int dfsch_list_mutable_p (dfsch_object_t *list)
int dfsch_list_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_lookup (dfsch_object_t *name, dfsch_object_t *env)
dfsch_object_t * dfsch_lookup_cstr (dfsch_object_t *ctx, char *name)
dfsch_object_t * dfsch_macro_expand (dfsch_object_t *macro, dfsch_object_t *args)
int dfsch_macro_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_make_context ()
dfsch_object_t * dfsch_make_form (dfsch_form_impl_t impl, void *baton, char *name)
dfsch_object_t * dfsch_make_macro (dfsch_object_t *proc)
dfsch_object_t * dfsch_make_object (const dfsch_type_t *type)
dfsch_object_t * dfsch_make_primitive (dfsch_primitive_impl_t prim, void *baton)
dfsch_object_t * dfsch_make_primitive_flags (dfsch_primitive_impl_t prim, void *baton, int flags)
dfsch_object_t * dfsch_make_symbol (char *symbol)
dfsch_object_t * dfsch_make_vector (size_t length, dfsch_object_t *fill)
dfsch_object_t * dfsch_member (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_memq (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_memv (dfsch_object_t *key, dfsch_object_t *alist)
dfsch_object_t * dfsch_named_lambda (dfsch_object_t *env, dfsch_object_t *args, dfsch_object_t *code, dfsch_object_t *name)
dfsch_object_t * dfsch_new_frame (dfsch_object_t *parent)
dfsch_object_t * dfsch_new_frame_from_hash (dfsch_object_t *parent, dfsch_object_t *hash)
dfsch_object_t * dfsch_nil ()
int dfsch_null_p (dfsch_object_t *obj)
int dfsch_number_p (dfsch_object_t *obj)
char * dfsch_object_2_string (dfsch_object_t *obj, int max_depth, int readable)
dfsch_type_t * dfsch_object_as_type (dfsch_object_t *obj)
int dfsch_pair_p (dfsch_object_t *obj)
int dfsch_primitive_p (dfsch_object_t *obj)
int dfsch_procedure_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_quasiquote (dfsch_object_t *env, dfsch_object_t *arg)
dfsch_object_t * dfsch_reverse (dfsch_object_t *list)
dfsch_object_t * dfsch_set (dfsch_object_t *name, dfsch_object_t *value, dfsch_object_t *env)
dfsch_object_t * dfsch_set_car (dfsch_object_t *pair, dfsch_object_t *c)
dfsch_object_t * dfsch_set_cdr (dfsch_object_t *pair, dfsch_object_t *c)
dfsch_object_t * dfsch_set_cstr (dfsch_object_t *env, char *name, dfsch_object_t *obj)
dfsch_object_t * dfsch_slot_ref (dfsch_object_t *obj, dfsch_slot_t *slot, int debug)
dfsch_object_t * dfsch_slot_ref_by_name (dfsch_object_t *obj, char *slot, int debug)
void dfsch_slot_set (dfsch_object_t *obj, dfsch_slot_t *slot, dfsch_object_t *value, int debug)
void dfsch_slot_set_by_name (dfsch_object_t *obj, char *slot, dfsch_object_t *value, int debug)
dfsch_object_t * dfsch_string_2_object (char *str)
dfsch_object_t * dfsch_string_2_object_list (char *str)
dfsch_object_t * dfsch_superclass (dfsch_object_t *obj)
int dfsch_superclass_p (dfsch_type_t *sub, dfsch_type_t *super)
char * dfsch_symbol (dfsch_object_t *symbol)
char * dfsch_symbol_2_typename (dfsch_object_t *symbol)
int dfsch_symbol_p (dfsch_object_t *obj)
void dfsch_throw (dfsch_object_t *tag, dfsch_object_t *value)
dfsch_type_t * dfsch_type_of (dfsch_object_t *obj)
void dfsch_unset (dfsch_object_t *name, dfsch_object_t *env)
dfsch_object_t * dfsch_vector (size_t count,...)
dfsch_object_t * dfsch_vector_2_list (dfsch_object_t *vector)
dfsch_object_t ** dfsch_vector_as_array (dfsch_object_t *vector, size_t *length)
dfsch_object_t * dfsch_vector_from_array (dfsch_object_t **array, size_t length)
size_t dfsch_vector_length (dfsch_object_t *vector)
int dfsch_vector_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_vector_ref (dfsch_object_t *vector, size_t k)
dfsch_object_t * dfsch_vector_set (dfsch_object_t *vector, size_t k, dfsch_object_t *obj)
dfsch_object_t * dfsch_zip (dfsch_object_t *llist)
Detailed Description
dfsch is quick and dirty implementation of someting that resembles scheme. This file contains interface specification.
Definition in file dfsch.h.
Define Documentation
#define DFSCH_ARG_END (al)
Value:
if ((al) != NULL)                                     \
    dfsch_error("exception:too-many-arguments",NULL)
Throws exception if arguments list contain any arguments.
Parameters:
al Argument list
Definition at line 540 of file dfsch.h.
Referenced by command_sleep(), decoded_time_apply(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), DFSCH_PRIMITIVE_HEAD(), http_query_2_alist(), http_query_2_hash(), http_split_path(), http_split_query(), inet_base64_decode(), inet_base64_encode(), inet_uri_base64_decode(), inet_uri_base64_encode(), inet_urldecode(), inet_urlencode(), inet_xml_escape(), native_alist_2_hash(), native_apply(), native_channel_create(), native_channel_read(), native_channel_write(), native_chdir(), native_chmod(), native_chown(), native_clock(), native_close(), native_close_file_port(), native_closedir(), native_condition_broadcast(), native_condition_create(), native_condition_signal(), native_condition_wait(), native_creat(), native_current_error_port(), native_current_input_port(), native_current_output_port(), native_cxr(), native_decode_universal_time(), native_display(), native_dup(), native_dup2(), native_encode_universal_time(), native_eof_object_p(), native_eval(), native_eval_proc(), native_exit(), native_fchdir(), native_fchmod(), native_fchown(), native_force(), native_fork(), native_fstat(), native_get_decoded_time(), native_get_universal_time(), native_getcwd(), native_getegid(), native_getenv(), native_geteuid(), native_getgid(), native_getpgid(), native_getpgrp(), native_getpid(), native_getppid(), native_getsid(), native_gettimeofday(), native_getuid(), native_hash_2_alist(), native_hash_p(), native_hash_ref(), native_hash_set(), native_hash_set_if_exists(), native_hash_unset(), native_isatty(), native_iso_format_time(), native_kill(), native_killpg(), native_link(), native_list_2_weak_vector(), native_lseek(), native_lstat(), native_make_hash(), native_make_weak_reference(), native_make_weak_vector(), native_mkdir(), native_mkfifo(), native_mutex_create(), native_mutex_lock(), native_mutex_trylock(), native_mutex_unlock(), native_newline(), native_nice(), native_null_port(), native_open_file_port(), native_opendir(), native_pipe(), native_port_read_buf(), native_port_read_line(), native_port_tell(), native_port_write_buf(), native_raise(), native_read(), native_readdir(), native_rename(), native_rmdir(), native_set_current_error_port(), native_set_current_input_port(), native_set_current_output_port(), native_setegid(), native_seteuid(), native_setgid(), native_setpgid(), native_setpgrp(), native_setsid(), native_setuid(), native_sig(), native_sleep(), native_stat(), native_stream_car(), native_stream_cdr(), native_string_input_port(), native_string_output_port(), native_string_output_port_value(), native_symlink(), native_sync(), native_thread_create(), native_thread_detach(), native_thread_join(), native_thread_self(), native_unlink(), native_unwrap(), native_wait(), native_weak_reference_dereference(), native_weak_reference_live_p(), native_weak_vector_2_list(), native_weak_vector_length(), native_weak_vector_ref(), native_weak_vector_set(), native_wrap(), native_write(), stat_apply(), throw_proc(), and throw_proc_arg().
#define DFSCH_ARG_REST (al, rest) (rest) = (al)
Store all unprocessed arguments into rest. (Syntactic sugar 2.0 :))
Definition at line 547 of file dfsch.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_DISCARD_ARG (al, name)
Value:
if (DFSCH_UNLIKELY(!DFSCH_PAIR_P((al))))              \
    dfsch_error("exception:required-argument-missing",  \
                dfsch_make_string_cstr(#name));         \
  (al) = DFSCH_FAST_CDR((al))
Parses one argument of no specific type from argument list and discards it
Parameters:
al Argument list
name Argument name (used only in exceptions)
Definition at line 477 of file dfsch.h.
#define DFSCH_FLAG_FUNC (name) if (dfsch_compare_symbol(dfsch___flag ,(name)))
Definition at line 605 of file dfsch.h.
#define DFSCH_FLAG_PARSER_BEGIN (args)
Value:
while (DFSCH_PAIR_P((args))){                                 \
    dfsch_object_t* dfsch___flag = DFSCH_FAST_CAR((args));
Definition at line 567 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), native_access(), native_mode(), native_regex_compile(), native_regex_match_once_p(), native_regex_match_p(), native_regex_substrings(), native_regex_substrings_once(), and native_waitpid().
#define DFSCH_FLAG_PARSER_BEGIN_ONE (args, name)
Value:
if (!DFSCH_PAIR_P((args))){                                           \
    dfsch_error("exception:required-argument-missing", #name);          \
  }                                                                     \
  {                                                                     \
    dfsch_object_t* dfsch___flag;                                       \
    dfsch___flag = DFSCH_FAST_CAR((args));                              \
    if (!dfsch_symbol_p(dfsch___flag)) {                                \
      dfsch_error("exception:not-a-symbol", dfsch___flag);              \
    }
Definition at line 576 of file dfsch.h.
#define DFSCH_FLAG_PARSER_BEGIN_ONE_OPT (args, name)
Value:
if (DFSCH_PAIR_P((args))){                                            \
    dfsch_object_t* dfsch___flag;                                       \
    dfsch___flag = DFSCH_FAST_CAR((args));                              \
    if (!dfsch_symbol_p(dfsch___flag)) {                                \
      dfsch_error("exception:not-a-symbol", dfsch___flag);              \
    }
Definition at line 587 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and native_port_seek().
#define DFSCH_FLAG_PARSER_BEGIN_SYM_ONLY (args)
Value:
while (DFSCH_PAIR_P((args))){                                 \
    dfsch_object_t* dfsch___flag = DFSCH_FAST_CAR((args));      \
    if (!dfsch_symbol_p(dfsch___flag)) break;
Definition at line 571 of file dfsch.h.
Referenced by native_open().
#define DFSCH_FLAG_PARSER_END (args)
Value:
(args) = DFSCH_FAST_CDR((args));  \
}
Definition at line 608 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), native_access(), native_mode(), native_open(), native_port_seek(), native_regex_compile(), native_regex_match_once_p(), native_regex_match_p(), native_regex_substrings(), native_regex_substrings_once(), and native_waitpid().
#define DFSCH_FLAG_SET (name, value, variable) if (dfsch_compare_symbol(dfsch___flag, (name))) (variable) |= (value)
Definition at line 599 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), native_access(), native_mode(), native_open(), native_regex_compile(), native_regex_match_once_p(), native_regex_match_p(), native_regex_substrings(), native_regex_substrings_once(), and native_waitpid().
#define DFSCH_FLAG_UNSET (name, value, variable) if (dfsch_compare_symbol(dfsch___flag ,(name))) (variable) &= ~(value)
Definition at line 602 of file dfsch.h.
Referenced by native_regex_compile(), native_regex_match_once_p(), and native_regex_substrings_once().
#define DFSCH_FLAG_VALUE (name, value, variable) if (dfsch_compare_symbol(dfsch___flag, (name))) (variable) = (value)
Definition at line 596 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and native_port_seek().
#define DFSCH_GENERIC_ARG (al, name, type, conv)
Value:
if (DFSCH_UNLIKELY(!DFSCH_PAIR_P((al))))          \
    dfsch_error("exception:required-argument-missing",  \
                dfsch_make_string_cstr(#name));         \
  { dfsch_object_t* dfsch___tmp = DFSCH_FAST_CAR((al)); \
    (name) = (type)(conv)(dfsch___tmp);                 \
    (al) = DFSCH_FAST_CDR((al));                        \
  }
Parses one argument from arguments list and converts it using given function. Intended for use in other macros, such as DFSCH_STRING_ARG.
Parameters:
al Argument list
name Variable or l-value.
type C type of result
conv Function for conversion from dfsch_object_t* to given type.
Definition at line 507 of file dfsch.h.
#define DFSCH_GENERIC_ARG_OPT (al, name, default, type, conv)
Value:
if (!DFSCH_PAIR_P((al))) \
    {(name)=(default);} else\
  { dfsch_object_t* dfsch___tmp = DFSCH_FAST_CAR((al)); \
    (name) = (type)(conv)(dfsch___tmp); \
    (al) = DFSCH_FAST_CDR((al));\
  }
Parses one argument from arguments list and converts it using given function. Intended for use in other macros, such as DFSCH_STRING_ARG. Uses default value instead of throwing exception when no arguments are left.
Parameters:
al Argument list
name Variable or l-value.
default Default value
type C type of result
conv Function for conversion from dfsch_object_t* to given type.
Definition at line 527 of file dfsch.h.
#define DFSCH_KEYWORD (name, variable)
Value:
if (dfsch_compare_symbol(dfsch___keyword, (name))){ \
    (variable) = (dfsch___value);                     \
    continue;                                         \
  }
Definition at line 624 of file dfsch.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_make_wrapper_type().
#define DFSCH_KEYWORD_GENERIC (name, variable, conv)
Value:
if (dfsch_compare_symbol(dfsch___keyword, (name))){ \
    (variable) = conv(dfsch___value);                     \
    continue;                                         \
  }
Definition at line 629 of file dfsch.h.
Referenced by dfsch_sxml_emitter_params(), and dfsch_sxml_parser_params().
#define DFSCH_KEYWORD_PARSER_BEGIN (args)
Value:
while (DFSCH_PAIR_P((args))){                                         \
    dfsch_object_t* dfsch___keyword;                                    \
    dfsch_object_t* dfsch___value;                                      \
    dfsch___keyword = DFSCH_FAST_CAR((args));                           \
    (args) = DFSCH_FAST_CDR((args));                                    \
    if (!DFSCH_PAIR_P((args))){                                         \
      dfsch_error("exception:keyword-without-arguemnt", dfsch___keyword); \
    }                                                                   \
    dfsch___value = DFSCH_FAST_CAR((args));                             \
    (args) = DFSCH_FAST_CDR((args));
Definition at line 612 of file dfsch.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_sxml_emitter_params(), dfsch_sxml_parser_params(), and native_make_wrapper_type().
#define DFSCH_KEYWORD_PARSER_END (args)
Value:
dfsch_error("exception:unknown-keyword", dfsch___keyword);   \
  }
Definition at line 636 of file dfsch.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_sxml_emitter_params(), dfsch_sxml_parser_params(), and native_make_wrapper_type().
#define DFSCH_LOCAL_SYMBOL_CACHE (symbol, name) static DFSCH_SYMBOL_CACHE(symbol, name)
Definition at line 563 of file dfsch.h.
#define DFSCH_OBJECT_ARG (al, name)
Value:
if (DFSCH_UNLIKELY(!DFSCH_PAIR_P((al))))          \
    dfsch_error("exception:required-argument-missing",  \
                dfsch_make_string_cstr(#name));\
  (name) = DFSCH_FAST_CAR((al)); \
  (al) = DFSCH_FAST_CDR((al))
Parses one argument of no specific type from argument list and assigns it to given variable (or l-value)
Parameters:
al Argument list
name Variable or l-value (also used as argument name in exceptions)
Definition at line 464 of file dfsch.h.
Referenced by decoded_time_apply(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), make_slots(), native_alist_2_hash(), native_apply(), native_channel_read(), native_channel_write(), native_close_file_port(), native_closedir(), native_condition_broadcast(), native_condition_signal(), native_condition_wait(), native_cxr(), native_display(), native_eof_object_p(), native_eval(), native_eval_proc(), native_force(), native_hash_2_alist(), native_hash_p(), native_hash_ref(), native_hash_set(), native_hash_set_if_exists(), native_hash_unset(), native_iso_format_time(), native_list_2_weak_vector(), native_lseek(), native_make_weak_reference(), native_mutex_lock(), native_mutex_trylock(), native_mutex_unlock(), native_port_seek(), native_port_tell(), native_readdir(), native_regex_match_p(), native_regex_substrings(), native_set_current_error_port(), native_set_current_input_port(), native_set_current_output_port(), native_sig(), native_stream_car(), native_stream_cdr(), native_string_output_port_value(), native_thread_create(), native_thread_detach(), native_thread_join(), native_weak_reference_dereference(), native_weak_reference_live_p(), native_weak_vector_2_list(), native_weak_vector_length(), native_weak_vector_ref(), native_weak_vector_set(), native_write(), stat_apply(), and throw_proc_arg().
#define DFSCH_OBJECT_ARG_OPT (al, name, default)
Value:
if (!DFSCH_PAIR_P((al))) \
   { (name) = (default);}else\
  {(name) = DFSCH_FAST_CAR((al)); \
  (al) = DFSCH_FAST_CDR((al));}
Parses one argument of no specific type from argument list and assigns it to given variable (or l-value). Uses default value instead of throwing exception when there are no arguments left.
Parameters:
al Argument list
name Variable or l-value.
default Default value
Definition at line 492 of file dfsch.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), inet_base64_encode(), native_alist_2_hash(), native_decode_universal_time(), native_display(), native_get_decoded_time(), native_iso_format_time(), native_make_hash(), native_make_weak_vector(), native_newline(), native_port_read_buf(), native_port_read_line(), native_port_write_buf(), native_read(), native_thread_create(), native_unwrap(), native_wrap(), and native_write().
#define DFSCH_OBJECT_CACHE (constructor, name)
Value:
dfsch_object_t* name(){                                               \
    static dfsch_object_t* dfsch___cache = NULL;                        \
    if (!dfsch___cache)                                                 \
      dfsch___cache = constructor;                                      \
    return dfsch___cache;                                               \
  }
Definition at line 551 of file dfsch.h.
#define DFSCH_SYMBOL_ARG (al, name) DFSCH_GENERIC_ARG(al, name, char*, dfsch_symbol)
Definition at line 640 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_SYMBOL_ARG_OPT (al, default, name) DFSCH_GENERIC_ARG_OPT(al, name, default, char*, dfsch_symbol)
Definition at line 642 of file dfsch.h.
#define DFSCH_SYMBOL_CACHE (symbol, name) DFSCH_OBJECT_CACHE(dfsch_make_symbol(symbol), name)
Definition at line 560 of file dfsch.h.
#define DFSCH_TRUE_P (o) ((o) != NULL)
Definition at line 455 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_sxml_emitter_params(), and dfsch_sxml_parser_params().
#define DFSCH_TYPE_ARG (al, name) DFSCH_GENERIC_ARG(al, name, dfsch_type_t*, dfsch_object_as_type)
Definition at line 644 of file dfsch.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_TYPE_ARG_OPT (al, default, name) DFSCH_GENERIC_ARG_OPT(al, name, default, dfsch_type_t*, dfsch_object_as_type)
Definition at line 646 of file dfsch.h.
Typedef Documentation
typedef struct dfsch_object_t dfsch_object_t
C datatype for scheme objects
Definition at line 60 of file dfsch.h.
typedef dfsch_object_t*(* dfsch_primitive_impl_t)(void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Native functions prototype.
Parameters:
baton Context pointer passed to callback
args Function arguments as scheme list
esc Tail call continuation - function should pass this value to functions which accept it and their return value is also return value of this native function.
Definition at line 83 of file dfsch.h.
typedef struct dfsch_symbol_iter_t dfsch_symbol_iter_t
Iterator for dfsch_get_next_symbol
Definition at line 443 of file dfsch.h.
typedef struct dfsch_tail_escape_t dfsch_tail_escape_t
Continuation used for tail-call elimination.
Definition at line 57 of file dfsch.h.
typedef struct dfsch_type_t dfsch_type_t
Representation of scheme datatypes.
Definition at line 63 of file dfsch.h.
Function Documentation
dfsch_object_t* dfsch_append (dfsch_object_t * llist)
Concatenate lists
Definition at line 1291 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, DFSCH_PAIR_P, dfsch_type_error(), and PAIR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_load_extend_path(), and dfsch_quasiquote().
{
  dfsch_object_t* head=NULL;
  dfsch_object_t* tail=NULL;
  dfsch_object_t* i = llist;
  dfsch_object_t* j;
  if (!llist)
    return NULL;
  while(DFSCH_PAIR_P(i) && DFSCH_PAIR_P(DFSCH_FAST_CDR(i))){
    j = DFSCH_FAST_CAR(i);
    while(DFSCH_PAIR_P(j)){
      if (head){
        object_t* tmp = dfsch_cons(DFSCH_FAST_CAR(j),NULL);
        DFSCH_FAST_CDR_MUT(tail) = tmp;
        tail = tmp;
      }else{
        head = tail = dfsch_cons(DFSCH_FAST_CAR(j),NULL);
      }
      j = DFSCH_FAST_CDR(j);
    }
    if (j && !DFSCH_PAIR_P(j)) {
      dfsch_type_error(j, PAIR, 0);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (!DFSCH_PAIR_P(i)){
    dfsch_type_error(i, PAIR, 0);
  }
  if (tail){
    DFSCH_FAST_CDR_MUT(tail) = DFSCH_FAST_CAR(i);
  }else{
    head = DFSCH_FAST_CAR(i);
  }
  return head;
}
dfsch_object_t* dfsch_apply (dfsch_object_t * proc, dfsch_object_t * args)
Apply procedure to given arguments
Definition at line 2765 of file dfsch.c.
References dfsch__get_thread_info(), and dfsch_apply_impl().
Referenced by async_apply_check(), dfsch_collections_priority_queue_push(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_enter_debugger(), dfsch_invoke_restart(), dfsch_macro_expand(), dfsch_signal(), dfsch_sort_list(), lisp_callback(), parser_apply(), thread_function(), wrapper_equal_p(), wrapper_hash(), and wrapper_write().
{
  return dfsch_apply_impl(proc, args, NULL, NULL, dfsch__get_thread_info());
}
dfsch_object_t* dfsch_apply_tr (dfsch_object_t * proc, dfsch_object_t * args, dfsch_tail_escape_t * esc)
Extended variant of dfsch_apply with support for tail recursion
Definition at line 2760 of file dfsch.c.
References dfsch__get_thread_info(), and dfsch_apply_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_perform_tr(), native_apply(), and wrapper_apply().
{
  return dfsch_apply_impl(proc, args, NULL, esc, dfsch__get_thread_info());
}
dfsch_object_t* dfsch_assert_instance (dfsch_object_t * obj, dfsch_type_t * type)
Definition at line 197 of file dfsch.c.
References DFSCH_END_WITH_RETRY_WITH_RESTART, DFSCH_INSTANCE_P, dfsch_make_symbol(), dfsch_type_error(), and DFSCH_WITH_RETRY_WITH_RESTART.
Referenced by dfsch_condition_field(), dfsch_condition_fields(), and dfsch_condition_put_field().
{
  dfsch_object_t* o = obj;
  while (!DFSCH_INSTANCE_P(o, type)){
    DFSCH_WITH_RETRY_WITH_RESTART(dfsch_make_symbol("use-value"),
                                  "Retry with alternate value") {
      dfsch_type_error(o, type, 1);
    } DFSCH_END_WITH_RETRY_WITH_RESTART(o);
  }
  return o;
}
void* dfsch_assert_type (dfsch_object_t * obj, dfsch_type_t * type)
Definition at line 187 of file dfsch.c.
References DFSCH_END_WITH_RETRY_WITH_RESTART, dfsch_make_symbol(), dfsch_type_error(), DFSCH_TYPE_OF, and DFSCH_WITH_RETRY_WITH_RESTART.
Referenced by dfsch_restart_description(), dfsch_restart_name(), and dfsch_restart_proc().
{
  dfsch_object_t* o = obj;
  while (DFSCH_TYPE_OF(o) != type){
    DFSCH_WITH_RETRY_WITH_RESTART(dfsch_make_symbol("use-value"),
                                  "Retry with alternate value") {
      dfsch_type_error(o, type, 0);
    } DFSCH_END_WITH_RETRY_WITH_RESTART(o);
  }
  return o;
}
dfsch_object_t* dfsch_assoc (dfsch_object_t * key, dfsch_object_t * alist)
Return alist entry with car equal? to key
Definition at line 1531 of file dfsch.c.
References dfsch_equal_p(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=alist;
  while (DFSCH_PAIR_P(i)){
    if (!DFSCH_PAIR_P(DFSCH_FAST_CAR(i))){
      dfsch_error("Not a alist",(object_t*)alist);
    }
    if (dfsch_equal_p(key, DFSCH_FAST_CAR(DFSCH_FAST_CAR(i)))){
      return DFSCH_FAST_CAR(i);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a alist", (object_t*)i);
  }
  return NULL;
}
dfsch_object_t* dfsch_assq (dfsch_object_t * key, dfsch_object_t * alist)
Return alist entry with car eq? to key
Definition at line 1557 of file dfsch.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by dfsch_condition_field(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=alist;
  while (DFSCH_PAIR_P(i)){
    if (!DFSCH_PAIR_P(DFSCH_FAST_CAR(i))){
      dfsch_error("Not a alist",(object_t*)alist);
    }
    if (key == DFSCH_FAST_CAR(DFSCH_FAST_CAR(i))){
      return DFSCH_FAST_CAR(i);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a alist",(object_t*)i);
  }
  return NULL;
}
dfsch_object_t* dfsch_assv (dfsch_object_t * key, dfsch_object_t * alist)
Return alist entry with car eqv? to key
Definition at line 1582 of file dfsch.c.
References dfsch_eqv_p(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=alist;
  while (DFSCH_PAIR_P(i)){
    if (!DFSCH_PAIR_P(DFSCH_FAST_CAR(i))){
      dfsch_error("Not a alist",(object_t*)alist);
    }
    if (dfsch_eqv_p(key, DFSCH_FAST_CAR(DFSCH_FAST_CAR(i)))){
      return DFSCH_FAST_CAR(i);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_error("Not a alist",(object_t*)i);
  }
  return NULL;
}
void dfsch_async_apply_check ()
Check for pending asynchronous apply
Definition at line 2425 of file dfsch.c.
References async_apply_check(), and dfsch__get_thread_info().
{
  async_apply_check(dfsch__get_thread_info());
}
void dfsch_async_apply_self (dfsch_object_t * proc)
Apply procedure later in evaluation (useful for signal handlers)
Definition at line 2026 of file dfsch.c.
References dfsch__thread_info_t::async_apply, and dfsch__get_thread_info().
Referenced by sigint_handler_break().
{
  dfsch__get_thread_info()->async_apply = proc;
}
int dfsch_atom_p (dfsch_object_t * obj)
Is OBJ an atom? (i.e. not pair)
Definition at line 843 of file dfsch.c.
References DFSCH_PAIR_P.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return !DFSCH_PAIR_P(obj);
}
dfsch_object_t* dfsch_bool (int bool)
Return true or nil depending on value of BOOL.
Definition at line 1826 of file dfsch.c.
References DFSCH_SYM_TRUE.
Referenced by boolean_accessor_ref(), decoded_time_apply(), DFSCH_DEFINE_PRIMITIVE(), dfsch_number_even_p(), dfsch_number_odd_p(), DFSCH_PRIMITIVE_HEAD(), dfsch_type_error(), native_eof_object_p(), native_hash_p(), native_hash_set_if_exists(), native_hash_unset(), native_mutex_trylock(), native_regex_match_once_p(), native_regex_match_p(), native_weak_reference_live_p(), and stat_apply().
{
  return bool ? DFSCH_SYM_TRUE : NULL;
}
dfsch_object_t* dfsch_car (dfsch_object_t * pair)
Return first (car) item of pair
Definition at line 936 of file dfsch.c.
References DFSCH_ASSERT_PAIR, and DFSCH_FAST_CAR.
Referenced by command_exit(), command_print(), command_write(), dfsch_alist_2_hash(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_copy_immutable(), dfsch_list_item(), dfsch_load(), dfsch_load_extend_path(), dfsch_provide(), dfsch_quasiquote(), dfsch_require(), dfsch_string_2_object(), dfsch_string_list_append(), directive_import(), list_get(), list_peek(), list_source(), native_cxr(), native_stream_car(), process_directive(), and search_modules().
{
  dfsch_object_t* p = DFSCH_ASSERT_PAIR(pair);
  return DFSCH_FAST_CAR(p);
}
dfsch_object_t* dfsch_cdr (dfsch_object_t * pair)
Return second (cdr) item of pair
Definition at line 940 of file dfsch.c.
References DFSCH_ASSERT_PAIR, and DFSCH_FAST_CDR.
Referenced by command_print(), command_write(), dfsch_alist_2_hash(), dfsch_condition_field(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_copy_immutable(), dfsch_load(), dfsch_quasiquote(), dfsch_stream_cdr(), dfsch_string_list_append(), directive_import(), list_get(), list_seek(), list_skip(), list_source(), native_cxr(), process_directive(), and search_modules().
{
  dfsch_object_t* p = DFSCH_ASSERT_PAIR(pair);
  return DFSCH_FAST_CDR(p);
}
void dfsch_cerror (char * type, dfsch_object_t * data)
Convenience wrapper for signaling recoverable error condition
Definition at line 2015 of file dfsch.c.
References dfsch_condition(), DFSCH_END_WITH_SIMPLE_RESTART, DFSCH_ERROR_TYPE, dfsch_make_string_cstr(), dfsch_make_symbol(), dfsch_signal(), and DFSCH_WITH_SIMPLE_RESTART.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  DFSCH_WITH_SIMPLE_RESTART(dfsch_make_symbol("continue"),
                            "Ignore error condition"){
    dfsch_signal(dfsch_condition(DFSCH_ERROR_TYPE,
                                 "message", dfsch_make_string_cstr(name),
                                 "object", detail,
                                 NULL));
  } DFSCH_END_WITH_SIMPLE_RESTART;
}
int dfsch_closure_p (dfsch_object_t * obj)
Is OBJ a lambda-closure?
int dfsch_compare_symbol (dfsch_object_t * symbol, char * string)
Compares value of given symbol to string.
Definition at line 1821 of file dfsch.c.
References ascii_strcasecmp, and dfsch_symbol().
Referenced by condition_write(), decoded_time_apply(), dfsch_format_trace(), native_lseek(), native_sig(), prettyprint_condition_fields(), and stat_apply().
{
  return (ascii_strcasecmp(string, dfsch_symbol(symbol)) == 0);
}
dfsch_object_t* dfsch_compile_lambda_list (dfsch_object_t * list)
Definition at line 2549 of file dfsch.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LAMBDA_LIST_TYPE, dfsch_list_length_fast(), dfsch_make_object_var(), DFSCH_PAIR_P, lambda_list_t::positional, lambda_list_t::positional_count, and lambda_list_t::rest.
Referenced by dfsch_destructuring_bind(), and dfsch_named_lambda().
{
  lambda_list_t* ll;
  long count = dfsch_list_length_fast(list);
  dfsch_object_t* i = list;
  size_t j;
  if (count == -1){
    count = 0;
  }
  ll = dfsch_make_object_var(DFSCH_LAMBDA_LIST_TYPE,
                             sizeof(dfsch_object_t*) * count);
  ll->positional_count = count;
  j = 0;
  while (DFSCH_PAIR_P(i)){
    if (j >= count){
      dfsch_error("wtf?", NULL);
    }
    ll->positional[j] = DFSCH_FAST_CAR(i);
    j++;
    i = DFSCH_FAST_CDR(i);
  }
  ll->rest = i;
  return ll;
}
dfsch_object_t* dfsch_cons (dfsch_object_t * car, dfsch_object_t * cdr)
Construct pair object
Definition at line 878 of file dfsch.c.
References dfsch_pair_t::car, dfsch_pair_t::cdr, and DFSCH_TAG_ENCODE.
Referenced by class_equal_p(), dfsch_append(), dfsch_cmdopts_argv_to_list(), dfsch_compute_restarts(), dfsch_condition_put_field(), dfsch_declare(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_enter_debugger(), dfsch_env_get(), dfsch_eqhash_2_alist(), dfsch_get_list_annotation(), dfsch_get_slots(), dfsch_hash_2_alist(), dfsch_http_query_2_alist(), dfsch_http_split_path(), dfsch_list_copy(), dfsch_parser_parse_object(), dfsch_provide(), dfsch_quasiquote(), dfsch_read_scm_stream(), dfsch_reverse(), dfsch_send(), dfsch_send_tr(), dfsch_signal(), dfsch_string_2_list(), dfsch_string_split(), dfsch_string_split_byte(), dfsch_string_split_char(), dfsch_string_utf8_2_list(), dfsch_xml_signal_error(), dfsch_zip(), load_callback(), lookup_impl(), parser_abort(), read_callback(), start_element_handler(), sxml_append(), and sxml_push().
{
  dfsch_pair_t* p = GC_NEW(dfsch_pair_t);
  p->car = car;
  p->cdr = cdr;
  return DFSCH_TAG_ENCODE(p, 1);
}
dfsch_object_t* dfsch_cons_immutable (dfsch_object_t * car, dfsch_object_t * cdr)
Construct immutable pair object
Definition at line 887 of file dfsch.c.
References dfsch_pair_t::car, dfsch_pair_t::cdr, and DFSCH_TAG_ENCODE.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_get_trace(), and dfsch_list_copy_immutable().
{
  dfsch_pair_t* p = GC_NEW(dfsch_pair_t);
  p->car = car;
  p->cdr = cdr;
  return DFSCH_TAG_ENCODE(p, 3);
}
dfsch_object_t* dfsch_define (dfsch_object_t * name, dfsch_object_t * value, dfsch_object_t * env)
Define variable name in environment env
Definition at line 2345 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_set(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, environment_t::owner, and environment_t::values.
Referenced by dfsch_define_cstr(), DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  environment_t* e = (environment_t*)DFSCH_ASSERT_TYPE(env,
                                                       DFSCH_ENVIRONMENT_TYPE);
  dfsch__thread_info_t *ti = dfsch__get_thread_info();
  if (e->owner != ti){
    e->owner = NULL;
    DFSCH_RWLOCK_WRLOCK(&environment_rwlock);
  }
  dfsch_eqhash_set(&e->values,
                   name, value);
  if (e->owner != ti){
    DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  }
  return value;
}
dfsch_object_t* dfsch_define_cstr (dfsch_object_t * ctx, char * name, dfsch_object_t * obj)
Define new variable in given context
Definition at line 2848 of file dfsch.c.
References dfsch_define(), and dfsch_make_symbol().
Referenced by debug_main(), dfsch__bignum_register(), dfsch__conditions_register(), dfsch__control_register(), dfsch__format_native_register(), dfsch__hash_native_register(), dfsch__native_cxr_register(), dfsch__native_register(), dfsch__number_native_register(), dfsch__object_native_register(), dfsch__port_native_register(), dfsch__promise_native_register(), dfsch__random_register(), dfsch__string_native_register(), dfsch__system_register(), dfsch__weak_native_register(), dfsch__wrapper_native_register(), dfsch_introspect_register(), dfsch_load_extend_path(), dfsch_load_register(), dfsch_make_context(), dfsch_module_cdebug_register(), dfsch_module_cmdopts_register(), dfsch_module_collections_register(), dfsch_module_console_register(), dfsch_module_extref_register(), dfsch_module_gcollect_register(), dfsch_module_inet_register(), dfsch_module_process_register(), dfsch_module_regex_register(), dfsch_module_sxml_register(), dfsch_module_threads_register(), dfsch_module_unix_register(), dfsch_module_xml_register(), dfsch_port_unsafe_register(), dfsch_provide(), load_scm(), and main().
{
  return dfsch_define(dfsch_make_symbol(name),
                      obj,
                      ctx);
}
dfsch_object_t* dfsch_destructuring_bind (dfsch_object_t * arglist, dfsch_object_t * list, dfsch_object_t * env)
Definition at line 2622 of file dfsch.c.
References destructure_impl(), dfsch_compile_lambda_list(), DFSCH_LAMBDA_LIST_TYPE, dfsch_new_frame(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  environment_t* e = dfsch_new_frame(env);
  lambda_list_t* l;
  if (DFSCH_TYPE_OF(arglist) != DFSCH_LAMBDA_LIST_TYPE){
    l = dfsch_compile_lambda_list(arglist);
  } else {
    l = arglist;
  }
  destructure_impl(l, list, e);
  return e;
}
dfsch_object_t* dfsch_ensure_mutable_list (dfsch_object_t * list)
Return mutable list - argument if it is mutable, fresh copy if not
Definition at line 1061 of file dfsch.c.
References dfsch_list_copy(), dfsch_list_length_check(), and dfsch_list_mutable_p().
Referenced by dfsch_sort_list().
{
  if (dfsch_list_mutable_p(list)){
    return list;
  }
  dfsch_list_length_check(list);
  return dfsch_list_copy(list);
}
dfsch_object_t* dfsch_env_get (dfsch_object_t * name, dfsch_object_t * env)
Get value of variable name in environment env. Return empty list in case of failure.
Definition at line 2271 of file dfsch.c.
References DFSCH_ASSERT_TYPE, dfsch_cons(), DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_ref(), DFSCH_INVALID_OBJECT, DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, environment_t::parent, and environment_t::values.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_env_get_cstr().
{
  environment_t *i;
  object_t* ret;
  i = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  DFSCH_RWLOCK_RDLOCK(&environment_rwlock);
  while (i){
    ret = dfsch_eqhash_ref(&i->values, name);
    if (ret != DFSCH_INVALID_OBJECT){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return dfsch_cons(ret, NULL);
    }
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  return NULL;
}
dfsch_object_t* dfsch_env_get_cstr (dfsch_object_t * ctx, char * name)
Look up value of given variable, returns list of one item if sucessful, empty list if not
Definition at line 2869 of file dfsch.c.
References dfsch_env_get(), and dfsch_make_symbol().
Referenced by dfsch_load(), dfsch_load_extend_path(), dfsch_provide(), and dfsch_require().
{
  return dfsch_env_get(dfsch_make_symbol(name), ctx);
}
int dfsch_eq_p (dfsch_object_t * a, dfsch_object_t * b)
Same object? (i.e. equal addresses)
Definition at line 76 of file dfsch.c.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return (a==b);
}
int dfsch_equal_p (dfsch_object_t * a, dfsch_object_t * b)
Equal object? (i.e. equal contents)
Definition at line 93 of file dfsch.c.
References dfsch_equal_p(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_PAIR_P, and DFSCH_TYPE_OF.
Referenced by dfsch_assoc(), DFSCH_DEFINE_PRIMITIVE(), dfsch_equal_p(), dfsch_hash_ref_fast(), dfsch_hash_set(), dfsch_hash_set_if_exists(), dfsch_hash_unset(), dfsch_member(), fracnum_equal_p(), pair_equal_p(), and vector_equal_p().
{
  if (a==b)
    return 1;
  if (!a || !b)
    return 0;
  if (DFSCH_TYPE_OF(a) != DFSCH_TYPE_OF(b)){
    if (DFSCH_PAIR_P(a) && DFSCH_PAIR_P(b)){
      return (dfsch_equal_p(DFSCH_FAST_CAR(a), DFSCH_FAST_CAR(b)) &&
              dfsch_equal_p(DFSCH_FAST_CDR(a), DFSCH_FAST_CDR(b)));
    } else {
      return 0;
    }
  }
  if (!DFSCH_TYPE_OF(a))
    return 0;
  if (!DFSCH_TYPE_OF(a)->equal_p)
    return 0;
  return DFSCH_TYPE_OF(a)->equal_p(a,b);
}
int dfsch_eqv_p (dfsch_object_t * a, dfsch_object_t * b)
Same object or number?
Definition at line 80 of file dfsch.c.
References dfsch_number_equal_p(), dfsch_number_p(), and DFSCH_TYPE_OF.
Referenced by dfsch_assv(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_memv().
{
  if (a==b)
    return 1;
  if (!a || !b)
    return 0;
  if ((DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b)) && dfsch_number_p(a))
    return dfsch_number_equal_p(a,b);
  return 0;
}
void dfsch_error (char * type, dfsch_object_t * data)
Convenience wrapper for signaling error condition from C code
Definition at line 2008 of file dfsch.c.
References dfsch_condition(), DFSCH_ERROR_TYPE, dfsch_make_string_cstr(), and dfsch_signal().
Referenced by decoded_time_apply(), destructure_impl(), destructuring_eval(), dfsch_apply_impl(), dfsch_assoc(), dfsch_assq(), dfsch_assv(), dfsch_bignum_div(), dfsch_bignum_exp(), dfsch_bignum_from_number(), dfsch_bignum_to_string(), dfsch_channel_read(), dfsch_channel_write(), dfsch_class_add_method(), dfsch_class_remove_method(), dfsch_collections_priority_queue_empty_p(), dfsch_collections_priority_queue_pop(), dfsch_collections_priority_queue_push(), dfsch_compile_lambda_list(), dfsch_condition_broadcast(), dfsch_condition_signal(), dfsch_condition_wait(), dfsch_condition_with_fields(), dfsch_console_read_object(), dfsch_decoded_time_get_tm(), DFSCH_DEFINE_PRIMITIVE(), dfsch_eval_proc_impl(), dfsch_extref_ref(), dfsch_find_method(), dfsch_find_slot(), dfsch_force_promise(), dfsch_format(), dfsch_invoke_restart(), dfsch_list_2_string_utf8(), dfsch_list_item(), dfsch_load(), dfsch_load_so(), dfsch_make_class(), dfsch_make_condition(), dfsch_make_file_random_state(), dfsch_make_instance(), dfsch_make_number_from_string(), dfsch_mutex_lock(), dfsch_mutex_trylock(), dfsch_mutex_unlock(), dfsch_number_denominator(), dfsch_number_div(), dfsch_number_div_i(), dfsch_number_mod(), dfsch_number_numerator(), dfsch_number_to_double(), dfsch_number_to_int64(), dfsch_number_to_long(), dfsch_number_to_string(), dfsch_open_file_port(), dfsch_parser_read_from_port(), dfsch_perform_tr(), dfsch_port_batch_read(), dfsch_port_batch_read_end(), dfsch_port_batch_read_start(), dfsch_port_read_buf(), dfsch_port_seek(), dfsch_port_tell(), dfsch_port_write_buf(), dfsch_process_close_port(), dfsch_provide(), dfsch_random_get_bytes(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_regex_match_p(), dfsch_regex_substrings(), dfsch_set(), dfsch_set_current_error_port(), dfsch_set_current_input_port(), dfsch_set_current_output_port(), dfsch_slot_ref(), dfsch_slot_set(), dfsch_string_2_object(), dfsch_string_2_object_list(), dfsch_string_output_port_value(), dfsch_string_ref(), dfsch_string_replace(), dfsch_string_split(), dfsch_string_split_byte(), dfsch_string_split_char(), dfsch_string_substring(), dfsch_string_substring_utf8(), dfsch_string_utf8_ref(), dfsch_sxml_emit_file(), dfsch_sxml_parse_file(), dfsch_thread_detach(), dfsch_thread_join(), dfsch_throw(), dfsch_unix_closedir(), dfsch_unix_get_stat(), dfsch_unix_readdir(), dfsch_unset(), dfsch_unwrap(), dfsch_vector_ref(), dfsch_vector_set(), dfsch_weak_reference_dereference(), dfsch_weak_reference_live_p(), dfsch_weak_vector_2_list(), dfsch_weak_vector_as_array(), dfsch_weak_vector_ref(), dfsch_weak_vector_set(), dfsch_wrap(), dfsch_write_strbuf(), dfsch_write_unreadable_start(), dfsch_xml_destroy_parser(), dfsch_xml_ext_set_character_data_proc(), dfsch_xml_parse_buf(), dfsch_xml_parse_file(), dfsch_xml_parse_port(), dfsch_xml_parser_ref(), dfsch_xml_set_comment_proc(), dfsch_xml_set_end_element_proc(), dfsch_xml_set_processing_instruction_proc(), dfsch_xml_set_start_element_proc(), dfsch_xml_signal_error(), dfsch_zip(), emit_attrs(), emit_object(), errno_error(), eval_list(), file_get_bytes(), file_port_read_buf(), file_port_seek(), file_port_tell(), file_port_write_buf(), int_to_str(), list_get(), list_peek(), list_seek(), list_skip(), lookup_impl(), native_alist_2_hash(), native_lseek(), native_make_hash(), native_sig(), parser_abort(), port_read_buf(), port_write_buf(), read_num_arg(), regex_compile(), rfputs(), spawn_port(), stat_apply(), and string_case().
{
  dfsch_signal(dfsch_condition(DFSCH_ERROR_TYPE,
                               "message", dfsch_make_string_cstr(name),
                               "object", detail,
                               NULL));
}
dfsch_object_t* dfsch_eval (dfsch_object_t * exp, dfsch_object_t * env)
Evaluate expression.
Definition at line 2543 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_parser_parse_object(), dfsch_quasiquote(), and repl_callback().
{
  return dfsch_eval_impl(exp,
                         DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                         NULL, dfsch__get_thread_info());
}
dfsch_object_t* dfsch_eval_list (dfsch_object_t * list, dfsch_object_t * env)
Evaluate multiple expressions and return values of all of them
Definition at line 2488 of file dfsch.c.
References dfsch__get_thread_info(), and eval_list().
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  return eval_list(list, env, dfsch__get_thread_info());
}
dfsch_object_t* dfsch_eval_proc (dfsch_object_t * exp, dfsch_object_t * env)
Evaluate multiple expressions returning value of final one.
Definition at line 2675 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_proc_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_force_promise(), dfsch_load_scm(), and main().
{
  return dfsch_eval_proc_impl(code,
                              DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                              NULL,
                              dfsch__get_thread_info());
}
dfsch_object_t* dfsch_eval_proc_tr (dfsch_object_t * code, dfsch_object_t * env, dfsch_tail_escape_t * esc)
Extended variant of dfsch_eval_proc with support for tail recursion
Definition at line 2667 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_proc_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_eval_proc().
{
  return dfsch_eval_proc_impl(code,
                              DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                              esc,
                              dfsch__get_thread_info());
}
dfsch_object_t* dfsch_eval_tr (dfsch_object_t * exp, dfsch_object_t * env, dfsch_tail_escape_t * esc)
Extended variant of dfsch_eval with support for tail recursion
Definition at line 2536 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and dfsch_eval_impl().
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_eval().
{
  return dfsch_eval_impl(exp,
                         DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                         esc, dfsch__get_thread_info());
}
int dfsch_exception_p (dfsch_object_t * obj)
Is OBJ an exception?
dfsch_slot_t* dfsch_find_slot (dfsch_type_t * type, char * name)
Definition at line 342 of file dfsch.c.
References dfsch_error(), dfsch_make_symbol(), dfsch_slot_t::name, dfsch_type_t::slots, dfsch_type_t::superclass, and dfsch_slot_t::type.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_slot_ref_by_name(), and dfsch_slot_set_by_name().
{
  dfsch_slot_t* i;
  while(type){
    if (type->slots){
    i = type->slots;
    while (i->type){
      if (strcmp(i->name, name)==0){
        return i;
      }
      i++;
    }
    }
    type = type->superclass;
  }
  dfsch_error("No such slot", dfsch_make_symbol(name));
}
int dfsch_form_p (dfsch_object_t * obj)
Is OBJ a special form?
Definition at line 863 of file dfsch.c.
References DFSCH_TYPE_OF, and FORM.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == FORM;
}
dfsch_object_t* dfsch_gensym ()
Returns unique generated symbol.
Definition at line 1764 of file dfsch.c.
References dfsch__symbol_t::data, and DFSCH_TAG_ENCODE.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_make_symbol().
{
  symbol_t *s = GC_NEW(symbol_t);
  s->data = NULL;
  return DFSCH_TAG_ENCODE(s, 2);
}
dfsch_object_t* dfsch_get_environment_variables (dfsch_object_t * env)
Definition at line 2377 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_2_alist(), and environment_t::values.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  environment_t* e = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  return dfsch_eqhash_2_alist(&e->values);
}
dfsch_object_t* dfsch_get_list_annotation (dfsch_object_t * list)
Definition at line 1204 of file dfsch.c.
References DFSCH__FAST_CDR_CODED_P, dfsch_cons(), DFSCH_INVALID_OBJECT, DFSCH_PAIR_P, and DFSCH_PAIR_REF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_format_trace(), and dfsch_print_trace_buffer().
{
  dfsch_object_t** i;
  if (!DFSCH_PAIR_P(list) || !DFSCH__FAST_CDR_CODED_P(list)){
    return NULL;
  }
  i = (dfsch_object_t**) DFSCH_PAIR_REF(list);
  while (*i != DFSCH_INVALID_OBJECT){
    i++;
  }
  /* i[1] is last CDR */
  if (i[2] || i[3]){
    return dfsch_cons(i[2], i[3]);
  } else {
    return NULL;
  }
}
char* dfsch_get_next_symbol (dfsch_symbol_iter_t ** iter)
Iterates over all symbols known by interpreter. And returns one per call, useful for things like completion. ITER is pointer to dfsch_symbol_iter_t*, when its value is NULL, new iterator is allocated. NULL is returned, when no more symbols are avaiable.
Definition at line 1835 of file dfsch.c.
References dfsch__symbol_t::data, hash_entry_t::entry, HASH_SIZE, and hash_entry_t::next.
                                                       { // deep magic
  if (*iter == NULL){
    *iter = GC_MALLOC(sizeof(dfsch_symbol_iter_t));
    (*iter)->bucket = 0;
    (*iter)->item = global_symbol_hash[(*iter)->bucket];
  }
  while ((*iter)->bucket < HASH_SIZE){
    if (!(*iter)->item){
      (*iter)->bucket ++;
      (*iter)->item = global_symbol_hash[(*iter)->bucket];
    }else{
      hash_entry_t *i = (*iter)->item;
      (*iter)->item = (*iter)->item->next;
      return i->entry->data;
    }
  }
  return NULL;
}
dfsch_object_t* dfsch_get_slots (dfsch_type_t * type)
Definition at line 318 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CDR_MUT, and dfsch_slot_t::type.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_slot_t* i;
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  dfsch_object_t* tmp;
  while(type){
    if (type->slots){
      i = type->slots;
      while (i->type){
        tmp = dfsch_cons((dfsch_object_t*)i, NULL);
        if (!head) {
          head = tail = tmp;
        } else {
          DFSCH_FAST_CDR_MUT(tail) = tmp;
          tail = tmp;
        }
        i++;
      }
    }
    type = type->superclass;
  }
  return head;
}
dfsch_object_t* dfsch_get_stack_trace ()
Return stack trace for running thread.
uint32_t dfsch_hash (dfsch_object_t * obj)
Get object hash
Definition at line 147 of file dfsch.c.
References DFSCH_TYPE_OF, and ptr_hash().
Referenced by DFSCH_DEFINE_PRIMITIVE(), fracnum_hash(), pair_hash(), and vector_hash().
{
  if (!obj){
    return 0;
  }
  if (!DFSCH_TYPE_OF(obj) || !DFSCH_TYPE_OF(obj)->hash){
    return ptr_hash(obj);
  }
  return DFSCH_TYPE_OF(obj)->hash(obj);
}
int dfsch_instance_p (dfsch_object_t * obj, dfsch_type_t * type)
Is object direct or indirect instance of given type?
Definition at line 183 of file dfsch.c.
References dfsch_superclass_p(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_superclass_p(DFSCH_TYPE_OF(obj), type);
}
dfsch_object_t* dfsch_lambda (dfsch_object_t * env, dfsch_object_t * args, dfsch_object_t * code)
Create new lambda closure.
Definition at line 1880 of file dfsch.c.
References dfsch_named_lambda().
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  return dfsch_named_lambda(env, args, code, NULL);
}
dfsch_object_t* dfsch_list (size_t count, ...)
Construct list from arguments
Definition at line 1333 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, and dfsch_multicons().
Referenced by character_data_handler(), destructure_impl(), destructuring_eval(), dfsch_collections_priority_queue_push(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_eqhash_2_alist(), dfsch_hash_2_alist(), dfsch_hash_ref(), dfsch_http_query_2_alist(), dfsch_load_extend_path(), dfsch_load_register(), dfsch_perform_tr(), dfsch_quasiquote(), dfsch_sort_list(), dfsch_sxml_emit_file(), dfsch_sxml_parse_file(), dfsch_xml_parse_file(), dfsch_xml_signal_error(), end_element_handler(), errno_error(), http_split_query(), lisp_callback(), native_pipe(), native_wait(), native_waitpid(), start_element_handler(), wrapper_apply(), wrapper_equal_p(), wrapper_hash(), and wrapper_write().
{
  dfsch_object_t *head;
  dfsch_object_t *cur;
  size_t i;
  va_list al;
  va_start(al,count);
  if (count == 0)
    return NULL;
  head = cur = dfsch_multicons(count);
  for(i = 0; i < count; ++i){
    DFSCH_FAST_CAR(cur) = va_arg(al, dfsch_object_t*);
    cur = DFSCH_FAST_CDR(cur);
  }
  va_end(al);
  return head;
}
dfsch_object_t* dfsch_list_2_vector (dfsch_object_t * list)
Converts list to vector.
Definition at line 2118 of file dfsch.c.
References vector_t::data, dfsch_list_as_array(), dfsch_make_object_var(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_parser_parse_object().
{
  vector_t* vector;
  size_t length;
  dfsch_object_t** array;
  array = dfsch_list_as_array(list, &length);
  vector = (vector_t*)dfsch_make_object_var(VECTOR,
                                            length * sizeof(dfsch_object_t*));
  vector->length = length;
  memcpy(vector->data, array, sizeof(dfsch_object_t*) * length);
  return (object_t*)vector;
}
dfsch_object_t* dfsch_list_annotate (dfsch_object_t * list, dfsch_object_t * source, dfsch_object_t * location)
Definition at line 1170 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_INVALID_OBJECT, dfsch_list_length(), DFSCH_MAKE_CLIST, and DFSCH_PAIR_P.
Referenced by parse_close().
{
  dfsch_object_t* j = list;
  size_t i=0;
  size_t len;
  object_t** data;
  int proper;
  if (list == NULL){
    return NULL;
  }
  len = dfsch_list_length(list, &proper);
  data = GC_MALLOC(sizeof(object_t*)*(len+4));
  while (DFSCH_PAIR_P(j)){
    if (i >= len){
      break; /* Can happen due to race condition in user code */
    }
    data[i] = DFSCH_FAST_CAR(j);
    j = DFSCH_FAST_CDR(j);
    i++;
  }
  data[i] = DFSCH_INVALID_OBJECT;
  data[i+1] = j;
  data[i+2] = source;
  data[i+3] = location;
  return DFSCH_MAKE_CLIST(data);
}
dfsch_object_t** dfsch_list_as_array (dfsch_object_t * list, size_t * length)
Convert struct to C array
Definition at line 1107 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_list_length_check(), and DFSCH_PAIR_P.
Referenced by dfsch_list_2_vector(), dfsch_list_2_weak_vector(), and dfsch_zip().
{
  dfsch_object_t* j = list;
  size_t i=0;
  size_t len;
  object_t** data;
  len = dfsch_list_length_check(list);
  data = GC_MALLOC(sizeof(object_t*)*len);
  while (DFSCH_PAIR_P(j)){
    if (i >= len){
      break; /* Can happen due to race condition in user code */
    }
    data[i] = DFSCH_FAST_CAR(j);
    j = DFSCH_FAST_CDR(j);
    i++;
  }
  if (length){
    *length = len;
  }
  return data;
}
dfsch_object_t* dfsch_list_copy (dfsch_object_t * list)
Copy list.
Definition at line 1356 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_ensure_mutable_list().
{
  dfsch_object_t *head;
  dfsch_object_t *tail;
  dfsch_object_t *i =  list;
  head = tail = NULL;
  while(DFSCH_PAIR_P(i)){
    if (head){
      object_t* tmp = dfsch_cons(DFSCH_FAST_CAR(i),NULL);
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    }else{
      head = tail = dfsch_cons(DFSCH_FAST_CAR(i),NULL);
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i && !DFSCH_PAIR_P(i)){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return (object_t*)head;
}
dfsch_object_t* dfsch_list_copy_immutable (dfsch_object_t * list)
Definition at line 1132 of file dfsch.c.
References dfsch_car(), dfsch_cdr(), dfsch_cons_immutable(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_INVALID_OBJECT, dfsch_list_length(), DFSCH_MAKE_CLIST, and DFSCH_PAIR_P.
{
  dfsch_object_t* j = list;
  size_t i=0;
  size_t len;
  object_t** data;
  int proper;
  if (list == NULL){
    return NULL;
  }
  len = dfsch_list_length(list, &proper);
  if (len == 1){
    return dfsch_cons_immutable(dfsch_car(list),
                                dfsch_cdr(list));
  }
  data = GC_MALLOC(sizeof(object_t*)*(len+4));
  while (DFSCH_PAIR_P(j)){
    if (i >= len){
      break; /* Can happen due to race condition in user code */
    }
    data[i] = DFSCH_FAST_CAR(j);
    j = DFSCH_FAST_CDR(j);
    i++;
  }
  data[i] = DFSCH_INVALID_OBJECT;
  i++;
  data[i] = j;
  data[i+1] = NULL;
  data[i+2] = NULL;
  return DFSCH_MAKE_CLIST(data);
}
dfsch_object_t* dfsch_list_from_array (dfsch_object_t ** array, size_t length)
Construct list from C array.
Definition at line 1090 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, and dfsch_multicons().
Referenced by dfsch_vector_2_list(), and dfsch_weak_vector_2_list().
{
  dfsch_object_t *head;
  dfsch_object_t *cur;
  size_t i;
  if (length == 0)
    return NULL;
  head = cur = dfsch_multicons(length);
  for(i = 0; i < length; ++i){
    DFSCH_FAST_CAR(cur) = array[i];
    cur = DFSCH_FAST_CDR(cur);
  }
  return (object_t*)head;
}
dfsch_object_t* dfsch_list_item (dfsch_object_t * list, int index)
Returns given item of list.
Definition at line 1077 of file dfsch.c.
References dfsch_car(), dfsch_error(), DFSCH_FAST_CDR, dfsch_make_number_from_long(), and DFSCH_PAIR_P.
Referenced by debug_invoke_restart(), dfsch_alist_2_hash(), DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* it = list;
  int i;
  for (i=0; i<index; ++i){
    if (DFSCH_PAIR_P(it)){
      it = DFSCH_FAST_CDR(it);
    }else{
      dfsch_error("No such item of list", dfsch_make_number_from_long(index));
    }
  }
  return dfsch_car(it);
}
long dfsch_list_length (dfsch_object_t * list, int * proper)
Returns number of items in given list or -1 for infinite lists
Definition at line 981 of file dfsch.c.
References DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by dfsch_list_annotate(), dfsch_list_copy_immutable(), dfsch_list_length_check(), and emit_attrs().
{
  dfsch_object_t *i;
  dfsch_object_t *j;
  long count;
  if (!list)
    return 0;
  if (!DFSCH_PAIR_P(list))
    return -1;
  i = j = list;
  count = 0;
  while (DFSCH_PAIR_P(i)){
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return -1;
    }
    j = DFSCH_FAST_CDR(j);
    if (!DFSCH_PAIR_P(i)){
      break;
    }
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return -1;
    }
  }
  if (proper){
    *proper = (i == NULL);
  } else {
    if (i) {
      return -1;
    }
  }
  return count;
}
long dfsch_list_length_check (dfsch_object_t * list)
Returns number of items in given finite list, fail otherwise
Definition at line 1069 of file dfsch.c.
References dfsch_list_length(), DFSCH_LIST_TYPE, and dfsch_type_error().
Referenced by command_exit(), DFSCH_DEFINE_PRIMITIVE(), dfsch_ensure_mutable_list(), dfsch_list_2_string(), dfsch_list_as_array(), make_bignum_from_digits(), and make_slots().
{
  long len;
  len = dfsch_list_length(list, NULL);
  if (len < 0)
    dfsch_type_error(list, DFSCH_LIST_TYPE, 1);
  return len;
}
long dfsch_list_length_fast (dfsch_object_t * list)
Returns number of items in given finite list
Definition at line 961 of file dfsch.c.
References DFSCH_FAST_CDR, and DFSCH_PAIR_P.
Referenced by dfsch_compile_lambda_list().
{
  dfsch_object_t *i;
  long count;
  if (!list)
    return 0;
  if (!DFSCH_PAIR_P(list))
    return -1;
  i = list;
  count = 0;
  while (DFSCH_PAIR_P(i)){
    i = DFSCH_FAST_CDR(i);
    ++count;
  }
  return count;
}
int dfsch_list_mutable_p (dfsch_object_t * list)
Check whenever list is mutable
Definition at line 1023 of file dfsch.c.
References DFSCH_FAST_CDR, DFSCH_MUTABLE_PAIR_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_ensure_mutable_list().
{
  dfsch_object_t *i;
  dfsch_object_t *j;
  long count;
  if (!list)
    return 1;
  if (DFSCH_TYPE_OF(list) != DFSCH_MUTABLE_PAIR_TYPE){
    return 0;
  }
  i = j = list;
  count = 0;
  while (DFSCH_TYPE_OF(i) == DFSCH_MUTABLE_PAIR_TYPE){
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return 0;
    }
    j = DFSCH_FAST_CDR(j);
    if (DFSCH_TYPE_OF(i) != DFSCH_MUTABLE_PAIR_TYPE){
      break;
    }
    i = DFSCH_FAST_CDR(i);
    ++count;
    if (i == j) {
      return 0;
    }
  }
  if (i)
    return 0;
  return 1;
}
int dfsch_list_p (dfsch_object_t * obj)
Is OBJ a proper list?
Definition at line 840 of file dfsch.c.
References DFSCH_INSTANCE_P, and DFSCH_LIST_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_LIST_TYPE);
}
dfsch_object_t* dfsch_lookup (dfsch_object_t * name, dfsch_object_t * env)
Get value of variable name in environment env.
Definition at line 2266 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and lookup_impl().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_lookup_cstr().
{
  return lookup_impl(name,
                     DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE),
                     dfsch__get_thread_info());
}
dfsch_object_t* dfsch_lookup_cstr (dfsch_object_t * ctx, char * name)
Looks up value of variable given by NAME. Throws exception:unbound-variable if such variable doesn't exist
Definition at line 2866 of file dfsch.c.
References dfsch_lookup(), and dfsch_make_symbol().
{
  return dfsch_lookup(dfsch_make_symbol(name), ctx);
}
dfsch_object_t* dfsch_macro_expand (dfsch_object_t * macro, dfsch_object_t * args)
Definition at line 2382 of file dfsch.c.
References dfsch_apply(), DFSCH_ASSERT_TYPE, and MACRO.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_eval_impl().
{
  return dfsch_apply(((macro_t*)DFSCH_ASSERT_TYPE(macro, MACRO))->proc, args);
}
int dfsch_macro_p (dfsch_object_t * obj)
Is OBJ a macro?
Definition at line 860 of file dfsch.c.
References DFSCH_TYPE_OF, and MACRO.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == MACRO;
}
dfsch_object_t* dfsch_make_context ()
Allocates new top-level context (environment).
Definition at line 2801 of file dfsch.c.
References dfsch__native_register(), DFSCH_ABSTRACT_TYPE, DFSCH_BOOLEAN_SLOT_TYPE, dfsch_define_cstr(), DFSCH_EMPTY_LIST_TYPE, DFSCH_ENVIRONMENT_TYPE, DFSCH_FORM_REF, DFSCH_FORM_TYPE, DFSCH_FUNCTION_TYPE, DFSCH_IMMUTABLE_PAIR_TYPE, DFSCH_INT_SLOT_TYPE, DFSCH_LIST_TYPE, DFSCH_LONG_SLOT_TYPE, DFSCH_MACRO_TYPE, dfsch_make_primitive(), dfsch_make_string_cstr(), DFSCH_META_TYPE, DFSCH_MUTABLE_PAIR_TYPE, dfsch_new_frame(), DFSCH_OBJECT_SLOT_TYPE, DFSCH_PAIR_TYPE, DFSCH_PRIMITIVE_TYPE, DFSCH_SIZE_T_SLOT_TYPE, DFSCH_SLOT_TYPE, DFSCH_SLOT_TYPE_TYPE, DFSCH_SPECIAL_TYPE, DFSCH_STANDARD_FUNCTION_TYPE, DFSCH_STRING_SLOT_TYPE, DFSCH_SYMBOL_TYPE, DFSCH_VECTOR_TYPE, HOST_TRIPLET, native_top_level_environment(), and PACKAGE_VERSION.
Referenced by debug_main(), DFSCH_DEFINE_PRIMITIVE(), and main().
{
  dfsch_object_t* ctx;
  ctx = dfsch_new_frame(NULL);
  dfsch_define_cstr(ctx, "<standard-type>", DFSCH_STANDARD_TYPE);
  dfsch_define_cstr(ctx, "<abstract-type>", DFSCH_ABSTRACT_TYPE);
  dfsch_define_cstr(ctx, "<meta-type>", DFSCH_META_TYPE);
  dfsch_define_cstr(ctx, "<special-type>", DFSCH_SPECIAL_TYPE);
  dfsch_define_cstr(ctx, "<standard-function>", DFSCH_STANDARD_FUNCTION_TYPE);
  dfsch_define_cstr(ctx, "<slot-type>", DFSCH_SLOT_TYPE_TYPE);
  dfsch_define_cstr(ctx, "<slot>", DFSCH_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<object-slot>", DFSCH_OBJECT_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<boolean-slot>", DFSCH_BOOLEAN_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<string-slot>", DFSCH_STRING_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<size_t-slot>", DFSCH_SIZE_T_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<int-slot>", DFSCH_INT_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<long-slot>", DFSCH_LONG_SLOT_TYPE);
  dfsch_define_cstr(ctx, "<list>", DFSCH_LIST_TYPE);
  dfsch_define_cstr(ctx, "<pair>", DFSCH_PAIR_TYPE);
  dfsch_define_cstr(ctx, "<mutable-pair>", DFSCH_MUTABLE_PAIR_TYPE);
  dfsch_define_cstr(ctx, "<immutable-pair>", DFSCH_IMMUTABLE_PAIR_TYPE);
  dfsch_define_cstr(ctx, "<empty-list>", DFSCH_EMPTY_LIST_TYPE);
  dfsch_define_cstr(ctx, "<symbol>", DFSCH_SYMBOL_TYPE);
  dfsch_define_cstr(ctx, "<primitive>", DFSCH_PRIMITIVE_TYPE);
  dfsch_define_cstr(ctx, "<function>", DFSCH_FUNCTION_TYPE);
  dfsch_define_cstr(ctx, "<macro>", DFSCH_MACRO_TYPE);
  dfsch_define_cstr(ctx, "<form>", DFSCH_FORM_TYPE);
  dfsch_define_cstr(ctx, "<vector>", DFSCH_VECTOR_TYPE);
  dfsch_define_cstr(ctx, "<environment>", DFSCH_ENVIRONMENT_TYPE);
  dfsch_define_cstr(ctx, "top-level-environment",
                    dfsch_make_primitive(&native_top_level_environment, ctx));
  dfsch_define_cstr(ctx, "current-environment",
                    DFSCH_FORM_REF(current_environment));
  dfsch_define_cstr(ctx,"*dfsch-version*",dfsch_make_string_cstr(PACKAGE_VERSION));
  dfsch_define_cstr(ctx,"*dfsch-platform*",dfsch_make_string_cstr(HOST_TRIPLET));
  dfsch__native_register(ctx);
  return ctx;
}
dfsch_object_t* dfsch_make_form (dfsch_form_impl_t impl, void * baton, char * name)
Wraps procedure for use as special form.
Definition at line 1918 of file dfsch.c.
References dfsch_form_t::baton, dfsch_make_object(), FORM, dfsch_form_t::impl, and dfsch_form_t::name.
{
  dfsch_form_t *f = (dfsch_form_t*)dfsch_make_object(FORM);
  f->impl = impl;
  f->baton = baton;
  f->name = name;
  return (object_t*)f;
}
dfsch_object_t* dfsch_make_macro (dfsch_object_t * proc)
Wraps procedure for use as macro.
Definition at line 1908 of file dfsch.c.
References dfsch_make_object(), MACRO, and macro_t::proc.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  macro_t *m = (macro_t*)dfsch_make_object(MACRO);
  if (!m)
    return NULL;
  m->proc = proc;
  return (object_t*)m;
}
dfsch_object_t* dfsch_make_object (const dfsch_type_t * type)
Create object of given type.
Definition at line 71 of file dfsch.c.
References dfsch_make_object_var().
Referenced by dfsch_channel_create(), dfsch_cmdopts_make_parser(), dfsch_collections_make_priority_queue(), dfsch_condition_create(), dfsch_hash_make(), dfsch_make_class(), dfsch_make_condition(), dfsch_make_decoded_time(), dfsch_make_default_random_state(), dfsch_make_file_port(), dfsch_make_file_random_state(), dfsch_make_form(), dfsch_make_instance(), dfsch_make_macro(), dfsch_make_number_from_double(), dfsch_make_primitive_flags(), dfsch_make_promise(), dfsch_make_restart(), dfsch_make_string_nocopy(), dfsch_make_weak_key_hash(), dfsch_make_weak_vector(), dfsch_make_wrapper_type(), dfsch_make_writer_state(), dfsch_mutex_create(), dfsch_named_lambda(), dfsch_regex_compile(), dfsch_string_input_port(), dfsch_string_list_append(), dfsch_string_output_port(), dfsch_thread_create(), dfsch_thread_self(), dfsch_unix_make_stat_struct(), dfsch_unix_opendir(), dfsch_weak_vector_from_array(), dfsch_wrap(), dfsch_xml_make_parser(), frac_cons(), and spawn_port().
{
  return dfsch_make_object_var(type, 0);
}
dfsch_object_t* dfsch_make_primitive (dfsch_primitive_impl_t prim, void * baton)
Create native function object
Definition at line 1888 of file dfsch.c.
References dfsch_make_primitive_flags().
Referenced by debug_main(), dfsch__control_register(), dfsch__format_native_register(), dfsch__hash_native_register(), dfsch__native_cxr_register(), dfsch__port_native_register(), dfsch__promise_native_register(), dfsch__string_native_register(), dfsch__system_register(), dfsch__weak_native_register(), dfsch__wrapper_native_register(), dfsch_load_register(), dfsch_make_context(), dfsch_make_throw_proc(), dfsch_make_throw_proc_arg(), dfsch_module_inet_register(), dfsch_module_regex_register(), dfsch_module_threads_register(), dfsch_module_unix_register(), dfsch_port_unsafe_register(), load_scm(), and main().
{
  return dfsch_make_primitive_flags(prim, baton, 0);
}
dfsch_object_t* dfsch_make_primitive_flags (dfsch_primitive_impl_t prim, void * baton, int flags)
Create native function object
Definition at line 1892 of file dfsch.c.
References dfsch_primitive_t::baton, dfsch_make_object(), dfsch_primitive_t::flags, PRIMITIVE, and dfsch_primitive_t::proc.
Referenced by dfsch_make_primitive().
{
  primitive_t* p = (primitive_t*)dfsch_make_object(PRIMITIVE);
  if (!p)
    return NULL;
  p->proc = prim;
  p->baton = baton;
  p->flags = 0;
  return (object_t*)p;
}
dfsch_object_t* dfsch_make_symbol (char * symbol)
Makes symbol object from string.
Definition at line 1772 of file dfsch.c.
References dfsch_gensym(), DFSCH_TAG_ENCODE, gsh_check_init(), lookup_symbol(), and make_symbol().
Referenced by debug_main(), dfsch_assert_instance(), dfsch_assert_type(), dfsch_cerror(), dfsch_condition_field_cstr(), dfsch_condition_put_field_cstr(), dfsch_console_read_objects(), dfsch_console_read_objects_parser(), dfsch_define_cstr(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_env_get_cstr(), dfsch_find_slot(), dfsch_get_trace(), dfsch_lookup_cstr(), dfsch_parser_define_directive_cstr(), dfsch_set_cstr(), main(), make_symbol(), native_alist_2_hash(), native_make_hash(), and start_element_handler().
{
  symbol_t *s;
  if (!symbol){
    return dfsch_gensym();
  }
  pthread_mutex_lock(&symbol_lock);
  gsh_check_init();
  // This code is slow already, so this check does not matter (too much)
  s = lookup_symbol(symbol);
  pthread_mutex_unlock(&symbol_lock);
  if (!s)
    s = make_symbol(symbol);
  return DFSCH_TAG_ENCODE(s, 2);
}
dfsch_object_t* dfsch_make_vector (size_t length, dfsch_object_t * fill)
Create vector
Definition at line 2032 of file dfsch.c.
References vector_t::data, dfsch_make_object_var(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and regex_substrings().
{
  vector_t* v;
  size_t i;
  v = (vector_t*)dfsch_make_object_var(VECTOR,
                                       length * sizeof(dfsch_object_t*));
  v->length = length;
  for(i = 0; i<length; ++i){
    v->data[i] = fill;
  }
  return (object_t*)v;
}
dfsch_object_t* dfsch_member (dfsch_object_t * key, dfsch_object_t * alist)
Return first cell of list with car equal? to key
Definition at line 1399 of file dfsch.c.
References dfsch_equal_p(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=list;
  while (DFSCH_PAIR_P(i)){
    if (dfsch_equal_p(key, DFSCH_FAST_CAR(i))){
      return (object_t*)i;
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return NULL;
}
dfsch_object_t* dfsch_memq (dfsch_object_t * key, dfsch_object_t * alist)
Return first cell of list with car eq? to key
Definition at line 1439 of file dfsch.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=list;
  while (DFSCH_PAIR_P(i)){
    if (key == DFSCH_FAST_CAR(i)){
      return (object_t*)i;
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return NULL;
}
dfsch_object_t* dfsch_memv (dfsch_object_t * key, dfsch_object_t * alist)
Return first cell of list with car eqv? to key
Definition at line 1419 of file dfsch.c.
References dfsch_eqv_p(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* i;
  i=list;
  while (DFSCH_PAIR_P(i)){
    if (dfsch_eqv_p(key, DFSCH_FAST_CAR(i))){
      return (object_t*)i;
    }
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return NULL;
}
dfsch_object_t* dfsch_named_lambda (dfsch_object_t * env, dfsch_object_t * args, dfsch_object_t * code, dfsch_object_t * name)
Create new named lambda closure.
Definition at line 1857 of file dfsch.c.
References closure_t::args, closure_t::code, DFSCH_ASSERT_TYPE, dfsch_compile_lambda_list(), DFSCH_ENVIRONMENT_TYPE, DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_object(), DFSCH_PAIR_P, DFSCH_STANDARD_FUNCTION_TYPE, dfsch_string_p(), closure_t::documentation, closure_t::env, closure_t::name, and closure_t::orig_code.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_lambda().
{
  closure_t *c = (closure_t*)dfsch_make_object(DFSCH_STANDARD_FUNCTION_TYPE);
  c->env = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  c->args = (lambda_list_t*)dfsch_compile_lambda_list(args);
  c->orig_code = code;
  if (DFSCH_PAIR_P(code) && dfsch_string_p(DFSCH_FAST_CAR(code))){
    c->code = DFSCH_FAST_CDR(code);
    c->documentation = DFSCH_FAST_CAR(code);
  } else {
    c->code = code;
    c->documentation = NULL;
  }
  c->name = name;
  return (object_t*)c;
}
dfsch_object_t* dfsch_new_frame (dfsch_object_t * parent)
Create new environment frame.
Definition at line 2221 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, and new_frame_impl().
Referenced by debug_main(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_destructuring_bind(), and dfsch_make_context().
{
  if (parent){
    parent = DFSCH_ASSERT_TYPE(parent, DFSCH_ENVIRONMENT_TYPE);
  }
  return (dfsch_object_t*)new_frame_impl((environment_t*)parent,
                                         dfsch__get_thread_info());
}
dfsch_object_t* dfsch_new_frame_from_hash (dfsch_object_t * parent, dfsch_object_t * hash)
Create new environment frame from given hash table
dfsch_object_t* dfsch_nil ()
Returns empty list, equivalent to NULL
Definition at line 872 of file dfsch.c.
{
  return NULL;
}
int dfsch_null_p (dfsch_object_t * obj)
Is OBJ null?
Definition at line 834 of file dfsch.c.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return !obj;
}
int dfsch_number_p (dfsch_object_t * obj)
Is OBJ a a number?
Definition at line 445 of file number.c.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_eqv_p(), and dfsch_number_to_string().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_NUMBER_TYPE);
}
char* dfsch_object_2_string (dfsch_object_t * obj, int max_depth, int readable)
Definition at line 2130 of file dfsch.c.
References dfsch_make_writer_state(), DFSCH_PRINT, DFSCH_WRITE, dfsch_write_object(), sl_append, sl_create, and sl_value.
Referenced by command_exit(), command_print(), command_write(), debug_main(), DFSCH_DEFINE_PRIMITIVE(), dfsch_format(), dfsch_format_trace(), dfsch_number_to_string(), dfsch_print_trace_buffer(), dfsch_signal(), dfsch_type_error(), format_a(), format_s(), format_w(), format_y(), main(), native_display(), native_write(), prettyprint_condition_fields(), and repl_callback().
{
  str_list_t* sl = sl_create();
  dfsch_writer_state_t* state = dfsch_make_writer_state(max_depth,
                                                        readable?
                                                        DFSCH_WRITE:
                                                        DFSCH_PRINT,
                                                        sl_append,
                                                        sl);
  dfsch_write_object(state, obj);
  return sl_value(sl);
}
dfsch_type_t* dfsch_object_as_type (dfsch_object_t * obj)
Definition at line 162 of file dfsch.c.
References DFSCH_ASSERT_INSTANCE, and DFSCH_STANDARD_TYPE.
Referenced by dfsch_superclass().
{
  return (dfsch_type_t*)DFSCH_ASSERT_INSTANCE(obj, DFSCH_STANDARD_TYPE);
}
int dfsch_pair_p (dfsch_object_t * obj)
Is OBJ a pair?
Definition at line 837 of file dfsch.c.
References DFSCH_PAIR_P.
Referenced by command_print(), command_write(), dfsch_alist_2_hash(), DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_2_string_utf8(), dfsch_load(), dfsch_parser_parse_object(), dfsch_quasiquote(), directive_import(), and process_directive().
{
  return DFSCH_PAIR_P(obj);
}
int dfsch_primitive_p (dfsch_object_t * obj)
Is OBJ a primitive (native) function?
Definition at line 849 of file dfsch.c.
References DFSCH_TYPE_OF, and PRIMITIVE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_TYPE_OF(obj) == PRIMITIVE;
}
int dfsch_procedure_p (dfsch_object_t * obj)
Is OBJ an applicable procedure?
Definition at line 856 of file dfsch.c.
References DFSCH_TYPE_OF, FUNCTION, and PRIMITIVE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return (DFSCH_TYPE_OF(obj) == PRIMITIVE || DFSCH_TYPE_OF(obj) == FUNCTION) ||
    (DFSCH_TYPE_OF(obj)->apply);
}
dfsch_object_t* dfsch_quasiquote (dfsch_object_t * env, dfsch_object_t * arg)
Expand quasi-quoted expression
Definition at line 2769 of file dfsch.c.
References dfsch_append(), dfsch_car(), dfsch_cdr(), dfsch_cons(), dfsch_eval(), dfsch_list(), dfsch_pair_p(), dfsch_quasiquote(), DFSCH_SYM_UNQUOTE, and DFSCH_SYM_UNQUOTE_SPLICING.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_quasiquote().
{
  if (dfsch_pair_p(arg)){
    object_t* car = dfsch_car(arg);
    object_t* cdr = dfsch_cdr(arg);
    if (car == DFSCH_SYM_UNQUOTE && dfsch_pair_p(cdr)){
      return dfsch_eval(dfsch_car(cdr), env);
    }else if (dfsch_pair_p(car)){
      if (dfsch_car(car) == DFSCH_SYM_UNQUOTE_SPLICING){
        return dfsch_append(dfsch_list(2,
                                       dfsch_eval(dfsch_car(dfsch_cdr(car)),
                                                  env),
                                       dfsch_quasiquote(env, cdr)));
      }
    }
    return dfsch_cons(dfsch_quasiquote(env,car), dfsch_quasiquote(env,cdr));
  }else{
    return arg;
  }
}
dfsch_object_t* dfsch_reverse (dfsch_object_t * list)
Reverses list
Definition at line 1382 of file dfsch.c.
References dfsch_cons(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_LIST_TYPE, DFSCH_PAIR_P, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  object_t *head;
  dfsch_object_t *i =  list;
  head = NULL;
  while(DFSCH_PAIR_P(i)){
    head = dfsch_cons(DFSCH_FAST_CAR(i), head);
    i = DFSCH_FAST_CDR(i);
  }
  if (i){
    dfsch_type_error(i, DFSCH_LIST_TYPE, 1);
  }
  return (object_t*)head;
}
dfsch_object_t* dfsch_set (dfsch_object_t * name, dfsch_object_t * value, dfsch_object_t * env)
Set value of variable name in environment env to value.
Definition at line 2291 of file dfsch.c.
References dfsch__get_thread_info(), DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_set_if_exists(), dfsch_error(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, environment_t::owner, environment_t::parent, and environment_t::values.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_set_cstr().
{
  environment_t *i;
  dfsch__thread_info_t *ti = dfsch__get_thread_info();
  i = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  while (i){
    if (i->owner != ti){
      i->owner = NULL;
      goto lock;
    }
    if(dfsch_eqhash_set_if_exists(&i->values, name, value, NULL))
      return value;
    i = i->parent;
  }
  dfsch_error("Unbound variable",name);
 lock:
  DFSCH_RWLOCK_WRLOCK(&environment_rwlock);
  while (i){
    if(dfsch_eqhash_set_if_exists(&i->values, name, value, NULL)){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return value;
    }
    i->owner = NULL;
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  dfsch_error("Unbound variable",name);
}
dfsch_object_t* dfsch_set_car (dfsch_object_t * pair, dfsch_object_t * c)
Set first (car) item of pair
Definition at line 945 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_FAST_CAR, and DFSCH_MUTABLE_PAIR_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* p = DFSCH_ASSERT_TYPE(pair, DFSCH_MUTABLE_PAIR_TYPE);
  DFSCH_FAST_CAR(p) = car;
  return p;
}
dfsch_object_t* dfsch_set_cdr (dfsch_object_t * pair, dfsch_object_t * c)
Set second (cdr) item of pair
Definition at line 953 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_FAST_CDR_MUT, and DFSCH_MUTABLE_PAIR_TYPE.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), dfsch_http_query_2_alist(), dfsch_http_split_path(), dfsch_parser_parse_object(), load_callback(), and read_callback().
{
  dfsch_object_t* p = DFSCH_ASSERT_TYPE(pair, DFSCH_MUTABLE_PAIR_TYPE);
  DFSCH_FAST_CDR_MUT(p) = cdr;
  return p;
}
dfsch_object_t* dfsch_set_cstr (dfsch_object_t * env, char * name, dfsch_object_t * obj)
Change value of variable.
Definition at line 2857 of file dfsch.c.
References dfsch_make_symbol(), and dfsch_set().
Referenced by dfsch_load_extend_path().
{
  return dfsch_set(dfsch_make_symbol(name),
                   obj,
                   ctx);
}
dfsch_object_t* dfsch_slot_ref (dfsch_object_t * obj, dfsch_slot_t * slot, int debug)
Definition at line 360 of file dfsch.c.
References dfsch_slot_t::access, dfsch_error(), DFSCH_SLOT_ACCESS_DEBUG_READ, dfsch_slot_t::offset, dfsch_slot_type_t::ref, and dfsch_slot_t::type.
Referenced by dfsch_slot_ref_by_name().
{
  if (!debug && slot->access == DFSCH_SLOT_ACCESS_DEBUG_READ) {
    dfsch_error("Slot not accesible", (dfsch_object_t*)slot);
  }
  return slot->type->ref(((char*) obj)+slot->offset);
}
dfsch_object_t* dfsch_slot_ref_by_name (dfsch_object_t * obj, char * slot, int debug)
Definition at line 379 of file dfsch.c.
References dfsch_find_slot(), dfsch_slot_ref(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_slot_ref(obj, dfsch_find_slot(DFSCH_TYPE_OF(obj),
                                             slot),
                        debug);
}
void dfsch_slot_set (dfsch_object_t * obj, dfsch_slot_t * slot, dfsch_object_t * value, int debug)
Definition at line 369 of file dfsch.c.
References dfsch_slot_t::access, dfsch_error(), DFSCH_SLOT_ACCESS_RW, dfsch_slot_t::offset, dfsch_slot_type_t::set, and dfsch_slot_t::type.
Referenced by dfsch_slot_set_by_name().
{
  if (!debug && slot->access != DFSCH_SLOT_ACCESS_RW) {
    dfsch_error("Slot not accesible", (dfsch_object_t*)slot);
  }
  slot->type->set(((char*) obj)+slot->offset, value);
}
void dfsch_slot_set_by_name (dfsch_object_t * obj, char * slot, dfsch_object_t * value, int debug)
Definition at line 386 of file dfsch.c.
References dfsch_find_slot(), dfsch_slot_set(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_slot_set(obj, dfsch_find_slot(DFSCH_TYPE_OF(obj),
                                      slot),
                 value,
                 debug);
}
dfsch_object_t* dfsch_string_2_object (char * str)
Parse string into object.
Definition at line 2182 of file dfsch.c.
References dfsch_car(), dfsch_error(), and dfsch_string_2_object_list().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  object_t* list = dfsch_string_2_object_list(str);
  if (!list) {
    dfsch_error("Input empty", NULL);
  }
  return dfsch_car(list);
}
dfsch_object_t* dfsch_string_2_object_list (char * str)
Parse string into list of objects
Definition at line 2163 of file dfsch.c.
References dfsch_error(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_feed(), dfsch_parser_get_level(), DFSCH_PARSER_STOPPED, read_ctx_t::head, parser, read_callback(), and read_ctx_t::tail.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_string_2_object(), and main().
{
  dfsch_parser_ctx_t *parser = dfsch_parser_create();
  read_ctx_t ctx;
  int err;
  dfsch_parser_callback(parser, read_callback, &ctx);
  ctx.head = ctx.tail = NULL;
  err = dfsch_parser_feed(parser, str);
  if (!err)
    dfsch_parser_feed(parser, " ");
  if ((err && err != DFSCH_PARSER_STOPPED)
      || dfsch_parser_get_level(parser)!=0){
    dfsch_error("Syntax error",NULL);
  }
  return ctx.head;
}
dfsch_object_t* dfsch_superclass (dfsch_object_t * obj)
Get superclass of given type
Definition at line 166 of file dfsch.c.
References dfsch_object_as_type(), and dfsch_type_t::superclass.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return (dfsch_object_t*)dfsch_object_as_type(obj)->superclass;
}
int dfsch_superclass_p (dfsch_type_t * sub, dfsch_type_t * super)
Definition at line 170 of file dfsch.c.
References dfsch_type_t::superclass.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_instance_p(), and dfsch_make_condition().
{
  if (sub == super)
    return 1;
  while (sub){
    sub = sub->superclass;
    if (sub==super){
      return 1;
    }
  }
  return 0;
}
char* dfsch_symbol (dfsch_object_t * symbol)
Returns string representation of given symbol.
Definition at line 1795 of file dfsch.c.
References DFSCH_ASSERT_TYPE, DFSCH_TAG_REF, and SYMBOL.
Referenced by dfsch_compare_symbol(), DFSCH_DEFINE_PRIMITIVE(), dfsch_parser_import_symbol(), dfsch_string_or_symbol_to_cstr(), dfsch_symbol_2_typename(), emit_attrs(), emit_object(), and make_slots().
{
  return ((symbol_t*)DFSCH_TAG_REF(DFSCH_ASSERT_TYPE(symbol, SYMBOL)))->data;
}
char* dfsch_symbol_2_typename (dfsch_object_t * symbol)
Definition at line 1799 of file dfsch.c.
References dfsch_symbol(), strancat, and strancpy.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  char *name;
  char *flt;
  name = dfsch_symbol(symbol);
  if (name[strlen(name)-1] == '>'){
    flt = strchr(name, '<');
    if (flt){
      if (flt == name){
        return strancpy(name+1, strlen(name) - 2);
      } else {
        return strancat(name, flt - name, flt+1, strlen(flt+1)-1);
      }
    }
  }
  return name;
}
int dfsch_symbol_p (dfsch_object_t * obj)
Is OBJ a symbol?
Definition at line 846 of file dfsch.c.
References DFSCH_TYPE_OF, and SYMBOL.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_string_or_symbol_to_cstr().
{
  return DFSCH_TYPE_OF(obj) == SYMBOL;
}
void dfsch_throw (dfsch_object_t * tag, dfsch_object_t * value)
Definition at line 1993 of file dfsch.c.
References dfsch__thread_info_t::catch_list, dfsch__continue_unwind(), dfsch__get_thread_info(), dfsch_error(), dfsch__catch_list_t::next, dfsch__catch_list_t::tag, dfsch__thread_info_t::throw_tag, and dfsch__thread_info_t::throw_value.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_xml_parse_buf(), dfsch_xml_parse_file(), dfsch_xml_parse_port(), throw_proc(), and throw_proc_arg().
{
  dfsch__thread_info_t *ti = dfsch__get_thread_info();
  dfsch__catch_list_t* i = ti->catch_list;
  while (i){
    if (i->tag == tag){
      ti->throw_tag = tag;
      ti->throw_value = value;
      dfsch__continue_unwind(ti);
    }
    i = i->next;
  }
  dfsch_error("Invalid catch tag", tag);
}
dfsch_type_t* dfsch_type_of (dfsch_object_t * obj)
Get object type
Definition at line 158 of file dfsch.c.
References DFSCH_TYPE_OF.
{
  return DFSCH_TYPE_OF(obj);
}
void dfsch_unset (dfsch_object_t * name, dfsch_object_t * env)
Unset variable name in environment env
Definition at line 2324 of file dfsch.c.
References environment_t::decls, DFSCH_ASSERT_TYPE, DFSCH_ENVIRONMENT_TYPE, dfsch_eqhash_unset(), dfsch_error(), dfsch_hash_unset(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, environment_t::parent, and environment_t::values.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
{
  environment_t *i;
  i = DFSCH_ASSERT_TYPE(env, DFSCH_ENVIRONMENT_TYPE);
  DFSCH_RWLOCK_WRLOCK(&environment_rwlock);
  while (i){
    if (i->decls){
      dfsch_hash_unset(i->decls, name);
    }
    if(dfsch_eqhash_unset(&i->values, name)){
      DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
      return;
    }
    i = i->parent;
  }
  DFSCH_RWLOCK_UNLOCK(&environment_rwlock);
  dfsch_error("Unbound variable",name);
}
dfsch_object_t* dfsch_vector (size_t count, ...)
Construct vector from arguments.
Definition at line 2046 of file dfsch.c.
References vector_t::data, dfsch_make_object_var(), vector_t::length, and VECTOR.
Referenced by dfsch_get_trace(), native_gettimeofday(), and regex_substrings().
{
  size_t i;
  vector_t* v =
    (vector_t*)dfsch_make_object_var(VECTOR, count * sizeof(dfsch_object_t*));
  va_list al;
  va_start(al,count);
  v->length = count;
  for(i = 0; i < count; ++i){
    v->data[i] = va_arg(al, dfsch_object_t*);
  }
  va_end(al);
  return (object_t*)v;
}
dfsch_object_t* dfsch_vector_2_list (dfsch_object_t * vector)
Converts vector to list.
Definition at line 2112 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, dfsch_list_from_array(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  return dfsch_list_from_array(v->data, v->length);
}
dfsch_object_t** dfsch_vector_as_array (dfsch_object_t * vector, size_t * length)
Returns pointer to internal object array of vector
Definition at line 2069 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, vector_t::length, and VECTOR.
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  if (length){
    *length = v->length;
  }
  return v->data;
}
dfsch_object_t* dfsch_vector_from_array (dfsch_object_t ** array, size_t length)
Creates vector from C array
Definition at line 2079 of file dfsch.c.
References vector_t::data, dfsch_make_object_var(), vector_t::length, and VECTOR.
{
  vector_t* v =
    (vector_t*)dfsch_make_object_var(VECTOR,
                                     sizeof(dfsch_object_t*) * length);
  v->length = length;
  memcpy(v->data, array, sizeof(object_t*) * length);
  return (object_t*)v;
}
size_t dfsch_vector_length (dfsch_object_t * vector)
Returns length of given vector.
Definition at line 2065 of file dfsch.c.
References DFSCH_ASSERT_TYPE, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return ((vector_t*)DFSCH_ASSERT_TYPE(vector, VECTOR))->length;
}
int dfsch_vector_p (dfsch_object_t * obj)
Is OBJ a vector?
Definition at line 867 of file dfsch.c.
References DFSCH_TYPE_OF, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_format_trace().
{
  return DFSCH_TYPE_OF(obj) == VECTOR;
}
dfsch_object_t* dfsch_vector_ref (dfsch_object_t * vector, size_t k)
Returns contents of k-th slot of vector.
Definition at line 2091 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, dfsch_error(), dfsch_make_number_from_long(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_format_trace().
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  if (v->length <= k)
    dfsch_error("Invalid index",dfsch_make_number_from_long(k));
  return v->data[k];
}
dfsch_object_t* dfsch_vector_set (dfsch_object_t * vector, size_t k, dfsch_object_t * obj)
Sets value of k-th slot of vector to obj.
Definition at line 2100 of file dfsch.c.
References vector_t::data, DFSCH_ASSERT_TYPE, dfsch_error(), dfsch_make_number_from_long(), vector_t::length, and VECTOR.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and regex_substrings().
{
  vector_t* v = DFSCH_ASSERT_TYPE(vector, VECTOR);
  if (v->length <= k)
    dfsch_error("Invalid index",dfsch_make_number_from_long(k));
  v->data[k] = obj;
  return vector;
}
dfsch_object_t* dfsch_zip (dfsch_object_t * llist)
Definition at line 1226 of file dfsch.c.
References dfsch_cons(), dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_FAST_CDR_MUT, dfsch_list_as_array(), DFSCH_PAIR_P, DFSCH_PAIR_TYPE, and dfsch_type_error().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  size_t len;
  object_t** args = dfsch_list_as_array(llist, &len);
  dfsch_object_t* shead;
  dfsch_object_t* stail;
  dfsch_object_t *head = NULL;
  dfsch_object_t *tail;
  dfsch_object_t* tmp;
  size_t i;
  if (len == 0){
    return NULL;
  }
  while(1){
    shead = NULL;
    for (i = 0; i<len; i++){
      if (!args[i]){
        if (i != 0){
          dfsch_error("Not a list of same length lists", llist);
        }
        goto out;
      }
      if (!DFSCH_PAIR_P(args[i])){
        dfsch_type_error(args[i], DFSCH_PAIR_TYPE, 0);
      }
      tmp = dfsch_cons(DFSCH_FAST_CAR(args[i]), NULL);
      if (shead){
        DFSCH_FAST_CDR_MUT(stail) = tmp;
      } else {
        shead = tmp;
      }
      stail = tmp;
      args[i] = DFSCH_FAST_CDR(args[i]);
    }
    tmp = dfsch_cons(shead, NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
    } else {
      head = tmp;
    }
    tail = tmp;
  }
 out:
  for (i = 0; i<len; i++){
    if (args[i]){
      dfsch_error("Not a list of same length lists", llist);
    }
  }
  return head;
}