dfsch: dfsch/eqhash.h File Reference
dfsch/eqhash.h File Reference
#include <dfsch/dfsch.h>
Data Structures
struct dfsch__eqhash_large_t
struct dfsch__eqhash_small_t
struct dfsch_eqhash_entry_t
struct dfsch_eqhash_t
Defines
#define DFSCH_EQHASH_CACHE_SIZE 8
#define DFSCH_EQHASH_LARGE 1
#define DFSCH_EQHASH_SMALL_SIZE 4
Typedefs
typedef struct dfsch_eqhash_entry_t dfsch_eqhash_entry_t
Functions
dfsch_object_t * dfsch_eqhash_2_alist (dfsch_eqhash_t *hash)
void dfsch_eqhash_init (dfsch_eqhash_t *hash, int start_large)
void dfsch_eqhash_put (dfsch_eqhash_t *hash, dfsch_object_t *key, dfsch_object_t *value)
dfsch_object_t * dfsch_eqhash_ref (dfsch_eqhash_t *hash, dfsch_object_t *key)
int dfsch_eqhash_ref_ex (dfsch_eqhash_t *hash, dfsch_object_t *key, dfsch_object_t **value, short *flags, dfsch_eqhash_entry_t **entry)
void dfsch_eqhash_set (dfsch_eqhash_t *hash, dfsch_object_t *key, dfsch_object_t *value)
void dfsch_eqhash_set_flags (dfsch_eqhash_t *hash, dfsch_object_t *key, long flags)
int dfsch_eqhash_set_if_exists (dfsch_eqhash_t *hash, dfsch_object_t *key, dfsch_object_t *value, short *flags)
int dfsch_eqhash_unset (dfsch_eqhash_t *hash, dfsch_object_t *key)
Define Documentation
#define DFSCH_EQHASH_CACHE_SIZE 8
Definition at line 28 of file eqhash.h.
Referenced by delete_entry(), and find_entry().
#define DFSCH_EQHASH_LARGE 1
Definition at line 30 of file eqhash.h.
#define DFSCH_EQHASH_SMALL_SIZE 4
Definition at line 27 of file eqhash.h.
Referenced by convert_to_large(), dfsch_eqhash_2_alist(), dfsch_eqhash_init(), dfsch_eqhash_put(), dfsch_eqhash_ref(), dfsch_eqhash_ref_ex(), dfsch_eqhash_set(), dfsch_eqhash_set_flags(), dfsch_eqhash_set_if_exists(), and dfsch_eqhash_unset().
Typedef Documentation
typedef struct dfsch_eqhash_entry_t dfsch_eqhash_entry_t
Definition at line 32 of file eqhash.h.
Function Documentation
dfsch_object_t* dfsch_eqhash_2_alist (dfsch_eqhash_t * hash)
Definition at line 320 of file eqhash.c.
References dfsch_eqhash_t::contents, dfsch_cons(), DFSCH_EQHASH_SMALL_SIZE, DFSCH_INVALID_OBJECT, dfsch_list(), dfsch_eqhash_t::is_large, dfsch_eqhash_entry_t::key, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::large, dfsch__eqhash_large_t::mask, dfsch_eqhash_entry_t::next, dfsch_eqhash_t::small, dfsch_eqhash_entry_t::value, dfsch__eqhash_small_t::values, and dfsch__eqhash_large_t::vector.
Referenced by dfsch_get_environment_variables().
{
  dfsch_object_t* result = NULL;
  int i;
  if (hash->is_large){
    for (i = 0; i <= hash->contents.large.mask; i++){
      dfsch_eqhash_entry_t* e = hash->contents.large.vector[i];
      while (e){
        result = dfsch_cons(dfsch_list(2, e->key, e->value), result);
        e = e->next;
      }
    }
  } else {
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] != DFSCH_INVALID_OBJECT){
        result = dfsch_cons(dfsch_list(2,
                                       hash->contents.small.keys[i],
                                       hash->contents.small.values[i]),
                            result);
      }
    }
  }
  return result;
}
void dfsch_eqhash_init (dfsch_eqhash_t * hash, int start_large)
Definition at line 43 of file eqhash.c.
References alloc_vector(), dfsch__eqhash_large_t::cache, dfsch_eqhash_t::contents, dfsch__eqhash_large_t::count, DFSCH_EQHASH_SMALL_SIZE, DFSCH_INVALID_OBJECT, dfsch__eqhash_small_t::flags, INITIAL_MASK, dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::large, dfsch__eqhash_large_t::mask, dfsch_eqhash_t::small, dfsch__eqhash_small_t::values, and dfsch__eqhash_large_t::vector.
Referenced by new_frame_impl().
{
  int i;
  if (start_large){
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE * 2; i++){
      hash->contents.large.cache[i] = NULL;
    }
    hash->contents.large.mask = INITIAL_MASK;
    hash->contents.large.count = 0;
    hash->contents.large.vector = alloc_vector(INITIAL_MASK);
  } else {
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      hash->contents.small.keys[i] = DFSCH_INVALID_OBJECT;
      hash->contents.small.values[i] = NULL;
      hash->contents.small.flags[i] = 0;
    }
  }
  hash->is_large = start_large;
}
void dfsch_eqhash_put (dfsch_eqhash_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Definition at line 125 of file eqhash.c.
References alloc_entry(), BUCKET, dfsch_eqhash_t::contents, convert_to_large(), dfsch__eqhash_large_t::count, DFSCH_EQHASH_SMALL_SIZE, DFSCH_INVALID_OBJECT, DFSCH_LIKELY, DFSCH_UNLIKELY, fast_ptr_hash(), grow_hash(), dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::large, dfsch__eqhash_large_t::mask, dfsch_eqhash_t::small, and dfsch__eqhash_small_t::values.
Referenced by destructure_impl(), destructuring_eval(), and dfsch_eqhash_set().
{
  if (DFSCH_LIKELY(!hash->is_large)){
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == DFSCH_INVALID_OBJECT){
        hash->contents.small.keys[i] = key;
        hash->contents.small.values[i] = value;
        return;
      }
    }
    convert_to_large(hash);
  }
  size_t h = fast_ptr_hash(key);
  hash->contents.large.count++;
  if (DFSCH_UNLIKELY(hash->contents.large.count / 2
                     > hash->contents.large.mask)){
    grow_hash(hash);
  }
  BUCKET(hash, h) = alloc_entry(key, value, 0, BUCKET(hash,h));
}
dfsch_object_t* dfsch_eqhash_ref (dfsch_eqhash_t * hash, dfsch_object_t * key)
Definition at line 269 of file eqhash.c.
References dfsch_eqhash_t::contents, DFSCH_EQHASH_SMALL_SIZE, DFSCH_INVALID_OBJECT, DFSCH_UNLIKELY, find_entry(), dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::small, dfsch_eqhash_entry_t::value, and dfsch__eqhash_small_t::values.
Referenced by dfsch_env_get(), and lookup_impl().
{
  if (DFSCH_UNLIKELY(hash->is_large)){
    dfsch_eqhash_entry_t* e = find_entry(hash, key);
    if (e) {
      return e->value;
    }
  } else {
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == key){
        return hash->contents.small.values[i];
      }
    }
  }
  return DFSCH_INVALID_OBJECT;
}
int dfsch_eqhash_ref_ex (dfsch_eqhash_t * hash, dfsch_object_t * key, dfsch_object_t ** value, short * flags, dfsch_eqhash_entry_t ** entry)
Definition at line 286 of file eqhash.c.
References dfsch_eqhash_t::contents, DFSCH_EQHASH_SMALL_SIZE, find_entry(), dfsch__eqhash_small_t::flags, dfsch_eqhash_entry_t::flags, dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::small, dfsch_eqhash_entry_t::value, and dfsch__eqhash_small_t::values.
{
  if (hash->is_large){
    dfsch_eqhash_entry_t* e = find_entry(hash, key);
    if (e) {
      if (value){
        *value = e->value;
      }
      if (flags){
        *flags = e->flags;
      }
      if (entry){
        *entry = e;
      }
      return 1;
    }
  } else {
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == key){
        if (value) {
          *value = hash->contents.small.values[i];
        }
        if (flags) {
          *flags = hash->contents.small.flags[i];
        }
        return 1;
      }
    }
  }
  return 0;
}
void dfsch_eqhash_set (dfsch_eqhash_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Definition at line 197 of file eqhash.c.
References dfsch_eqhash_t::contents, dfsch_eqhash_put(), DFSCH_EQHASH_SMALL_SIZE, find_entry(), dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::small, dfsch_eqhash_entry_t::value, and dfsch__eqhash_small_t::values.
Referenced by dfsch_define().
{
  if (hash->is_large){
    dfsch_eqhash_entry_t* e = find_entry(hash, key);
    if (e) {
      e->value = value;
      return;
    }
  } else {
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == key){
        hash->contents.small.values[i] = value;
        return;
      }
    }
  }
  dfsch_eqhash_put(hash, key, value);
}
void dfsch_eqhash_set_flags (dfsch_eqhash_t * hash, dfsch_object_t * key, long flags)
Definition at line 216 of file eqhash.c.
References dfsch_eqhash_t::contents, DFSCH_EQHASH_SMALL_SIZE, find_entry(), dfsch__eqhash_small_t::flags, dfsch_eqhash_entry_t::flags, dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, and dfsch_eqhash_t::small.
{
  if (hash->is_large){
    dfsch_eqhash_entry_t* e = find_entry(hash, key);
    if (e) {
      e->flags = flags;
      return;
    }
  } else {
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == key){
        hash->contents.small.flags[i] = flags;
        return;
      }
    }
  }
}
int dfsch_eqhash_set_if_exists (dfsch_eqhash_t * hash, dfsch_object_t * key, dfsch_object_t * value, short * flags)
Definition at line 234 of file eqhash.c.
References dfsch_eqhash_t::contents, DFSCH_EQHASH_SMALL_SIZE, find_entry(), dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, dfsch_eqhash_t::small, dfsch_eqhash_entry_t::value, and dfsch__eqhash_small_t::values.
Referenced by dfsch_set().
{
  if (hash->is_large){
    dfsch_eqhash_entry_t* e = find_entry(hash, key);
    if (e) {
      e->value = value;
      return 1;
    }
  } else {
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == key){
        hash->contents.small.values[i] = value;
        return 1;
      }
    }
  }
  return 0;
}
int dfsch_eqhash_unset (dfsch_eqhash_t * hash, dfsch_object_t * key)
Definition at line 254 of file eqhash.c.
References dfsch_eqhash_t::contents, delete_entry(), DFSCH_EQHASH_SMALL_SIZE, DFSCH_INVALID_OBJECT, dfsch_eqhash_t::is_large, dfsch__eqhash_small_t::keys, and dfsch_eqhash_t::small.
Referenced by dfsch_unset().
{
  if (hash->is_large){
    return delete_entry(hash, key);
  } else {
    int i;
    for (i = 0; i < DFSCH_EQHASH_SMALL_SIZE; i++){
      if (hash->contents.small.keys[i] == key){
        hash->contents.small.keys[i] = DFSCH_INVALID_OBJECT;
        return 1;
      }
    }
  }
  return 0;
}