dfsch: dfsch/lib/extref.h File Reference
dfsch/lib/extref.h File Reference
#include <dfsch/dfsch.h>
#include <time.h>
Defines
#define DFSCH_EXTREF_FROMNOW 0
#define DFSCH_EXTREF_ONCEONLY 1
#define DFSCH_EXTREF_REFRESH 2
Functions
char * dfsch_extref_create (dfsch_object_t *object, time_t timeout, int mode)
dfsch_object_t * dfsch_extref_ref (char *ref)
dfsch_object_t * dfsch_module_extref_register (dfsch_object_t *env)
Define Documentation
#define DFSCH_EXTREF_FROMNOW 0
Definition at line 28 of file extref.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_EXTREF_ONCEONLY 1
Definition at line 29 of file extref.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_extref_ref().
#define DFSCH_EXTREF_REFRESH 2
Definition at line 30 of file extref.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_extref_ref().
Function Documentation
char* dfsch_extref_create (dfsch_object_t * object, time_t timeout, int mode)
Definition at line 363 of file extref.c.
References create_uniq_id(), encode_uniqid(), extref_put(), extref_t::mode, extref_t::object, extref_t::timeout, extref_t::uniqid, and extref_t::valid_to.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  extref_t* er = GC_MALLOC(sizeof(extref_t));
  create_uniq_id(er->uniqid);
  er->timeout = timeout;
  er->mode = mode;
  er->valid_to = time(NULL) + timeout;
  er->object = object;
  extref_put(er);
  return encode_uniqid(er->uniqid);
}
dfsch_object_t* dfsch_extref_ref (char * ref)
Definition at line 375 of file extref.c.
References decode_uniqid(), dfsch_error(), DFSCH_EXTREF_ONCEONLY, DFSCH_EXTREF_REFRESH, dfsch_make_string_cstr(), extref_get(), extref_t::mode, extref_t::object, extref_t::timeout, and extref_t::valid_to.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  extref_t* er;
  uint32_t uniq_id[3];
  if (!decode_uniqid(uniq_id, ref)){
    dfsch_error("extref:invalid-handle", dfsch_make_string_cstr(ref));
  }
  er = extref_get(uniq_id);
  if (!er){
    dfsch_error("extref:expired-handle", dfsch_make_string_cstr(ref));
  }
  switch(er->mode){
  case DFSCH_EXTREF_REFRESH:
    er->valid_to = er->timeout + time(NULL);
    break;
  case DFSCH_EXTREF_ONCEONLY:
    er->valid_to = 0;
    break;
  }
  return er->object;
}
dfsch_object_t* dfsch_module_extref_register (dfsch_object_t * env)
Definition at line 59 of file extref_mod.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "extref");
  dfsch_define_cstr(env, "extref:make", DFSCH_PRIMITIVE_REF(extref_make));
  dfsch_define_cstr(env, "extref:ref", DFSCH_PRIMITIVE_REF(extref_ref));
  return env;
}