dfsch: lib/extref_mod.c File Reference
lib/extref_mod.c File Reference
#include "dfsch/lib/extref.h"
#include <dfsch/number.h>
#include <pthread.h>
#include <stdint.h>
#include <gc/gc.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <string.h>
Functions
DFSCH_DEFINE_PRIMITIVE (extref_ref, 0)
DFSCH_DEFINE_PRIMITIVE (extref_make, 0)
dfsch_object_t * dfsch_module_extref_register (dfsch_object_t *env)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (extref_ref , 0)
Definition at line 50 of file extref_mod.c.
References DFSCH_ARG_END, dfsch_extref_ref(), and DFSCH_STRING_ARG.
{
  char* handle;
  DFSCH_STRING_ARG(args, handle);
  DFSCH_ARG_END(args);
  return dfsch_extref_ref(handle);
}
DFSCH_DEFINE_PRIMITIVE (extref_make , 0)
Definition at line 33 of file extref_mod.c.
References DFSCH_ARG_END, dfsch_extref_create(), DFSCH_EXTREF_FROMNOW, DFSCH_EXTREF_ONCEONLY, DFSCH_EXTREF_REFRESH, DFSCH_FLAG_PARSER_BEGIN_ONE_OPT, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_VALUE, DFSCH_LONG_ARG_OPT, dfsch_make_string_cstr(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* object;
  time_t timeout;
  int mode = DFSCH_EXTREF_FROMNOW;
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_LONG_ARG_OPT(args, timeout, 600);
  DFSCH_FLAG_PARSER_BEGIN_ONE_OPT(args, mode);
  DFSCH_FLAG_VALUE("fromnow", DFSCH_EXTREF_FROMNOW, mode);
  DFSCH_FLAG_VALUE("refresh", DFSCH_EXTREF_REFRESH, mode);
  DFSCH_FLAG_VALUE("onceonly", DFSCH_EXTREF_ONCEONLY, mode);
  DFSCH_FLAG_PARSER_END(args);
  DFSCH_ARG_END(args);
  return dfsch_make_string_cstr(dfsch_extref_create(object, timeout, mode));
}
dfsch_object_t* dfsch_module_extref_register (dfsch_object_t * env)
Definition at line 59 of file extref_mod.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "extref");
  dfsch_define_cstr(env, "extref:make", DFSCH_PRIMITIVE_REF(extref_make));
  dfsch_define_cstr(env, "extref:ref", DFSCH_PRIMITIVE_REF(extref_ref));
  return env;
}