dfsch: dfsch/format.h File Reference
dfsch/format.h File Reference
#include <dfsch/dfsch.h>
Functions
char * dfsch_format (char *string, dfsch_object_t *args)
Function Documentation
char* dfsch_format (char * string, dfsch_object_t * args)
Definition at line 195 of file format.c.
References ARG_MAX, format_stack_t::args, dfsch_char_encode(), dfsch_error(), dfsch_format(), DFSCH_MAKE_FIXNUM, dfsch_number_format(), dfsch_number_to_long(), dfsch_number_to_string(), dfsch_object_2_string(), dfsch_saprintf(), dfsch_string_to_cstr(), FLAG_AT, FLAG_COLON, format_a(), format_push(), format_r(), format_s(), format_w(), format_y(), list_backskip(), list_get(), list_seek(), list_skip(), make_format_list(), read_num_arg(), sl_append, sl_create, sl_nappend, and sl_value.
Referenced by dfsch_format(), and native_format().
{
  int argc;
  int argv[ARG_MAX];
  int neg;
  size_t l;
  str_list_t* out = sl_create();
  int flags;
  format_stack_t* state = format_push(NULL,
                                      string, '\0', make_format_list(args));
  while (*string){
    if (*string == '~'){
      string++;
      flags = 0;
      argc = 0;
      if (!*string){
        dfsch_error("Incomplete format directive", NULL);
      }
      if (strchr("0123456789'\",", *string)){
        argc = 1;
        while(1) {
          switch (*string){
          case '0':
          case '1':
          case '2':
          case '3':
          case '4':
          case '5':
          case '6':
          case '7':
          case '8':
          case '9':
          case '-':
          case '+':
            argv[argc-1] = read_num_arg(&string);
            break;
          case ',':
            argv[argc-1] = -1;
            string++;
            break;
          default:
            argv[argc-1] = 0;
            string++;
            break;
          }
          if (*string == ','){
            argc++;
            if (argc == ARG_MAX){
              dfsch_error("Too many arguments to format directive",
                          NULL);
            }
            string++;
            continue;
          } else {
            break;
          }
        }
      }
    flags:
      if (!*string){
        dfsch_error("Incomplete format directive", NULL);
      }
      if (*string == ':'){
        flags |= FLAG_COLON;
        string++;
        goto flags;
      }
      if (*string == '@'){
        flags |= FLAG_AT;
        string++;
        goto flags;
      }
      /* End of arguments and flags */
      switch(*string){
      case '\0':
        dfsch_error("Incomplete format directive", NULL);
      case 'a':
      case 'A':
        sl_append(out, format_a(flags, argc, argv, list_get(state->args)));
        break;
      case 's':
      case 'S':
        sl_append(out, format_s(flags, argc, argv, list_get(state->args)));
        break;
      case 'w':
      case 'W':
        sl_append(out, format_w(flags, argc, argv, list_get(state->args)));
        break;
      case 'y':
      case 'Y':
        sl_append(out, format_y(flags, argc, argv, list_get(state->args)));
        break;
      case 'r':
      case 'R':
        sl_append(out, format_r(flags, argc, argv, list_get(state->args)));
        break;
      case 'd':
      case 'D':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 10));
        break;
      case 'x':
      case 'X':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 16));
        break;
      case 'o':
      case 'O':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 8));
        break;
      case 'b':
      case 'B':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 2));
        break;
      case 'c':
      case 'C':
        sl_append(out,
                  dfsch_char_encode(dfsch_number_to_long(list_get(state->args))));
        break;
      case 'f':
      case 'F':
        switch (argc){
        case 1:
          sl_append(out,
                    dfsch_saprintf("%*s", argv[0],
                                   dfsch_object_2_string(list_get(state->args),
                                                   1000, 1)));
          break;
        case 2:
          sl_append(out, dfsch_number_format(list_get(state->args),
                                             argv[0], argv[1]));
          break;
        default:
          dfsch_error("Wrong number of arguments to ~f",
                      DFSCH_MAKE_FIXNUM(argc));
        }
        break;
      case '?':
        {
          char* fmt = dfsch_string_to_cstr(list_get(state->args));
          sl_append(out, dfsch_format(fmt, list_get(state->args)));
        }
        break;
      case '*':
        if (argc == 0){
          argc = 1;
          if (flags == FLAG_AT){
            argv[0] = 0;
          } else {
            argv[0] = 1;
          }
        }
        switch (flags){
        case FLAG_COLON:
          list_backskip(state->args, argv[0]);
          break;
        case FLAG_AT:
          list_seek(state->args, argv[0]);
          break;
        default:
          list_skip(state->args, argv[0]);
        }
        break;
      case '~':
        sl_append(out, "~");
        break;
      case '%':
      case '&':
        sl_append(out, "\n");
        break;
      default:
        dfsch_error("Unknown format directive", NULL);
      }
      string++;
    } else {
      l = strcspn(string, "~");
      sl_nappend(out, string, l);
      string += l;
    }
  }
  return sl_value(out);
}