dfsch: src/format.c File Reference
src/format.c File Reference
#include "dfsch/format.h"
#include <dfsch/strings.h>
#include "util.h"
#include "internal.h"
#include <string.h>
Data Structures
struct format_list_t
struct format_stack_t
Defines
#define ARG_MAX 16
#define FLAG_AT 2
#define FLAG_COLON 1
Typedefs
typedef struct format_stack_t format_stack_t
Functions
void dfsch__format_native_register (dfsch_object_t *ctx)
char * dfsch_format (char *string, dfsch_object_t *args)
static char * format_a (int flags, int argc, int *argv, dfsch_object_t *obj)
static format_stack_t * format_push (format_stack_t *prev, char *start, char type, format_list_t *args)
static char * format_r (int flags, int argc, int *argv, dfsch_object_t *obj)
static char * format_s (int flags, int argc, int *argv, dfsch_object_t *obj)
static char * format_w (int flags, int argc, int *argv, dfsch_object_t *obj)
static char * format_y (int flags, int argc, int *argv, dfsch_object_t *obj)
static void list_backskip (format_list_t *l, size_t count)
static dfsch_object_t * list_get (format_list_t *l)
static dfsch_object_t * list_peek (format_list_t *l)
static void list_seek (format_list_t *l, size_t count)
static void list_skip (format_list_t *l, size_t count)
static format_list_t * make_format_list (dfsch_object_t *list)
static dfsch_object_t * native_format (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static int read_num_arg (char **string)
Define Documentation
#define ARG_MAX 16
Definition at line 72 of file format.c.
Referenced by dfsch_format().
#define FLAG_AT 2
Definition at line 32 of file format.c.
Referenced by dfsch_format().
#define FLAG_COLON 1
Definition at line 31 of file format.c.
Referenced by dfsch_format().
Typedef Documentation
typedef struct format_stack_t format_stack_t
Definition at line 173 of file format.c.
Function Documentation
void dfsch__format_native_register (dfsch_object_t * ctx)
Definition at line 399 of file format.c.
References dfsch_define_cstr(), dfsch_make_primitive(), and native_format().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "format",
                    dfsch_make_primitive(&native_format,NULL));
}
char* dfsch_format (char * string, dfsch_object_t * args)
Definition at line 195 of file format.c.
References ARG_MAX, format_stack_t::args, dfsch_char_encode(), dfsch_error(), dfsch_format(), DFSCH_MAKE_FIXNUM, dfsch_number_format(), dfsch_number_to_long(), dfsch_number_to_string(), dfsch_object_2_string(), dfsch_saprintf(), dfsch_string_to_cstr(), FLAG_AT, FLAG_COLON, format_a(), format_push(), format_r(), format_s(), format_w(), format_y(), list_backskip(), list_get(), list_seek(), list_skip(), make_format_list(), read_num_arg(), sl_append, sl_create, sl_nappend, and sl_value.
Referenced by dfsch_format(), and native_format().
{
  int argc;
  int argv[ARG_MAX];
  int neg;
  size_t l;
  str_list_t* out = sl_create();
  int flags;
  format_stack_t* state = format_push(NULL,
                                      string, '\0', make_format_list(args));
  while (*string){
    if (*string == '~'){
      string++;
      flags = 0;
      argc = 0;
      if (!*string){
        dfsch_error("Incomplete format directive", NULL);
      }
      if (strchr("0123456789'\",", *string)){
        argc = 1;
        while(1) {
          switch (*string){
          case '0':
          case '1':
          case '2':
          case '3':
          case '4':
          case '5':
          case '6':
          case '7':
          case '8':
          case '9':
          case '-':
          case '+':
            argv[argc-1] = read_num_arg(&string);
            break;
          case ',':
            argv[argc-1] = -1;
            string++;
            break;
          default:
            argv[argc-1] = 0;
            string++;
            break;
          }
          if (*string == ','){
            argc++;
            if (argc == ARG_MAX){
              dfsch_error("Too many arguments to format directive",
                          NULL);
            }
            string++;
            continue;
          } else {
            break;
          }
        }
      }
    flags:
      if (!*string){
        dfsch_error("Incomplete format directive", NULL);
      }
      if (*string == ':'){
        flags |= FLAG_COLON;
        string++;
        goto flags;
      }
      if (*string == '@'){
        flags |= FLAG_AT;
        string++;
        goto flags;
      }
      /* End of arguments and flags */
      switch(*string){
      case '\0':
        dfsch_error("Incomplete format directive", NULL);
      case 'a':
      case 'A':
        sl_append(out, format_a(flags, argc, argv, list_get(state->args)));
        break;
      case 's':
      case 'S':
        sl_append(out, format_s(flags, argc, argv, list_get(state->args)));
        break;
      case 'w':
      case 'W':
        sl_append(out, format_w(flags, argc, argv, list_get(state->args)));
        break;
      case 'y':
      case 'Y':
        sl_append(out, format_y(flags, argc, argv, list_get(state->args)));
        break;
      case 'r':
      case 'R':
        sl_append(out, format_r(flags, argc, argv, list_get(state->args)));
        break;
      case 'd':
      case 'D':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 10));
        break;
      case 'x':
      case 'X':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 16));
        break;
      case 'o':
      case 'O':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 8));
        break;
      case 'b':
      case 'B':
        sl_append(out, dfsch_number_to_string(list_get(state->args), 2));
        break;
      case 'c':
      case 'C':
        sl_append(out,
                  dfsch_char_encode(dfsch_number_to_long(list_get(state->args))));
        break;
      case 'f':
      case 'F':
        switch (argc){
        case 1:
          sl_append(out,
                    dfsch_saprintf("%*s", argv[0],
                                   dfsch_object_2_string(list_get(state->args),
                                                   1000, 1)));
          break;
        case 2:
          sl_append(out, dfsch_number_format(list_get(state->args),
                                             argv[0], argv[1]));
          break;
        default:
          dfsch_error("Wrong number of arguments to ~f",
                      DFSCH_MAKE_FIXNUM(argc));
        }
        break;
      case '?':
        {
          char* fmt = dfsch_string_to_cstr(list_get(state->args));
          sl_append(out, dfsch_format(fmt, list_get(state->args)));
        }
        break;
      case '*':
        if (argc == 0){
          argc = 1;
          if (flags == FLAG_AT){
            argv[0] = 0;
          } else {
            argv[0] = 1;
          }
        }
        switch (flags){
        case FLAG_COLON:
          list_backskip(state->args, argv[0]);
          break;
        case FLAG_AT:
          list_seek(state->args, argv[0]);
          break;
        default:
          list_skip(state->args, argv[0]);
        }
        break;
      case '~':
        sl_append(out, "~");
        break;
      case '%':
      case '&':
        sl_append(out, "\n");
        break;
      default:
        dfsch_error("Unknown format directive", NULL);
      }
      string++;
    } else {
      l = strcspn(string, "~");
      sl_nappend(out, string, l);
      string += l;
    }
  }
  return sl_value(out);
}
static char* format_a (int flags, int argc, int * argv, dfsch_object_t * obj) [static]
Definition at line 74 of file format.c.
References dfsch_object_2_string().
Referenced by dfsch_format().
{
  if (argc == 0){
    return dfsch_object_2_string(obj, 1000, 0);
  } else {
    return dfsch_object_2_string(obj, argv[0], 0);
  }
}
static format_stack_t* format_push (format_stack_t * prev, char * start, char type, format_list_t * args) [static]
Definition at line 182 of file format.c.
References format_stack_t::args, format_stack_t::next, format_stack_t::start, and format_stack_t::type.
Referenced by dfsch_format().
{
  format_stack_t* state = GC_NEW(format_stack_t);
  state->next = prev;
  state->start = start;
  state->type = type;
  state->args = args;
  return state;
}
static char* format_r (int flags, int argc, int * argv, dfsch_object_t * obj) [static]
Definition at line 98 of file format.c.
References dfsch_number_to_string().
Referenced by dfsch_format().
{
  if (argc == 0){
    return dfsch_number_to_string(obj, 10);
  } else {
    return dfsch_number_to_string(obj, argv[0]);
  }
}
static char* format_s (int flags, int argc, int * argv, dfsch_object_t * obj) [static]
Definition at line 81 of file format.c.
References dfsch_object_2_string().
Referenced by dfsch_format().
{
  if (argc == 0){
    return dfsch_object_2_string(obj, 1000, 1);
  } else {
    return dfsch_object_2_string(obj, argv[0], 1);
  }
}
static char* format_w (int flags, int argc, int * argv, dfsch_object_t * obj) [static]
Definition at line 88 of file format.c.
References dfsch_object_2_string().
Referenced by dfsch_format().
{
  return dfsch_object_2_string(obj, 1000, 1);
}
static char* format_y (int flags, int argc, int * argv, dfsch_object_t * obj) [static]
Definition at line 91 of file format.c.
References dfsch_object_2_string().
Referenced by dfsch_format().
{
  if (argc == 0){
    return dfsch_object_2_string(obj, 1000, 1);
  } else {
    return dfsch_object_2_string(obj, argv[0], 1);
  }
}
static void list_backskip (format_list_t * l, size_t count) [static]
Definition at line 169 of file format.c.
References format_list_t::cur_pos, and list_seek().
Referenced by dfsch_format().
{
  list_seek(l, l->cur_pos - count);
}
static dfsch_object_t* list_get (format_list_t * l) [static]
Definition at line 122 of file format.c.
References format_list_t::cur, format_list_t::cur_pos, dfsch_car(), dfsch_cdr(), and dfsch_error().
Referenced by dfsch_format().
{
  dfsch_object_t* ret;
  if (!l->cur){
    dfsch_error("No more arguments", NULL);
  }
  ret = dfsch_car(l->cur);
  l->cur = dfsch_cdr(l->cur);
  l->cur_pos++;
  return ret;
}
static dfsch_object_t* list_peek (format_list_t * l) [static]
Definition at line 135 of file format.c.
References format_list_t::cur, dfsch_car(), and dfsch_error().
{
  dfsch_object_t* ret;
  if (!l->cur){
    dfsch_error("No more arguments", NULL);
  }
  ret = dfsch_car(l->cur);
  return ret;
}
static void list_seek (format_list_t * l, size_t count) [static]
Definition at line 156 of file format.c.
References format_list_t::cur, format_list_t::cur_pos, dfsch_cdr(), dfsch_error(), and format_list_t::head.
Referenced by dfsch_format(), and list_backskip().
{
  l->cur = l->head;
  l->cur_pos = 0;
  while (l->cur){
    if (count == 0){
      return;
    }
    count--;
    l->cur = dfsch_cdr(l->cur);
    l->cur_pos++;
  }
  dfsch_error("No more arguments", NULL);
}
static void list_skip (format_list_t * l, size_t count) [static]
Definition at line 145 of file format.c.
References format_list_t::cur, format_list_t::cur_pos, dfsch_cdr(), and dfsch_error().
Referenced by dfsch_format().
{
  while (l->cur){
    if (count == 0){
      return;
    }
    count--;
    l->cur = dfsch_cdr(l->cur);
    l->cur_pos++;
  }
  dfsch_error("No more arguments", NULL);
}
static format_list_t* make_format_list (dfsch_object_t * list) [static]
Definition at line 112 of file format.c.
References format_list_t::cur, format_list_t::cur_pos, and format_list_t::head.
Referenced by dfsch_format().
{
  format_list_t* l = GC_NEW(format_list_t);
  l->cur_pos = 0;
  l->head = list;
  l->cur = list;
  return l;
}
static dfsch_object_t* native_format (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 390 of file format.c.
References dfsch_format(), dfsch_make_string_cstr(), and DFSCH_STRING_ARG.
Referenced by dfsch__format_native_register().
{
  char* format;
  DFSCH_STRING_ARG(args, format);
  return dfsch_make_string_cstr(dfsch_format(format, args));
}
static int read_num_arg (char ** string) [static]
Definition at line 34 of file format.c.
References dfsch_error().
Referenced by dfsch_format().
{
  int neg = 0;
  int res = 0;
  if (**string == '-'){
    neg = 1;
    (*string)++;
  }else if (**string == '+'){
    (*string)++;
  }
 next:
  switch(**string){
  case '\0':
    dfsch_error("Incomplete format directive", NULL);
  case '0':
  case '1':
  case '2':
  case '3':
  case '4':
  case '5':
  case '6':
  case '7':
  case '8':
  case '9':
    res *= 10;
    res += **string - '0';
    (*string)++;
    goto next;
  }
  if (neg){
    return -res;
  } else {
    return res;
  }
}