dfsch: lib/gcollect.c File Reference
lib/gcollect.c File Reference
#include "dfsch/lib/gcollect.h"
#include <dfsch/number.h>
#include <dfsch/load.h>
Functions
DFSCH_DEFINE_PRIMITIVE (disable, 0)
DFSCH_DEFINE_PRIMITIVE (enable, 0)
DFSCH_DEFINE_PRIMITIVE (count, 0)
DFSCH_DEFINE_PRIMITIVE (total_bytes, 0)
DFSCH_DEFINE_PRIMITIVE (bytes_since_gc, 0)
DFSCH_DEFINE_PRIMITIVE (free_bytes, 0)
DFSCH_DEFINE_PRIMITIVE (heap_size, 0)
DFSCH_DEFINE_PRIMITIVE (gcollect, 0)
dfsch_object_t * dfsch_module_gcollect_register (dfsch_object_t *env)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (disable , 0)
Definition at line 71 of file gcollect.c.
References DFSCH_ARG_END.
{
  DFSCH_ARG_END(args);
  GC_disable();
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (enable , 0)
Definition at line 66 of file gcollect.c.
References DFSCH_ARG_END.
{
  DFSCH_ARG_END(args);
  GC_enable();
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (count , 0)
Definition at line 60 of file gcollect.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(GC_gc_no);
}
DFSCH_DEFINE_PRIMITIVE (total_bytes , 0)
Definition at line 53 of file gcollect.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(GC_get_total_bytes());
}
DFSCH_DEFINE_PRIMITIVE (bytes_since_gc , 0)
Definition at line 47 of file gcollect.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(GC_get_bytes_since_gc());
}
DFSCH_DEFINE_PRIMITIVE (free_bytes , 0)
Definition at line 41 of file gcollect.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(GC_get_free_bytes());
}
DFSCH_DEFINE_PRIMITIVE (heap_size , 0)
Definition at line 35 of file gcollect.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(GC_get_heap_size());
}
DFSCH_DEFINE_PRIMITIVE (gcollect , 0)
Definition at line 27 of file gcollect.c.
References DFSCH_ARG_END.
{
  DFSCH_ARG_END(args);
  GC_gcollect();
  return NULL;
}
dfsch_object_t* dfsch_module_gcollect_register (dfsch_object_t * env)
Definition at line 77 of file gcollect.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "gcollect");
  dfsch_define_cstr(env, "gcollect:gcollect!",
                    DFSCH_PRIMITIVE_REF(gcollect));
  dfsch_define_cstr(env, "gcollect:heap-size",
                    DFSCH_PRIMITIVE_REF(heap_size));
  dfsch_define_cstr(env, "gcollect:free-bytes",
                    DFSCH_PRIMITIVE_REF(free_bytes));
  dfsch_define_cstr(env, "gcollect:bytes-since-gc",
                    DFSCH_PRIMITIVE_REF(bytes_since_gc));
  dfsch_define_cstr(env, "gcollect:total-bytes",
                    DFSCH_PRIMITIVE_REF(total_bytes));
  dfsch_define_cstr(env, "gcollect:count",
                    DFSCH_PRIMITIVE_REF(count));
  dfsch_define_cstr(env, "gcollect:enable!",
                    DFSCH_PRIMITIVE_REF(enable));
  dfsch_define_cstr(env, "gcollect:disable!",
                    DFSCH_PRIMITIVE_REF(disable));
  return NULL;
}