dfsch: src/hash.c File Reference
src/hash.c File Reference
#include <dfsch/hash.h>
#include "internal.h"
#include <stdlib.h>
#include "util.h"
#include <stdio.h>
Data Structures
struct hash_entry_t
struct hash_t
Defines
#define GET_HASH(obj, hash)
#define HASH(hash, key)
#define HASH_TYPE(hash) ((dfsch_custom_hash_type_t*)DFSCH_TYPE_OF(hash))
#define IMPLEMENTS(hash, feature)
#define INITIAL_MASK 0x07
Typedefs
typedef struct hash_entry_t hash_entry_t
Functions
static hash_entry_t * alloc_entry (size_t hash, dfsch_object_t *key, dfsch_object_t *value, hash_entry_t *next)
static hash_entry_t ** alloc_vector (size_t mask)
void dfsch__hash_native_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_alist_2_hash (dfsch_object_t *alist, int mode)
dfsch_object_t * dfsch_hash_2_alist (dfsch_object_t *hash_obj)
dfsch_object_t * dfsch_hash_make (int mode)
int dfsch_hash_p (dfsch_object_t *obj)
void dfsch_hash_put (dfsch_object_t *hash_obj, dfsch_object_t *key, dfsch_object_t *value)
dfsch_object_t * dfsch_hash_ref (dfsch_object_t *hash_obj, dfsch_object_t *key)
int dfsch_hash_ref_fast (dfsch_object_t *hash_obj, dfsch_object_t *key, dfsch_object_t **res)
void dfsch_hash_set (dfsch_object_t *hash_obj, dfsch_object_t *key, dfsch_object_t *value)
int dfsch_hash_set_if_exists (dfsch_object_t *hash_obj, dfsch_object_t *key, dfsch_object_t *value)
int dfsch_hash_unset (dfsch_object_t *hash_obj, dfsch_object_t *key)
static void hash_change_size (hash_t *hash, size_t new_mask)
static void hash_finalizer (hash_t *h, void *cd)
static dfsch_object_t * native_alist_2_hash (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_hash_2_alist (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_hash_p (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_hash_ref (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_hash_set (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_hash_set_if_exists (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_hash_unset (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_make_hash (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Variables
dfsch_type_t dfsch_custom_hash_type_type
dfsch_type_t dfsch_hash_basetype
dfsch_type_t dfsch_standard_hash_type
Define Documentation
#define GET_HASH (obj, hash)
Value:
if (DFSCH_TYPE_OF(obj) == DFSCH_STANDARD_HASH_TYPE){                  \
    hash = (hash_t*)obj;                                                \
  } else if (!obj ||                                                    \
             !DFSCH_INSTANCE_P(DFSCH_TYPE_OF(obj), DFSCH_CUSTOM_HASH_TYPE_TYPE)){ \
    dfsch_error("exception:not-a-hash", obj);                           \
  }else
Definition at line 122 of file hash.c.
Referenced by dfsch_hash_2_alist(), dfsch_hash_put(), dfsch_hash_ref_fast(), dfsch_hash_set(), dfsch_hash_set_if_exists(), and dfsch_hash_unset().
#define HASH (hash, key)
Value:
((hash)->equal?dfsch_hash((key))\
                         :((((size_t)key) >> 3)) ^ (((size_t)key) >> 15))
Definition at line 118 of file hash.c.
Referenced by dfsch_hash_put(), dfsch_hash_ref_fast(), dfsch_hash_set(), dfsch_hash_set_if_exists(), and dfsch_hash_unset().
#define HASH_TYPE (hash) ((dfsch_custom_hash_type_t*)DFSCH_TYPE_OF(hash))
Definition at line 130 of file hash.c.
Referenced by dfsch_hash_2_alist(), dfsch_hash_put(), dfsch_hash_ref_fast(), dfsch_hash_set(), dfsch_hash_set_if_exists(), and dfsch_hash_unset().
#define IMPLEMENTS (hash, feature)
Value:
if (!HASH_TYPE(hash)->feature){                                       \
    dfsch_error("exception:" #feature "-not-supported-by-this-hash-type", \
                hash);                                                  \
  }
Definition at line 132 of file hash.c.
Referenced by dfsch_hash_2_alist(), dfsch_hash_put(), dfsch_hash_ref_fast(), dfsch_hash_set(), dfsch_hash_set_if_exists(), and dfsch_hash_unset().
#define INITIAL_MASK 0x07
Definition at line 36 of file hash.c.
Typedef Documentation
typedef struct hash_entry_t hash_entry_t
Definition at line 38 of file hash.c.
Function Documentation
static hash_entry_t* alloc_entry (size_t hash, dfsch_object_t * key, dfsch_object_t * value, hash_entry_t * next) [static]
Definition at line 192 of file hash.c.
References hash_entry_t::hash, hash_entry_t::key, hash_entry_t::next, and hash_entry_t::value.
Referenced by dfsch_hash_put(), dfsch_hash_set(), and hash_change_size().
{
  hash_entry_t *e = GC_NEW(hash_entry_t);
  e->hash = hash;
  e->key = key;
  e->value = value;
  e->next = next;
  return e;
}
static hash_entry_t** alloc_vector (size_t mask) [static]
Definition at line 88 of file hash.c.
Referenced by dfsch_hash_make(), and hash_change_size().
{
  return GC_MALLOC((sizeof(hash_entry_t*))*(mask+1));
}
void dfsch__hash_native_register (dfsch_object_t * ctx)
Definition at line 544 of file hash.c.
References DFSCH_CUSTOM_HASH_TYPE_TYPE, dfsch_define_cstr(), dfsch_make_primitive(), DFSCH_STANDARD_HASH_TYPE, native_alist_2_hash(), native_hash_2_alist(), native_hash_p(), native_hash_ref(), native_hash_set(), native_hash_set_if_exists(), native_hash_unset(), and native_make_hash().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<hash>", DFSCH_HASH_BASETYPE);
  dfsch_define_cstr(ctx, "<standard-hash>", DFSCH_STANDARD_HASH_TYPE);
  dfsch_define_cstr(ctx, "<custom-hash-type>", DFSCH_CUSTOM_HASH_TYPE_TYPE);
  dfsch_define_cstr(ctx, "make-hash",
                    dfsch_make_primitive(&native_make_hash,NULL));
  dfsch_define_cstr(ctx, "hash?",
                    dfsch_make_primitive(&native_hash_p,NULL));
  dfsch_define_cstr(ctx, "hash-ref",
                    dfsch_make_primitive(&native_hash_ref,NULL));
  dfsch_define_cstr(ctx, "hash-unset!",
                    dfsch_make_primitive(&native_hash_unset,NULL));
  dfsch_define_cstr(ctx, "hash-set!",
                    dfsch_make_primitive(&native_hash_set,NULL));
  dfsch_define_cstr(ctx, "hash-set-if-exists!",
                    dfsch_make_primitive(&native_hash_set_if_exists,NULL));
  dfsch_define_cstr(ctx, "hash->alist",
                    dfsch_make_primitive(&native_hash_2_alist,NULL));
  dfsch_define_cstr(ctx, "alist->hash",
                    dfsch_make_primitive(&native_alist_2_hash,NULL));
}
dfsch_object_t* dfsch_alist_2_hash (dfsch_object_t * alist, int mode)
Convert list of associations to hash table.
Definition at line 416 of file hash.c.
References dfsch_car(), dfsch_cdr(), dfsch_hash_make(), dfsch_hash_set(), dfsch_list_item(), and dfsch_pair_p().
Referenced by native_alist_2_hash().
{
  dfsch_object_t* hash = dfsch_hash_make(mode);
  dfsch_object_t* i = alist;
  while (dfsch_pair_p(i)){
    dfsch_object_t* item = dfsch_car(i);
    dfsch_object_t* name = dfsch_list_item(item, 0);
    dfsch_object_t* value = dfsch_list_item(item, 1);
    dfsch_hash_set(hash, name, value);
    i = dfsch_cdr(i);
  }
  return hash;
}
dfsch_object_t* dfsch_hash_2_alist (dfsch_object_t * hash_obj)
Convert hash table to list of associations.
Definition at line 388 of file hash.c.
References dfsch_cons(), dfsch_list(), DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, GET_HASH, HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by native_hash_2_alist().
{
  dfsch_object_t *alist = NULL;
  int j;
  hash_entry_t *i;
  hash_t *hash;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, hash_2_alist);
    return HASH_TYPE(hash_obj)->hash_2_alist(hash_obj);
  }
  DFSCH_RWLOCK_RDLOCK(&hash->lock);
  for (j=0; j<(hash->mask+1); j++){
    i = hash->vector[j];
    while (i){
      alist = dfsch_cons(dfsch_list(2,
                                    i->key,
                                    i->value),
                         alist);
      i = i->next;
    }
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return alist;
}
dfsch_object_t* dfsch_hash_make (int mode)
Create new hash table object
Definition at line 98 of file hash.c.
References alloc_vector(), hash_t::count, DFSCH_HASH_EQ, DFSCH_INIT_RWLOCK, dfsch_make_object(), DFSCH_STANDARD_HASH_TYPE, hash_t::equal, hash_finalizer(), INITIAL_MASK, hash_t::lock, hash_t::mask, and hash_t::vector.
Referenced by dfsch_alist_2_hash(), dfsch_declare(), dfsch_http_query_2_hash(), dfsch_make_class(), and native_make_hash().
{
  hash_t *h = (hash_t*)dfsch_make_object(DFSCH_STANDARD_HASH_TYPE);
  h->count = 0;
  h->mask = INITIAL_MASK;
  h->vector = alloc_vector(h->mask);
  h->equal = mode != DFSCH_HASH_EQ;
  DFSCH_INIT_RWLOCK(&h->lock);
#ifdef DFSCH_THREADS_FINALIZE
  GC_REGISTER_FINALIZER_NO_ORDER(h, (GC_finalization_proc)hash_finalizer,
                                 NULL, NULL, NULL);
#endif
  return (dfsch_object_t*)h;
}
int dfsch_hash_p (dfsch_object_t * obj)
Check whenever given object is hashtable
Definition at line 112 of file hash.c.
References DFSCH_CUSTOM_HASH_TYPE_TYPE, DFSCH_INSTANCE_P, DFSCH_STANDARD_HASH_TYPE, and DFSCH_TYPE_OF.
Referenced by native_hash_p().
{
  return DFSCH_TYPE_OF(obj) == DFSCH_STANDARD_HASH_TYPE ||
    DFSCH_INSTANCE_P(DFSCH_TYPE_OF(obj), DFSCH_CUSTOM_HASH_TYPE_TYPE);
}
void dfsch_hash_put (dfsch_object_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Associate value with key
Definition at line 230 of file hash.c.
References alloc_entry(), hash_t::count, DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, GET_HASH, HASH, hash_change_size(), HASH_TYPE, IMPLEMENTS, hash_t::lock, hash_t::mask, and hash_t::vector.
{
  hash_t *hash;
  size_t h;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, set);
    HASH_TYPE(hash_obj)->set(hash_obj, key, value);
    return;
  };
  h = HASH(hash, key);
  DFSCH_RWLOCK_WRLOCK(&hash->lock);
  hash->count++;
  if (hash->count > (hash->mask+1)){ // Should table grow?
    hash_change_size(hash, ((hash->mask+1) * 2) - 1);
  }
  hash->vector[h & hash->mask] = alloc_entry(h,
                                             key,
                                             value,
                                             hash->vector[h & hash->mask]);
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
}
dfsch_object_t* dfsch_hash_ref (dfsch_object_t * hash, dfsch_object_t * key)
Get given entry in hashtable.
Return value is pair, whose CAR is value associated with key or empty list in case of non-existant key.
Definition at line 181 of file hash.c.
References dfsch_hash_ref_fast(), and dfsch_list().
Referenced by native_hash_ref().
{
  dfsch_object_t* res;
  if (dfsch_hash_ref_fast(hash_obj, key, &res)){
    return dfsch_list(1, res);
  } else {
    return NULL;
  }
}
int dfsch_hash_ref_fast (dfsch_object_t * hash_obj, dfsch_object_t * key, dfsch_object_t ** res)
Definition at line 139 of file hash.c.
References dfsch_equal_p(), DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by dfsch_declare(), dfsch_find_method(), and dfsch_hash_ref().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *i;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, ref);
    return HASH_TYPE(hash_obj)->ref(hash_obj, key, res);
  };
  DFSCH_RWLOCK_RDLOCK(&hash->lock);
  h = HASH(hash, key);
  i = hash->vector[h & hash->mask];
  if (hash->equal){
    while (i){
      if (h == i->hash && dfsch_equal_p(i->key, key)){
        *res = i->value;
        DFSCH_RWLOCK_UNLOCK(&hash->lock);
        return 1;
      }
      i = i->next;
    }
  } else {
    while (i){
      if (h == i->hash && i->key == key){
        *res = i->value;
        DFSCH_RWLOCK_UNLOCK(&hash->lock);
        return 1;
      }
      i = i->next;
    }
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return 0;
}
void dfsch_hash_set (dfsch_object_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Associate value with key
Definition at line 260 of file hash.c.
References alloc_entry(), hash_t::count, dfsch_equal_p(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, hash_change_size(), HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by dfsch_alist_2_hash(), dfsch_class_add_method(), dfsch_declare(), dfsch_find_method(), dfsch_http_query_2_hash(), and native_hash_set().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *entry;
  hash_entry_t *i;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, set);
    HASH_TYPE(hash_obj)->set(hash_obj, key, value);
    return;
  };
  h = HASH(hash, key);
  DFSCH_RWLOCK_WRLOCK(&hash->lock);
  i = entry = hash->vector[h & hash->mask];
  while (i){
    if (h == i->hash &&
        (hash->equal ? dfsch_equal_p(i->key, key) : i->key == key)){
      i->value = value;
      DFSCH_RWLOCK_UNLOCK(&hash->lock);
      return;
    }
    i = i->next;
  }
  // It isn't here, so we will add new item
  hash->count++;
  if (hash->count > (hash->mask+1)){ // Should table grow?
    hash_change_size(hash, ((hash->mask+1) * 2) - 1);
  }
  hash->vector[h & hash->mask] = alloc_entry(h,
                                             key,
                                             value,
                                             hash->vector[h & hash->mask]);
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
}
int dfsch_hash_set_if_exists (dfsch_object_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Set value associated with given key only when there is already such key.
Definition at line 352 of file hash.c.
References dfsch_equal_p(), DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by native_hash_set_if_exists().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *i;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, set_if_exists);
    return HASH_TYPE(hash_obj)->set_if_exists(hash_obj, key, value);
  }
  h = HASH(hash, key);
  DFSCH_RWLOCK_RDLOCK(&hash->lock);
  i = hash->vector[h & hash->mask];
  while (i){
    if (h == i->hash &&
        (hash->equal ? dfsch_equal_p(i->key, key) : i->key == key)){
      i->value = value;
      DFSCH_RWLOCK_UNLOCK(&hash->lock);
      return 1;
    }
    i = i->next;
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return 0;
}
int dfsch_hash_unset (dfsch_object_t * hash, dfsch_object_t * key)
Delete given key.
Definition at line 306 of file hash.c.
References hash_t::count, dfsch_equal_p(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, hash_change_size(), HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, and hash_t::vector.
Referenced by dfsch_class_remove_method(), dfsch_unset(), and native_hash_unset().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *i, *j;
  int k;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, unset);
    return HASH_TYPE(hash_obj)->unset(hash_obj, key);
  }
  h = HASH(hash, key);
  DFSCH_RWLOCK_WRLOCK(&hash->lock);
  i = hash->vector[h & hash->mask];
  j = NULL;
  while (i){
    if (h == i->hash &&
        (hash->equal ? dfsch_equal_p(i->key, key) : i->key == key)){
      if (j){
        j->next = i->next;
      } else {
        hash->vector[h & hash->mask] = NULL;
      }
      hash->count --;
      if (hash->count+16 < (hash->mask+1)/2
          && hash->mask != 0x3){ // Should table shrink?
        hash_change_size(hash, ((hash->mask+1) / 2) - 1);
      }
      DFSCH_RWLOCK_UNLOCK(&hash->lock);
      return 1;
    }
    j = i;
    i = i->next;
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return 0;
}
static void hash_change_size (hash_t * hash, size_t new_mask) [static]
Definition at line 204 of file hash.c.
References alloc_entry(), alloc_vector(), hash_entry_t::hash, hash_entry_t::key, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by dfsch_hash_put(), dfsch_hash_set(), and dfsch_hash_unset().
{
  int j;
  hash_entry_t *i;
  hash_entry_t **vector = alloc_vector(new_mask);
  for (j = 0; j <= hash->mask; j++){
    i = hash->vector[j];
    while (i){
      hash_entry_t *next = i->next;
      size_t h = i->hash;
      if (i->next != vector[h & new_mask]){
        vector[h & new_mask] = alloc_entry(h,
                                           i->key,
                                           i->value,
                                           vector[h & new_mask]);
      } else {
        vector[h & new_mask] = i;
      }
      i = next;
    }
  }
  hash->mask = new_mask;
  hash->vector = vector;
}
static void hash_finalizer (hash_t * h, void * cd) [static]
Definition at line 93 of file hash.c.
References DFSCH_DESTROY_RWLOCK, and hash_t::lock.
Referenced by dfsch_hash_make().
{
  DFSCH_DESTROY_RWLOCK(&h->lock);
}
static dfsch_object_t* native_alist_2_hash (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 522 of file hash.c.
References dfsch_alist_2_hash(), DFSCH_ARG_END, dfsch_error(), DFSCH_HASH_EQ, DFSCH_HASH_EQUAL, DFSCH_HASH_EQV, dfsch_make_symbol(), DFSCH_OBJECT_ARG, and DFSCH_OBJECT_ARG_OPT.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* alist;
  dfsch_object_t *mode;
  DFSCH_OBJECT_ARG(args, alist);
  DFSCH_OBJECT_ARG_OPT(args, mode, NULL);
  DFSCH_ARG_END(args);
  if (!mode)
    return dfsch_alist_2_hash(alist, DFSCH_HASH_EQ);
  if (mode == dfsch_make_symbol("equal?"))
    return dfsch_alist_2_hash(alist, DFSCH_HASH_EQUAL);
  if (mode == dfsch_make_symbol("eqv?"))
    return dfsch_alist_2_hash(alist, DFSCH_HASH_EQV);
  if (mode == dfsch_make_symbol("eq?"))
    return dfsch_alist_2_hash(alist, DFSCH_HASH_EQ);
  dfsch_error("exception:unknown-mode", mode);
}
static dfsch_object_t* native_hash_2_alist (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 512 of file hash.c.
References DFSCH_ARG_END, dfsch_hash_2_alist(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* hash;
  DFSCH_OBJECT_ARG(args, hash);
  DFSCH_ARG_END(args);
  return dfsch_hash_2_alist(hash);
}
static dfsch_object_t* native_hash_p (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 458 of file hash.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_hash_p(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_hash_p(obj));
}
static dfsch_object_t* native_hash_ref (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 466 of file hash.c.
References DFSCH_ARG_END, dfsch_hash_ref(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* hash;
  dfsch_object_t* key;
  DFSCH_OBJECT_ARG(args, hash);
  DFSCH_OBJECT_ARG(args, key);
  DFSCH_ARG_END(args);
  return dfsch_hash_ref(hash, key);
}
static dfsch_object_t* native_hash_set (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 486 of file hash.c.
References DFSCH_ARG_END, dfsch_hash_set(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* hash;
  dfsch_object_t* key;
  dfsch_object_t* value;
  DFSCH_OBJECT_ARG(args, hash);
  DFSCH_OBJECT_ARG(args, key);
  DFSCH_OBJECT_ARG(args, value);
  DFSCH_ARG_END(args);
  dfsch_hash_set(hash, key, value);
  return hash;
}
static dfsch_object_t* native_hash_set_if_exists (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 499 of file hash.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_hash_set_if_exists(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* hash;
  dfsch_object_t* key;
  dfsch_object_t* value;
  DFSCH_OBJECT_ARG(args, hash);
  DFSCH_OBJECT_ARG(args, key);
  DFSCH_OBJECT_ARG(args, value);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_hash_set_if_exists(hash, key, value));
}
static dfsch_object_t* native_hash_unset (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 476 of file hash.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_hash_unset(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t* hash;
  dfsch_object_t* key;
  DFSCH_OBJECT_ARG(args, hash);
  DFSCH_OBJECT_ARG(args, key);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_hash_unset(hash, key));
}
static dfsch_object_t* native_make_hash (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 441 of file hash.c.
References DFSCH_ARG_END, dfsch_error(), DFSCH_HASH_EQ, DFSCH_HASH_EQUAL, DFSCH_HASH_EQV, dfsch_hash_make(), dfsch_make_symbol(), and DFSCH_OBJECT_ARG_OPT.
Referenced by dfsch__hash_native_register().
{
  dfsch_object_t *mode;
  DFSCH_OBJECT_ARG_OPT(args, mode, NULL);
  DFSCH_ARG_END(args);
  if (!mode)
    return dfsch_hash_make(DFSCH_HASH_EQ);
  if (mode == dfsch_make_symbol("equal?"))
    return dfsch_hash_make(DFSCH_HASH_EQUAL);
  if (mode == dfsch_make_symbol("eqv?"))
    return dfsch_hash_make(DFSCH_HASH_EQV);
  if (mode == dfsch_make_symbol("eq?"))
    return dfsch_hash_make(DFSCH_HASH_EQ);
  dfsch_error("exception:unknown-mode", mode);
}
Variable Documentation
dfsch_type_t dfsch_custom_hash_type_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_custom_hash_type_t),
  "custom-hash-type",
  NULL,
  NULL,
  NULL
}
Definition at line 77 of file hash.c.
dfsch_type_t dfsch_hash_basetype
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "hash",
  NULL,
  NULL,
  NULL
}
Definition at line 57 of file hash.c.
dfsch_type_t dfsch_standard_hash_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  DFSCH_HASH_BASETYPE,
  sizeof(hash_t),
  "standard-hash",
  NULL,
  NULL,
  NULL
}
Definition at line 67 of file hash.c.