dfsch: dfsch/hash.h File Reference
dfsch/hash.h File Reference
#include <dfsch/dfsch.h>
Data Structures
struct dfsch_custom_hash_type_t
Defines
#define DFSCH_CUSTOM_HASH_TYPE_TYPE (&dfsch_custom_hash_type_type)
#define DFSCH_HASH_BASETYPE (&dfsch_hash_basetype)
#define DFSCH_HASH_EQ 0
#define DFSCH_HASH_EQUAL 2
#define DFSCH_HASH_EQV 1
#define DFSCH_STANDARD_HASH_TYPE (&dfsch_standard_hash_type)
Typedefs
typedef dfsch_object_t *(* dfsch_custom_hash_2_alist)(dfsch_object_t *hash)
typedef int(* dfsch_custom_hash_ref_t)(dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t **res)
typedef int(* dfsch_custom_hash_set_if_exists_t)(dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
typedef void(* dfsch_custom_hash_set_t)(dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
typedef int(* dfsch_custom_hash_unset_t)(dfsch_object_t *hash, dfsch_object_t *key)
Functions
dfsch_object_t * dfsch_alist_2_hash (dfsch_object_t *alist, int mode)
dfsch_object_t * dfsch_hash_2_alist (dfsch_object_t *hash_obj)
dfsch_object_t * dfsch_hash_make (int mode)
int dfsch_hash_p (dfsch_object_t *obj)
void dfsch_hash_put (dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
dfsch_object_t * dfsch_hash_ref (dfsch_object_t *hash, dfsch_object_t *key)
int dfsch_hash_ref_fast (dfsch_object_t *hash_obj, dfsch_object_t *key, dfsch_object_t **res)
void dfsch_hash_set (dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
int dfsch_hash_set_if_exists (dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
int dfsch_hash_unset (dfsch_object_t *hash, dfsch_object_t *key)
Variables
dfsch_type_t dfsch_custom_hash_type_type
dfsch_type_t dfsch_hash_basetype
dfsch_type_t dfsch_standard_hash_type
Detailed Description
Hash table datatype.
Definition in file hash.h.
Define Documentation
#define DFSCH_CUSTOM_HASH_TYPE_TYPE (&dfsch_custom_hash_type_type)
Definition at line 131 of file hash.h.
Referenced by dfsch__hash_native_register(), and dfsch_hash_p().
#define DFSCH_HASH_BASETYPE (&dfsch_hash_basetype)
Definition at line 127 of file hash.h.
#define DFSCH_HASH_EQ 0
Definition at line 37 of file hash.h.
Referenced by dfsch_declare(), dfsch_hash_make(), dfsch_make_class(), native_alist_2_hash(), and native_make_hash().
#define DFSCH_HASH_EQUAL 2
Definition at line 39 of file hash.h.
Referenced by dfsch_http_query_2_hash(), native_alist_2_hash(), and native_make_hash().
#define DFSCH_HASH_EQV 1
Definition at line 38 of file hash.h.
Referenced by native_alist_2_hash(), and native_make_hash().
#define DFSCH_STANDARD_HASH_TYPE (&dfsch_standard_hash_type)
Definition at line 129 of file hash.h.
Referenced by dfsch__hash_native_register(), dfsch_hash_make(), and dfsch_hash_p().
Typedef Documentation
typedef dfsch_object_t*(* dfsch_custom_hash_2_alist)(dfsch_object_t *hash)
Definition at line 114 of file hash.h.
typedef int(* dfsch_custom_hash_ref_t)(dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t **res)
Definition at line 103 of file hash.h.
typedef int(* dfsch_custom_hash_set_if_exists_t)(dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
Definition at line 111 of file hash.h.
typedef void(* dfsch_custom_hash_set_t)(dfsch_object_t *hash, dfsch_object_t *key, dfsch_object_t *value)
Definition at line 106 of file hash.h.
typedef int(* dfsch_custom_hash_unset_t)(dfsch_object_t *hash, dfsch_object_t *key)
Definition at line 109 of file hash.h.
Function Documentation
dfsch_object_t* dfsch_alist_2_hash (dfsch_object_t * alist, int mode)
Convert list of associations to hash table.
Definition at line 416 of file hash.c.
References dfsch_car(), dfsch_cdr(), dfsch_hash_make(), dfsch_hash_set(), dfsch_list_item(), and dfsch_pair_p().
Referenced by native_alist_2_hash().
{
  dfsch_object_t* hash = dfsch_hash_make(mode);
  dfsch_object_t* i = alist;
  while (dfsch_pair_p(i)){
    dfsch_object_t* item = dfsch_car(i);
    dfsch_object_t* name = dfsch_list_item(item, 0);
    dfsch_object_t* value = dfsch_list_item(item, 1);
    dfsch_hash_set(hash, name, value);
    i = dfsch_cdr(i);
  }
  return hash;
}
dfsch_object_t* dfsch_hash_2_alist (dfsch_object_t * hash_obj)
Convert hash table to list of associations.
Definition at line 388 of file hash.c.
References dfsch_cons(), dfsch_list(), DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, GET_HASH, HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by native_hash_2_alist().
{
  dfsch_object_t *alist = NULL;
  int j;
  hash_entry_t *i;
  hash_t *hash;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, hash_2_alist);
    return HASH_TYPE(hash_obj)->hash_2_alist(hash_obj);
  }
  DFSCH_RWLOCK_RDLOCK(&hash->lock);
  for (j=0; j<(hash->mask+1); j++){
    i = hash->vector[j];
    while (i){
      alist = dfsch_cons(dfsch_list(2,
                                    i->key,
                                    i->value),
                         alist);
      i = i->next;
    }
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return alist;
}
dfsch_object_t* dfsch_hash_make (int mode)
Create new hash table object
Definition at line 98 of file hash.c.
References alloc_vector(), hash_t::count, DFSCH_HASH_EQ, DFSCH_INIT_RWLOCK, dfsch_make_object(), DFSCH_STANDARD_HASH_TYPE, hash_t::equal, hash_finalizer(), INITIAL_MASK, hash_t::lock, hash_t::mask, and hash_t::vector.
Referenced by dfsch_alist_2_hash(), dfsch_declare(), dfsch_http_query_2_hash(), dfsch_make_class(), and native_make_hash().
{
  hash_t *h = (hash_t*)dfsch_make_object(DFSCH_STANDARD_HASH_TYPE);
  h->count = 0;
  h->mask = INITIAL_MASK;
  h->vector = alloc_vector(h->mask);
  h->equal = mode != DFSCH_HASH_EQ;
  DFSCH_INIT_RWLOCK(&h->lock);
#ifdef DFSCH_THREADS_FINALIZE
  GC_REGISTER_FINALIZER_NO_ORDER(h, (GC_finalization_proc)hash_finalizer,
                                 NULL, NULL, NULL);
#endif
  return (dfsch_object_t*)h;
}
int dfsch_hash_p (dfsch_object_t * obj)
Check whenever given object is hashtable
Definition at line 112 of file hash.c.
References DFSCH_CUSTOM_HASH_TYPE_TYPE, DFSCH_INSTANCE_P, DFSCH_STANDARD_HASH_TYPE, and DFSCH_TYPE_OF.
Referenced by native_hash_p().
{
  return DFSCH_TYPE_OF(obj) == DFSCH_STANDARD_HASH_TYPE ||
    DFSCH_INSTANCE_P(DFSCH_TYPE_OF(obj), DFSCH_CUSTOM_HASH_TYPE_TYPE);
}
void dfsch_hash_put (dfsch_object_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Associate value with key
Definition at line 230 of file hash.c.
References alloc_entry(), hash_t::count, DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, GET_HASH, HASH, hash_change_size(), HASH_TYPE, IMPLEMENTS, hash_t::lock, hash_t::mask, and hash_t::vector.
{
  hash_t *hash;
  size_t h;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, set);
    HASH_TYPE(hash_obj)->set(hash_obj, key, value);
    return;
  };
  h = HASH(hash, key);
  DFSCH_RWLOCK_WRLOCK(&hash->lock);
  hash->count++;
  if (hash->count > (hash->mask+1)){ // Should table grow?
    hash_change_size(hash, ((hash->mask+1) * 2) - 1);
  }
  hash->vector[h & hash->mask] = alloc_entry(h,
                                             key,
                                             value,
                                             hash->vector[h & hash->mask]);
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
}
dfsch_object_t* dfsch_hash_ref (dfsch_object_t * hash, dfsch_object_t * key)
Get given entry in hashtable.
Return value is pair, whose CAR is value associated with key or empty list in case of non-existant key.
Definition at line 181 of file hash.c.
References dfsch_hash_ref_fast(), and dfsch_list().
Referenced by native_hash_ref().
{
  dfsch_object_t* res;
  if (dfsch_hash_ref_fast(hash_obj, key, &res)){
    return dfsch_list(1, res);
  } else {
    return NULL;
  }
}
int dfsch_hash_ref_fast (dfsch_object_t * hash_obj, dfsch_object_t * key, dfsch_object_t ** res)
Definition at line 139 of file hash.c.
References dfsch_equal_p(), DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by dfsch_declare(), dfsch_find_method(), and dfsch_hash_ref().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *i;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, ref);
    return HASH_TYPE(hash_obj)->ref(hash_obj, key, res);
  };
  DFSCH_RWLOCK_RDLOCK(&hash->lock);
  h = HASH(hash, key);
  i = hash->vector[h & hash->mask];
  if (hash->equal){
    while (i){
      if (h == i->hash && dfsch_equal_p(i->key, key)){
        *res = i->value;
        DFSCH_RWLOCK_UNLOCK(&hash->lock);
        return 1;
      }
      i = i->next;
    }
  } else {
    while (i){
      if (h == i->hash && i->key == key){
        *res = i->value;
        DFSCH_RWLOCK_UNLOCK(&hash->lock);
        return 1;
      }
      i = i->next;
    }
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return 0;
}
void dfsch_hash_set (dfsch_object_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Associate value with key
Definition at line 260 of file hash.c.
References alloc_entry(), hash_t::count, dfsch_equal_p(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, hash_change_size(), HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by dfsch_alist_2_hash(), dfsch_class_add_method(), dfsch_declare(), dfsch_find_method(), dfsch_http_query_2_hash(), and native_hash_set().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *entry;
  hash_entry_t *i;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, set);
    HASH_TYPE(hash_obj)->set(hash_obj, key, value);
    return;
  };
  h = HASH(hash, key);
  DFSCH_RWLOCK_WRLOCK(&hash->lock);
  i = entry = hash->vector[h & hash->mask];
  while (i){
    if (h == i->hash &&
        (hash->equal ? dfsch_equal_p(i->key, key) : i->key == key)){
      i->value = value;
      DFSCH_RWLOCK_UNLOCK(&hash->lock);
      return;
    }
    i = i->next;
  }
  // It isn't here, so we will add new item
  hash->count++;
  if (hash->count > (hash->mask+1)){ // Should table grow?
    hash_change_size(hash, ((hash->mask+1) * 2) - 1);
  }
  hash->vector[h & hash->mask] = alloc_entry(h,
                                             key,
                                             value,
                                             hash->vector[h & hash->mask]);
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
}
int dfsch_hash_set_if_exists (dfsch_object_t * hash, dfsch_object_t * key, dfsch_object_t * value)
Set value associated with given key only when there is already such key.
Definition at line 352 of file hash.c.
References dfsch_equal_p(), DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, hash_entry_t::value, and hash_t::vector.
Referenced by native_hash_set_if_exists().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *i;
  int j;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, set_if_exists);
    return HASH_TYPE(hash_obj)->set_if_exists(hash_obj, key, value);
  }
  h = HASH(hash, key);
  DFSCH_RWLOCK_RDLOCK(&hash->lock);
  i = hash->vector[h & hash->mask];
  while (i){
    if (h == i->hash &&
        (hash->equal ? dfsch_equal_p(i->key, key) : i->key == key)){
      i->value = value;
      DFSCH_RWLOCK_UNLOCK(&hash->lock);
      return 1;
    }
    i = i->next;
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return 0;
}
int dfsch_hash_unset (dfsch_object_t * hash, dfsch_object_t * key)
Delete given key.
Definition at line 306 of file hash.c.
References hash_t::count, dfsch_equal_p(), DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, hash_t::equal, GET_HASH, hash_entry_t::hash, HASH, hash_change_size(), HASH_TYPE, IMPLEMENTS, hash_entry_t::key, hash_t::lock, hash_t::mask, hash_entry_t::next, and hash_t::vector.
Referenced by dfsch_class_remove_method(), dfsch_unset(), and native_hash_unset().
{
  size_t h;
  hash_t *hash;
  hash_entry_t *i, *j;
  int k;
  GET_HASH(hash_obj, hash){
    IMPLEMENTS(hash_obj, unset);
    return HASH_TYPE(hash_obj)->unset(hash_obj, key);
  }
  h = HASH(hash, key);
  DFSCH_RWLOCK_WRLOCK(&hash->lock);
  i = hash->vector[h & hash->mask];
  j = NULL;
  while (i){
    if (h == i->hash &&
        (hash->equal ? dfsch_equal_p(i->key, key) : i->key == key)){
      if (j){
        j->next = i->next;
      } else {
        hash->vector[h & hash->mask] = NULL;
      }
      hash->count --;
      if (hash->count+16 < (hash->mask+1)/2
          && hash->mask != 0x3){ // Should table shrink?
        hash_change_size(hash, ((hash->mask+1) / 2) - 1);
      }
      DFSCH_RWLOCK_UNLOCK(&hash->lock);
      return 1;
    }
    j = i;
    i = i->next;
  }
  DFSCH_RWLOCK_UNLOCK(&hash->lock);
  return 0;
}
Variable Documentation
dfsch_type_t dfsch_custom_hash_type_type
Definition at line 77 of file hash.c.
dfsch_type_t dfsch_hash_basetype
Definition at line 57 of file hash.c.
dfsch_type_t dfsch_standard_hash_type
Definition at line 67 of file hash.c.