dfsch: lib/inet_mod.c File Reference
lib/inet_mod.c File Reference
#include "dfsch/lib/inet.h"
#include <dfsch/strings.h>
#include <dfsch/hash.h>
#include <string.h>
Functions
dfsch_object_t * dfsch_module_inet_register (dfsch_object_t *env)
static dfsch_object_t * http_query_2_alist (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * http_query_2_hash (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * http_split_path (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * http_split_query (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_base64_decode (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_base64_encode (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_uri_base64_decode (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_uri_base64_encode (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_urldecode (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_urlencode (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * inet_xml_escape (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Function Documentation
dfsch_object_t* dfsch_module_inet_register (dfsch_object_t * env)
Definition at line 151 of file inet_mod.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_provide(), http_query_2_alist(), http_query_2_hash(), http_split_path(), http_split_query(), inet_base64_decode(), inet_base64_encode(), inet_uri_base64_decode(), inet_uri_base64_encode(), inet_urldecode(), inet_urlencode(), and inet_xml_escape().
{
  dfsch_provide(env, "inet");
  dfsch_define_cstr(env, "http:split-query",
                    dfsch_make_primitive(http_split_query, NULL));
  dfsch_define_cstr(env, "http:split-path",
                    dfsch_make_primitive(http_split_path, NULL));
  dfsch_define_cstr(env, "http:query->alist",
                    dfsch_make_primitive(http_query_2_alist, NULL));
  dfsch_define_cstr(env, "http:query->hash",
                    dfsch_make_primitive(http_query_2_hash, NULL));
  dfsch_define_cstr(env, "inet:urldecode",
                    dfsch_make_primitive(inet_urldecode, NULL));
  dfsch_define_cstr(env, "inet:urlencode",
                    dfsch_make_primitive(inet_urlencode, NULL));
  dfsch_define_cstr(env, "inet:base64-encode",
                    dfsch_make_primitive(inet_base64_encode, NULL));
  dfsch_define_cstr(env, "inet:uri-base64-encode",
                    dfsch_make_primitive(inet_uri_base64_encode, NULL));
  dfsch_define_cstr(env, "inet:base64-decode",
                    dfsch_make_primitive(inet_base64_decode, NULL));
  dfsch_define_cstr(env, "inet:uri-base64-decode",
                    dfsch_make_primitive(inet_uri_base64_decode, NULL));
  dfsch_define_cstr(env, "inet:xml-escape",
                    dfsch_make_primitive(inet_xml_escape, NULL));
}
static dfsch_object_t* http_query_2_alist (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 58 of file inet_mod.c.
References DFSCH_ARG_END, dfsch_http_query_2_alist(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_inet_register().
{
  char* query;
  DFSCH_STRING_ARG(args, query);
  DFSCH_ARG_END(args);
  return dfsch_http_query_2_alist(query);
}
static dfsch_object_t* http_query_2_hash (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 67 of file inet_mod.c.
References DFSCH_ARG_END, dfsch_http_query_2_hash(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_inet_register().
{
  char* query;
  DFSCH_STRING_ARG(args, query);
  DFSCH_ARG_END(args);
  return dfsch_http_query_2_hash(query);
}
static dfsch_object_t* http_split_path (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 48 of file inet_mod.c.
References DFSCH_ARG_END, dfsch_http_split_path(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_inet_register().
{
  char* path;
  DFSCH_STRING_ARG(args, path);
  DFSCH_ARG_END(args);
  return dfsch_http_split_path(path);
}
static dfsch_object_t* http_split_query (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 28 of file inet_mod.c.
References DFSCH_ARG_END, dfsch_list(), dfsch_make_string_buf(), dfsch_make_string_cstr(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_inet_register().
{
  char* pos;
  char* uri;
  DFSCH_STRING_ARG(args, uri);
  DFSCH_ARG_END(args);
  pos = strchr(uri, '?');
  if (!pos){
    return dfsch_list(1,
                      dfsch_make_string_cstr(uri));
  } else {
    return dfsch_list(2,
                      dfsch_make_string_buf(uri, pos-uri),
                      dfsch_make_string_cstr(pos+1));
  }
}
static dfsch_object_t* inet_base64_decode (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 119 of file inet_mod.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_inet_base64_decode(), and dfsch_make_string_nocopy().
Referenced by dfsch_module_inet_register().
{
  dfsch_strbuf_t* str;
  DFSCH_BUFFER_ARG(args, str);
  DFSCH_ARG_END(args);
  return dfsch_make_string_nocopy(dfsch_inet_base64_decode(str));
}
static dfsch_object_t* inet_base64_encode (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 95 of file inet_mod.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_inet_base64_encode(), dfsch_make_string_nocopy(), and DFSCH_OBJECT_ARG_OPT.
Referenced by dfsch_module_inet_register().
{
  dfsch_strbuf_t* str;
  dfsch_object_t* wrap;
  dfsch_object_t* pad;
  DFSCH_BUFFER_ARG(args, str);
  DFSCH_OBJECT_ARG_OPT(args, wrap, NULL);
  DFSCH_OBJECT_ARG_OPT(args, pad, NULL);
  DFSCH_ARG_END(args);
  return dfsch_make_string_nocopy(dfsch_inet_base64_encode(str,
                                                           wrap!=NULL,
                                                           pad!=NULL));
}
static dfsch_object_t* inet_uri_base64_decode (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 128 of file inet_mod.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_inet_uri_base64_decode(), and dfsch_make_string_nocopy().
Referenced by dfsch_module_inet_register().
{
  dfsch_strbuf_t* str;
  DFSCH_BUFFER_ARG(args, str);
  DFSCH_ARG_END(args);
  return dfsch_make_string_nocopy(dfsch_inet_uri_base64_decode(str));
}
static dfsch_object_t* inet_uri_base64_encode (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 110 of file inet_mod.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_inet_uri_base64_encode(), and dfsch_make_string_nocopy().
Referenced by dfsch_module_inet_register().
{
  dfsch_strbuf_t* str;
  DFSCH_BUFFER_ARG(args, str);
  DFSCH_ARG_END(args);
  return dfsch_make_string_nocopy(dfsch_inet_uri_base64_encode(str));
}
static dfsch_object_t* inet_urldecode (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 76 of file inet_mod.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_inet_urldecode(), and dfsch_make_string_nocopy().
Referenced by dfsch_module_inet_register().
{
  dfsch_strbuf_t* str;
  DFSCH_BUFFER_ARG(args, str);
  DFSCH_ARG_END(args);
  return dfsch_make_string_nocopy(dfsch_inet_urldecode(str));
}
static dfsch_object_t* inet_urlencode (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 85 of file inet_mod.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_inet_urlencode(), and dfsch_make_string_nocopy().
Referenced by dfsch_module_inet_register().
{
  dfsch_strbuf_t* str;
  DFSCH_BUFFER_ARG(args, str);
  DFSCH_ARG_END(args);
  return dfsch_make_string_nocopy(dfsch_inet_urlencode(str));
}
static dfsch_object_t* inet_xml_escape (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 138 of file inet_mod.c.
References DFSCH_ARG_END, dfsch_inet_xml_escape(), dfsch_make_string_cstr(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_inet_register().
{
  char* str;
  DFSCH_STRING_ARG(args, str);
  DFSCH_ARG_END(args);
  return dfsch_make_string_cstr(dfsch_inet_xml_escape(str));
}