dfsch: src/internal.h File Reference
src/internal.h File Reference
#include <dfsch/dfsch.h>
Functions
void dfsch__bignum_register (dfsch_object_t *ctx)
void dfsch__conditions_register (dfsch_object_t *ctx)
void dfsch__control_register (dfsch_object_t *ctx)
void dfsch__format_native_register (dfsch_object_t *ctx)
void dfsch__generic_register (dfsch_object_t *ctx)
void dfsch__hash_native_register (dfsch_object_t *ctx)
void dfsch__native_register (dfsch_object_t *ctx)
void dfsch__number_native_register (dfsch_object_t *ctx)
void dfsch__port_native_register (dfsch_object_t *ctx)
void dfsch__promise_native_register (dfsch_object_t *ctx)
void dfsch__string_native_register (dfsch_object_t *ctx)
void dfsch__system_register (dfsch_object_t *ctx)
void dfsch__weak_native_register (dfsch_object_t *ctx)
void dfsch__wrapper_native_register (dfsch_object_t *ctx)
Function Documentation
void dfsch__bignum_register (dfsch_object_t * ctx)
Definition at line 1008 of file bignum.c.
References DFSCH_BIGNUM_TYPE, dfsch_define_cstr(), and DFSCH_PRIMITIVE_REF.
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<bignum>", DFSCH_BIGNUM_TYPE);
  dfsch_define_cstr(ctx, "integer-expt", DFSCH_PRIMITIVE_REF(integer_expt));
  dfsch_define_cstr(ctx, "integer->bytes", DFSCH_PRIMITIVE_REF(bignum_2_bytes));
  dfsch_define_cstr(ctx, "bytes->integer", DFSCH_PRIMITIVE_REF(bytes_2_bignum));
}
void dfsch__conditions_register (dfsch_object_t * ctx)
Definition at line 582 of file conditions.c.
References DFSCH_CONDITION_TYPE, dfsch_define_cstr(), DFSCH_ERROR_TYPE, DFSCH_FORM_REF, DFSCH_OPERATING_SYSTEM_ERROR_TYPE, DFSCH_PRIMITIVE_REF, DFSCH_RUNTIME_ERROR_TYPE, DFSCH_TYPE_ERROR_TYPE, and DFSCH_WARNING_TYPE.
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<condition>", DFSCH_CONDITION_TYPE);
  dfsch_define_cstr(ctx, "<warning>", DFSCH_WARNING_TYPE);
  dfsch_define_cstr(ctx, "<error>", DFSCH_ERROR_TYPE);
  dfsch_define_cstr(ctx, "<runtime-error>", DFSCH_RUNTIME_ERROR_TYPE);
  dfsch_define_cstr(ctx, "<type-error>", DFSCH_TYPE_ERROR_TYPE);
  dfsch_define_cstr(ctx, "<operating-system-error>",
                    DFSCH_OPERATING_SYSTEM_ERROR_TYPE);
  dfsch_define_cstr(ctx, "make-condition",
                    DFSCH_PRIMITIVE_REF(make_condition));
  dfsch_define_cstr(ctx, "make-condition-with-fields",
                    DFSCH_PRIMITIVE_REF(make_condition_with_fields));
  dfsch_define_cstr(ctx, "condition-field",
                    DFSCH_PRIMITIVE_REF(condition_field));
  dfsch_define_cstr(ctx, "condition-put-field",
                    DFSCH_PRIMITIVE_REF(condition_put_field));
  dfsch_define_cstr(ctx, "condition-fields",
                    DFSCH_PRIMITIVE_REF(condition_fields));
  dfsch_define_cstr(ctx, "signal",
                    DFSCH_PRIMITIVE_REF(signal));
  dfsch_define_cstr(ctx, "invoke-restart",
                    DFSCH_PRIMITIVE_REF(invoke_restart));
  dfsch_define_cstr(ctx, "compute-restarts",
                    DFSCH_PRIMITIVE_REF(compute_restarts));
  dfsch_define_cstr(ctx, "warning",
                    DFSCH_PRIMITIVE_REF(warning));
  dfsch_define_cstr(ctx, "error",
                    DFSCH_PRIMITIVE_REF(error));
  dfsch_define_cstr(ctx, "runtime-error",
                    DFSCH_PRIMITIVE_REF(runtime_error));
  dfsch_define_cstr(ctx, "restart-name",
                    DFSCH_PRIMITIVE_REF(restart_name));
  dfsch_define_cstr(ctx, "restart-description",
                    DFSCH_PRIMITIVE_REF(restart_description));
  dfsch_define_cstr(ctx, "handler-bind",
                    DFSCH_FORM_REF(handler_bind));
  dfsch_define_cstr(ctx, "restart-bind",
                    DFSCH_FORM_REF(restart_bind));
}
void dfsch__control_register (dfsch_object_t * ctx)
Definition at line 454 of file control.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, native_apply(), native_eval(), and native_eval_proc().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "begin", DFSCH_FORM_REF(begin));
  dfsch_define_cstr(ctx, "let", DFSCH_FORM_REF(let));
  dfsch_define_cstr(ctx, "let*", DFSCH_FORM_REF(let_seq));
  dfsch_define_cstr(ctx, "letrec", DFSCH_FORM_REF(letrec));
  dfsch_define_cstr(ctx, "quasiquote", DFSCH_FORM_REF(quasiquote));
  dfsch_define_cstr(ctx, "quote", DFSCH_FORM_REF(quote));
  dfsch_define_cstr(ctx, "if", DFSCH_FORM_REF(if));
  dfsch_define_cstr(ctx, "when", DFSCH_FORM_REF(when));
  dfsch_define_cstr(ctx, "unless", DFSCH_FORM_REF(unless));
  dfsch_define_cstr(ctx, "cond", DFSCH_FORM_REF(cond));
  dfsch_define_cstr(ctx, "case", DFSCH_FORM_REF(case));
  dfsch_define_cstr(ctx, "unwind-protect", DFSCH_FORM_REF(unwind_protect));
  dfsch_define_cstr(ctx, "catch", DFSCH_FORM_REF(catch));
  dfsch_define_cstr(ctx, "throw", DFSCH_PRIMITIVE_REF(throw));
  dfsch_define_cstr(ctx, "eval", dfsch_make_primitive(&native_eval,NULL));
  dfsch_define_cstr(ctx, "eval-proc", dfsch_make_primitive(&native_eval_proc,
                                                          NULL));
  dfsch_define_cstr(ctx, "apply", dfsch_make_primitive(&native_apply,NULL));
  dfsch_define_cstr(ctx, "do", DFSCH_FORM_REF(do));
  dfsch_define_cstr(ctx, "dolist", DFSCH_FORM_REF(dolist));
  dfsch_define_cstr(ctx, "destructuring-bind",
                    DFSCH_FORM_REF(destructuring_bind));
}
void dfsch__format_native_register (dfsch_object_t * ctx)
Definition at line 399 of file format.c.
References dfsch_define_cstr(), dfsch_make_primitive(), and native_format().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "format",
                    dfsch_make_primitive(&native_format,NULL));
}
void dfsch__generic_register (dfsch_object_t * ctx)
void dfsch__hash_native_register (dfsch_object_t * ctx)
Definition at line 544 of file hash.c.
References DFSCH_CUSTOM_HASH_TYPE_TYPE, dfsch_define_cstr(), dfsch_make_primitive(), DFSCH_STANDARD_HASH_TYPE, native_alist_2_hash(), native_hash_2_alist(), native_hash_p(), native_hash_ref(), native_hash_set(), native_hash_set_if_exists(), native_hash_unset(), and native_make_hash().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<hash>", DFSCH_HASH_BASETYPE);
  dfsch_define_cstr(ctx, "<standard-hash>", DFSCH_STANDARD_HASH_TYPE);
  dfsch_define_cstr(ctx, "<custom-hash-type>", DFSCH_CUSTOM_HASH_TYPE_TYPE);
  dfsch_define_cstr(ctx, "make-hash",
                    dfsch_make_primitive(&native_make_hash,NULL));
  dfsch_define_cstr(ctx, "hash?",
                    dfsch_make_primitive(&native_hash_p,NULL));
  dfsch_define_cstr(ctx, "hash-ref",
                    dfsch_make_primitive(&native_hash_ref,NULL));
  dfsch_define_cstr(ctx, "hash-unset!",
                    dfsch_make_primitive(&native_hash_unset,NULL));
  dfsch_define_cstr(ctx, "hash-set!",
                    dfsch_make_primitive(&native_hash_set,NULL));
  dfsch_define_cstr(ctx, "hash-set-if-exists!",
                    dfsch_make_primitive(&native_hash_set_if_exists,NULL));
  dfsch_define_cstr(ctx, "hash->alist",
                    dfsch_make_primitive(&native_hash_2_alist,NULL));
  dfsch_define_cstr(ctx, "alist->hash",
                    dfsch_make_primitive(&native_alist_2_hash,NULL));
}
void dfsch__native_register (dfsch_object_t * ctx)
Definition at line 860 of file native.c.
References dfsch__bignum_register(), dfsch__conditions_register(), dfsch__control_register(), dfsch__format_native_register(), dfsch__hash_native_register(), dfsch__native_cxr_register(), dfsch__number_native_register(), dfsch__object_native_register(), dfsch__port_native_register(), dfsch__promise_native_register(), dfsch__random_register(), dfsch__string_native_register(), dfsch__system_register(), dfsch__weak_native_register(), dfsch__wrapper_native_register(), dfsch_define_cstr(), DFSCH_FORM_REF, DFSCH_PRIMITIVE_REF, and DFSCH_SYM_TRUE.
Referenced by dfsch_make_context().
{
  dfsch_define_cstr(ctx, "gensym", DFSCH_PRIMITIVE_REF(gensym));
  dfsch_define_cstr(ctx, "id", DFSCH_PRIMITIVE_REF(id));
  dfsch_define_cstr(ctx, "hash", DFSCH_PRIMITIVE_REF(hash));
  dfsch_define_cstr(ctx, "type-of", DFSCH_PRIMITIVE_REF(type_of));
  dfsch_define_cstr(ctx, "type-name", DFSCH_PRIMITIVE_REF(type_name));
  dfsch_define_cstr(ctx, "superclass?", DFSCH_PRIMITIVE_REF(superclass_p));
  dfsch_define_cstr(ctx, "instance?", DFSCH_PRIMITIVE_REF(instance_p));
  dfsch_define_cstr(ctx, "superclass", DFSCH_PRIMITIVE_REF(superclass));
  dfsch_define_cstr(ctx, "get-list-annotation",
                    DFSCH_PRIMITIVE_REF(get_list_annotation));
  dfsch_define_cstr(ctx, "eq?", DFSCH_PRIMITIVE_REF(eq_p));
  dfsch_define_cstr(ctx, "eqv?", DFSCH_PRIMITIVE_REF(eqv_p));
  dfsch_define_cstr(ctx, "equal?", DFSCH_PRIMITIVE_REF(equal_p));
  dfsch_define_cstr(ctx, "and", DFSCH_FORM_REF(and));
  dfsch_define_cstr(ctx, "or",DFSCH_FORM_REF(or));
  dfsch_define_cstr(ctx, "not", DFSCH_PRIMITIVE_REF(not));
  dfsch_define_cstr(ctx, "lambda", DFSCH_FORM_REF(lambda));
  dfsch_define_cstr(ctx, "define", DFSCH_FORM_REF(define));
  dfsch_define_cstr(ctx, "define-variable", DFSCH_FORM_REF(define_variable));
  dfsch_define_cstr(ctx, "define-constant", DFSCH_FORM_REF(define_constant));
  dfsch_define_cstr(ctx, "declare", DFSCH_FORM_REF(declare));
  dfsch_define_cstr(ctx, "defined?", DFSCH_FORM_REF(defined_p));
  dfsch_define_cstr(ctx, "set!", DFSCH_FORM_REF(set));
  dfsch_define_cstr(ctx, "unset!", DFSCH_FORM_REF(unset));
  dfsch_define_cstr(ctx, "make-macro", DFSCH_PRIMITIVE_REF(make_macro));
  dfsch_define_cstr(ctx, "define-macro", DFSCH_FORM_REF(define_macro));
  dfsch_define_cstr(ctx, "cons", DFSCH_PRIMITIVE_REF(cons));
  dfsch_define_cstr(ctx, "cons-immutable", DFSCH_PRIMITIVE_REF(cons_immutable));
  dfsch_define_cstr(ctx, "list", DFSCH_PRIMITIVE_REF(list));
  dfsch_define_cstr(ctx, "car", DFSCH_PRIMITIVE_REF(car));
  dfsch_define_cstr(ctx, "cdr", DFSCH_PRIMITIVE_REF(cdr));
  dfsch_define_cstr(ctx, "set-car!", DFSCH_PRIMITIVE_REF(set_car));
  dfsch_define_cstr(ctx, "set-cdr!", DFSCH_PRIMITIVE_REF(set_cdr));
  dfsch_define_cstr(ctx, "length", DFSCH_PRIMITIVE_REF(length));
  dfsch_define_cstr(ctx, "zip", DFSCH_PRIMITIVE_REF(zip));
  dfsch_define_cstr(ctx, "append", DFSCH_PRIMITIVE_REF(append));
  dfsch_define_cstr(ctx, "for-each", DFSCH_PRIMITIVE_REF(for_each));
  dfsch_define_cstr(ctx, "map", DFSCH_PRIMITIVE_REF(map));
  dfsch_define_cstr(ctx, "filter", DFSCH_PRIMITIVE_REF(filter));
  dfsch_define_cstr(ctx, "reduce", DFSCH_PRIMITIVE_REF(reduce));
  dfsch_define_cstr(ctx, "list-ref", DFSCH_PRIMITIVE_REF(list_ref));
  dfsch_define_cstr(ctx, "reverse", DFSCH_PRIMITIVE_REF(reverse));
  dfsch_define_cstr(ctx, "member", DFSCH_PRIMITIVE_REF(member));
  dfsch_define_cstr(ctx, "memq", DFSCH_PRIMITIVE_REF(memq));
  dfsch_define_cstr(ctx, "memv", DFSCH_PRIMITIVE_REF(memv));
  dfsch_define_cstr(ctx, "sort-list!", DFSCH_PRIMITIVE_REF(sort_list));
  dfsch_define_cstr(ctx, "assoc", DFSCH_PRIMITIVE_REF(assoc));
  dfsch_define_cstr(ctx, "assq", DFSCH_PRIMITIVE_REF(assq));
  dfsch_define_cstr(ctx, "assv", DFSCH_PRIMITIVE_REF(assv));
  dfsch_define_cstr(ctx, "null?", DFSCH_PRIMITIVE_REF(null_p));
  dfsch_define_cstr(ctx, "atom?", DFSCH_PRIMITIVE_REF(atom_p));
  dfsch_define_cstr(ctx, "pair?", DFSCH_PRIMITIVE_REF(pair_p));
  dfsch_define_cstr(ctx, "list?", DFSCH_PRIMITIVE_REF(list_p));
  dfsch_define_cstr(ctx, "symbol?", DFSCH_PRIMITIVE_REF(symbol_p));
  dfsch_define_cstr(ctx, "string?", DFSCH_PRIMITIVE_REF(string_p));
  dfsch_define_cstr(ctx, "primitive?",
                   DFSCH_PRIMITIVE_REF(primitive_p));
  dfsch_define_cstr(ctx, "function?", DFSCH_PRIMITIVE_REF(function_p));
  dfsch_define_cstr(ctx, "procedure?",
                   DFSCH_PRIMITIVE_REF(procedure_p));
  dfsch_define_cstr(ctx, "macro?", DFSCH_PRIMITIVE_REF(macro_p));
  dfsch_define_cstr(ctx, "form?", DFSCH_PRIMITIVE_REF(form_p));
  dfsch_define_cstr(ctx, "vector?", DFSCH_PRIMITIVE_REF(vector_p));
  dfsch_define_cstr(ctx, "true", DFSCH_SYM_TRUE);
  dfsch_define_cstr(ctx, "nil", NULL);
  dfsch_define_cstr(ctx, "else", DFSCH_SYM_TRUE);
  dfsch_define_cstr(ctx, "t", DFSCH_SYM_TRUE);
  dfsch_define_cstr(ctx, "T", DFSCH_SYM_TRUE);
  dfsch_define_cstr(ctx, "make-vector",
                   DFSCH_PRIMITIVE_REF(make_vector));
  dfsch_define_cstr(ctx, "vector",
                   DFSCH_PRIMITIVE_REF(vector));
  dfsch_define_cstr(ctx, "vector-length",
                   DFSCH_PRIMITIVE_REF(vector_length));
  dfsch_define_cstr(ctx, "vector-set!",
                   DFSCH_PRIMITIVE_REF(vector_set));
  dfsch_define_cstr(ctx, "vector-ref",
                   DFSCH_PRIMITIVE_REF(vector_ref));
  dfsch_define_cstr(ctx, "vector->list",
                   DFSCH_PRIMITIVE_REF(vector_2_list));
  dfsch_define_cstr(ctx, "list->vector",
                   DFSCH_PRIMITIVE_REF(list_2_vector));
  dfsch_define_cstr(ctx, "object->string",
                   DFSCH_PRIMITIVE_REF(object_2_string));
  dfsch_define_cstr(ctx, "string->object",
                   DFSCH_PRIMITIVE_REF(string_2_object));
  dfsch_define_cstr(ctx, "string->object-list",
                   DFSCH_PRIMITIVE_REF(string_2_object_list));
  dfsch_define_cstr(ctx, "dfsch%write-object",
                   DFSCH_PRIMITIVE_REF(write__object));
  dfsch_define_cstr(ctx, "dfsch%write-string",
                   DFSCH_PRIMITIVE_REF(write__string));
  dfsch_define_cstr(ctx, "symbol->string",
                   DFSCH_PRIMITIVE_REF(symbol_2_string));
  dfsch_define_cstr(ctx, "string->symbol",
                   DFSCH_PRIMITIVE_REF(string_2_symbol));
  dfsch_define_cstr(ctx, "macro-expand",
                   DFSCH_PRIMITIVE_REF(macro_expand));
  dfsch_define_cstr(ctx, "slot-ref", DFSCH_PRIMITIVE_REF(slot_ref));
  dfsch_define_cstr(ctx, "slot-set!", DFSCH_PRIMITIVE_REF(slot_set));
  dfsch_define_cstr(ctx, "get-slots", DFSCH_PRIMITIVE_REF(get_slots));
  dfsch_define_cstr(ctx, "find-slot", DFSCH_PRIMITIVE_REF(find_slot));
  dfsch__native_cxr_register(ctx);
  dfsch__control_register(ctx);
  dfsch__system_register(ctx);
  dfsch__hash_native_register(ctx);
  dfsch__promise_native_register(ctx);
  dfsch__number_native_register(ctx);
  dfsch__string_native_register(ctx);
  dfsch__wrapper_native_register(ctx);
  dfsch__object_native_register(ctx);
  dfsch__weak_native_register(ctx);
  dfsch__format_native_register(ctx);
  dfsch__port_native_register(ctx);
  dfsch__bignum_register(ctx);
  dfsch__conditions_register(ctx);
  dfsch__random_register(ctx);
}
void dfsch__number_native_register (dfsch_object_t * ctx)
Definition at line 1432 of file number.c.
References dfsch_define_cstr(), DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), DFSCH_NUMBER_TYPE, DFSCH_PRIMITIVE_REF, DFSCH_RATIONAL_TYPE, and DFSCH_REAL_TYPE.
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<number>", DFSCH_NUMBER_TYPE);
  dfsch_define_cstr(ctx, "<real>", DFSCH_REAL_TYPE);
  dfsch_define_cstr(ctx, "<rational>", DFSCH_RATIONAL_TYPE);
  dfsch_define_cstr(ctx, "<integer>", DFSCH_INTEGER_TYPE);
  dfsch_define_cstr(ctx, "<fixnum>", DFSCH_FIXNUM_TYPE);
  dfsch_define_cstr(ctx, "<flonum>", DFSCH_FLONUM_TYPE);
  dfsch_define_cstr(ctx, "<fracnum>", DFSCH_FRACNUM_TYPE);
  dfsch_define_cstr(ctx, "+", DFSCH_PRIMITIVE_REF(plus));
  dfsch_define_cstr(ctx, "-", DFSCH_PRIMITIVE_REF(minus));
  dfsch_define_cstr(ctx, "*", DFSCH_PRIMITIVE_REF(mult));
  dfsch_define_cstr(ctx, "/", DFSCH_PRIMITIVE_REF(slash));
  dfsch_define_cstr(ctx, "/i", DFSCH_PRIMITIVE_REF(slash_i));
  dfsch_define_cstr(ctx, "%", DFSCH_PRIMITIVE_REF(modulo));
  dfsch_define_cstr(ctx, "=", DFSCH_PRIMITIVE_REF(number_equal));
  dfsch_define_cstr(ctx, "<", DFSCH_PRIMITIVE_REF(lt));
  dfsch_define_cstr(ctx, ">", DFSCH_PRIMITIVE_REF(gt));
  dfsch_define_cstr(ctx, "<=", DFSCH_PRIMITIVE_REF(lte));
  dfsch_define_cstr(ctx, ">=", DFSCH_PRIMITIVE_REF(gte));
  dfsch_define_cstr(ctx, "number?", DFSCH_PRIMITIVE_REF(number_p));
  dfsch_define_cstr(ctx, "real?", DFSCH_PRIMITIVE_REF(real_p));
  dfsch_define_cstr(ctx, "rational?", DFSCH_PRIMITIVE_REF(rational_p));
  dfsch_define_cstr(ctx, "integer?", DFSCH_PRIMITIVE_REF(integer_p));
  dfsch_define_cstr(ctx, "exact?", DFSCH_PRIMITIVE_REF(exact_p));
  dfsch_define_cstr(ctx, "inexact?", DFSCH_PRIMITIVE_REF(inexact_p));
  dfsch_define_cstr(ctx, "exact->inexact",
                    DFSCH_PRIMITIVE_REF(exact_2_inexact));
  dfsch_define_cstr(ctx, "pi",
                    dfsch_make_number_from_double(4*atan(1)));
  dfsch_define_cstr(ctx, "abs", DFSCH_PRIMITIVE_REF(abs));
  dfsch_define_cstr(ctx, "exp", DFSCH_PRIMITIVE_REF(exp));
  dfsch_define_cstr(ctx, "log", DFSCH_PRIMITIVE_REF(log));
  dfsch_define_cstr(ctx, "expt", DFSCH_PRIMITIVE_REF(expt));
  dfsch_define_cstr(ctx, "sin", DFSCH_PRIMITIVE_REF(sin));
  dfsch_define_cstr(ctx, "cos", DFSCH_PRIMITIVE_REF(cos));
  dfsch_define_cstr(ctx, "tan", DFSCH_PRIMITIVE_REF(tan));
  dfsch_define_cstr(ctx, "asin", DFSCH_PRIMITIVE_REF(asin));
  dfsch_define_cstr(ctx, "acos", DFSCH_PRIMITIVE_REF(acos));
  dfsch_define_cstr(ctx, "atan", DFSCH_PRIMITIVE_REF(atan));
  dfsch_define_cstr(ctx, "sqrt", DFSCH_PRIMITIVE_REF(sqrt));
  dfsch_define_cstr(ctx, "min", DFSCH_PRIMITIVE_REF(min));
  dfsch_define_cstr(ctx, "max", DFSCH_PRIMITIVE_REF(max));
  dfsch_define_cstr(ctx, "zero?", DFSCH_PRIMITIVE_REF(zero_p));
  dfsch_define_cstr(ctx, "negative?", DFSCH_PRIMITIVE_REF(negative_p));
  dfsch_define_cstr(ctx, "positive?", DFSCH_PRIMITIVE_REF(positive_p));
  dfsch_define_cstr(ctx, "even?", DFSCH_PRIMITIVE_REF(even_p));
  dfsch_define_cstr(ctx, "odd?", DFSCH_PRIMITIVE_REF(odd_p));
  dfsch_define_cstr(ctx, "round", DFSCH_PRIMITIVE_REF(round));
  dfsch_define_cstr(ctx, "floor", DFSCH_PRIMITIVE_REF(floor));
  dfsch_define_cstr(ctx, "ceiling", DFSCH_PRIMITIVE_REF(ceiling));
  dfsch_define_cstr(ctx, "truncate", DFSCH_PRIMITIVE_REF(truncate));
  dfsch_define_cstr(ctx, "number->string",
                   DFSCH_PRIMITIVE_REF(number_2_string));
  dfsch_define_cstr(ctx, "string->number",
                   DFSCH_PRIMITIVE_REF(string_2_number));
  dfsch_define_cstr(ctx, "most-positive-fixnum",
                    DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_MAX));
  dfsch_define_cstr(ctx, "most-negative-fixnum",
                    DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_MIN));
  dfsch_define_cstr(ctx, "gcd", DFSCH_PRIMITIVE_REF(gcd));
  dfsch_define_cstr(ctx, "mod-inv", DFSCH_PRIMITIVE_REF(mod_inv));
  dfsch_define_cstr(ctx, "lcm", DFSCH_PRIMITIVE_REF(lcm));
  dfsch_define_cstr(ctx, "logand", DFSCH_PRIMITIVE_REF(logand));
  dfsch_define_cstr(ctx, "logior", DFSCH_PRIMITIVE_REF(logior));
  dfsch_define_cstr(ctx, "logxor", DFSCH_PRIMITIVE_REF(logxor));
  dfsch_define_cstr(ctx, "lognot", DFSCH_PRIMITIVE_REF(lognot));
}
void dfsch__port_native_register (dfsch_object_t * ctx)
Definition at line 938 of file ports.c.
References dfsch_define_cstr(), DFSCH_EOF_OBJECT_TYPE, DFSCH_FILE_PORT_TYPE, dfsch_make_primitive(), DFSCH_NULL_PORT_TYPE, DFSCH_PRIMITIVE_REF, DFSCH_STRING_INPUT_PORT_TYPE, DFSCH_STRING_OUTPUT_PORT_TYPE, native_current_error_port(), native_current_input_port(), native_current_output_port(), native_display(), native_eof_object_p(), native_newline(), native_null_port(), native_port_read_buf(), native_port_read_line(), native_port_seek(), native_port_tell(), native_port_write_buf(), native_read(), native_string_input_port(), native_string_output_port(), native_string_output_port_value(), and native_write().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<port>", DFSCH_PORT_TYPE);
  dfsch_define_cstr(ctx, "<null-port>", DFSCH_NULL_PORT_TYPE);
  dfsch_define_cstr(ctx, "<file-port>", DFSCH_FILE_PORT_TYPE);
  dfsch_define_cstr(ctx, "<string-input-port>", DFSCH_STRING_INPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "<string-output-port>", DFSCH_STRING_OUTPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "<eof-object>", DFSCH_EOF_OBJECT_TYPE);
  dfsch_define_cstr(ctx, "current-output-port",
                    dfsch_make_primitive(native_current_output_port, NULL));
  dfsch_define_cstr(ctx, "current-input-port",
                    dfsch_make_primitive(native_current_input_port, NULL));
  dfsch_define_cstr(ctx, "current-error-port",
                    dfsch_make_primitive(native_current_error_port, NULL));
  dfsch_define_cstr(ctx, "null-port",
                    dfsch_make_primitive(native_null_port, NULL));
  dfsch_define_cstr(ctx, "write",
                    dfsch_make_primitive(native_write, NULL));
  dfsch_define_cstr(ctx, "display",
                    dfsch_make_primitive(native_display, NULL));
  dfsch_define_cstr(ctx, "newline",
                    dfsch_make_primitive(native_newline, NULL));
  dfsch_define_cstr(ctx, "read",
                    dfsch_make_primitive(native_read, NULL));
  dfsch_define_cstr(ctx, "eof-object?",
                    dfsch_make_primitive(native_eof_object_p, NULL));
  dfsch_define_cstr(ctx, "port-write-buf",
                    dfsch_make_primitive(native_port_write_buf, NULL));
  dfsch_define_cstr(ctx, "port-read-buf",
                    dfsch_make_primitive(native_port_read_buf, NULL));
  dfsch_define_cstr(ctx, "port-read-whole",
                    DFSCH_PRIMITIVE_REF(port_read_whole));
  dfsch_define_cstr(ctx, "port-read-line",
                    dfsch_make_primitive(native_port_read_line, NULL));
  dfsch_define_cstr(ctx, "port-seek!",
                    dfsch_make_primitive(native_port_seek, NULL));
  dfsch_define_cstr(ctx, "port-tell",
                    dfsch_make_primitive(native_port_tell, NULL));
  dfsch_define_cstr(ctx, "string-output-port",
                    dfsch_make_primitive(native_string_output_port, NULL));
  dfsch_define_cstr(ctx, "string-output-port-value",
                    dfsch_make_primitive(native_string_output_port_value,
                                         NULL));
  dfsch_define_cstr(ctx, "string-input-port",
                    dfsch_make_primitive(native_string_input_port, NULL));
}
void dfsch__promise_native_register (dfsch_object_t * ctx)
Definition at line 135 of file promise.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_make_primitive(), native_force(), native_stream_car(), and native_stream_cdr().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<promise>", &promise_type);
  dfsch_define_cstr(ctx, "delay", DFSCH_FORM_REF(delay));
  dfsch_define_cstr(ctx, "force",
                   dfsch_make_primitive(&native_force,NULL));
  dfsch_define_cstr(ctx, "stream-cons", DFSCH_FORM_REF(stream_cons));
  dfsch_define_cstr(ctx, "stream-car",
                   dfsch_make_primitive(&native_stream_car,NULL));
  dfsch_define_cstr(ctx, "stream-cdr",
                   dfsch_make_primitive(&native_stream_cdr,NULL));
}
void dfsch__string_native_register (dfsch_object_t * ctx)
Definition at line 1572 of file strings.c.
References dfsch_define_cstr(), dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, dfsch_string_ci_eq_p(), dfsch_string_ci_gt_p(), dfsch_string_ci_gte_p(), dfsch_string_ci_lt_p(), dfsch_string_ci_lte_p(), dfsch_string_eq_p(), dfsch_string_gt_p(), dfsch_string_gte_p(), dfsch_string_lt_p(), dfsch_string_lte_p(), pathname_basename(), pathname_dirname(), pathname_extension(), pathname_filename(), and string_length().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<string>", &string_type);
  dfsch_define_cstr(ctx, "string-append",
                   DFSCH_PRIMITIVE_REF(string_append));
  dfsch_define_cstr(ctx, "substring-bytes",
                   DFSCH_PRIMITIVE_REF(substring));
  dfsch_define_cstr(ctx, "substring",
                   DFSCH_PRIMITIVE_REF(substring_utf8));
  dfsch_define_cstr(ctx, "string-byte-ref",
                   DFSCH_PRIMITIVE_REF(string_ref));
  dfsch_define_cstr(ctx, "string-ref",
                   DFSCH_PRIMITIVE_REF(string_utf8_ref));
  dfsch_define_cstr(ctx, "string-byte-length",
                   DFSCH_PRIMITIVE_REF(string_length));
  dfsch_define_cstr(ctx, "string-length",
                   DFSCH_PRIMITIVE_REF(string_utf8_length));
  dfsch_define_cstr(ctx, "string->byte-list",
                   DFSCH_PRIMITIVE_REF(string_2_list));
  dfsch_define_cstr(ctx, "string->list",
                   DFSCH_PRIMITIVE_REF(string_utf8_2_list));
  dfsch_define_cstr(ctx, "byte-list->string",
                   DFSCH_PRIMITIVE_REF(list_2_string));
  dfsch_define_cstr(ctx, "list->string",
                   DFSCH_PRIMITIVE_REF(list_2_string_utf8));
  dfsch_define_cstr(ctx, "string=?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_eq_p));
  dfsch_define_cstr(ctx, "string<?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_lt_p));
  dfsch_define_cstr(ctx, "string>?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_gt_p));
  dfsch_define_cstr(ctx, "string<=?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_lte_p));
  dfsch_define_cstr(ctx, "string>=?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_gte_p));
  dfsch_define_cstr(ctx, "string-ci=?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_ci_eq_p));
  dfsch_define_cstr(ctx, "string-ci<?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_ci_lt_p));
  dfsch_define_cstr(ctx, "string-ci>?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_ci_gt_p));
  dfsch_define_cstr(ctx, "string-ci<=?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_ci_lte_p));
  dfsch_define_cstr(ctx, "string-ci>=?",
                   dfsch_make_primitive(&p_string_cmp_p_impl,
                                        &dfsch_string_ci_gte_p));
  dfsch_define_cstr(ctx, "char-upcase",
                   DFSCH_PRIMITIVE_REF(char_upcase));
  dfsch_define_cstr(ctx, "char-downcase",
                   DFSCH_PRIMITIVE_REF(char_downcase));
  dfsch_define_cstr(ctx, "char-titlecase",
                   DFSCH_PRIMITIVE_REF(char_titlecase));
  dfsch_define_cstr(ctx, "char-category",
                   DFSCH_PRIMITIVE_REF(char_category));
  dfsch_define_cstr(ctx, "char-alphabetic?",
                   DFSCH_PRIMITIVE_REF(char_alphabetic_p));
  dfsch_define_cstr(ctx, "char-numeric?",
                   DFSCH_PRIMITIVE_REF(char_numeric_p));
  dfsch_define_cstr(ctx, "char-whitespace?",
                   DFSCH_PRIMITIVE_REF(char_whitespace_p));
  dfsch_define_cstr(ctx, "char-lower-case?",
                   DFSCH_PRIMITIVE_REF(char_lower_case_p));
  dfsch_define_cstr(ctx, "char-upper-case?",
                   DFSCH_PRIMITIVE_REF(char_upper_case_p));
  dfsch_define_cstr(ctx, "char-decimal?",
                   DFSCH_PRIMITIVE_REF(char_decimal_p));
  dfsch_define_cstr(ctx, "char-mark?",
                   DFSCH_PRIMITIVE_REF(char_mark_p));
  dfsch_define_cstr(ctx, "string-upcase",
                   DFSCH_PRIMITIVE_REF(string_upcase));
  dfsch_define_cstr(ctx, "string-downcase",
                   DFSCH_PRIMITIVE_REF(string_downcase));
  dfsch_define_cstr(ctx, "string-titlecase",
                   DFSCH_PRIMITIVE_REF(string_titlecase));
  dfsch_define_cstr(ctx, "string-search",
                   DFSCH_PRIMITIVE_REF(string_search));
  dfsch_define_cstr(ctx, "string-search-ci",
                   DFSCH_PRIMITIVE_REF(string_search_ci));
  dfsch_define_cstr(ctx, "string-split",
                   DFSCH_PRIMITIVE_REF(string_split));
  dfsch_define_cstr(ctx, "string-split-on-byte",
                   DFSCH_PRIMITIVE_REF(string_split_on_byte));
  dfsch_define_cstr(ctx, "string-split-on-character",
                   DFSCH_PRIMITIVE_REF(string_split_on_character));
  dfsch_define_cstr(ctx, "string-replace",
                   DFSCH_PRIMITIVE_REF(string_replace));
  dfsch_define_cstr(ctx, "pathname-basename",
                   DFSCH_PRIMITIVE_REF(pathname_basename));
  dfsch_define_cstr(ctx, "pathname-dirname",
                   DFSCH_PRIMITIVE_REF(pathname_dirname));
  dfsch_define_cstr(ctx, "pathname-filename",
                   DFSCH_PRIMITIVE_REF(pathname_filename));
  dfsch_define_cstr(ctx, "pathname-extension",
                   DFSCH_PRIMITIVE_REF(pathname_extension));
}
void dfsch__system_register (dfsch_object_t * ctx)
Definition at line 229 of file system.c.
References dfsch_define_cstr(), dfsch_make_number_from_long(), dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, native_decode_universal_time(), native_encode_universal_time(), native_get_decoded_time(), native_get_universal_time(), and native_iso_format_time().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<decoded-time>", &decoded_time_type);
  dfsch_define_cstr(ctx, "decode-universal-time",
                    dfsch_make_primitive(native_decode_universal_time, NULL));
  dfsch_define_cstr(ctx, "encode-universal-time",
                    dfsch_make_primitive(native_encode_universal_time, NULL));
  dfsch_define_cstr(ctx, "get-decoded-time",
                    dfsch_make_primitive(native_get_decoded_time, NULL));
  dfsch_define_cstr(ctx, "get-universal-time",
                    dfsch_make_primitive(native_get_universal_time, NULL));
  dfsch_define_cstr(ctx, "iso-format-time",
                    dfsch_make_primitive(native_iso_format_time, NULL));
  dfsch_define_cstr(ctx, "get-internal-real-time",
                    DFSCH_PRIMITIVE_REF(get_internal_real_time));
  dfsch_define_cstr(ctx, "get-internal-run-time",
                    DFSCH_PRIMITIVE_REF(get_internal_run_time));
  dfsch_define_cstr(ctx, "internal-time-units-per-second",
                    dfsch_make_number_from_long(sysconf(_SC_CLK_TCK)));
}
void dfsch__weak_native_register (dfsch_object_t * ctx)
Definition at line 530 of file weak.c.
References dfsch_define_cstr(), dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, DFSCH_WEAK_KEY_HASH_TYPE, DFSCH_WEAK_REFERENCE_TYPE, DFSCH_WEAK_VECTOR_TYPE, native_list_2_weak_vector(), native_make_weak_reference(), native_make_weak_vector(), native_weak_reference_dereference(), native_weak_reference_live_p(), native_weak_vector(), native_weak_vector_2_list(), native_weak_vector_length(), native_weak_vector_ref(), and native_weak_vector_set().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<weak-reference>", DFSCH_WEAK_REFERENCE_TYPE);
  dfsch_define_cstr(ctx, "<weak-vector>", DFSCH_WEAK_VECTOR_TYPE);
  dfsch_define_cstr(ctx, "<weak-key-hash>", DFSCH_WEAK_KEY_HASH_TYPE);
  dfsch_define_cstr(ctx, "make-weak-reference",
                    dfsch_make_primitive(&native_make_weak_reference,NULL));
  dfsch_define_cstr(ctx, "weak-reference-live?",
                    dfsch_make_primitive(&native_weak_reference_live_p,NULL));
  dfsch_define_cstr(ctx, "weak-reference-dereference",
                    dfsch_make_primitive(&native_weak_reference_dereference,
                                         NULL));
  dfsch_define_cstr(ctx, "make-weak-vector",
                   dfsch_make_primitive(&native_make_weak_vector,NULL));
  dfsch_define_cstr(ctx, "weak-vector",
                   dfsch_make_primitive(&native_weak_vector,NULL));
  dfsch_define_cstr(ctx, "weak-vector-length",
                   dfsch_make_primitive(&native_weak_vector_length,NULL));
  dfsch_define_cstr(ctx, "weak-vector-set!",
                   dfsch_make_primitive(&native_weak_vector_set,NULL));
  dfsch_define_cstr(ctx, "weak-vector-ref",
                   dfsch_make_primitive(&native_weak_vector_ref,NULL));
  dfsch_define_cstr(ctx, "weak-vector->list",
                   dfsch_make_primitive(&native_weak_vector_2_list,NULL));
  dfsch_define_cstr(ctx, "list->weak-vector",
                   dfsch_make_primitive(&native_list_2_weak_vector,NULL));
  dfsch_define_cstr(ctx, "make-weak-key-hash",
                    DFSCH_PRIMITIVE_REF(make_weak_key_hash));
}
void dfsch__wrapper_native_register (dfsch_object_t * ctx)
Definition at line 244 of file wrapper.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_make_primitive(), native_make_wrapper_type(), native_unwrap(), and native_wrap().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<wrapper-type>", &wrapper_type);
  dfsch_define_cstr(ctx, "define-wrapper-type",
                    DFSCH_FORM_REF(define_wrapper_type));
  dfsch_define_cstr(ctx, "make-wrapper-type",
                   dfsch_make_primitive(&native_make_wrapper_type, NULL));
  dfsch_define_cstr(ctx, "wrap",
                   dfsch_make_primitive(&native_wrap, NULL));
  dfsch_define_cstr(ctx, "unwrap",
                   dfsch_make_primitive(&native_unwrap, NULL));
}