dfsch: dfsch/introspect.h File Reference
dfsch/introspect.h File Reference
#include <dfsch/dfsch.h>
Functions
dfsch_object_t * dfsch_get_trace_buffer ()
void dfsch_introspect_register (dfsch_object_t *env)
void dfsch_print_trace_buffer ()
Function Documentation
dfsch_object_t* dfsch_get_trace_buffer ()
void dfsch_introspect_register (dfsch_object_t * env)
Definition at line 266 of file introspect.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
Referenced by debug_main().
{
  dfsch_provide(env, "introspect");
  dfsch_define_cstr(env, "set-invoke-debugger-on-all-conditions!",
                    DFSCH_PRIMITIVE_REF(set_invoke_debugger_on_all_conditions));
  dfsch_define_cstr(env, "set-debugger!", DFSCH_PRIMITIVE_REF(set_debugger));
  dfsch_define_cstr(env, "enter-debugger",
                    DFSCH_PRIMITIVE_REF(enter_debugger));
  dfsch_define_cstr(env, "lookup-in-environment",
                    DFSCH_PRIMITIVE_REF(lookup_in_environment));
  dfsch_define_cstr(env, "set-in-environment!",
                    DFSCH_PRIMITIVE_REF(set_in_environment));
  dfsch_define_cstr(env, "unset-from-environment!",
                    DFSCH_PRIMITIVE_REF(unset_from_environment));
  dfsch_define_cstr(env, "define-in-environment!",
                    DFSCH_PRIMITIVE_REF(define_in_environment));
  dfsch_define_cstr(env, "get-variables",
                    DFSCH_PRIMITIVE_REF(get_variables));
  dfsch_define_cstr(env, "load-into-environment!",
                    DFSCH_PRIMITIVE_REF(load_into_environment));
  dfsch_define_cstr(env, "make-environment",
                    DFSCH_PRIMITIVE_REF(make_environment));
  dfsch_define_cstr(env, "make-empty-environment",
                    DFSCH_PRIMITIVE_REF(make_empty_environment));
  dfsch_define_cstr(env, "make-default-environment",
                    DFSCH_PRIMITIVE_REF(make_default_environment));
}
void dfsch_print_trace_buffer ()
Definition at line 53 of file introspect.c.
References dfsch__tracepoint_t::data, dfsch__get_thread_info(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_get_list_annotation(), dfsch_object_2_string(), DFSCH_TRACEPOINT_KIND_APPLY, DFSCH_TRACEPOINT_KIND_EVAL, DFSCH_TRACEPOINT_KIND_INVALID, DFSCH_TYPE_OF, dfsch__tracepoint_t::flags, dfsch__thread_info_t::trace_buffer, dfsch__thread_info_t::trace_depth, and dfsch__thread_info_t::trace_ptr.
Referenced by dfsch_signal().
{
  int i;
  dfsch__thread_info_t* ti = dfsch__get_thread_info();
  for (i = 0; i <= ti->trace_depth; i++){
    if (i == ti->trace_ptr){
      fprintf(stderr, "> ");
    } else {
      fprintf(stderr, "  ");
    }
    switch (ti->trace_buffer[i].flags & 0xff){
    case DFSCH_TRACEPOINT_KIND_INVALID:
      fprintf(stderr, "0x00000000\n");
      break;
    case DFSCH_TRACEPOINT_KIND_APPLY:
      fprintf(stderr, "0x%08x %p (%s) %p (%s)\n",
              ti->trace_buffer[i].flags,
              ti->trace_buffer[i].data.apply.proc,
              DFSCH_TYPE_OF(ti->trace_buffer[i].data.apply.proc)->name,
              ti->trace_buffer[i].data.apply.args,
              DFSCH_TYPE_OF(ti->trace_buffer[i].data.apply.args)->name);
      fprintf(stderr, "       %s\n     %s\n",
              dfsch_object_2_string(ti->trace_buffer[i].data.apply.proc,
                                    10, 1),
              dfsch_object_2_string(ti->trace_buffer[i].data.apply.args,
                                    10, 1));
      break;
    case DFSCH_TRACEPOINT_KIND_EVAL:
      {
        dfsch_object_t* annot =
          dfsch_get_list_annotation(ti->trace_buffer[i].data.eval.expr);
        fprintf(stderr, "0x%08x %p (%s) %p (%s)\n",
                ti->trace_buffer[i].flags,
                ti->trace_buffer[i].data.eval.expr,
                DFSCH_TYPE_OF(ti->trace_buffer[i].data.eval.expr)->name,
                ti->trace_buffer[i].data.eval.env,
                DFSCH_TYPE_OF(ti->trace_buffer[i].data.eval.env)->name);
        fprintf(stderr, "     %s\n",
                dfsch_object_2_string(ti->trace_buffer[i].data.apply.proc,
                                      10, 1));
        if (annot){
          fprintf(stderr, "       @ %s:%s\n",
                  dfsch_object_2_string(DFSCH_FAST_CAR(annot), 2, 0),
                  dfsch_object_2_string(DFSCH_FAST_CDR(annot), 1, 0));
        }
      }
      break;
    }
  }
}