dfsch: dfsch/load.h File Reference
dfsch/load.h File Reference
#include <dfsch/dfsch.h>
#include <stdio.h>
Functions
dfsch_object_t * dfsch_load (dfsch_object_t *env, char *name, dfsch_object_t *path_list)
dfsch_object_t * dfsch_load_extend_path (dfsch_object_t *ctx, char *dir)
dfsch_object_t * dfsch_load_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_load_scm (dfsch_object_t *ctx, char *scm_name)
dfsch_object_t * dfsch_load_scm_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_load_so (dfsch_object_t *ctx, char *so_name, char *sym_name)
dfsch_object_t * dfsch_load_so_register (dfsch_object_t *ctx)
void dfsch_provide (dfsch_object_t *env, char *name)
dfsch_object_t * dfsch_read_scm (char *scm_name, dfsch_object_t *eval_env)
dfsch_object_t * dfsch_read_scm_fd (int f, char *name, dfsch_object_t *eval_env)
dfsch_object_t * dfsch_read_scm_stream (FILE *f, char *name, dfsch_object_t *eval_env)
dfsch_object_t * dfsch_require (dfsch_object_t *env, char *name, dfsch_object_t *path_list)
Function Documentation
dfsch_object_t* dfsch_load (dfsch_object_t * env, char * name, dfsch_object_t * path_list)
Load given module (as by require, but unconditionally)
Definition at line 162 of file load.c.
References dfsch_car(), dfsch_cdr(), dfsch_env_get_cstr(), dfsch_error(), dfsch_load_scm(), dfsch_load_so(), dfsch_make_string_cstr(), dfsch_pair_p(), dfsch_string_to_cstr(), get_module_symbol(), my_scandir(), builtin_module_t::register_proc, sl_append, sl_create, sl_value, and stracat.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), and dfsch_require().
{
  struct stat st;
  dfsch_object_t* path;
  char *pathpart;
  char *fname;
  str_list_t* l;
  int i;
  for (i = 0; i < sizeof(builtin_modules) / sizeof(builtin_module_t); i++){
    if (strcmp(builtin_modules[i].name, name) == 0){
      builtin_modules[i].register_proc(env);
      return NULL;
    }
  }
  if (path_list){
    path = path_list;
  } else {
    path = dfsch_env_get_cstr(env, "load:*path*");
    if (path)
      path = dfsch_car(path);
  }
  while (dfsch_pair_p(path)){
    l = sl_create();
    sl_append(l, dfsch_string_to_cstr(dfsch_car(path)));
    sl_append(l, "/");
    sl_append(l, name);
    pathpart = sl_value(l);
    if (stat(pathpart, &st) == 0){
      if (S_ISREG(st.st_mode) || S_ISLNK(st.st_mode)){
        if (strcmp(".so", pathpart+strlen(pathpart)-3) == 0){
          return dfsch_load_so(env, pathpart, get_module_symbol(name));
        } else {
          return dfsch_load_scm(env, pathpart);
        }
      }
      if (S_ISDIR(st.st_mode)){
        char** list = my_scandir(pathpart);
        while(*list){
          l = sl_create();
          sl_append(l, pathpart);
          sl_append(l, "/");
          sl_append(l, *list);
          if (strcmp(".so", (*list)+strlen(*list)-3) == 0){
            dfsch_load_so(env, fname, get_module_symbol(name));
          } else {
            dfsch_load_scm(env, fname);
          }
          list++;
        }
        return NULL;
      }
    }
    fname = stracat(pathpart, ".scm");
    if (stat(fname, &st) == 0 && (S_ISREG(st.st_mode) || S_ISLNK(st.st_mode))){
      return dfsch_load_scm(env, fname);
    }
    fname = stracat(pathpart, ".so");
    if (stat(fname, &st) == 0 && (S_ISREG(st.st_mode) || S_ISLNK(st.st_mode))){
      return dfsch_load_so(env, fname, get_module_symbol(name));
    }
    path = dfsch_cdr(path);
  }
  dfsch_error("Module not found", dfsch_make_string_cstr(name));
}
dfsch_object_t* dfsch_load_extend_path (dfsch_object_t * ctx, char * dir)
Append directory to load:path
Definition at line 279 of file load.c.
References dfsch_append(), dfsch_car(), dfsch_define_cstr(), dfsch_env_get_cstr(), dfsch_list(), dfsch_make_string_cstr(), and dfsch_set_cstr().
Referenced by main().
{
  dfsch_object_t* path = dfsch_env_get_cstr(ctx, "load:*path*");
  if (path){
    dfsch_set_cstr(ctx, "load:*path*",
                   dfsch_append(dfsch_list(2,
                                           dfsch_car(path),
                                           dfsch_list(1,
                                                      dfsch_make_string_cstr(dir)))));
  }else{
    dfsch_define_cstr(ctx, "load:*path*",
                     dfsch_list(1, dfsch_make_string_cstr(dir)));
  }
}
dfsch_object_t* dfsch_load_register (dfsch_object_t * ctx)
Register this module.
Definition at line 448 of file load.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_list(), dfsch_make_primitive(), dfsch_make_string_cstr(), load_scm(), and native_read_scm().
Referenced by main().
{
  dfsch_define_cstr(ctx, "load:*path*",
                    dfsch_list(3,
                               dfsch_make_string_cstr("."),
                               dfsch_make_string_cstr(DFSCH_LIB_SCM_DIR),
                               dfsch_make_string_cstr(DFSCH_LIB_SO_DIR)));
  dfsch_define_cstr(ctx, "load:*modules*", NULL);
  dfsch_define_cstr(ctx, "load:scm!",  DFSCH_FORM_REF(load_scm));
  dfsch_define_cstr(ctx, "load:read-scm",
                    dfsch_make_primitive(native_read_scm,ctx));
  dfsch_define_cstr(ctx, "load:so!", DFSCH_FORM_REF(load_so));
  dfsch_define_cstr(ctx, "load!", DFSCH_FORM_REF(load));
  dfsch_define_cstr(ctx, "require", DFSCH_FORM_REF(require));
  dfsch_define_cstr(ctx, "provide", DFSCH_FORM_REF(provide));
  return NULL;
}
dfsch_object_t* dfsch_load_scm (dfsch_object_t * ctx, char * scm_name)
Load given source file (absolute path) into given environment.
Definition at line 92 of file load.c.
References dfsch_eval_proc(), and dfsch_read_scm().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_load(), DFSCH_PRIMITIVE_HEAD(), load_scm(), and main().
{
  return dfsch_eval_proc(dfsch_read_scm(fname, ctx), ctx);
}
dfsch_object_t* dfsch_load_scm_register (dfsch_object_t * ctx)
Register scheme related part of this module.
dfsch_object_t* dfsch_load_so (dfsch_object_t * ctx, char * so_name, char * sym_name)
Load given shared object module and register it into given context.
Definition at line 44 of file load.c.
References dfsch_error(), dfsch_make_string_cstr(), and DFSCH_SYM_TRUE.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and dfsch_load().
{
  void *handle;
  dfsch_object_t* (*entry)(dfsch_object_t*);
  char* err;
  err = dlerror();
  handle = dlopen(so_name, RTLD_NOW);
  err = dlerror();
  if (err){
    dfsch_error("dlopen() failed", dfsch_make_string_cstr(err));
  }
  entry = dlsym(handle, sym_name);
  err = dlerror();
  if (err){
    dfsch_error("dlsym() failed", dfsch_make_string_cstr(err));
  }
  entry(ctx);
  return DFSCH_SYM_TRUE;
}
dfsch_object_t* dfsch_load_so_register (dfsch_object_t * ctx)
Register shared object related part of this module.
void dfsch_provide (dfsch_object_t * env, char * name)
Provide given module (mark as loaded)
Definition at line 258 of file load.c.
References dfsch_car(), dfsch_cons(), dfsch_define_cstr(), dfsch_env_get_cstr(), dfsch_error(), dfsch_make_string_cstr(), and search_modules().
Referenced by DFSCH_DEFINE_FORM_IMPL(), dfsch_introspect_register(), dfsch_module_cmdopts_register(), dfsch_module_collections_register(), dfsch_module_console_register(), dfsch_module_extref_register(), dfsch_module_gcollect_register(), dfsch_module_inet_register(), dfsch_module_regex_register(), dfsch_module_sxml_register(), dfsch_module_threads_register(), dfsch_module_unix_register(), and dfsch_module_xml_register().
{
  dfsch_object_t* modules = dfsch_env_get_cstr(env, "load:*modules*");
  if (modules){
    modules = dfsch_car(modules);
  }
  if (search_modules(modules, name)){
    dfsch_error("Module already provided", dfsch_make_string_cstr(name));
  }
  /*
   * there should be define - module list is related to environment, but
   * this distinction is in most cases totally irrelevant, because modules
   * are mostly loaded into toplevel environment.
   */
  dfsch_define_cstr(env, "load:*modules*",
                    dfsch_cons(dfsch_make_string_cstr(name),
                               modules));
}
dfsch_object_t* dfsch_read_scm (char * scm_name, dfsch_object_t * eval_env)
Read scheme list from given file.
Definition at line 293 of file load.c.
References dfsch_operating_system_error(), and dfsch_read_scm_stream().
Referenced by dfsch_load_scm(), and native_read_scm().
{
  FILE* f = fopen(scm_name,"r");
  char buf[8193];
  import_ctx_t ictx;
  ssize_t r;
  int err=0;
  dfsch_object_t *obj;
  if (!f){
    dfsch_operating_system_error("fopen");
  }
  obj = dfsch_read_scm_stream(f, scm_name, eval_env);
  fclose(f);
  return obj;
}
dfsch_object_t* dfsch_read_scm_fd (int f, char * name, dfsch_object_t * eval_env)
Read scheme list from given file descriptor.
Definition at line 312 of file load.c.
References dfsch_error(), dfsch_make_string_cstr(), dfsch_operating_system_error(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_eval_env(), dfsch_parser_feed(), dfsch_parser_get_level(), DFSCH_PARSER_STOPPED, import_ctx_t::head, load_callback(), and parser.
{
  char buf[8193];
  import_ctx_t ictx;
  ssize_t r;
  int err=0;
  ictx.head = NULL;
  dfsch_parser_ctx_t *parser = dfsch_parser_create();
  dfsch_parser_callback(parser, load_callback, &ictx);
  dfsch_parser_eval_env(parser, eval_env);
  while (!err && (r = read(f, buf, 8192))>0){
    buf[r]=0;
    err = dfsch_parser_feed(parser,buf);
  }
  if (r<0){
    dfsch_operating_system_error("read");
  }
  if ((err && err != DFSCH_PARSER_STOPPED)
      || dfsch_parser_get_level(parser) != 0){
    if (name)
      dfsch_error("Syntax error", dfsch_make_string_cstr(name));
    else
      dfsch_error("Syntax error", NULL);
  }
  return ictx.head;
}
dfsch_object_t* dfsch_read_scm_stream (FILE * f, char * name, dfsch_object_t * eval_env)
Read scheme list from given stdio stream.
Definition at line 345 of file load.c.
References dfsch_cons(), dfsch_error(), dfsch_make_number_from_long(), dfsch_make_string_cstr(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_eval_env(), dfsch_parser_feed(), dfsch_parser_get_level(), dfsch_parser_set_source(), DFSCH_PARSER_STOPPED, import_ctx_t::head, load_callback(), and parser.
Referenced by dfsch_read_scm().
{
  char buf[8193];
  import_ctx_t ictx;
  ssize_t r;
  int err=0;
  int l=0;
  ictx.head = NULL;
  dfsch_parser_ctx_t *parser = dfsch_parser_create();
  dfsch_parser_callback(parser, load_callback, &ictx);
  dfsch_parser_set_source(parser, dfsch_make_string_cstr(name));
  dfsch_parser_eval_env(parser, eval_env);
  while (!err && (fgets(buf, 8192, f))){
    if (buf[strlen(buf)-1] == '\n')
      // I'm not interested in '\r' or any other weird ideas
      l++;
    err = dfsch_parser_feed(parser,buf);
  }
  if ((err && err != DFSCH_PARSER_STOPPED)
      || dfsch_parser_get_level(parser)!=0){
    if (name)
      dfsch_error("Syntax error",
                  dfsch_cons(dfsch_make_string_cstr(name),
                             dfsch_make_number_from_long(l)));
    else
      dfsch_error("Syntax error",
                  dfsch_cons(NULL,
                             dfsch_make_number_from_long(l)));
  }
  return ictx.head;
}
dfsch_object_t* dfsch_require (dfsch_object_t * env, char * name, dfsch_object_t * path_list)
Load given module if it is not provided yet
Definition at line 245 of file load.c.
References dfsch_car(), dfsch_env_get_cstr(), dfsch_load(), and search_modules().
Referenced by DFSCH_DEFINE_FORM_IMPL(), and main().
{
  dfsch_object_t* modules = dfsch_env_get_cstr(env, "load:*modules*");
  if (modules){
    modules = dfsch_car(modules);
  }
  if (search_modules(modules, name)){
    return NULL;
  }
  return dfsch_load(env, name, path_list);
}