dfsch: src/native_cxr.c File Reference
src/native_cxr.c File Reference
#include <dfsch/dfsch.h>
#include "internal.h"
Functions
void dfsch__native_cxr_register (dfsch_object_t *ctx)
static dfsch_object_t * native_cxr (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Variables
static char * cxr_table [][2]
Function Documentation
void dfsch__native_cxr_register (dfsch_object_t * ctx)
Definition at line 58 of file native_cxr.c.
References cxr_table, dfsch_define_cstr(), dfsch_make_primitive(), and native_cxr().
Referenced by dfsch__native_register().
{
  int i;
  for (i=0; i < (sizeof(cxr_table)/sizeof(cxr_table[0])); i++){
    dfsch_define_cstr(ctx, cxr_table[i][0],
                     dfsch_make_primitive(&native_cxr,cxr_table[i][1]));
  }
}
static dfsch_object_t* native_cxr (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 38 of file native_cxr.c.
References DFSCH_ARG_END, dfsch_car(), dfsch_cdr(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__native_cxr_register().
{
  dfsch_object_t* pair;
  char* action = (char*) baton;
  DFSCH_OBJECT_ARG(args, pair);
  DFSCH_ARG_END(args);
  while(*action){
    if ((*action) == 'a'){
      pair = dfsch_car(pair);
    } else {
      pair = dfsch_cdr(pair);
    }
    action++;
  }
  return pair;
}
Variable Documentation
char* cxr_table[][2] [static]
Definition at line 4 of file native_cxr.c.
Referenced by dfsch__native_cxr_register().