dfsch: dfsch/number.h File Reference
dfsch/number.h File Reference
#include <dfsch/dfsch.h>
Defines
#define DFSCH_BIGNUM_TYPE ((dfsch_type_t*)&dfsch_bignum_type)
#define DFSCH_DOUBLE_ARG(al, name) DFSCH_GENERIC_ARG(al, name, double, dfsch_number_to_double)
#define DFSCH_DOUBLE_ARG_OPT(al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, double, dfsch_number_to_double)
#define DFSCH_FIXNUM_TYPE ((dfsch_type_t*)&dfsch_fixnum_type)
#define DFSCH_FLONUM_TYPE ((dfsch_type_t*)&dfsch_flonum_type)
#define DFSCH_FRACNUM_TYPE ((dfsch_type_t*)&dfsch_fracnum_type)
#define DFSCH_INT64_ARG(al, name) DFSCH_GENERIC_ARG(al, name, long, dfsch_number_to_int64)
#define DFSCH_INT64_ARG_OPT(al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, long, dfsch_number_to_int64)
#define DFSCH_INTEGER_TYPE (&dfsch_integer_type)
#define DFSCH_LONG_ARG(al, name) DFSCH_GENERIC_ARG(al, name, long, dfsch_number_to_long)
#define DFSCH_LONG_ARG_OPT(al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, long, dfsch_number_to_long)
#define DFSCH_NUMBER_TYPE (&dfsch_number_type)
#define DFSCH_RATIONAL_TYPE (&dfsch_rational_type)
#define DFSCH_REAL_TYPE (&dfsch_real_type)
Typedefs
typedef dfsch_type_t dfsch_number_type_t
Functions
int dfsch_integer_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_make_number_from_double (double n)
dfsch_object_t * dfsch_make_number_from_int64 (int64_t n)
dfsch_object_t * dfsch_make_number_from_long (long n)
dfsch_object_t * dfsch_make_number_from_string (char *str, int base)
dfsch_object_t * dfsch_number_abs (dfsch_object_t *n)
dfsch_object_t * dfsch_number_add (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_denominator (dfsch_object_t *n)
dfsch_object_t * dfsch_number_div (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_div_i (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_even_p (dfsch_object_t *n)
int dfsch_number_exact_p (dfsch_object_t *obj)
char * dfsch_number_format (dfsch_object_t *n, int width, int digits)
dfsch_object_t * dfsch_number_gcd (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_gt (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_gte (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_lcm (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_logand (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_logior (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_lognot (dfsch_object_t *a)
dfsch_object_t * dfsch_number_logxor (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_lt (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_lte (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_mod (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_mul (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_neg (dfsch_object_t *n)
int dfsch_number_negative_p (dfsch_object_t *n)
dfsch_object_t * dfsch_number_numerator (dfsch_object_t *n)
int dfsch_number_odd_p (dfsch_object_t *n)
int dfsch_number_p (dfsch_object_t *obj)
int dfsch_number_positive_p (dfsch_object_t *n)
int dfsch_number_sign (dfsch_object_t *n)
dfsch_object_t * dfsch_number_sub (dfsch_object_t *a, dfsch_object_t *b)
double dfsch_number_to_double (dfsch_object_t *n)
dfsch_object_t * dfsch_number_to_inexact (dfsch_object_t *n)
int64_t dfsch_number_to_int64 (dfsch_object_t *n)
long dfsch_number_to_long (dfsch_object_t *n)
char * dfsch_number_to_string (dfsch_object_t *n, int base)
int dfsch_number_zero_p (dfsch_object_t *n)
int dfsch_rational_p (dfsch_object_t *obj)
int dfsch_real_p (dfsch_object_t *obj)
Variables
dfsch_number_type_t dfsch_bignum_type
dfsch_number_type_t dfsch_fixnum_type
dfsch_number_type_t dfsch_flonum_type
dfsch_number_type_t dfsch_fracnum_type
dfsch_type_t dfsch_integer_type
dfsch_type_t dfsch_number_type
dfsch_type_t dfsch_rational_type
dfsch_type_t dfsch_real_type
Detailed Description
Number datatype.
Definition in file number.h.
Define Documentation
#define DFSCH_BIGNUM_TYPE ((dfsch_type_t*)&dfsch_bignum_type)
Definition at line 52 of file number.h.
Referenced by dfsch__bignum_register(), dfsch_bignum_from_number(), DFSCH_DEFINE_PRIMITIVE(), dfsch_number_cmp(), dfsch_number_equal_p(), dfsch_number_even_p(), dfsch_number_neg(), dfsch_number_odd_p(), dfsch_number_sign(), dfsch_number_to_double(), dfsch_number_to_int64(), dfsch_number_to_long(), dfsch_number_to_string(), and make_bignum().
#define DFSCH_DOUBLE_ARG (al, name) DFSCH_GENERIC_ARG(al, name, double, dfsch_number_to_double)
Definition at line 143 of file number.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_DOUBLE_ARG_OPT (al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, double, dfsch_number_to_double)
Definition at line 145 of file number.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_FIXNUM_TYPE ((dfsch_type_t*)&dfsch_fixnum_type)
Definition at line 48 of file number.h.
Referenced by dfsch__number_native_register(), dfsch_bignum_from_number(), DFSCH_DEFINE_PRIMITIVE(), dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div_i(), dfsch_number_equal_p(), dfsch_number_even_p(), dfsch_number_logand(), dfsch_number_logior(), dfsch_number_lognot(), dfsch_number_logxor(), dfsch_number_mod(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_odd_p(), dfsch_number_sign(), dfsch_number_sub(), dfsch_number_to_double(), dfsch_number_to_int64(), dfsch_number_to_long(), dfsch_number_to_string(), and dfsch_random_get_number().
#define DFSCH_FLONUM_TYPE ((dfsch_type_t*)&dfsch_flonum_type)
Definition at line 50 of file number.h.
Referenced by dfsch__number_native_register(), dfsch_make_number_from_double(), dfsch_number_add(), dfsch_number_div(), dfsch_number_mul(), dfsch_number_sub(), and dfsch_number_to_double().
#define DFSCH_FRACNUM_TYPE ((dfsch_type_t*)&dfsch_fracnum_type)
Definition at line 54 of file number.h.
Referenced by dfsch__number_native_register(), dfsch_number_add(), dfsch_number_cmp(), dfsch_number_denominator(), dfsch_number_div(), dfsch_number_equal_p(), dfsch_number_even_p(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_numerator(), dfsch_number_odd_p(), dfsch_number_sign(), dfsch_number_sub(), dfsch_number_to_double(), and frac_cons().
#define DFSCH_INT64_ARG (al, name) DFSCH_GENERIC_ARG(al, name, long, dfsch_number_to_int64)
Definition at line 153 of file number.h.
Referenced by native_port_seek().
#define DFSCH_INT64_ARG_OPT (al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, long, dfsch_number_to_int64)
Definition at line 155 of file number.h.
#define DFSCH_INTEGER_TYPE (&dfsch_integer_type)
Definition at line 45 of file number.h.
#define DFSCH_LONG_ARG (al, name) DFSCH_GENERIC_ARG(al, name, long, dfsch_number_to_long)
Definition at line 148 of file number.h.
Referenced by command_sleep(), debug_invoke_restart(), DFSCH_DEFINE_PRIMITIVE(), native_chmod(), native_chown(), native_close(), native_creat(), native_decode_universal_time(), native_dup(), native_dup2(), native_encode_universal_time(), native_exit(), native_fchdir(), native_fchmod(), native_fchown(), native_fstat(), native_getpgid(), native_isatty(), native_kill(), native_killpg(), native_lseek(), native_make_weak_vector(), native_mkdir(), native_mkfifo(), native_nice(), native_port_read_buf(), native_raise(), native_read(), native_setegid(), native_seteuid(), native_setgid(), native_setpgid(), native_setuid(), native_sleep(), native_waitpid(), native_weak_vector_ref(), native_weak_vector_set(), and native_write().
#define DFSCH_LONG_ARG_OPT (al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, long, dfsch_number_to_long)
Definition at line 150 of file number.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), native_channel_create(), native_getsid(), and native_open().
#define DFSCH_NUMBER_TYPE (&dfsch_number_type)
Definition at line 39 of file number.h.
Referenced by dfsch__number_native_register(), and dfsch_number_p().
#define DFSCH_RATIONAL_TYPE (&dfsch_rational_type)
Definition at line 43 of file number.h.
Referenced by dfsch__number_native_register(), dfsch_number_exact_p(), and dfsch_rational_p().
#define DFSCH_REAL_TYPE (&dfsch_real_type)
Definition at line 41 of file number.h.
Referenced by dfsch__number_native_register(), and dfsch_real_p().
Typedef Documentation
typedef dfsch_type_t dfsch_number_type_t
Definition at line 36 of file number.h.
Function Documentation
int dfsch_integer_p (dfsch_object_t * obj)
Definition at line 454 of file number.c.
References DFSCH_INSTANCE_P.
Referenced by command_exit(), DFSCH_DEFINE_PRIMITIVE(), dfsch_number_denominator(), and dfsch_number_numerator().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_INTEGER_TYPE);
}
dfsch_object_t* dfsch_make_number_from_double (double n)
Makes number object from given floating-point number.
Definition at line 217 of file number.c.
References DFSCH_FLONUM_TYPE, dfsch_make_object(), and flonum_t::flonum.
Referenced by dfsch__number_native_register(), DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), dfsch_number_add(), dfsch_number_div(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_sub(), dfsch_number_to_inexact(), and dfsch_random_get_number().
{
  flonum_t *n;
  n = (flonum_t*)dfsch_make_object(DFSCH_FLONUM_TYPE);
  n->flonum = num;
  return (dfsch_object_t*)n;
}
dfsch_object_t* dfsch_make_number_from_int64 (int64_t n)
Makes number object from int64_t
Definition at line 232 of file number.c.
References DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, dfsch_make_bignum_int64(), and DFSCH_MAKE_FIXNUM.
Referenced by dfsch_make_number_from_string().
{
  if (num > DFSCH_FIXNUM_MAX || num < DFSCH_FIXNUM_MIN){
    return dfsch_make_bignum_int64(num);
  }
  return DFSCH_MAKE_FIXNUM(num);
}
dfsch_object_t* dfsch_make_number_from_long (long n)
Makes number object from given integer number.
Definition at line 225 of file number.c.
References DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, dfsch_make_bignum_int64(), and DFSCH_MAKE_FIXNUM.
Referenced by decoded_time_apply(), dfsch__system_register(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_item(), dfsch_number_div_i(), dfsch_number_mod(), dfsch_number_neg(), dfsch_read_scm_stream(), dfsch_string_ref(), dfsch_string_substring(), dfsch_string_substring_utf8(), dfsch_string_utf8_2_list(), dfsch_string_utf8_ref(), dfsch_vector_ref(), dfsch_vector_set(), dfsch_weak_vector_set(), dfsch_xml_signal_error(), errno_error(), native_clock(), native_creat(), native_dup(), native_dup2(), native_encode_universal_time(), native_fork(), native_get_universal_time(), native_getegid(), native_geteuid(), native_getgid(), native_getpgid(), native_getpgrp(), native_getpid(), native_getppid(), native_getsid(), native_gettimeofday(), native_getuid(), native_mode(), native_open(), native_pipe(), native_port_tell(), native_setpgrp(), native_setsid(), native_sig(), native_sleep(), native_wait(), native_waitpid(), native_weak_vector_length(), native_write(), parser_abort(), regex_substrings(), stat_apply(), tokenizer_process(), and wrapper_hash().
{
  if (num > DFSCH_FIXNUM_MAX || num < DFSCH_FIXNUM_MIN){
    return dfsch_make_bignum_int64((int64_t)num);
  }
  return DFSCH_MAKE_FIXNUM(num);
}
dfsch_object_t* dfsch_make_number_from_string (char * str, int base)
Creates number from external representation.
Definition at line 252 of file number.c.
References dfsch_error(), DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_make_number_from_int64(), dfsch_make_number_from_string(), dfsch_number_add(), dfsch_number_div(), dfsch_number_mul(), and dfsch_number_neg().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), and dispatch_atom().
{
  dfsch_object_t* n = DFSCH_MAKE_FIXNUM(0);
  int64_t sn = 0;
  int64_t on = 0;
  int base = obase;
  int d;
  int negative = 0;
  if (strchr(string, '.') != NULL ||
      (base == 10 && strpbrk(string, "eE") != NULL)){
    if (base != 10 && base != 0){
      dfsch_error("exception:non-supported-base-for-real-numbers",
                  DFSCH_MAKE_FIXNUM(base));
    }
    return dfsch_make_number_from_double(atof(string));
  }
  if (*string == '-'){
    string++;
    negative = 1;
  }
  if (base == 0){
    if (*string == '0'){
      string++;
      base = 8;
      if (*string == 'x' || *string == 'X'){
        string++;
        base = 16;
      }
    } else {
      base = 10;
    }
  }
  while (*string && *string != '/' &&
         sn <= DFSCH_FIXNUM_MAX && sn >= 0 && sn >= on){
    d = dig_val[*string];
    if (d >= base){
      dfsch_error("exception:invalid-digit", DFSCH_MAKE_FIXNUM(*string));
    }
    on = sn;
    sn *= base;
    sn += d;
    string++;
  }
  if (!*string){
    return dfsch_make_number_from_int64(negative ? -sn : sn);
  }
  if (*string == '/'){
    string++;
    if (strchr(string, '/') != NULL){
      dfsch_error("exception:too-many-slashes", NULL);
    }
    return dfsch_number_div(dfsch_make_number_from_int64(negative ? -sn : sn),
                            dfsch_make_number_from_string(string, obase));
  }
  n = DFSCH_MAKE_FIXNUM(on);
  string--;
  while (*string && *string != '/'){
    d = dig_val[*string];
    if (d >= base){
      dfsch_error("exception:invalid-digit", DFSCH_MAKE_FIXNUM(*string));
    }
    n = dfsch_number_mul(n, DFSCH_MAKE_FIXNUM(base));
    n = dfsch_number_add(n, DFSCH_MAKE_FIXNUM(d));
    string++;
  }
  if (*string == '/'){
    string++;
    if (strchr(string, '/') != NULL){
      dfsch_error("exception:too-many-slashes", NULL);
    }
    n = dfsch_number_div(n,
                         dfsch_make_number_from_string(string+1, obase));
  }
  if (negative){
    return dfsch_number_neg(n);
  } else {
    return n;
  }
}
dfsch_object_t* dfsch_number_abs (dfsch_object_t * n)
Absolute value
Definition at line 682 of file number.c.
References dfsch_number_neg(), and dfsch_number_negative_p().
Referenced by frac_cons().
{
  if (dfsch_number_negative_p(n)){
    return dfsch_number_neg(n);
  } else {
    return n;
  }
}
dfsch_object_t* dfsch_number_add (dfsch_object_t * a, dfsch_object_t * b)
Add arguments.
Definition at line 596 of file number.c.
References dfsch_bignum_add(), dfsch_bignum_from_number(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_add(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), dfsch_number_add(), and dfsch_number_mod_inv().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a)== DFSCH_FIXNUM_TYPE){
      long an = DFSCH_FIXNUM_REF(a)<<2;
      long bn = DFSCH_FIXNUM_REF(b)<<2;
      long x = an + bn;
      if ((an^x) >= 0 || (bn^x) >= 0) {
        return DFSCH_MAKE_FIXNUM(x>>2);
    }
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    return dfsch_make_number_from_double
      (dfsch_number_to_double((dfsch_object_t*) a) +
       dfsch_number_to_double((dfsch_object_t*) b));
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_add(dfsch_number_mul(dfsch_number_numerator(a),
                                                  dfsch_number_denominator(b)),
                                 dfsch_number_mul(dfsch_number_numerator(b),
                                                  dfsch_number_denominator(a))),
                c);
  }
  return dfsch_bignum_to_number(dfsch_bignum_add(dfsch_bignum_from_number(a),
                                                 dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_denominator (dfsch_object_t * n)
Definition at line 207 of file number.c.
References dfsch_error(), DFSCH_FRACNUM_TYPE, dfsch_integer_p(), DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_mul(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return ((fracnum_t*)n)->denom;
  }
  if (dfsch_integer_p(n)){
    return DFSCH_MAKE_FIXNUM(1);
  }
  dfsch_error("exception:not-a-rational-number", n);
}
dfsch_object_t* dfsch_number_div (dfsch_object_t * a, dfsch_object_t * b)
Divide arguments
Definition at line 736 of file number.c.
References dfsch_error(), DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_make_number_from_string().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    double an = dfsch_number_to_double((dfsch_object_t*) a);
    double bn = dfsch_number_to_double((dfsch_object_t*) b);
    if (bn == 0.0)
      dfsch_error("exception:division-by-zero", NULL);
    return dfsch_make_number_from_double(an / bn);
  }
  if (b == DFSCH_MAKE_FIXNUM(0)){
      dfsch_error("exception:division-by-zero", NULL);
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_mul(dfsch_number_numerator(a),
                                 dfsch_number_denominator(b)),
                dfsch_number_mul(dfsch_number_denominator(a),
                                 dfsch_number_numerator(b)));
  }
  return frac_cons(a, b);
}
dfsch_object_t* dfsch_number_div_i (dfsch_object_t * a, dfsch_object_t * b)
Integer division
Definition at line 768 of file number.c.
References dfsch_bignum_div(), dfsch_bignum_from_number(), dfsch_bignum_to_number(), dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_long(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_lcm(), dfsch_number_mod_inv(), and frac_cons().
{
  dfsch_bignum_t* r;
  if (b == DFSCH_MAKE_FIXNUM(0)){
      dfsch_error("exception:division-by-zero", NULL);
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    long an = DFSCH_FIXNUM_REF(a);
    long bn = DFSCH_FIXNUM_REF(b);
    return dfsch_make_number_from_long(an / bn);
  }
  dfsch_bignum_div(dfsch_bignum_from_number(a),
                   dfsch_bignum_from_number(b),
                   &r, NULL);
  return dfsch_bignum_to_number(r);
}
int dfsch_number_even_p (dfsch_object_t * n)
Definition at line 564 of file number.c.
References dfsch_bignum_even_p(), DFSCH_BIGNUM_TYPE, dfsch_bool(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return (DFSCH_FIXNUM_REF(n) & 0x01 == 0);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
      return dfsch_bignum_even_p(n);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return 0; /* proper fracnum cannot be integer */
  } else {
    double nn = dfsch_number_to_double(n);
    nn /= 2.0;
    return dfsch_bool(nn == round(nn));
  }
}
int dfsch_number_exact_p (dfsch_object_t * obj)
Definition at line 457 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_RATIONAL_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_RATIONAL_TYPE);
}
char* dfsch_number_format (dfsch_object_t * n, int width, int digits)
Definition at line 440 of file number.c.
References dfsch_number_to_double(), and dfsch_saprintf().
Referenced by dfsch_format().
{
  double num = dfsch_number_to_double(n);
  return dfsch_saprintf("%*.*f", width, digits, num);
}
dfsch_object_t* dfsch_number_gcd (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 813 of file number.c.
References dfsch_number_lt(), dfsch_number_mod(), and dfsch_number_sign().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_lcm(), and frac_cons().
{
  dfsch_object_t* t;
  if (dfsch_number_lt(a, b)){
    t = a;
    a = b;
    b = t;
  }
  while (dfsch_number_sign(b) != 0){
    a = dfsch_number_mod(a, b);
    if (dfsch_number_lt(a, b)){
      t = a;
      a = b;
      b = t;
    }
  }
  return a;
}
int dfsch_number_gt (dfsch_object_t * a, dfsch_object_t * b)
Greater than operator
Definition at line 523 of file number.c.
References dfsch_number_cmp().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_number_cmp(a, b) > 0;
}
int dfsch_number_gte (dfsch_object_t * a, dfsch_object_t * b)
Greater than or equal operator
Definition at line 529 of file number.c.
References dfsch_number_cmp().
{
  return dfsch_number_cmp(a, b) >= 0;
}
dfsch_object_t* dfsch_number_lcm (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 865 of file number.c.
References dfsch_number_div_i(), dfsch_number_gcd(), and dfsch_number_mul().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_number_div_i(dfsch_number_mul(a, b),
                            dfsch_number_gcd(a, b));
}
dfsch_object_t* dfsch_number_logand (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 871 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_logand(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_REF(a) & DFSCH_FIXNUM_REF(b));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_logand(dfsch_bignum_from_number(a),
                                               dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_logior (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 880 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_logior(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_REF(a) | DFSCH_FIXNUM_REF(b));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_logior(dfsch_bignum_from_number(a),
                                               dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_lognot (dfsch_object_t * a)
Definition at line 898 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_lognot(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(-DFSCH_FIXNUM_REF(a));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_lognot(dfsch_bignum_from_number(a)));
}
dfsch_object_t* dfsch_number_logxor (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 889 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_logxor(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_REF(a) ^ DFSCH_FIXNUM_REF(b));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_logxor(dfsch_bignum_from_number(a),
                                               dfsch_bignum_from_number(b)));
}
int dfsch_number_lt (dfsch_object_t * a, dfsch_object_t * b)
Less than operator
Definition at line 520 of file number.c.
References dfsch_number_cmp().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_number_gcd().
{
  return dfsch_number_cmp(a, b) < 0;
}
int dfsch_number_lte (dfsch_object_t * a, dfsch_object_t * b)
Less than or equal operator
Definition at line 526 of file number.c.
References dfsch_number_cmp().
{
  return dfsch_number_cmp(a, b) <= 0;
}
dfsch_object_t* dfsch_number_mod (dfsch_object_t * a, dfsch_object_t * b)
Modulo
Definition at line 791 of file number.c.
References dfsch_bignum_div(), dfsch_bignum_from_number(), dfsch_bignum_to_number(), dfsch_error(), DFSCH_FIXNUM_TYPE, dfsch_make_number_from_long(), dfsch_number_to_long(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_gcd(), and dfsch_number_mod_inv().
{
  dfsch_bignum_t* r;
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    long an = dfsch_number_to_long((dfsch_object_t*) a);
    long bn = dfsch_number_to_long((dfsch_object_t*) b);
    if (bn == 0)
      dfsch_error("exception:division-by-zero", NULL);
    return dfsch_make_number_from_long(an % bn);
  }
  dfsch_bignum_div(dfsch_bignum_from_number(a),
                   dfsch_bignum_from_number(b),
                   NULL, &r);
  return dfsch_bignum_to_number(r);
}
dfsch_object_t* dfsch_number_mul (dfsch_object_t * a, dfsch_object_t * b)
Multiply arguments
Definition at line 691 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_mul(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_lcm(), dfsch_number_mod_inv(), dfsch_number_mul(), dfsch_number_sub(), and dfsch_random_get_number().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    long an = DFSCH_FIXNUM_REF(a)<<2;
    long bn = DFSCH_FIXNUM_REF(b);
    long x = an * bn;
    double xd = (double)an * (double)bn;
    if (x == xd){
      return DFSCH_MAKE_FIXNUM(x>>2);
    }else{
      double d = x > xd ? x - xd : xd - x;
      double p = xd >= 0 ? xd : -xd;
      if (32.0 * d <= p){
        return DFSCH_MAKE_FIXNUM(x>>2);
      }
    }
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    return dfsch_make_number_from_double
      (dfsch_number_to_double((dfsch_object_t*) a) *
       dfsch_number_to_double((dfsch_object_t*) b));
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_mul(dfsch_number_numerator(a),
                                 dfsch_number_numerator(b)),
                dfsch_number_mul(dfsch_number_denominator(b),
                                 dfsch_number_denominator(a)));
  }
  return dfsch_bignum_to_number(dfsch_bignum_mul(dfsch_bignum_from_number(a),
                                                 dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_neg (dfsch_object_t * n)
Additive inverse
Definition at line 670 of file number.c.
References dfsch_bignum_neg(), dfsch_bignum_to_number(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_make_number_from_double(), dfsch_make_number_from_long(), dfsch_number_neg(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by dfsch_make_number_from_string(), dfsch_number_abs(), dfsch_number_neg(), and frac_cons().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return dfsch_make_number_from_long(DFSCH_FIXNUM_REF(n));
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_number(dfsch_bignum_neg(n));
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return frac_cons(dfsch_number_neg(((fracnum_t*)n)->num),
                     ((fracnum_t*)n)->denom);
  } else {
    return dfsch_make_number_from_double(-dfsch_number_to_double(n));
  }
}
int dfsch_number_negative_p (dfsch_object_t * n)
Definition at line 555 of file number.c.
References dfsch_number_sign().
Referenced by dfsch_number_abs(), dfsch_number_mod_inv(), and frac_cons().
{
  return dfsch_number_sign(n) < 0;
}
dfsch_object_t* dfsch_number_numerator (dfsch_object_t * n)
Definition at line 198 of file number.c.
References dfsch_error(), DFSCH_FRACNUM_TYPE, dfsch_integer_p(), and DFSCH_TYPE_OF.
Referenced by dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_mul(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return ((fracnum_t*)n)->num;
  }
  if (dfsch_integer_p(n)){
    return n;
  }
  dfsch_error("exception:not-a-rational-number", n);
}
int dfsch_number_odd_p (dfsch_object_t * n)
Definition at line 577 of file number.c.
References dfsch_bignum_even_p(), DFSCH_BIGNUM_TYPE, dfsch_bool(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return (DFSCH_FIXNUM_REF(n) & 0x01 == 1);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
      return !dfsch_bignum_even_p(n);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return 0; /* proper fracnum cannot be integer */
  } else {
    double nn = dfsch_number_to_double(n);
    nn = (nn + 1.0) /2.0;
    return dfsch_bool(nn == round(nn));
  }
}
int dfsch_number_p (dfsch_object_t * obj)
Is OBJ a a number?
Definition at line 445 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_NUMBER_TYPE.
{
  return DFSCH_INSTANCE_P(obj, DFSCH_NUMBER_TYPE);
}
int dfsch_number_positive_p (dfsch_object_t * n)
Definition at line 558 of file number.c.
References dfsch_number_sign().
{
  return dfsch_number_sign(n) > 0;
}
int dfsch_number_sign (dfsch_object_t * n)
Definition at line 533 of file number.c.
References dfsch_bignum_sign(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_sign(), dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_gcd(), dfsch_number_negative_p(), dfsch_number_positive_p(), dfsch_number_sign(), and dfsch_number_zero_p().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    if (DFSCH_FIXNUM_REF(n) == 0){
      return 0;
    } else {
      return (DFSCH_FIXNUM_REF(n) < 0) ? - 1 : 1;
    }
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_sign(n);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return dfsch_number_sign(((fracnum_t*)n)->num);
  } else {
    double nn = dfsch_number_to_double(n);
    if (nn == 0.0){
      return 0;
    } else {
      return (DFSCH_FIXNUM_REF(n) < 0) ? - 1 : 1;
    }
  }
}
dfsch_object_t* dfsch_number_sub (dfsch_object_t * a, dfsch_object_t * b)
Substract arguments.
Definition at line 634 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_sub(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_sub(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_mod_inv(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a)== DFSCH_FIXNUM_TYPE){
    long an = DFSCH_FIXNUM_REF(a)<<2;
    long bn = DFSCH_FIXNUM_REF(b)<<2;
    long x = an - bn;
    if ((an^x) >= 0 || (~bn^x) >= 0)
      return DFSCH_MAKE_FIXNUM(x>>2);
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    return dfsch_make_number_from_double
      (dfsch_number_to_double((dfsch_object_t*) a) -
       dfsch_number_to_double((dfsch_object_t*) b));
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_sub(dfsch_number_mul(dfsch_number_numerator(a),
                                                  dfsch_number_denominator(b)),
                                 dfsch_number_mul(dfsch_number_numerator(b),
                                                  dfsch_number_denominator(a))),
                c);
  }
  return dfsch_bignum_to_number(dfsch_bignum_sub(dfsch_bignum_from_number(a),
                                                 dfsch_bignum_from_number(b)));
}
double dfsch_number_to_double (dfsch_object_t * n)
Returns value of given number as double.
Definition at line 342 of file number.c.
References dfsch_bignum_to_double(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_equal_p(), dfsch_number_even_p(), dfsch_number_format(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_odd_p(), dfsch_number_sign(), dfsch_number_sub(), dfsch_number_to_double(), and dfsch_number_to_inexact().
{
  if (DFSCH_TYPE_OF(n)==DFSCH_FIXNUM_TYPE){
    return (double)DFSCH_FIXNUM_REF(n);
  }
  if (DFSCH_TYPE_OF(n)==DFSCH_FLONUM_TYPE){
    return ((flonum_t*)n)->flonum;
  }
  if (DFSCH_TYPE_OF(n)==DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_double((dfsch_bignum_t*)n);
  }
  if (DFSCH_TYPE_OF(n)==DFSCH_FRACNUM_TYPE){
    return dfsch_number_to_double(((fracnum_t*)n)->num) /
    dfsch_number_to_double(((fracnum_t*)n)->denom);
  }
  dfsch_error("exception:not-a-real-number", n);
}
dfsch_object_t* dfsch_number_to_inexact (dfsch_object_t * n)
Definition at line 358 of file number.c.
References dfsch_make_number_from_double(), and dfsch_number_to_double().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_make_number_from_double(dfsch_number_to_double(n));
}
int64_t dfsch_number_to_int64 (dfsch_object_t * n)
Returns value of given number as int64_t.
Definition at line 377 of file number.c.
References dfsch_bignum_to_int64(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, and DFSCH_TYPE_OF.
{
  int64_t r;
  if (DFSCH_TYPE_OF(n)==DFSCH_FIXNUM_TYPE){
    return DFSCH_FIXNUM_REF(n);
  } else if (DFSCH_TYPE_OF(n)==DFSCH_BIGNUM_TYPE){
    if (!dfsch_bignum_to_int64((dfsch_bignum_t*)n, &r)){
      dfsch_error("exception:value-too-large", NULL);
    }
    return r;
  }
  dfsch_error("exception:not-an-integer", n);
}
long dfsch_number_to_long (dfsch_object_t * n)
Returns value of given number as long.
Definition at line 361 of file number.c.
References dfsch_bignum_to_int64(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, and DFSCH_TYPE_OF.
Referenced by command_exit(), dfsch_format(), dfsch_list_2_string(), dfsch_list_2_string_utf8(), dfsch_number_mod(), and make_bignum_from_digits().
{
  int64_t r;
  if (DFSCH_TYPE_OF(n)==DFSCH_FIXNUM_TYPE){
    return DFSCH_FIXNUM_REF(n); /* we expect that fixnum fits in long */
  } else if (DFSCH_TYPE_OF(n)==DFSCH_BIGNUM_TYPE){
    if (!dfsch_bignum_to_int64((dfsch_bignum_t*)n, &r) ||
        r < LONG_MIN || r > LONG_MAX){
      dfsch_error("exception:value-too-large", NULL);
    }
    return r;
  }
  dfsch_error("exception:not-an-integer", n);
}
char* dfsch_number_to_string (dfsch_object_t * n, int base)
Definition at line 422 of file number.c.
References dfsch_bignum_to_string(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, dfsch_number_p(), dfsch_object_2_string(), DFSCH_TYPE_OF, and int_to_str().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_format(), format_r(), and fracnum_write().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return int_to_str(DFSCH_FIXNUM_REF(n), base);
  }
  if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_string((dfsch_bignum_t*)n, base);
  }
  if (!dfsch_number_p(n)){
    dfsch_error("Not a number", n);
  }
  if (base != 10){
    dfsch_error("Unsupported base for this numeric type", NULL);
  }
  return dfsch_object_2_string(n, 1, 1); /* fallback */
}
int dfsch_number_zero_p (dfsch_object_t * n)
Definition at line 561 of file number.c.
References dfsch_number_sign().
{
  return dfsch_number_sign(n) == 0;
}
int dfsch_rational_p (dfsch_object_t * obj)
Definition at line 451 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_RATIONAL_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_RATIONAL_TYPE);
}
int dfsch_real_p (dfsch_object_t * obj)
Definition at line 448 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_REAL_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_REAL_TYPE);
}
Variable Documentation
dfsch_number_type_t dfsch_bignum_type
Definition at line 89 of file bignum.c.
dfsch_number_type_t dfsch_fixnum_type
Definition at line 105 of file number.c.
dfsch_number_type_t dfsch_flonum_type
Definition at line 128 of file number.c.
dfsch_number_type_t dfsch_fracnum_type
Definition at line 159 of file number.c.
dfsch_type_t dfsch_integer_type
Definition at line 89 of file number.c.
dfsch_type_t dfsch_number_type
Definition at line 59 of file number.c.
dfsch_type_t dfsch_rational_type
Definition at line 79 of file number.c.
dfsch_type_t dfsch_real_type
Definition at line 69 of file number.c.