dfsch: src/number.c File Reference
src/number.c File Reference
#include <dfsch/number.h>
#include <dfsch/bignum.h>
#include <dfsch/strings.h>
#include "util.h"
#include "internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <math.h>
#include <errno.h>
#include <assert.h>
Data Structures
struct flonum_t
struct fracnum_t
Typedefs
typedef dfsch_object_t object_t
Functions
void dfsch__number_native_register (dfsch_object_t *ctx)
DFSCH_DEFINE_PRIMITIVE (lcm, NULL)
DFSCH_DEFINE_PRIMITIVE (mod_inv, NULL)
DFSCH_DEFINE_PRIMITIVE (gcd, NULL)
DFSCH_DEFINE_PRIMITIVE (string_2_number, NULL)
DFSCH_DEFINE_PRIMITIVE (number_2_string, NULL)
DFSCH_DEFINE_PRIMITIVE (truncate, NULL)
DFSCH_DEFINE_PRIMITIVE (ceiling, NULL)
DFSCH_DEFINE_PRIMITIVE (floor, NULL)
DFSCH_DEFINE_PRIMITIVE (round, NULL)
DFSCH_DEFINE_PRIMITIVE (min, NULL)
DFSCH_DEFINE_PRIMITIVE (max, NULL)
DFSCH_DEFINE_PRIMITIVE (odd_p, NULL)
DFSCH_DEFINE_PRIMITIVE (even_p, NULL)
DFSCH_DEFINE_PRIMITIVE (negative_p, NULL)
DFSCH_DEFINE_PRIMITIVE (positive_p, NULL)
DFSCH_DEFINE_PRIMITIVE (zero_p, NULL)
DFSCH_DEFINE_PRIMITIVE (expt, NULL)
DFSCH_DEFINE_PRIMITIVE (sqrt, NULL)
DFSCH_DEFINE_PRIMITIVE (atan, NULL)
DFSCH_DEFINE_PRIMITIVE (acos, NULL)
DFSCH_DEFINE_PRIMITIVE (asin, NULL)
DFSCH_DEFINE_PRIMITIVE (tan, NULL)
DFSCH_DEFINE_PRIMITIVE (cos, NULL)
DFSCH_DEFINE_PRIMITIVE (sin, NULL)
DFSCH_DEFINE_PRIMITIVE (log, NULL)
DFSCH_DEFINE_PRIMITIVE (exp, NULL)
DFSCH_DEFINE_PRIMITIVE (abs, NULL)
DFSCH_DEFINE_PRIMITIVE (lognot, NULL)
DFSCH_DEFINE_PRIMITIVE (logxor, NULL)
DFSCH_DEFINE_PRIMITIVE (logior, NULL)
DFSCH_DEFINE_PRIMITIVE (logand, NULL)
DFSCH_DEFINE_PRIMITIVE (gte, NULL)
DFSCH_DEFINE_PRIMITIVE (lte, NULL)
DFSCH_DEFINE_PRIMITIVE (gt, NULL)
DFSCH_DEFINE_PRIMITIVE (lt, NULL)
DFSCH_DEFINE_PRIMITIVE (number_equal, NULL)
DFSCH_DEFINE_PRIMITIVE (modulo, NULL)
DFSCH_DEFINE_PRIMITIVE (slash_i, NULL)
DFSCH_DEFINE_PRIMITIVE (slash, NULL)
DFSCH_DEFINE_PRIMITIVE (mult, NULL)
DFSCH_DEFINE_PRIMITIVE (minus, NULL)
DFSCH_DEFINE_PRIMITIVE (plus, NULL)
DFSCH_DEFINE_PRIMITIVE (exact_2_inexact, 0)
DFSCH_DEFINE_PRIMITIVE (inexact_p, NULL)
DFSCH_DEFINE_PRIMITIVE (exact_p, NULL)
DFSCH_DEFINE_PRIMITIVE (integer_p, NULL)
DFSCH_DEFINE_PRIMITIVE (rational_p, NULL)
DFSCH_DEFINE_PRIMITIVE (real_p, NULL)
DFSCH_DEFINE_PRIMITIVE (number_p, NULL)
int dfsch_integer_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_make_number_from_double (double num)
dfsch_object_t * dfsch_make_number_from_int64 (int64_t num)
dfsch_object_t * dfsch_make_number_from_long (long num)
dfsch_object_t * dfsch_make_number_from_string (char *string, int obase)
dfsch_object_t * dfsch_number_abs (dfsch_object_t *n)
dfsch_object_t * dfsch_number_add (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_cmp (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_denominator (dfsch_object_t *n)
dfsch_object_t * dfsch_number_div (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_div_i (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_equal_p (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_even_p (dfsch_object_t *n)
int dfsch_number_exact_p (dfsch_object_t *obj)
char * dfsch_number_format (dfsch_object_t *n, int width, int digits)
dfsch_object_t * dfsch_number_gcd (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_gt (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_gte (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_lcm (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_logand (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_logior (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_lognot (dfsch_object_t *a)
dfsch_object_t * dfsch_number_logxor (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_lt (dfsch_object_t *a, dfsch_object_t *b)
int dfsch_number_lte (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_mod (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_mod_inv (dfsch_object_t *n, dfsch_object_t *m)
dfsch_object_t * dfsch_number_mul (dfsch_object_t *a, dfsch_object_t *b)
dfsch_object_t * dfsch_number_neg (dfsch_object_t *n)
int dfsch_number_negative_p (dfsch_object_t *n)
dfsch_object_t * dfsch_number_numerator (dfsch_object_t *n)
int dfsch_number_odd_p (dfsch_object_t *n)
int dfsch_number_p (dfsch_object_t *obj)
int dfsch_number_positive_p (dfsch_object_t *n)
int dfsch_number_sign (dfsch_object_t *n)
dfsch_object_t * dfsch_number_sub (dfsch_object_t *a, dfsch_object_t *b)
double dfsch_number_to_double (dfsch_object_t *n)
dfsch_object_t * dfsch_number_to_inexact (dfsch_object_t *n)
int64_t dfsch_number_to_int64 (dfsch_object_t *n)
long dfsch_number_to_long (dfsch_object_t *n)
char * dfsch_number_to_string (dfsch_object_t *n, int base)
int dfsch_number_zero_p (dfsch_object_t *n)
int dfsch_rational_p (dfsch_object_t *obj)
int dfsch_real_p (dfsch_object_t *obj)
static size_t diffusion (size_t h)
static void fixnum_write (dfsch_object_t *n, dfsch_writer_state_t *state)
static int flonum_equal_p (flonum_t *a, flonum_t *b)
static uint32_t flonum_hash (flonum_t *n)
static void flonum_write (flonum_t *n, dfsch_writer_state_t *state)
static dfsch_object_t * frac_cons (dfsch_object_t *num, dfsch_object_t *denom)
static int fracnum_equal_p (fracnum_t *a, fracnum_t *b)
static uint32_t fracnum_hash (fracnum_t *n)
static void fracnum_write (fracnum_t *n, dfsch_writer_state_t *state)
static char * int_to_str (long i, int base)
Variables
dfsch_number_type_t dfsch_fixnum_type
dfsch_number_type_t dfsch_flonum_type
dfsch_number_type_t dfsch_fracnum_type
dfsch_type_t dfsch_integer_type
dfsch_type_t dfsch_number_type
dfsch_type_t dfsch_rational_type
dfsch_type_t dfsch_real_type
static int dig_val [128]
static char * digits = "0123456789abcdefghijklmnopqrstuvwxyz"
Typedef Documentation
typedef dfsch_object_t object_t
Definition at line 35 of file number.c.
Function Documentation
void dfsch__number_native_register (dfsch_object_t * ctx)
Definition at line 1432 of file number.c.
References dfsch_define_cstr(), DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), DFSCH_NUMBER_TYPE, DFSCH_PRIMITIVE_REF, DFSCH_RATIONAL_TYPE, and DFSCH_REAL_TYPE.
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<number>", DFSCH_NUMBER_TYPE);
  dfsch_define_cstr(ctx, "<real>", DFSCH_REAL_TYPE);
  dfsch_define_cstr(ctx, "<rational>", DFSCH_RATIONAL_TYPE);
  dfsch_define_cstr(ctx, "<integer>", DFSCH_INTEGER_TYPE);
  dfsch_define_cstr(ctx, "<fixnum>", DFSCH_FIXNUM_TYPE);
  dfsch_define_cstr(ctx, "<flonum>", DFSCH_FLONUM_TYPE);
  dfsch_define_cstr(ctx, "<fracnum>", DFSCH_FRACNUM_TYPE);
  dfsch_define_cstr(ctx, "+", DFSCH_PRIMITIVE_REF(plus));
  dfsch_define_cstr(ctx, "-", DFSCH_PRIMITIVE_REF(minus));
  dfsch_define_cstr(ctx, "*", DFSCH_PRIMITIVE_REF(mult));
  dfsch_define_cstr(ctx, "/", DFSCH_PRIMITIVE_REF(slash));
  dfsch_define_cstr(ctx, "/i", DFSCH_PRIMITIVE_REF(slash_i));
  dfsch_define_cstr(ctx, "%", DFSCH_PRIMITIVE_REF(modulo));
  dfsch_define_cstr(ctx, "=", DFSCH_PRIMITIVE_REF(number_equal));
  dfsch_define_cstr(ctx, "<", DFSCH_PRIMITIVE_REF(lt));
  dfsch_define_cstr(ctx, ">", DFSCH_PRIMITIVE_REF(gt));
  dfsch_define_cstr(ctx, "<=", DFSCH_PRIMITIVE_REF(lte));
  dfsch_define_cstr(ctx, ">=", DFSCH_PRIMITIVE_REF(gte));
  dfsch_define_cstr(ctx, "number?", DFSCH_PRIMITIVE_REF(number_p));
  dfsch_define_cstr(ctx, "real?", DFSCH_PRIMITIVE_REF(real_p));
  dfsch_define_cstr(ctx, "rational?", DFSCH_PRIMITIVE_REF(rational_p));
  dfsch_define_cstr(ctx, "integer?", DFSCH_PRIMITIVE_REF(integer_p));
  dfsch_define_cstr(ctx, "exact?", DFSCH_PRIMITIVE_REF(exact_p));
  dfsch_define_cstr(ctx, "inexact?", DFSCH_PRIMITIVE_REF(inexact_p));
  dfsch_define_cstr(ctx, "exact->inexact",
                    DFSCH_PRIMITIVE_REF(exact_2_inexact));
  dfsch_define_cstr(ctx, "pi",
                    dfsch_make_number_from_double(4*atan(1)));
  dfsch_define_cstr(ctx, "abs", DFSCH_PRIMITIVE_REF(abs));
  dfsch_define_cstr(ctx, "exp", DFSCH_PRIMITIVE_REF(exp));
  dfsch_define_cstr(ctx, "log", DFSCH_PRIMITIVE_REF(log));
  dfsch_define_cstr(ctx, "expt", DFSCH_PRIMITIVE_REF(expt));
  dfsch_define_cstr(ctx, "sin", DFSCH_PRIMITIVE_REF(sin));
  dfsch_define_cstr(ctx, "cos", DFSCH_PRIMITIVE_REF(cos));
  dfsch_define_cstr(ctx, "tan", DFSCH_PRIMITIVE_REF(tan));
  dfsch_define_cstr(ctx, "asin", DFSCH_PRIMITIVE_REF(asin));
  dfsch_define_cstr(ctx, "acos", DFSCH_PRIMITIVE_REF(acos));
  dfsch_define_cstr(ctx, "atan", DFSCH_PRIMITIVE_REF(atan));
  dfsch_define_cstr(ctx, "sqrt", DFSCH_PRIMITIVE_REF(sqrt));
  dfsch_define_cstr(ctx, "min", DFSCH_PRIMITIVE_REF(min));
  dfsch_define_cstr(ctx, "max", DFSCH_PRIMITIVE_REF(max));
  dfsch_define_cstr(ctx, "zero?", DFSCH_PRIMITIVE_REF(zero_p));
  dfsch_define_cstr(ctx, "negative?", DFSCH_PRIMITIVE_REF(negative_p));
  dfsch_define_cstr(ctx, "positive?", DFSCH_PRIMITIVE_REF(positive_p));
  dfsch_define_cstr(ctx, "even?", DFSCH_PRIMITIVE_REF(even_p));
  dfsch_define_cstr(ctx, "odd?", DFSCH_PRIMITIVE_REF(odd_p));
  dfsch_define_cstr(ctx, "round", DFSCH_PRIMITIVE_REF(round));
  dfsch_define_cstr(ctx, "floor", DFSCH_PRIMITIVE_REF(floor));
  dfsch_define_cstr(ctx, "ceiling", DFSCH_PRIMITIVE_REF(ceiling));
  dfsch_define_cstr(ctx, "truncate", DFSCH_PRIMITIVE_REF(truncate));
  dfsch_define_cstr(ctx, "number->string",
                   DFSCH_PRIMITIVE_REF(number_2_string));
  dfsch_define_cstr(ctx, "string->number",
                   DFSCH_PRIMITIVE_REF(string_2_number));
  dfsch_define_cstr(ctx, "most-positive-fixnum",
                    DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_MAX));
  dfsch_define_cstr(ctx, "most-negative-fixnum",
                    DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_MIN));
  dfsch_define_cstr(ctx, "gcd", DFSCH_PRIMITIVE_REF(gcd));
  dfsch_define_cstr(ctx, "mod-inv", DFSCH_PRIMITIVE_REF(mod_inv));
  dfsch_define_cstr(ctx, "lcm", DFSCH_PRIMITIVE_REF(lcm));
  dfsch_define_cstr(ctx, "logand", DFSCH_PRIMITIVE_REF(logand));
  dfsch_define_cstr(ctx, "logior", DFSCH_PRIMITIVE_REF(logior));
  dfsch_define_cstr(ctx, "logxor", DFSCH_PRIMITIVE_REF(logxor));
  dfsch_define_cstr(ctx, "lognot", DFSCH_PRIMITIVE_REF(lognot));
}
DFSCH_DEFINE_PRIMITIVE (lcm , NULL)
Definition at line 1420 of file number.c.
References DFSCH_ARG_END, dfsch_number_lcm(), and DFSCH_OBJECT_ARG.
{
  object_t* a;
  object_t* b;
  DFSCH_OBJECT_ARG(args, a);
  DFSCH_OBJECT_ARG(args, b);
  DFSCH_ARG_END(args);
  return dfsch_number_lcm(a, b);
}
DFSCH_DEFINE_PRIMITIVE (mod_inv , NULL)
Definition at line 1409 of file number.c.
References DFSCH_ARG_END, dfsch_number_mod_inv(), and DFSCH_OBJECT_ARG.
{
  object_t* a;
  object_t* b;
  DFSCH_OBJECT_ARG(args, a);
  DFSCH_OBJECT_ARG(args, b);
  DFSCH_ARG_END(args);
  return dfsch_number_mod_inv(a, b);
}
DFSCH_DEFINE_PRIMITIVE (gcd , NULL)
Definition at line 1398 of file number.c.
References DFSCH_ARG_END, dfsch_number_gcd(), and DFSCH_OBJECT_ARG.
{
  object_t* a;
  object_t* b;
  DFSCH_OBJECT_ARG(args, a);
  DFSCH_OBJECT_ARG(args, b);
  DFSCH_ARG_END(args);
  return dfsch_number_gcd(a, b);
}
DFSCH_DEFINE_PRIMITIVE (string_2_number , NULL)
Definition at line 1388 of file number.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG_OPT, dfsch_make_number_from_string(), and DFSCH_STRING_ARG.
{
  char *str;
  long base;
  DFSCH_STRING_ARG(args, str);
  DFSCH_LONG_ARG_OPT(args, base, 10);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_string(str, base);
}
DFSCH_DEFINE_PRIMITIVE (number_2_string , NULL)
Definition at line 1378 of file number.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG_OPT, dfsch_make_string_cstr(), dfsch_number_to_string(), and DFSCH_OBJECT_ARG.
{
  object_t *n;
  long base;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_LONG_ARG_OPT(args, base, 10);
  DFSCH_ARG_END(args);
  return dfsch_make_string_cstr(dfsch_number_to_string(n, base));
}
DFSCH_DEFINE_PRIMITIVE (truncate , NULL)
Definition at line 1371 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(trunc(z));
}
DFSCH_DEFINE_PRIMITIVE (ceiling , NULL)
Definition at line 1365 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(ceil(z));
}
DFSCH_DEFINE_PRIMITIVE (floor , NULL)
Definition at line 1359 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(floor(z));
}
DFSCH_DEFINE_PRIMITIVE (round , NULL)
Definition at line 1353 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(round(z));
}
DFSCH_DEFINE_PRIMITIVE (min , NULL)
Definition at line 1340 of file number.c.
References dfsch_number_gt(), and DFSCH_OBJECT_ARG.
{
  object_t *max;
  object_t *i;
  DFSCH_OBJECT_ARG(args, max);
  while (args){
    DFSCH_OBJECT_ARG(args, i);
    if (dfsch_number_gt(max, i))
      max = i;
  }
  return max;
}
DFSCH_DEFINE_PRIMITIVE (max , NULL)
Definition at line 1327 of file number.c.
References dfsch_number_lt(), and DFSCH_OBJECT_ARG.
{
  object_t *max;
  object_t *i;
  DFSCH_OBJECT_ARG(args, max);
  while (args){
    DFSCH_OBJECT_ARG(args, i);
    if (dfsch_number_lt(max, i))
      max = i;
  }
  return max;
}
DFSCH_DEFINE_PRIMITIVE (odd_p , NULL)
Definition at line 1320 of file number.c.
References DFSCH_ARG_END, dfsch_number_odd_p(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  return dfsch_number_odd_p(n);
}
DFSCH_DEFINE_PRIMITIVE (even_p , NULL)
Definition at line 1313 of file number.c.
References DFSCH_ARG_END, dfsch_number_even_p(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  return dfsch_number_even_p(n);
}
DFSCH_DEFINE_PRIMITIVE (negative_p , NULL)
Definition at line 1306 of file number.c.
References DFSCH_ARG_END, dfsch_number_sign(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  return dfsch_number_sign(n) < 0;
}
DFSCH_DEFINE_PRIMITIVE (positive_p , NULL)
Definition at line 1299 of file number.c.
References DFSCH_ARG_END, dfsch_number_sign(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  return dfsch_number_sign(n) > 0;
}
DFSCH_DEFINE_PRIMITIVE (zero_p , NULL)
Definition at line 1292 of file number.c.
References DFSCH_ARG_END, dfsch_number_sign(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  return dfsch_number_sign(n) == 0;
}
DFSCH_DEFINE_PRIMITIVE (expt , NULL)
Definition at line 1274 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, dfsch_error(), dfsch_list(), dfsch_make_number_from_double(), and dfsch_make_symbol().
{
  double z0, z1, v;
  DFSCH_DOUBLE_ARG(args, z0);
  DFSCH_DOUBLE_ARG(args, z1);
  DFSCH_ARG_END(args);
  errno = 0;
  v = pow(z0,z1);
  if (errno == EDOM) // XXX
    dfsch_error("Argument not in domain",
                dfsch_list(3,
                           dfsch_make_symbol("expt"),
                           dfsch_make_number_from_double(z0),
                           dfsch_make_number_from_double(z1)));
  return dfsch_make_number_from_double(v);
}
DFSCH_DEFINE_PRIMITIVE (sqrt , NULL)
Definition at line 1260 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, dfsch_error(), dfsch_list(), dfsch_make_number_from_double(), and dfsch_make_symbol().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  if (z < 0.0)
    dfsch_error("Argument not in domain",
                dfsch_list(2,
                           dfsch_make_symbol("sqrt"),
                           dfsch_make_number_from_double(z)));
  return dfsch_make_number_from_double(sqrt(z));
}
DFSCH_DEFINE_PRIMITIVE (atan , NULL)
Definition at line 1252 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, DFSCH_DOUBLE_ARG_OPT, and dfsch_make_number_from_double().
{
  double z0, z1;
  DFSCH_DOUBLE_ARG(args, z0);
  DFSCH_DOUBLE_ARG_OPT(args, z1, 1.0);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(atan(z0/z1));
}
DFSCH_DEFINE_PRIMITIVE (acos , NULL)
Definition at line 1238 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, dfsch_error(), dfsch_list(), dfsch_make_number_from_double(), and dfsch_make_symbol().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  if (z > 1.0 || z < -1.0)
    dfsch_error("Argument not in domain",
                dfsch_list(2,
                           dfsch_make_symbol("acos"),
                           dfsch_make_number_from_double(z)));
  return dfsch_make_number_from_double(acos(z));
}
DFSCH_DEFINE_PRIMITIVE (asin , NULL)
Definition at line 1224 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, dfsch_error(), dfsch_list(), dfsch_make_number_from_double(), and dfsch_make_symbol().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  if (z > 1.0 || z < -1.0)
    dfsch_error("Argument not in domain",
                dfsch_list(2,
                           dfsch_make_symbol("asin"),
                           dfsch_make_number_from_double(z)));
  return dfsch_make_number_from_double(asin(z));
}
DFSCH_DEFINE_PRIMITIVE (tan , NULL)
Definition at line 1217 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(tan(z));
}
DFSCH_DEFINE_PRIMITIVE (cos , NULL)
Definition at line 1211 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(cos(z));
}
DFSCH_DEFINE_PRIMITIVE (sin , NULL)
Definition at line 1205 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(sin(z));
}
DFSCH_DEFINE_PRIMITIVE (log , NULL)
Definition at line 1191 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG, dfsch_error(), dfsch_list(), dfsch_make_number_from_double(), and dfsch_make_symbol().
{
  double z;
  DFSCH_DOUBLE_ARG(args, z);
  DFSCH_ARG_END(args);
  if (z <= 0.0)
    dfsch_error("Argument not in domain",
                dfsch_list(2,
                           dfsch_make_symbol("log"),
                           dfsch_make_number_from_double(z)));
  return dfsch_make_number_from_double(log(z));
}
DFSCH_DEFINE_PRIMITIVE (exp , NULL)
Definition at line 1184 of file number.c.
References DFSCH_ARG_END, DFSCH_DOUBLE_ARG_OPT, and dfsch_make_number_from_double().
{
  double z;
  DFSCH_DOUBLE_ARG_OPT(args, z, 1.0);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(exp(z));
}
DFSCH_DEFINE_PRIMITIVE (abs , NULL)
Definition at line 1163 of file number.c.
References DFSCH_ARG_END, dfsch_bignum_abs(), dfsch_bignum_to_number(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_to_double(), DFSCH_OBJECT_ARG, and DFSCH_TYPE_OF.
{
  object_t *n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    if (DFSCH_FIXNUM_REF(n) >= 0){
      return n;
    } else {
      return DFSCH_MAKE_FIXNUM(-DFSCH_FIXNUM_REF(n));
    }
  }
  if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_number(dfsch_bignum_abs((dfsch_bignum_t*)n));
  }
  return dfsch_make_number_from_double(fabs(dfsch_number_to_double(n)));
}
DFSCH_DEFINE_PRIMITIVE (lognot , NULL)
Definition at line 1152 of file number.c.
References DFSCH_ARG_END, dfsch_number_lognot(), and DFSCH_OBJECT_ARG.
{
  object_t *n;
  DFSCH_OBJECT_ARG(args, n);
  DFSCH_ARG_END(args);
  return dfsch_number_lognot(n);
}
DFSCH_DEFINE_PRIMITIVE (logxor , NULL)
Definition at line 1142 of file number.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_MAKE_FIXNUM, dfsch_number_logxor(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  dfsch_object_t* s = DFSCH_MAKE_FIXNUM(0);
  while(DFSCH_PAIR_P(i)){
    s = dfsch_number_logxor(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (logior , NULL)
Definition at line 1132 of file number.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_MAKE_FIXNUM, dfsch_number_logior(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  dfsch_object_t* s = DFSCH_MAKE_FIXNUM(0);
  while(DFSCH_PAIR_P(i)){
    s = dfsch_number_logior(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (logand , NULL)
Definition at line 1121 of file number.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_MAKE_FIXNUM, dfsch_number_logand(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  dfsch_object_t* s = DFSCH_MAKE_FIXNUM(-1); /* all ones */
  while(DFSCH_PAIR_P(i)){
    s = dfsch_number_logand(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (gte , NULL)
Definition at line 1105 of file number.c.
References dfsch_number_cmp(), DFSCH_OBJECT_ARG, and DFSCH_SYM_TRUE.
{
  object_t *a;
  object_t *b;
  DFSCH_OBJECT_ARG(args, a);
  while (args){
    DFSCH_OBJECT_ARG(args, b);
    if (dfsch_number_cmp(a, b) < 0)
      return NULL;
    a = b;
  }
  return DFSCH_SYM_TRUE;
}
DFSCH_DEFINE_PRIMITIVE (lte , NULL)
Definition at line 1092 of file number.c.
References dfsch_number_cmp(), DFSCH_OBJECT_ARG, and DFSCH_SYM_TRUE.
{
  object_t *a;
  object_t *b;
  DFSCH_OBJECT_ARG(args, a);
  while (args){
    DFSCH_OBJECT_ARG(args, b);
    if (dfsch_number_cmp(a, b) > 0)
      return NULL;
    a = b;
  }
  return DFSCH_SYM_TRUE;
}
DFSCH_DEFINE_PRIMITIVE (gt , NULL)
Definition at line 1079 of file number.c.
References dfsch_number_cmp(), DFSCH_OBJECT_ARG, and DFSCH_SYM_TRUE.
{
  object_t *a;
  object_t *b;
  DFSCH_OBJECT_ARG(args, a);
  while (args){
    DFSCH_OBJECT_ARG(args, b);
    if (dfsch_number_cmp(a, b) <= 0)
      return NULL;
    a = b;
  }
  return DFSCH_SYM_TRUE;
}
DFSCH_DEFINE_PRIMITIVE (lt , NULL)
Definition at line 1066 of file number.c.
References dfsch_number_cmp(), DFSCH_OBJECT_ARG, and DFSCH_SYM_TRUE.
{
  object_t *a;
  object_t *b;
  DFSCH_OBJECT_ARG(args, a);
  while (args){
    DFSCH_OBJECT_ARG(args, b);
    if (dfsch_number_cmp(a, b) >= 0)
      return NULL;
    a = b;
  }
  return DFSCH_SYM_TRUE;
}
DFSCH_DEFINE_PRIMITIVE (number_equal , NULL)
Definition at line 1057 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_number_equal_p(), and DFSCH_OBJECT_ARG.
{
  object_t* z0, *z1;
  DFSCH_OBJECT_ARG(args, z0);
  DFSCH_OBJECT_ARG(args, z1);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_number_equal_p(z0,z1));
}
DFSCH_DEFINE_PRIMITIVE (modulo , NULL)
Definition at line 1037 of file number.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_number_from_long(), dfsch_number_div(), dfsch_number_mod(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  object_t* s;
  if (!DFSCH_PAIR_P(i))
    dfsch_error("Too few arguments",i);
  if (!DFSCH_FAST_CDR(i))
    return dfsch_number_div(dfsch_make_number_from_long(1),
                            DFSCH_FAST_CAR(i));
  s = DFSCH_FAST_CAR(i);
  i = DFSCH_FAST_CDR(i);
  while(DFSCH_PAIR_P(i)){
    s=dfsch_number_mod(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (slash_i , NULL)
Definition at line 1018 of file number.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_number_div_i(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  object_t* s;
  if (!DFSCH_PAIR_P(i))
    dfsch_error("Too few arguments",i);
  if (!DFSCH_FAST_CDR(i))
    dfsch_error("Too few arguments",i);
  s = DFSCH_FAST_CAR(i);
  i = DFSCH_FAST_CDR(i);
  while(DFSCH_PAIR_P(i)){
    s=dfsch_number_div_i(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (slash , NULL)
Definition at line 999 of file number.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_number_from_long(), dfsch_number_div(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  object_t* s;
  if (!DFSCH_PAIR_P(i))
    dfsch_error("Too few arguments",i);
  if (!DFSCH_FAST_CDR(i))
    return dfsch_number_div(dfsch_make_number_from_long(1),
                            DFSCH_FAST_CAR(i));
  s = DFSCH_FAST_CAR(i);
  i = DFSCH_FAST_CDR(i);
  while(DFSCH_PAIR_P(i)){
    s=dfsch_number_div(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (mult , NULL)
Definition at line 989 of file number.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_number_from_long(), dfsch_number_mul(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  object_t* s = dfsch_make_number_from_long(1);
  while(DFSCH_PAIR_P(i)){
    s = dfsch_number_mul(s,DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (minus , NULL)
Definition at line 972 of file number.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_number_from_long(), dfsch_number_sub(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  object_t* s;
  if (!DFSCH_PAIR_P(i))
    dfsch_error("Too few arguments",i);
  if (!DFSCH_FAST_CDR(i))
    return dfsch_number_sub(dfsch_make_number_from_long(0), DFSCH_FAST_CAR(i));
  s = DFSCH_FAST_CAR(i);
  i = DFSCH_FAST_CDR(i);
  while(DFSCH_PAIR_P(i)){
    s = dfsch_number_sub(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (plus , NULL)
Definition at line 962 of file number.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_make_number_from_long(), dfsch_number_add(), and DFSCH_PAIR_P.
{
  object_t* i = args;
  dfsch_object_t* s = dfsch_make_number_from_long(0);
  while(DFSCH_PAIR_P(i)){
    s = dfsch_number_add(s, DFSCH_FAST_CAR(i));
    i = DFSCH_FAST_CDR(i);
  }
  return s;
}
DFSCH_DEFINE_PRIMITIVE (exact_2_inexact , 0)
Definition at line 956 of file number.c.
References dfsch_number_to_inexact(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* n;
  DFSCH_OBJECT_ARG(args, n);
  return dfsch_number_to_inexact(n);
}
DFSCH_DEFINE_PRIMITIVE (inexact_p , NULL)
Definition at line 949 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_number_exact_p(), and DFSCH_OBJECT_ARG.
{
  object_t *obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(!dfsch_number_exact_p(obj));
}
DFSCH_DEFINE_PRIMITIVE (exact_p , NULL)
Definition at line 942 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_number_exact_p(), and DFSCH_OBJECT_ARG.
{
  object_t *obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_number_exact_p(obj));
}
DFSCH_DEFINE_PRIMITIVE (integer_p , NULL)
Definition at line 935 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_integer_p(), and DFSCH_OBJECT_ARG.
{
  object_t *obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_integer_p(obj));
}
DFSCH_DEFINE_PRIMITIVE (rational_p , NULL)
Definition at line 928 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), DFSCH_OBJECT_ARG, and dfsch_rational_p().
{
  object_t *obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_rational_p(obj));
}
DFSCH_DEFINE_PRIMITIVE (real_p , NULL)
Definition at line 921 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), DFSCH_OBJECT_ARG, and dfsch_real_p().
{
  object_t *obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_real_p(obj));
}
DFSCH_DEFINE_PRIMITIVE (number_p , NULL)
Definition at line 914 of file number.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_number_p(), and DFSCH_OBJECT_ARG.
{
  object_t *obj;
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_number_p(obj));
}
int dfsch_integer_p (dfsch_object_t * obj)
Definition at line 454 of file number.c.
References DFSCH_INSTANCE_P.
Referenced by command_exit(), DFSCH_DEFINE_PRIMITIVE(), dfsch_number_denominator(), and dfsch_number_numerator().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_INTEGER_TYPE);
}
dfsch_object_t* dfsch_make_number_from_double (double n)
Makes number object from given floating-point number.
Definition at line 217 of file number.c.
References DFSCH_FLONUM_TYPE, dfsch_make_object(), and flonum_t::flonum.
Referenced by dfsch__number_native_register(), DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), dfsch_number_add(), dfsch_number_div(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_sub(), dfsch_number_to_inexact(), and dfsch_random_get_number().
{
  flonum_t *n;
  n = (flonum_t*)dfsch_make_object(DFSCH_FLONUM_TYPE);
  n->flonum = num;
  return (dfsch_object_t*)n;
}
dfsch_object_t* dfsch_make_number_from_int64 (int64_t n)
Makes number object from int64_t
Definition at line 232 of file number.c.
References DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, dfsch_make_bignum_int64(), and DFSCH_MAKE_FIXNUM.
Referenced by dfsch_make_number_from_string().
{
  if (num > DFSCH_FIXNUM_MAX || num < DFSCH_FIXNUM_MIN){
    return dfsch_make_bignum_int64(num);
  }
  return DFSCH_MAKE_FIXNUM(num);
}
dfsch_object_t* dfsch_make_number_from_long (long n)
Makes number object from given integer number.
Definition at line 225 of file number.c.
References DFSCH_FIXNUM_MAX, DFSCH_FIXNUM_MIN, dfsch_make_bignum_int64(), and DFSCH_MAKE_FIXNUM.
Referenced by decoded_time_apply(), dfsch__system_register(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_item(), dfsch_number_div_i(), dfsch_number_mod(), dfsch_number_neg(), dfsch_read_scm_stream(), dfsch_string_ref(), dfsch_string_substring(), dfsch_string_substring_utf8(), dfsch_string_utf8_2_list(), dfsch_string_utf8_ref(), dfsch_vector_ref(), dfsch_vector_set(), dfsch_weak_vector_set(), dfsch_xml_signal_error(), errno_error(), native_clock(), native_creat(), native_dup(), native_dup2(), native_encode_universal_time(), native_fork(), native_get_universal_time(), native_getegid(), native_geteuid(), native_getgid(), native_getpgid(), native_getpgrp(), native_getpid(), native_getppid(), native_getsid(), native_gettimeofday(), native_getuid(), native_mode(), native_open(), native_pipe(), native_port_tell(), native_setpgrp(), native_setsid(), native_sig(), native_sleep(), native_wait(), native_waitpid(), native_weak_vector_length(), native_write(), parser_abort(), regex_substrings(), stat_apply(), tokenizer_process(), and wrapper_hash().
{
  if (num > DFSCH_FIXNUM_MAX || num < DFSCH_FIXNUM_MIN){
    return dfsch_make_bignum_int64((int64_t)num);
  }
  return DFSCH_MAKE_FIXNUM(num);
}
dfsch_object_t* dfsch_make_number_from_string (char * str, int base)
Creates number from external representation.
Definition at line 252 of file number.c.
References dfsch_error(), DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_make_number_from_int64(), dfsch_make_number_from_string(), dfsch_number_add(), dfsch_number_div(), dfsch_number_mul(), and dfsch_number_neg().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), and dispatch_atom().
{
  dfsch_object_t* n = DFSCH_MAKE_FIXNUM(0);
  int64_t sn = 0;
  int64_t on = 0;
  int base = obase;
  int d;
  int negative = 0;
  if (strchr(string, '.') != NULL ||
      (base == 10 && strpbrk(string, "eE") != NULL)){
    if (base != 10 && base != 0){
      dfsch_error("exception:non-supported-base-for-real-numbers",
                  DFSCH_MAKE_FIXNUM(base));
    }
    return dfsch_make_number_from_double(atof(string));
  }
  if (*string == '-'){
    string++;
    negative = 1;
  }
  if (base == 0){
    if (*string == '0'){
      string++;
      base = 8;
      if (*string == 'x' || *string == 'X'){
        string++;
        base = 16;
      }
    } else {
      base = 10;
    }
  }
  while (*string && *string != '/' &&
         sn <= DFSCH_FIXNUM_MAX && sn >= 0 && sn >= on){
    d = dig_val[*string];
    if (d >= base){
      dfsch_error("exception:invalid-digit", DFSCH_MAKE_FIXNUM(*string));
    }
    on = sn;
    sn *= base;
    sn += d;
    string++;
  }
  if (!*string){
    return dfsch_make_number_from_int64(negative ? -sn : sn);
  }
  if (*string == '/'){
    string++;
    if (strchr(string, '/') != NULL){
      dfsch_error("exception:too-many-slashes", NULL);
    }
    return dfsch_number_div(dfsch_make_number_from_int64(negative ? -sn : sn),
                            dfsch_make_number_from_string(string, obase));
  }
  n = DFSCH_MAKE_FIXNUM(on);
  string--;
  while (*string && *string != '/'){
    d = dig_val[*string];
    if (d >= base){
      dfsch_error("exception:invalid-digit", DFSCH_MAKE_FIXNUM(*string));
    }
    n = dfsch_number_mul(n, DFSCH_MAKE_FIXNUM(base));
    n = dfsch_number_add(n, DFSCH_MAKE_FIXNUM(d));
    string++;
  }
  if (*string == '/'){
    string++;
    if (strchr(string, '/') != NULL){
      dfsch_error("exception:too-many-slashes", NULL);
    }
    n = dfsch_number_div(n,
                         dfsch_make_number_from_string(string+1, obase));
  }
  if (negative){
    return dfsch_number_neg(n);
  } else {
    return n;
  }
}
dfsch_object_t* dfsch_number_abs (dfsch_object_t * n)
Absolute value
Definition at line 682 of file number.c.
References dfsch_number_neg(), and dfsch_number_negative_p().
Referenced by frac_cons().
{
  if (dfsch_number_negative_p(n)){
    return dfsch_number_neg(n);
  } else {
    return n;
  }
}
dfsch_object_t* dfsch_number_add (dfsch_object_t * a, dfsch_object_t * b)
Add arguments.
Definition at line 596 of file number.c.
References dfsch_bignum_add(), dfsch_bignum_from_number(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_add(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), dfsch_number_add(), and dfsch_number_mod_inv().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a)== DFSCH_FIXNUM_TYPE){
      long an = DFSCH_FIXNUM_REF(a)<<2;
      long bn = DFSCH_FIXNUM_REF(b)<<2;
      long x = an + bn;
      if ((an^x) >= 0 || (bn^x) >= 0) {
        return DFSCH_MAKE_FIXNUM(x>>2);
    }
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    return dfsch_make_number_from_double
      (dfsch_number_to_double((dfsch_object_t*) a) +
       dfsch_number_to_double((dfsch_object_t*) b));
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_add(dfsch_number_mul(dfsch_number_numerator(a),
                                                  dfsch_number_denominator(b)),
                                 dfsch_number_mul(dfsch_number_numerator(b),
                                                  dfsch_number_denominator(a))),
                c);
  }
  return dfsch_bignum_to_number(dfsch_bignum_add(dfsch_bignum_from_number(a),
                                                 dfsch_bignum_from_number(b)));
}
int dfsch_number_cmp (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 482 of file number.c.
References dfsch_bignum_cmp(), dfsch_bignum_from_number(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_gt(), dfsch_number_gte(), dfsch_number_lt(), and dfsch_number_lte().
{
  if (a == b) {
    return 0;
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b)){
    if (DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
      return DFSCH_FIXNUM_REF(a) < DFSCH_FIXNUM_REF(b) ? -1 : 1;
    }
    if (DFSCH_TYPE_OF(a) == DFSCH_BIGNUM_TYPE){
      return dfsch_bignum_cmp((dfsch_bignum_t*)a, (dfsch_bignum_t*)b);
    }
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    return dfsch_number_cmp(dfsch_number_mul(dfsch_number_numerator(a),
                                             dfsch_number_denominator(b)),
                            dfsch_number_mul(dfsch_number_numerator(b),
                                             dfsch_number_denominator(a)));
  }
  if ((DFSCH_TYPE_OF(a) == DFSCH_BIGNUM_TYPE &&
       DFSCH_TYPE_OF(b) == DFSCH_FIXNUM_TYPE) ||
      (DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE &&
       DFSCH_TYPE_OF(b) == DFSCH_BIGNUM_TYPE)){
    return dfsch_bignum_cmp(dfsch_bignum_from_number(a),
                            dfsch_bignum_from_number(b));
  }
  if (dfsch_number_to_double(a) == dfsch_number_to_double(b)){
    return 0;
  } else {
    return (dfsch_number_to_double(a) < dfsch_number_to_double(b)) ?
      -1 : 1;
  }
}
dfsch_object_t* dfsch_number_denominator (dfsch_object_t * n)
Definition at line 207 of file number.c.
References dfsch_error(), DFSCH_FRACNUM_TYPE, dfsch_integer_p(), DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_mul(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return ((fracnum_t*)n)->denom;
  }
  if (dfsch_integer_p(n)){
    return DFSCH_MAKE_FIXNUM(1);
  }
  dfsch_error("exception:not-a-rational-number", n);
}
dfsch_object_t* dfsch_number_div (dfsch_object_t * a, dfsch_object_t * b)
Divide arguments
Definition at line 736 of file number.c.
References dfsch_error(), DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_make_number_from_string().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    double an = dfsch_number_to_double((dfsch_object_t*) a);
    double bn = dfsch_number_to_double((dfsch_object_t*) b);
    if (bn == 0.0)
      dfsch_error("exception:division-by-zero", NULL);
    return dfsch_make_number_from_double(an / bn);
  }
  if (b == DFSCH_MAKE_FIXNUM(0)){
      dfsch_error("exception:division-by-zero", NULL);
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_mul(dfsch_number_numerator(a),
                                 dfsch_number_denominator(b)),
                dfsch_number_mul(dfsch_number_denominator(a),
                                 dfsch_number_numerator(b)));
  }
  return frac_cons(a, b);
}
dfsch_object_t* dfsch_number_div_i (dfsch_object_t * a, dfsch_object_t * b)
Integer division
Definition at line 768 of file number.c.
References dfsch_bignum_div(), dfsch_bignum_from_number(), dfsch_bignum_to_number(), dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_long(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_lcm(), dfsch_number_mod_inv(), and frac_cons().
{
  dfsch_bignum_t* r;
  if (b == DFSCH_MAKE_FIXNUM(0)){
      dfsch_error("exception:division-by-zero", NULL);
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    long an = DFSCH_FIXNUM_REF(a);
    long bn = DFSCH_FIXNUM_REF(b);
    return dfsch_make_number_from_long(an / bn);
  }
  dfsch_bignum_div(dfsch_bignum_from_number(a),
                   dfsch_bignum_from_number(b),
                   &r, NULL);
  return dfsch_bignum_to_number(r);
}
int dfsch_number_equal_p (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 462 of file number.c.
References dfsch_bignum_equal_p(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_eqv_p().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b)){
    if (DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
      return DFSCH_FIXNUM_REF(a) == DFSCH_FIXNUM_REF(b);
    }
    if (DFSCH_TYPE_OF(a) == DFSCH_BIGNUM_TYPE){
      return dfsch_bignum_equal_p((dfsch_bignum_t*)a,
                                  (dfsch_bignum_t*)b);
    }
    if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE){
      return dfsch_number_equal_p(((fracnum_t*)a)->num, ((fracnum_t*)a)->num) &&
        dfsch_number_equal_p(((fracnum_t*)a)->denom, ((fracnum_t*)a)->denom);
    }
  }
  return dfsch_number_to_double(a) == dfsch_number_to_double(b);
}
int dfsch_number_even_p (dfsch_object_t * n)
Definition at line 564 of file number.c.
References dfsch_bignum_even_p(), DFSCH_BIGNUM_TYPE, dfsch_bool(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return (DFSCH_FIXNUM_REF(n) & 0x01 == 0);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
      return dfsch_bignum_even_p(n);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return 0; /* proper fracnum cannot be integer */
  } else {
    double nn = dfsch_number_to_double(n);
    nn /= 2.0;
    return dfsch_bool(nn == round(nn));
  }
}
int dfsch_number_exact_p (dfsch_object_t * obj)
Definition at line 457 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_RATIONAL_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_RATIONAL_TYPE);
}
char* dfsch_number_format (dfsch_object_t * n, int width, int digits)
Definition at line 440 of file number.c.
References dfsch_number_to_double(), and dfsch_saprintf().
Referenced by dfsch_format().
{
  double num = dfsch_number_to_double(n);
  return dfsch_saprintf("%*.*f", width, digits, num);
}
dfsch_object_t* dfsch_number_gcd (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 813 of file number.c.
References dfsch_number_lt(), dfsch_number_mod(), and dfsch_number_sign().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_lcm(), and frac_cons().
{
  dfsch_object_t* t;
  if (dfsch_number_lt(a, b)){
    t = a;
    a = b;
    b = t;
  }
  while (dfsch_number_sign(b) != 0){
    a = dfsch_number_mod(a, b);
    if (dfsch_number_lt(a, b)){
      t = a;
      a = b;
      b = t;
    }
  }
  return a;
}
int dfsch_number_gt (dfsch_object_t * a, dfsch_object_t * b)
Greater than operator
Definition at line 523 of file number.c.
References dfsch_number_cmp().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_number_cmp(a, b) > 0;
}
int dfsch_number_gte (dfsch_object_t * a, dfsch_object_t * b)
Greater than or equal operator
Definition at line 529 of file number.c.
References dfsch_number_cmp().
{
  return dfsch_number_cmp(a, b) >= 0;
}
dfsch_object_t* dfsch_number_lcm (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 865 of file number.c.
References dfsch_number_div_i(), dfsch_number_gcd(), and dfsch_number_mul().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_number_div_i(dfsch_number_mul(a, b),
                            dfsch_number_gcd(a, b));
}
dfsch_object_t* dfsch_number_logand (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 871 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_logand(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_REF(a) & DFSCH_FIXNUM_REF(b));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_logand(dfsch_bignum_from_number(a),
                                               dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_logior (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 880 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_logior(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_REF(a) | DFSCH_FIXNUM_REF(b));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_logior(dfsch_bignum_from_number(a),
                                               dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_lognot (dfsch_object_t * a)
Definition at line 898 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_lognot(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(-DFSCH_FIXNUM_REF(a));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_lognot(dfsch_bignum_from_number(a)));
}
dfsch_object_t* dfsch_number_logxor (dfsch_object_t * a, dfsch_object_t * b)
Definition at line 889 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_logxor(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(DFSCH_FIXNUM_REF(a) ^ DFSCH_FIXNUM_REF(b));
  }
  return
    dfsch_bignum_to_number(dfsch_bignum_logxor(dfsch_bignum_from_number(a),
                                               dfsch_bignum_from_number(b)));
}
int dfsch_number_lt (dfsch_object_t * a, dfsch_object_t * b)
Less than operator
Definition at line 520 of file number.c.
References dfsch_number_cmp().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_number_gcd().
{
  return dfsch_number_cmp(a, b) < 0;
}
int dfsch_number_lte (dfsch_object_t * a, dfsch_object_t * b)
Less than or equal operator
Definition at line 526 of file number.c.
References dfsch_number_cmp().
{
  return dfsch_number_cmp(a, b) <= 0;
}
dfsch_object_t* dfsch_number_mod (dfsch_object_t * a, dfsch_object_t * b)
Modulo
Definition at line 791 of file number.c.
References dfsch_bignum_div(), dfsch_bignum_from_number(), dfsch_bignum_to_number(), dfsch_error(), DFSCH_FIXNUM_TYPE, dfsch_make_number_from_long(), dfsch_number_to_long(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_gcd(), and dfsch_number_mod_inv().
{
  dfsch_bignum_t* r;
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    long an = dfsch_number_to_long((dfsch_object_t*) a);
    long bn = dfsch_number_to_long((dfsch_object_t*) b);
    if (bn == 0)
      dfsch_error("exception:division-by-zero", NULL);
    return dfsch_make_number_from_long(an % bn);
  }
  dfsch_bignum_div(dfsch_bignum_from_number(a),
                   dfsch_bignum_from_number(b),
                   NULL, &r);
  return dfsch_bignum_to_number(r);
}
dfsch_object_t* dfsch_number_mod_inv (dfsch_object_t * n, dfsch_object_t * m)
Definition at line 834 of file number.c.
References DFSCH_MAKE_FIXNUM, dfsch_number_add(), dfsch_number_div_i(), dfsch_number_mod(), dfsch_number_mul(), dfsch_number_negative_p(), and dfsch_number_sub().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* a = n;
  dfsch_object_t* b = m;
  dfsch_object_t* t;
  dfsch_object_t* x = DFSCH_MAKE_FIXNUM(0);
  dfsch_object_t* lx = DFSCH_MAKE_FIXNUM(1);
  dfsch_object_t* q;
  a = dfsch_number_mod(a, b);
  while (b != DFSCH_MAKE_FIXNUM(0)){
    t = b;
    q = dfsch_number_div_i(a, b);
    b = dfsch_number_mod(a, b);
    a = t;
    t = x;
    x = dfsch_number_sub(lx, dfsch_number_mul(q, x));
    lx = t;
  }
  if (dfsch_number_negative_p(lx)){
    lx = dfsch_number_add(lx, m);
  }
  return lx;
}
dfsch_object_t* dfsch_number_mul (dfsch_object_t * a, dfsch_object_t * b)
Multiply arguments
Definition at line 691 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_mul(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_make_number_from_string(), dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_lcm(), dfsch_number_mod_inv(), dfsch_number_mul(), dfsch_number_sub(), and dfsch_random_get_number().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a) == DFSCH_FIXNUM_TYPE){
    long an = DFSCH_FIXNUM_REF(a)<<2;
    long bn = DFSCH_FIXNUM_REF(b);
    long x = an * bn;
    double xd = (double)an * (double)bn;
    if (x == xd){
      return DFSCH_MAKE_FIXNUM(x>>2);
    }else{
      double d = x > xd ? x - xd : xd - x;
      double p = xd >= 0 ? xd : -xd;
      if (32.0 * d <= p){
        return DFSCH_MAKE_FIXNUM(x>>2);
      }
    }
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    return dfsch_make_number_from_double
      (dfsch_number_to_double((dfsch_object_t*) a) *
       dfsch_number_to_double((dfsch_object_t*) b));
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_mul(dfsch_number_numerator(a),
                                 dfsch_number_numerator(b)),
                dfsch_number_mul(dfsch_number_denominator(b),
                                 dfsch_number_denominator(a)));
  }
  return dfsch_bignum_to_number(dfsch_bignum_mul(dfsch_bignum_from_number(a),
                                                 dfsch_bignum_from_number(b)));
}
dfsch_object_t* dfsch_number_neg (dfsch_object_t * n)
Additive inverse
Definition at line 670 of file number.c.
References dfsch_bignum_neg(), dfsch_bignum_to_number(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_make_number_from_double(), dfsch_make_number_from_long(), dfsch_number_neg(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by dfsch_make_number_from_string(), dfsch_number_abs(), dfsch_number_neg(), and frac_cons().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return dfsch_make_number_from_long(DFSCH_FIXNUM_REF(n));
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_number(dfsch_bignum_neg(n));
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return frac_cons(dfsch_number_neg(((fracnum_t*)n)->num),
                     ((fracnum_t*)n)->denom);
  } else {
    return dfsch_make_number_from_double(-dfsch_number_to_double(n));
  }
}
int dfsch_number_negative_p (dfsch_object_t * n)
Definition at line 555 of file number.c.
References dfsch_number_sign().
Referenced by dfsch_number_abs(), dfsch_number_mod_inv(), and frac_cons().
{
  return dfsch_number_sign(n) < 0;
}
dfsch_object_t* dfsch_number_numerator (dfsch_object_t * n)
Definition at line 198 of file number.c.
References dfsch_error(), DFSCH_FRACNUM_TYPE, dfsch_integer_p(), and DFSCH_TYPE_OF.
Referenced by dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_mul(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return ((fracnum_t*)n)->num;
  }
  if (dfsch_integer_p(n)){
    return n;
  }
  dfsch_error("exception:not-a-rational-number", n);
}
int dfsch_number_odd_p (dfsch_object_t * n)
Definition at line 577 of file number.c.
References dfsch_bignum_even_p(), DFSCH_BIGNUM_TYPE, dfsch_bool(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return (DFSCH_FIXNUM_REF(n) & 0x01 == 1);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
      return !dfsch_bignum_even_p(n);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return 0; /* proper fracnum cannot be integer */
  } else {
    double nn = dfsch_number_to_double(n);
    nn = (nn + 1.0) /2.0;
    return dfsch_bool(nn == round(nn));
  }
}
int dfsch_number_p (dfsch_object_t * obj)
Is OBJ a a number?
Definition at line 445 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_NUMBER_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_eqv_p(), and dfsch_number_to_string().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_NUMBER_TYPE);
}
int dfsch_number_positive_p (dfsch_object_t * n)
Definition at line 558 of file number.c.
References dfsch_number_sign().
{
  return dfsch_number_sign(n) > 0;
}
int dfsch_number_sign (dfsch_object_t * n)
Definition at line 533 of file number.c.
References dfsch_bignum_sign(), DFSCH_BIGNUM_TYPE, DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_sign(), dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_gcd(), dfsch_number_negative_p(), dfsch_number_positive_p(), dfsch_number_sign(), and dfsch_number_zero_p().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    if (DFSCH_FIXNUM_REF(n) == 0){
      return 0;
    } else {
      return (DFSCH_FIXNUM_REF(n) < 0) ? - 1 : 1;
    }
  } else if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_sign(n);
  } else if (DFSCH_TYPE_OF(n) == DFSCH_FRACNUM_TYPE){
    return dfsch_number_sign(((fracnum_t*)n)->num);
  } else {
    double nn = dfsch_number_to_double(n);
    if (nn == 0.0){
      return 0;
    } else {
      return (DFSCH_FIXNUM_REF(n) < 0) ? - 1 : 1;
    }
  }
}
dfsch_object_t* dfsch_number_sub (dfsch_object_t * a, dfsch_object_t * b)
Substract arguments.
Definition at line 634 of file number.c.
References dfsch_bignum_from_number(), dfsch_bignum_sub(), dfsch_bignum_to_number(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_denominator(), dfsch_number_mul(), dfsch_number_numerator(), dfsch_number_sub(), dfsch_number_to_double(), DFSCH_TYPE_OF, and frac_cons().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_mod_inv(), and dfsch_number_sub().
{
  if (DFSCH_TYPE_OF(a) == DFSCH_TYPE_OF(b) &&
      DFSCH_TYPE_OF(a)== DFSCH_FIXNUM_TYPE){
    long an = DFSCH_FIXNUM_REF(a)<<2;
    long bn = DFSCH_FIXNUM_REF(b)<<2;
    long x = an - bn;
    if ((an^x) >= 0 || (~bn^x) >= 0)
      return DFSCH_MAKE_FIXNUM(x>>2);
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FLONUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FLONUM_TYPE){
    return dfsch_make_number_from_double
      (dfsch_number_to_double((dfsch_object_t*) a) -
       dfsch_number_to_double((dfsch_object_t*) b));
  }
  if (DFSCH_TYPE_OF(a) == DFSCH_FRACNUM_TYPE ||
      DFSCH_TYPE_OF(b) == DFSCH_FRACNUM_TYPE){
    dfsch_object_t* c = dfsch_number_mul(dfsch_number_denominator(a),
                                         dfsch_number_denominator(b));
    return
      frac_cons(dfsch_number_sub(dfsch_number_mul(dfsch_number_numerator(a),
                                                  dfsch_number_denominator(b)),
                                 dfsch_number_mul(dfsch_number_numerator(b),
                                                  dfsch_number_denominator(a))),
                c);
  }
  return dfsch_bignum_to_number(dfsch_bignum_sub(dfsch_bignum_from_number(a),
                                                 dfsch_bignum_from_number(b)));
}
double dfsch_number_to_double (dfsch_object_t * n)
Returns value of given number as double.
Definition at line 342 of file number.c.
References dfsch_bignum_to_double(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_FLONUM_TYPE, DFSCH_FRACNUM_TYPE, dfsch_number_to_double(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_number_add(), dfsch_number_cmp(), dfsch_number_div(), dfsch_number_equal_p(), dfsch_number_even_p(), dfsch_number_format(), dfsch_number_mul(), dfsch_number_neg(), dfsch_number_odd_p(), dfsch_number_sign(), dfsch_number_sub(), dfsch_number_to_double(), and dfsch_number_to_inexact().
{
  if (DFSCH_TYPE_OF(n)==DFSCH_FIXNUM_TYPE){
    return (double)DFSCH_FIXNUM_REF(n);
  }
  if (DFSCH_TYPE_OF(n)==DFSCH_FLONUM_TYPE){
    return ((flonum_t*)n)->flonum;
  }
  if (DFSCH_TYPE_OF(n)==DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_double((dfsch_bignum_t*)n);
  }
  if (DFSCH_TYPE_OF(n)==DFSCH_FRACNUM_TYPE){
    return dfsch_number_to_double(((fracnum_t*)n)->num) /
    dfsch_number_to_double(((fracnum_t*)n)->denom);
  }
  dfsch_error("exception:not-a-real-number", n);
}
dfsch_object_t* dfsch_number_to_inexact (dfsch_object_t * n)
Definition at line 358 of file number.c.
References dfsch_make_number_from_double(), and dfsch_number_to_double().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_make_number_from_double(dfsch_number_to_double(n));
}
int64_t dfsch_number_to_int64 (dfsch_object_t * n)
Returns value of given number as int64_t.
Definition at line 377 of file number.c.
References dfsch_bignum_to_int64(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, and DFSCH_TYPE_OF.
{
  int64_t r;
  if (DFSCH_TYPE_OF(n)==DFSCH_FIXNUM_TYPE){
    return DFSCH_FIXNUM_REF(n);
  } else if (DFSCH_TYPE_OF(n)==DFSCH_BIGNUM_TYPE){
    if (!dfsch_bignum_to_int64((dfsch_bignum_t*)n, &r)){
      dfsch_error("exception:value-too-large", NULL);
    }
    return r;
  }
  dfsch_error("exception:not-an-integer", n);
}
long dfsch_number_to_long (dfsch_object_t * n)
Returns value of given number as long.
Definition at line 361 of file number.c.
References dfsch_bignum_to_int64(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, and DFSCH_TYPE_OF.
Referenced by command_exit(), dfsch_format(), dfsch_list_2_string(), dfsch_list_2_string_utf8(), dfsch_number_mod(), and make_bignum_from_digits().
{
  int64_t r;
  if (DFSCH_TYPE_OF(n)==DFSCH_FIXNUM_TYPE){
    return DFSCH_FIXNUM_REF(n); /* we expect that fixnum fits in long */
  } else if (DFSCH_TYPE_OF(n)==DFSCH_BIGNUM_TYPE){
    if (!dfsch_bignum_to_int64((dfsch_bignum_t*)n, &r) ||
        r < LONG_MIN || r > LONG_MAX){
      dfsch_error("exception:value-too-large", NULL);
    }
    return r;
  }
  dfsch_error("exception:not-an-integer", n);
}
char* dfsch_number_to_string (dfsch_object_t * n, int base)
Definition at line 422 of file number.c.
References dfsch_bignum_to_string(), DFSCH_BIGNUM_TYPE, dfsch_error(), DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, dfsch_number_p(), dfsch_object_2_string(), DFSCH_TYPE_OF, and int_to_str().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_format(), format_r(), and fracnum_write().
{
  if (DFSCH_TYPE_OF(n) == DFSCH_FIXNUM_TYPE){
    return int_to_str(DFSCH_FIXNUM_REF(n), base);
  }
  if (DFSCH_TYPE_OF(n) == DFSCH_BIGNUM_TYPE){
    return dfsch_bignum_to_string((dfsch_bignum_t*)n, base);
  }
  if (!dfsch_number_p(n)){
    dfsch_error("Not a number", n);
  }
  if (base != 10){
    dfsch_error("Unsupported base for this numeric type", NULL);
  }
  return dfsch_object_2_string(n, 1, 1); /* fallback */
}
int dfsch_number_zero_p (dfsch_object_t * n)
Definition at line 561 of file number.c.
References dfsch_number_sign().
{
  return dfsch_number_sign(n) == 0;
}
int dfsch_rational_p (dfsch_object_t * obj)
Definition at line 451 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_RATIONAL_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_RATIONAL_TYPE);
}
int dfsch_real_p (dfsch_object_t * obj)
Definition at line 448 of file number.c.
References DFSCH_INSTANCE_P, and DFSCH_REAL_TYPE.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return DFSCH_INSTANCE_P(obj, DFSCH_REAL_TYPE);
}
static size_t diffusion (size_t h) [static]
Definition at line 48 of file number.c.
Referenced by flonum_hash().
{
  h ^= h >> 5 | h << sizeof(size_t)*8 - 5;
  h ^= h << 7 | h << sizeof(size_t)*8 - 7;
  h += 0x8025f5a6;
  h ^= h >> 11 | h << sizeof(size_t)*8 - 11;
  h ^= h << 13 | h << sizeof(size_t)*8 - 13;
  return h;
}
static void fixnum_write (dfsch_object_t * n, dfsch_writer_state_t * state) [static]
Definition at line 101 of file number.c.
References DFSCH_FIXNUM_REF, dfsch_write_string(), and saprintf.
{
  dfsch_write_string(state, saprintf("%ld", DFSCH_FIXNUM_REF(n)));
}
static int flonum_equal_p (flonum_t * a, flonum_t * b) [static]
Definition at line 124 of file number.c.
References flonum_t::flonum.
{
  return a->flonum == b->flonum;
}
static uint32_t flonum_hash (flonum_t * n) [static]
Definition at line 119 of file number.c.
References diffusion(), and flonum_t::flonum.
{
  return diffusion(((size_t)n->flonum) ^
    ((size_t) (exp(round(32-log(n->flonum))) *
               (n->flonum - trunc(n->flonum)))));
}
static void flonum_write (flonum_t * n, dfsch_writer_state_t * state) [static]
Definition at line 116 of file number.c.
References dfsch_write_string(), flonum_t::flonum, and saprintf.
{
  dfsch_write_string(state, saprintf("%.32g", n->flonum));
}
static dfsch_object_t* frac_cons (dfsch_object_t * num, dfsch_object_t * denom) [static]
Definition at line 170 of file number.c.
References fracnum_t::denom, DFSCH_FRACNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_object(), dfsch_number_abs(), dfsch_number_div_i(), dfsch_number_gcd(), dfsch_number_neg(), dfsch_number_negative_p(), and fracnum_t::num.
Referenced by dfsch_number_add(), dfsch_number_div(), dfsch_number_mul(), dfsch_number_neg(), and dfsch_number_sub().
{
  fracnum_t* f = (fracnum_t*)dfsch_make_object(DFSCH_FRACNUM_TYPE);
  dfsch_object_t* n;
  dfsch_object_t* d;
  dfsch_object_t* x;
  int negative = dfsch_number_negative_p(num) != dfsch_number_negative_p(denom);
  n = dfsch_number_abs(num);
  d = dfsch_number_abs(denom);
  x = dfsch_number_gcd(n, d);
  d = dfsch_number_div_i(d, x);
  n = dfsch_number_div_i(n, x);
  if (negative){
    n = dfsch_number_neg(n);
  }
  if (d == DFSCH_MAKE_FIXNUM(1)){
    return n;
  }
  f->num = n;
  f->denom = d;
  return (dfsch_object_t*)f;
}
static int fracnum_equal_p (fracnum_t * a, fracnum_t * b) [static]
Definition at line 144 of file number.c.
References fracnum_t::denom, dfsch_equal_p(), and fracnum_t::num.
{
  return
    dfsch_equal_p(a->num, b->num) &&
    dfsch_equal_p(a->denom, b->denom);
}
static uint32_t fracnum_hash (fracnum_t * n) [static]
Definition at line 149 of file number.c.
References fracnum_t::denom, dfsch_hash(), and fracnum_t::num.
{
  uint32_t h;
  h = 0x7e9aa806;
  h ^= dfsch_hash(n->num);
  h = h << 16 | h >> 16;
  h ^= dfsch_hash(n->denom);
  return h;
}
static void fracnum_write (fracnum_t * n, dfsch_writer_state_t * state) [static]
Definition at line 139 of file number.c.
References fracnum_t::denom, dfsch_number_to_string(), dfsch_write_string(), and fracnum_t::num.
{
  dfsch_write_string(state, dfsch_number_to_string(n->num, 10));
  dfsch_write_string(state, "/");
  dfsch_write_string(state, dfsch_number_to_string(n->denom, 10));
}
static char* int_to_str (long i, int base) [static]
Definition at line 394 of file number.c.
References dfsch_error().
Referenced by dfsch_number_to_string().
{
  long n;
  char* buf = GC_MALLOC_ATOMIC(32); /* where do you have larger fixnums? */
  buf += 31;
  *buf = '\0';
  if (base == 0 || base > 36){
    dfsch_error("Invalid base", NULL);
  }
  n = labs(i);
  while (n > 0){
    buf--;
    *buf = digits[n % base];
    n /= base;
  }
  if (i < 0){
    buf--;
    *buf = '-';
    return buf;
  } else {
    return buf;
  }
}
Variable Documentation
dfsch_number_type_t dfsch_fixnum_type
Initial value:
 {
  DFSCH_SPECIAL_TYPE,
  DFSCH_INTEGER_TYPE,
  0,
  "fixnum",
  NULL,
  (dfsch_type_write_t)fixnum_write,
  NULL,
  NULL
}
Definition at line 105 of file number.c.
dfsch_number_type_t dfsch_flonum_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  DFSCH_REAL_TYPE,
  sizeof(flonum_t),
  "flonum",
  (dfsch_type_equal_p_t)flonum_equal_p,
  (dfsch_type_write_t)flonum_write,
  NULL,
  (dfsch_type_hash_t)flonum_hash,
}
Definition at line 128 of file number.c.
dfsch_number_type_t dfsch_fracnum_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  DFSCH_RATIONAL_TYPE,
  sizeof(fracnum_t),
  "fracnum",
  (dfsch_type_equal_p_t)fracnum_equal_p,
  (dfsch_type_write_t)fracnum_write,
  NULL,
  (dfsch_type_hash_t)fracnum_hash,
}
Definition at line 159 of file number.c.
dfsch_type_t dfsch_integer_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  DFSCH_RATIONAL_TYPE,
  0,
  "integer",
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 89 of file number.c.
dfsch_type_t dfsch_number_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "number",
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 59 of file number.c.
dfsch_type_t dfsch_rational_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  DFSCH_REAL_TYPE,
  0,
  "rational",
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 79 of file number.c.
dfsch_type_t dfsch_real_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  DFSCH_NUMBER_TYPE,
  0,
  "real",
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 69 of file number.c.
int dig_val[128] [static]
Initial value:
 {
  37, 37, 37, 37,  37, 37, 37, 37,  37, 37, 37, 37,  37, 37, 37, 37,
  37, 37, 37, 37,  37, 37, 37, 37,  37, 37, 37, 37,  37, 37, 37, 37,
  37, 37, 37, 37,  37, 37, 37, 37,  37, 37, 37, 37,  37, 37, 37, 37,
  0,  1,  2,  3,   4,  5,  6,  7,   8,  9,  37, 37,  37, 37, 37, 37,
  37, 10, 11, 12, 13,  14, 15, 16, 17,  18, 19, 20, 21,  22, 23, 24,
  25, 26, 27, 28, 29,  30, 31, 32, 33,  34, 35, 36, 37,  37, 37, 37,
  37, 10, 11, 12, 13,  14, 15, 16, 17,  18, 19, 20, 21,  22, 23, 24,
  25, 26, 27, 28, 29,  30, 31, 32, 33,  34, 35, 36, 37,  37, 37, 37
}
Definition at line 240 of file number.c.
char* digits = "0123456789abcdefghijklmnopqrstuvwxyz" [static]
Definition at line 392 of file number.c.