dfsch: dfsch/object.h File Reference
dfsch/object.h File Reference
#include <dfsch/dfsch.h>
Defines
#define DFSCH_CLASS_TYPE (&dfsch_class_type)
Functions
dfsch_object_t * dfsch_find_method (dfsch_object_t *klass, dfsch_object_t *selector)
dfsch_object_t * dfsch_make_class (dfsch_object_t *superclass, char *name, dfsch_object_t *slots)
dfsch_object_t * dfsch_make_instance (dfsch_object_t *klass, dfsch_object_t *args)
dfsch_object_t * dfsch_perform (dfsch_object_t *klass, dfsch_object_t *selector, dfsch_object_t *args)
dfsch_object_t * dfsch_perform_tr (dfsch_object_t *klass, dfsch_object_t *selector, dfsch_object_t *args, dfsch_tail_escape_t *esc)
int dfsch_responds_to_p (dfsch_object_t *klass, dfsch_object_t *selector)
dfsch_object_t * dfsch_s_apply_instance ()
dfsch_object_t * dfsch_s_equal_instance_p ()
dfsch_object_t * dfsch_s_initialize_instance ()
dfsch_object_t * dfsch_s_instance_hash ()
dfsch_object_t * dfsch_s_write_instance ()
dfsch_object_t * dfsch_send (dfsch_object_t *obj, dfsch_object_t *selector, dfsch_object_t *args)
dfsch_object_t * dfsch_send_tr (dfsch_object_t *obj, dfsch_object_t *selector, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Variables
dfsch_type_t dfsch_class_type
Define Documentation
#define DFSCH_CLASS_TYPE (&dfsch_class_type)
Definition at line 32 of file object.h.
Referenced by dfsch__object_native_register(), dfsch_class_add_method(), dfsch_class_remove_method(), dfsch_find_method(), dfsch_make_class(), and dfsch_make_instance().
Function Documentation
dfsch_object_t* dfsch_find_method (dfsch_object_t * klass, dfsch_object_t * selector)
Definition at line 151 of file object.c.
References DFSCH_CLASS_TYPE, dfsch_error(), dfsch_hash_ref_fast(), dfsch_hash_set(), DFSCH_INSTANCE_P, class_t::methods, class_t::send_cache, class_t::standard_type, and dfsch_type_t::superclass.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_perform_tr(), and dfsch_responds_to_p().
{
  dfsch_object_t* method;
  class_t* c;
  if (!DFSCH_INSTANCE_P(klass, DFSCH_CLASS_TYPE)){
    dfsch_error("Not a class", klass);
  }
  c = (class_t*)klass;
  if (dfsch_hash_ref_fast(c->send_cache, selector, &method)){
    return method;
  }
  while(DFSCH_INSTANCE_P(c, DFSCH_CLASS_TYPE)){
    if (dfsch_hash_ref_fast(c->methods, selector, &method)){
      dfsch_hash_set(((class_t*)klass)->send_cache, selector, method);
      return method;
    }
    c = (class_t*) c->standard_type.superclass;
  }
  return NULL;
}
dfsch_object_t* dfsch_make_class (dfsch_object_t * superclass, char * name, dfsch_object_t * slots)
Definition at line 107 of file object.c.
References adjust_sizes(), DFSCH_CLASS_TYPE, dfsch_error(), DFSCH_HASH_EQ, dfsch_hash_make(), DFSCH_INSTANCE_P, dfsch_make_object(), DFSCH_TYPEF_USER_EXTENSIBLE, dfsch_type_t::flags, make_slots(), class_t::methods, dfsch_type_t::name, class_t::send_cache, dfsch_type_t::size, dfsch_type_t::slots, class_t::standard_type, and dfsch_type_t::superclass.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  class_t* klass = dfsch_make_object(DFSCH_CLASS_TYPE);
  klass->standard_type.superclass = superclass;
  klass->standard_type.name = name;
  klass->standard_type.slots = make_slots(slots);
  klass->standard_type.flags = DFSCH_TYPEF_USER_EXTENSIBLE;
  if (superclass){
    if (!DFSCH_INSTANCE_P(superclass, DFSCH_CLASS_TYPE)){
      dfsch_error("Not a class", superclass);
    }
    klass->standard_type.size = adjust_sizes(klass->standard_type.slots,
                                             ((dfsch_type_t*)
                                              superclass)->size);
  } else {
    klass->standard_type.size = adjust_sizes(klass->standard_type.slots,
                                             sizeof(dfsch_object_t));
  }
  /* klass->standard_type.equal_p = class_equal_p;
  klass->standard_type.write = class_write;
  klass->standard_type.apply = class_apply;
  klass->standard_type.hash = class_hash;*/
  klass->methods = dfsch_hash_make(DFSCH_HASH_EQ);
  klass->send_cache = dfsch_hash_make(DFSCH_HASH_EQ);
  return (dfsch_type_t*)klass;
}
dfsch_object_t* dfsch_make_instance (dfsch_object_t * klass, dfsch_object_t * args)
Definition at line 139 of file object.c.
References DFSCH_CLASS_TYPE, dfsch_error(), DFSCH_INSTANCE_P, dfsch_make_object(), dfsch_s_initialize_instance(), and dfsch_send().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_object_t* obj;
  if (!DFSCH_INSTANCE_P(klass, DFSCH_CLASS_TYPE)){
    dfsch_error("Not a class", klass);
  }
  obj = dfsch_make_object(klass);
  dfsch_send(obj, dfsch_s_initialize_instance(), args);
  return obj;
}
dfsch_object_t* dfsch_perform (dfsch_object_t * klass, dfsch_object_t * selector, dfsch_object_t * args)
Definition at line 215 of file object.c.
References dfsch_perform_tr().
{
  return dfsch_perform_tr(klass, selector, args, NULL);
}
dfsch_object_t* dfsch_perform_tr (dfsch_object_t * klass, dfsch_object_t * selector, dfsch_object_t * args, dfsch_tail_escape_t * esc)
Definition at line 205 of file object.c.
References dfsch_apply_tr(), dfsch_error(), dfsch_find_method(), and dfsch_list().
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_perform(), dfsch_send(), and dfsch_send_tr().
{
  dfsch_object_t* method = dfsch_find_method(klass, selector);
  if (!method){
    dfsch_error("Message not understood", dfsch_list(2, klass, selector));
  }
  return dfsch_apply_tr(method, args, esc);
}
int dfsch_responds_to_p (dfsch_object_t * klass, dfsch_object_t * selector)
Definition at line 200 of file object.c.
References dfsch_find_method().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_find_method(klass, selector) != NULL;
}
dfsch_object_t* dfsch_s_apply_instance ()
dfsch_object_t* dfsch_s_equal_instance_p ()
Referenced by class_equal_p().
dfsch_object_t* dfsch_s_initialize_instance ()
Referenced by dfsch_make_instance().
dfsch_object_t* dfsch_s_instance_hash ()
dfsch_object_t* dfsch_s_write_instance ()
dfsch_object_t* dfsch_send (dfsch_object_t * obj, dfsch_object_t * selector, dfsch_object_t * args)
Definition at line 230 of file object.c.
References dfsch_cons(), dfsch_perform_tr(), and DFSCH_TYPE_OF.
Referenced by class_equal_p(), and dfsch_make_instance().
{
  return dfsch_perform_tr(DFSCH_TYPE_OF(obj),
                          selector,
                          dfsch_cons(obj, args),
                          NULL);
}
dfsch_object_t* dfsch_send_tr (dfsch_object_t * obj, dfsch_object_t * selector, dfsch_object_t * args, dfsch_tail_escape_t * esc)
Definition at line 221 of file object.c.
References dfsch_cons(), dfsch_perform_tr(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_perform_tr(DFSCH_TYPE_OF(obj),
                          selector,
                          dfsch_cons(obj, args),
                          esc);
}
Variable Documentation
dfsch_type_t dfsch_class_type
Definition at line 37 of file object.c.