dfsch: dfsch/parse.h File Reference
dfsch/parse.h File Reference
#include <dfsch/dfsch.h>
#include <dfsch/ports.h>
Defines
#define DFSCH_PARSER_CAR_EXPECTED 4
#define DFSCH_PARSER_INVALID_ESCAPE 6
#define DFSCH_PARSER_INVALID_NUMBER 7
#define DFSCH_PARSER_LIST_EXPECTED 5
#define DFSCH_PARSER_NOERROR 0
#define DFSCH_PARSER_NULL 254
#define DFSCH_PARSER_STOPPED 255
#define DFSCH_PARSER_UNEXPECTED_CLOSE 1
#define DFSCH_PARSER_UNEXPECTED_DOT 2
#define DFSCH_PARSER_UNEXPECTED_OBJECT 3
#define DFSCH_PARSER_UNREADABLE 8
Typedefs
typedef int(* dfsch_parser_callback_t)(dfsch_object_t *obj, void *baton)
typedef struct dfsch_parser_ctx_t dfsch_parser_ctx_t
typedef int(* dfsch_parser_directive_t)(dfsch_parser_ctx_t *ctx, dfsch_object_t *args, void *baton)
Functions
void dfsch_parser_callback (dfsch_parser_ctx_t *ctx, dfsch_parser_callback_t callback, void *baton)
void dfsch_parser_clear_directives (dfsch_parser_ctx_t *ctx)
void dfsch_parser_clear_symbols (dfsch_parser_ctx_t *ctx)
dfsch_parser_ctx_t * dfsch_parser_create ()
void dfsch_parser_define_default_directives (dfsch_parser_ctx_t *ctx)
void dfsch_parser_define_directive_cstr (dfsch_parser_ctx_t *ctx, char *tag, dfsch_parser_directive_t directive, void *baton)
void dfsch_parser_define_symbol (dfsch_parser_ctx_t *ctx, char *name, dfsch_object_t *symbol)
void dfsch_parser_eval_env (dfsch_parser_ctx_t *ctx, dfsch_object_t *env)
int dfsch_parser_feed (dfsch_parser_ctx_t *ctx, char *data)
int dfsch_parser_feed_line (dfsch_parser_ctx_t *ctx, char *data)
int dfsch_parser_get_level (dfsch_parser_ctx_t *ctx)
void dfsch_parser_import_symbol (dfsch_parser_ctx_t *ctx, dfsch_object_t *symbol)
void dfsch_parser_parse_object (dfsch_parser_ctx_t *ctx, dfsch_object_t *obj)
dfsch_object_t * dfsch_parser_read_from_port (dfsch_object_t *port)
void dfsch_parser_reset (dfsch_parser_ctx_t *ctx)
void dfsch_parser_set_source (dfsch_parser_ctx_t *ctx, dfsch_object_t *source)
int dfsch_parser_top_level (dfsch_parser_ctx_t *ctx)
void dfsch_parser_undefine_symbol (dfsch_parser_ctx_t *ctx, char *name)
Detailed Description
Stream based S-expression parser.
Definition in file parse.h.
Define Documentation
#define DFSCH_PARSER_CAR_EXPECTED 4
Definition at line 42 of file parse.h.
#define DFSCH_PARSER_INVALID_ESCAPE 6
Definition at line 44 of file parse.h.
#define DFSCH_PARSER_INVALID_NUMBER 7
Definition at line 45 of file parse.h.
#define DFSCH_PARSER_LIST_EXPECTED 5
Definition at line 43 of file parse.h.
#define DFSCH_PARSER_NOERROR 0
Definition at line 38 of file parse.h.
#define DFSCH_PARSER_NULL 254
Definition at line 47 of file parse.h.
#define DFSCH_PARSER_STOPPED 255
Definition at line 48 of file parse.h.
Referenced by dfsch_read_scm_fd(), dfsch_read_scm_stream(), and dfsch_string_2_object_list().
#define DFSCH_PARSER_UNEXPECTED_CLOSE 1
Definition at line 39 of file parse.h.
#define DFSCH_PARSER_UNEXPECTED_DOT 2
Definition at line 40 of file parse.h.
#define DFSCH_PARSER_UNEXPECTED_OBJECT 3
Definition at line 41 of file parse.h.
#define DFSCH_PARSER_UNREADABLE 8
Definition at line 46 of file parse.h.
Typedef Documentation
typedef int(* dfsch_parser_callback_t)(dfsch_object_t *obj, void *baton)
Definition at line 51 of file parse.h.
typedef struct dfsch_parser_ctx_t dfsch_parser_ctx_t
Definition at line 50 of file parse.h.
typedef int(* dfsch_parser_directive_t)(dfsch_parser_ctx_t *ctx, dfsch_object_t *args, void *baton)
Definition at line 52 of file parse.h.
Function Documentation
void dfsch_parser_callback (dfsch_parser_ctx_t * ctx, dfsch_parser_callback_t callback, void * baton)
Sets callback for complete objects parsed.
Definition at line 290 of file parse.c.
References dfsch_parser_ctx_t::baton, and dfsch_parser_ctx_t::callback.
Referenced by dfsch_console_read_object(), dfsch_console_read_objects(), dfsch_parser_read_from_port(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_string_2_object_list(), and noninteractive_repl().
{
  ctx->callback = callback;
  ctx->baton = baton;
}
void dfsch_parser_clear_directives (dfsch_parser_ctx_t * ctx)
Definition at line 321 of file parse.c.
References dfsch_parser_ctx_t::directives.
{
  ctx->directives = NULL;
}
void dfsch_parser_clear_symbols (dfsch_parser_ctx_t * ctx)
Definition at line 324 of file parse.c.
References dfsch_parser_ctx_t::symbol_map.
{
  ctx->symbol_map = NULL;
}
dfsch_parser_ctx_t* dfsch_parser_create ()
Creates new parser instance
Definition at line 198 of file parse.c.
References dfsch_parser_ctx_t::column, create_queue(), dfsch_parser_define_default_directives(), dfsch_parser_ctx_t::env, dfsch_parser_ctx_t::error, dfsch_parser_ctx_t::level, dfsch_parser_ctx_t::line, dfsch_parser_ctx_t::parser, dfsch_parser_ctx_t::q, dfsch_parser_ctx_t::symbol_map, and dfsch_parser_ctx_t::tokenizer_state.
Referenced by dfsch_console_read_object(), dfsch_console_read_objects(), dfsch_parser_read_from_port(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_string_2_object_list(), and noninteractive_repl().
{
  dfsch_parser_ctx_t *ctx = GC_MALLOC(sizeof(dfsch_parser_ctx_t));
  if (!ctx)
    return NULL;
  ctx->q = create_queue();
  if (!ctx->q){
    return NULL;
  }
  ctx->tokenizer_state = T_NONE;
  ctx->parser = NULL;
  ctx->line = 1;
  ctx->column = 1;
  ctx->level = 0 ;
  ctx->error = 0;
  ctx->symbol_map = NULL;
  ctx->env = 0;
  dfsch_parser_define_default_directives(ctx);
  return ctx;
}
void dfsch_parser_define_default_directives (dfsch_parser_ctx_t * ctx)
Definition at line 339 of file parse.c.
References dfsch_parser_define_directive_cstr(), directive_import(), and dfsch_parser_ctx_t::directives.
Referenced by dfsch_parser_create().
{
  ctx->directives = NULL;
  dfsch_parser_define_directive_cstr(ctx, "import", directive_import, NULL);
}
void dfsch_parser_define_directive_cstr (dfsch_parser_ctx_t * ctx, char * tag, dfsch_parser_directive_t directive, void * baton)
Definition at line 315 of file parse.c.
References dfsch_make_symbol(), and dfsch_parser_define_directive().
Referenced by dfsch_parser_define_default_directives().
{
  dfsch_parser_define_directive(ctx, dfsch_make_symbol(tag), directive, baton);
}
void dfsch_parser_define_symbol (dfsch_parser_ctx_t * ctx, char * name, dfsch_object_t * symbol)
Definition at line 237 of file parse.c.
References ascii_strcasecmp, symbol_map_t::name, symbol_map_t::next, symbol_map_t::symbol, and dfsch_parser_ctx_t::symbol_map.
Referenced by dfsch_parser_import_symbol().
{
  symbol_map_t* entry;
  entry = ctx->symbol_map;
  while (entry) {
    if (ascii_strcasecmp(name, entry->name) == 0){
      entry->symbol = symbol;
      return;
    }
    entry = entry->next;
  }
  entry = GC_NEW(symbol_map_t);
  entry->symbol = symbol;
  entry->name = name;
  entry->next = ctx->symbol_map;
  ctx->symbol_map = entry;
}
void dfsch_parser_eval_env (dfsch_parser_ctx_t * ctx, dfsch_object_t * env)
Definition at line 298 of file parse.c.
References dfsch_parser_ctx_t::env.
Referenced by dfsch_read_scm_fd(), and dfsch_read_scm_stream().
{
  ctx->env = env;
}
int dfsch_parser_feed (dfsch_parser_ctx_t * ctx, char * data)
Feed some data into parser.
Definition at line 1061 of file parse.c.
References DFSCH_PROTECT, DFSCH_PROTECT_END, DFSCH_UNWIND, DFSCH_UNWIND_DETECT, dfsch_parser_ctx_t::error, feed_queue(), get_queue(), parser_reset(), dfsch_parser_ctx_t::q, and tokenizer_process().
Referenced by dfsch_parser_feed_catch(), dfsch_parser_feed_line(), dfsch_parser_read_from_port(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), and dfsch_string_2_object_list().
{
  ctx->error = 0;
  DFSCH_UNWIND{
  feed_queue(ctx->q, data);
  tokenizer_process(ctx, get_queue(ctx->q));
  }DFSCH_PROTECT{
  }DFSCH_UNWIND_DETECT{
    parser_reset(ctx);
  }DFSCH_PROTECT_END;
  return ctx->error;
}
int dfsch_parser_feed_line (dfsch_parser_ctx_t * ctx, char * data)
Definition at line 1075 of file parse.c.
References dfsch_parser_feed().
Referenced by dfsch_console_read_object(), and dfsch_console_read_objects_parser().
{
  int ret;
  if (ret = dfsch_parser_feed(ctx, data)){
    return ret;
  }
  return dfsch_parser_feed(ctx, "\n");
}
int dfsch_parser_get_level (dfsch_parser_ctx_t * ctx)
Get nesting level (i.e. some value proportional to depth of parser stack)
Definition at line 1092 of file parse.c.
References dfsch_parser_ctx_t::level.
Referenced by dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_string_2_object_list(), and get_prompt().
{
  return ctx->level;
}
void dfsch_parser_import_symbol (dfsch_parser_ctx_t * ctx, dfsch_object_t * symbol)
Definition at line 279 of file parse.c.
References dfsch_parser_define_symbol(), and dfsch_symbol().
Referenced by directive_import().
{
  char* name;
  name = rindex(dfsch_symbol(symbol), ':');
  if (name && name[1]!=0){
    dfsch_parser_define_symbol(ctx, name + 1, symbol);
  }
}
void dfsch_parser_parse_object (dfsch_parser_ctx_t * ctx, dfsch_object_t * obj)
Definition at line 388 of file parse.c.
References dfsch_parser_ctx_t::baton, dfsch_parser_ctx_t::callback, dfsch_cons(), dfsch_eval(), dfsch_list_2_vector(), dfsch_pair_p(), dfsch_set_cdr(), dfsch_parser_ctx_t::env, dfsch_parser_ctx_t::error, parser_stack_t::front, parser_stack_t::last, parse_object, dfsch_parser_ctx_t::parser, parser_abort(), parser_pop(), process_directive(), parser_stack_t::state, and parser_stack_t::tag.
{
  if (ctx->parser){
    switch(ctx->parser->state){
    case P_LIST:
      {
        dfsch_object_t *new = dfsch_cons(obj, NULL);
        if (ctx->parser->last){
          dfsch_set_cdr(ctx->parser->last, new);
        }else{
          ctx->parser->front = new;
        }
        ctx->parser->last = new;
        break;
      }
    case P_DOT:
      if (ctx->parser->last){
        dfsch_set_cdr(ctx->parser->last, obj);
        ctx->parser->state = P_PREEND;
        return;
      }else{
        parser_abort(ctx, "parser:car-expected");
      }
    case P_QUOTE:
      {
        dfsch_object_t* tag = ctx->parser->tag;
        parser_pop(ctx);
        parse_object(ctx, dfsch_cons(tag, dfsch_cons(obj, NULL)));
        return;
      }
    case P_HASH:
      parser_pop(ctx);
      if ((!obj) || dfsch_pair_p(obj)){
        parse_object(ctx, dfsch_list_2_vector(obj));
      }else{
        parser_abort(ctx, "parser:list-expected");
      }
      return;
    case P_EVAL:
      parser_pop(ctx);
      if (ctx->env){
        parse_object(ctx, dfsch_eval(obj, ctx->env));
        /* XXX: What happens when this throws exception is not entirely clear */
      }else{
        parser_abort(ctx, "parser:evaluation-not-permitted");
      }
      return;
    case P_DIRECTIVE:
      parser_pop(ctx);
      process_directive(ctx, obj);
      return;
    default:
      parser_abort(ctx, "parser:unexpected-object");
    }
  }else{
    //    DFSCH_TRY { XXX
      if (!(*ctx->callback)(obj,ctx->baton)){
        ctx->error = 1;
      }
      /*} DFSCH_SCATCH(ex) {
      parser_abort_ex(ctx, ex);
      } DFSCH_SCATCHEND;*/
  }
}
dfsch_object_t* dfsch_parser_read_from_port (dfsch_object_t * port)
Read one object from port.
Definition at line 1124 of file parse.c.
References dfsch_eof_object(), dfsch_error(), dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_feed(), dfsch_parser_top_level(), dfsch_port_batch_read(), dfsch_port_batch_read_end(), dfsch_port_batch_read_start(), DFSCH_PROTECT, DFSCH_PROTECT_END, DFSCH_UNWIND, parser, and read_callback().
Referenced by native_read().
{
  dfsch_parser_ctx_t* parser = dfsch_parser_create();
  int ch;
  char buf[2];
  dfsch_object_t* res;
  int ok = 0;
  dfsch_port_batch_read_start(port);
  dfsch_parser_callback(parser, read_callback, &res);
  DFSCH_UNWIND {
    while ((ch = dfsch_port_batch_read(port)) != -1){
      buf[0] = ch;
      buf[1] = 0;
      if (dfsch_parser_feed(parser, buf)){
        dfsch_port_batch_read_end(port);
        ok = 1;
        break;
      }
    }
  } DFSCH_PROTECT {
    dfsch_port_batch_read_end(port);
  } DFSCH_PROTECT_END;
  if (ok){
    return res;
  }
  if (dfsch_parser_top_level(parser)){
    return dfsch_eof_object();
  } else {
    dfsch_error("parser:unexpected-end-of-file", port);
  }
}
void dfsch_parser_reset (dfsch_parser_ctx_t * ctx)
Destroy current parser context and start from scratch (useful for C-c in interactive applications)
Definition at line 1096 of file parse.c.
References empty_queue(), dfsch_parser_ctx_t::error, dfsch_parser_ctx_t::level, dfsch_parser_ctx_t::parser, dfsch_parser_ctx_t::q, and dfsch_parser_ctx_t::tokenizer_state.
{
  empty_queue(ctx->q);
  ctx->tokenizer_state = T_NONE;
  ctx->parser = NULL;
  ctx->level = 0 ;
  ctx->error = 0;
}
void dfsch_parser_set_source (dfsch_parser_ctx_t * ctx, dfsch_object_t * source)
Definition at line 1104 of file parse.c.
References dfsch_parser_ctx_t::source.
Referenced by dfsch_console_read_objects(), and dfsch_read_scm_stream().
{
  ctx->source = source;
}
int dfsch_parser_top_level (dfsch_parser_ctx_t * ctx)
Return true if parser is in default state.
Definition at line 1108 of file parse.c.
References dfsch_parser_ctx_t::parser, and dfsch_parser_ctx_t::tokenizer_state.
Referenced by dfsch_console_read_object(), and dfsch_parser_read_from_port().
{
  return (ctx->parser == NULL) & (ctx->tokenizer_state == T_NONE);
}
void dfsch_parser_undefine_symbol (dfsch_parser_ctx_t * ctx, char * name)
Definition at line 258 of file parse.c.
References ascii_strcasecmp, symbol_map_t::name, symbol_map_t::next, and dfsch_parser_ctx_t::symbol_map.
{
  symbol_map_t* i = ctx->symbol_map;
  symbol_map_t* j;
  if (!i){
    return;
  }
  if (ascii_strcasecmp(name, i->name) == 0){
    ctx->symbol_map = i->next;
  }
  while (i){
    if (ascii_strcasecmp(name, i->name) == 0){
      j->next = i->next;
      return;
    }
    i = i->next;
  }
}