dfsch: src/ports.c File Reference
src/ports.c File Reference
#include "dfsch/ports.h"
#include <dfsch/strings.h>
#include <dfsch/object.h>
#include <dfsch/number.h>
#include <dfsch/magic.h>
#include <dfsch/parse.h>
#include "internal.h"
#include "util.h"
#include <string.h>
#include <errno.h>
Data Structures
struct current_ports_t
struct eof_object_t
struct file_port_t
struct null_port_t
struct string_input_port_t
struct string_output_port_t
Functions
current_ports_t * current_ports ()
void dfsch__port_native_register (dfsch_object_t *ctx)
void dfsch_close_file_port (dfsch_object_t *port)
dfsch_object_t * dfsch_current_error_port ()
dfsch_object_t * dfsch_current_input_port ()
dfsch_object_t * dfsch_current_output_port ()
DFSCH_DEFINE_PRIMITIVE (port_read_whole, 0)
dfsch_object_t * dfsch_eof_object ()
int dfsch_eof_object_p (dfsch_object_t *obj)
int dfsch_input_port_p (dfsch_object_t *port)
dfsch_object_t * dfsch_make_file_port (FILE *file, int close, char *name)
dfsch_object_t * dfsch_null_port ()
DFSCH_OBJECT_CACHE (dfsch_make_file_port(stderr, 0,"(standard error)"), dfsch_standard_error_port)
DFSCH_OBJECT_CACHE (dfsch_make_file_port(stdout, 0,"(standard output)"), dfsch_standard_output_port)
DFSCH_OBJECT_CACHE (dfsch_make_file_port(stdin, 0,"(standard input)"), dfsch_standard_input_port)
dfsch_object_t * dfsch_open_file_port (char *filename, char *mode)
int dfsch_output_port_p (dfsch_object_t *port)
int dfsch_port_batch_read (dfsch_object_t *port)
void dfsch_port_batch_read_end (dfsch_object_t *port)
void dfsch_port_batch_read_start (dfsch_object_t *port)
int dfsch_port_p (dfsch_object_t *port)
ssize_t dfsch_port_read_buf (dfsch_object_t *port, char *buf, size_t size)
dfsch_strbuf_t * dfsch_port_read_whole (dfsch_object_t *port)
dfsch_strbuf_t * dfsch_port_readline (dfsch_object_t *port)
void dfsch_port_seek (dfsch_object_t *port, int64_t offset, int whence)
int64_t dfsch_port_tell (dfsch_object_t *port)
void dfsch_port_unsafe_register (dfsch_object_t *ctx)
void dfsch_port_write_buf (dfsch_object_t *port, char *buf, size_t size)
void dfsch_port_write_cstr (dfsch_object_t *port, char *str)
void dfsch_set_current_error_port (dfsch_object_t *port)
void dfsch_set_current_input_port (dfsch_object_t *port)
void dfsch_set_current_output_port (dfsch_object_t *port)
dfsch_object_t * dfsch_string_input_port (char *buf, size_t len)
dfsch_object_t * dfsch_string_output_port ()
dfsch_strbuf_t * dfsch_string_output_port_value (dfsch_object_t *port)
static void errno_error (char *name, dfsch_object_t *object, int e)
static void file_port_finalizer (file_port_t *port, void *cd)
static ssize_t file_port_read_buf (file_port_t *port, char *buf, size_t len)
static void file_port_seek (file_port_t *port, int64_t offset, int whence)
static int64_t file_port_tell (file_port_t *port)
static void file_port_write (file_port_t *port, dfsch_writer_state_t *state)
static void file_port_write_buf (file_port_t *port, char *buf, size_t len)
static dfsch_object_t * native_close_file_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_current_error_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_current_input_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_current_output_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_display (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_eof_object_p (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_newline (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_null_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_open_file_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_port_read_buf (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_port_read_line (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_port_seek (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_port_tell (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_port_write_buf (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_read (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_set_current_error_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_set_current_input_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_set_current_output_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_string_input_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_string_output_port (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_string_output_port_value (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_write (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static ssize_t null_port_read_buf (dfsch_object_t *port, char *buf, size_t len)
static void null_port_write_buf (dfsch_object_t *port, char *buf, size_t len)
static ssize_t string_input_port_read_buf (string_input_port_t *port, char *buf, size_t len)
static void string_output_port_write_buf (string_output_port_t *port, char *buf, size_t len)
Variables
dfsch_type_t dfsch_eof_object_type
dfsch_port_type_t dfsch_file_port_type
dfsch_port_type_t dfsch_null_port_type
dfsch_type_t dfsch_port_type
dfsch_type_t dfsch_port_type_type
dfsch_port_type_t dfsch_string_input_port_type
dfsch_port_type_t dfsch_string_output_port_type
eof_object_t eof_object
static dfsch_slot_t file_port_slots []
static null_port_t null_port
Function Documentation
current_ports_t* current_ports ()
Definition at line 312 of file ports.c.
Referenced by dfsch_current_error_port(), dfsch_current_input_port(), dfsch_current_output_port(), dfsch_set_current_error_port(), dfsch_set_current_input_port(), and dfsch_set_current_output_port().
{
  static current_ports_t p = {&null_port, &null_port, &null_port};
  return &p;
}
void dfsch__port_native_register (dfsch_object_t * ctx)
Definition at line 938 of file ports.c.
References dfsch_define_cstr(), DFSCH_EOF_OBJECT_TYPE, DFSCH_FILE_PORT_TYPE, dfsch_make_primitive(), DFSCH_NULL_PORT_TYPE, DFSCH_PRIMITIVE_REF, DFSCH_STRING_INPUT_PORT_TYPE, DFSCH_STRING_OUTPUT_PORT_TYPE, native_current_error_port(), native_current_input_port(), native_current_output_port(), native_display(), native_eof_object_p(), native_newline(), native_null_port(), native_port_read_buf(), native_port_read_line(), native_port_seek(), native_port_tell(), native_port_write_buf(), native_read(), native_string_input_port(), native_string_output_port(), native_string_output_port_value(), and native_write().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<port>", DFSCH_PORT_TYPE);
  dfsch_define_cstr(ctx, "<null-port>", DFSCH_NULL_PORT_TYPE);
  dfsch_define_cstr(ctx, "<file-port>", DFSCH_FILE_PORT_TYPE);
  dfsch_define_cstr(ctx, "<string-input-port>", DFSCH_STRING_INPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "<string-output-port>", DFSCH_STRING_OUTPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "<eof-object>", DFSCH_EOF_OBJECT_TYPE);
  dfsch_define_cstr(ctx, "current-output-port",
                    dfsch_make_primitive(native_current_output_port, NULL));
  dfsch_define_cstr(ctx, "current-input-port",
                    dfsch_make_primitive(native_current_input_port, NULL));
  dfsch_define_cstr(ctx, "current-error-port",
                    dfsch_make_primitive(native_current_error_port, NULL));
  dfsch_define_cstr(ctx, "null-port",
                    dfsch_make_primitive(native_null_port, NULL));
  dfsch_define_cstr(ctx, "write",
                    dfsch_make_primitive(native_write, NULL));
  dfsch_define_cstr(ctx, "display",
                    dfsch_make_primitive(native_display, NULL));
  dfsch_define_cstr(ctx, "newline",
                    dfsch_make_primitive(native_newline, NULL));
  dfsch_define_cstr(ctx, "read",
                    dfsch_make_primitive(native_read, NULL));
  dfsch_define_cstr(ctx, "eof-object?",
                    dfsch_make_primitive(native_eof_object_p, NULL));
  dfsch_define_cstr(ctx, "port-write-buf",
                    dfsch_make_primitive(native_port_write_buf, NULL));
  dfsch_define_cstr(ctx, "port-read-buf",
                    dfsch_make_primitive(native_port_read_buf, NULL));
  dfsch_define_cstr(ctx, "port-read-whole",
                    DFSCH_PRIMITIVE_REF(port_read_whole));
  dfsch_define_cstr(ctx, "port-read-line",
                    dfsch_make_primitive(native_port_read_line, NULL));
  dfsch_define_cstr(ctx, "port-seek!",
                    dfsch_make_primitive(native_port_seek, NULL));
  dfsch_define_cstr(ctx, "port-tell",
                    dfsch_make_primitive(native_port_tell, NULL));
  dfsch_define_cstr(ctx, "string-output-port",
                    dfsch_make_primitive(native_string_output_port, NULL));
  dfsch_define_cstr(ctx, "string-output-port-value",
                    dfsch_make_primitive(native_string_output_port_value,
                                         NULL));
  dfsch_define_cstr(ctx, "string-input-port",
                    dfsch_make_primitive(native_string_input_port, NULL));
}
void dfsch_close_file_port (dfsch_object_t * port)
Definition at line 676 of file ports.c.
References file_port_t::close, DFSCH_ASSERT_INSTANCE, DFSCH_FILE_PORT_TYPE, file_port_t::file, and file_port_t::open.
Referenced by native_close_file_port().
{
  file_port_t* p = DFSCH_ASSERT_INSTANCE(port, DFSCH_FILE_PORT_TYPE);
  p = (file_port_t*) port;
  if (p->close && p->open){
    fclose(p->file);
    p->open = 0;
  }
}
dfsch_object_t* dfsch_current_error_port ()
Definition at line 323 of file ports.c.
References current_ports(), and current_ports_t::error_port.
Referenced by native_current_error_port().
{
  return current_ports()->error_port;
}
dfsch_object_t* dfsch_current_input_port ()
Definition at line 320 of file ports.c.
References current_ports(), and current_ports_t::input_port.
Referenced by native_current_input_port(), native_port_read_buf(), native_port_read_line(), native_port_write_buf(), and native_read().
{
  return current_ports()->input_port;
}
dfsch_object_t* dfsch_current_output_port ()
Definition at line 317 of file ports.c.
References current_ports(), and current_ports_t::output_port.
Referenced by native_current_output_port(), native_display(), native_newline(), and native_write().
{
  return current_ports()->output_port;
}
DFSCH_DEFINE_PRIMITIVE (port_read_whole , 0)
Definition at line 816 of file ports.c.
References DFSCH_ARG_END, dfsch_make_string_strbuf(), DFSCH_OBJECT_ARG, and dfsch_port_read_whole().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  return dfsch_make_string_strbuf(dfsch_port_read_whole(port));
}
dfsch_object_t* dfsch_eof_object ()
Definition at line 241 of file ports.c.
Referenced by dfsch_console_read_object(), and dfsch_parser_read_from_port().
{
  return (dfsch_object_t*)&eof_object;
}
int dfsch_eof_object_p (dfsch_object_t * obj)
Definition at line 244 of file ports.c.
Referenced by native_eof_object_p().
{
  return obj == &eof_object;
}
int dfsch_input_port_p (dfsch_object_t * port)
Definition at line 73 of file ports.c.
References DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_set_current_input_port().
{
  return DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE &&
    ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->read_buf;
}
dfsch_object_t* dfsch_make_file_port (FILE * file, int close, char * name)
Definition at line 621 of file ports.c.
References file_port_t::close, DFSCH_FILE_PORT_TYPE, dfsch_make_object(), file_port_t::file, file_port_finalizer(), file_port_t::name, and file_port_t::open.
Referenced by dfsch_open_file_port().
{
  file_port_t* port = (file_port_t*)dfsch_make_object(DFSCH_FILE_PORT_TYPE);
  port->file = file;
  port->close = close;
  port->name = name;
  port->open = 1; /* Creating closed ports makes no sense */
  if (close){
    GC_REGISTER_FINALIZER(port, (GC_finalization_proc)file_port_finalizer,
                          NULL, NULL, NULL);
  }
  return (dfsch_object_t*)port;
}
dfsch_object_t* dfsch_null_port ()
Definition at line 292 of file ports.c.
Referenced by native_null_port().
{
  return (dfsch_object_t*) &null_port;
}
DFSCH_OBJECT_CACHE (dfsch_make_file_port(stderr, 0,"(standard error)") , dfsch_standard_error_port)
DFSCH_OBJECT_CACHE (dfsch_make_file_port(stdout, 0,"(standard output)") , dfsch_standard_output_port)
DFSCH_OBJECT_CACHE (dfsch_make_file_port(stdin, 0,"(standard input)") , dfsch_standard_input_port)
dfsch_object_t* dfsch_open_file_port (char * filename, char * mode)
XXX
Definition at line 644 of file ports.c.
References dfsch_error(), dfsch_make_file_port(), dfsch_make_string_cstr(), and dfsch_operating_system_error().
Referenced by native_open_file_port().
{
  FILE* file;
  if (mode[0] != 'r' && mode[0] != 'w' && mode[0] != 'a'){
    dfsch_error("Invalid file port mode",
                dfsch_make_string_cstr(mode));
  }
  if (mode[1] != 0){
    if (mode[1] != '+' && mode[1] != 'b'){
      dfsch_error("Invalid file port mode",
                  dfsch_make_string_cstr(mode));
    }
    if (mode[2] != 0){
      if ((mode[2] != '+' && mode[2] != 'b')
          || (mode[2] == mode[1])
          || (mode[3] != 0)){
        dfsch_error("Invalid file port mode",
                    dfsch_make_string_cstr(mode));
      }
    }
  }
  file = fopen(filename, mode);
  if (!file){
      dfsch_operating_system_error("fopen");
  }
  return dfsch_make_file_port(file, 1, filename);
}
int dfsch_output_port_p (dfsch_object_t * port)
Definition at line 69 of file ports.c.
References DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_set_current_error_port(), and dfsch_set_current_output_port().
{
  return DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE &&
    ((dfsch_port_type_t*)DFSCH_TYPE_OF(port))->write_buf;
}
int dfsch_port_batch_read (dfsch_object_t * port)
Definition at line 160 of file ports.c.
References dfsch_error(), dfsch_port_read_buf(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_parser_read_from_port(), and dfsch_port_readline().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read){
      return ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read(port);
    } else {
      char buf;
      if (dfsch_port_read_buf(port, &buf, 1) != 1){
        return -1;
      } else {
        return buf;
      }
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_batch_read_end (dfsch_object_t * port)
Definition at line 151 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_parser_read_from_port(), and dfsch_port_readline().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_end){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_end(port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_batch_read_start (dfsch_object_t * port)
Definition at line 142 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_parser_read_from_port(), and dfsch_port_readline().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_start){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_start(port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
int dfsch_port_p (dfsch_object_t * port)
Definition at line 66 of file ports.c.
References DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
{
  return DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE;
}
ssize_t dfsch_port_read_buf (dfsch_object_t * port, char * buf, size_t size)
Definition at line 95 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_port_batch_read(), dfsch_port_read_whole(), dfsch_sxml_parse_port(), dfsch_xml_parse_port(), and native_port_read_buf().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->read_buf){
      return ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->read_buf(port,
                                                                   buf, size);
    } else {
      dfsch_error("Not an input port", port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
dfsch_strbuf_t* dfsch_port_read_whole (dfsch_object_t * port)
Definition at line 108 of file ports.c.
References dfsch_port_read_buf(), sl_create, sl_nappend, and sl_value_strbuf.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  ssize_t ret;
  char* buf = GC_MALLOC_ATOMIC(1024);
  str_list_t* sl = sl_create();
  while ((ret = dfsch_port_read_buf(port, buf, 1024))){
    sl_nappend(sl, buf, ret);
    buf = GC_MALLOC_ATOMIC(1024);
  }
  return sl_value_strbuf(sl);
}
dfsch_strbuf_t* dfsch_port_readline (dfsch_object_t * port)
Definition at line 177 of file ports.c.
References dfsch_port_batch_read(), dfsch_port_batch_read_end(), dfsch_port_batch_read_start(), DFSCH_PROTECT, DFSCH_PROTECT_END, dfsch_strbuf_create(), and DFSCH_UNWIND.
Referenced by native_port_read_line().
{
  int ch;
  char* buf;
  size_t buflen;
  size_t len;
  buflen = 128;
  len = 0;
  buf = GC_MALLOC_ATOMIC(buflen);
  dfsch_port_batch_read_start(port);
  DFSCH_UNWIND {
    while (1){
      ch = dfsch_port_batch_read(port);
      if (ch == -1){
        break;
      }
      if (buflen <= len){
        buflen *= 2;
        buf = GC_REALLOC(buf, buflen);
      }
      buf[len] = ch;
      len++;
      if (ch == '\n'){
        break;
      }
    }
  } DFSCH_PROTECT {
    dfsch_port_batch_read_end(port);
  } DFSCH_PROTECT_END;
  if (len == 0){
    return NULL;
  }
  return dfsch_strbuf_create(buf, len);
}
void dfsch_port_seek (dfsch_object_t * port, int64_t offset, int whence)
Definition at line 119 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by native_port_seek().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->seek){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->seek(port, offset, whence);
    } else {
      dfsch_error("Port is not seekable", port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
int64_t dfsch_port_tell (dfsch_object_t * port)
Definition at line 130 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by native_port_tell().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->tell){
      return ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->tell(port);
    } else {
      return -1;
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_unsafe_register (dfsch_object_t * ctx)
Definition at line 988 of file ports.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_standard_error_port(), dfsch_standard_input_port(), dfsch_standard_output_port(), native_close_file_port(), native_open_file_port(), native_set_current_error_port(), native_set_current_input_port(), and native_set_current_output_port().
Referenced by main().
{
  dfsch_define_cstr(ctx, "set-current-output-port!",
                    dfsch_make_primitive(native_set_current_output_port, NULL));
  dfsch_define_cstr(ctx, "set-current-input-port!",
                    dfsch_make_primitive(native_set_current_input_port, NULL));
  dfsch_define_cstr(ctx, "set-current-error-port!",
                    dfsch_make_primitive(native_set_current_error_port, NULL));
  dfsch_define_cstr(ctx, "open-file-port",
                    dfsch_make_primitive(native_open_file_port, NULL));
  dfsch_define_cstr(ctx, "close-file-port!",
                    dfsch_make_primitive(native_close_file_port, NULL));
  dfsch_define_cstr(ctx, "*standard-input-port*",
                    dfsch_standard_input_port());
  dfsch_define_cstr(ctx, "*standard-output-port*",
                    dfsch_standard_output_port());
  dfsch_define_cstr(ctx, "*standard-error-port*",
                    dfsch_standard_error_port());
}
void dfsch_port_write_buf (dfsch_object_t * port, char * buf, size_t size)
Definition at line 79 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_port_write_cstr(), native_display(), native_newline(), native_port_write_buf(), and native_write().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->write_buf){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->write_buf(port, buf, size);
    } else {
      dfsch_error("Not an output port", port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_write_cstr (dfsch_object_t * port, char * str)
Definition at line 90 of file ports.c.
References dfsch_port_write_buf().
Referenced by dfsch_sxml_emit_port().
{
  dfsch_port_write_buf(port, str, strlen(str));
}
void dfsch_set_current_error_port (dfsch_object_t * port)
Definition at line 339 of file ports.c.
References current_ports(), dfsch_error(), dfsch_output_port_p(), and current_ports_t::error_port.
Referenced by native_set_current_error_port().
{
  if (!dfsch_output_port_p(port)){
    dfsch_error("Not an output port", port);
  }
  current_ports()->error_port = port;
}
void dfsch_set_current_input_port (dfsch_object_t * port)
Definition at line 333 of file ports.c.
References current_ports(), dfsch_error(), dfsch_input_port_p(), and current_ports_t::input_port.
Referenced by native_set_current_input_port().
{
  if (!dfsch_input_port_p(port)){
    dfsch_error("Not an input port", port);
  }
  current_ports()->input_port = port;
}
void dfsch_set_current_output_port (dfsch_object_t * port)
Definition at line 327 of file ports.c.
References current_ports(), dfsch_error(), dfsch_output_port_p(), and current_ports_t::output_port.
Referenced by native_set_current_output_port().
{
  if (!dfsch_output_port_p(port)){
    dfsch_error("Not an output port", port);
  }
  current_ports()->output_port = port;
}
dfsch_object_t* dfsch_string_input_port (char * buf, size_t len)
Definition at line 469 of file ports.c.
References string_input_port_t::buf, create_finalized_mutex, string_input_port_t::cur, dfsch_make_object(), DFSCH_STRING_INPUT_PORT_TYPE, string_input_port_t::len, and string_input_port_t::mutex.
Referenced by native_string_input_port().
{
  string_input_port_t* port =
    (string_input_port_t*)dfsch_make_object(DFSCH_STRING_INPUT_PORT_TYPE);
  port->buf = buf;
  port->len = len;
  port->cur = 0;
  port->mutex = create_finalized_mutex();
  return (dfsch_object_t*)port;
}
dfsch_object_t* dfsch_string_output_port ()
Definition at line 389 of file ports.c.
References create_finalized_mutex, dfsch_make_object(), DFSCH_STRING_OUTPUT_PORT_TYPE, string_output_port_t::list, string_output_port_t::mutex, and sl_create.
Referenced by native_string_output_port().
{
  string_output_port_t* port =
    (string_output_port_t*)dfsch_make_object(DFSCH_STRING_OUTPUT_PORT_TYPE);
  port->mutex = create_finalized_mutex();
  port->list = sl_create();
  return (dfsch_object_t*)port;
}
dfsch_strbuf_t* dfsch_string_output_port_value (dfsch_object_t * port)
Definition at line 398 of file ports.c.
References dfsch_error(), DFSCH_STRING_OUTPUT_PORT_TYPE, DFSCH_TYPE_OF, string_output_port_t::list, string_output_port_t::mutex, and sl_value_strbuf.
Referenced by native_string_output_port_value().
{
  string_output_port_t* p;
  dfsch_strbuf_t* buf;
  if (DFSCH_TYPE_OF(port) != DFSCH_STRING_OUTPUT_PORT_TYPE){
    dfsch_error("exceptiion:not-a-string-output-port", port);
  }
  p = (string_output_port_t*) port;
  pthread_mutex_lock(p->mutex);
  buf = sl_value_strbuf(p->list);
  pthread_mutex_unlock(p->mutex);
  return buf;
}
static void errno_error (char * name, dfsch_object_t * object, int e) [static]
Definition at line 498 of file ports.c.
References dfsch_error(), dfsch_list(), dfsch_make_number_from_long(), and dfsch_make_string_cstr().
{
  dfsch_error(name, dfsch_list(3,
                               object,
                               dfsch_make_number_from_long(e),
                               dfsch_make_string_cstr(strerror(e))));
}
static void file_port_finalizer (file_port_t * port, void * cd) [static]
Definition at line 614 of file ports.c.
References file_port_t::close, file_port_t::file, and file_port_t::open.
Referenced by dfsch_make_file_port().
{
  if (port->open && port->close){
    fclose(port->file);
    port->open = 0;
  }
}
static ssize_t file_port_read_buf (file_port_t * port, char * buf, size_t len) [static]
Definition at line 520 of file ports.c.
References dfsch_error(), dfsch_operating_system_error(), file_port_t::file, and file_port_t::open.
{
  size_t ret;
  if (!port->open){
    dfsch_error("Port is closed", port);
  }
  ret = fread(buf, 1, len, port->file);
  if (ret == 0){
    if (feof(port->file)){
      return 0;
    } else {
      dfsch_operating_system_error("fread");
    }
  }
  return ret;
}
static void file_port_seek (file_port_t * port, int64_t offset, int whence) [static]
Definition at line 553 of file ports.c.
References dfsch_error(), dfsch_operating_system_error(), file_port_t::file, and file_port_t::open.
{
  if (!port->open){
    dfsch_error("exception:port-closed", port);
  }
  if (fseek(port->file, offset, whence) != 0){
    dfsch_operating_system_error("fseek");
  }
}
static int64_t file_port_tell (file_port_t * port) [static]
Definition at line 563 of file ports.c.
References dfsch_error(), dfsch_operating_system_error(), file_port_t::file, and file_port_t::open.
{
  off_t ret;
  if (!port->open){
    dfsch_error("exception:port-closed", port);
  }
  ret = ftell(port->file);
  if (ret == -1){
    dfsch_operating_system_error("ftell");
  }
  return ret;
}
static void file_port_write (file_port_t * port, dfsch_writer_state_t * state) [static]
Definition at line 538 of file ports.c.
References dfsch_write_unreadable(), file_port_t::file, file_port_t::name, and file_port_t::open.
{
  if (port->open){
    if (port->name){
      dfsch_write_unreadable(state, port,
                             "name %s fd %d",
                             port->name,
                             fileno(port->file));
    } else {
      dfsch_write_unreadable(state, port, "fd %d", fileno(port->file));
    }
  } else {
    dfsch_write_unreadable(state, port, "*closed*");
  }
}
static void file_port_write_buf (file_port_t * port, char * buf, size_t len) [static]
Definition at line 505 of file ports.c.
References dfsch_error(), dfsch_operating_system_error(), file_port_t::file, and file_port_t::open.
{
  size_t ret;
  if (!port->open){
    dfsch_error("Port is closed", port);
  }
  if (len != 0){
    ret = fwrite(buf, len, 1, port->file);
    if (ret == 0){
      dfsch_operating_system_error("fwrite");
    }
  }
}
static dfsch_object_t* native_close_file_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 927 of file ports.c.
References DFSCH_ARG_END, dfsch_close_file_port(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_port_unsafe_register().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  dfsch_close_file_port(port);
  return NULL;
}
static dfsch_object_t* native_current_error_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 703 of file ports.c.
References DFSCH_ARG_END, and dfsch_current_error_port().
Referenced by dfsch__port_native_register().
{
  DFSCH_ARG_END(args);
  return dfsch_current_error_port();
}
static dfsch_object_t* native_current_input_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 697 of file ports.c.
References DFSCH_ARG_END, and dfsch_current_input_port().
Referenced by dfsch__port_native_register().
{
  DFSCH_ARG_END(args);
  return dfsch_current_input_port();
}
static dfsch_object_t* native_current_output_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 691 of file ports.c.
References DFSCH_ARG_END, and dfsch_current_output_port().
Referenced by dfsch__port_native_register().
{
  DFSCH_ARG_END(args);
  return dfsch_current_output_port();
}
static dfsch_object_t* native_display (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 757 of file ports.c.
References DFSCH_ARG_END, dfsch_current_output_port(), dfsch_object_2_string(), DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, and dfsch_port_write_buf().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  dfsch_object_t* object;
  char *buf;
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_output_port());
  DFSCH_ARG_END(args);
  buf = dfsch_object_2_string(object, 1000, 0);
  dfsch_port_write_buf(port, buf, strlen(buf));
  return NULL;
}
static dfsch_object_t* native_eof_object_p (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 906 of file ports.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_eof_object_p(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* object;
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_eof_object_p(object));
}
static dfsch_object_t* native_newline (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 772 of file ports.c.
References DFSCH_ARG_END, dfsch_current_output_port(), DFSCH_OBJECT_ARG_OPT, and dfsch_port_write_buf().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  char *buf;
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_output_port());
  DFSCH_ARG_END(args);
  dfsch_port_write_buf(port, "\n", 1);
  return NULL;
}
static dfsch_object_t* native_null_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 736 of file ports.c.
References DFSCH_ARG_END, and dfsch_null_port().
Referenced by dfsch__port_native_register().
{
  DFSCH_ARG_END(args);
  return dfsch_null_port();
}
static dfsch_object_t* native_open_file_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 916 of file ports.c.
References DFSCH_ARG_END, dfsch_open_file_port(), and DFSCH_STRING_ARG.
Referenced by dfsch_port_unsafe_register().
{
  char* fname;
  char* mode;
  DFSCH_STRING_ARG(args, fname);
  DFSCH_STRING_ARG(args, mode);
  DFSCH_ARG_END(args);
  return dfsch_open_file_port(fname, mode);
}
static dfsch_object_t* native_port_read_buf (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 796 of file ports.c.
References DFSCH_ARG_END, dfsch_current_input_port(), DFSCH_LONG_ARG, dfsch_make_string_buf(), DFSCH_OBJECT_ARG_OPT, and dfsch_port_read_buf().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  size_t len;
  char* buf;
  DFSCH_LONG_ARG(args, len);
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_input_port());
  DFSCH_ARG_END(args);
  buf = GC_MALLOC_ATOMIC(len);
  len = dfsch_port_read_buf(port, buf, len);
  if (len == 0){
    return NULL;
  }
  return dfsch_make_string_buf(buf, len);
}
static dfsch_object_t* native_port_read_line (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 823 of file ports.c.
References DFSCH_ARG_END, dfsch_current_input_port(), dfsch_make_string_strbuf(), DFSCH_OBJECT_ARG_OPT, and dfsch_port_readline().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  dfsch_strbuf_t* buf;
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_input_port());
  DFSCH_ARG_END(args);
  buf = dfsch_port_readline(port);
  if (!buf){
    return NULL;
  }
  return dfsch_make_string_strbuf(buf);
}
static dfsch_object_t* native_port_seek (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 852 of file ports.c.
References DFSCH_FLAG_PARSER_BEGIN_ONE_OPT, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_VALUE, DFSCH_INT64_ARG, DFSCH_OBJECT_ARG, and dfsch_port_seek().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  int64_t offset;
  int whence = SEEK_SET;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_INT64_ARG(args, offset);
  DFSCH_FLAG_PARSER_BEGIN_ONE_OPT(args, whence);
  DFSCH_FLAG_VALUE("set", SEEK_SET, whence);
  DFSCH_FLAG_VALUE("cur", SEEK_CUR, whence);
  DFSCH_FLAG_VALUE("end", SEEK_END, whence);
  DFSCH_FLAG_PARSER_END(args);
  dfsch_port_seek(port, offset, whence);
  return NULL;
}
static dfsch_object_t* native_port_tell (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 871 of file ports.c.
References DFSCH_ARG_END, dfsch_make_number_from_long(), DFSCH_OBJECT_ARG, and dfsch_port_tell().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  char *buf;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(dfsch_port_tell(port));
}
static dfsch_object_t* native_port_write_buf (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 839 of file ports.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_current_input_port(), DFSCH_OBJECT_ARG_OPT, dfsch_port_write_buf(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  dfsch_strbuf_t* buf;
  DFSCH_BUFFER_ARG(args, buf);
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_input_port());
  DFSCH_ARG_END(args);
  dfsch_port_write_buf(port, buf->ptr, buf->len);
  return NULL;
}
static dfsch_object_t* native_read (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 785 of file ports.c.
References DFSCH_ARG_END, dfsch_current_input_port(), DFSCH_OBJECT_ARG_OPT, and dfsch_parser_read_from_port().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  char *buf;
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_input_port());
  DFSCH_ARG_END(args);
  return dfsch_parser_read_from_port(port);
}
static dfsch_object_t* native_set_current_error_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 727 of file ports.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_set_current_error_port().
Referenced by dfsch_port_unsafe_register().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  dfsch_set_current_error_port(port);
  return NULL;
}
static dfsch_object_t* native_set_current_input_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 718 of file ports.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_set_current_input_port().
Referenced by dfsch_port_unsafe_register().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  dfsch_set_current_input_port(port);
  return NULL;
}
static dfsch_object_t* native_set_current_output_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 709 of file ports.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_set_current_output_port().
Referenced by dfsch_port_unsafe_register().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  dfsch_set_current_output_port(port);
  return NULL;
}
static dfsch_object_t* native_string_input_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 897 of file ports.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_string_input_port(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by dfsch__port_native_register().
{
  dfsch_strbuf_t* string;
  DFSCH_BUFFER_ARG(args, string);
  DFSCH_ARG_END(args);
  return dfsch_string_input_port(string->ptr, string->len);
}
static dfsch_object_t* native_string_output_port (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 882 of file ports.c.
References DFSCH_ARG_END, and dfsch_string_output_port().
Referenced by dfsch__port_native_register().
{
  DFSCH_ARG_END(args);
  return dfsch_string_output_port();
}
static dfsch_object_t* native_string_output_port_value (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 888 of file ports.c.
References DFSCH_ARG_END, dfsch_make_string_strbuf(), DFSCH_OBJECT_ARG, and dfsch_string_output_port_value().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  return dfsch_make_string_strbuf(dfsch_string_output_port_value(port));
}
static dfsch_object_t* native_write (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 742 of file ports.c.
References DFSCH_ARG_END, dfsch_current_output_port(), dfsch_object_2_string(), DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, and dfsch_port_write_buf().
Referenced by dfsch__port_native_register().
{
  dfsch_object_t* port;
  dfsch_object_t* object;
  char *buf;
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_OBJECT_ARG_OPT(args, port, dfsch_current_output_port());
  DFSCH_ARG_END(args);
  buf = dfsch_object_2_string(object, 1000, 1);
  dfsch_port_write_buf(port, buf, strlen(buf));
  return NULL;
}
static ssize_t null_port_read_buf (dfsch_object_t * port, char * buf, size_t len) [static]
Definition at line 262 of file ports.c.
{
  return 0;
}
static void null_port_write_buf (dfsch_object_t * port, char * buf, size_t len) [static]
Definition at line 259 of file ports.c.
{
}
static ssize_t string_input_port_read_buf (string_input_port_t * port, char * buf, size_t len) [static]
Definition at line 426 of file ports.c.
References string_input_port_t::buf, string_input_port_t::cur, string_input_port_t::len, and string_input_port_t::mutex.
{
  size_t rlen;
  pthread_mutex_lock(port->mutex);
  if (port->len < len + port->cur){
    len = port->len - port->cur;
  }
  memcpy(buf, port->buf + port->cur, len);
  port->cur += len;
  pthread_mutex_unlock(port->mutex);
  return len;
}
static void string_output_port_write_buf (string_output_port_t * port, char * buf, size_t len) [static]
Definition at line 357 of file ports.c.
References string_output_port_t::list, string_output_port_t::mutex, and sl_nappend.
{
  pthread_mutex_lock(port->mutex);
  sl_nappend(port->list, buf, len);
  pthread_mutex_unlock(port->mutex);
}
Variable Documentation
dfsch_type_t dfsch_eof_object_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(eof_object_t),
  "eof-object",
  NULL,
  NULL,
  NULL
}
Definition at line 227 of file ports.c.
dfsch_port_type_t dfsch_file_port_type
Initial value:
 {
  {
    DFSCH_PORT_TYPE_TYPE,
    DFSCH_PORT_TYPE,
    sizeof(file_port_t),
    "file-port",
    NULL,
    (dfsch_type_write_t)file_port_write,
    NULL,
    NULL,
    &file_port_slots,
    "port backed by stdio stream"
  },
  (dfsch_port_write_buf_t)file_port_write_buf,
  (dfsch_port_read_buf_t)file_port_read_buf,
  (dfsch_port_seek_t)file_port_seek,
  (dfsch_port_tell_t)file_port_tell,
  NULL,
  NULL,
  NULL
}
Definition at line 588 of file ports.c.
dfsch_port_type_t dfsch_null_port_type
Initial value:
 {
  {
    DFSCH_PORT_TYPE_TYPE,
    DFSCH_PORT_TYPE,
    sizeof(null_port_t),
    "null-port",
    NULL,
    NULL,
    NULL
  },
  null_port_write_buf,
  null_port_read_buf,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 267 of file ports.c.
dfsch_type_t dfsch_port_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "port",
  NULL,
  NULL,
  NULL
}
Definition at line 46 of file ports.c.
dfsch_type_t dfsch_port_type_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_port_type_t),
  "port-type",
  NULL,
  NULL,
  NULL
}
Type of port types.
Definition at line 56 of file ports.c.
dfsch_port_type_t dfsch_string_input_port_type
Initial value:
 {
  {
    DFSCH_PORT_TYPE_TYPE,
    DFSCH_PORT_TYPE,
    sizeof(string_input_port_t),
    "string-input-port",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "Input-only port backed by string"
  },
  NULL,
  (dfsch_port_read_buf_t)string_input_port_read_buf,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 444 of file ports.c.
dfsch_port_type_t dfsch_string_output_port_type
Initial value:
 {
  {
    DFSCH_PORT_TYPE_TYPE,
    DFSCH_PORT_TYPE,
    sizeof(string_output_port_t),
    "string-output-port",
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    "Output only port backed by string"
  },
  (dfsch_port_write_buf_t)string_output_port_write_buf,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 364 of file ports.c.
eof_object_t eof_object
Initial value:
 {
  &dfsch_eof_object_type
}
Definition at line 237 of file ports.c.
dfsch_slot_t file_port_slots[] [static]
Initial value:
 {
  DFSCH_STRING_SLOT(file_port_t, name, DFSCH_SLOT_ACCESS_RO,
                    "Filename associated to port"),
  DFSCH_BOOLEAN_SLOT(file_port_t, open, DFSCH_SLOT_ACCESS_RO,
                     "Is port open for accesses?"),
  DFSCH_BOOLEAN_SLOT(file_port_t, close, DFSCH_SLOT_ACCESS_RO,
                     "Will port be automatically closed by GC?"),
  DFSCH_SLOT_TERMINATOR,
}
Definition at line 578 of file ports.c.
null_port_t null_port [static]
Initial value:
 {
  &dfsch_null_port_type
}
Definition at line 288 of file ports.c.