dfsch: dfsch/ports.h File Reference
dfsch/ports.h File Reference
#include <dfsch/dfsch.h>
#include <sys/types.h>
#include <stdio.h>
#include <dfsch/strings.h>
#include <stdint.h>
Data Structures
struct dfsch_port_type_t
Defines
#define DFSCH_EOF_OBJECT_TYPE (&dfsch_eof_object_type)
#define DFSCH_FILE_PORT_TYPE (&dfsch_file_port_type)
#define DFSCH_NULL_PORT_TYPE (&dfsch_null_port_type)
#define DFSCH_PORT_TYPE (&dfsch_port_type)
#define DFSCH_PORT_TYPE_TYPE (&dfsch_port_type_type)
#define DFSCH_STRING_INPUT_PORT_TYPE (&dfsch_string_input_port_type)
#define DFSCH_STRING_OUTPUT_PORT_TYPE (&dfsch_string_output_port_type)
Typedefs
typedef void(* dfsch_port_batch_read_end_t)(dfsch_object_t *port)
typedef void(* dfsch_port_batch_read_start_t)(dfsch_object_t *port)
typedef int(* dfsch_port_batch_read_t)(dfsch_object_t *port)
typedef int(* dfsch_port_get_caps_t)(dfsch_object_t *port)
typedef ssize_t(* dfsch_port_read_buf_t)(dfsch_object_t *port, char *buf, size_t size)
typedef void(* dfsch_port_seek_t)(dfsch_object_t *port, int64_t offset, int whence)
typedef int64_t(* dfsch_port_tell_t)(dfsch_object_t *port)
typedef void(* dfsch_port_write_buf_t)(dfsch_object_t *port, char *buf, size_t size)
Functions
void dfsch_close_file_port (dfsch_object_t *port)
dfsch_object_t * dfsch_current_error_port ()
dfsch_object_t * dfsch_current_input_port ()
dfsch_object_t * dfsch_current_output_port ()
dfsch_object_t * dfsch_eof_object ()
int dfsch_eof_object_p (dfsch_object_t *obj)
int dfsch_input_port_p (dfsch_object_t *obj)
dfsch_object_t * dfsch_make_file_port (FILE *file, int close, char *name)
dfsch_object_t * dfsch_null_port ()
dfsch_object_t * dfsch_open_file_port (char *filename, char *mode)
int dfsch_output_port_p (dfsch_object_t *obj)
int dfsch_port_batch_read (dfsch_object_t *port)
void dfsch_port_batch_read_end (dfsch_object_t *port)
void dfsch_port_batch_read_start (dfsch_object_t *port)
int dfsch_port_p (dfsch_object_t *obj)
ssize_t dfsch_port_read_buf (dfsch_object_t *port, char *buf, size_t size)
dfsch_strbuf_t * dfsch_port_read_whole (dfsch_object_t *port)
dfsch_strbuf_t * dfsch_port_readline (dfsch_object_t *port)
void dfsch_port_seek (dfsch_object_t *port, int64_t offset, int whence)
int64_t dfsch_port_tell (dfsch_object_t *port)
void dfsch_port_unsafe_register (dfsch_object_t *ctx)
void dfsch_port_write_buf (dfsch_object_t *port, char *buf, size_t size)
void dfsch_port_write_cstr (dfsch_object_t *port, char *str)
void dfsch_set_current_error_port (dfsch_object_t *port)
void dfsch_set_current_input_port (dfsch_object_t *port)
void dfsch_set_current_output_port (dfsch_object_t *port)
dfsch_object_t * dfsch_standard_error_port ()
dfsch_object_t * dfsch_standard_input_port ()
dfsch_object_t * dfsch_standard_output_port ()
dfsch_object_t * dfsch_string_output_port ()
dfsch_strbuf_t * dfsch_string_output_port_value (dfsch_object_t *port)
Variables
dfsch_type_t dfsch_eof_object_type
dfsch_port_type_t dfsch_file_port_type
dfsch_port_type_t dfsch_null_port_type
dfsch_type_t dfsch_port_type
dfsch_type_t dfsch_port_type_type
dfsch_port_type_t dfsch_string_input_port_type
dfsch_port_type_t dfsch_string_output_port_type
Define Documentation
#define DFSCH_EOF_OBJECT_TYPE (&dfsch_eof_object_type)
Definition at line 117 of file ports.h.
Referenced by dfsch__port_native_register().
#define DFSCH_FILE_PORT_TYPE (&dfsch_file_port_type)
Definition at line 125 of file ports.h.
Referenced by dfsch__port_native_register(), dfsch_close_file_port(), and dfsch_make_file_port().
#define DFSCH_NULL_PORT_TYPE (&dfsch_null_port_type)
Definition at line 119 of file ports.h.
Referenced by dfsch__port_native_register().
#define DFSCH_PORT_TYPE (&dfsch_port_type)
Definition at line 115 of file ports.h.
#define DFSCH_PORT_TYPE_TYPE (&dfsch_port_type_type)
Pointer to type of port types.
Definition at line 112 of file ports.h.
Referenced by dfsch_input_port_p(), dfsch_output_port_p(), dfsch_port_batch_read(), dfsch_port_batch_read_end(), dfsch_port_batch_read_start(), dfsch_port_p(), dfsch_port_read_buf(), dfsch_port_seek(), dfsch_port_tell(), and dfsch_port_write_buf().
#define DFSCH_STRING_INPUT_PORT_TYPE (&dfsch_string_input_port_type)
Definition at line 123 of file ports.h.
Referenced by dfsch__port_native_register(), and dfsch_string_input_port().
#define DFSCH_STRING_OUTPUT_PORT_TYPE (&dfsch_string_output_port_type)
Definition at line 121 of file ports.h.
Referenced by dfsch__port_native_register(), dfsch_string_output_port(), and dfsch_string_output_port_value().
Typedef Documentation
typedef void(* dfsch_port_batch_read_end_t)(dfsch_object_t *port)
Definition at line 50 of file ports.h.
typedef void(* dfsch_port_batch_read_start_t)(dfsch_object_t *port)
Definition at line 49 of file ports.h.
typedef int(* dfsch_port_batch_read_t)(dfsch_object_t *port)
Definition at line 51 of file ports.h.
typedef int(* dfsch_port_get_caps_t)(dfsch_object_t *port)
Definition at line 53 of file ports.h.
typedef ssize_t(* dfsch_port_read_buf_t)(dfsch_object_t *port, char *buf, size_t size)
Definition at line 43 of file ports.h.
typedef void(* dfsch_port_seek_t)(dfsch_object_t *port, int64_t offset, int whence)
Definition at line 45 of file ports.h.
typedef int64_t(* dfsch_port_tell_t)(dfsch_object_t *port)
Definition at line 47 of file ports.h.
typedef void(* dfsch_port_write_buf_t)(dfsch_object_t *port, char *buf, size_t size)
Definition at line 41 of file ports.h.
Function Documentation
void dfsch_close_file_port (dfsch_object_t * port)
Definition at line 676 of file ports.c.
References file_port_t::close, DFSCH_ASSERT_INSTANCE, DFSCH_FILE_PORT_TYPE, file_port_t::file, and file_port_t::open.
Referenced by native_close_file_port().
{
  file_port_t* p = DFSCH_ASSERT_INSTANCE(port, DFSCH_FILE_PORT_TYPE);
  p = (file_port_t*) port;
  if (p->close && p->open){
    fclose(p->file);
    p->open = 0;
  }
}
dfsch_object_t* dfsch_current_error_port ()
Definition at line 323 of file ports.c.
References current_ports(), and current_ports_t::error_port.
Referenced by native_current_error_port().
{
  return current_ports()->error_port;
}
dfsch_object_t* dfsch_current_input_port ()
Definition at line 320 of file ports.c.
References current_ports(), and current_ports_t::input_port.
Referenced by native_current_input_port(), native_port_read_buf(), native_port_read_line(), native_port_write_buf(), and native_read().
{
  return current_ports()->input_port;
}
dfsch_object_t* dfsch_current_output_port ()
Definition at line 317 of file ports.c.
References current_ports(), and current_ports_t::output_port.
Referenced by native_current_output_port(), native_display(), native_newline(), and native_write().
{
  return current_ports()->output_port;
}
dfsch_object_t* dfsch_eof_object ()
Definition at line 241 of file ports.c.
Referenced by dfsch_console_read_object(), and dfsch_parser_read_from_port().
{
  return (dfsch_object_t*)&eof_object;
}
int dfsch_eof_object_p (dfsch_object_t * obj)
Definition at line 244 of file ports.c.
Referenced by native_eof_object_p().
{
  return obj == &eof_object;
}
int dfsch_input_port_p (dfsch_object_t * obj)
Definition at line 73 of file ports.c.
References DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_set_current_input_port().
{
  return DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE &&
    ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->read_buf;
}
dfsch_object_t* dfsch_make_file_port (FILE * file, int close, char * name)
Definition at line 621 of file ports.c.
References file_port_t::close, DFSCH_FILE_PORT_TYPE, dfsch_make_object(), file_port_t::file, file_port_finalizer(), file_port_t::name, and file_port_t::open.
Referenced by dfsch_open_file_port().
{
  file_port_t* port = (file_port_t*)dfsch_make_object(DFSCH_FILE_PORT_TYPE);
  port->file = file;
  port->close = close;
  port->name = name;
  port->open = 1; /* Creating closed ports makes no sense */
  if (close){
    GC_REGISTER_FINALIZER(port, (GC_finalization_proc)file_port_finalizer,
                          NULL, NULL, NULL);
  }
  return (dfsch_object_t*)port;
}
dfsch_object_t* dfsch_null_port ()
Definition at line 292 of file ports.c.
Referenced by native_null_port().
{
  return (dfsch_object_t*) &null_port;
}
dfsch_object_t* dfsch_open_file_port (char * filename, char * mode)
XXX
Definition at line 644 of file ports.c.
References dfsch_error(), dfsch_make_file_port(), dfsch_make_string_cstr(), and dfsch_operating_system_error().
Referenced by native_open_file_port().
{
  FILE* file;
  if (mode[0] != 'r' && mode[0] != 'w' && mode[0] != 'a'){
    dfsch_error("Invalid file port mode",
                dfsch_make_string_cstr(mode));
  }
  if (mode[1] != 0){
    if (mode[1] != '+' && mode[1] != 'b'){
      dfsch_error("Invalid file port mode",
                  dfsch_make_string_cstr(mode));
    }
    if (mode[2] != 0){
      if ((mode[2] != '+' && mode[2] != 'b')
          || (mode[2] == mode[1])
          || (mode[3] != 0)){
        dfsch_error("Invalid file port mode",
                    dfsch_make_string_cstr(mode));
      }
    }
  }
  file = fopen(filename, mode);
  if (!file){
      dfsch_operating_system_error("fopen");
  }
  return dfsch_make_file_port(file, 1, filename);
}
int dfsch_output_port_p (dfsch_object_t * obj)
Definition at line 69 of file ports.c.
References DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_set_current_error_port(), and dfsch_set_current_output_port().
{
  return DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE &&
    ((dfsch_port_type_t*)DFSCH_TYPE_OF(port))->write_buf;
}
int dfsch_port_batch_read (dfsch_object_t * port)
Definition at line 160 of file ports.c.
References dfsch_error(), dfsch_port_read_buf(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_parser_read_from_port(), and dfsch_port_readline().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read){
      return ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read(port);
    } else {
      char buf;
      if (dfsch_port_read_buf(port, &buf, 1) != 1){
        return -1;
      } else {
        return buf;
      }
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_batch_read_end (dfsch_object_t * port)
Definition at line 151 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_parser_read_from_port(), and dfsch_port_readline().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_end){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_end(port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_batch_read_start (dfsch_object_t * port)
Definition at line 142 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_parser_read_from_port(), and dfsch_port_readline().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_start){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->batch_read_start(port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
int dfsch_port_p (dfsch_object_t * obj)
Definition at line 66 of file ports.c.
References DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
{
  return DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE;
}
ssize_t dfsch_port_read_buf (dfsch_object_t * port, char * buf, size_t size)
Definition at line 95 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_port_batch_read(), dfsch_port_read_whole(), dfsch_sxml_parse_port(), dfsch_xml_parse_port(), and native_port_read_buf().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->read_buf){
      return ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->read_buf(port,
                                                                   buf, size);
    } else {
      dfsch_error("Not an input port", port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
dfsch_strbuf_t* dfsch_port_read_whole (dfsch_object_t * port)
Definition at line 108 of file ports.c.
References dfsch_port_read_buf(), sl_create, sl_nappend, and sl_value_strbuf.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  ssize_t ret;
  char* buf = GC_MALLOC_ATOMIC(1024);
  str_list_t* sl = sl_create();
  while ((ret = dfsch_port_read_buf(port, buf, 1024))){
    sl_nappend(sl, buf, ret);
    buf = GC_MALLOC_ATOMIC(1024);
  }
  return sl_value_strbuf(sl);
}
dfsch_strbuf_t* dfsch_port_readline (dfsch_object_t * port)
Definition at line 177 of file ports.c.
References dfsch_port_batch_read(), dfsch_port_batch_read_end(), dfsch_port_batch_read_start(), DFSCH_PROTECT, DFSCH_PROTECT_END, dfsch_strbuf_create(), and DFSCH_UNWIND.
Referenced by native_port_read_line().
{
  int ch;
  char* buf;
  size_t buflen;
  size_t len;
  buflen = 128;
  len = 0;
  buf = GC_MALLOC_ATOMIC(buflen);
  dfsch_port_batch_read_start(port);
  DFSCH_UNWIND {
    while (1){
      ch = dfsch_port_batch_read(port);
      if (ch == -1){
        break;
      }
      if (buflen <= len){
        buflen *= 2;
        buf = GC_REALLOC(buf, buflen);
      }
      buf[len] = ch;
      len++;
      if (ch == '\n'){
        break;
      }
    }
  } DFSCH_PROTECT {
    dfsch_port_batch_read_end(port);
  } DFSCH_PROTECT_END;
  if (len == 0){
    return NULL;
  }
  return dfsch_strbuf_create(buf, len);
}
void dfsch_port_seek (dfsch_object_t * port, int64_t offset, int whence)
Definition at line 119 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by native_port_seek().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->seek){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->seek(port, offset, whence);
    } else {
      dfsch_error("Port is not seekable", port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
int64_t dfsch_port_tell (dfsch_object_t * port)
Definition at line 130 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by native_port_tell().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->tell){
      return ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->tell(port);
    } else {
      return -1;
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_unsafe_register (dfsch_object_t * ctx)
Definition at line 988 of file ports.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_standard_error_port(), dfsch_standard_input_port(), dfsch_standard_output_port(), native_close_file_port(), native_open_file_port(), native_set_current_error_port(), native_set_current_input_port(), and native_set_current_output_port().
Referenced by main().
{
  dfsch_define_cstr(ctx, "set-current-output-port!",
                    dfsch_make_primitive(native_set_current_output_port, NULL));
  dfsch_define_cstr(ctx, "set-current-input-port!",
                    dfsch_make_primitive(native_set_current_input_port, NULL));
  dfsch_define_cstr(ctx, "set-current-error-port!",
                    dfsch_make_primitive(native_set_current_error_port, NULL));
  dfsch_define_cstr(ctx, "open-file-port",
                    dfsch_make_primitive(native_open_file_port, NULL));
  dfsch_define_cstr(ctx, "close-file-port!",
                    dfsch_make_primitive(native_close_file_port, NULL));
  dfsch_define_cstr(ctx, "*standard-input-port*",
                    dfsch_standard_input_port());
  dfsch_define_cstr(ctx, "*standard-output-port*",
                    dfsch_standard_output_port());
  dfsch_define_cstr(ctx, "*standard-error-port*",
                    dfsch_standard_error_port());
}
void dfsch_port_write_buf (dfsch_object_t * port, char * buf, size_t size)
Definition at line 79 of file ports.c.
References dfsch_error(), DFSCH_PORT_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by dfsch_port_write_cstr(), native_display(), native_newline(), native_port_write_buf(), and native_write().
{
  if (DFSCH_TYPE_OF(port)->type == DFSCH_PORT_TYPE_TYPE){
    if (((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->write_buf){
      ((dfsch_port_type_t*)(DFSCH_TYPE_OF(port)))->write_buf(port, buf, size);
    } else {
      dfsch_error("Not an output port", port);
    }
  } else {
    dfsch_error("Not a port", port);
  }
}
void dfsch_port_write_cstr (dfsch_object_t * port, char * str)
Definition at line 90 of file ports.c.
References dfsch_port_write_buf().
Referenced by dfsch_sxml_emit_port().
{
  dfsch_port_write_buf(port, str, strlen(str));
}
void dfsch_set_current_error_port (dfsch_object_t * port)
Definition at line 339 of file ports.c.
References current_ports(), dfsch_error(), dfsch_output_port_p(), and current_ports_t::error_port.
Referenced by native_set_current_error_port().
{
  if (!dfsch_output_port_p(port)){
    dfsch_error("Not an output port", port);
  }
  current_ports()->error_port = port;
}
void dfsch_set_current_input_port (dfsch_object_t * port)
Definition at line 333 of file ports.c.
References current_ports(), dfsch_error(), dfsch_input_port_p(), and current_ports_t::input_port.
Referenced by native_set_current_input_port().
{
  if (!dfsch_input_port_p(port)){
    dfsch_error("Not an input port", port);
  }
  current_ports()->input_port = port;
}
void dfsch_set_current_output_port (dfsch_object_t * port)
Definition at line 327 of file ports.c.
References current_ports(), dfsch_error(), dfsch_output_port_p(), and current_ports_t::output_port.
Referenced by native_set_current_output_port().
{
  if (!dfsch_output_port_p(port)){
    dfsch_error("Not an output port", port);
  }
  current_ports()->output_port = port;
}
dfsch_object_t* dfsch_standard_error_port ()
Referenced by dfsch_port_unsafe_register().
dfsch_object_t* dfsch_standard_input_port ()
Referenced by dfsch_port_unsafe_register().
dfsch_object_t* dfsch_standard_output_port ()
Referenced by dfsch_port_unsafe_register().
dfsch_object_t* dfsch_string_output_port ()
Definition at line 389 of file ports.c.
References create_finalized_mutex, dfsch_make_object(), DFSCH_STRING_OUTPUT_PORT_TYPE, string_output_port_t::list, string_output_port_t::mutex, and sl_create.
Referenced by native_string_output_port().
{
  string_output_port_t* port =
    (string_output_port_t*)dfsch_make_object(DFSCH_STRING_OUTPUT_PORT_TYPE);
  port->mutex = create_finalized_mutex();
  port->list = sl_create();
  return (dfsch_object_t*)port;
}
dfsch_strbuf_t* dfsch_string_output_port_value (dfsch_object_t * port)
Definition at line 398 of file ports.c.
References dfsch_error(), DFSCH_STRING_OUTPUT_PORT_TYPE, DFSCH_TYPE_OF, string_output_port_t::list, string_output_port_t::mutex, and sl_value_strbuf.
Referenced by native_string_output_port_value().
{
  string_output_port_t* p;
  dfsch_strbuf_t* buf;
  if (DFSCH_TYPE_OF(port) != DFSCH_STRING_OUTPUT_PORT_TYPE){
    dfsch_error("exceptiion:not-a-string-output-port", port);
  }
  p = (string_output_port_t*) port;
  pthread_mutex_lock(p->mutex);
  buf = sl_value_strbuf(p->list);
  pthread_mutex_unlock(p->mutex);
  return buf;
}
Variable Documentation
dfsch_type_t dfsch_eof_object_type
Definition at line 227 of file ports.c.
dfsch_port_type_t dfsch_file_port_type
Definition at line 588 of file ports.c.
dfsch_port_type_t dfsch_null_port_type
Definition at line 267 of file ports.c.
dfsch_type_t dfsch_port_type
Definition at line 46 of file ports.c.
dfsch_type_t dfsch_port_type_type
Type of port types.
Definition at line 56 of file ports.c.
dfsch_port_type_t dfsch_string_input_port_type
Definition at line 444 of file ports.c.
dfsch_port_type_t dfsch_string_output_port_type
Definition at line 364 of file ports.c.