dfsch: lib/process.c File Reference
lib/process.c File Reference
#include "dfsch/lib/process.h"
#include <string.h>
#include <errno.h>
Data Structures
struct processs_port_t
Typedefs
typedef struct processs_port_t process_port_t
Functions
dfsch_object_t * dfsch_process_close_port (dfsch_object_t *port)
dfsch_object_t * dfsch_process_spawn_with_input_port (char *cmd_line)
dfsch_object_t * dfsch_process_spawn_with_output_port (char *cmd_line)
static void port_finalizer (process_port_t *port, void *cd)
static ssize_t port_read_buf (process_port_t *port, char *buf, size_t len)
static void port_write_buf (process_port_t *port, char *buf, size_t len)
static void process_port_write (process_port_t *port, dfsch_writer_state_t *state)
static dfsch_object_t * spawn_port (dfsch_object_t *klass, char *cmd_line)
Variables
dfsch_port_type_t dfsch_process_input_port_type
dfsch_port_type_t dfsch_process_output_port_type
dfsch_type_t dfsch_process_port_type
Typedef Documentation
typedef struct processs_port_t process_port_t
Function Documentation
dfsch_object_t* dfsch_process_close_port (dfsch_object_t * port)
Definition at line 172 of file process.c.
References DFSCH_ASSERT_INSTANCE, dfsch_error(), DFSCH_MAKE_FIXNUM, dfsch_make_string_cstr(), DFSCH_PROCESS_PORT_TYPE, processs_port_t::file, and processs_port_t::open.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  process_port_t* p = DFSCH_ASSERT_INSTANCE(port, DFSCH_PROCESS_PORT_TYPE);
  int r;
  if (p->open){
    p->open = 0;
    r = pclose(p->file);
    if (r == -1){
      dfsch_error("Error while closing process port",
                  dfsch_make_string_cstr(strerror(errno)));
    }
    return DFSCH_MAKE_FIXNUM(r);
  }
  return NULL;
}
dfsch_object_t* dfsch_process_spawn_with_input_port (char * cmd_line)
Definition at line 165 of file process.c.
References DFSCH_PROCESS_INPUT_PORT_TYPE, and spawn_port().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return spawn_port(DFSCH_PROCESS_INPUT_PORT_TYPE, cmd_line);
}
dfsch_object_t* dfsch_process_spawn_with_output_port (char * cmd_line)
Definition at line 168 of file process.c.
References DFSCH_PROCESS_OUTPUT_PORT_TYPE, and spawn_port().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return spawn_port(DFSCH_PROCESS_OUTPUT_PORT_TYPE, cmd_line);
}
static void port_finalizer (process_port_t * port, void * cd) [static]
Definition at line 133 of file process.c.
References processs_port_t::file, and processs_port_t::open.
Referenced by spawn_port().
{
  if (port->open){
    pclose(port->file);
    port->open = 0;
  }
}
static ssize_t port_read_buf (process_port_t * port, char * buf, size_t len) [static]
Definition at line 92 of file process.c.
References dfsch_error(), processs_port_t::file, and processs_port_t::open.
{
  size_t ret;
  if (!port->open){
    dfsch_error("Port is already closed", port);
  }
  ret = fread(buf, 1, len, port->file);
  if (ret == 0){
    if (feof(port->file)){
      return 0;
    } else {
      dfsch_error("Error reading from process port", strerror(errno));
    }
  }
  return ret;
}
static void port_write_buf (process_port_t * port, char * buf, size_t len) [static]
Definition at line 55 of file process.c.
References dfsch_error(), processs_port_t::file, and processs_port_t::open.
{
  size_t ret;
  if (!port->open){
    dfsch_error("Port is already closed", port);
  }
  if (len != 0){
    ret = fwrite(buf, len, 1, port->file);
    if (ret == 0){
      dfsch_error("Error writing to process port", strerror(errno));
    }
  }
}
static void process_port_write (process_port_t * port, dfsch_writer_state_t * state) [static]
Definition at line 33 of file process.c.
References processs_port_t::cmd_line, dfsch_write_unreadable(), processs_port_t::file, and processs_port_t::open.
{
  if (port->open){
    dfsch_write_unreadable(state, port,
                           "name %s fd %d",
                           port->cmd_line,
                           fileno(port->file));
  } else {
    dfsch_write_unreadable(state, port, "*closed*");
  }
}
static dfsch_object_t* spawn_port (dfsch_object_t * klass, char * cmd_line) [static]
Definition at line 140 of file process.c.
References processs_port_t::cmd_line, dfsch_error(), dfsch_make_object(), dfsch_make_string_cstr(), DFSCH_PROCESS_INPUT_PORT_TYPE, processs_port_t::file, processs_port_t::open, and port_finalizer().
Referenced by dfsch_process_spawn_with_input_port(), and dfsch_process_spawn_with_output_port().
{
  process_port_t* p = dfsch_make_object(klass);
  p->cmd_line = cmd_line;
  if (klass == DFSCH_PROCESS_INPUT_PORT_TYPE){
    p->file = popen(cmd_line, "r");
  } else {
    p->file = popen(cmd_line, "w");
  }
  if (!p->file){
    dfsch_error("Cannot spawn process",
                dfsch_make_string_cstr(strerror(errno)));
  }
  GC_REGISTER_FINALIZER(p, (GC_finalization_proc)port_finalizer,
                        NULL, NULL, NULL);
  p->open = 1;
  return (dfsch_object_t*)p;
}
Variable Documentation
dfsch_port_type_t dfsch_process_input_port_type
Initial value:
 {
  {
    DFSCH_PORT_TYPE_TYPE,
    DFSCH_PROCESS_PORT_TYPE,
    sizeof(process_port_t),
    "process:input-port",
    NULL,
    NULL,
    NULL
  },
  NULL,
  (dfsch_port_read_buf_t)port_read_buf,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 112 of file process.c.
dfsch_port_type_t dfsch_process_output_port_type
Initial value:
 {
  {
    DFSCH_PORT_TYPE_TYPE,
    DFSCH_PROCESS_PORT_TYPE,
    sizeof(process_port_t),
    "process:output-port",
    NULL,
    NULL,
    NULL
  },
  (dfsch_port_write_buf_t)port_write_buf,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 71 of file process.c.
dfsch_type_t dfsch_process_port_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  DFSCH_PORT_TYPE,
  sizeof(process_port_t),
  "process:port",
  NULL,
  (dfsch_type_write_t)process_port_write,
  NULL
}
Definition at line 45 of file process.c.