dfsch: lib/process_mod.c File Reference
lib/process_mod.c File Reference
#include "dfsch/lib/process.h"
#include <string.h>
#include <errno.h>
Functions
DFSCH_DEFINE_PRIMITIVE (close_port, NULL)
DFSCH_DEFINE_PRIMITIVE (spawn_with_output_port, NULL)
DFSCH_DEFINE_PRIMITIVE (spawn_with_input_port, NULL)
DFSCH_DEFINE_PRIMITIVE (spawn, NULL)
dfsch_object_t * dfsch_module_process_register (dfsch_object_t *ctx)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (close_port , NULL)
Definition at line 54 of file process_mod.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_process_close_port().
{
  dfsch_object_t* port;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_END(args);
  return dfsch_process_close_port(port);
}
DFSCH_DEFINE_PRIMITIVE (spawn_with_output_port , NULL)
Definition at line 47 of file process_mod.c.
References DFSCH_ARG_END, dfsch_process_spawn_with_output_port(), and DFSCH_STRING_ARG.
{
  char* cmd_line;
  DFSCH_STRING_ARG(args, cmd_line);
  DFSCH_ARG_END(args);
  return dfsch_process_spawn_with_output_port(cmd_line);
}
DFSCH_DEFINE_PRIMITIVE (spawn_with_input_port , NULL)
Definition at line 41 of file process_mod.c.
References DFSCH_ARG_END, dfsch_process_spawn_with_input_port(), and DFSCH_STRING_ARG.
{
  char* cmd_line;
  DFSCH_STRING_ARG(args, cmd_line);
  DFSCH_ARG_END(args);
  return dfsch_process_spawn_with_input_port(cmd_line);
}
DFSCH_DEFINE_PRIMITIVE (spawn , NULL)
Definition at line 26 of file process_mod.c.
References DFSCH_ARG_END, dfsch_error(), DFSCH_MAKE_FIXNUM, dfsch_make_string_cstr(), and DFSCH_STRING_ARG.
{
  char* cmd_line;
  int r;
  DFSCH_STRING_ARG(args, cmd_line);
  DFSCH_ARG_END(args);
  r = system(cmd_line);
  if (r == -1){
    dfsch_error("Cannot spawn process",
                dfsch_make_string_cstr(strerror(errno)));
  }
  return DFSCH_MAKE_FIXNUM(r);
}
dfsch_object_t* dfsch_module_process_register (dfsch_object_t * ctx)
Definition at line 63 of file process_mod.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, DFSCH_PROCESS_INPUT_PORT_TYPE, DFSCH_PROCESS_OUTPUT_PORT_TYPE, and DFSCH_PROCESS_PORT_TYPE.
{
  dfsch_define_cstr(ctx, "process:<port>",
                    DFSCH_PROCESS_PORT_TYPE);
  dfsch_define_cstr(ctx, "process:<input-port>",
                    DFSCH_PROCESS_INPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "process:<output-port>",
                    DFSCH_PROCESS_OUTPUT_PORT_TYPE);
  dfsch_define_cstr(ctx, "process:spawn!",
                    DFSCH_PRIMITIVE_REF(spawn));
  dfsch_define_cstr(ctx, "process:spawn-with-input-port!",
                    DFSCH_PRIMITIVE_REF(spawn_with_input_port));
  dfsch_define_cstr(ctx, "process:spawn-with-output-port!",
                    DFSCH_PRIMITIVE_REF(spawn_with_output_port));
  dfsch_define_cstr(ctx, "process:close-port!",
                    DFSCH_PRIMITIVE_REF(close_port));
}