dfsch: dfsch/promise.h File Reference
dfsch/promise.h File Reference
#include <dfsch/dfsch.h>
Functions
dfsch_object_t * dfsch_force_promise (dfsch_object_t *promise)
dfsch_object_t * dfsch_make_promise (dfsch_object_t *expr, dfsch_object_t *env)
dfsch_object_t * dfsch_stream_cdr (dfsch_object_t *stream)
Function Documentation
dfsch_object_t* dfsch_force_promise (dfsch_object_t * promise)
Definition at line 62 of file promise.c.
References dfsch_error(), dfsch_eval_proc(), DFSCH_TYPE_OF, promise_t::env, promise_t::expr, promise_t::mutex, promise_t::set, and promise_t::value.
Referenced by dfsch_stream_cdr(), and native_force().
{
  dfsch_object_t* val;
  promise_t* p = (promise_t*)promise;
  if (DFSCH_TYPE_OF(promise) != &promise_type)
    dfsch_error("exception:not-a-promise", promise);
  if (!p->set){
    val = dfsch_eval_proc(p->expr, p->env);
    pthread_mutex_lock(p->mutex);
    if (!p->set){
      p->set = 1;
      p->value = val;
    }
    pthread_mutex_unlock(p->mutex);
  }
  return p->value;
}
dfsch_object_t* dfsch_make_promise (dfsch_object_t * expr, dfsch_object_t * env)
Definition at line 43 of file promise.c.
References create_finalized_mutex, dfsch_make_object(), promise_t::env, promise_t::expr, promise_t::mutex, promise_t::set, and promise_t::value.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  promise_t* p = (promise_t*)dfsch_make_object(&promise_type);
  p->expr = expr;
  p->env = env;
  p->value = NULL;
  p->set = 0;
  p->mutex = create_finalized_mutex();
  return (dfsch_object_t*)p;
}
dfsch_object_t* dfsch_stream_cdr (dfsch_object_t * stream)
Definition at line 81 of file promise.c.
References dfsch_cdr(), and dfsch_force_promise().
Referenced by native_stream_cdr().
{
  return dfsch_force_promise(dfsch_cdr(stream));
}