dfsch: src/promise.c File Reference
src/promise.c File Reference
#include <dfsch/promise.h>
#include "util.h"
Data Structures
struct promise_t
Functions
dfsch_object_t * dfsch__promise_native_register (dfsch_object_t *ctx)
DFSCH_DEFINE_FORM_IMPL (stream_cons, NULL)
DFSCH_DEFINE_FORM_IMPL (delay,"Create new promise")
dfsch_object_t * dfsch_force_promise (dfsch_object_t *promise)
dfsch_object_t * dfsch_make_promise (dfsch_object_t *expr, dfsch_object_t *env)
dfsch_object_t * dfsch_stream_cdr (dfsch_object_t *stream)
static dfsch_object_t * native_force (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_stream_car (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_stream_cdr (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Variables
static const dfsch_type_t promise_type
Function Documentation
dfsch_object_t* dfsch__promise_native_register (dfsch_object_t * ctx)
Definition at line 135 of file promise.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_make_primitive(), native_force(), native_stream_car(), and native_stream_cdr().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<promise>", &promise_type);
  dfsch_define_cstr(ctx, "delay", DFSCH_FORM_REF(delay));
  dfsch_define_cstr(ctx, "force",
                   dfsch_make_primitive(&native_force,NULL));
  dfsch_define_cstr(ctx, "stream-cons", DFSCH_FORM_REF(stream_cons));
  dfsch_define_cstr(ctx, "stream-car",
                   dfsch_make_primitive(&native_stream_car,NULL));
  dfsch_define_cstr(ctx, "stream-cdr",
                   dfsch_make_primitive(&native_stream_cdr,NULL));
}
DFSCH_DEFINE_FORM_IMPL (stream_cons , NULL)
Definition at line 104 of file promise.c.
References DFSCH_ARG_END, dfsch_cons(), dfsch_eval(), dfsch_list(), dfsch_make_promise(), and DFSCH_OBJECT_ARG.
{
  dfsch_object_t* head;
  dfsch_object_t* tail;
  DFSCH_OBJECT_ARG(args, head);
  DFSCH_OBJECT_ARG(args, tail);
  DFSCH_ARG_END(args);
  return dfsch_cons(dfsch_eval(head, env),
                    dfsch_make_promise(dfsch_list(1,
                                                  tail),
                                       env));
}
DFSCH_DEFINE_FORM_IMPL (delay , "Create new promise")
Definition at line 91 of file promise.c.
References dfsch_make_promise().
{
  return dfsch_make_promise(args, env);
}
dfsch_object_t* dfsch_force_promise (dfsch_object_t * promise)
Definition at line 62 of file promise.c.
References dfsch_error(), dfsch_eval_proc(), DFSCH_TYPE_OF, promise_t::env, promise_t::expr, promise_t::mutex, promise_t::set, and promise_t::value.
Referenced by dfsch_stream_cdr(), and native_force().
{
  dfsch_object_t* val;
  promise_t* p = (promise_t*)promise;
  if (DFSCH_TYPE_OF(promise) != &promise_type)
    dfsch_error("exception:not-a-promise", promise);
  if (!p->set){
    val = dfsch_eval_proc(p->expr, p->env);
    pthread_mutex_lock(p->mutex);
    if (!p->set){
      p->set = 1;
      p->value = val;
    }
    pthread_mutex_unlock(p->mutex);
  }
  return p->value;
}
dfsch_object_t* dfsch_make_promise (dfsch_object_t * expr, dfsch_object_t * env)
Definition at line 43 of file promise.c.
References create_finalized_mutex, dfsch_make_object(), promise_t::env, promise_t::expr, promise_t::mutex, promise_t::set, and promise_t::value.
Referenced by DFSCH_DEFINE_FORM_IMPL().
{
  promise_t* p = (promise_t*)dfsch_make_object(&promise_type);
  p->expr = expr;
  p->env = env;
  p->value = NULL;
  p->set = 0;
  p->mutex = create_finalized_mutex();
  return (dfsch_object_t*)p;
}
dfsch_object_t* dfsch_stream_cdr (dfsch_object_t * stream)
Definition at line 81 of file promise.c.
References dfsch_cdr(), and dfsch_force_promise().
Referenced by native_stream_cdr().
{
  return dfsch_force_promise(dfsch_cdr(stream));
}
static dfsch_object_t* native_force (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 95 of file promise.c.
References DFSCH_ARG_END, dfsch_force_promise(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__promise_native_register().
{
  dfsch_object_t* promise;
  DFSCH_OBJECT_ARG(args, promise);
  DFSCH_ARG_END(args);
  return dfsch_force_promise(promise);
}
static dfsch_object_t* native_stream_car (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 118 of file promise.c.
References DFSCH_ARG_END, dfsch_car(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__promise_native_register().
{
  dfsch_object_t* stream;
  DFSCH_OBJECT_ARG(args, stream);
  DFSCH_ARG_END(args);
  return dfsch_car(stream);
}
static dfsch_object_t* native_stream_cdr (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 126 of file promise.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_stream_cdr().
Referenced by dfsch__promise_native_register().
{
  dfsch_object_t* stream;
  DFSCH_OBJECT_ARG(args, stream);
  DFSCH_ARG_END(args);
  return dfsch_stream_cdr(stream);
}
Variable Documentation
const dfsch_type_t promise_type [static]
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(promise_t),
  "promise",
  NULL,
  NULL
}
Definition at line 34 of file promise.c.