dfsch: dfsch/random.h File Reference
dfsch/random.h File Reference
#include <dfsch/dfsch.h>
Data Structures
struct dfsch_random_state_type_t
Defines
#define DFSCH_DEFAULT_RANDOM_STATE_TYPE (&dfsch_default_random_state_type)
#define DFSCH_FILE_RANDOM_STATE_TYPE (&dfsch_file_random_state_type)
#define DFSCH_RANDOM_STATE_TYPE (&dfsch_random_state_type)
#define DFSCH_RANDOM_STATE_TYPE_TYPE (&dfsch_random_state_type_type)
Typedefs
typedef void(* dfsch_random_get_bytes_t)(dfsch_object_t *state, uint8_t *buf, size_t len)
Functions
dfsch_object_t * dfsch_get_random_state ()
dfsch_object_t * dfsch_make_default_random_state (uint8_t *seed, size_t len)
dfsch_object_t * dfsch_make_file_random_state (char *filename)
dfsch_object_t * dfsch_random_get_bignum (dfsch_object_t *state, size_t len)
void dfsch_random_get_bytes (dfsch_object_t *state, uint8_t *buf, size_t len)
double dfsch_random_get_double (dfsch_object_t *state)
int dfsch_random_get_integer (dfsch_object_t *state, int max)
dfsch_object_t * dfsch_random_get_number (dfsch_object_t *state, dfsch_object_t *max)
void dfsch_set_random_state (dfsch_object_t *state)
Variables
dfsch_random_state_type_t dfsch_default_random_state_type
dfsch_random_state_type_t dfsch_file_random_state_type
dfsch_type_t dfsch_random_state_type
dfsch_type_t dfsch_random_state_type_type
Define Documentation
#define DFSCH_DEFAULT_RANDOM_STATE_TYPE (&dfsch_default_random_state_type)
Definition at line 20 of file random.h.
Referenced by dfsch__random_register(), and dfsch_make_default_random_state().
#define DFSCH_FILE_RANDOM_STATE_TYPE (&dfsch_file_random_state_type)
Definition at line 22 of file random.h.
Referenced by dfsch__random_register(), and dfsch_make_file_random_state().
#define DFSCH_RANDOM_STATE_TYPE (&dfsch_random_state_type)
Definition at line 16 of file random.h.
Referenced by dfsch__random_register().
#define DFSCH_RANDOM_STATE_TYPE_TYPE (&dfsch_random_state_type_type)
Definition at line 18 of file random.h.
Referenced by dfsch_random_get_bytes().
Typedef Documentation
typedef void(* dfsch_random_get_bytes_t)(dfsch_object_t *state, uint8_t *buf, size_t len)
Definition at line 6 of file random.h.
Function Documentation
dfsch_object_t* dfsch_get_random_state ()
Definition at line 51 of file random.c.
References make_default_state().
Referenced by dfsch_random_get_bytes().
{
  if (!random_state){
    random_state = make_default_state();
  }
  return random_state;
}
dfsch_object_t* dfsch_make_default_random_state (uint8_t * seed, size_t len)
Definition at line 175 of file random.c.
References default_state_t::counter, DFSCH_DEFAULT_RANDOM_STATE_TYPE, dfsch_make_object(), default_state_t::okeys, default_state_t::skeys, default_state_t::state, and default_state_t::sum.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and make_default_state().
{
  default_state_t* state = dfsch_make_object(DFSCH_DEFAULT_RANDOM_STATE_TYPE);
  uint32_t u = 0x01234567;
  uint32_t v = 0x89abcdef;
  int i, j;
  state->counter = 0;
  state->sum = 0;
  for (j = 0; j < 8; j++){
    for (i = 0; i < 8; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[state->sum % len] |
                       (seed[(state->sum + 1) % len] << 8) |
                       (seed[(state->sum + 2) % len] << 16) |
                       (seed[(state->sum + 3) % len] << 24)));
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[(state->sum >> 11) % len] |
                       (seed[((state->sum >> 11) + 1) % len] << 8) |
                       (seed[((state->sum >> 11) + 2) % len] << 16) |
                       (seed[((state->sum >> 11) + 3) % len] << 24)));
    }
    state->state[j][0] = u;
    state->state[j][1] = v;
  }
  for (j = 0; j < 2; j++){
    for (i = 0; i < 8; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[state->sum % len] |
                       (seed[(state->sum + 1) % len] << 8) |
                       (seed[(state->sum + 2) % len] << 16) |
                       (seed[(state->sum + 3) % len] << 24)));
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[(state->sum >> 11) % len] |
                       (seed[((state->sum >> 11) + 1) % len] << 8) |
                       (seed[((state->sum >> 11) + 2) % len] << 16) |
                       (seed[((state->sum >> 11) + 3) % len] << 24)));
    }
    state->skeys[j + 0] = u;
    state->skeys[j + 1] = v;
  }
  for (j = 0; j < 2; j++){
    for (i = 0; i < 8; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[state->sum % len] |
                       (seed[(state->sum + 1) % len] << 8) |
                       (seed[(state->sum + 2) % len] << 16) |
                       (seed[(state->sum + 3) % len] << 24)));
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[(state->sum >> 11) % len] |
                       (seed[((state->sum >> 11) + 1) % len] << 8) |
                       (seed[((state->sum >> 11) + 2) % len] << 16) |
                       (seed[((state->sum >> 11) + 3) % len] << 24)));
    }
    state->okeys[j + 0] = u;
    state->okeys[j + 1] = v;
  }
  return (dfsch_object_t*) state;
}
dfsch_object_t* dfsch_make_file_random_state (char * filename)
Definition at line 279 of file random.c.
References dfsch_error(), DFSCH_FILE_RANDOM_STATE_TYPE, dfsch_make_object(), dfsch_make_string_cstr(), file_state_t::fd, and file_state_finalizer().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  file_state_t* state = dfsch_make_object(DFSCH_FILE_RANDOM_STATE_TYPE);
  state->fd = open(filename, O_RDONLY);
  if (state->fd < 0){
    dfsch_error("Cannot open file", dfsch_make_string_cstr(filename));
  }
  GC_REGISTER_FINALIZER(state, (GC_finalization_proc)file_state_finalizer,
                        NULL, NULL, NULL);
  return state;
}
dfsch_object_t* dfsch_random_get_bignum (dfsch_object_t * state, size_t len)
Definition at line 98 of file random.c.
References dfsch_bignum_from_bytes(), dfsch_bignum_to_number(), and dfsch_random_get_bytes().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  uint8_t *buf;
  if ((len % 8) != 0){
    buf = GC_MALLOC_ATOMIC(len / 8 + 1);
    dfsch_random_get_bytes(state, buf, len / 8 + 1);
    *buf &= (1 << (len & 7)) - 1;
    return dfsch_bignum_to_number(dfsch_bignum_from_bytes(buf, len / 8 + 1));
  } else {
    buf = GC_MALLOC_ATOMIC(len / 8);
    dfsch_random_get_bytes(state, buf, len / 8);
    return dfsch_bignum_to_number(dfsch_bignum_from_bytes(buf, len / 8));
  }
}
void dfsch_random_get_bytes (dfsch_object_t * state, uint8_t * buf, size_t len)
Definition at line 61 of file random.c.
References dfsch_error(), dfsch_get_random_state(), DFSCH_RANDOM_STATE_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_random_get_bignum(), dfsch_random_get_double(), and dfsch_random_get_integer().
{
  if (!state){
    state = dfsch_get_random_state();
  }
  if (DFSCH_TYPE_OF(state)->type != DFSCH_RANDOM_STATE_TYPE_TYPE){
    dfsch_error("Not a random state", state);
  }
  ((dfsch_random_state_type_t*)(DFSCH_TYPE_OF(state)))->get_bytes(state, buf, len);
}
double dfsch_random_get_double (dfsch_object_t * state)
Definition at line 82 of file random.c.
References dfsch_random_get_bytes().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_random_get_number().
{
  uint64_t val;
  dfsch_random_get_bytes(state, &val, sizeof(uint64_t));
  val &= (1LL << 53) - 1;
  return (double)val/(double)(1LL << 53);
}
int dfsch_random_get_integer (dfsch_object_t * state, int max)
Definition at line 70 of file random.c.
References dfsch_random_get_bytes().
Referenced by dfsch_random_get_number().
{
  int bits;
  int val;
  do {
    dfsch_random_get_bytes(state, &bits, sizeof(unsigned int));
    if (bits < 0){
      bits = -bits;
    }
    val = bits % max;
  } while (bits - val - (max+1) < 0);
  return val;
}
dfsch_object_t* dfsch_random_get_number (dfsch_object_t * state, dfsch_object_t * max)
Definition at line 88 of file random.c.
References DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_mul(), dfsch_random_get_double(), dfsch_random_get_integer(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(max) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(dfsch_random_get_integer(state,
                                                      DFSCH_FIXNUM_REF(max)));
  }
  return
    dfsch_number_mul(dfsch_make_number_from_double(dfsch_random_get_double(state)),
                     max);
}
void dfsch_set_random_state (dfsch_object_t * state)
Definition at line 57 of file random.c.
{
  random_state = state;
}
Variable Documentation
dfsch_random_state_type_t dfsch_default_random_state_type
Definition at line 161 of file random.c.
dfsch_random_state_type_t dfsch_file_random_state_type
Definition at line 258 of file random.c.
dfsch_type_t dfsch_random_state_type
Definition at line 8 of file random.c.
dfsch_type_t dfsch_random_state_type_type
Definition at line 14 of file random.c.