dfsch: lib/regex_mod.c File Reference
lib/regex_mod.c File Reference
#include "dfsch/lib/regex.h"
Functions
dfsch_object_t * dfsch_module_regex_register (dfsch_object_t *ctx)
static dfsch_object_t * native_regex_compile (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_regex_match_once_p (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_regex_match_p (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_regex_substrings (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_regex_substrings_once (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Function Documentation
dfsch_object_t* dfsch_module_regex_register (dfsch_object_t * ctx)
Define regular expression primitives in given environment.
Definition at line 123 of file regex_mod.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_provide(), native_regex_compile(), native_regex_match_once_p(), native_regex_match_p(), native_regex_substrings(), and native_regex_substrings_once().
{
  dfsch_define_cstr(ctx, "regex:compile",
                   dfsch_make_primitive(&native_regex_compile,NULL));
  dfsch_define_cstr(ctx, "regex:match?",
                   dfsch_make_primitive(&native_regex_match_p,NULL));
  dfsch_define_cstr(ctx, "regex:substrings",
                   dfsch_make_primitive(&native_regex_substrings,NULL));
  dfsch_define_cstr(ctx, "regex:match-once?",
                   dfsch_make_primitive(&native_regex_match_once_p,NULL));
  dfsch_define_cstr(ctx, "regex:substrings-once",
                   dfsch_make_primitive(&native_regex_substrings_once, NULL));
  dfsch_provide(ctx, "regex");
  return NULL;
}
static dfsch_object_t* native_regex_compile (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 24 of file regex_mod.c.
References DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_SET, DFSCH_FLAG_UNSET, dfsch_regex_compile(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_regex_register().
{
  char* expression;
  int flags = REG_EXTENDED;
  DFSCH_STRING_ARG(args, expression);
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_UNSET("basic", REG_EXTENDED, flags);
  DFSCH_FLAG_SET("icase", REG_ICASE, flags);
  DFSCH_FLAG_SET("nosub", REG_NOSUB, flags);
  DFSCH_FLAG_SET("newline", REG_NEWLINE, flags);
  DFSCH_FLAG_PARSER_END(args);
  return dfsch_regex_compile(expression, flags);
}
static dfsch_object_t* native_regex_match_once_p (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 75 of file regex_mod.c.
References dfsch_bool(), DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_SET, DFSCH_FLAG_UNSET, dfsch_regex_match_once_p(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_regex_register().
{
  char* expression;
  char* string;
  int mflags = 0;
  int cflags = REG_EXTENDED | REG_NOSUB;
  DFSCH_STRING_ARG(args, expression);
  DFSCH_STRING_ARG(args, string);
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_UNSET("basic", REG_EXTENDED, cflags);
  DFSCH_FLAG_SET("icase", REG_ICASE, cflags);
  DFSCH_FLAG_SET("newline", REG_NEWLINE, cflags);
  DFSCH_FLAG_SET("notbol", REG_NOTBOL, mflags);
  DFSCH_FLAG_SET("noteol", REG_NOTEOL, mflags);
  DFSCH_FLAG_PARSER_END(args);
  return dfsch_bool(dfsch_regex_match_once_p(expression,
                                             cflags,
                                             mflags,
                                             string));
}
static dfsch_object_t* native_regex_match_p (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 41 of file regex_mod.c.
References dfsch_bool(), DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_SET, DFSCH_OBJECT_ARG, dfsch_regex_match_p(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_regex_register().
{
  dfsch_object_t* expression;
  char* string;
  int flags = 0;
  DFSCH_OBJECT_ARG(args, expression);
  DFSCH_STRING_ARG(args, string);
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_SET("notbol", REG_NOTBOL, flags);
  DFSCH_FLAG_SET("noteol", REG_NOTEOL, flags);
  DFSCH_FLAG_PARSER_END(args);
  return dfsch_bool(dfsch_regex_match_p(expression, string, flags));
}
static dfsch_object_t* native_regex_substrings (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 58 of file regex_mod.c.
References DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_SET, DFSCH_OBJECT_ARG, dfsch_regex_substrings(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_regex_register().
{
  dfsch_object_t* expression;
  char* string;
  int flags = 0;
  DFSCH_OBJECT_ARG(args, expression);
  DFSCH_STRING_ARG(args, string);
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_SET("notbol", REG_NOTBOL, flags);
  DFSCH_FLAG_SET("noteol", REG_NOTEOL, flags);
  DFSCH_FLAG_PARSER_END(args);
  return dfsch_regex_substrings(expression, string, flags);
}
static dfsch_object_t* native_regex_substrings_once (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 100 of file regex_mod.c.
References DFSCH_FLAG_PARSER_BEGIN, DFSCH_FLAG_PARSER_END, DFSCH_FLAG_SET, DFSCH_FLAG_UNSET, dfsch_regex_substrings_once(), and DFSCH_STRING_ARG.
Referenced by dfsch_module_regex_register().
{
  char* expression;
  char* string;
  int mflags = 0;
  int cflags = REG_EXTENDED;
  DFSCH_STRING_ARG(args, expression);
  DFSCH_STRING_ARG(args, string);
  DFSCH_FLAG_PARSER_BEGIN(args);
  DFSCH_FLAG_UNSET("basic", REG_EXTENDED, cflags);
  DFSCH_FLAG_SET("icase", REG_ICASE, cflags);
  DFSCH_FLAG_SET("newline", REG_NEWLINE, cflags);
  DFSCH_FLAG_SET("notbol", REG_NOTBOL, mflags);
  DFSCH_FLAG_SET("noteol", REG_NOTEOL, mflags);
  DFSCH_FLAG_PARSER_END(args);
  return dfsch_regex_substrings_once(expression, cflags, mflags, string);
}