dfsch: lib/regex.c File Reference
lib/regex.c File Reference
#include "dfsch/lib/regex.h"
Data Structures
struct dfsch_regex_t
Functions
dfsch_object_t * dfsch_regex_compile (char *expression, int flags)
int dfsch_regex_match_once_p (char *expression, int cflags, int mflags, char *string)
int dfsch_regex_match_p (dfsch_object_t *regex, char *string, int flags)
dfsch_object_t * dfsch_regex_substrings (dfsch_object_t *regex, char *string, int flags)
dfsch_object_t * dfsch_regex_substrings_once (char *expression, int cflags, int mflags, char *string)
static int get_sub_count (char *expression, int flags)
static void regex_compile (regex_t *regex, char *expression, int flags)
static void regex_finalizer (dfsch_regex_t *regex, void *cd)
char * regex_get_error (int errcode, const regex_t *preg)
static int regex_match (regex_t *regex, char *string, int flags)
static dfsch_object_t * regex_substrings (regex_t *regex, char *string, int sub_count, int flags)
Variables
static dfsch_type_t regex_type
Function Documentation
dfsch_object_t* dfsch_regex_compile (char * expression, int flags)
Compile given regular expression into regex object. Flags are same as for regcomp(3).
Definition at line 85 of file regex.c.
References dfsch_make_object(), get_sub_count(), dfsch_regex_t::regex, regex_compile(), regex_finalizer(), and dfsch_regex_t::sub_count.
Referenced by native_regex_compile().
{
  dfsch_regex_t* r = (dfsch_regex_t*)dfsch_make_object(&regex_type);
  regex_compile(&(r->regex), expression, flags);
  if ((flags & REG_NOSUB) == REG_NOSUB){
    r->sub_count = 0;
  }else{
    r->sub_count = get_sub_count(expression, flags);
  }
  GC_REGISTER_FINALIZER(r, (GC_finalization_proc)regex_finalizer,
                        NULL, NULL, NULL);
  return (dfsch_object_t*)r;
}
int dfsch_regex_match_once_p (char * expression, int cflags, int mflags, char * string)
Definition at line 164 of file regex.c.
References regex_compile(), and regex_match().
Referenced by native_regex_match_once_p().
{
  regex_t regex;
  int r;
  regex_compile(&regex, expression, cflags);
  r = regex_match(&regex, string, mflags);
  regfree(&regex);
  return r;
}
int dfsch_regex_match_p (dfsch_object_t * regex, char * string, int flags)
Apply precompiled regex object to given string and return whetever regular expression matches
Definition at line 106 of file regex.c.
References dfsch_error(), DFSCH_TYPE_OF, and regex_match().
Referenced by native_regex_match_p().
{
  if (DFSCH_TYPE_OF(regex) != &regex_type)
    dfsch_error("regex:not-a-regex", regex);
  return regex_match(&(((dfsch_regex_t*)regex)->regex), string, flags);
}
dfsch_object_t* dfsch_regex_substrings (dfsch_object_t * regex, char * string, int flags)
Apply precompiled regex object to given string and return vector of matching substrings (each as vector of start offset, end offset and matching string).
Definition at line 152 of file regex.c.
References dfsch_error(), DFSCH_TYPE_OF, dfsch_regex_t::regex, regex_substrings(), and dfsch_regex_t::sub_count.
Referenced by native_regex_substrings().
{
  dfsch_regex_t* r;
  if (DFSCH_TYPE_OF(regex) != &regex_type)
    dfsch_error("regex:not-a-regex", regex);
  r = (dfsch_regex_t*)regex;
  if (r->sub_count == 0)
    dfsch_error("regex:compiled-with-nosub", regex);
  return regex_substrings(&(r->regex), string, r->sub_count, flags);
}
dfsch_object_t* dfsch_regex_substrings_once (char * expression, int cflags, int mflags, char * string)
Definition at line 177 of file regex.c.
References get_sub_count(), regex_compile(), and regex_substrings().
Referenced by native_regex_substrings_once().
{
  regex_t regex;
  dfsch_object_t* r;
  regex_compile(&regex, expression, cflags);
  r = regex_substrings(&regex, string,
                       get_sub_count(expression, cflags),
                       mflags);
  regfree(&regex);
  return r;
}
static int get_sub_count (char * expression, int flags) [static]
Definition at line 53 of file regex.c.
Referenced by dfsch_regex_compile(), and dfsch_regex_substrings_once().
{
  int escape;
  int r;
  escape = 0;
  r = 0;
  while (*expression){
    switch (*expression){
    case '\\':
      escape = 1;
      break;
    case '(':
      if ((flags & REG_EXTENDED) == REG_EXTENDED || escape){
        r++;
      }
    default:
      escape = 0;
    }
    expression++;
  }
  return r+1;
}
static void regex_compile (regex_t * regex, char * expression, int flags) [static]
Definition at line 75 of file regex.c.
References dfsch_error(), dfsch_make_string_cstr(), and regex_get_error().
Referenced by dfsch_regex_compile(), dfsch_regex_match_once_p(), and dfsch_regex_substrings_once().
{
  int err;
  err = regcomp(regex, expression, flags);
  if (err != 0){
    dfsch_error("regex:error",
                dfsch_make_string_cstr(regex_get_error(err, regex)));
  }
}
static void regex_finalizer (dfsch_regex_t * regex, void * cd) [static]
Definition at line 40 of file regex.c.
References dfsch_regex_t::regex.
Referenced by dfsch_regex_compile().
{
  regfree(&(regex->regex));
}
char* regex_get_error (int errcode, const regex_t * preg)
Definition at line 44 of file regex.c.
Referenced by regex_compile().
{
  size_t len;
  char* buf;
  len = regerror(errcode, preg, NULL, 0);
  buf = GC_MALLOC_ATOMIC(len);
  regerror(errcode, preg, buf, len);
  return buf;
}
static int regex_match (regex_t * regex, char * string, int flags) [static]
Definition at line 102 of file regex.c.
Referenced by dfsch_regex_match_once_p(), and dfsch_regex_match_p().
{
  return (regexec(regex, string, 0, NULL, flags) == 0);
}
static dfsch_object_t* regex_substrings (regex_t * regex, char * string, int sub_count, int flags) [static]
Definition at line 113 of file regex.c.
References dfsch_make_number_from_long(), dfsch_make_string_buf(), dfsch_make_vector(), dfsch_vector(), and dfsch_vector_set().
Referenced by dfsch_regex_substrings(), and dfsch_regex_substrings_once().
{
  regmatch_t *match;
  int i;
  int count;
  dfsch_object_t* vector;
  match = GC_MALLOC_ATOMIC(sizeof(regmatch_t)*sub_count);
  if (regexec(regex, string, sub_count, match, flags) == REG_NOMATCH){
    GC_FREE(match);
    return NULL;
  }
  count = 0;
  for (i = 0; i < sub_count; i++){
    if (match[i].rm_so == -1)  // No more substring matches
      break;
    count ++;
  }
  vector = dfsch_make_vector(count, NULL);
  for (i = 0; i < count; i++){
    dfsch_vector_set(vector, i,
                     dfsch_vector(3,
                                  dfsch_make_number_from_long(match[i].rm_so),
                                  dfsch_make_number_from_long(match[i].rm_eo),
                                  dfsch_make_string_buf(string+match[i].rm_so,
                                                        match[i].rm_eo-match[i].rm_so)));
  }
  GC_FREE(match);
  return vector;
}
Variable Documentation
dfsch_type_t regex_type [static]
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(dfsch_regex_t),
  "regex",
  NULL,
  NULL,
  NULL,
}
Definition at line 30 of file regex.c.