dfsch: dfsch/lib/regex.h File Reference
dfsch/lib/regex.h File Reference
#include <dfsch/dfsch.h>
#include <regex.h>
Functions
dfsch_object_t * dfsch_module_regex_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_regex_compile (char *expression, int flags)
int dfsch_regex_match_once_p (char *expression, int cflags, int mflags, char *string)
int dfsch_regex_match_p (dfsch_object_t *regex, char *string, int flags)
dfsch_object_t * dfsch_regex_substrings (dfsch_object_t *regex, char *string, int flags)
dfsch_object_t * dfsch_regex_substrings_once (char *expression, int cflags, int mflags, char *string)
Function Documentation
dfsch_object_t* dfsch_module_regex_register (dfsch_object_t * ctx)
Define regular expression primitives in given environment.
Definition at line 123 of file regex_mod.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_provide(), native_regex_compile(), native_regex_match_once_p(), native_regex_match_p(), native_regex_substrings(), and native_regex_substrings_once().
{
  dfsch_define_cstr(ctx, "regex:compile",
                   dfsch_make_primitive(&native_regex_compile,NULL));
  dfsch_define_cstr(ctx, "regex:match?",
                   dfsch_make_primitive(&native_regex_match_p,NULL));
  dfsch_define_cstr(ctx, "regex:substrings",
                   dfsch_make_primitive(&native_regex_substrings,NULL));
  dfsch_define_cstr(ctx, "regex:match-once?",
                   dfsch_make_primitive(&native_regex_match_once_p,NULL));
  dfsch_define_cstr(ctx, "regex:substrings-once",
                   dfsch_make_primitive(&native_regex_substrings_once, NULL));
  dfsch_provide(ctx, "regex");
  return NULL;
}
dfsch_object_t* dfsch_regex_compile (char * expression, int flags)
Compile given regular expression into regex object. Flags are same as for regcomp(3).
Definition at line 85 of file regex.c.
References dfsch_make_object(), get_sub_count(), dfsch_regex_t::regex, regex_compile(), regex_finalizer(), and dfsch_regex_t::sub_count.
Referenced by native_regex_compile().
{
  dfsch_regex_t* r = (dfsch_regex_t*)dfsch_make_object(&regex_type);
  regex_compile(&(r->regex), expression, flags);
  if ((flags & REG_NOSUB) == REG_NOSUB){
    r->sub_count = 0;
  }else{
    r->sub_count = get_sub_count(expression, flags);
  }
  GC_REGISTER_FINALIZER(r, (GC_finalization_proc)regex_finalizer,
                        NULL, NULL, NULL);
  return (dfsch_object_t*)r;
}
int dfsch_regex_match_once_p (char * expression, int cflags, int mflags, char * string)
Definition at line 164 of file regex.c.
References regex_compile(), and regex_match().
Referenced by native_regex_match_once_p().
{
  regex_t regex;
  int r;
  regex_compile(&regex, expression, cflags);
  r = regex_match(&regex, string, mflags);
  regfree(&regex);
  return r;
}
int dfsch_regex_match_p (dfsch_object_t * regex, char * string, int flags)
Apply precompiled regex object to given string and return whetever regular expression matches
Definition at line 106 of file regex.c.
References dfsch_error(), DFSCH_TYPE_OF, and regex_match().
Referenced by native_regex_match_p().
{
  if (DFSCH_TYPE_OF(regex) != &regex_type)
    dfsch_error("regex:not-a-regex", regex);
  return regex_match(&(((dfsch_regex_t*)regex)->regex), string, flags);
}
dfsch_object_t* dfsch_regex_substrings (dfsch_object_t * regex, char * string, int flags)
Apply precompiled regex object to given string and return vector of matching substrings (each as vector of start offset, end offset and matching string).
Definition at line 152 of file regex.c.
References dfsch_error(), DFSCH_TYPE_OF, dfsch_regex_t::regex, regex_substrings(), and dfsch_regex_t::sub_count.
Referenced by native_regex_substrings().
{
  dfsch_regex_t* r;
  if (DFSCH_TYPE_OF(regex) != &regex_type)
    dfsch_error("regex:not-a-regex", regex);
  r = (dfsch_regex_t*)regex;
  if (r->sub_count == 0)
    dfsch_error("regex:compiled-with-nosub", regex);
  return regex_substrings(&(r->regex), string, r->sub_count, flags);
}
dfsch_object_t* dfsch_regex_substrings_once (char * expression, int cflags, int mflags, char * string)
Definition at line 177 of file regex.c.
References get_sub_count(), regex_compile(), and regex_substrings().
Referenced by native_regex_substrings_once().
{
  regex_t regex;
  dfsch_object_t* r;
  regex_compile(&regex, expression, cflags);
  r = regex_substrings(&regex, string,
                       get_sub_count(expression, cflags),
                       mflags);
  regfree(&regex);
  return r;
}