dfsch: src/repl.c File Reference
src/repl.c File Reference
#include <dfsch/dfsch.h>
#include <dfsch/number.h>
#include <dfsch/parse.h>
#include <dfsch/load.h>
#include <dfsch/ports.h>
#include <dfsch/magic.h>
#include <dfsch/lib/cdebug.h>
#include <dfsch/lib/cmdopts.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <assert.h>
Data Structures
struct reload_ctx_t
Functions
static dfsch_object_t * command_exit (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * command_print (void *arg, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * command_sleep (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * command_write (void *arg, dfsch_object_t *args, dfsch_tail_escape_t *esc)
DFSCH_DEFINE_PRIMITIVE (break, 0)
DFSCH_PRIMITIVE_HEAD (reload)
void interactive_repl (dfsch_object_t *ctx)
static void load_scm (dfsch_object_t *env, char *fname)
int main (int argc, char **argv)
void noninteractive_repl (dfsch_object_t *ctx)
static int repl_callback (dfsch_object_t *obj, void *baton)
static void sigint_handler_break (int sig)
Variables
dfsch_parser_ctx_t * parser
Function Documentation
static dfsch_object_t* command_exit (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 61 of file repl.c.
References dfsch_car(), dfsch_integer_p(), dfsch_list_length_check(), dfsch_number_to_long(), and dfsch_object_2_string().
Referenced by main().
{
  switch (dfsch_list_length_check(args)){
  case 0:
    exit(0);
  case 1:
    if (dfsch_integer_p(dfsch_car(args))){
      exit((int)dfsch_number_to_long(dfsch_car(args)));
    }
  default:
    fputs(dfsch_object_2_string(args,100,0),stderr);
    fputs("\n",stderr);
    fflush(stderr);
    exit(1);
  }
}
static dfsch_object_t* command_print (void * arg, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 88 of file repl.c.
References dfsch_car(), dfsch_cdr(), dfsch_object_2_string(), and dfsch_pair_p().
Referenced by main().
{
  while (dfsch_pair_p(args)){
    fputs(dfsch_object_2_string(dfsch_car(args), 100, 0), stdout);
    args = dfsch_cdr(args);
  }
  puts("");
  return NULL;
}
static dfsch_object_t* command_sleep (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 77 of file repl.c.
References DFSCH_ARG_END, and DFSCH_LONG_ARG.
Referenced by main().
{
  long time;
  DFSCH_LONG_ARG(args, time);
  DFSCH_ARG_END(args);
  sleep(time);
  return NULL;
}
static dfsch_object_t* command_write (void * arg, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 98 of file repl.c.
References dfsch_car(), dfsch_cdr(), dfsch_object_2_string(), and dfsch_pair_p().
{
  while (dfsch_pair_p(args)){
    fputs(dfsch_object_2_string(dfsch_car(args), 100, 1), stdout);
    args = dfsch_cdr(args);
  }
  puts("");
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (break , 0)
Definition at line 51 of file repl.c.
References dfsch_cerror().
{
  dfsch_cerror("SIGINT caught", NULL);
}
DFSCH_PRIMITIVE_HEAD (reload)
Definition at line 143 of file repl.c.
References DFSCH_ARG_END, dfsch_load_scm(), reload_ctx_t::env, and reload_ctx_t::fname.
{
  reload_ctx_t* c = baton;
  DFSCH_ARG_END(args);
  dfsch_load_scm(c->env, c->fname);
  return NULL;
}
void interactive_repl (dfsch_object_t * ctx)
Definition at line 110 of file repl.c.
References dfsch_console_run_repl().
Referenced by main().
{
  dfsch_console_run_repl("]=> ", ctx);
}
static void load_scm (dfsch_object_t * env, char * fname) [static]
Definition at line 149 of file repl.c.
References dfsch_define_cstr(), dfsch_load_scm(), dfsch_make_primitive(), reload_ctx_t::env, and reload_ctx_t::fname.
Referenced by dfsch_load_register(), and main().
{
  reload_ctx_t* c = GC_NEW(reload_ctx_t);
  dfsch_load_scm(env, fname);
  c->fname = fname;
  c->env = env;
  dfsch_define_cstr(env, "reload", dfsch_make_primitive(p_reload_impl, c));
}
int main (int argc, char ** argv)
Definition at line 157 of file repl.c.
References command_exit(), command_print(), command_sleep(), dfsch_cdebug_set_as_debugger(), dfsch_cmdopts_argv_to_list(), dfsch_define_cstr(), dfsch_eval_proc(), dfsch_load_extend_path(), dfsch_load_register(), dfsch_load_scm(), dfsch_make_context(), dfsch_make_primitive(), dfsch_make_restart(), dfsch_make_symbol(), dfsch_object_2_string(), dfsch_port_unsafe_register(), dfsch_require(), dfsch_restart_bind(), dfsch_string_2_object_list(), interactive_repl(), load_scm(), noninteractive_repl(), PACKAGE_VERSION, and sigint_handler_break().
{
  int c;
  dfsch_object_t* ctx;
  int interactive = 1;
  int force_interactive = 0;
  GC_INIT();
  signal(SIGINT, sigint_handler_break);
  ctx = dfsch_make_context();
  dfsch_load_register(ctx);
  dfsch_port_unsafe_register(ctx);
  dfsch_define_cstr(ctx,"exit",dfsch_make_primitive(command_exit,NULL));
  dfsch_define_cstr(ctx,"print",dfsch_make_primitive(command_print,NULL));
  dfsch_define_cstr(ctx,"sleep",dfsch_make_primitive(command_sleep,NULL));
  dfsch_restart_bind(dfsch_make_restart(dfsch_make_symbol("quit"),
                                        dfsch_make_primitive(command_exit,
                                                             NULL),
                                        "Exit interpreter",
                                        NULL));
  while ((c=getopt(argc, argv, "+ir:l:L:e:E:hvd")) != -1){
    switch (c){
    case 'r':
      dfsch_require(ctx, optarg, NULL);
      break;
    case 'l':
      load_scm(ctx, optarg);
      break;
    case 'L':
      dfsch_load_extend_path(ctx, optarg);
      break;
    case 'e':
      {
        dfsch_eval_proc(dfsch_string_2_object_list(optarg), ctx);
        interactive = 0;
        break;
      }
    case 'E':
      {
        puts(dfsch_object_2_string(dfsch_eval_proc(dfsch_string_2_object_list(optarg), ctx),
                                   100, 1));
        interactive = 0;
        break;
      }
    case 'd':
      dfsch_cdebug_set_as_debugger();
      break;
    case 'i':
      force_interactive = 1;
      break;
    case 'v':
      printf("dfsch version %s\n\n", PACKAGE_VERSION);
      puts("Copyright (C) 2005-2009 Ales Hakl");
      puts("dfsch comes with ABSOLUTELY NO WARRANTY");
      puts("This is free software, and you are welcome to redistribute it");
      puts("under certain conditions; see file COPYING for details.");
      return 0;
    default:
      printf("Usage: %s [<options>] [<filename> ...]\n\n", argv[0]);
      puts("Options:");
      puts("  -l <filename>     Load scheme file on startup");
      puts("  -r <module-name>  Require (load) module on startup");
      puts("  -L <directory>    Append directory to load:path");
      puts("  -e <expression>   Execute given expression");
      puts("  -E <expression>   Evaluate given expression");
      puts("  -i                Force interactive mode");
      puts("  -d                Enable cdebug debugger early");
      puts("");
      puts("First non-option argument is treated as filename of program to run");
      puts("Run without non-option arguments to start in interactive mode");
      return 0;
    }
  }
  if (optind < argc) {
    dfsch_define_cstr(ctx, "*posix-argv*",
                      dfsch_cmdopts_argv_to_list(argc - optind,
                                                 argv + optind));
    dfsch_load_scm(ctx, argv[optind]);
    return 0;
  }
  if (interactive || force_interactive){
    if (isatty(0)){
      dfsch_cdebug_set_as_debugger();
      interactive_repl(ctx);
    }else{
      noninteractive_repl(ctx);
    }
  }
  return 0;
}
void noninteractive_repl (dfsch_object_t * ctx)
Definition at line 121 of file repl.c.
References dfsch_parser_callback(), dfsch_parser_create(), dfsch_parser_feed_catch(), and repl_callback().
Referenced by main().
{
  parser = dfsch_parser_create();
  dfsch_parser_callback(parser, repl_callback, ctx);
  while (!feof(stdin)){
    char str[4096];
    char *ret;
    if (fgets(str, 4096, stdin) == NULL)
      break;
    dfsch_parser_feed_catch(parser, str);
  }
  puts("");
}
static int repl_callback (dfsch_object_t * obj, void * baton) [static]
Definition at line 114 of file repl.c.
References dfsch_eval(), dfsch_object_2_string(), and sigint_handler_break().
Referenced by noninteractive_repl().
{
  dfsch_object_t* ret;
  signal(SIGINT, sigint_handler_break);
  ret = dfsch_eval(obj, baton);
  puts(dfsch_object_2_string(ret,100,1));
}
static void sigint_handler_break (int sig) [static]
Definition at line 55 of file repl.c.
References dfsch_async_apply_self(), and DFSCH_PRIMITIVE_REF.
Referenced by main(), and repl_callback().
{
  dfsch_async_apply_self(DFSCH_PRIMITIVE_REF(break));
}
Variable Documentation
dfsch_parser_ctx_t* parser
Definition at line 59 of file repl.c.
Referenced by dfsch_console_read_object(), dfsch_console_read_objects(), DFSCH_DEFINE_PRIMITIVE(), dfsch_parser_read_from_port(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_string_2_object_list(), and dfsch_xml_make_parser().