dfsch: src/random.c File Reference
src/random.c File Reference
#include <dfsch/random.h>
#include <sys/times.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>
Data Structures
struct default_state_t
struct file_state_t
struct random_init_t
Functions
static void default_get_bytes (default_state_t *state, uint8_t *buf, size_t len)
void dfsch__random_register (dfsch_object_t *ctx)
DFSCH_DEFINE_PRIMITIVE (make_file_random_state, 0)
DFSCH_DEFINE_PRIMITIVE (make_default_random_state, 0)
DFSCH_DEFINE_PRIMITIVE (random, 0)
DFSCH_DEFINE_PRIMITIVE (random_bignum, 0)
DFSCH_DEFINE_PRIMITIVE (random_flonum, 0)
DFSCH_DEFINE_PRIMITIVE (random_bytes, 0)
dfsch_object_t * dfsch_get_random_state ()
dfsch_object_t * dfsch_make_default_random_state (uint8_t *seed, size_t len)
dfsch_object_t * dfsch_make_file_random_state (char *filename)
dfsch_object_t * dfsch_random_get_bignum (dfsch_object_t *state, size_t len)
void dfsch_random_get_bytes (dfsch_object_t *state, uint8_t *buf, size_t len)
double dfsch_random_get_double (dfsch_object_t *state)
int dfsch_random_get_integer (dfsch_object_t *state, int max)
dfsch_object_t * dfsch_random_get_number (dfsch_object_t *state, dfsch_object_t *max)
void dfsch_set_random_state (dfsch_object_t *state)
static void file_get_bytes (file_state_t *state, uint8_t *buf, size_t len)
static void file_state_finalizer (file_state_t *state)
static dfsch_object_t * make_default_state ()
Variables
dfsch_random_state_type_t dfsch_default_random_state_type
dfsch_random_state_type_t dfsch_file_random_state_type
dfsch_type_t dfsch_random_state_type
dfsch_type_t dfsch_random_state_type_type
static dfsch_object_t * random_state
Function Documentation
static void default_get_bytes (default_state_t * state, uint8_t * buf, size_t len) [static]
Definition at line 122 of file random.c.
References default_state_t::counter, default_state_t::okeys, default_state_t::skeys, default_state_t::state, and default_state_t::sum.
{
  uint32_t v = state->sum;
  uint32_t u = state->counter;
  int i;
  state->counter++;
  for (i = 0; i < 8; i++){
    v += (((u << 4) ^ (u >> 5)) + u) ^
      (state->sum + state->skeys[state->sum & 3]);
    state->sum += 0x9e3779b9;
    u += (((u << 4) ^ (u >> 5)) + u) ^
      (state->sum + state->state[i][0]);
    v += (((u << 4) ^ (u >> 5)) + u) ^
      (state->sum + state->state[i][1]);
    state->sum += 0x9e3779b9;
    u += (((u << 4) ^ (u >> 5)) + u) ^
      (state->sum + state->skeys[(state->sum >> 11) & 3]);
    state->okeys[(state->counter + 1) & 7] ^= v ^ u;
  }
  state->state[state->counter & 7][0] = u;
  state->state[state->counter & 7][1] = v;
  while (len){
    for (i = 0; i < 4; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + state->okeys[state->sum & 7]);
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + state->okeys[(state->sum >> 11) & 7]);
    }
    *buf = u;
    buf++;
    len--;
    u >>= 8;
    v >>= 8;
    u += state->sum;
    v += state->counter;
  }
}
void dfsch__random_register (dfsch_object_t * ctx)
Definition at line 344 of file random.c.
References DFSCH_DEFAULT_RANDOM_STATE_TYPE, dfsch_define_cstr(), DFSCH_FILE_RANDOM_STATE_TYPE, DFSCH_PRIMITIVE_REF, and DFSCH_RANDOM_STATE_TYPE.
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<random-state>", DFSCH_RANDOM_STATE_TYPE);
  dfsch_define_cstr(ctx, "<default-random-state>",
                    DFSCH_DEFAULT_RANDOM_STATE_TYPE);
  dfsch_define_cstr(ctx, "<file-random-state>", DFSCH_FILE_RANDOM_STATE_TYPE);
  dfsch_define_cstr(ctx, "random-bytes", DFSCH_PRIMITIVE_REF(random_bytes));
  dfsch_define_cstr(ctx, "random-flonum", DFSCH_PRIMITIVE_REF(random_flonum));
  dfsch_define_cstr(ctx, "random-bignum", DFSCH_PRIMITIVE_REF(random_bignum));
  dfsch_define_cstr(ctx, "random", DFSCH_PRIMITIVE_REF(random));
  dfsch_define_cstr(ctx, "make-default-random-state",
                    DFSCH_PRIMITIVE_REF(make_default_random_state));
  dfsch_define_cstr(ctx, "make-file-random-state",
                    DFSCH_PRIMITIVE_REF(make_file_random_state));
}
DFSCH_DEFINE_PRIMITIVE (make_file_random_state , 0)
Definition at line 337 of file random.c.
References DFSCH_ARG_END, dfsch_make_file_random_state(), and DFSCH_STRING_ARG.
{
  char* filename;
  DFSCH_STRING_ARG(args, filename);
  DFSCH_ARG_END(args);
  return dfsch_make_file_random_state(filename);
}
DFSCH_DEFINE_PRIMITIVE (make_default_random_state , 0)
Definition at line 331 of file random.c.
References DFSCH_ARG_END, DFSCH_BUFFER_ARG, dfsch_make_default_random_state(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
{
  dfsch_strbuf_t* seed;
  DFSCH_BUFFER_ARG(args, seed);
  DFSCH_ARG_END(args);
  return dfsch_make_default_random_state(seed->ptr, seed->len);
}
DFSCH_DEFINE_PRIMITIVE (random , 0)
Definition at line 322 of file random.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, and dfsch_random_get_number().
{
  dfsch_object_t* max;
  dfsch_object_t* state;
  DFSCH_OBJECT_ARG(args, max);
  DFSCH_OBJECT_ARG_OPT(args, state, NULL);
  DFSCH_ARG_END(args);
  return dfsch_random_get_number(state, max);
}
DFSCH_DEFINE_PRIMITIVE (random_bignum , 0)
Definition at line 313 of file random.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG, DFSCH_OBJECT_ARG_OPT, and dfsch_random_get_bignum().
{
  size_t len;
  dfsch_object_t* state;
  DFSCH_LONG_ARG(args, len);
  DFSCH_OBJECT_ARG_OPT(args, state, NULL);
  DFSCH_ARG_END(args);
  return dfsch_random_get_bignum(state, len);
}
DFSCH_DEFINE_PRIMITIVE (random_flonum , 0)
Definition at line 306 of file random.c.
References DFSCH_ARG_END, dfsch_make_number_from_double(), DFSCH_OBJECT_ARG_OPT, and dfsch_random_get_double().
{
  dfsch_object_t* state;
  DFSCH_OBJECT_ARG_OPT(args, state, NULL);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_double(dfsch_random_get_double(state));
}
DFSCH_DEFINE_PRIMITIVE (random_bytes , 0)
Definition at line 293 of file random.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG, dfsch_make_string_buf(), DFSCH_OBJECT_ARG_OPT, and dfsch_random_get_bytes().
{
  size_t len;
  uint8_t *buf;
  dfsch_object_t* state;
  DFSCH_LONG_ARG(args, len);
  DFSCH_OBJECT_ARG_OPT(args, state, NULL);
  DFSCH_ARG_END(args);
  buf = GC_MALLOC_ATOMIC(len);
  dfsch_random_get_bytes(state, buf, len);
  return dfsch_make_string_buf(buf, len);
}
dfsch_object_t* dfsch_get_random_state ()
Definition at line 51 of file random.c.
References make_default_state().
Referenced by dfsch_random_get_bytes().
{
  if (!random_state){
    random_state = make_default_state();
  }
  return random_state;
}
dfsch_object_t* dfsch_make_default_random_state (uint8_t * seed, size_t len)
Definition at line 175 of file random.c.
References default_state_t::counter, DFSCH_DEFAULT_RANDOM_STATE_TYPE, dfsch_make_object(), default_state_t::okeys, default_state_t::skeys, default_state_t::state, and default_state_t::sum.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and make_default_state().
{
  default_state_t* state = dfsch_make_object(DFSCH_DEFAULT_RANDOM_STATE_TYPE);
  uint32_t u = 0x01234567;
  uint32_t v = 0x89abcdef;
  int i, j;
  state->counter = 0;
  state->sum = 0;
  for (j = 0; j < 8; j++){
    for (i = 0; i < 8; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[state->sum % len] |
                       (seed[(state->sum + 1) % len] << 8) |
                       (seed[(state->sum + 2) % len] << 16) |
                       (seed[(state->sum + 3) % len] << 24)));
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[(state->sum >> 11) % len] |
                       (seed[((state->sum >> 11) + 1) % len] << 8) |
                       (seed[((state->sum >> 11) + 2) % len] << 16) |
                       (seed[((state->sum >> 11) + 3) % len] << 24)));
    }
    state->state[j][0] = u;
    state->state[j][1] = v;
  }
  for (j = 0; j < 2; j++){
    for (i = 0; i < 8; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[state->sum % len] |
                       (seed[(state->sum + 1) % len] << 8) |
                       (seed[(state->sum + 2) % len] << 16) |
                       (seed[(state->sum + 3) % len] << 24)));
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[(state->sum >> 11) % len] |
                       (seed[((state->sum >> 11) + 1) % len] << 8) |
                       (seed[((state->sum >> 11) + 2) % len] << 16) |
                       (seed[((state->sum >> 11) + 3) % len] << 24)));
    }
    state->skeys[j + 0] = u;
    state->skeys[j + 1] = v;
  }
  for (j = 0; j < 2; j++){
    for (i = 0; i < 8; i++){
      v += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[state->sum % len] |
                       (seed[(state->sum + 1) % len] << 8) |
                       (seed[(state->sum + 2) % len] << 16) |
                       (seed[(state->sum + 3) % len] << 24)));
      state->sum += 0x9e3779b9;
      u += (((u << 4) ^ (u >> 5)) + u) ^
        (state->sum + (seed[(state->sum >> 11) % len] |
                       (seed[((state->sum >> 11) + 1) % len] << 8) |
                       (seed[((state->sum >> 11) + 2) % len] << 16) |
                       (seed[((state->sum >> 11) + 3) % len] << 24)));
    }
    state->okeys[j + 0] = u;
    state->okeys[j + 1] = v;
  }
  return (dfsch_object_t*) state;
}
dfsch_object_t* dfsch_make_file_random_state (char * filename)
Definition at line 279 of file random.c.
References dfsch_error(), DFSCH_FILE_RANDOM_STATE_TYPE, dfsch_make_object(), dfsch_make_string_cstr(), file_state_t::fd, and file_state_finalizer().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  file_state_t* state = dfsch_make_object(DFSCH_FILE_RANDOM_STATE_TYPE);
  state->fd = open(filename, O_RDONLY);
  if (state->fd < 0){
    dfsch_error("Cannot open file", dfsch_make_string_cstr(filename));
  }
  GC_REGISTER_FINALIZER(state, (GC_finalization_proc)file_state_finalizer,
                        NULL, NULL, NULL);
  return state;
}
dfsch_object_t* dfsch_random_get_bignum (dfsch_object_t * state, size_t len)
Definition at line 98 of file random.c.
References dfsch_bignum_from_bytes(), dfsch_bignum_to_number(), and dfsch_random_get_bytes().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  uint8_t *buf;
  if ((len % 8) != 0){
    buf = GC_MALLOC_ATOMIC(len / 8 + 1);
    dfsch_random_get_bytes(state, buf, len / 8 + 1);
    *buf &= (1 << (len & 7)) - 1;
    return dfsch_bignum_to_number(dfsch_bignum_from_bytes(buf, len / 8 + 1));
  } else {
    buf = GC_MALLOC_ATOMIC(len / 8);
    dfsch_random_get_bytes(state, buf, len / 8);
    return dfsch_bignum_to_number(dfsch_bignum_from_bytes(buf, len / 8));
  }
}
void dfsch_random_get_bytes (dfsch_object_t * state, uint8_t * buf, size_t len)
Definition at line 61 of file random.c.
References dfsch_error(), dfsch_get_random_state(), DFSCH_RANDOM_STATE_TYPE_TYPE, and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE(), dfsch_random_get_bignum(), dfsch_random_get_double(), and dfsch_random_get_integer().
{
  if (!state){
    state = dfsch_get_random_state();
  }
  if (DFSCH_TYPE_OF(state)->type != DFSCH_RANDOM_STATE_TYPE_TYPE){
    dfsch_error("Not a random state", state);
  }
  ((dfsch_random_state_type_t*)(DFSCH_TYPE_OF(state)))->get_bytes(state, buf, len);
}
double dfsch_random_get_double (dfsch_object_t * state)
Definition at line 82 of file random.c.
References dfsch_random_get_bytes().
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_random_get_number().
{
  uint64_t val;
  dfsch_random_get_bytes(state, &val, sizeof(uint64_t));
  val &= (1LL << 53) - 1;
  return (double)val/(double)(1LL << 53);
}
int dfsch_random_get_integer (dfsch_object_t * state, int max)
Definition at line 70 of file random.c.
References dfsch_random_get_bytes().
Referenced by dfsch_random_get_number().
{
  int bits;
  int val;
  do {
    dfsch_random_get_bytes(state, &bits, sizeof(unsigned int));
    if (bits < 0){
      bits = -bits;
    }
    val = bits % max;
  } while (bits - val - (max+1) < 0);
  return val;
}
dfsch_object_t* dfsch_random_get_number (dfsch_object_t * state, dfsch_object_t * max)
Definition at line 88 of file random.c.
References DFSCH_FIXNUM_REF, DFSCH_FIXNUM_TYPE, DFSCH_MAKE_FIXNUM, dfsch_make_number_from_double(), dfsch_number_mul(), dfsch_random_get_double(), dfsch_random_get_integer(), and DFSCH_TYPE_OF.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  if (DFSCH_TYPE_OF(max) == DFSCH_FIXNUM_TYPE){
    return DFSCH_MAKE_FIXNUM(dfsch_random_get_integer(state,
                                                      DFSCH_FIXNUM_REF(max)));
  }
  return
    dfsch_number_mul(dfsch_make_number_from_double(dfsch_random_get_double(state)),
                     max);
}
void dfsch_set_random_state (dfsch_object_t * state)
Definition at line 57 of file random.c.
{
  random_state = state;
}
static void file_get_bytes (file_state_t * state, uint8_t * buf, size_t len) [static]
Definition at line 245 of file random.c.
References dfsch_error(), and file_state_t::fd.
{
  ssize_t r;
  while (len){
    r = read(state->fd, buf, len);
    if (r < 0){
      if (errno != EAGAIN){
        dfsch_error("Error reading random source", state);
      }
    }
    len -= r;
  }
}
static void file_state_finalizer (file_state_t * state) [static]
Definition at line 272 of file random.c.
References file_state_t::fd.
Referenced by dfsch_make_file_random_state().
{
  if (state->fd >= 0){
    close(state->fd);
    state->fd = -1;
  }
}
static dfsch_object_t* make_default_state () [static]
Definition at line 32 of file random.c.
References random_init_t::clock, dfsch_make_default_random_state(), random_init_t::rusage, random_init_t::sys_random, random_init_t::time, and random_init_t::tms.
Referenced by dfsch_get_random_state().
{
  random_init_t seed;
  int fd;
  seed.time = time(NULL);
  seed.clock = times(&seed.tms);
  getrusage(RUSAGE_SELF, &seed.rusage);
  fd = open("/dev/urandom", O_RDONLY | O_NONBLOCK);
  if (fd < 0) {
    fd = open("/dev/random", O_RDONLY | O_NONBLOCK);
  }
  if (fd >= 0){
    read(fd, &seed.sys_random, 16);
    close(fd);
  }
  return dfsch_make_default_random_state(&seed, sizeof(random_init_t));
}
Variable Documentation
dfsch_random_state_type_t dfsch_default_random_state_type
Initial value:
 {
  {
    DFSCH_RANDOM_STATE_TYPE_TYPE,
    DFSCH_RANDOM_STATE_TYPE,
    sizeof(default_state_t),
    "default-random-state",
    NULL,
    NULL,
    NULL,
    NULL
  },
  (dfsch_random_get_bytes_t)default_get_bytes,
  0
}
Definition at line 161 of file random.c.
dfsch_random_state_type_t dfsch_file_random_state_type
Initial value:
 {
  {
    DFSCH_RANDOM_STATE_TYPE_TYPE,
    DFSCH_RANDOM_STATE_TYPE,
    sizeof(file_state_t),
    "file-random-state",
    NULL,
    NULL,
    NULL,
    NULL
  },
  (dfsch_random_get_bytes_t)file_get_bytes,
  0
}
Definition at line 258 of file random.c.
dfsch_type_t dfsch_random_state_type
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "random-state",
}
Definition at line 8 of file random.c.
dfsch_type_t dfsch_random_state_type_type
Initial value:
 {
  DFSCH_META_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(dfsch_random_state_type),
  "random-state-type",
}
Definition at line 14 of file random.c.
dfsch_object_t* random_state [static]
Definition at line 21 of file random.c.