dfsch: dfsch/strings.h File Reference
dfsch/strings.h File Reference
#include <dfsch/dfsch.h>
Data Structures
struct dfsch_strbuf_t
Defines
#define DFSCH_BUFFER_ARG(al, name) DFSCH_GENERIC_ARG(al, name, dfsch_strbuf_t*, dfsch_string_to_buf)
#define DFSCH_BUFFER_ARG_OPT(al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, dfsch_strbuf_t*, dfsch_string_to_buf)
#define DFSCH_STRING_ARG(al, name) DFSCH_GENERIC_ARG(al, name, char*, dfsch_string_to_cstr)
#define DFSCH_STRING_ARG_OPT(al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, char*, dfsch_string_to_cstr)
#define DFSCH_STRING_OR_SYMBOL_ARG(al, name) DFSCH_GENERIC_ARG(al, name, char*, dfsch_string_or_symbol_to_cstr)
#define DFSCH_STRING_OR_SYMBOL_ARG_OPT(al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, char*, dfsch_string_or_symbol_to_cstr)
Functions
char * dfsch_char_category (uint32_t c)
uint32_t dfsch_char_downcase (uint32_t c)
char * dfsch_char_encode (uint32_t c)
uint32_t dfsch_char_titlecase (uint32_t c)
uint32_t dfsch_char_upcase (uint32_t c)
dfsch_object_t * dfsch_make_string_buf (char *ptr, size_t len)
dfsch_object_t * dfsch_make_string_cstr (char *string)
dfsch_object_t * dfsch_make_string_nocopy (dfsch_strbuf_t *buf)
dfsch_object_t * dfsch_make_string_strbuf (dfsch_strbuf_t *strbuf)
dfsch_strbuf_t * dfsch_strbuf_create (char *ptr, size_t len)
dfsch_object_t * dfsch_string_2_list (dfsch_object_t *string)
int dfsch_string_ci_eq_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_ci_gt_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_ci_gte_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_ci_lt_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_ci_lte_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_cmp (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_cmp_ci (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_eq_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_gt_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_gte_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
size_t dfsch_string_length (dfsch_object_t *string)
dfsch_object_t * dfsch_string_list_append (dfsch_object_t *list)
int dfsch_string_lt_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
int dfsch_string_lte_p (dfsch_strbuf_t *a, dfsch_strbuf_t *b)
char * dfsch_string_or_symbol_to_cstr (dfsch_object_t *obj)
int dfsch_string_p (dfsch_object_t *obj)
char dfsch_string_ref (dfsch_object_t *string, size_t index)
dfsch_strbuf_t * dfsch_string_replace (dfsch_strbuf_t *str, dfsch_strbuf_t *from, dfsch_strbuf_t *to, int max_matches, int case_sensitive)
int dfsch_string_search (dfsch_strbuf_t *needle, dfsch_strbuf_t *haystack)
int dfsch_string_search_ci (dfsch_strbuf_t *needle, dfsch_strbuf_t *haystack)
dfsch_object_t * dfsch_string_split (dfsch_strbuf_t *str, dfsch_strbuf_t *separator, int max_parts, int case_sensitive, int preserve_empty)
dfsch_object_t * dfsch_string_split_byte (dfsch_strbuf_t *str, dfsch_strbuf_t *separator, int max_parts, int preserve_empty)
dfsch_object_t * dfsch_string_split_char (dfsch_strbuf_t *str, dfsch_strbuf_t *separator, int max_parts, int preserve_empty)
dfsch_object_t * dfsch_string_substring (dfsch_object_t *string, size_t start, size_t end)
dfsch_object_t * dfsch_string_substring_utf8 (dfsch_object_t *string, size_t start, size_t end)
dfsch_strbuf_t * dfsch_string_to_buf (dfsch_object_t *obj)
char * dfsch_string_to_cstr (dfsch_object_t *obj)
Define Documentation
#define DFSCH_BUFFER_ARG (al, name) DFSCH_GENERIC_ARG(al, name, dfsch_strbuf_t*, dfsch_string_to_buf)
Definition at line 91 of file strings.h.
Referenced by DFSCH_DEFINE_PRIMITIVE(), DFSCH_PRIMITIVE_HEAD(), inet_base64_decode(), inet_base64_encode(), inet_uri_base64_decode(), inet_uri_base64_encode(), inet_urldecode(), inet_urlencode(), native_port_write_buf(), native_string_input_port(), and native_write().
#define DFSCH_BUFFER_ARG_OPT (al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, dfsch_strbuf_t*, dfsch_string_to_buf)
Definition at line 93 of file strings.h.
#define DFSCH_STRING_ARG (al, name) DFSCH_GENERIC_ARG(al, name, char*, dfsch_string_to_cstr)
Definition at line 81 of file strings.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), DFSCH_DEFINE_PRIMITIVE(), http_query_2_alist(), http_query_2_hash(), http_split_path(), http_split_query(), inet_xml_escape(), native_access(), native_chdir(), native_chmod(), native_chown(), native_creat(), native_format(), native_getenv(), native_link(), native_lstat(), native_make_wrapper_type(), native_mkdir(), native_mkfifo(), native_open(), native_open_file_port(), native_opendir(), native_read_scm(), native_regex_compile(), native_regex_match_once_p(), native_regex_match_p(), native_regex_substrings(), native_regex_substrings_once(), native_rename(), native_rmdir(), native_stat(), native_symlink(), and native_unlink().
#define DFSCH_STRING_ARG_OPT (al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, char*, dfsch_string_to_cstr)
Definition at line 83 of file strings.h.
Referenced by DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_STRING_OR_SYMBOL_ARG (al, name) DFSCH_GENERIC_ARG(al, name, char*, dfsch_string_or_symbol_to_cstr)
Definition at line 86 of file strings.h.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and DFSCH_DEFINE_PRIMITIVE().
#define DFSCH_STRING_OR_SYMBOL_ARG_OPT (al, name, default) DFSCH_GENERIC_ARG_OPT(al, name, default, char*, dfsch_string_or_symbol_to_cstr)
Definition at line 88 of file strings.h.
Function Documentation
char* dfsch_char_category (uint32_t c)
Definition at line 644 of file strings.c.
References UDATA_ENTRY.
Referenced by dfsch_char_alphabetic_p(), dfsch_char_decimal_p(), dfsch_char_lower_case_p(), dfsch_char_mark_p(), dfsch_char_numeric_p(), dfsch_char_upper_case_p(), dfsch_char_whitespace_p(), and DFSCH_DEFINE_PRIMITIVE().
{
  return UDATA_ENTRY(c).category;
}
uint32_t dfsch_char_downcase (uint32_t c)
Definition at line 634 of file strings.c.
References UDATA_ENTRY.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and string_case().
{
  return UDATA_ENTRY(c).lower_offset + c;
}
char* dfsch_char_encode (uint32_t c)
Definition at line 610 of file strings.c.
Referenced by dfsch_format().
{
  char* ptr = GC_MALLOC_ATOMIC(5);
  if (c <= 0x7f){
    ptr[0] = c;
    ptr[1] = '\0';
  } else if (c <= 0x7ff) {
    ptr[0] = 0xc0 | ((c >> 6) & 0x1f);
    ptr[1] = 0x80 | (c & 0x3f);
    ptr[2] = '\0';
  } else if (c <= 0xffff) {
    ptr[0] = 0xe0 | ((c >> 12) & 0x0f);
    ptr[1] = 0x80 | ((c >> 6) & 0x3f);
    ptr[2] = 0x80 | (c & 0x3f);
    ptr[3] = '\0';
  } else {
    ptr[0] = 0xf0 | ((c >> 18) & 0x07);
    ptr[1] = 0x80 | ((c >> 12) & 0x3f);
    ptr[2] = 0x80 | ((c >> 6) & 0x3f);
    ptr[3] = 0x80 | (c & 0x3f);
    ptr[4] = '\0';
  }
  return ptr;
}
uint32_t dfsch_char_titlecase (uint32_t c)
Definition at line 640 of file strings.c.
References UDATA_ENTRY.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and string_case().
{
  return UDATA_ENTRY(c).title_offset + c;
}
uint32_t dfsch_char_upcase (uint32_t c)
Definition at line 637 of file strings.c.
References UDATA_ENTRY.
Referenced by ci_prefix_p(), DFSCH_DEFINE_PRIMITIVE(), dfsch_string_cmp_ci(), and string_case().
{
  return UDATA_ENTRY(c).upper_offset + c;
}
dfsch_object_t* dfsch_make_string_buf (char * ptr, size_t len)
Definition at line 189 of file strings.c.
References dfsch_string_t::buf, dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, and dfsch_string_t::type.
Referenced by character_data_handler(), DFSCH_DEFINE_PRIMITIVE(), dfsch_list_2_string(), dfsch_list_2_string_utf8(), dfsch_make_string_cstr(), dfsch_make_string_strbuf(), dfsch_string_split(), dfsch_string_split_byte(), dfsch_string_split_char(), dfsch_string_substring(), dfsch_string_substring_utf8(), dispatch_string(), http_split_query(), native_port_read_buf(), native_read(), pathname_basename(), pathname_dirname(), pathname_extension(), pathname_filename(), regex_substrings(), and string_case().
{
  dfsch_string_t *s = GC_MALLOC_ATOMIC(sizeof(dfsch_string_t)+len+1);
  s->type = &string_type;
  s->buf.ptr = (char *)(s + 1);
  s->buf.len = len;
  if(ptr) // For allocating space to be used later
    memcpy(s->buf.ptr, ptr, len);
  s->buf.ptr[len] = 0;
  return (dfsch_object_t*)s;
}
dfsch_object_t* dfsch_make_string_cstr (char * string)
Definition at line 180 of file strings.c.
References dfsch_make_string_buf().
Referenced by dfsch_cerror(), dfsch_cmdopts_argv_to_list(), dfsch_condition_broadcast(), dfsch_condition_signal(), dfsch_condition_wait(), DFSCH_DEFINE_PRIMITIVE(), dfsch_error(), dfsch_extref_ref(), dfsch_load(), dfsch_load_extend_path(), dfsch_load_register(), dfsch_load_so(), dfsch_make_context(), dfsch_make_file_random_state(), dfsch_mutex_lock(), dfsch_mutex_unlock(), dfsch_open_file_port(), dfsch_operating_system_error_saved(), dfsch_process_close_port(), dfsch_provide(), dfsch_read_scm_fd(), dfsch_read_scm_stream(), dfsch_signal_condition(), dfsch_sxml_emit_file(), dfsch_sxml_parse_file(), dfsch_thread_detach(), dfsch_thread_join(), dfsch_type_error(), dfsch_xml_parse_file(), dfsch_xml_signal_error(), end_element_handler(), errno_error(), find_long_opt(), http_split_query(), inet_xml_escape(), lisp_callback(), native_format(), native_getcwd(), native_getenv(), native_iso_format_time(), native_readdir(), regex_compile(), spawn_port(), start_element_handler(), and string_accessor_ref().
{
  if (!string)
    return NULL;
  return dfsch_make_string_buf(string, strlen(string));
}
dfsch_object_t* dfsch_make_string_nocopy (dfsch_strbuf_t * buf)
Definition at line 204 of file strings.c.
References dfsch_string_t::buf, dfsch_make_object(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE(), inet_base64_decode(), inet_base64_encode(), inet_uri_base64_decode(), inet_uri_base64_encode(), inet_urldecode(), inet_urlencode(), and urldecode_to_string().
{
  dfsch_string_t *s =
    (dfsch_string_t*)dfsch_make_object(&string_type);
  s->buf.ptr = buf->ptr;
  s->buf.len = buf->len;
  return (dfsch_object_t*)s;
}
dfsch_object_t* dfsch_make_string_strbuf (dfsch_strbuf_t * strbuf)
Definition at line 186 of file strings.c.
References dfsch_make_string_buf(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE(), native_port_read_line(), and native_string_output_port_value().
{
  return dfsch_make_string_buf(strbuf->ptr, strbuf->len);
}
dfsch_strbuf_t* dfsch_strbuf_create (char * ptr, size_t len)
Definition at line 171 of file strings.c.
References dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by dfsch_bignum_to_bytes(), and dfsch_port_readline().
{
  dfsch_strbuf_t *sb = GC_NEW(dfsch_strbuf_t);
  sb->ptr = ptr;
  sb->len = len;
  return sb;
}
dfsch_object_t* dfsch_string_2_list (dfsch_object_t * string)
Definition at line 335 of file strings.c.
References dfsch_string_t::buf, dfsch_cons(), DFSCH_FAST_CDR_MUT, DFSCH_MAKE_FIXNUM, dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, STRING, and TYPE_CHECK.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_string_t* s = (dfsch_string_t*) string;
  dfsch_object_t *head;
  dfsch_object_t *tail;
  size_t i;
  TYPE_CHECK(s, STRING, "string");
  if (s->buf.len == 0)
    return NULL;
  head = tail = dfsch_cons(DFSCH_MAKE_FIXNUM(s->buf.ptr[0]),
                           NULL);
  for(i = 1; i < s->buf.len; ++i){
    object_t *tmp;
    tmp = dfsch_cons(DFSCH_MAKE_FIXNUM(s->buf.ptr[i]),NULL);
    DFSCH_FAST_CDR_MUT(tail) = tmp;
    tail = tmp;
  }
  return head;
}
int dfsch_string_ci_eq_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 833 of file strings.c.
References dfsch_string_cmp_ci().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp_ci(a, b) == 0;
}
int dfsch_string_ci_gt_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 839 of file strings.c.
References dfsch_string_cmp_ci().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp_ci(a, b) > 0;
}
int dfsch_string_ci_gte_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 845 of file strings.c.
References dfsch_string_cmp_ci().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp_ci(a, b) >= 0;
}
int dfsch_string_ci_lt_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 836 of file strings.c.
References dfsch_string_cmp_ci().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp_ci(a, b) < 0;
}
int dfsch_string_ci_lte_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 842 of file strings.c.
References dfsch_string_cmp_ci().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp_ci(a, b) <= 0;
}
int dfsch_string_cmp (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 233 of file strings.c.
References dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by dfsch_string_gt_p(), dfsch_string_gte_p(), dfsch_string_lt_p(), and dfsch_string_lte_p().
{
  if (a->len != b->len){
    size_t l = (a->len < b->len) ? a->len : b->len;
    int r = memcmp(a->ptr, b->ptr, l);
    if (r == 0){
      return (a->len < b->len) ? -1 : 1;
    }else {
      return r;
    }
  }
  return memcmp(a->ptr, b->ptr, a->len);
}
int dfsch_string_cmp_ci (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 801 of file strings.c.
References dfsch_char_upcase(), get_char(), dfsch_strbuf_t::len, next_char(), and dfsch_strbuf_t::ptr.
Referenced by dfsch_string_ci_eq_p(), dfsch_string_ci_gt_p(), dfsch_string_ci_gte_p(), dfsch_string_ci_lt_p(), and dfsch_string_ci_lte_p().
{
  char* ai = a->ptr;
  char* ae = a->ptr + a->len;
  char* bi = b->ptr;
  char* be = b->ptr + b->len;
  uint32_t ac;
  uint32_t bc;
  while (ai && bi){
    ac = dfsch_char_upcase(get_char(ai, ae));
    bc = dfsch_char_upcase(get_char(bi, be));
    if (ac < bc){
      return -1;
    }
    if (ac > bc){
      return 1;
    }
    ai = next_char(ai, ae);
    bi = next_char(bi, be);
  }
  if (ai) {
    return 1;
  } else if (bi) {
    return -1;
  } else {
    return 0;
  }
}
int dfsch_string_eq_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 247 of file strings.c.
References dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by dfsch__string_native_register().
{
  if (a->len != b->len)
      return 0;
  return memcmp(a->ptr, b->ptr, a->len) == 0;
}
int dfsch_string_gt_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 256 of file strings.c.
References dfsch_string_cmp().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp(a, b) > 0;
}
int dfsch_string_gte_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 262 of file strings.c.
References dfsch_string_cmp().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp(a, b) >= 0;
}
size_t dfsch_string_length (dfsch_object_t * string)
Definition at line 312 of file strings.c.
References dfsch_string_t::buf, dfsch_strbuf_t::len, STRING, and TYPE_CHECK.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_string_t* s = (dfsch_string_t*) string;
  TYPE_CHECK(s, STRING, "string");
  return s->buf.len;
}
dfsch_object_t* dfsch_string_list_append (dfsch_object_t * list)
Definition at line 266 of file strings.c.
References dfsch_string_t::buf, dfsch_car(), dfsch_cdr(), dfsch_make_object(), dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, STRING, and TYPE_CHECK.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  object_t* i = list;
  size_t len = 0;
  dfsch_string_t *r = (dfsch_string_t*)dfsch_make_object(STRING);
  char* ptr;
  while (i){
    dfsch_string_t *s = (dfsch_string_t*)dfsch_car(i);
    TYPE_CHECK(s, STRING, "string");
    len += s->buf.len;
    i = dfsch_cdr(i);
  }
  r->buf.len = len;
  r->buf.ptr = ptr = GC_MALLOC_ATOMIC(len+1);
  i = list;
  while (i){
    dfsch_string_t *s = (dfsch_string_t*)dfsch_car(i);
    memcpy(ptr, s->buf.ptr, s->buf.len);
    ptr += s->buf.len;
    i = dfsch_cdr(i);
  }
  *ptr = 0;
  return (dfsch_object_t*)r;
}
int dfsch_string_lt_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 253 of file strings.c.
References dfsch_string_cmp().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp(a, b) < 0;
}
int dfsch_string_lte_p (dfsch_strbuf_t * a, dfsch_strbuf_t * b)
Definition at line 259 of file strings.c.
References dfsch_string_cmp().
Referenced by dfsch__string_native_register().
{
  return dfsch_string_cmp(a, b) <= 0;
}
char* dfsch_string_or_symbol_to_cstr (dfsch_object_t * obj)
Definition at line 218 of file strings.c.
References dfsch_symbol(), dfsch_symbol_p(), STRING, and TYPE_CHECK.
{
  if (dfsch_symbol_p(obj)){
    return dfsch_symbol(obj);
  }
  TYPE_CHECK(obj, STRING, "string");
  return ((dfsch_string_t*)obj)->buf.ptr;
}
int dfsch_string_p (dfsch_object_t * obj)
Definition at line 167 of file strings.c.
References DFSCH_TYPE_OF.
Referenced by character_data_handler(), DFSCH_DEFINE_PRIMITIVE(), dfsch_named_lambda(), and emit_object().
{
  return DFSCH_TYPE_OF(obj) == &string_type;
}
char dfsch_string_ref (dfsch_object_t * string, size_t index)
Definition at line 301 of file strings.c.
References dfsch_string_t::buf, dfsch_error(), dfsch_make_number_from_long(), dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, STRING, and TYPE_CHECK.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_string_t* s = (dfsch_string_t*) string;
  TYPE_CHECK(s, STRING, "string");
  if (index >= s->buf.len)
    dfsch_error("Index out of bounds",
                dfsch_make_number_from_long(index));
  return s->buf.ptr[index];
}
dfsch_strbuf_t* dfsch_string_replace (dfsch_strbuf_t * str, dfsch_strbuf_t * from, dfsch_strbuf_t * to, int max_matches, int case_sensitive)
Definition at line 1106 of file strings.c.
References dfsch_error(), dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, search_ci_impl(), search_impl(), skip_chars(), sl_create, sl_nappend, sl_value_strbuf, and string_length().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  char* i = str->ptr;
  char* e = str->ptr + str->len;
  char* l = i;
  int c = 0;
  int pos;
  int sep_len = string_length(from->ptr,
                              from->ptr + from->len);
  str_list_t* sl = sl_create();
  if (max_matches != -1 && max_matches < 1){
    dfsch_error("Invalid maximal number of string parts", NULL);
  }
  while (i) {
    if (case_sensitive){
      pos = search_impl(from->ptr, from->ptr + from->len, i, e);
    } else {
      pos = search_ci_impl(from->ptr, from->ptr + from->len,
                           i, e);
    }
    if (pos == -1){
      break;
    }
    i = skip_chars(i, e, pos); // XXX: naive, slow, whatever
    if (i != l) {
      sl_nappend(sl, l, i - l);
    }
    i = skip_chars(i, e, sep_len);
    sl_nappend(sl, to->ptr, to->len);
    l = i;
    if (!l){
      l = e;
    }
    c++;
    if (c == max_matches){
      break;
    }
  }
  if (l != e){
    sl_nappend(sl, l, e - l);
  }
  return sl_value_strbuf(sl);
}
int dfsch_string_search (dfsch_strbuf_t * needle, dfsch_strbuf_t * haystack)
Definition at line 867 of file strings.c.
References dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, and search_impl().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return search_impl(n->ptr, n->ptr + n->len, h->ptr, h->ptr + h->len);
}
int dfsch_string_search_ci (dfsch_strbuf_t * needle, dfsch_strbuf_t * haystack)
Definition at line 911 of file strings.c.
References dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, and search_ci_impl().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return search_ci_impl(n->ptr, n->ptr + n->len, h->ptr, h->ptr + h->len);
}
dfsch_object_t* dfsch_string_split (dfsch_strbuf_t * str, dfsch_strbuf_t * separator, int max_parts, int case_sensitive, int preserve_empty)
Definition at line 924 of file strings.c.
References dfsch_cons(), dfsch_error(), DFSCH_FAST_CDR_MUT, dfsch_make_string_buf(), dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, search_ci_impl(), search_impl(), skip_chars(), and string_length().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  char* i = str->ptr;
  char* e = str->ptr + str->len;
  char* l = i;
  int c = 1;
  int pos;
  int sep_len = string_length(separator->ptr,
                              separator->ptr + separator->len);
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  dfsch_object_t* tmp;
  if (max_parts != -1 && max_parts < 2){
    dfsch_error("Invalid maximal number of string parts", NULL);
  }
  while (i) {
    if (case_sensitive){
      pos = search_impl(separator->ptr, separator->ptr + separator->len, i, e);
    } else {
      pos = search_ci_impl(separator->ptr, separator->ptr + separator->len,
                           i, e);
    }
    if (pos == -1){
      break;
    }
    i = skip_chars(i, e, pos); // XXX: naive, slow, whatever
    if (i != l || preserve_empty) {
      tmp = dfsch_cons(dfsch_make_string_buf(l, i - l), NULL);
      if (head){
        DFSCH_FAST_CDR_MUT(tail) = tmp;
        tail = tmp;
      } else {
        head = tail = tmp;
      }
    }
    i = skip_chars(i, e, sep_len);
    l = i;
    if (!l){
      l = e;
    }
    c++;
    if (c == max_parts){
      break;
    }
  }
  if (l != e || preserve_empty){
    tmp = dfsch_cons(dfsch_make_string_buf(l, e - l), NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    } else {
      head = tail = tmp;
    }
  }
  return head;
}
dfsch_object_t* dfsch_string_split_byte (dfsch_strbuf_t * str, dfsch_strbuf_t * separator, int max_parts, int preserve_empty)
Definition at line 991 of file strings.c.
References dfsch_cons(), dfsch_error(), DFSCH_FAST_CDR_MUT, dfsch_make_string_buf(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  char* i = str->ptr;
  char* e = str->ptr + str->len;
  char* l = i;
  int c = 1;
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  dfsch_object_t* tmp;
  if (max_parts != -1 && max_parts < 2){
    dfsch_error("Invalid maximal number of string parts", NULL);
  }
  while (i != e){
    if (memchr(separator->ptr, *i, separator->len) != NULL){
      if (i != l || preserve_empty) {
        tmp = dfsch_cons(dfsch_make_string_buf(l, i - l), NULL);
        if (head){
          DFSCH_FAST_CDR_MUT(tail) = tmp;
          tail = tmp;
        } else {
          head = tail = tmp;
        }
      }
      i++;
      l = i;
      c++;
      if (c == max_parts){
        break;
      }
    } else {
      i++;
    }
  }
  if (l != e || preserve_empty){
    tmp = dfsch_cons(dfsch_make_string_buf(l, e - l), NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    } else {
      head = tail = tmp;
    }
  }
  return head;
}
dfsch_object_t* dfsch_string_split_char (dfsch_strbuf_t * str, dfsch_strbuf_t * separator, int max_parts, int preserve_empty)
Definition at line 1055 of file strings.c.
References contains_char(), dfsch_cons(), dfsch_error(), DFSCH_FAST_CDR_MUT, dfsch_make_string_buf(), get_char(), dfsch_strbuf_t::len, next_char(), and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  char* i = str->ptr;
  char* e = str->ptr + str->len;
  char* l = i;
  int c = 1;
  dfsch_object_t* head = NULL;
  dfsch_object_t* tail;
  dfsch_object_t* tmp;
  if (max_parts != -1 && max_parts < 2){
    dfsch_error("Invalid maximal number of string parts", NULL);
  }
  while (i){
    if (contains_char(separator, get_char(i, e))){
      if (i != l || preserve_empty) {
        tmp = dfsch_cons(dfsch_make_string_buf(l, i - l), NULL);
        if (head){
          DFSCH_FAST_CDR_MUT(tail) = tmp;
          tail = tmp;
        } else {
          head = tail = tmp;
        }
      }
      i = next_char(i, e);
      l = i;
      c++;
      if (c == max_parts){
        break;
      }
    } else {
      i = next_char(i, e);
    }
  }
  if (l != e || preserve_empty){
    tmp = dfsch_cons(dfsch_make_string_buf(l, e - l), NULL);
    if (head){
      DFSCH_FAST_CDR_MUT(tail) = tmp;
      tail = tmp;
    } else {
      head = tail = tmp;
    }
  }
  return head;
}
dfsch_object_t* dfsch_string_substring (dfsch_object_t * string, size_t start, size_t end)
Definition at line 319 of file strings.c.
References dfsch_string_t::buf, dfsch_error(), dfsch_make_number_from_long(), dfsch_make_string_buf(), dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, STRING, and TYPE_CHECK.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_string_t* s = (dfsch_string_t*) string;
  TYPE_CHECK(s, STRING, "string");
  if (end > s->buf.len)
    dfsch_error("Index out of bounds",
                dfsch_make_number_from_long(end));
  if (start > end)
    dfsch_error("Index out of bounds",
                dfsch_make_number_from_long(start));
  return dfsch_make_string_buf(s->buf.ptr+start, end-start);
}
dfsch_object_t* dfsch_string_substring_utf8 (dfsch_object_t * string, size_t start, size_t end)
Definition at line 488 of file strings.c.
References dfsch_error(), dfsch_make_number_from_long(), dfsch_make_string_buf(), dfsch_string_to_buf(), dfsch_strbuf_t::len, next_char(), and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_strbuf_t* buf = dfsch_string_to_buf(string);
  char* i = buf->ptr;
  char* e = buf->ptr + buf->len;
  size_t l = 0;
  char* sp = NULL;
  char* ep = NULL;
  if (start > end)
    dfsch_error("Index out of bounds",
                dfsch_make_number_from_long(start));
  if (buf->len == 0){
    dfsch_error("Index out of bounds",
                dfsch_make_number_from_long(start));
  }
  while (i){
    if (l == start){
      sp = i;
    }
    if (l == end){
      ep = i;
    }
    l++;
    i = next_char(i, e);
  }
  if (end == l){
    ep = e;
  }
  return dfsch_make_string_buf(sp, ep - sp);
}
dfsch_strbuf_t* dfsch_string_to_buf (dfsch_object_t * obj)
Definition at line 227 of file strings.c.
References STRING, and TYPE_CHECK.
Referenced by character_data_handler(), dfsch_string_substring_utf8(), dfsch_string_utf8_2_list(), dfsch_string_utf8_length(), dfsch_string_utf8_ref(), pathname_basename(), pathname_dirname(), pathname_extension(), pathname_filename(), and string_case().
{
  TYPE_CHECK(obj, STRING, "string");
  return &(((dfsch_string_t*)obj)->buf);
}
char* dfsch_string_to_cstr (dfsch_object_t * obj)
Definition at line 213 of file strings.c.
References STRING, and TYPE_CHECK.
Referenced by dfsch_format(), dfsch_load(), dfsch_sxml_emitter_params(), dfsch_sxml_parser_params(), emit_attrs(), emit_object(), list_source(), search_modules(), string_accessor_set(), and wrapper_write().
{
  TYPE_CHECK(obj, STRING, "string");
  return ((dfsch_string_t*)obj)->buf.ptr;
}