dfsch: lib/sxml_mod.c File Reference
lib/sxml_mod.c File Reference
#include <dfsch/lib/sxml.h>
#include <dfsch/load.h>
Functions
DFSCH_DEFINE_PRIMITIVE (emit_port, 0)
DFSCH_DEFINE_PRIMITIVE (emit_file, 0)
DFSCH_DEFINE_PRIMITIVE (emit_string, 0)
DFSCH_DEFINE_PRIMITIVE (parse_port, 0)
DFSCH_DEFINE_PRIMITIVE (parse_file, 0)
DFSCH_DEFINE_PRIMITIVE (parse_string, 0)
void dfsch_module_sxml_register (dfsch_object_t *env)
Function Documentation
DFSCH_DEFINE_PRIMITIVE (emit_port , 0)
Definition at line 56 of file sxml_mod.c.
References DFSCH_ARG_REST, DFSCH_OBJECT_ARG, dfsch_sxml_emit_port(), and dfsch_sxml_emitter_params().
{
  dfsch_object_t* params;
  dfsch_object_t* infoset;
  dfsch_object_t* port;
  dfsch_sxml_emitter_params_t* p;
  DFSCH_OBJECT_ARG(args, infoset);
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_REST(args, params);
  p = dfsch_sxml_emitter_params(params);
  dfsch_sxml_emit_port(infoset, port, p);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (emit_file , 0)
Definition at line 43 of file sxml_mod.c.
References DFSCH_ARG_REST, DFSCH_OBJECT_ARG, DFSCH_STRING_ARG, dfsch_sxml_emit_file(), and dfsch_sxml_emitter_params().
{
  dfsch_object_t* params;
  dfsch_object_t* infoset;
  char* filename;
  dfsch_sxml_emitter_params_t* p;
  DFSCH_OBJECT_ARG(args, infoset);
  DFSCH_STRING_ARG(args, filename);
  DFSCH_ARG_REST(args, params);
  p = dfsch_sxml_emitter_params(params);
  dfsch_sxml_emit_file(infoset, filename, p);
  return NULL;
}
DFSCH_DEFINE_PRIMITIVE (emit_string , 0)
Definition at line 33 of file sxml_mod.c.
References DFSCH_ARG_REST, dfsch_make_string_cstr(), DFSCH_OBJECT_ARG, dfsch_sxml_emit_cstr(), and dfsch_sxml_emitter_params().
{
  dfsch_object_t* params;
  dfsch_object_t* infoset;
  dfsch_sxml_emitter_params_t* p;
  DFSCH_OBJECT_ARG(args, infoset);
  DFSCH_ARG_REST(args, params);
  p = dfsch_sxml_emitter_params(params);
  return dfsch_make_string_cstr(dfsch_sxml_emit_cstr(infoset, p));
}
DFSCH_DEFINE_PRIMITIVE (parse_port , 0)
Definition at line 22 of file sxml_mod.c.
References DFSCH_ARG_REST, DFSCH_OBJECT_ARG, dfsch_sxml_parse_port(), and dfsch_sxml_parser_params().
{
  dfsch_object_t* port;
  dfsch_object_t* params;
  DFSCH_OBJECT_ARG(args, port);
  DFSCH_ARG_REST(args, params);
  return dfsch_sxml_parse_port(port,
                                   dfsch_sxml_parser_params(params));
}
DFSCH_DEFINE_PRIMITIVE (parse_file , 0)
Definition at line 13 of file sxml_mod.c.
References DFSCH_ARG_REST, DFSCH_STRING_ARG, dfsch_sxml_parse_file(), and dfsch_sxml_parser_params().
{
  char* filename;
  dfsch_object_t* params;
  DFSCH_STRING_ARG(args, filename);
  DFSCH_ARG_REST(args, params);
  return dfsch_sxml_parse_file(filename,
                                   dfsch_sxml_parser_params(params));
}
DFSCH_DEFINE_PRIMITIVE (parse_string , 0)
Definition at line 4 of file sxml_mod.c.
References DFSCH_ARG_REST, DFSCH_BUFFER_ARG, dfsch_sxml_parse_strbuf(), and dfsch_sxml_parser_params().
{
  dfsch_strbuf_t* string;
  dfsch_object_t* params;
  DFSCH_BUFFER_ARG(args, string);
  DFSCH_ARG_REST(args, params);
  return dfsch_sxml_parse_strbuf(string,
                                     dfsch_sxml_parser_params(params));
}
void dfsch_module_sxml_register (dfsch_object_t * env)
Definition at line 70 of file sxml_mod.c.
References dfsch_define_cstr(), DFSCH_PRIMITIVE_REF, and dfsch_provide().
{
  dfsch_provide(env, "sxml");
  dfsch_define_cstr(env, "sxml:parse-string",
                    DFSCH_PRIMITIVE_REF(parse_string));
  dfsch_define_cstr(env, "sxml:parse-file",
                    DFSCH_PRIMITIVE_REF(parse_file));
  dfsch_define_cstr(env, "sxml:parse-port",
                    DFSCH_PRIMITIVE_REF(parse_port));
  dfsch_define_cstr(env, "sxml:emit-string",
                    DFSCH_PRIMITIVE_REF(emit_string));
  dfsch_define_cstr(env, "sxml:emit-file",
                    DFSCH_PRIMITIVE_REF(emit_file));
  dfsch_define_cstr(env, "sxml:emit-port",
                    DFSCH_PRIMITIVE_REF(emit_port));
}