dfsch: lib/sxml.c File Reference
lib/sxml.c File Reference
#include <dfsch/lib/sxml.h>
#include <dfsch/lib/xml.h>
#include <dfsch/util.h>
#include <dfsch/ports.h>
#include <expat.h>
#include <assert.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <dfsch/magic.h>
Data Structures
struct emitter_t
struct parser_ctx_t
struct sxml_stack_t
Defines
#define BUFFER_LENGTH 4096
Typedefs
typedef struct sxml_stack_t sxml_stack_t
typedef void(* write_cb_t)(void *target, char *buf)
Functions
static XMLCALL void character_data_handler (parser_ctx_t *c, char *data, int len)
DFSCH_LOCAL_SYMBOL_CACHE ("@", at_symbol)
char * dfsch_sxml_emit_cstr (dfsch_object_t *infoset, dfsch_sxml_emitter_params_t *params)
void dfsch_sxml_emit_file (dfsch_object_t *infoset, char *filename, dfsch_sxml_emitter_params_t *params)
void dfsch_sxml_emit_port (dfsch_object_t *infoset, dfsch_object_t *port, dfsch_sxml_emitter_params_t *params)
dfsch_sxml_emitter_params_t * dfsch_sxml_emitter_params (dfsch_object_t *args)
dfsch_object_t * dfsch_sxml_parse_buf (char *buf, size_t len, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_cstr (char *s, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_file (char *filename, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_port (dfsch_object_t *port, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_strbuf (dfsch_strbuf_t *b, dfsch_sxml_parser_params_t *params)
dfsch_sxml_parser_params_t * dfsch_sxml_parser_params (dfsch_object_t *args)
static void emit_attrs (emitter_t *e, dfsch_object_t *attrs)
static void emit_element (emitter_t *e, char *name, dfsch_object_t *children)
static void emit_infoset (emitter_t *e, dfsch_object_t *infoset)
static emitter_t * emit_init (dfsch_sxml_emitter_params_t *params, void *target, write_cb_t write)
static void emit_object (emitter_t *e, dfsch_object_t *o)
static XMLCALL void end_element_handler (parser_ctx_t *c, char *name)
static void rfputs (FILE *f, char *s)
static XMLCALL void start_element_handler (parser_ctx_t *c, char *name, char **attrs)
static void sxml_append (parser_ctx_t *c, dfsch_object_t *o)
static dfsch_object_t * sxml_done (XML_Parser p)
static XML_Parser sxml_init (dfsch_sxml_parser_params_t *params)
static void sxml_pop (parser_ctx_t *c)
static void sxml_push (parser_ctx_t *c, dfsch_object_t *tag)
Variables
static dfsch_sxml_parser_params_t default_parser_params
static XML_Memory_Handling_Suite gc_suite
Define Documentation
#define BUFFER_LENGTH 4096
Definition at line 130 of file sxml.c.
Referenced by dfsch_sxml_parse_file(), dfsch_sxml_parse_port(), dfsch_xml_parse_file(), and dfsch_xml_parse_port().
Typedef Documentation
typedef struct sxml_stack_t sxml_stack_t
Definition at line 12 of file sxml.c.
typedef void(* write_cb_t)(void *target, char *buf)
Definition at line 225 of file sxml.c.
Function Documentation
static XMLCALL void character_data_handler (parser_ctx_t * c, char * data, int len) [static]
Definition at line 76 of file sxml.c.
References DFSCH_FAST_CAR, dfsch_make_string_buf(), dfsch_string_p(), dfsch_string_to_buf(), dfsch_strbuf_t::len, dfsch_strbuf_t::ptr, parser_ctx_t::stack, sxml_append(), and sxml_stack_t::tail.
Referenced by sxml_init().
{
  if (dfsch_string_p(DFSCH_FAST_CAR(c->stack->tail))){
    dfsch_strbuf_t* o = dfsch_string_to_buf(DFSCH_FAST_CAR(c->stack->tail));
    char* buf = GC_MALLOC_ATOMIC(len+o->len);
    memcpy(buf, o->ptr, o->len);
    memcpy(buf+o->len, data, len);
    DFSCH_FAST_CAR(c->stack->tail) = dfsch_make_string_buf(buf, len+o->len);
  } else {
    sxml_append(c, dfsch_make_string_buf(data, len));
  }
}
DFSCH_LOCAL_SYMBOL_CACHE ("@" , at_symbol)
char* dfsch_sxml_emit_cstr (dfsch_object_t * infoset, dfsch_sxml_emitter_params_t * params)
Definition at line 323 of file sxml.c.
References dfsch_sl_append(), dfsch_sl_create(), dfsch_sl_value(), emit_infoset(), emit_init(), and emitter_t::target.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  emitter_t* e = emit_init(params, dfsch_sl_create(), dfsch_sl_append);
  emit_infoset(e, infoset);
  return dfsch_sl_value(e->target);
}
void dfsch_sxml_emit_file (dfsch_object_t * infoset, char * filename, dfsch_sxml_emitter_params_t * params)
Definition at line 341 of file sxml.c.
References dfsch_error(), dfsch_list(), dfsch_make_string_cstr(), DFSCH_PROTECT, DFSCH_PROTECT_END, DFSCH_UNWIND, emit_infoset(), emit_init(), and rfputs().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  emitter_t* e;
  FILE* f = fopen(filename, "w");
  if (!f){
    dfsch_error("Cannot open file",
                dfsch_list(2,
                           dfsch_make_string_cstr(filename),
                           dfsch_make_string_cstr(strerror(errno))));
  }
  DFSCH_UNWIND {
    e = emit_init(params, f, rfputs);
    emit_infoset(e, infoset);
  } DFSCH_PROTECT {
    fclose(f);
  } DFSCH_PROTECT_END;
}
void dfsch_sxml_emit_port (dfsch_object_t * infoset, dfsch_object_t * port, dfsch_sxml_emitter_params_t * params)
Definition at line 329 of file sxml.c.
References dfsch_port_write_cstr(), emit_infoset(), and emit_init().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  emitter_t* e = emit_init(params, port, dfsch_port_write_cstr);
  emit_infoset(e, infoset);
}
dfsch_sxml_emitter_params_t* dfsch_sxml_emitter_params (dfsch_object_t * args)
Definition at line 361 of file sxml.c.
References DFSCH_KEYWORD_GENERIC, DFSCH_KEYWORD_PARSER_BEGIN, DFSCH_KEYWORD_PARSER_END, dfsch_string_to_cstr(), DFSCH_TRUE_P, dfsch_sxml_emitter_params_t::dtd_public, dfsch_sxml_emitter_params_t::dtd_system, dfsch_sxml_emitter_params_t::prepend_string, dfsch_sxml_emitter_params_t::pretty_print, and dfsch_sxml_emitter_params_t::xml_decl.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_sxml_emitter_params_t* p = GC_NEW(dfsch_sxml_emitter_params_t);
  DFSCH_KEYWORD_PARSER_BEGIN(args);
  DFSCH_KEYWORD_GENERIC("pretty-print", p->pretty_print, DFSCH_TRUE_P);
  DFSCH_KEYWORD_GENERIC("xml-decl", p->xml_decl, DFSCH_TRUE_P);
  DFSCH_KEYWORD_GENERIC("dtd-public", p->dtd_public, dfsch_string_to_cstr);
  DFSCH_KEYWORD_GENERIC("dtd-system", p->dtd_system, dfsch_string_to_cstr);
  DFSCH_KEYWORD_GENERIC("prepend-string", p->prepend_string,
                        dfsch_string_to_cstr);
  DFSCH_KEYWORD_PARSER_END(args);
  return p;
}
dfsch_object_t* dfsch_sxml_parse_buf (char * buf, size_t len, dfsch_sxml_parser_params_t * params)
Definition at line 197 of file sxml.c.
References dfsch_xml_signal_error(), sxml_done(), and sxml_init().
Referenced by dfsch_sxml_parse_cstr(), and dfsch_sxml_parse_strbuf().
{
  XML_Parser p = sxml_init(params);
  if (XML_Parse(p, buf, len, 1) != XML_STATUS_OK){
    dfsch_xml_signal_error(p);
  }
  return sxml_done(p);
}
dfsch_object_t* dfsch_sxml_parse_cstr (char * s, dfsch_sxml_parser_params_t * params)
Definition at line 209 of file sxml.c.
References dfsch_sxml_parse_buf().
{
  return dfsch_sxml_parse_buf(s, strlen(s), params);
}
dfsch_object_t* dfsch_sxml_parse_file (char * filename, dfsch_sxml_parser_params_t * params)
Definition at line 132 of file sxml.c.
References BUFFER_LENGTH, dfsch_error(), dfsch_list(), dfsch_make_string_cstr(), dfsch_xml_signal_error(), sxml_done(), and sxml_init().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  XML_Parser p = sxml_init(params);
  FILE* f;
  size_t r;
  char* buf;
  f = fopen(filename, "r");
  if (!f){
    dfsch_error("Cannot open file",
                dfsch_list(2,
                           dfsch_make_string_cstr(filename),
                           dfsch_make_string_cstr(strerror(errno))));
  }
  while ((!feof(f)) && (!ferror(f))){
    buf = XML_GetBuffer(p, BUFFER_LENGTH);
    r = fread(buf, 1, BUFFER_LENGTH, f);
    if (XML_ParseBuffer(p, r, 0) != XML_STATUS_OK){
      fclose(f);
      dfsch_xml_signal_error(p);
    }
  }
  if (ferror(f)){
    dfsch_object_t* tmp = dfsch_list(2,
                                     dfsch_make_string_cstr(filename),
                                     dfsch_make_string_cstr(strerror(errno)));
    fclose(f);
    dfsch_error("Error reading file", tmp);
  }
  fclose(f);
  if (XML_Parse(p, NULL, 0, 1) != XML_STATUS_OK){
    dfsch_xml_signal_error(p);
  }
  return sxml_done(p);
}
dfsch_object_t* dfsch_sxml_parse_port (dfsch_object_t * port, dfsch_sxml_parser_params_t * params)
Definition at line 172 of file sxml.c.
References BUFFER_LENGTH, dfsch_port_read_buf(), dfsch_xml_signal_error(), sxml_done(), and sxml_init().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  XML_Parser p = sxml_init(params);
  size_t r;
  char* buf;
  while (1){
    buf = XML_GetBuffer(p, BUFFER_LENGTH);
    r = dfsch_port_read_buf(port, buf, BUFFER_LENGTH);
    if (r==0){
      break;
    }
    if (XML_ParseBuffer(p, r, 0) != XML_STATUS_OK){
      dfsch_xml_signal_error(p);
    }
  }
  if (XML_Parse(p, NULL, 0, 1) != XML_STATUS_OK){
    dfsch_xml_signal_error(p);
  }
  return sxml_done(p);
}
dfsch_object_t* dfsch_sxml_parse_strbuf (dfsch_strbuf_t * b, dfsch_sxml_parser_params_t * params)
Definition at line 205 of file sxml.c.
References dfsch_sxml_parse_buf(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_sxml_parse_buf(b->ptr, b->len, params);
}
dfsch_sxml_parser_params_t* dfsch_sxml_parser_params (dfsch_object_t * args)
Definition at line 214 of file sxml.c.
References dfsch_sxml_parser_params_t::collapse_whitespace, DFSCH_KEYWORD_GENERIC, DFSCH_KEYWORD_PARSER_BEGIN, DFSCH_KEYWORD_PARSER_END, dfsch_string_to_cstr(), DFSCH_TRUE_P, dfsch_sxml_parser_params_t::encoding, and dfsch_sxml_parser_params_t::namespaces.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_sxml_parser_params_t* p = GC_NEW(dfsch_sxml_parser_params_t);
  DFSCH_KEYWORD_PARSER_BEGIN(args);
  DFSCH_KEYWORD_GENERIC("namespaces", p->namespaces, DFSCH_TRUE_P);
  DFSCH_KEYWORD_GENERIC("encoding", p->encoding, dfsch_string_to_cstr);
  DFSCH_KEYWORD_GENERIC("collapse-whitespace",
                        p->collapse_whitespace, DFSCH_TRUE_P);
  DFSCH_KEYWORD_PARSER_END(args);
  return p;
}
static void emit_attrs (emitter_t * e, dfsch_object_t * attrs) [static]
Definition at line 245 of file sxml.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_inet_xml_escape(), dfsch_list_length(), DFSCH_PAIR_P, dfsch_saprintf(), dfsch_string_to_cstr(), dfsch_symbol(), emitter_t::target, and emitter_t::write.
Referenced by emit_element().
{
  while (DFSCH_PAIR_P(attrs)){
    dfsch_object_t* a = DFSCH_FAST_CAR(attrs);
    char *name;
    char *value;
    switch (dfsch_list_length(a, NULL)){
    case 1:
      name = dfsch_symbol(DFSCH_FAST_CAR(a));
      e->write(e->target, dfsch_saprintf(" %s=\"%s\"", name, name));
      break;
    case 2:
      name = dfsch_symbol(DFSCH_FAST_CAR(a));
      a = DFSCH_FAST_CDR(a);
      value = dfsch_string_to_cstr(DFSCH_FAST_CAR(a));
      e->write(e->target, dfsch_saprintf(" %s=\"%s\"", name,
                                         dfsch_inet_xml_escape(value)));
      break;
    default:
      dfsch_error("Invalid format of attribute", a);
    }
    attrs = DFSCH_FAST_CDR(attrs);
  }
}
static void emit_element (emitter_t * e, char * name, dfsch_object_t * children) [static]
Definition at line 274 of file sxml.c.
References DFSCH_FAST_CAR, DFSCH_FAST_CDR, DFSCH_PAIR_P, dfsch_saprintf(), emit_attrs(), emit_object(), emitter_t::target, and emitter_t::write.
Referenced by emit_object().
{
  dfsch_object_t* attrs = NULL;
  if (DFSCH_PAIR_P(children) &&
      DFSCH_PAIR_P(DFSCH_FAST_CAR(children)) &&
      DFSCH_FAST_CAR(DFSCH_FAST_CAR(children)) == at_symbol()){
    attrs = DFSCH_FAST_CDR(DFSCH_FAST_CAR(children));
    children = DFSCH_FAST_CDR(children);
  }
  e->write(e->target, "<");
  e->write(e->target, name);
  emit_attrs(e, attrs);
  if (children){
    e->write(e->target, ">");
    while (DFSCH_PAIR_P(children)){
      emit_object(e, DFSCH_FAST_CAR(children));
      children = DFSCH_FAST_CDR(children);
    }
    e->write(e->target, dfsch_saprintf("</%s>", name));
  } else {
    e->write(e->target, " />");
  }
}
static void emit_infoset (emitter_t * e, dfsch_object_t * infoset) [static]
Definition at line 309 of file sxml.c.
References dfsch_saprintf(), dfsch_sxml_emitter_params_t::dtd_public, dfsch_sxml_emitter_params_t::dtd_system, emit_object(), emitter_t::params, emitter_t::target, emitter_t::write, and dfsch_sxml_emitter_params_t::xml_decl.
Referenced by dfsch_sxml_emit_cstr(), dfsch_sxml_emit_file(), and dfsch_sxml_emit_port().
{
  if (e->params->xml_decl){
    e->write(e->target, "<?xml version=\"1.0\" ?>\n");
  }
  if (e->params->dtd_public && e->params->dtd_system){
    /* XML does not allow PUBLIC-only DTD*/
    e->write(e->target,
             dfsch_saprintf("<!DOCTYPE PUBLIC \"%s\" \"%s\">",
                            e->params->dtd_public,
                            e->params->dtd_system));
  }
  emit_object(e, infoset);
}
static emitter_t* emit_init (dfsch_sxml_emitter_params_t * params, void * target, write_cb_t write) [static]
Definition at line 234 of file sxml.c.
References emitter_t::params, emitter_t::start_col, emitter_t::target, and emitter_t::write.
Referenced by dfsch_sxml_emit_cstr(), dfsch_sxml_emit_file(), and dfsch_sxml_emit_port().
{
  emitter_t* e = GC_NEW(emitter_t);
  e->params = params;
  e->target = target;
  e->write = write;
  e->start_col = 0;
  return e;
}
static void emit_object (emitter_t * e, dfsch_object_t * o) [static]
Definition at line 299 of file sxml.c.
References dfsch_error(), DFSCH_FAST_CAR, DFSCH_FAST_CDR, dfsch_inet_xml_escape(), DFSCH_PAIR_P, dfsch_string_p(), dfsch_string_to_cstr(), dfsch_symbol(), emit_element(), emitter_t::target, and emitter_t::write.
Referenced by emit_element(), and emit_infoset().
{
  if (dfsch_string_p(o)){
    e->write(e->target, dfsch_inet_xml_escape(dfsch_string_to_cstr(o)));
  } else if (DFSCH_PAIR_P(o)){
    emit_element(e, dfsch_symbol(DFSCH_FAST_CAR(o)), DFSCH_FAST_CDR(o));
  } else {
    dfsch_error("Invalid object in SXML infoset", o);
  }
}
static XMLCALL void end_element_handler (parser_ctx_t * c, char * name) [static]
Definition at line 71 of file sxml.c.
References sxml_pop().
Referenced by sxml_init().
{
  sxml_pop(c);
}
static void rfputs (FILE * f, char * s) [static]
Definition at line 335 of file sxml.c.
References dfsch_error().
Referenced by dfsch_sxml_emit_file().
{
  if (fputs(s, f) == EOF){
    dfsch_error("fputs failed", NULL);
  }
}
static XMLCALL void start_element_handler (parser_ctx_t * c, char * name, char ** attrs) [static]
Definition at line 55 of file sxml.c.
References dfsch_cons(), dfsch_list(), dfsch_make_string_cstr(), dfsch_make_symbol(), sxml_append(), and sxml_push().
Referenced by sxml_init().
{
  sxml_push(c, dfsch_make_symbol(name));
  if (*attrs){
    dfsch_object_t* a_list = NULL;
    while (*attrs){
      a_list = dfsch_cons(dfsch_list(2,
                                     dfsch_make_symbol(*attrs),
                                     dfsch_make_string_cstr(*(attrs+1))),
                          a_list);
      attrs+=2;
    }
    sxml_append(c, dfsch_cons(at_symbol(), a_list));
  }
}
static void sxml_append (parser_ctx_t * c, dfsch_object_t * o) [static]
Definition at line 40 of file sxml.c.
References dfsch_cons(), DFSCH_FAST_CDR_MUT, parser_ctx_t::res, parser_ctx_t::stack, and sxml_stack_t::tail.
Referenced by character_data_handler(), start_element_handler(), and sxml_pop().
{
  if (!c->stack){
    c->res = o;
  } else {
    dfsch_object_t* p = dfsch_cons(o, NULL);
    DFSCH_FAST_CDR_MUT(c->stack->tail) = p;
    c->stack->tail = p;
  }
}
static dfsch_object_t* sxml_done (XML_Parser p) [static]
Definition at line 124 of file sxml.c.
References parser_ctx_t::res, and parser_ctx_t::stack.
Referenced by dfsch_sxml_parse_buf(), dfsch_sxml_parse_file(), and dfsch_sxml_parse_port().
{
  parser_ctx_t* c = XML_GetUserData(p);
  assert(!c->stack);
  return c->res;
}
static XML_Parser sxml_init (dfsch_sxml_parser_params_t * params) [static]
Definition at line 97 of file sxml.c.
References character_data_handler(), dfsch_sxml_parser_params_t::encoding, end_element_handler(), gc_suite, dfsch_sxml_parser_params_t::namespaces, parser_ctx_t::params, parser_ctx_t::stack, and start_element_handler().
Referenced by dfsch_sxml_parse_buf(), dfsch_sxml_parse_file(), and dfsch_sxml_parse_port().
{
  XML_Parser p;
  parser_ctx_t* c;
  static char sep = ':';
  if (!params){
    params = &default_parser_params;
  }
  p = XML_ParserCreate_MM(params->encoding, &gc_suite,
                          params->namespaces ? &sep : NULL);
  c = GC_NEW(parser_ctx_t);
  c->params = params;
  c->stack = NULL;
  XML_SetUserData(p, c);
  XML_SetElementHandler(p,
                        (XML_StartElementHandler)start_element_handler,
                        (XML_EndElementHandler)end_element_handler);
  XML_SetCharacterDataHandler(p,
                              (XML_CharacterDataHandler)character_data_handler);
  return p;
}
static void sxml_pop (parser_ctx_t * c) [static]
Definition at line 49 of file sxml.c.
References sxml_stack_t::head, sxml_stack_t::next, parser_ctx_t::stack, and sxml_append().
Referenced by end_element_handler().
{
  dfsch_object_t* l = c->stack->head;
  c->stack = c->stack->next;
  sxml_append(c, l);
}
static void sxml_push (parser_ctx_t * c, dfsch_object_t * tag) [static]
Definition at line 34 of file sxml.c.
References dfsch_cons(), sxml_stack_t::head, sxml_stack_t::next, parser_ctx_t::stack, and sxml_stack_t::tail.
Referenced by start_element_handler().
{
  sxml_stack_t* s = GC_NEW(stack_t);
  s->next = c->stack;
  s->head = s->tail = dfsch_cons(tag, NULL);
  c->stack = s;
}
Variable Documentation
dfsch_sxml_parser_params_t default_parser_params [static]
Initial value:
 {
  0,
  NULL,
  0
}
Definition at line 91 of file sxml.c.
XML_Memory_Handling_Suite gc_suite [static]
Initial value:
 {
  GC_malloc,
  GC_realloc,
  GC_free
}
Definition at line 26 of file sxml.c.
Referenced by sxml_init().