dfsch: dfsch/lib/sxml.h File Reference
dfsch/lib/sxml.h File Reference
#include <dfsch/dfsch.h>
Data Structures
struct dfsch_sxml_emitter_params_t
struct dfsch_sxml_parser_params_t
Functions
char * dfsch_sxml_emit_cstr (dfsch_object_t *infoset, dfsch_sxml_emitter_params_t *params)
void dfsch_sxml_emit_file (dfsch_object_t *infoset, char *filename, dfsch_sxml_emitter_params_t *params)
void dfsch_sxml_emit_port (dfsch_object_t *infoset, dfsch_object_t *port, dfsch_sxml_emitter_params_t *params)
dfsch_sxml_emitter_params_t * dfsch_sxml_emitter_params (dfsch_object_t *args)
dfsch_object_t * dfsch_sxml_parse_buf (char *buf, size_t len, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_cstr (char *s, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_file (char *filename, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_port (dfsch_object_t *port, dfsch_sxml_parser_params_t *params)
dfsch_object_t * dfsch_sxml_parse_strbuf (dfsch_strbuf_t *b, dfsch_sxml_parser_params_t *params)
dfsch_sxml_parser_params_t * dfsch_sxml_parser_params (dfsch_object_t *args)
Function Documentation
char* dfsch_sxml_emit_cstr (dfsch_object_t * infoset, dfsch_sxml_emitter_params_t * params)
Definition at line 323 of file sxml.c.
References dfsch_sl_append(), dfsch_sl_create(), dfsch_sl_value(), emit_infoset(), emit_init(), and emitter_t::target.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  emitter_t* e = emit_init(params, dfsch_sl_create(), dfsch_sl_append);
  emit_infoset(e, infoset);
  return dfsch_sl_value(e->target);
}
void dfsch_sxml_emit_file (dfsch_object_t * infoset, char * filename, dfsch_sxml_emitter_params_t * params)
Definition at line 341 of file sxml.c.
References dfsch_error(), dfsch_list(), dfsch_make_string_cstr(), DFSCH_PROTECT, DFSCH_PROTECT_END, DFSCH_UNWIND, emit_infoset(), emit_init(), and rfputs().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  emitter_t* e;
  FILE* f = fopen(filename, "w");
  if (!f){
    dfsch_error("Cannot open file",
                dfsch_list(2,
                           dfsch_make_string_cstr(filename),
                           dfsch_make_string_cstr(strerror(errno))));
  }
  DFSCH_UNWIND {
    e = emit_init(params, f, rfputs);
    emit_infoset(e, infoset);
  } DFSCH_PROTECT {
    fclose(f);
  } DFSCH_PROTECT_END;
}
void dfsch_sxml_emit_port (dfsch_object_t * infoset, dfsch_object_t * port, dfsch_sxml_emitter_params_t * params)
Definition at line 329 of file sxml.c.
References dfsch_port_write_cstr(), emit_infoset(), and emit_init().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  emitter_t* e = emit_init(params, port, dfsch_port_write_cstr);
  emit_infoset(e, infoset);
}
dfsch_sxml_emitter_params_t* dfsch_sxml_emitter_params (dfsch_object_t * args)
Definition at line 361 of file sxml.c.
References DFSCH_KEYWORD_GENERIC, DFSCH_KEYWORD_PARSER_BEGIN, DFSCH_KEYWORD_PARSER_END, dfsch_string_to_cstr(), DFSCH_TRUE_P, dfsch_sxml_emitter_params_t::dtd_public, dfsch_sxml_emitter_params_t::dtd_system, dfsch_sxml_emitter_params_t::prepend_string, dfsch_sxml_emitter_params_t::pretty_print, and dfsch_sxml_emitter_params_t::xml_decl.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_sxml_emitter_params_t* p = GC_NEW(dfsch_sxml_emitter_params_t);
  DFSCH_KEYWORD_PARSER_BEGIN(args);
  DFSCH_KEYWORD_GENERIC("pretty-print", p->pretty_print, DFSCH_TRUE_P);
  DFSCH_KEYWORD_GENERIC("xml-decl", p->xml_decl, DFSCH_TRUE_P);
  DFSCH_KEYWORD_GENERIC("dtd-public", p->dtd_public, dfsch_string_to_cstr);
  DFSCH_KEYWORD_GENERIC("dtd-system", p->dtd_system, dfsch_string_to_cstr);
  DFSCH_KEYWORD_GENERIC("prepend-string", p->prepend_string,
                        dfsch_string_to_cstr);
  DFSCH_KEYWORD_PARSER_END(args);
  return p;
}
dfsch_object_t* dfsch_sxml_parse_buf (char * buf, size_t len, dfsch_sxml_parser_params_t * params)
Definition at line 197 of file sxml.c.
References dfsch_xml_signal_error(), sxml_done(), and sxml_init().
Referenced by dfsch_sxml_parse_cstr(), and dfsch_sxml_parse_strbuf().
{
  XML_Parser p = sxml_init(params);
  if (XML_Parse(p, buf, len, 1) != XML_STATUS_OK){
    dfsch_xml_signal_error(p);
  }
  return sxml_done(p);
}
dfsch_object_t* dfsch_sxml_parse_cstr (char * s, dfsch_sxml_parser_params_t * params)
Definition at line 209 of file sxml.c.
References dfsch_sxml_parse_buf().
{
  return dfsch_sxml_parse_buf(s, strlen(s), params);
}
dfsch_object_t* dfsch_sxml_parse_file (char * filename, dfsch_sxml_parser_params_t * params)
Definition at line 132 of file sxml.c.
References BUFFER_LENGTH, dfsch_error(), dfsch_list(), dfsch_make_string_cstr(), dfsch_xml_signal_error(), sxml_done(), and sxml_init().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  XML_Parser p = sxml_init(params);
  FILE* f;
  size_t r;
  char* buf;
  f = fopen(filename, "r");
  if (!f){
    dfsch_error("Cannot open file",
                dfsch_list(2,
                           dfsch_make_string_cstr(filename),
                           dfsch_make_string_cstr(strerror(errno))));
  }
  while ((!feof(f)) && (!ferror(f))){
    buf = XML_GetBuffer(p, BUFFER_LENGTH);
    r = fread(buf, 1, BUFFER_LENGTH, f);
    if (XML_ParseBuffer(p, r, 0) != XML_STATUS_OK){
      fclose(f);
      dfsch_xml_signal_error(p);
    }
  }
  if (ferror(f)){
    dfsch_object_t* tmp = dfsch_list(2,
                                     dfsch_make_string_cstr(filename),
                                     dfsch_make_string_cstr(strerror(errno)));
    fclose(f);
    dfsch_error("Error reading file", tmp);
  }
  fclose(f);
  if (XML_Parse(p, NULL, 0, 1) != XML_STATUS_OK){
    dfsch_xml_signal_error(p);
  }
  return sxml_done(p);
}
dfsch_object_t* dfsch_sxml_parse_port (dfsch_object_t * port, dfsch_sxml_parser_params_t * params)
Definition at line 172 of file sxml.c.
References BUFFER_LENGTH, dfsch_port_read_buf(), dfsch_xml_signal_error(), sxml_done(), and sxml_init().
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  XML_Parser p = sxml_init(params);
  size_t r;
  char* buf;
  while (1){
    buf = XML_GetBuffer(p, BUFFER_LENGTH);
    r = dfsch_port_read_buf(port, buf, BUFFER_LENGTH);
    if (r==0){
      break;
    }
    if (XML_ParseBuffer(p, r, 0) != XML_STATUS_OK){
      dfsch_xml_signal_error(p);
    }
  }
  if (XML_Parse(p, NULL, 0, 1) != XML_STATUS_OK){
    dfsch_xml_signal_error(p);
  }
  return sxml_done(p);
}
dfsch_object_t* dfsch_sxml_parse_strbuf (dfsch_strbuf_t * b, dfsch_sxml_parser_params_t * params)
Definition at line 205 of file sxml.c.
References dfsch_sxml_parse_buf(), dfsch_strbuf_t::len, and dfsch_strbuf_t::ptr.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  return dfsch_sxml_parse_buf(b->ptr, b->len, params);
}
dfsch_sxml_parser_params_t* dfsch_sxml_parser_params (dfsch_object_t * args)
Definition at line 214 of file sxml.c.
References dfsch_sxml_parser_params_t::collapse_whitespace, DFSCH_KEYWORD_GENERIC, DFSCH_KEYWORD_PARSER_BEGIN, DFSCH_KEYWORD_PARSER_END, dfsch_string_to_cstr(), DFSCH_TRUE_P, dfsch_sxml_parser_params_t::encoding, and dfsch_sxml_parser_params_t::namespaces.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  dfsch_sxml_parser_params_t* p = GC_NEW(dfsch_sxml_parser_params_t);
  DFSCH_KEYWORD_PARSER_BEGIN(args);
  DFSCH_KEYWORD_GENERIC("namespaces", p->namespaces, DFSCH_TRUE_P);
  DFSCH_KEYWORD_GENERIC("encoding", p->encoding, dfsch_string_to_cstr);
  DFSCH_KEYWORD_GENERIC("collapse-whitespace",
                        p->collapse_whitespace, DFSCH_TRUE_P);
  DFSCH_KEYWORD_PARSER_END(args);
  return p;
}