dfsch: src/system.c File Reference
src/system.c File Reference
#include "internal.h"
#include "util.h"
#include <dfsch/dfsch.h>
#include <dfsch/number.h>
#include <time.h>
#include <sys/times.h>
#include <unistd.h>
#include <limits.h>
Data Structures
struct decoded_time_t
Functions
static dfsch_object_t * decoded_time_apply (decoded_time_t *time, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static int decoded_time_equal_p (decoded_time_t *a, decoded_time_t *b)
size_t decoded_time_hash (decoded_time_t *time)
static void decoded_time_write (decoded_time_t *time, dfsch_writer_state_t *state)
void dfsch__system_register (dfsch_object_t *ctx)
struct tm * dfsch_decoded_time_get_tm (dfsch_object_t *time)
DFSCH_DEFINE_PRIMITIVE (get_internal_run_time, NULL)
DFSCH_DEFINE_PRIMITIVE (get_internal_real_time, NULL)
dfsch_object_t * dfsch_make_decoded_time ()
static dfsch_object_t * native_decode_universal_time (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_encode_universal_time (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_get_decoded_time (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_get_universal_time (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_iso_format_time (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Variables
dfsch_type_t decoded_time_type
Function Documentation
static dfsch_object_t* decoded_time_apply (decoded_time_t * time, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 58 of file system.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_compare_symbol(), dfsch_error(), dfsch_make_number_from_long(), DFSCH_OBJECT_ARG, and decoded_time_t::tm.
{
  dfsch_object_t* selector;
  DFSCH_OBJECT_ARG(args, selector);
  DFSCH_ARG_END(args);
  if (dfsch_compare_symbol(selector, "sec")){
    return dfsch_make_number_from_long(time->tm.tm_sec);
  } else if (dfsch_compare_symbol(selector, "min")){
    return dfsch_make_number_from_long(time->tm.tm_min);
  } else if (dfsch_compare_symbol(selector, "hour")){
    return dfsch_make_number_from_long(time->tm.tm_hour);
  } else if (dfsch_compare_symbol(selector, "date")){
    return dfsch_make_number_from_long(time->tm.tm_mday);
  } else if (dfsch_compare_symbol(selector, "month")){
    return dfsch_make_number_from_long(time->tm.tm_mon + 1);
  } else if (dfsch_compare_symbol(selector, "year")){
    return dfsch_make_number_from_long(time->tm.tm_year + 1900);
  } else if (dfsch_compare_symbol(selector, "day")){
    return dfsch_make_number_from_long(time->tm.tm_wday);
  } else if (dfsch_compare_symbol(selector, "year-day")){
    return dfsch_make_number_from_long(time->tm.tm_yday + 1);
  } else if (dfsch_compare_symbol(selector, "dst?")){
    return dfsch_bool(time->tm.tm_isdst == 1);
  }
  dfsch_error("exception:no-such-decoded-time-field", selector);
}
static int decoded_time_equal_p (decoded_time_t * a, decoded_time_t * b) [static]
Definition at line 38 of file system.c.
References decoded_time_t::tm.
{
  return (a->tm.tm_sec == b->tm.tm_sec)
    && (a->tm.tm_min == b->tm.tm_min)
    && (a->tm.tm_hour == b->tm.tm_hour)
    && (a->tm.tm_mday == b->tm.tm_mday)
    && (a->tm.tm_mon == b->tm.tm_mon)
    && (a->tm.tm_year == b->tm.tm_year)
    && (a->tm.tm_wday == b->tm.tm_wday)
    && (a->tm.tm_yday == b->tm.tm_yday)
    && (a->tm.tm_isdst == b->tm.tm_isdst);
}
size_t decoded_time_hash (decoded_time_t * time)
Definition at line 89 of file system.c.
References decoded_time_t::tm.
{
  return time->tm.tm_sec ^ time->tm.tm_min ^ time->tm.tm_hour
    ^ time->tm.tm_yday ^ time->tm.tm_year;
}
static void decoded_time_write (decoded_time_t * time, dfsch_writer_state_t * state) [static]
Definition at line 50 of file system.c.
References dfsch_write_unreadable(), and decoded_time_t::tm.
{
  dfsch_write_unreadable(state, time, "%04d-%02d-%02dT%02d:%02d:%02d",
                         time->tm.tm_year+1900, time->tm.tm_mon+1,
                         time->tm.tm_mday,
                         time->tm.tm_hour, time->tm.tm_min, time->tm.tm_sec);
}
void dfsch__system_register (dfsch_object_t * ctx)
Definition at line 229 of file system.c.
References dfsch_define_cstr(), dfsch_make_number_from_long(), dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, native_decode_universal_time(), native_encode_universal_time(), native_get_decoded_time(), native_get_universal_time(), and native_iso_format_time().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<decoded-time>", &decoded_time_type);
  dfsch_define_cstr(ctx, "decode-universal-time",
                    dfsch_make_primitive(native_decode_universal_time, NULL));
  dfsch_define_cstr(ctx, "encode-universal-time",
                    dfsch_make_primitive(native_encode_universal_time, NULL));
  dfsch_define_cstr(ctx, "get-decoded-time",
                    dfsch_make_primitive(native_get_decoded_time, NULL));
  dfsch_define_cstr(ctx, "get-universal-time",
                    dfsch_make_primitive(native_get_universal_time, NULL));
  dfsch_define_cstr(ctx, "iso-format-time",
                    dfsch_make_primitive(native_iso_format_time, NULL));
  dfsch_define_cstr(ctx, "get-internal-real-time",
                    DFSCH_PRIMITIVE_REF(get_internal_real_time));
  dfsch_define_cstr(ctx, "get-internal-run-time",
                    DFSCH_PRIMITIVE_REF(get_internal_run_time));
  dfsch_define_cstr(ctx, "internal-time-units-per-second",
                    dfsch_make_number_from_long(sysconf(_SC_CLK_TCK)));
}
struct tm* dfsch_decoded_time_get_tm (dfsch_object_t * time) [read]
Definition at line 109 of file system.c.
References dfsch_error(), and DFSCH_TYPE_OF.
Referenced by native_decode_universal_time(), native_get_decoded_time(), and native_iso_format_time().
{
  if (DFSCH_TYPE_OF(time) != &decoded_time_type){
    dfsch_error("exception:not-a-decoded-time", time);
  }
  return &(((decoded_time_t*)time)->tm);
}
DFSCH_DEFINE_PRIMITIVE (get_internal_run_time , NULL)
Definition at line 218 of file system.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  struct tms t;
  DFSCH_ARG_END(args);
  times(&t);
  return dfsch_make_number_from_long((t.tms_utime + t.tms_stime) & LONG_MAX);
}
DFSCH_DEFINE_PRIMITIVE (get_internal_real_time , NULL)
Definition at line 212 of file system.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
{
  struct tms t;
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(times(&t) & LONG_MAX);
}
dfsch_object_t* dfsch_make_decoded_time ()
Definition at line 105 of file system.c.
References dfsch_make_object().
Referenced by native_decode_universal_time(), and native_get_decoded_time().
{
  return dfsch_make_object(&decoded_time_type);
}
static dfsch_object_t* native_decode_universal_time (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 117 of file system.c.
References DFSCH_ARG_END, dfsch_decoded_time_get_tm(), DFSCH_LONG_ARG, dfsch_make_decoded_time(), and DFSCH_OBJECT_ARG_OPT.
Referenced by dfsch__system_register().
{
  time_t time;
  dfsch_object_t* utc;
  dfsch_object_t* ret;
  DFSCH_LONG_ARG(args, time);
  DFSCH_OBJECT_ARG_OPT(args, utc, NULL);
  DFSCH_ARG_END(args);
  ret = dfsch_make_decoded_time();
  if (utc){
    gmtime_r(&time, dfsch_decoded_time_get_tm(ret));
  } else {
    localtime_r(&time, dfsch_decoded_time_get_tm(ret));
  }
  return ret;
}
static dfsch_object_t* native_encode_universal_time (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 139 of file system.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG, and dfsch_make_number_from_long().
Referenced by dfsch__system_register().
{
  struct tm tm;
  DFSCH_LONG_ARG(args, tm.tm_sec);
  DFSCH_LONG_ARG(args, tm.tm_min);
  DFSCH_LONG_ARG(args, tm.tm_hour);
  DFSCH_LONG_ARG(args, tm.tm_mday);
  DFSCH_LONG_ARG(args, tm.tm_mon);
  DFSCH_LONG_ARG(args, tm.tm_year);
  DFSCH_ARG_END(args);
  tm.tm_mon -= 1;
  tm.tm_year -= 1900;
  return dfsch_make_number_from_long(mktime(&tm));
}
static dfsch_object_t* native_get_decoded_time (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 158 of file system.c.
References DFSCH_ARG_END, dfsch_decoded_time_get_tm(), dfsch_make_decoded_time(), and DFSCH_OBJECT_ARG_OPT.
Referenced by dfsch__system_register().
{
  time_t t;
  dfsch_object_t* utc;
  dfsch_object_t* ret;
  DFSCH_OBJECT_ARG_OPT(args, utc, NULL);
  DFSCH_ARG_END(args);
  ret = dfsch_make_decoded_time();
  t = time(NULL);
  if (utc){
    gmtime_r(&t, dfsch_decoded_time_get_tm(ret));
  } else {
    localtime_r(&t, dfsch_decoded_time_get_tm(ret));
  }
  return ret;
}
static dfsch_object_t* native_get_universal_time (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 181 of file system.c.
References DFSCH_ARG_END, and dfsch_make_number_from_long().
Referenced by dfsch__system_register().
{
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(time(NULL));
}
static dfsch_object_t* native_iso_format_time (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 189 of file system.c.
References DFSCH_ARG_END, dfsch_decoded_time_get_tm(), dfsch_make_string_cstr(), DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, and saprintf.
Referenced by dfsch__system_register().
{
  char t = ' ';
  dfsch_object_t* use_t;
  dfsch_object_t* time;
  struct tm* tm;
  DFSCH_OBJECT_ARG(args, time);
  DFSCH_OBJECT_ARG_OPT(args, use_t, NULL);
  DFSCH_ARG_END(args);
  if (use_t){
    t = 'T';
  }
  tm = dfsch_decoded_time_get_tm(time);
  return dfsch_make_string_cstr(saprintf("%04d-%02d-%02d%c%02d:%02d:%02d",
                                         tm->tm_year+1900, tm->tm_mon+1,
                                         tm->tm_mday, t,
                                         tm->tm_hour, tm->tm_min, tm->tm_sec));
}
Variable Documentation
dfsch_type_t decoded_time_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(decoded_time_t),
  "decoded-time",
  (dfsch_type_equal_p_t)decoded_time_equal_p,
  (dfsch_type_write_t)decoded_time_write,
  (dfsch_type_apply_t)decoded_time_apply,
  (dfsch_type_hash_t)decoded_time_hash
}
Definition at line 94 of file system.c.