dfsch: dfsch/lib/threads.h File Reference
dfsch/lib/threads.h File Reference
#include <dfsch/dfsch.h>
Functions
dfsch_object_t * dfsch_channel_create (size_t buffer)
dfsch_object_t * dfsch_channel_read (dfsch_object_t *channel)
void dfsch_channel_write (dfsch_object_t *channel, dfsch_object_t *object)
void dfsch_condition_broadcast (dfsch_object_t *condition)
dfsch_object_t * dfsch_condition_create ()
void dfsch_condition_signal (dfsch_object_t *condition)
void dfsch_condition_wait (dfsch_object_t *condition, dfsch_object_t *mutex)
dfsch_object_t * dfsch_module_threads_register (dfsch_object_t *ctx)
dfsch_object_t * dfsch_mutex_create ()
void dfsch_mutex_lock (dfsch_object_t *mutex)
int dfsch_mutex_trylock (dfsch_object_t *mutex)
void dfsch_mutex_unlock (dfsch_object_t *mutex)
dfsch_object_t * dfsch_thread_create (dfsch_object_t *function, dfsch_object_t *arguments)
void dfsch_thread_detach (dfsch_object_t *thread)
dfsch_object_t * dfsch_thread_join (dfsch_object_t *thread)
dfsch_object_t * dfsch_thread_self ()
Function Documentation
dfsch_object_t* dfsch_channel_create (size_t buffer)
Definition at line 313 of file threads.c.
References channel_t::buf, channel_t::buf_len, create_finalized_cvar, create_finalized_mutex, dfsch_make_object(), channel_t::mutex, channel_t::read, channel_t::readptr, channel_t::write, and channel_t::writeptr.
Referenced by native_channel_create().
{
  channel_t* ch = (channel_t*)dfsch_make_object(&channel_type);
  ch->read = create_finalized_cvar();
  ch->write = create_finalized_cvar();
  ch->mutex = create_finalized_mutex();
  ch->buf = GC_MALLOC(sizeof(dfsch_object_t*)*buffer);
  ch->buf_len = buffer;
  ch->readptr = 0;
  ch->writeptr = 0;
  return (dfsch_object_t*)ch;
}
dfsch_object_t* dfsch_channel_read (dfsch_object_t * channel)
Definition at line 328 of file threads.c.
References channel_t::buf, channel_t::buf_len, dfsch_error(), DFSCH_TYPE_OF, channel_t::mutex, channel_t::read, channel_t::readptr, channel_t::write, and channel_t::writeptr.
Referenced by native_channel_read().
{
  channel_t* ch;
  dfsch_object_t* ret;
  /*
   * pthread functions returning errors here probably means that something is
   * fundamentaly wrong, so we don't bother to check for them.
   */
  if (DFSCH_TYPE_OF(channel) != &channel_type)
    dfsch_error("thread:not-a-channel", channel);
  ch = (channel_t*) channel;
  pthread_mutex_lock(ch->mutex);
  while(ch->readptr == ch->writeptr){ // Buffer is empty
    pthread_cond_wait(ch->read, ch->mutex);
  }
  ret = ch->buf[ch->readptr];
  ch->buf[ch->readptr] = NULL;
  ch->readptr = (ch->readptr + 1) % ch->buf_len;
  pthread_mutex_unlock(ch->mutex);
  pthread_cond_signal(ch->write);
  return ret;
}
void dfsch_channel_write (dfsch_object_t * channel, dfsch_object_t * object)
Definition at line 358 of file threads.c.
References channel_t::buf, channel_t::buf_len, dfsch_error(), DFSCH_TYPE_OF, channel_t::mutex, channel_t::read, channel_t::readptr, channel_t::write, and channel_t::writeptr.
Referenced by native_channel_write().
{
  channel_t* ch;
  size_t new_writeptr;
  /*
   * pthread functions returning errors here probably means that something is
   * fundamentaly wrong, so we don't bother to check for them.
   */
  if (DFSCH_TYPE_OF(channel) != &channel_type)
    dfsch_error("thread:not-a-channel", channel);
  ch = (channel_t*) channel;
  pthread_mutex_lock(ch->mutex);
  new_writeptr = (ch->writeptr + 1) % ch->buf_len;
  while(ch->readptr == new_writeptr){ // Buffer is full
    pthread_cond_wait(ch->write, ch->mutex);
  }
  ch->buf[ch->writeptr] = object;
  ch->writeptr = new_writeptr;
  pthread_mutex_unlock(ch->mutex);
  pthread_cond_signal(ch->read);
}
void dfsch_condition_broadcast (dfsch_object_t * condition)
Definition at line 266 of file threads.c.
References condition_t::cond, dfsch_error(), dfsch_make_string_cstr(), and DFSCH_TYPE_OF.
Referenced by native_condition_broadcast().
{
  condition_t* c;
  int err;
  if (DFSCH_TYPE_OF(cond) != &condition_type)
    dfsch_error("thread:not-a-condition", cond);
  c = (condition_t*)cond;
  err = pthread_cond_broadcast(&(c->cond));
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
}
dfsch_object_t* dfsch_condition_create ()
Definition at line 219 of file threads.c.
References condition_t::cond, condition_finalizer(), and dfsch_make_object().
Referenced by native_condition_create().
{
  condition_t* cond = (condition_t*)dfsch_make_object(&condition_type);
  GC_REGISTER_FINALIZER(cond,
                        (GC_finalization_proc)condition_finalizer,
                        NULL, NULL, NULL);
  pthread_cond_init(&(cond->cond), NULL);
  return (dfsch_object_t*)cond;
}
void dfsch_condition_signal (dfsch_object_t * condition)
Definition at line 251 of file threads.c.
References condition_t::cond, dfsch_error(), dfsch_make_string_cstr(), and DFSCH_TYPE_OF.
Referenced by native_condition_signal().
{
  condition_t* c;
  int err;
  if (DFSCH_TYPE_OF(cond) != &condition_type)
    dfsch_error("thread:not-a-condition", cond);
  c = (condition_t*)cond;
  err = pthread_cond_signal(&(c->cond));
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
}
void dfsch_condition_wait (dfsch_object_t * condition, dfsch_object_t * mutex)
Definition at line 231 of file threads.c.
References condition_t::cond, dfsch_error(), dfsch_make_string_cstr(), DFSCH_TYPE_OF, and mutex_obj_t::mutex.
Referenced by native_condition_wait().
{
  condition_t* c;
  int err;
  mutex_obj_t* m;
  if (DFSCH_TYPE_OF(mutex) != &mutex_type)
    dfsch_error("thread:not-a-mutex", mutex);
  if (DFSCH_TYPE_OF(cond) != &condition_type)
    dfsch_error("thread:not-a-condition", cond);
  c = (condition_t*)cond;
  m = (mutex_obj_t*)mutex;
  err = pthread_cond_wait(&(c->cond), &(m->mutex));
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
}
dfsch_object_t* dfsch_module_threads_register (dfsch_object_t * ctx)
Definition at line 171 of file threads_mod.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_provide(), native_channel_create(), native_channel_read(), native_channel_write(), native_condition_broadcast(), native_condition_create(), native_condition_signal(), native_condition_wait(), native_mutex_create(), native_mutex_lock(), native_mutex_trylock(), native_mutex_unlock(), native_thread_create(), native_thread_detach(), native_thread_join(), and native_thread_self().
{
  dfsch_define_cstr(ctx, "thread:create",
                   dfsch_make_primitive(&native_thread_create,NULL));
  dfsch_define_cstr(ctx, "thread:join",
                   dfsch_make_primitive(&native_thread_join,NULL));
  dfsch_define_cstr(ctx, "thread:detach",
                   dfsch_make_primitive(&native_thread_detach,NULL));
  dfsch_define_cstr(ctx, "thread:self",
                   dfsch_make_primitive(&native_thread_self,NULL));
  dfsch_define_cstr(ctx, "mutex:create",
                   dfsch_make_primitive(&native_mutex_create,NULL));
  dfsch_define_cstr(ctx, "mutex:lock",
                   dfsch_make_primitive(&native_mutex_lock,NULL));
  dfsch_define_cstr(ctx, "mutex:trylock",
                   dfsch_make_primitive(&native_mutex_trylock,NULL));
  dfsch_define_cstr(ctx, "mutex:unlock",
                   dfsch_make_primitive(&native_mutex_unlock,NULL));
  dfsch_define_cstr(ctx, "condition:create",
                   dfsch_make_primitive(&native_condition_create,NULL));
  dfsch_define_cstr(ctx, "condition:wait",
                   dfsch_make_primitive(&native_condition_wait,NULL));
  dfsch_define_cstr(ctx, "condition:signal",
                   dfsch_make_primitive(&native_condition_signal,NULL));
  dfsch_define_cstr(ctx, "condition:broadcast",
                   dfsch_make_primitive(&native_condition_broadcast,NULL));
  dfsch_define_cstr(ctx, "channel:create",
                   dfsch_make_primitive(&native_channel_create,NULL));
  dfsch_define_cstr(ctx, "channel:read",
                   dfsch_make_primitive(&native_channel_read,NULL));
  dfsch_define_cstr(ctx, "channel:write",
                   dfsch_make_primitive(&native_channel_write,NULL));
  dfsch_provide(ctx, "threads");
  return NULL;
}
dfsch_object_t* dfsch_mutex_create ()
Definition at line 144 of file threads.c.
References dfsch_make_object(), mutex_obj_t::mutex, and mutex_finalizer().
Referenced by native_mutex_create().
{
  mutex_obj_t* mutex = (mutex_obj_t*)dfsch_make_object(&mutex_type);
  GC_REGISTER_FINALIZER(mutex,
                        (GC_finalization_proc)mutex_finalizer,
                        NULL, NULL, NULL);
  pthread_mutex_init(&(mutex->mutex), NULL);
  return (dfsch_object_t*)mutex;
}
void dfsch_mutex_lock (dfsch_object_t * mutex)
Definition at line 155 of file threads.c.
References dfsch_error(), dfsch_make_string_cstr(), DFSCH_TYPE_OF, and mutex_obj_t::mutex.
Referenced by native_mutex_lock().
{
  mutex_obj_t* m;
  int err;
  if (DFSCH_TYPE_OF(mutex) != &mutex_type)
    dfsch_error("thread:not-a-mutex", mutex);
  m = (mutex_obj_t*)mutex;
  err = pthread_mutex_lock(&(m->mutex));
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
}
int dfsch_mutex_trylock (dfsch_object_t * mutex)
Definition at line 169 of file threads.c.
References dfsch_error(), DFSCH_TYPE_OF, and mutex_obj_t::mutex.
Referenced by native_mutex_trylock().
{
  mutex_obj_t* m;
  if (DFSCH_TYPE_OF(mutex) != &mutex_type)
    dfsch_error("thread:not-a-mutex", mutex);
  m = (mutex_obj_t*)mutex;
  return (pthread_mutex_trylock(&(m->mutex)) == 0);
}
void dfsch_mutex_unlock (dfsch_object_t * mutex)
Definition at line 178 of file threads.c.
References dfsch_error(), dfsch_make_string_cstr(), DFSCH_TYPE_OF, and mutex_obj_t::mutex.
Referenced by native_mutex_unlock().
{
  mutex_obj_t* m;
  int err;
  if (DFSCH_TYPE_OF(mutex) != &mutex_type)
    dfsch_error("thread:not-a-mutex", mutex);
  m = (mutex_obj_t*)mutex;
  err = pthread_mutex_unlock(&(m->mutex));
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
}
dfsch_object_t* dfsch_thread_create (dfsch_object_t * function, dfsch_object_t * arguments)
Definition at line 57 of file threads.c.
References thread_args_t::args, dfsch_make_object(), thread_args_t::function, thread_obj_t::thread, and thread_function().
Referenced by native_thread_create().
{
  thread_obj_t* thread = (thread_obj_t*) dfsch_make_object(&thread_type);
  thread_args_t* args = GC_NEW(thread_args_t);
  args->function = function;
  args->args = arguments;
  pthread_create(&(thread->thread),
                 NULL,
                 (void*(*)(void*))thread_function,
                 args);
  return (dfsch_object_t*)thread;
}
void dfsch_thread_detach (dfsch_object_t * thread)
Definition at line 91 of file threads.c.
References dfsch_error(), dfsch_make_string_cstr(), DFSCH_TYPE_OF, and thread_obj_t::thread.
Referenced by native_thread_detach().
{
  thread_obj_t* t;
  int err;
  if (DFSCH_TYPE_OF(thread) != &thread_type)
    dfsch_error("thread:not-a-thread", thread);
  t = (thread_obj_t*)thread;
  err = pthread_detach(t->thread);
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
}
dfsch_object_t* dfsch_thread_join (dfsch_object_t * thread)
Definition at line 74 of file threads.c.
References dfsch_error(), dfsch_make_string_cstr(), DFSCH_TYPE_OF, and thread_obj_t::thread.
Referenced by native_thread_join().
{
  thread_obj_t* t;
  dfsch_object_t* ret;
  int err;
  if (DFSCH_TYPE_OF(thread) != &thread_type)
    dfsch_error("thread:not-a-thread", thread);
  t = (thread_obj_t*)thread;
  err = pthread_join(t->thread, (void*)&ret);
  if (err != 0){
    dfsch_error("thread:unix-error",dfsch_make_string_cstr(strerror(err)));
  }
  return ret;
}
dfsch_object_t* dfsch_thread_self ()
Definition at line 106 of file threads.c.
References dfsch_make_object(), and thread_obj_t::thread.
Referenced by native_thread_self().
{
  thread_obj_t* thread = (thread_obj_t*) dfsch_make_object(&thread_type);
  thread->thread = pthread_self();
  return (dfsch_object_t*)thread;
}