dfsch: lib/threads_mod.c File Reference
lib/threads_mod.c File Reference
#include "dfsch/lib/threads.h"
#include <dfsch/number.h>
#include "src/util.h"
#include <errno.h>
#include <string.h>
Functions
dfsch_object_t * dfsch_module_threads_register (dfsch_object_t *ctx)
static dfsch_object_t * native_channel_create (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_channel_read (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_channel_write (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_condition_broadcast (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_condition_create (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_condition_signal (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_condition_wait (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_mutex_create (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_mutex_lock (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_mutex_trylock (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_mutex_unlock (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_thread_create (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_thread_detach (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_thread_join (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_thread_self (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
Function Documentation
dfsch_object_t* dfsch_module_threads_register (dfsch_object_t * ctx)
Definition at line 171 of file threads_mod.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_provide(), native_channel_create(), native_channel_read(), native_channel_write(), native_condition_broadcast(), native_condition_create(), native_condition_signal(), native_condition_wait(), native_mutex_create(), native_mutex_lock(), native_mutex_trylock(), native_mutex_unlock(), native_thread_create(), native_thread_detach(), native_thread_join(), and native_thread_self().
{
  dfsch_define_cstr(ctx, "thread:create",
                   dfsch_make_primitive(&native_thread_create,NULL));
  dfsch_define_cstr(ctx, "thread:join",
                   dfsch_make_primitive(&native_thread_join,NULL));
  dfsch_define_cstr(ctx, "thread:detach",
                   dfsch_make_primitive(&native_thread_detach,NULL));
  dfsch_define_cstr(ctx, "thread:self",
                   dfsch_make_primitive(&native_thread_self,NULL));
  dfsch_define_cstr(ctx, "mutex:create",
                   dfsch_make_primitive(&native_mutex_create,NULL));
  dfsch_define_cstr(ctx, "mutex:lock",
                   dfsch_make_primitive(&native_mutex_lock,NULL));
  dfsch_define_cstr(ctx, "mutex:trylock",
                   dfsch_make_primitive(&native_mutex_trylock,NULL));
  dfsch_define_cstr(ctx, "mutex:unlock",
                   dfsch_make_primitive(&native_mutex_unlock,NULL));
  dfsch_define_cstr(ctx, "condition:create",
                   dfsch_make_primitive(&native_condition_create,NULL));
  dfsch_define_cstr(ctx, "condition:wait",
                   dfsch_make_primitive(&native_condition_wait,NULL));
  dfsch_define_cstr(ctx, "condition:signal",
                   dfsch_make_primitive(&native_condition_signal,NULL));
  dfsch_define_cstr(ctx, "condition:broadcast",
                   dfsch_make_primitive(&native_condition_broadcast,NULL));
  dfsch_define_cstr(ctx, "channel:create",
                   dfsch_make_primitive(&native_channel_create,NULL));
  dfsch_define_cstr(ctx, "channel:read",
                   dfsch_make_primitive(&native_channel_read,NULL));
  dfsch_define_cstr(ctx, "channel:write",
                   dfsch_make_primitive(&native_channel_write,NULL));
  dfsch_provide(ctx, "threads");
  return NULL;
}
static dfsch_object_t* native_channel_create (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 137 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_channel_create(), and DFSCH_LONG_ARG_OPT.
Referenced by dfsch_module_threads_register().
{
  size_t buffer;
  DFSCH_LONG_ARG_OPT(args, buffer, 16);
  DFSCH_ARG_END(args);
  return dfsch_channel_create(buffer);
}
static dfsch_object_t* native_channel_read (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 146 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_channel_read(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* channel;
  DFSCH_OBJECT_ARG(args, channel);
  DFSCH_ARG_END(args);
  return dfsch_channel_read(channel);
}
static dfsch_object_t* native_channel_write (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 155 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_channel_write(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* channel;
  dfsch_object_t* object;
  DFSCH_OBJECT_ARG(args, channel);
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_ARG_END(args);
  dfsch_channel_write(channel, object);
  return object;
}
static dfsch_object_t* native_condition_broadcast (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 126 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_condition_broadcast(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* cond;
  DFSCH_OBJECT_ARG(args, cond);
  DFSCH_ARG_END(args);
  dfsch_condition_broadcast(cond);
  return cond;
}
static dfsch_object_t* native_condition_create (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 97 of file threads_mod.c.
References DFSCH_ARG_END, and dfsch_condition_create().
Referenced by dfsch_module_threads_register().
{
  DFSCH_ARG_END(args);
  return dfsch_condition_create();
}
static dfsch_object_t* native_condition_signal (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 116 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_condition_signal(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* cond;
  DFSCH_OBJECT_ARG(args, cond);
  DFSCH_ARG_END(args);
  dfsch_condition_signal(cond);
  return cond;
}
static dfsch_object_t* native_condition_wait (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 104 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_condition_wait(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* cond;
  dfsch_object_t* mutex;
  DFSCH_OBJECT_ARG(args, cond);
  DFSCH_OBJECT_ARG(args, mutex);
  DFSCH_ARG_END(args);
  dfsch_condition_wait(cond, mutex);
  return cond;
}
static dfsch_object_t* native_mutex_create (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 65 of file threads_mod.c.
References DFSCH_ARG_END, and dfsch_mutex_create().
Referenced by dfsch_module_threads_register().
{
  DFSCH_ARG_END(args);
  return dfsch_mutex_create();
}
static dfsch_object_t* native_mutex_lock (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 71 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_mutex_lock(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* mutex;
  DFSCH_OBJECT_ARG(args, mutex);
  DFSCH_ARG_END(args);
  dfsch_mutex_lock(mutex);
  return mutex;
}
static dfsch_object_t* native_mutex_trylock (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 80 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_bool(), dfsch_mutex_trylock(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* mutex;
  DFSCH_OBJECT_ARG(args, mutex);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_mutex_trylock(mutex));
}
static dfsch_object_t* native_mutex_unlock (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 88 of file threads_mod.c.
References DFSCH_ARG_END, dfsch_mutex_unlock(), and DFSCH_OBJECT_ARG.
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* mutex;
  DFSCH_OBJECT_ARG(args, mutex);
  DFSCH_ARG_END(args);
  dfsch_mutex_unlock(mutex);
  return mutex;
}
static dfsch_object_t* native_thread_create (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 30 of file threads_mod.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, DFSCH_OBJECT_ARG_OPT, and dfsch_thread_create().
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* function;
  dfsch_object_t* arguments;
  DFSCH_OBJECT_ARG(args, function);
  DFSCH_OBJECT_ARG_OPT(args, arguments, NULL);
  DFSCH_ARG_END(args);
  return dfsch_thread_create(function, arguments);
}
static dfsch_object_t* native_thread_detach (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 49 of file threads_mod.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_thread_detach().
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* thread;
  DFSCH_OBJECT_ARG(args, thread);
  DFSCH_ARG_END(args);
  dfsch_thread_detach(thread);
  return thread;
}
static dfsch_object_t* native_thread_join (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 41 of file threads_mod.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_thread_join().
Referenced by dfsch_module_threads_register().
{
  dfsch_object_t* thread;
  DFSCH_OBJECT_ARG(args, thread);
  DFSCH_ARG_END(args);
  return dfsch_thread_join(thread);
}
static dfsch_object_t* native_thread_self (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 58 of file threads_mod.c.
References DFSCH_ARG_END, and dfsch_thread_self().
Referenced by dfsch_module_threads_register().
{
  DFSCH_ARG_END(args);
  return dfsch_thread_self();
}