dfsch: dfsch/lib/unix.h File Reference
dfsch/lib/unix.h File Reference
#include <dfsch/dfsch.h>
Functions
dfsch_object_t * dfsch_module_unix_register (dfsch_object_t *ctx)
void dfsch_unix_closedir (dfsch_object_t *dir_obj)
struct stat * dfsch_unix_get_stat (dfsch_object_t *stat)
dfsch_object_t * dfsch_unix_make_stat_struct ()
dfsch_object_t * dfsch_unix_opendir (char *name)
char * dfsch_unix_readdir (dfsch_object_t *dir_obj)
Function Documentation
dfsch_object_t* dfsch_module_unix_register (dfsch_object_t * ctx)
Definition at line 1128 of file unix.c.
References dfsch_define_cstr(), dfsch_make_primitive(), dfsch_provide(), native_access(), native_chdir(), native_chmod(), native_chown(), native_clock(), native_close(), native_closedir(), native_creat(), native_dup(), native_dup2(), native_exit(), native_fchdir(), native_fchmod(), native_fchown(), native_fork(), native_fstat(), native_getcwd(), native_getegid(), native_getenv(), native_geteuid(), native_getgid(), native_getpgid(), native_getpgrp(), native_getpid(), native_getppid(), native_getsid(), native_gettimeofday(), native_getuid(), native_isatty(), native_kill(), native_killpg(), native_link(), native_lseek(), native_lstat(), native_mkdir(), native_mkfifo(), native_mode(), native_nice(), native_open(), native_opendir(), native_pipe(), native_raise(), native_read(), native_readdir(), native_rename(), native_rmdir(), native_setegid(), native_seteuid(), native_setgid(), native_setpgid(), native_setpgrp(), native_setsid(), native_setuid(), native_sig(), native_sleep(), native_stat(), native_symlink(), native_sync(), native_unlink(), native_wait(), native_waitpid(), and native_write().
{
  dfsch_define_cstr(ctx, "unix:mode",
                    dfsch_make_primitive(native_mode, NULL));
  dfsch_define_cstr(ctx, "unix:sig",
                    dfsch_make_primitive(native_sig, NULL));
  dfsch_define_cstr(ctx, "unix:access",
                    dfsch_make_primitive(native_access, NULL));
  dfsch_define_cstr(ctx, "unix:chdir",
                    dfsch_make_primitive(native_chdir, NULL));
  dfsch_define_cstr(ctx, "unix:fchdir",
                    dfsch_make_primitive(native_fchdir, NULL));
  dfsch_define_cstr(ctx, "unix:chmod",
                    dfsch_make_primitive(native_chmod, NULL));
  dfsch_define_cstr(ctx, "unix:fchmod",
                    dfsch_make_primitive(native_fchmod, NULL));
  dfsch_define_cstr(ctx, "unix:chown",
                    dfsch_make_primitive(native_chown, NULL));
  dfsch_define_cstr(ctx, "unix:fchown",
                    dfsch_make_primitive(native_fchown, NULL));
  dfsch_define_cstr(ctx, "unix:clock",
                    dfsch_make_primitive(native_clock, NULL));
  dfsch_define_cstr(ctx, "unix:close",
                    dfsch_make_primitive(native_close, NULL));
  dfsch_define_cstr(ctx, "unix:closedir",
                    dfsch_make_primitive(native_closedir, NULL));
  dfsch_define_cstr(ctx, "unix:creat",
                    dfsch_make_primitive(native_creat, NULL));
  dfsch_define_cstr(ctx, "unix:dup",
                    dfsch_make_primitive(native_dup, NULL));
  dfsch_define_cstr(ctx, "unix:dup2",
                    dfsch_make_primitive(native_dup2, NULL));
  dfsch_define_cstr(ctx, "unix:exit",
                    dfsch_make_primitive(native_exit, NULL));
  dfsch_define_cstr(ctx, "unix:fork",
                    dfsch_make_primitive(native_fork, NULL));
  dfsch_define_cstr(ctx, "unix:fstat",
                    dfsch_make_primitive(native_fstat, NULL));
  dfsch_define_cstr(ctx, "unix:getcwd",
                    dfsch_make_primitive(native_getcwd, NULL));
  dfsch_define_cstr(ctx, "unix:getegid",
                    dfsch_make_primitive(native_getegid, NULL));
  dfsch_define_cstr(ctx, "unix:geteuid",
                    dfsch_make_primitive(native_geteuid, NULL));
  dfsch_define_cstr(ctx, "unix:getgid",
                    dfsch_make_primitive(native_getgid, NULL));
  dfsch_define_cstr(ctx, "unix:getuid",
                    dfsch_make_primitive(native_getuid, NULL));
  dfsch_define_cstr(ctx, "unix:getenv",
                    dfsch_make_primitive(native_getenv, NULL));
  dfsch_define_cstr(ctx, "unix:getpgid",
                    dfsch_make_primitive(native_getpgid, NULL));
  dfsch_define_cstr(ctx, "unix:getpgrp",
                    dfsch_make_primitive(native_getpgrp, NULL));
  dfsch_define_cstr(ctx, "unix:getsid",
                    dfsch_make_primitive(native_getsid, NULL));
  dfsch_define_cstr(ctx, "unix:getpid",
                    dfsch_make_primitive(native_getpid, NULL));
  dfsch_define_cstr(ctx, "unix:getppid",
                    dfsch_make_primitive(native_getppid, NULL));
  dfsch_define_cstr(ctx, "unix:gettimeofday",
                    dfsch_make_primitive(native_gettimeofday, NULL));
  dfsch_define_cstr(ctx, "unix:isatty",
                    dfsch_make_primitive(native_isatty, NULL));
  dfsch_define_cstr(ctx, "unix:kill",
                    dfsch_make_primitive(native_kill, NULL));
  dfsch_define_cstr(ctx, "unix:killpg",
                    dfsch_make_primitive(native_killpg, NULL));
  dfsch_define_cstr(ctx, "unix:link",
                    dfsch_make_primitive(native_link, NULL));
  dfsch_define_cstr(ctx, "unix:lseek",
                    dfsch_make_primitive(native_lseek, NULL));
  dfsch_define_cstr(ctx, "unix:lstat",
                    dfsch_make_primitive(native_lstat, NULL));
  dfsch_define_cstr(ctx, "unix:mkdir",
                    dfsch_make_primitive(native_mkdir, NULL));
  dfsch_define_cstr(ctx, "unix:mkfifo",
                    dfsch_make_primitive(native_mkfifo, NULL));
  dfsch_define_cstr(ctx, "unix:nice",
                    dfsch_make_primitive(native_nice, NULL));
  dfsch_define_cstr(ctx, "unix:open",
                    dfsch_make_primitive(native_open, NULL));
  dfsch_define_cstr(ctx, "unix:opendir",
                    dfsch_make_primitive(native_opendir, NULL));
  dfsch_define_cstr(ctx, "unix:pipe",
                    dfsch_make_primitive(native_pipe, NULL));
  dfsch_define_cstr(ctx, "unix:raise",
                    dfsch_make_primitive(native_raise, NULL));
  dfsch_define_cstr(ctx, "unix:read",
                    dfsch_make_primitive(native_read, NULL));
  dfsch_define_cstr(ctx, "unix:readdir",
                    dfsch_make_primitive(native_readdir, NULL));
  dfsch_define_cstr(ctx, "unix:rename",
                    dfsch_make_primitive(native_rename, NULL));
  dfsch_define_cstr(ctx, "unix:rmdir",
                    dfsch_make_primitive(native_rmdir, NULL));
  dfsch_define_cstr(ctx, "unix:setegid",
                    dfsch_make_primitive(native_setegid, NULL));
  dfsch_define_cstr(ctx, "unix:seteuid",
                    dfsch_make_primitive(native_seteuid, NULL));
  dfsch_define_cstr(ctx, "unix:setgid",
                    dfsch_make_primitive(native_setgid, NULL));
  dfsch_define_cstr(ctx, "unix:setuid",
                    dfsch_make_primitive(native_setuid, NULL));
  dfsch_define_cstr(ctx, "unix:setpgid",
                    dfsch_make_primitive(native_setpgid, NULL));
  dfsch_define_cstr(ctx, "unix:setpgrp",
                    dfsch_make_primitive(native_setpgrp, NULL));
  dfsch_define_cstr(ctx, "unix:setsid",
                    dfsch_make_primitive(native_setsid, NULL));
  dfsch_define_cstr(ctx, "unix:sleep",
                    dfsch_make_primitive(native_sleep, NULL));
  dfsch_define_cstr(ctx, "unix:stat",
                    dfsch_make_primitive(native_stat, NULL));
  dfsch_define_cstr(ctx, "unix:symlink",
                    dfsch_make_primitive(native_symlink, NULL));
  dfsch_define_cstr(ctx, "unix:sync",
                    dfsch_make_primitive(native_sync, NULL));
  dfsch_define_cstr(ctx, "unix:wait",
                    dfsch_make_primitive(native_wait, NULL));
  dfsch_define_cstr(ctx, "unix:waitpid",
                    dfsch_make_primitive(native_waitpid, NULL));
  dfsch_define_cstr(ctx, "unix:write",
                    dfsch_make_primitive(native_write, NULL));
  dfsch_define_cstr(ctx, "unix:unlink",
                    dfsch_make_primitive(native_unlink, NULL));
  dfsch_provide(ctx, "unix");
  return NULL;
}
void dfsch_unix_closedir (dfsch_object_t * dir_obj)
Definition at line 84 of file unix.c.
References dfsch_error(), DFSCH_TYPE_OF, dir_t::dir, and dir_t::open.
Referenced by native_closedir().
{
  dir_t* dir;
  if (DFSCH_TYPE_OF(dir_obj) != &dir_type){
    dfsch_error("unix:not-a-directory", dir_obj);
  }
  dir = (dir_t*)dir_obj;
  if (dir->open){
    closedir(dir->dir);
    dir->open = 0;
  }
}
struct stat* dfsch_unix_get_stat (dfsch_object_t * stat) [read]
Definition at line 211 of file unix.c.
References dfsch_error(), and DFSCH_TYPE_OF.
Referenced by native_fstat(), native_lstat(), and native_stat().
{
  if (DFSCH_TYPE_OF(stat) != &stat_type){
    dfsch_error("unix:not-a-stat-struct", stat);
  }
  return &(((stat_t*)stat)->st);
}
dfsch_object_t* dfsch_unix_make_stat_struct ()
Definition at line 207 of file unix.c.
References dfsch_make_object().
Referenced by native_fstat(), native_lstat(), and native_stat().
{
  return dfsch_make_object(&stat_type);
}
dfsch_object_t* dfsch_unix_opendir (char * name)
Definition at line 71 of file unix.c.
References dfsch_make_object(), dfsch_operating_system_error(), dir_t::dir, dir_finalizer(), and dir_t::open.
Referenced by native_opendir().
{
  dir_t* dir = (dir_t*)dfsch_make_object(&dir_type);
  dir->dir = opendir(name);
  if (!dir->dir){
    dfsch_operating_system_error("opendir");
  }
  dir->open = 1;
  GC_REGISTER_FINALIZER(dir, (GC_finalization_proc)dir_finalizer,
                        NULL, NULL, NULL);
  return (dfsch_object_t*) dir;
}
char* dfsch_unix_readdir (dfsch_object_t * dir_obj)
Definition at line 97 of file unix.c.
References dfsch_error(), dfsch_operating_system_error(), DFSCH_TYPE_OF, dir_t::dir, and dir_t::open.
Referenced by native_readdir().
{
  dir_t* dir;
  struct dirent* dent;
  if (DFSCH_TYPE_OF(dir_obj) != &dir_type){
    dfsch_error("unix:not-a-directory", dir_obj);
  }
  dir = (dir_t*)dir_obj;
  if (!dir->open){
    dfsch_error("unix:directory-object-is-closed", dir_obj);
  }
  errno = 0;
  dent = readdir(dir->dir);
  if (!dent){
    if (errno != 0){
      dfsch_operating_system_error("readdir");
    } else {
      return NULL;
    }
  }
  return dent->d_name;
}