dfsch: dfsch/weak.h File Reference
dfsch/weak.h File Reference
#include <dfsch/dfsch.h>
#include <dfsch/hash.h>
Defines
#define DFSCH_WEAK_KEY_HASH_TYPE ((dfsch_type_t*)&dfsch_weak_key_hash_type)
#define DFSCH_WEAK_REFERENCE_TYPE (&dfsch_weak_reference_type)
#define DFSCH_WEAK_VECTOR_TYPE (&dfsch_weak_vector_type)
Functions
dfsch_object_t * dfsch_make_weak_reference (dfsch_object_t *refered)
dfsch_object_t * dfsch_make_weak_vector (size_t length, dfsch_object_t *fill)
dfsch_object_t * dfsch_weak_reference_dereference (dfsch_object_t *reference)
int dfsch_weak_reference_live_p (dfsch_object_t *reference)
dfsch_object_t ** dfsch_weak_vector_as_array (dfsch_object_t *vector, size_t *length)
dfsch_object_t * dfsch_weak_vector_from_array (dfsch_object_t **array, size_t length)
size_t dfsch_weak_vector_length (dfsch_object_t *vector)
dfsch_object_t * dfsch_weak_vector_ref (dfsch_object_t *vector, size_t k)
dfsch_object_t * dfsch_weak_vector_set (dfsch_object_t *vector, size_t k, dfsch_object_t *obj)
Variables
dfsch_custom_hash_type_t dfsch_weak_key_hash_type
dfsch_type_t dfsch_weak_reference_type
dfsch_type_t dfsch_weak_vector_type
Define Documentation
#define DFSCH_WEAK_KEY_HASH_TYPE ((dfsch_type_t*)&dfsch_weak_key_hash_type)
Definition at line 56 of file weak.h.
Referenced by dfsch__weak_native_register(), and dfsch_make_weak_key_hash().
#define DFSCH_WEAK_REFERENCE_TYPE (&dfsch_weak_reference_type)
Definition at line 52 of file weak.h.
Referenced by dfsch__weak_native_register(), dfsch_make_weak_reference(), dfsch_weak_reference_dereference(), and dfsch_weak_reference_live_p().
#define DFSCH_WEAK_VECTOR_TYPE (&dfsch_weak_vector_type)
Definition at line 54 of file weak.h.
Referenced by dfsch__weak_native_register(), dfsch_make_weak_vector(), dfsch_weak_vector_2_list(), dfsch_weak_vector_as_array(), dfsch_weak_vector_from_array(), dfsch_weak_vector_length(), dfsch_weak_vector_ref(), and dfsch_weak_vector_set().
Function Documentation
dfsch_object_t* dfsch_make_weak_reference (dfsch_object_t * refered)
Definition at line 64 of file weak.c.
References DFSCH_WEAK_REFERENCE_TYPE, reference_t::live, reference_t::object, register_weak_pointer(), and reference_t::type.
Referenced by native_make_weak_reference().
{
  reference_t* ref = (reference_t*)GC_MALLOC_ATOMIC(sizeof(reference_t));
  ref->type = DFSCH_WEAK_REFERENCE_TYPE;
  ref->object = refered;
  ref->live = 1;
  register_weak_pointer((void**)&ref->live, refered);
  return (dfsch_object_t*)ref;
}
dfsch_object_t* dfsch_make_weak_vector (size_t length, dfsch_object_t * fill)
Definition at line 122 of file weak.c.
References weak_vector_t::data, dfsch_make_object(), DFSCH_WEAK_VECTOR_TYPE, weak_vector_t::length, register_weak_pointer(), and weak_vector_t::set.
Referenced by native_make_weak_vector().
{
  weak_vector_t* v = (weak_vector_t*)dfsch_make_object(DFSCH_WEAK_VECTOR_TYPE);
  size_t i;
  v->length = length;
  v->set = 0;
  v->data = GC_MALLOC_ATOMIC(sizeof(dfsch_object_t*) * length);
  for(i = 0; i<length; ++i){
    v->data[i] = fill;
    v->set = register_weak_pointer((void**)&v->data[i], fill);
  }
  return (dfsch_object_t*)v;
}
dfsch_object_t* dfsch_weak_reference_dereference (dfsch_object_t * reference)
Definition at line 94 of file weak.c.
References dereference(), dfsch_error(), DFSCH_TYPE_OF, and DFSCH_WEAK_REFERENCE_TYPE.
Referenced by native_weak_reference_dereference().
{
  reference_t* ref;
  if (DFSCH_TYPE_OF(reference) != DFSCH_WEAK_REFERENCE_TYPE)
    dfsch_error("exception:not-a-reference", reference);
  ref = (reference_t*) reference;
  return GC_call_with_alloc_lock((GC_fn_type)dereference, ref);
}
int dfsch_weak_reference_live_p (dfsch_object_t * reference)
Definition at line 76 of file weak.c.
References dfsch_error(), DFSCH_TYPE_OF, DFSCH_WEAK_REFERENCE_TYPE, and reference_t::live.
Referenced by native_weak_reference_live_p().
{
  reference_t* ref;
  if (DFSCH_TYPE_OF(reference) != DFSCH_WEAK_REFERENCE_TYPE)
    dfsch_error("exception:not-a-reference", reference);
  ref = (reference_t*) reference;
  return ref->live;
}
dfsch_object_t** dfsch_weak_vector_as_array (dfsch_object_t * vector, size_t * length)
Definition at line 144 of file weak.c.
References dfsch_error(), DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
{
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-weak-vector",vector);
  if (length){
    *length = ((weak_vector_t*)vector)->length;
  }
  return ((weak_vector_t*)vector)->data;
}
dfsch_object_t* dfsch_weak_vector_from_array (dfsch_object_t ** array, size_t length)
Definition at line 156 of file weak.c.
References weak_vector_t::data, dfsch_make_object(), DFSCH_WEAK_VECTOR_TYPE, weak_vector_t::length, and register_weak_pointer().
Referenced by dfsch_list_2_weak_vector().
{
  weak_vector_t* v = (weak_vector_t*)dfsch_make_object(DFSCH_WEAK_VECTOR_TYPE);
  size_t i;
  v->length = length;
  v->data = GC_MALLOC_ATOMIC(sizeof(dfsch_object_t*) * length);
  for(i = 0; i<length; ++i){
    v->data[i] = array[i];
    register_weak_pointer((void**)&v->data[i], array[i]);
  }
  return (dfsch_object_t*)v;
}
size_t dfsch_weak_vector_length (dfsch_object_t * vector)
Definition at line 137 of file weak.c.
References DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
Referenced by native_weak_vector_length().
{
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    return 0;
  return ((weak_vector_t*)vector)->length;
}
dfsch_object_t* dfsch_weak_vector_ref (dfsch_object_t * vector, size_t k)
Definition at line 173 of file weak.c.
References weak_vector_t::data, dfsch_error(), DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
Referenced by native_weak_vector_ref().
{
  weak_vector_t* v;
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-weak-vector",vector);
  return v->data[k];
}
dfsch_object_t* dfsch_weak_vector_set (dfsch_object_t * vector, size_t k, dfsch_object_t * obj)
Definition at line 182 of file weak.c.
References weak_vector_t::data, dfsch_error(), dfsch_make_number_from_long(), DFSCH_TYPE_OF, DFSCH_WEAK_VECTOR_TYPE, weak_vector_t::length, register_weak_pointer(), and weak_vector_t::set.
Referenced by native_weak_vector_set().
{
  weak_vector_t* v;
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-weak-vector",vector);
  v = (weak_vector_t*) vector;
  if (v->length <= k){
    dfsch_error("exception:invalid-index",dfsch_make_number_from_long(k));
  }
  if (v->set){
    GC_unregister_disappearing_link((void**)&v->data[k]);
  }
  v->data[k] = obj;
  v->set = register_weak_pointer((void**)&v->data[k], obj);
  return vector;
}
Variable Documentation
dfsch_custom_hash_type_t dfsch_weak_key_hash_type
Definition at line 384 of file weak.c.
dfsch_type_t dfsch_weak_reference_type
Definition at line 44 of file weak.c.
dfsch_type_t dfsch_weak_vector_type
Definition at line 111 of file weak.c.