dfsch: src/weak.c File Reference
src/weak.c File Reference
#include "dfsch/weak.h"
#include <dfsch/number.h>
#include "internal.h"
#include "util.h"
#include <gc/gc.h>
#include <stdlib.h>
Data Structures
struct reference_t
struct weak_hash_entry_t
struct weak_key_hash_t
struct weak_vector_t
Defines
#define DEFAULT_WEAK_KEY_HASH_SIZE 128
#define HIDE_OBJECT(o) ((dfsch_object_t*) ~((size_t) (o)))
#define REVEAL_OBJECT(o) HIDE_OBJECT(o)
Typedefs
typedef struct weak_hash_entry_t weak_hash_entry_t
Functions
dfsch_object_t * dereference (reference_t *ref)
void dfsch__weak_native_register (dfsch_object_t *ctx)
DFSCH_DEFINE_PRIMITIVE (make_weak_key_hash, 0)
dfsch_object_t * dfsch_list_2_weak_vector (dfsch_object_t *list)
dfsch_object_t * dfsch_make_weak_key_hash ()
dfsch_object_t * dfsch_make_weak_reference (dfsch_object_t *refered)
dfsch_object_t * dfsch_make_weak_vector (size_t length, dfsch_object_t *fill)
dfsch_object_t * dfsch_weak_reference_dereference (dfsch_object_t *reference)
int dfsch_weak_reference_live_p (dfsch_object_t *reference)
dfsch_object_t * dfsch_weak_vector_2_list (dfsch_object_t *vector)
dfsch_object_t ** dfsch_weak_vector_as_array (dfsch_object_t *vector, size_t *length)
dfsch_object_t * dfsch_weak_vector_from_array (dfsch_object_t **array, size_t length)
size_t dfsch_weak_vector_length (dfsch_object_t *vector)
dfsch_object_t * dfsch_weak_vector_ref (dfsch_object_t *vector, size_t k)
dfsch_object_t * dfsch_weak_vector_set (dfsch_object_t *vector, size_t k, dfsch_object_t *obj)
static weak_hash_entry_t * find_entry (weak_hash_entry_t **head, dfsch_object_t *key, size_t *count)
static dfsch_object_t * native_list_2_weak_vector (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_make_weak_reference (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_make_weak_vector (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_reference_dereference (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_reference_live_p (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_vector (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_vector_2_list (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_vector_length (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_vector_ref (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_weak_vector_set (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static size_t ptr_hash (dfsch_object_t *ptr)
static int register_weak_pointer (void **pointer, void *object)
static weak_hash_entry_t * weak_hash_entry_create (dfsch_object_t *key, dfsch_object_t *value, weak_hash_entry_t *next)
static weak_hash_entry_t * weak_key_entry_create (dfsch_object_t *key, dfsch_object_t *value, weak_hash_entry_t *next)
static int weak_key_hash_ref (weak_key_hash_t *h, dfsch_object_t *key, dfsch_object_t **res)
static void weak_key_hash_set (weak_key_hash_t *h, dfsch_object_t *key, dfsch_object_t *value)
Variables
dfsch_custom_hash_type_t dfsch_weak_key_hash_type
dfsch_type_t dfsch_weak_reference_type
dfsch_type_t dfsch_weak_vector_type
Define Documentation
#define DEFAULT_WEAK_KEY_HASH_SIZE 128
Definition at line 298 of file weak.c.
Referenced by dfsch_make_weak_key_hash().
#define HIDE_OBJECT (o) ((dfsch_object_t*) ~((size_t) (o)))
Definition at line 225 of file weak.c.
Referenced by weak_key_entry_create(), weak_key_hash_ref(), and weak_key_hash_set().
#define REVEAL_OBJECT (o) HIDE_OBJECT(o)
Definition at line 226 of file weak.c.
Typedef Documentation
typedef struct weak_hash_entry_t weak_hash_entry_t
Definition at line 228 of file weak.c.
Function Documentation
dfsch_object_t* dereference (reference_t * ref)
Definition at line 85 of file weak.c.
References reference_t::live, and reference_t::object.
Referenced by dfsch_weak_reference_dereference().
{
  if (!ref->live){
    ref->object = NULL;
    return NULL;
  } else {
    return ref->object;
  }
}
void dfsch__weak_native_register (dfsch_object_t * ctx)
Definition at line 530 of file weak.c.
References dfsch_define_cstr(), dfsch_make_primitive(), DFSCH_PRIMITIVE_REF, DFSCH_WEAK_KEY_HASH_TYPE, DFSCH_WEAK_REFERENCE_TYPE, DFSCH_WEAK_VECTOR_TYPE, native_list_2_weak_vector(), native_make_weak_reference(), native_make_weak_vector(), native_weak_reference_dereference(), native_weak_reference_live_p(), native_weak_vector(), native_weak_vector_2_list(), native_weak_vector_length(), native_weak_vector_ref(), and native_weak_vector_set().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<weak-reference>", DFSCH_WEAK_REFERENCE_TYPE);
  dfsch_define_cstr(ctx, "<weak-vector>", DFSCH_WEAK_VECTOR_TYPE);
  dfsch_define_cstr(ctx, "<weak-key-hash>", DFSCH_WEAK_KEY_HASH_TYPE);
  dfsch_define_cstr(ctx, "make-weak-reference",
                    dfsch_make_primitive(&native_make_weak_reference,NULL));
  dfsch_define_cstr(ctx, "weak-reference-live?",
                    dfsch_make_primitive(&native_weak_reference_live_p,NULL));
  dfsch_define_cstr(ctx, "weak-reference-dereference",
                    dfsch_make_primitive(&native_weak_reference_dereference,
                                         NULL));
  dfsch_define_cstr(ctx, "make-weak-vector",
                   dfsch_make_primitive(&native_make_weak_vector,NULL));
  dfsch_define_cstr(ctx, "weak-vector",
                   dfsch_make_primitive(&native_weak_vector,NULL));
  dfsch_define_cstr(ctx, "weak-vector-length",
                   dfsch_make_primitive(&native_weak_vector_length,NULL));
  dfsch_define_cstr(ctx, "weak-vector-set!",
                   dfsch_make_primitive(&native_weak_vector_set,NULL));
  dfsch_define_cstr(ctx, "weak-vector-ref",
                   dfsch_make_primitive(&native_weak_vector_ref,NULL));
  dfsch_define_cstr(ctx, "weak-vector->list",
                   dfsch_make_primitive(&native_weak_vector_2_list,NULL));
  dfsch_define_cstr(ctx, "list->weak-vector",
                   dfsch_make_primitive(&native_list_2_weak_vector,NULL));
  dfsch_define_cstr(ctx, "make-weak-key-hash",
                    DFSCH_PRIMITIVE_REF(make_weak_key_hash));
}
DFSCH_DEFINE_PRIMITIVE (make_weak_key_hash , 0)
Definition at line 522 of file weak.c.
References DFSCH_ARG_END, and dfsch_make_weak_key_hash().
{
  DFSCH_ARG_END(args);
  return dfsch_make_weak_key_hash();
}
dfsch_object_t* dfsch_list_2_weak_vector (dfsch_object_t * list)
Definition at line 214 of file weak.c.
References dfsch_list_as_array(), and dfsch_weak_vector_from_array().
Referenced by native_list_2_weak_vector(), and native_weak_vector().
{
  dfsch_object_t** data;
  size_t length;
  data = dfsch_list_as_array(list, &length);
  return dfsch_weak_vector_from_array(data, length);
}
dfsch_object_t* dfsch_make_weak_key_hash ()
Definition at line 300 of file weak.c.
References weak_key_hash_t::buckets, weak_key_hash_t::count, DEFAULT_WEAK_KEY_HASH_SIZE, DFSCH_CREATE_RWLOCK, dfsch_make_object(), DFSCH_WEAK_KEY_HASH_TYPE, weak_key_hash_t::lock, and weak_key_hash_t::mask.
Referenced by DFSCH_DEFINE_PRIMITIVE().
{
  weak_key_hash_t* h = dfsch_make_object(DFSCH_WEAK_KEY_HASH_TYPE);
  h->mask = DEFAULT_WEAK_KEY_HASH_SIZE - 1;
  h->buckets = GC_MALLOC(DEFAULT_WEAK_KEY_HASH_SIZE*sizeof(weak_hash_entry_t*));
  h->count = 0;
  h->lock = DFSCH_CREATE_RWLOCK();
  return (dfsch_object_t*)h;
}
dfsch_object_t* dfsch_make_weak_reference (dfsch_object_t * refered)
Definition at line 64 of file weak.c.
References DFSCH_WEAK_REFERENCE_TYPE, reference_t::live, reference_t::object, register_weak_pointer(), and reference_t::type.
Referenced by native_make_weak_reference().
{
  reference_t* ref = (reference_t*)GC_MALLOC_ATOMIC(sizeof(reference_t));
  ref->type = DFSCH_WEAK_REFERENCE_TYPE;
  ref->object = refered;
  ref->live = 1;
  register_weak_pointer((void**)&ref->live, refered);
  return (dfsch_object_t*)ref;
}
dfsch_object_t* dfsch_make_weak_vector (size_t length, dfsch_object_t * fill)
Definition at line 122 of file weak.c.
References weak_vector_t::data, dfsch_make_object(), DFSCH_WEAK_VECTOR_TYPE, weak_vector_t::length, register_weak_pointer(), and weak_vector_t::set.
Referenced by native_make_weak_vector().
{
  weak_vector_t* v = (weak_vector_t*)dfsch_make_object(DFSCH_WEAK_VECTOR_TYPE);
  size_t i;
  v->length = length;
  v->set = 0;
  v->data = GC_MALLOC_ATOMIC(sizeof(dfsch_object_t*) * length);
  for(i = 0; i<length; ++i){
    v->data[i] = fill;
    v->set = register_weak_pointer((void**)&v->data[i], fill);
  }
  return (dfsch_object_t*)v;
}
dfsch_object_t* dfsch_weak_reference_dereference (dfsch_object_t * reference)
Definition at line 94 of file weak.c.
References dereference(), dfsch_error(), DFSCH_TYPE_OF, and DFSCH_WEAK_REFERENCE_TYPE.
Referenced by native_weak_reference_dereference().
{
  reference_t* ref;
  if (DFSCH_TYPE_OF(reference) != DFSCH_WEAK_REFERENCE_TYPE)
    dfsch_error("exception:not-a-reference", reference);
  ref = (reference_t*) reference;
  return GC_call_with_alloc_lock((GC_fn_type)dereference, ref);
}
int dfsch_weak_reference_live_p (dfsch_object_t * reference)
Definition at line 76 of file weak.c.
References dfsch_error(), DFSCH_TYPE_OF, DFSCH_WEAK_REFERENCE_TYPE, and reference_t::live.
Referenced by native_weak_reference_live_p().
{
  reference_t* ref;
  if (DFSCH_TYPE_OF(reference) != DFSCH_WEAK_REFERENCE_TYPE)
    dfsch_error("exception:not-a-reference", reference);
  ref = (reference_t*) reference;
  return ref->live;
}
dfsch_object_t* dfsch_weak_vector_2_list (dfsch_object_t * vector)
Definition at line 205 of file weak.c.
References dfsch_error(), dfsch_list_from_array(), DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
Referenced by native_weak_vector_2_list().
{
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-vector",vector);
  return dfsch_list_from_array(((weak_vector_t*)vector)->data,
                               ((weak_vector_t*)vector)->length);
}
dfsch_object_t** dfsch_weak_vector_as_array (dfsch_object_t * vector, size_t * length)
Definition at line 144 of file weak.c.
References dfsch_error(), DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
{
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-weak-vector",vector);
  if (length){
    *length = ((weak_vector_t*)vector)->length;
  }
  return ((weak_vector_t*)vector)->data;
}
dfsch_object_t* dfsch_weak_vector_from_array (dfsch_object_t ** array, size_t length)
Definition at line 156 of file weak.c.
References weak_vector_t::data, dfsch_make_object(), DFSCH_WEAK_VECTOR_TYPE, weak_vector_t::length, and register_weak_pointer().
Referenced by dfsch_list_2_weak_vector().
{
  weak_vector_t* v = (weak_vector_t*)dfsch_make_object(DFSCH_WEAK_VECTOR_TYPE);
  size_t i;
  v->length = length;
  v->data = GC_MALLOC_ATOMIC(sizeof(dfsch_object_t*) * length);
  for(i = 0; i<length; ++i){
    v->data[i] = array[i];
    register_weak_pointer((void**)&v->data[i], array[i]);
  }
  return (dfsch_object_t*)v;
}
size_t dfsch_weak_vector_length (dfsch_object_t * vector)
Definition at line 137 of file weak.c.
References DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
Referenced by native_weak_vector_length().
{
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    return 0;
  return ((weak_vector_t*)vector)->length;
}
dfsch_object_t* dfsch_weak_vector_ref (dfsch_object_t * vector, size_t k)
Definition at line 173 of file weak.c.
References weak_vector_t::data, dfsch_error(), DFSCH_TYPE_OF, and DFSCH_WEAK_VECTOR_TYPE.
Referenced by native_weak_vector_ref().
{
  weak_vector_t* v;
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-weak-vector",vector);
  return v->data[k];
}
dfsch_object_t* dfsch_weak_vector_set (dfsch_object_t * vector, size_t k, dfsch_object_t * obj)
Definition at line 182 of file weak.c.
References weak_vector_t::data, dfsch_error(), dfsch_make_number_from_long(), DFSCH_TYPE_OF, DFSCH_WEAK_VECTOR_TYPE, weak_vector_t::length, register_weak_pointer(), and weak_vector_t::set.
Referenced by native_weak_vector_set().
{
  weak_vector_t* v;
  if (DFSCH_TYPE_OF(vector) != DFSCH_WEAK_VECTOR_TYPE)
    dfsch_error("exception:not-a-weak-vector",vector);
  v = (weak_vector_t*) vector;
  if (v->length <= k){
    dfsch_error("exception:invalid-index",dfsch_make_number_from_long(k));
  }
  if (v->set){
    GC_unregister_disappearing_link((void**)&v->data[k]);
  }
  v->data[k] = obj;
  v->set = register_weak_pointer((void**)&v->data[k], obj);
  return vector;
}
static weak_hash_entry_t* find_entry (weak_hash_entry_t ** head, dfsch_object_t * key, size_t * count) [static]
Definition at line 249 of file weak.c.
References weak_hash_entry_t::key, weak_hash_entry_t::live, and weak_hash_entry_t::next.
Referenced by weak_key_hash_ref(), and weak_key_hash_set().
{
  weak_hash_entry_t* tmp;
  weak_hash_entry_t* i;
  weak_hash_entry_t* res = NULL;
  i = *head;
  while (i && !i->live){
    i = i->next;
    *head = i;
    (*count)--;
  }
  if (!i){
    return NULL;
  }
  if (i->key == key){
    res = i;
  }
  tmp = i;
  i = i->next;
  while (i){
    if (!i->live){
      tmp->next = i->next;
      i = i->next;
      (*count)--;
      continue;
    }
    if (i->key == key){
      res = i;
    }
    i = i->next;
  }
  return res;
}
static dfsch_object_t* native_list_2_weak_vector (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 509 of file weak.c.
References DFSCH_ARG_END, dfsch_list_2_weak_vector(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* list;
  DFSCH_OBJECT_ARG(args, list);
  DFSCH_ARG_END(args);
  return dfsch_list_2_weak_vector(list);
}
static dfsch_object_t* native_make_weak_reference (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 406 of file weak.c.
References DFSCH_ARG_END, dfsch_make_weak_reference(), and DFSCH_OBJECT_ARG.
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* object;
  DFSCH_OBJECT_ARG(args, object);
  DFSCH_ARG_END(args);
  return dfsch_make_weak_reference(object);
}
static dfsch_object_t* native_make_weak_vector (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 441 of file weak.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG, dfsch_make_weak_vector(), and DFSCH_OBJECT_ARG_OPT.
Referenced by dfsch__weak_native_register().
{
  size_t length;
  dfsch_object_t* fill;
  DFSCH_LONG_ARG(args, length);
  DFSCH_OBJECT_ARG_OPT(args, fill, NULL);
  DFSCH_ARG_END(args);
  return dfsch_make_weak_vector(length,fill);
}
static dfsch_object_t* native_weak_reference_dereference (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 426 of file weak.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_weak_reference_dereference().
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* reference;
  DFSCH_OBJECT_ARG(args, reference);
  DFSCH_ARG_END(args);
  return dfsch_weak_reference_dereference(reference);
}
static dfsch_object_t* native_weak_reference_live_p (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 416 of file weak.c.
References DFSCH_ARG_END, dfsch_bool(), DFSCH_OBJECT_ARG, and dfsch_weak_reference_live_p().
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* reference;
  DFSCH_OBJECT_ARG(args, reference);
  DFSCH_ARG_END(args);
  return dfsch_bool(dfsch_weak_reference_live_p(reference));
}
static dfsch_object_t* native_weak_vector (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 454 of file weak.c.
References dfsch_list_2_weak_vector().
Referenced by dfsch__weak_native_register().
{
  return dfsch_list_2_weak_vector(args);
}
static dfsch_object_t* native_weak_vector_2_list (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 498 of file weak.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG, and dfsch_weak_vector_2_list().
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* vector;
  DFSCH_OBJECT_ARG(args, vector);
  DFSCH_ARG_END(args);
  return dfsch_weak_vector_2_list(vector);
}
static dfsch_object_t* native_weak_vector_length (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 459 of file weak.c.
References DFSCH_ARG_END, dfsch_make_number_from_long(), DFSCH_OBJECT_ARG, and dfsch_weak_vector_length().
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* vector;
  DFSCH_OBJECT_ARG(args,vector);
  DFSCH_ARG_END(args);
  return dfsch_make_number_from_long(dfsch_weak_vector_length(vector));
}
static dfsch_object_t* native_weak_vector_ref (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 470 of file weak.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG, DFSCH_OBJECT_ARG, and dfsch_weak_vector_ref().
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* vector;
  size_t k;
  DFSCH_OBJECT_ARG(args, vector);
  DFSCH_LONG_ARG(args, k);
  DFSCH_ARG_END(args);
  return dfsch_weak_vector_ref(vector, k);
}
static dfsch_object_t* native_weak_vector_set (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 483 of file weak.c.
References DFSCH_ARG_END, DFSCH_LONG_ARG, DFSCH_OBJECT_ARG, and dfsch_weak_vector_set().
Referenced by dfsch__weak_native_register().
{
  dfsch_object_t* vector;
  size_t k;
  dfsch_object_t* obj;
  DFSCH_OBJECT_ARG(args, vector);
  DFSCH_LONG_ARG(args, k);
  DFSCH_OBJECT_ARG(args, obj);
  DFSCH_ARG_END(args);
  return dfsch_weak_vector_set(vector, k, obj);
}
static size_t ptr_hash (dfsch_object_t * ptr) [static]
Definition at line 318 of file weak.c.
Referenced by weak_key_hash_ref(), and weak_key_hash_set().
{
  size_t a = (size_t)ptr;
  size_t b = (size_t)ptr >> 16 | (size_t)ptr << 16;
  a ^= b >> 2;
  b ^= a >> 3;
  a ^= b << 5;
  b ^= a << 7;
  a ^= b >> 11;
  b ^= a >> 13;
  a ^= b << 17;
  b ^= a << 23;
  return b ^ a;
}
static int register_weak_pointer (void ** pointer, void * object) [static]
Definition at line 54 of file weak.c.
Referenced by dfsch_make_weak_reference(), dfsch_make_weak_vector(), dfsch_weak_vector_from_array(), dfsch_weak_vector_set(), and weak_key_entry_create().
{
  if (object && GC_base(object)){
    /* Causes random crashes with non GC'able objects*/
    GC_general_register_disappearing_link(pointer, object);
    return 1;
  }
  return 0;
}
static weak_hash_entry_t* weak_hash_entry_create (dfsch_object_t * key, dfsch_object_t * value, weak_hash_entry_t * next) [static]
Definition at line 237 of file weak.c.
References weak_hash_entry_t::key, weak_hash_entry_t::live, weak_hash_entry_t::next, and weak_hash_entry_t::value.
Referenced by weak_key_entry_create().
{
  weak_hash_entry_t* e = GC_NEW(weak_hash_entry_t);
  e->key = key;
  e->value = value;
  e->next = next;
  e->live = 1;
  return e;
}
static weak_hash_entry_t* weak_key_entry_create (dfsch_object_t * key, dfsch_object_t * value, weak_hash_entry_t * next) [static]
Definition at line 311 of file weak.c.
References HIDE_OBJECT, weak_hash_entry_t::live, register_weak_pointer(), and weak_hash_entry_create().
Referenced by weak_key_hash_set().
{
  weak_hash_entry_t* e = weak_hash_entry_create(HIDE_OBJECT(key), value, next);
  register_weak_pointer(&e->live, key);
  return e;
}
static int weak_key_hash_ref (weak_key_hash_t * h, dfsch_object_t * key, dfsch_object_t ** res) [static]
Definition at line 333 of file weak.c.
References weak_key_hash_t::buckets, weak_key_hash_t::count, DFSCH_RWLOCK_RDLOCK, DFSCH_RWLOCK_UNLOCK, find_entry(), HIDE_OBJECT, weak_key_hash_t::lock, weak_key_hash_t::mask, ptr_hash(), and weak_hash_entry_t::value.
{
  weak_hash_entry_t* e;
  uint32_t hash = ptr_hash(key);
  /*
   * There is no need to perform any special locking regarding GC,
   * worst possible outcome of race condition with GC here is returning
   * value that should be instead discarded, but this is still perfectly
   * valid value. It is reasonable to expect that user code can cope with
   * this in some meaningful manner (with doing nothing being pretty
   * reasonable).
   */
  DFSCH_RWLOCK_RDLOCK(h->lock);
  e = find_entry(&h->buckets[hash & h->mask], HIDE_OBJECT(key), &h->count);
  if (!e){
    DFSCH_RWLOCK_UNLOCK(h->lock);
    return 0;
  }
  *res = e->value;
  DFSCH_RWLOCK_UNLOCK(h->lock);
  return 1;
}
static void weak_key_hash_set (weak_key_hash_t * h, dfsch_object_t * key, dfsch_object_t * value) [static]
Definition at line 361 of file weak.c.
References weak_key_hash_t::buckets, weak_key_hash_t::count, DFSCH_RWLOCK_UNLOCK, DFSCH_RWLOCK_WRLOCK, find_entry(), HIDE_OBJECT, weak_key_hash_t::lock, weak_key_hash_t::mask, ptr_hash(), weak_hash_entry_t::value, and weak_key_entry_create().
{
  uint32_t hash = ptr_hash(key);
  weak_hash_entry_t* e;
  DFSCH_RWLOCK_WRLOCK(h->lock);
  e = find_entry(&h->buckets[hash & h->mask], HIDE_OBJECT(key), &h->count);
  if (e){
    e->value = value;
  }else{
    h->count++;
    h->buckets[hash & h->mask] =
      weak_key_entry_create(key,
                            value,
                            h->buckets[hash & h->mask]);
  }
  DFSCH_RWLOCK_UNLOCK(h->lock);
}
Variable Documentation
dfsch_custom_hash_type_t dfsch_weak_key_hash_type
Initial value:
 {
  {
    DFSCH_CUSTOM_HASH_TYPE_TYPE,
    DFSCH_HASH_BASETYPE,
    sizeof(weak_key_hash_t),
    "weak-key-hash",
    NULL,
    NULL,
    NULL,
    NULL
  },
  (dfsch_custom_hash_ref_t)weak_key_hash_ref,
  (dfsch_custom_hash_set_t)weak_key_hash_set,
}
Definition at line 384 of file weak.c.
dfsch_type_t dfsch_weak_reference_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(reference_t),
  "weak-reference",
  NULL,
  NULL,
  NULL
}
Definition at line 44 of file weak.c.
dfsch_type_t dfsch_weak_vector_type
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  NULL,
  sizeof(weak_vector_t),
  "weak-vector",
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 111 of file weak.c.