dfsch: dfsch/wrapper.h File Reference
dfsch/wrapper.h File Reference
#include <dfsch/dfsch.h>
Functions
dfsch_object_t * dfsch_make_wrapper_type (char *name, dfsch_object_t *write, dfsch_object_t *equal_p, dfsch_object_t *apply, dfsch_object_t *hash)
dfsch_object_t * dfsch_unwrap (dfsch_object_t *type, dfsch_object_t *wrapper)
dfsch_object_t * dfsch_wrap (dfsch_object_t *type, dfsch_object_t *object)
Function Documentation
dfsch_object_t* dfsch_make_wrapper_type (char * name, dfsch_object_t * write, dfsch_object_t * equal_p, dfsch_object_t * apply, dfsch_object_t * hash)
Definition at line 100 of file wrapper.c.
References wrapper_type_t::apply, dfsch_type_t::apply, dfsch_make_object(), wrapper_type_t::equal_p, dfsch_type_t::equal_p, wrapper_type_t::hash, dfsch_type_t::hash, dfsch_type_t::name, dfsch_type_t::size, dfsch_type_t::superclass, wrapper_type_t::type, wrapper_apply(), wrapper_equal_p(), wrapper_hash(), wrapper_write(), wrapper_type_t::write, and dfsch_type_t::write.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_make_wrapper_type().
{
  wrapper_type_t* t = (wrapper_type_t*)
    dfsch_make_object((dfsch_type_t*)&wrapper_type);
  t->type.name = name;
  t->type.size = sizeof(wrapper_t);
  t->type.superclass = &wrapper_basetype;
  if (write){
    t->type.write = wrapper_write;
    t->write = write;
  }else{
    t->type.write = NULL;
  }
  if (equal_p){
    t->type.equal_p = wrapper_equal_p;
    t->equal_p = equal_p;
  }else{
    t->type.equal_p = NULL;
  }
  if (apply){
    t->type.apply = wrapper_apply;
    t->apply = apply;
  }else{
    t->type.apply = NULL;
  }
  if (hash){
    t->type.hash = wrapper_hash;
    t->hash = hash;
  }else{
    t->type.hash = NULL;
  }
  return (dfsch_object_t*)t;
}
dfsch_object_t* dfsch_unwrap (dfsch_object_t * type, dfsch_object_t * wrapper)
Definition at line 159 of file wrapper.c.
References dfsch_error(), DFSCH_TYPE_OF, and wrapper_t::object.
Referenced by native_unwrap().
{
  wrapper_t* w;
  wrapper_type_t* t;
  if (DFSCH_TYPE_OF(type) != &wrapper_type)
    dfsch_error("exception:not-a-wrapper-type", type);
  t = (wrapper_type_t*)type;
  if (DFSCH_TYPE_OF(wrapper) != (dfsch_type_t*)t)
    dfsch_error("exception:type-mismatch", type);
  w = (wrapper_t*)wrapper;
  return w->object;
}
dfsch_object_t* dfsch_wrap (dfsch_object_t * type, dfsch_object_t * object)
Definition at line 144 of file wrapper.c.
References dfsch_error(), dfsch_make_object(), DFSCH_TYPE_OF, and wrapper_t::object.
Referenced by native_wrap().
{
  wrapper_t* w;
  wrapper_type_t* t;
  if (DFSCH_TYPE_OF(type) != &wrapper_type)
    dfsch_error("exception:not-a-wrapper-type", type);
  t = (wrapper_type_t*)type;
  w = (wrapper_t*)dfsch_make_object((dfsch_type_t*)t);
  w->object = object;
  return (dfsch_object_t*)w;
}