dfsch: src/wrapper.c File Reference
src/wrapper.c File Reference
#include "dfsch/wrapper.h"
#include <dfsch/strings.h>
#include "util.h"
Data Structures
struct wrapper_t
struct wrapper_type_t
Functions
void dfsch__wrapper_native_register (dfsch_object_t *ctx)
DFSCH_DEFINE_FORM_IMPL (define_wrapper_type, NULL)
dfsch_object_t * dfsch_make_wrapper_type (char *name, dfsch_object_t *write, dfsch_object_t *equal_p, dfsch_object_t *apply, dfsch_object_t *hash)
dfsch_object_t * dfsch_unwrap (dfsch_object_t *type, dfsch_object_t *wrapper)
dfsch_object_t * dfsch_wrap (dfsch_object_t *type, dfsch_object_t *object)
static dfsch_object_t * native_make_wrapper_type (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_unwrap (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * native_wrap (void *baton, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static dfsch_object_t * wrapper_apply (dfsch_object_t *obj, dfsch_object_t *args, dfsch_tail_escape_t *esc)
static int wrapper_equal_p (dfsch_object_t *a, dfsch_object_t *b)
static size_t wrapper_hash (dfsch_object_t *obj)
static void wrapper_write (dfsch_object_t *obj, dfsch_writer_state_t *state)
Variables
static const dfsch_type_t wrapper_basetype
static const dfsch_type_t wrapper_type
Function Documentation
void dfsch__wrapper_native_register (dfsch_object_t * ctx)
Definition at line 244 of file wrapper.c.
References dfsch_define_cstr(), DFSCH_FORM_REF, dfsch_make_primitive(), native_make_wrapper_type(), native_unwrap(), and native_wrap().
Referenced by dfsch__native_register().
{
  dfsch_define_cstr(ctx, "<wrapper-type>", &wrapper_type);
  dfsch_define_cstr(ctx, "define-wrapper-type",
                    DFSCH_FORM_REF(define_wrapper_type));
  dfsch_define_cstr(ctx, "make-wrapper-type",
                   dfsch_make_primitive(&native_make_wrapper_type, NULL));
  dfsch_define_cstr(ctx, "wrap",
                   dfsch_make_primitive(&native_wrap, NULL));
  dfsch_define_cstr(ctx, "unwrap",
                   dfsch_make_primitive(&native_unwrap, NULL));
}
DFSCH_DEFINE_FORM_IMPL (define_wrapper_type , NULL)
Definition at line 175 of file wrapper.c.
References dfsch_define(), dfsch_eval_list(), DFSCH_KEYWORD, DFSCH_KEYWORD_PARSER_BEGIN, DFSCH_KEYWORD_PARSER_END, dfsch_make_wrapper_type(), DFSCH_OBJECT_ARG, and dfsch_symbol_2_typename().
{
  dfsch_object_t* write = NULL;
  dfsch_object_t* equal_p = NULL;
  dfsch_object_t* apply = NULL;
  dfsch_object_t* hash = NULL;
  dfsch_object_t* name;
  dfsch_object_t* type;
  char* typename;
  DFSCH_OBJECT_ARG(args, name);
  args = dfsch_eval_list(args, env);
  DFSCH_KEYWORD_PARSER_BEGIN(args);
  DFSCH_KEYWORD("write", write);
  DFSCH_KEYWORD("equal?", equal_p);
  DFSCH_KEYWORD("apply", apply);
  DFSCH_KEYWORD("hash", hash);
  DFSCH_KEYWORD_PARSER_END(args);
  type = dfsch_make_wrapper_type(dfsch_symbol_2_typename(name),
                                 write, equal_p, apply, hash);
  dfsch_define(name, type, env);
  return type;
}
dfsch_object_t* dfsch_make_wrapper_type (char * name, dfsch_object_t * write, dfsch_object_t * equal_p, dfsch_object_t * apply, dfsch_object_t * hash)
Definition at line 100 of file wrapper.c.
References wrapper_type_t::apply, dfsch_type_t::apply, dfsch_make_object(), wrapper_type_t::equal_p, dfsch_type_t::equal_p, wrapper_type_t::hash, dfsch_type_t::hash, dfsch_type_t::name, dfsch_type_t::size, dfsch_type_t::superclass, wrapper_type_t::type, wrapper_apply(), wrapper_equal_p(), wrapper_hash(), wrapper_write(), wrapper_type_t::write, and dfsch_type_t::write.
Referenced by DFSCH_DEFINE_FORM_IMPL(), and native_make_wrapper_type().
{
  wrapper_type_t* t = (wrapper_type_t*)
    dfsch_make_object((dfsch_type_t*)&wrapper_type);
  t->type.name = name;
  t->type.size = sizeof(wrapper_t);
  t->type.superclass = &wrapper_basetype;
  if (write){
    t->type.write = wrapper_write;
    t->write = write;
  }else{
    t->type.write = NULL;
  }
  if (equal_p){
    t->type.equal_p = wrapper_equal_p;
    t->equal_p = equal_p;
  }else{
    t->type.equal_p = NULL;
  }
  if (apply){
    t->type.apply = wrapper_apply;
    t->apply = apply;
  }else{
    t->type.apply = NULL;
  }
  if (hash){
    t->type.hash = wrapper_hash;
    t->hash = hash;
  }else{
    t->type.hash = NULL;
  }
  return (dfsch_object_t*)t;
}
dfsch_object_t* dfsch_unwrap (dfsch_object_t * type, dfsch_object_t * wrapper)
Definition at line 159 of file wrapper.c.
References dfsch_error(), DFSCH_TYPE_OF, and wrapper_t::object.
Referenced by native_unwrap().
{
  wrapper_t* w;
  wrapper_type_t* t;
  if (DFSCH_TYPE_OF(type) != &wrapper_type)
    dfsch_error("exception:not-a-wrapper-type", type);
  t = (wrapper_type_t*)type;
  if (DFSCH_TYPE_OF(wrapper) != (dfsch_type_t*)t)
    dfsch_error("exception:type-mismatch", type);
  w = (wrapper_t*)wrapper;
  return w->object;
}
dfsch_object_t* dfsch_wrap (dfsch_object_t * type, dfsch_object_t * object)
Definition at line 144 of file wrapper.c.
References dfsch_error(), dfsch_make_object(), DFSCH_TYPE_OF, and wrapper_t::object.
Referenced by native_wrap().
{
  wrapper_t* w;
  wrapper_type_t* t;
  if (DFSCH_TYPE_OF(type) != &wrapper_type)
    dfsch_error("exception:not-a-wrapper-type", type);
  t = (wrapper_type_t*)type;
  w = (wrapper_t*)dfsch_make_object((dfsch_type_t*)t);
  w->object = object;
  return (dfsch_object_t*)w;
}
static dfsch_object_t* native_make_wrapper_type (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 201 of file wrapper.c.
References DFSCH_KEYWORD, DFSCH_KEYWORD_PARSER_BEGIN, DFSCH_KEYWORD_PARSER_END, dfsch_make_wrapper_type(), and DFSCH_STRING_ARG.
Referenced by dfsch__wrapper_native_register().
{
  dfsch_object_t* write = NULL;
  dfsch_object_t* equal_p = NULL;
  dfsch_object_t* apply = NULL;
  dfsch_object_t* hash = NULL;
  char* name;
  DFSCH_STRING_ARG(args, name);
  DFSCH_KEYWORD_PARSER_BEGIN(args);
  DFSCH_KEYWORD("write", write);
  DFSCH_KEYWORD("equal?", equal_p);
  DFSCH_KEYWORD("apply", apply);
  DFSCH_KEYWORD("hash", hash);
  DFSCH_KEYWORD_PARSER_END(args);
  return dfsch_make_wrapper_type(name, write, equal_p, apply, hash);
}
static dfsch_object_t* native_unwrap (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 232 of file wrapper.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG_OPT, and dfsch_unwrap().
Referenced by dfsch__wrapper_native_register().
{
  dfsch_object_t* type;
  dfsch_object_t* wrapper;
  DFSCH_OBJECT_ARG_OPT(args, type, NULL);
  DFSCH_OBJECT_ARG_OPT(args, wrapper, NULL);
  DFSCH_ARG_END(args);
  return dfsch_unwrap(type, wrapper);
}
static dfsch_object_t* native_wrap (void * baton, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 221 of file wrapper.c.
References DFSCH_ARG_END, DFSCH_OBJECT_ARG_OPT, and dfsch_wrap().
Referenced by dfsch__wrapper_native_register().
{
  dfsch_object_t* type;
  dfsch_object_t* object;
  DFSCH_OBJECT_ARG_OPT(args, type, NULL);
  DFSCH_OBJECT_ARG_OPT(args, object, NULL);
  DFSCH_ARG_END(args);
  return dfsch_wrap(type, object);
}
static dfsch_object_t* wrapper_apply (dfsch_object_t * obj, dfsch_object_t * args, dfsch_tail_escape_t * esc) [static]
Definition at line 59 of file wrapper.c.
References wrapper_type_t::apply, dfsch_apply_tr(), dfsch_list(), and dfsch_object_t::type.
Referenced by dfsch_make_wrapper_type().
{
  wrapper_type_t* type = (wrapper_type_t*) obj->type;
  return dfsch_apply_tr(type->apply,
                        dfsch_list(2, obj, args),
                        esc);
}
static int wrapper_equal_p (dfsch_object_t * a, dfsch_object_t * b) [static]
Definition at line 51 of file wrapper.c.
References dfsch_apply(), dfsch_list(), wrapper_type_t::equal_p, and dfsch_object_t::type.
Referenced by dfsch_make_wrapper_type().
{
  wrapper_type_t* type = (wrapper_type_t*) a->type;
  return (dfsch_apply(type->equal_p,
                      dfsch_list(2, a, b))) != NULL;
}
static size_t wrapper_hash (dfsch_object_t * obj) [static]
Definition at line 68 of file wrapper.c.
References dfsch_apply(), dfsch_list(), dfsch_make_number_from_long(), wrapper_type_t::hash, and dfsch_object_t::type.
Referenced by dfsch_make_wrapper_type().
{
  wrapper_type_t* type = (wrapper_type_t*) obj->type;
  return
    dfsch_make_number_from_long(dfsch_apply(type->hash,
                                            dfsch_list(1,
                                                       obj)));
}
static void wrapper_write (dfsch_object_t * obj, dfsch_writer_state_t * state) [static]
Definition at line 41 of file wrapper.c.
References dfsch_apply(), dfsch_list(), dfsch_string_to_cstr(), dfsch_object_t::type, and wrapper_type_t::write.
Referenced by dfsch_make_wrapper_type().
{
  wrapper_type_t* type = (wrapper_type_t*) obj->type;
  return
    dfsch_string_to_cstr(dfsch_apply(type->write,
                                     dfsch_list(2,
                                                obj,
                                                state)));
}
Variable Documentation
const dfsch_type_t wrapper_basetype [static]
Initial value:
 {
  DFSCH_ABSTRACT_TYPE,
  NULL,
  0,
  "wraped-object",
  NULL,
  NULL,
  NULL,
  NULL
}
Definition at line 77 of file wrapper.c.
const dfsch_type_t wrapper_type [static]
Initial value:
 {
  DFSCH_STANDARD_TYPE,
  DFSCH_STANDARD_TYPE,
  sizeof(wrapper_type_t),
  "wrapper-type",
  NULL,
  NULL,
  NULL,
}
Definition at line 89 of file wrapper.c.