dfsch: dfsch/writer.h File Reference
dfsch/writer.h File Reference
#include <dfsch/dfsch.h>
Defines
#define DFSCH_PRINT 2
#define DFSCH_STRICT_WRITE 0
#define DFSCH_WRITE 1
#define DFSCH_WRITE_CIRCULAR -1
Functions
void dfsch_invalidate_writer_state (dfsch_writer_state_t *state)
dfsch_writer_state_t * dfsch_make_writer_state (int max_depth, int readability, dfsch_output_proc_t proc, void *baton)
void dfsch_write_object (dfsch_writer_state_t *state, dfsch_object_t *object)
void dfsch_write_pprint_begin (dfsch_writer_state_t *state)
void dfsch_write_pprint_end (dfsch_writer_state_t *state)
void dfsch_write_pprint_indent (dfsch_writer_state_t *state)
void dfsch_write_pprint_newline (dfsch_writer_state_t *state)
void dfsch_write_strbuf (dfsch_writer_state_t *state, char *str, size_t len)
void dfsch_write_string (dfsch_writer_state_t *state, char *str)
void dfsch_write_unreadable (dfsch_writer_state_t *state, dfsch_object_t *obj, char *format,...)
void dfsch_write_unreadable_end (dfsch_writer_state_t *state)
void dfsch_write_unreadable_start (dfsch_writer_state_t *state, dfsch_object_t *obj)
int dfsch_writer_state_cmark_p (dfsch_writer_state_t *state)
int dfsch_writer_state_pprint_p (dfsch_writer_state_t *state)
int dfsch_writer_state_print_p (dfsch_writer_state_t *state)
Define Documentation
#define DFSCH_PRINT 2
Definition at line 14 of file writer.h.
Referenced by dfsch_object_2_string(), and dfsch_writer_state_print_p().
#define DFSCH_STRICT_WRITE 0
Definition at line 12 of file writer.h.
Referenced by dfsch_write_unreadable_start().
#define DFSCH_WRITE 1
Definition at line 13 of file writer.h.
Referenced by dfsch_object_2_string().
#define DFSCH_WRITE_CIRCULAR -1
Definition at line 11 of file writer.h.
Function Documentation
void dfsch_invalidate_writer_state (dfsch_writer_state_t * state)
Definition at line 62 of file writer.c.
References dfsch_writer_state_t::output_baton, and dfsch_writer_state_t::output_proc.
{
  state->output_proc = NULL;
  state->output_baton = NULL;
}
dfsch_writer_state_t* dfsch_make_writer_state (int max_depth, int readability, dfsch_output_proc_t proc, void * baton)
Definition at line 47 of file writer.c.
References dfsch_writer_state_t::c_mark, dfsch_writer_state_t::depth, dfsch_make_object(), DFSCH_WRITER_STATE_TYPE, dfsch_writer_state_t::output_baton, dfsch_writer_state_t::output_proc, and dfsch_writer_state_t::readability.
Referenced by dfsch_object_2_string().
{
  dfsch_writer_state_t* state =
    (dfsch_writer_state_t*)dfsch_make_object(DFSCH_WRITER_STATE_TYPE);
  state->output_proc = proc;
  state->output_baton = baton;
  state->depth = max_depth;
  state->readability = readability;
  state->c_mark = 0;
  return state;
}
void dfsch_write_object (dfsch_writer_state_t * state, dfsch_object_t * object)
Definition at line 76 of file writer.c.
References dfsch_writer_state_t::c_mark, dfsch_writer_state_t::depth, DFSCH_TYPE_OF, dfsch_write_string(), dfsch_write_unreadable(), dfsch_type_t::superclass, and dfsch_type_t::write.
Referenced by condition_write(), DFSCH_DEFINE_PRIMITIVE(), dfsch_object_2_string(), function_write(), pair_write(), print_lambda_list(), and vector_write().
{
  dfsch_type_t* type;
  char* ret;
  if (state->c_mark){
    // TODO
  } else {
    if (!object){
      dfsch_write_string(state, "()");
      return;
    }
    if (state->depth==0){
      dfsch_write_string(state, "...");
      return;
    }
    type = DFSCH_TYPE_OF(object);
  }
  while (type){
    if (type->write){
      state->depth--;
      type->write(object, state);
      state->depth++;
      return;
    }
    type = type->superclass;
  }
  if (!state->c_mark){
    dfsch_write_unreadable(state, object, "");
  }
}
void dfsch_write_pprint_begin (dfsch_writer_state_t * state)
Definition at line 158 of file writer.c.
{
}
void dfsch_write_pprint_end (dfsch_writer_state_t * state)
Definition at line 161 of file writer.c.
{
}
void dfsch_write_pprint_indent (dfsch_writer_state_t * state)
Definition at line 155 of file writer.c.
{
}
void dfsch_write_pprint_newline (dfsch_writer_state_t * state)
Definition at line 152 of file writer.c.
{
}
void dfsch_write_strbuf (dfsch_writer_state_t * state, char * str, size_t len)
Definition at line 117 of file writer.c.
References dfsch_writer_state_t::c_mark, dfsch_error(), dfsch_writer_state_t::output_baton, and dfsch_writer_state_t::output_proc.
Referenced by DFSCH_DEFINE_PRIMITIVE(), and dfsch_write_string().
{
  if (state->c_mark){
    return;
  }
  if (state->output_proc){
    state->output_proc(state->output_baton, str, len);
  } else {
    dfsch_error("Stale writer-state", state);
  }
}
void dfsch_write_string (dfsch_writer_state_t * state, char * str)
Definition at line 113 of file writer.c.
References dfsch_write_strbuf().
Referenced by bignum_write(), condition_write(), dfsch_write_object(), dfsch_write_unreadable(), dfsch_write_unreadable_end(), dfsch_write_unreadable_start(), fixnum_write(), flonum_write(), fracnum_write(), function_write(), pair_write(), print_lambda_list(), string_write(), symbol_write(), and vector_write().
{
  dfsch_write_strbuf(state, str, strlen(str));
}
void dfsch_write_unreadable (dfsch_writer_state_t * state, dfsch_object_t * obj, char * format, ...)
Definition at line 129 of file writer.c.
References dfsch_write_string(), dfsch_write_unreadable_end(), dfsch_write_unreadable_start(), sl_create, and vsaprintf.
Referenced by decoded_time_write(), dfsch_write_object(), file_port_write(), primitive_write(), process_port_write(), slot_write(), stat_write(), symbol_write(), and type_write().
{
  str_list_t* sl = sl_create();
  va_list args;
  char *ret;
  va_start(args, format);
  dfsch_write_unreadable_start(state, obj);
  dfsch_write_string(state, vsaprintf(format, args));
  dfsch_write_unreadable_end(state);
}
void dfsch_write_unreadable_end (dfsch_writer_state_t * state)
Definition at line 148 of file writer.c.
References dfsch_write_string().
Referenced by condition_write(), dfsch_write_unreadable(), function_write(), and lambda_list_write().
{
  dfsch_write_string(state, ">");
}
void dfsch_write_unreadable_start (dfsch_writer_state_t * state, dfsch_object_t * obj)
Definition at line 140 of file writer.c.
References dfsch_error(), DFSCH_STRICT_WRITE, DFSCH_TYPE_OF, dfsch_write_string(), dfsch_writer_state_t::readability, and saprintf.
Referenced by condition_write(), dfsch_write_unreadable(), function_write(), and lambda_list_write().
{
  if (state->readability == DFSCH_STRICT_WRITE){
    dfsch_error("Object has no readable representation", obj);
  }
  dfsch_write_string(state,
                     saprintf("#<%s %p ", DFSCH_TYPE_OF(obj)->name, obj));
}
int dfsch_writer_state_cmark_p (dfsch_writer_state_t * state)
Definition at line 72 of file writer.c.
References dfsch_writer_state_t::c_mark.
{
  return state->c_mark;
}
int dfsch_writer_state_pprint_p (dfsch_writer_state_t * state)
Definition at line 69 of file writer.c.
{
  return 0;
}
int dfsch_writer_state_print_p (dfsch_writer_state_t * state)
Definition at line 66 of file writer.c.
References DFSCH_PRINT, and dfsch_writer_state_t::readability.
Referenced by string_write().
{
  return state->readability == DFSCH_PRINT;
}